### ISSUE TITLE
[Feature] Слайды динамической высоты в Gallery

### ISSUE THREAD

**Issue by Artur-Frank** [VKCOM/VKUI#1002]
Если компоненту Gallery назначить height: auto ( Нужно если контент разной высоты ) То на  mvk через хром была замечена проблема ( после перелистывания часть предыдущего слайда видна по краю хоть ширина установлена на 100% ).

**Шаги воспроизведения**
Разместить 2 слайда разной высоты ( иногда срабатывает и с одинаковой ) и установить :
```
.Gallery { height: auto !important }
```

либо из кода :
```
style={{ height: 'auto' }}
```

**Ожидаемое поведение**
Анимация слайда доводится до конца

**Скриншоты**
![image](https://user-images.githubusercontent.com/53945036/92699762-ab9ab000-f356-11ea-8bae-c0f143bb2837.png)
![image](https://user-images.githubusercontent.com/53945036/92699876-c705bb00-f356-11ea-9038-7f0c69f91910.png)
  

На скриншотах на Gallery не воздействует ничего. производился скрол и анимация скрола останавливается на этих этапах. Если проскролить страницу вниз то 50/50 активная страница встает на свое правильное положение.

Исправил эту проблему убрав полосу прокрутки во всем приложении :
```
html::-webkit-scrollbar {
    display: none;
}
```

**Comment by Artur-Frank** [comment]
Если поставить фиксированную высоту Gallery... к примеру height: 800px... то все начинает работать нормально.

**Comment by Artur-Frank** [comment]
Проблема отладчика в Хроме, все работает нормально без отладки.

**Comment by ArthurStam** [comment]
Привет. Нужен живой пример. Без него непонятно что происходит. Форкнуться можно отсюда: https://codesandbox.io/s/vkui-boilerplate-oj149

**Comment by thoughtspile** [comment]
Пример: https://codesandbox.io/s/vkui-gallery-auto-height-xm0tb?file=/src/index.js

Не баг: галерея не рассчитана на слайды динамической высоты. Технически это проблематично сделать и таких галерей я не видал.

Возможно, @wayshev пояснит, правильно ли так использовать галерею?

**Comment by ArthurStam** [comment]
Обсудили с Ваней. Так использовать галерею не стоит. У слайдов должна быть одинаковая высота. Ширина может быть разной.
