### ISSUE TITLE
Пропсы Textarea не поддерживаются

### ISSUE THREAD

**Issue by drfisher** [VKCOM/VKUI#1011]
Пропсы, [указанные в документации](https://vkcom.github.io/vkui-styleguide/#textarea) (top, bottom и т.п.), никак не поддерживаются в коде

https://github.com/VKCOM/VKUI/blob/d81fd1f62cc84011e5c111c98d9fb6bc0ca79d21/src/components/Textarea/Textarea.tsx#L122

**Comment by ArthurStam** [comment]
Привет. Мы не самым удачным образом реализовали апи для отрисовки top и bottom. В ближайшее время выкатим апдейт с новой логикой в v4. Этот тикет закрываю, потому что он дублирует #858. Можешь подписаться на тот, чтобы быть в курсе прогресса.
