### ISSUE TITLE
[Bug] Некорректная работа пропа bottom в компоненте Input

### ISSUE THREAD

**Issue by velialiev** [VKCOM/VKUI#1012]
**Описание**
Проп bottom на Input работает только в том случае, если Input является непосредственным ребенком FormLayout. Более того, я заметил даже такую интересную особенность, что мой кастомный компонент умеет рендерить проп bottom, что явно говорит о том, что логика этого пропа реализована на уровне FormLayout и никак не связана с тем компонентом, в который этот проп непосредственно передается.

**Шаги воспроизведения**
1. Создать компонент и отрендерить в нем Input
2. Отрендерить созданный компонент в FormLayout
3. Установить в проп bottom компонента Input любое значение
4. Посмотреть, отрендерился ли bottom (не отрендерится)
5. Удалить проп bottom из Input и передать его в созданный нами компонент
6. Посмотреть, отрендерился ли проп bottom (на этом этапе он отрендерится корректно)

**Ожидаемое поведение**
Проп bottom должен работать на уровне компонента Input и рендерить именно то, что передано в проп bottom конкретного Input. Кастомные компоненты не должны уметь показывать bottom только потому, что они отрендерены в FormLayout

Этот баг делает невозможным создание обертки над Input компонентом (в моем случае обертка нужна для работы с Formik через useField)

Вот такой компонент не отрендерит bottom никогда (специально передавал туда значения без условий и они не отрендерились):

![изображение](https://user-images.githubusercontent.com/55160134/93019626-d4ce7100-f5e0-11ea-9d16-13b07ecf7ee4.png)

**Comment by ArthurStam** [comment]
Привет. Мы не самым удачным образом реализовали апи для отрисовки top и bottom. В ближайшее время выкатим апдейт с новой логикой в v4. Этот тикет закрываю, потому что он дублирует #858. Можешь подписаться на тот, чтобы быть в курсе прогресса.
