### ISSUE TITLE
[Bug] Некорректное отображение хедера при наличии динамического контента на странице

### ISSUE THREAD

**Issue by velialiev** [VKCOM/VKUI#1013]
**Описание**:
Хедер прыгает, если проскроллить исчезающий после закрытия страницы контент под ним, перейти на другую страницу и затем вернуться обратно

Баг очень специфический, поэтому прикладываю видео: https://youtu.be/81pmGYqmz-Q

**Шаги воспроизведения**
1. Открыть Panel с данными, которые подгружаются динамически (допустим, с сервера). Данных должно быть достаточно, чтобы появился скролл
2. Проскролить вниз
2. Перейти с этой Panel на другую
3. Перейти обратно через кнопку "Назад"
4. Смотреть на надпись в хедере, она будет прыгать по экрану

**Ожидаемое поведение**
Хедер должен вести себя корректно и не прыгать вниз

**Comment by ArthurStam** [comment]
Привет. Это ожидаемое поведение. Мы запоминаем состояние скролла и при возврате ожидаем, что контент будет ровно тот, что был при переходе вперед. Нужно кэшировать данные панели, чтобы при повторном рендере отрисовывать эти данные без запроса. Тогда скачка шапки не будет

**Comment by veli-aliev** [comment]
Привет, может как-то можно прикрепить этот хедер к верху экрана независимо от этого? Каким-нибудь position: fixed, он же от скролла никак не зависит. Я так и не смог посмотреть, из-за каких стилей это происходит, потому что баг секундный.

Я не уверен, что рассчитывать на то, что все данные с панели будут кешироваться - это хорошая идея. Я возвращаю пользователя обратно на эту панель после того, как он прошел 4-5 панелей, на которых он заполнял формы. Сфетчиваю данные заново я для того, чтобы показать сущность, созданную пользователем в процессе заполнения этих форм. 

Я могу добавить эту сущность в список вручную, но что если за это время кто-то другой создаст такую же сущность? Данные станут неконсистентными. Разве я могу кешировать эти данные с учетом того, что у меня нет сокета и динамически эти данные я не обновляю? Пользователем будет ожидаться, что если он перезашел на страницу, то данные на ней должны быть актуальными

**Comment by velialiev** [comment]
Привет, может как-то можно прикрепить этот хедер к верху экрана независимо от этого? Каким-нибудь position: fixed, он же от скролла никак не зависит. Я так и не смог посмотреть, из-за каких стилей это происходит, потому что баг секундный.

Я не уверен, что рассчитывать на то, что все данные с панели будут кешироваться - это хорошая идея. Я возвращаю пользователя обратно на эту панель после того, как он прошел 4-5 панелей, на которых он заполнял формы. Сфетчиваю данные заново я для того, чтобы показать сущность, созданную пользователем в процессе заполнения этих форм.

Я могу добавить эту сущность в список вручную, но что если за это время кто-то другой создаст такую же сущность? Данные станут неконсистентными. Разве я могу кешировать эти данные с учетом того, что у меня нет сокета и динамически эти данные я не обновляю? Пользователем будет ожидаться, что если он перезашел на страницу, то данные на ней должны быть актуальными

**Comment by velialiev** [comment]
Я уже даже не столько ожидаю фикса бага, сколько мне интересно, какого паттерна в этой ситуации придерживаются разработчики ВК и как обрабатывают эту проблему. В вашем мобильном клиенте есть вебсокет. Если бы его там не было, как бы вы решали это? В какой момент вы бы обновляли кеш?

**Comment by ArthurStam** [comment]
За мобильные клиенты не отвечу. В наших VKUI-приложениях мы сбрасываем кэш как только происходит переход с панели назад.

**Comment by velialiev** [comment]
Если в VKUI-приложении перейти назад со страницы, на которой был динамический контент и которая была проскроллена вниз, а потом перейти обратно вперед на нее, то бага с хедером не будет? Если нет, то можно закрывать issue, я просто не знал принципов разраотки VKUI-приложений) 

Было бы круто, если бы хедер не дергало никогда, даже если разработчик пишет своеобразно, но если это нельзя сделать, то ок

**Comment by ArthurStam** [comment]
Если коротко — хедер будет дергать при переходе назад, если высота содержимого панели изменилась.
