### ISSUE TITLE
[Bug] Разные цвета placeholder у Input и Select

### ISSUE THREAD

**Issue by velialiev** [VKCOM/VKUI#1014]
**Описание**
Input и Select имеют разные цвета placeholder

**Ожидаемое поведение**
Цвета плейсхолдера у всех видов инпута должны быть одинаковыми

**Скриншоты**
<img width="418" alt="изображение" src="https://user-images.githubusercontent.com/55160134/93031025-3e29a080-f630-11ea-9eec-3b6fff10ab2c.png">

**Comment by ArthurStam** [comment]
Спасибо, поправим

**Comment by ArthurStam** [comment]
Поправлено в v4
