### ISSUE TITLE
[Bug] ModalPage. TypeError: target.closest is not a function

### ISSUE THREAD

**Issue by velialiev** [VKCOM/VKUI#1024]
**Описание**
Возникает ошибка TypeError: target.closest is not a function при скрытии ModalPage свайпом вниз

**Шаги воспроизведения**
1 Добавить ModalPage на страницу и открыть ее
2 Нажать курсором на хедер модалки
3 Тянуть вниз

**Видео**
https://youtu.be/JFgT6EqtU_A

**Comment by ArthurStam** [comment]
Привет. Нужен сниппет с кодом. А лучше — живой пример с воспроизведением вот тут https://codesandbox.io/s/vkui-boilerplate-oj149

**Comment by ArthurStam** [comment]
Закрываю тикет из-за отсутствия активности.
