### ISSUE TITLE
[Bug] Некорректная работа скроллов в модальном окне при псевдоклассе dynamicContentHeight

### ISSUE THREAD

**Issue by MyTowerSky** [VKCOM/VKUI#1025]
**Описание**
Скроллы в длинных модальных окнах у которых установлен dynamicContentHeight работают некорректно. С пк версии видно, что скролл бар пропадает каждые X секунд, чтобы его вызвать нужно нажать внутри окна и далее успеть быстро свайпнуть пока он снова не исчез.

**Шаги воспроизведения**
1. Создаем модальное окно и приписываем к нему dynamicContentHeight
2. Добавляем большое количество контента, чтобы окно возможно было скроллить.
3. Пытаемся скроллить окно.

**Ожидаемое поведение**
Окно скроллиться нормально, все нажатия считываются с первого раза.

**Пример с воспроизведением**
https://vk.com/doc457232519_565050721?hash=34c2ebf3e1544ab776&dl=f8a52d8e840c535106
https://vk.com/doc457232519_565051643?hash=23afee413aa0f05d47&dl=1ae3847ba474aa92fe

**Comment by gbowsky** [comment]
Привет! Воспроизвести проблему не смог, можешь пожалуйста уточнить версию VKUI?
