### ISSUE TITLE
[Bug] Некорректное поведение CardGrid

### ISSUE THREAD

**Issue by gvencadze** [VKCOM/VKUI#1026]
**Описание**
При вложении более двух элементов Card в CardGrid - ломается сетка (второй и последующие ряды получают лишний отступ и выстраиваются друг под другом, а не в ряд). В случае с size="m" в первом ряду - 2 карточки, в следующих по одной, при size="s" - 3 и 2 соответственно.

**Шаги воспроизведения**
Вложить больше двух Card("m" / "s") в CardGrid

**Ожидаемое поведение**
Сетка не ломается

**Скриншоты**
m size
![m size cards](https://user-images.githubusercontent.com/48713403/93758622-783b0980-fc11-11ea-8f1e-d8df3d6b6590.png)

s size
![s size cards](https://user-images.githubusercontent.com/48713403/93758555-593c7780-fc11-11ea-9c98-ef466afbc8f2.png)

**Пример с воспроизведением**
[m size cards](https://codesandbox.io/s/vkui-boilerplate-forked-7oysn?file=/src/index.js)
[s size cards](https://codesandbox.io/s/vkui-boilerplate-forked-ytj9f?file=/src/index.js)

**Comment by ArthurStam** [comment]
Привет. Спасибо, поправим.
