### ISSUE TITLE
[Feature] Дополнительное действие при отмене

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1029]
В компоненте `Search` нельзя прокинуть дополнительное действие на кнопку «Отмена» на iOS.
Хотелось бы поддержки, чтобы поведение соответствовало нативному аналогу.

**Comment by ArthurStam** [comment]
Привет. А в нативном аналоге есть обработчик onCancel? И опиши пожалуйста кейс, когда это пригодилось.

**Comment by eolme** [comment]
На iOS 2 кнопки:

1. Крестик внутри input, который просто очищает поле.
2. Кнопка отмена, которая отменяет само действие, т.е. убирает фокус и скрывает маску.

**Comment by ArthurStam** [comment]
У нас это всё есть)

**Comment by eolme** [comment]
Ок, тогда можно пример как я могу скрыть маску при нажатии на "отмена?")

**Comment by ArthurStam** [comment]
`onBlur = (e) => { if (e.target.value === '') console.log('скрыть маску') }` не подходит?

**Comment by eolme** [comment]
Не совсем, например, как в подкастах сделать уже не получится<img src="https://user-images.githubusercontent.com/11076888/94268869-db4cd900-ff4e-11ea-8d73-d37ba1bba238.png" width="375" />

**Comment by ArthurStam** [comment]
Не понял, что ты имеешь в виду.

**Comment by eolme** [comment]
Там непрозрачная маска на весь экран с "недавние" и "популярные"

**Comment by ArthurStam** [comment]
Всё ещё не понимаю, какую задачу у тебя не получается решить. Можешь пример накидать в sandbox?

**Comment by eolme** [comment]
В общем, вот 2 экрана накидал:

1. Фокус/нет фокуса - не имеет значения, поле пустое, список листается. Кнопка отмена дублирует кнопку назад - убирает маску.
2. Фокус/нет фокуса - не имеет значения, поле не пустое, список листается. Кнопка очистить очищает и возвращает состояние на 1 экран. Кнопка отмена дублирует кнопку назад - убирает маску.

Т.е. нельзя ориентироваться на фокус/блюр.

<img src="https://user-images.githubusercontent.com/11076888/94479395-c76ed480-01e5-11eb-9789-7a465ea06fa3.png" width="375" />

**Comment by eolme** [comment]
Веду к тому, что невозможно однозначно идентифицировать, что была нажата кнопка отмена.

**Comment by ArthurStam** [comment]
1. Почему кнопка отмена дублирует кнопку назад? Отмена должна очищает инпут и делает блюр. Назад — возвращает на предыдущий экран.

2. Ты щас про крестик или про "отменить"? Крестик возвращает к первому состоянию, отменить — помимо очистки делает расфокус и пропадает сама.

**Comment by ArthurStam** [comment]
Закрываю тикет за отсутствием активности
