### ISSUE TITLE
[Bug] Неровный Radio

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1030]
https://prnt.sc/unkysx

platform=vkcom, Браузер Opera 70.0.3728.189

**Comment by ArthurStam** [comment]
Привет. Какая OS? Зум в браузере 100%?

**Comment by gbowsky** [comment]
По шрифтам видно что это Windows (Segoe UI)

**Comment by SkyGopnik** [comment]
> Привет. Какая OS? Зум в браузере 100%?

Зум да 100%, ОСь Win 10 Pro
