### ISSUE TITLE
[Bug] SimpleCell disabled шлёт ивент в onClick

### ISSUE THREAD

**Issue by ub1x** [VKCOM/VKUI#1038]
**Описание**
Опишите проблему.
В SimpleCell при пропсе disabled отключается анимация клика, но приходит событие onClick, как по мне это нелогичное поведение

**Ожидаемое поведение**
onClick не срабатывает при пропсе disabled

**Пример с воспроизведением**
https://codesandbox.io/s/vkui-boilerplate-forked-o401w?file=/src/index.js

**Comment by ArthurStam** [comment]
Привет, спасибо, будет поправило в `4.0.0-beta.31`. Stay tuned.
