### ISSUE TITLE
[Bug] Скроллбар в CustomScrollView 

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1047]
**Описание**
Кастомный сколлбар в CustomScrollView при скролле с помощью ползунка выкидывает очень много ошибок и, соответственно не работает/лагает из-за этого.

**Скриншоты**
![image](https://user-images.githubusercontent.com/11076888/94859356-70ffd100-0445-11eb-83bc-a156446667b3.png)

**Comment by ArthurStam** [comment]
Спасибо, поправим.

**Comment by gbowsky** [comment]
Привет, попытался воспроизвести твой тикет, но не получилось. Может есть ещё какие-нибудь шаги для воспроизведения?
https://pgw6d.csb.app/
