### ISSUE TITLE
[Bug] Не собирается проект через react-scripts build

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#1057]
**Описание**
На версии ^4.0.0-beta.30 проект не собирается

На 3 всё хорошо, возможно что-то с минификацией 

**Скриншоты**
<img width="301" alt="Снимок экрана 2020-10-03 в 22 32 39" src="https://user-images.githubusercontent.com/45998835/95000306-5a35b780-05c8-11eb-90da-4bbaa04beefe.png">

**Comment by eolme** [comment]
workaround: брать из папки src

**Comment by ArthurStam** [comment]
Привет. Уточни пожалуйста номер версии react-scripts

**Comment by ilyapishchulin** [comment]
3.4.3

**Comment by ArthurStam** [comment]
Будет поправлено в `4.0.0-beta.31`
