### ISSUE TITLE
[Bug] При использовании RichCell внутри after html компонента с display: flex он дублируется в RichCell__top

### ISSUE THREAD

**Issue by danyarubtsov** [VKCOM/VKUI#1059]
**Описание**
При использовании RichCell внутри after html компонента с display: flex он дублируется в RichCell__top

**Шаги воспроизведения**
      <RichCell
        before={<Avatar size={48} src={getAvatarUrl('user_lihachyov')} />}
        text="Поездка в Лиссабон"
        caption="Вчера в 20:30"
        after={<div style={{ display: 'flex' }}>+ 1 2500 </div>}
      >
        Михаил Лихачев
      </RichCell>

**Ожидаемое поведение**
HTML Компонент  с display: flex не дублируется в RichCell__top

**Comment by ub1x** [comment]
с любым display воспроизводится, не только flex

**Comment by ArthurStam** [comment]
Привет. Баг был на стороне пакета иконок. https://github.com/VKCOM/VKUI/issues/1699#issuecomment-867709390

**Comment by ArthurStam** [comment]
My bad, плохо прочитал суть репорта.

**Comment by eugpoloz** [comment]
Похоже, что починили, на v4.28.0 не смогла воспроизвести.
