### ISSUE TITLE
[Bug] Сбрасывание значения Slider при работе с ним

### ISSUE THREAD

**Issue by antoxxxa-2** [VKCOM/VKUI#1061]
**Описание**
если тянуть слайдер,  то на границе документа получается вот такой артефакт.
в этот момент (на скриншоте 
![image](https://user-images.githubusercontent.com/1327258/95178482-27f2a880-07c8-11eb-8de6-4977ba4b0d18.png)

![image](https://user-images.githubusercontent.com/1327258/95178448-1d381380-07c8-11eb-88a6-4eda0eb690f4.png)
) e.shiftX NaN
Посмотреть все изображения
глубже не копал, условие типа
if(isNaN(e.shiftX)) {
return;
} помогает полечить

**Шаги воспроизведения**
тянуть слайдер к краю документа

**Ожидаемое поведение**
слайдер не должен прыгать в изначальное значение.

**Пример с воспроизведением**
Воспроизводится на https://vkcom.github.io/vkui-styleguide/
![Запись экрана 2020-09-23 в 13 14 53](https://user-images.githubusercontent.com/1327258/95178271-e530d080-07c7-11eb-8da3-03056313671b.gif)

**Comment by thoughtspile** [comment]
Не знаю делись линки, но исправлено #1272 в v4.0.4
