### ISSUE TITLE
[Bug] Обводка Banner заходит на FixedLayout (PanelHeaderContext)

### ISSUE THREAD

**Issue by gbowsky** [VKCOM/VKUI#1062]
**Описание, скриншоты**
* Наблюдаю конфликт z-index у компонента PanelHeaderContext с Banner.
 ![image](https://user-images.githubusercontent.com/36237725/95330905-e0e0e200-08b1-11eb-82ac-e4083ff7a859.png)

**Шаги воспроизведения**
* Добавить в панель PanelHeaderContext и Banner;
* Открыть PanelHeaderContext, и будет видно что рамка баннера парит над фоном PanelHeaderContext;

**Пример с воспроизведением**
* https://8wutg.csb.app/ - пример в sandbox, проблема воспроизвелась при UA Android и iOS

**Прочие сведения**
* Microsoft Edge | 85.0.564.68 (Official build) (64-bit)
* Windows 10 OS Version 2004 (Build 20226.1000)
* VKUI: 3.12.6 **(Актуально в v4.0.0-beta.30)**

**Comment by 21alexander21** [comment]
vkui@4.0.4 проблема до сих пор актуально
наш кейс такой:
поверх баннера открывается дропдаун в портале, а поверх дропдауна псевдоэлемент с серой рамкой из-за z-index: 3
