### ISSUE TITLE
[Bug] PullToRefresh в веб-версии вращается вокруг одного из своих углов

### ISSUE THREAD

**Issue by Kli-1** [VKCOM/VKUI#1063]
**Описание**
В версии для vk.com спиннер в компоненте PullToRefresh крутится не так как должен, а крутится сама картинка, выходя за пределы отведенной области

**Шаги воспроизведения**
При исполнении жеста PullToRefresh в веб-версии воспроизводится данный баг

**Ожидаемое поведение**
Вращение спинера вокруг центра

**Скриншоты**
![image](https://user-images.githubusercontent.com/54179487/95336631-92374600-08b9-11eb-9621-25d796883bcc.png)

**Comment by gbowsky** [comment]
Масштабирование какое?

**Comment by Kli-1** [comment]
> Масштаб какой?

100%, изначальный. В meta viewport тоже ничего не менял

**Comment by gbowsky** [comment]
А системное масштабирование не применяется?

**Comment by Kli-1** [comment]
Нет, системное масштабирование не применял. На скриншоте наверное плохо понятно что я имел ввиду, но имелось ввиду что именно само вращение происходит как-бы не вокруг центра, а вокруг одного из углов. Т.е. появляется он как и необходимо, в центре, но само вращение сдвигает его, и после оборота он снова оказывается там где должен быть
