### ISSUE TITLE
[Feature] Нельзя передать ref в компонент Card

### ISSUE THREAD

**Issue by riledv** [VKCOM/VKUI#1067]
Предлагаю добавить возможность передавать ref в компонент Card. Из-за того, что в компонент Card нельзя передать ref, то нельзя узнать, например, размер карточки.

Обходные пути:
Даже если обернуть Card в div и установить ref этому div, все равно возникают проблемы, потому что обычно Card должен быть обернут в CardGrid.
Сейчас работает вариант с добавлением дочернего div с ref, но это выглядит ненадежно, потому что могут, например, появиться падинги у Card и тогда дочерний элемент с ref будет возвращать некорректные размеры карточки.

**Comment by riledv** [comment]
#1068

**Comment by riledv** [comment]
#1068 реализация

**Comment by fedorov-xyz** [comment]
Доступно с версии 3.12.8.
