### ISSUE TITLE
[Bug] Highlighting text in modalRoot

### ISSUE THREAD

**Issue by NoneWillSurvive** [VKCOM/VKUI#1071]
**Описание**
Внутри модальных окон (ModalRoot) не работает выделение части текста мышкой в компонентах <Input /> и <Textarea />. Хотя вне ModalRoot этой проблемы нет. 

**Шаги воспроизведения**
1. Ввод любого текста в Input который внутри ModalRoot.
2. Выделение мышкой части слова. (не работает)

**Ожидаемое поведение**
Аналогичное поведение, как вне компоенты ModalRoot

**Скриншоты**
https://prnt.sc/uy1akd

**Comment by thoughtspile** [comment]
Related to #335

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
