### ISSUE TITLE
[Bug] неправильный размер шрифта Title в Pannel Header на Android

### ISSUE THREAD

**Issue by wayshev** [VKCOM/VKUI#1073]
В доке font-size: 20 https://vkcom.github.io/vkui-styleguide/#panelheader
![Screen Shot 2020-10-13 at 17 50 11](https://user-images.githubusercontent.com/61538408/95877221-8c8ba580-0d7c-11eb-94a4-3370ad26a38b.png)

В макете font-size: 23, line-height: 28 — https://www.figma.com/file/lLXmjJhnJa4OhgZXzcNJD9/VKUI-Android-Library?node-id=48%3A4865
![Screen Shot 2020-10-13 at 17 50 20](https://user-images.githubusercontent.com/61538408/95877238-91505980-0d7c-11eb-8d2a-40e581462c7e.png)

**Comment by thoughtspile** [comment]
Исправлено в [v4.0.0-beta.34](https://vkcom.github.io/VKUI/4.0.0-beta.34/#!/PanelHeader)

<img width="390" alt="Снимок экрана 2020-12-08 в 17 19 12" src="https://user-images.githubusercontent.com/5262915/101495351-892a2a00-3979-11eb-920b-35548279ccf4.png">
