### ISSUE TITLE
[Bug] Нет возможности переопределить цвет подложки компонента Switch

### ISSUE THREAD

**Issue by daniil4** [VKCOM/VKUI#1077]
**Описание**
При изменении цвета accent, меняется основной цвет компонента Switch, но цвет подложки в активном состоянии остается светло синим

**Шаги воспроизведения**
Задать кастомный цвет --accent 

**Ожидаемое поведение**
Возможность переопределить цвет подложки через отдельный параметр, либо использование accent цвета с opacity для подложки

**Скриншоты**
![soEfPCphrUg](https://user-images.githubusercontent.com/8034203/96123015-70266f00-0f1c-11eb-9cec-212591eb108b.jpg)

**Comment by ArthurStam** [comment]
Будет поправлено в 4-й версии
