### ISSUE TITLE
[Tooltip]: разваливается вся страница 

### ISSUE THREAD

**Issue by 21alexander21** [VKCOM/VKUI#1078]
Если рендерить `Tooltip` НЕ внутри элементов с классами `FixedLayout`, `PanelHeader__in`, `Panel__in`, то страница развалится с uncaught эксепшеном: `null.getBoundingClientRect();`. 

Хотелось бы упоминания в документации о том, что компонент работает только внутри каких-то других компонентов, отлов ошибки в проде и понятный эксепшен в dev'е, либо фолбэк на `body`, чтоб ошибки не было совсем.

https://github.com/VKCOM/VKUI/blob/4d5fa128427a1cf0c97f2b9ce8612d9927989348/src/components/Tooltip/Tooltip.tsx#L54

**Comment by gbowsky** [comment]
fixed in #1460

**Comment by thoughtspile** [comment]
ну ворнинг это хорошая идея

**Comment by gbowsky** [comment]
в документации решение с примером есть, про ворнинг не дочитал))
