### ISSUE TITLE
[Tooltip]: опечатка в доке

### ISSUE THREAD

**Issue by 21alexander21** [VKCOM/VKUI#1079]
Тут речь про React-компонент, а не React-компонент

https://github.com/VKCOM/VKUI/blob/c881266f37a741747c39c8eca8018f1fce1cca61/src/components/Tooltip/Tooltip.tsx#L131

**UPD**
Должно быть не `React-компонент`, а `ReactNode`

**Comment by ArthurStam** [comment]
> Тут речь про React-компонент, а не React-компонент
Не понял

**Comment by 21alexander21** [comment]
https://github.com/VKCOM/VKUI/blob/c881266f37a741747c39c8eca8018f1fce1cca61/src/components/Tooltip/Tooltip.tsx#L135

`children` имеет тип `React.ReactNode`, этот тип включает в себя `React.ReactElement`, а jsdoc'е написано про какой-то компонент, если передать компонент, то будет ошибка, потому что этот кейс никак не обрабатывается

**Comment by ArthurStam** [comment]
Теперь понял, спасибо

**Comment by inomdzhon** [comment]
Кажется сейчас из контекста и так понятно о чём речь
