### ISSUE TITLE
[Bug] HorizontalScroll не работает внутри ModalPage

### ISSUE THREAD

**Issue by drfisher** [VKCOM/VKUI#1080]
Внутри этой функции вызывается preventDefault, что ломает нативный скрол в компоненте HorizontalScroll, если он находится внутри ModalPage

https://github.com/VKCOM/VKUI/blob/c881266f37a741747c39c8eca8018f1fce1cca61/src/components/ModalRoot/ModalRoot.tsx#L210

**Comment by thoughtspile** [comment]
Duplicate of #335
