### ISSUE TITLE
[Bug] PanelHeaderContext позволяет скроллить контент за ним

### ISSUE THREAD

**Issue by danyarubtsov** [VKCOM/VKUI#1081]
**Описание**
PanelHeaderContext позволяет скроллить контент за ним.

**Шаги воспроизведения**
Откройте компонент PanelHeaderContext, после чего скрольте любой контент ЗА ним, который визуально заблокирован за счёт затемнение

**Ожидаемое поведение**
Скролл контента за PanelHeaderContext недоступен.

**Comment by ArthurStam** [comment]
Дубликат: #291
