### ISSUE TITLE
[Bug] пустой Search имеет активный курсор в зоне "отмены", которая в свою очередь появляется при наличии текста в Search

### ISSUE THREAD

**Issue by ub1x** [VKCOM/VKUI#1082]
**Описание**
пустой Search имеет курсор в зоне "отмены", которая в свою очередь появляется при наличии текста в Search

**Шаги воспроизведения**
Просто стоит создать Search, и пока он пустой навести мышкой в зону, где появится клавиша "отмена" в случае наличия текста в компоненте

**Ожидаемое поведение**
До появления клавиши "отмена" - зона около Search неактивна, курсор не триггерится

**Скриншоты**
https://vk.com/doc155335341_573039800?hash=424136d1e535be9509&dl=136bd3a0ac34be61b8

**Comment by ArthurStam** [comment]
Будет поправлено в v4
