### ISSUE TITLE
[Bug] Не запускаются проекты с vkui v4

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1083]
Фото ошибки: https://prnt.sc/v346vy

Конфиг webpack: https://pastebin.com/kBYMi9qA
package.json: https://pastebin.com/9SvmVXUM

**Comment by maksimdegtyarev** [comment]
+1

**Comment by SkyGopnik** [comment]
Поставлю +1 за девушку из чата VKUI

**Comment by maksimdegtyarev** [comment]
На самом деле это повтор https://github.com/VKCOM/VKUI/issues/1057

**Comment by ArthurStam** [comment]
Привет. А зачем ты sass-loader'ом пытаешься загрузить обычный css?
