### ISSUE TITLE
[Bug] Export в v4

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1088]
Главный - index.ts 
Дописать export { default as ChipsSelect } from './components/ChipsSelect/ChipsSelect';

**Comment by ArthurStam** [comment]
Забыли упомянуть это в доке. `ChipsSelect` — нестабильный компонент. Его нужно импортировать так:
`import { ChipsSelect } from '@vkontakte/vkui/dist/unstable'`
Стили так же нужно импортить отдельно: `import '@vkontakte/vkui/dist/unstable.css'`

**Comment by SkyGopnik** [comment]
Вроде бы всё ок с ним), но у меня импорт автоматом сразу от компонента полный путь прописался, по этому и написал)
