### ISSUE TITLE
[Enhancement][Snackbar] Добавить возможность отображать вверху экрана

### ISSUE THREAD

**Issue by polzav** [VKCOM/VKUI#1090]
Хотелось бы иметь возможность отображать сверху экрана, а так же настраивать отступ сверху или снизу, чтобы не перекрывать важые элементы интерфейса.
![Screen (6)](https://user-images.githubusercontent.com/19476756/96975003-9c487e00-1522-11eb-9df0-3aacb08448a6.png)

**Comment by ArthurStam** [comment]
Обсуждаем с дизайном.

**Comment by ArthurStam** [comment]
Обсудили. Добавим такое расположение.

**Comment by ArthurStam** [comment]
https://www.figma.com/file/lLXmjJhnJa4OhgZXzcNJD9/VKUI-Android-Library?node-id=146%3A10

**Comment by Fliqle** [comment]
@SevereCloud, привет. Вот это нужно доделать асап. У нас там разработка зависла. Почта, облако, календарь, заметки все используют.

**Comment by levtsypanov** [comment]
Тоже писал по этому поводу.

может добавить свойство `placement` как у Tooltip и присвоить каждому расположению анимацию выезда. Было бы полезно.

Допустим placement="top-left" или placement="bottom-right".

**Comment by inomdzhon** [comment]
> Тоже писал по этому поводу.
> 
> может добавить свойство `placement` как у Tooltip и присвоить каждому расположению анимацию выезда. Было бы полезно.
> 
> Допустим placement="top-left" или placement="bottom-right".

Хорошая идея

Изучу
