### ISSUE TITLE
[Bug] Шапка некорректно себя ведёт при Swipe Back на iOS

### ISSUE THREAD

**Issue by ilyaeyoza** [VKCOM/VKUI#1092]
**Описание**
Шапка некорректно себя ведёт при Swipe Back на iOS

**Шаги воспроизведения**
Пример на сервисе - vk.com/app7614099

1. Открываем таб Информация
2. Открываем любой стиль
3. Листаем вниз
4. Делаем свайп бек

**Ожидаемое поведение**
Шапка ( PanelHeader ) должна оставаться на месте и не слетать как на видео

**Скринкасты**
Видео: https://yadi.sk/i/TaLQSe58rq-yNg

**Comment by eolme** [comment]
Фиксится с #1064

**Comment by ArthurStam** [comment]
Дубликат #1187
