### ISSUE TITLE
[Bug] Форма поиска не реагирует на клик

### ISSUE THREAD

**Issue by drfisher** [VKCOM/VKUI#1095]
**Описание**
Поле поиска не реагирует на клики в правую часть поля, не происходит фокуса на текстовое поле.

**Шаги воспроизведения**
1) Кликнуть на правый край формы поиска, в ту ее часть, где после фокусировки должна появиться кнопка "Отмена".
2) Поле никак не реагирует на клик, фокусировки не происходит.

**Ожидаемое поведение**
Поле реагирует на клик в любую свою часть. При этом курсор ставится внутрь текстового поля.

![CleanShot 2020-10-28 at 18 54 15@2x](https://user-images.githubusercontent.com/530830/97461808-23e12300-194f-11eb-8cb2-bd8dfcb261bd.png)
![CleanShot 2020-10-28 at 18 54 52@2x](https://user-images.githubusercontent.com/530830/97461817-26437d00-194f-11eb-8761-987027fdc4b6.png)

**Comment by thoughtspile** [comment]
Исправлено в [v4.0.0-beta.33](https://vkcom.github.io/VKUI/4.0.0-beta.33/#!/Search)
PR https://github.com/VKCOM/VKUI/pull/1131
Related to https://github.com/VKCOM/VKUI/issues/1082
