### ISSUE TITLE
Съезжают кнопки "Закрыть", "Меню" (iOS)

### ISSUE THREAD

**Issue by unvir** [VKCOM/VKUI#110]
Когда включен режим модема на iOS, видимо, изменяется размер окна браузера и съезжают кнопки. iPhone 6+

![vghg8eyzx3a](https://user-images.githubusercontent.com/14196542/44425715-4f10a080-a595-11e8-8853-e0a6a99e04c2.jpg)

**Comment by ArthurStam** [comment]
Будет фикс со стороны iOS клиента
