### ISSUE TITLE
[Bug] Текст в top кмпонента Select не генерируется, если он не находится внутри FormLayout

### ISSUE THREAD

**Issue by kozhevnikovans** [VKCOM/VKUI#1105]
Если добавить Select не внутрь FormLayout блок текста в top и  buttom не генерируется.
Особенно проблемно, если нужно создать отдельный компонет, который возвращает <Select>.

Пример кода с ошибкой во вложении
[tmp.txt](https://github.com/VKCOM/VKUI/files/5473406/tmp.txt)

**Comment by fedorov-xyz** [comment]
Эта проблема будет исправлена в v4: там появился новый компонент `FormItem`.

https://vkcom.github.io/VKUI/4.0.0-beta.32/#/FormItem
