### ISSUE TITLE
[Bug] [Input] У автозаполненного инпута не видно границ и скргуления

### ISSUE THREAD

**Issue by 21alexander21** [VKCOM/VKUI#1107]
**Описание**
У автозаполненного инпута не видно обводки и ее скругления.

**Шаги воспроизведения**
Отрендерить инпут и дать бразуеру подставить значения, или в девтулзах поменять background-color

**Ожидаемое поведение**
Хочется видеть автозаполненные поля, как их рисует юзерагент, при этом хочется чтобы все инпуты были в едином стиле

**Скриншоты**
Опционально.
![image](https://user-images.githubusercontent.com/12668989/97961923-f9231e80-1dd5-11eb-8afd-cdd86b868e28.png)

**Пример с воспроизведением**
-

**Comment by NekR** [comment]
Известно, спасибо. Фиксится вот в этом ПРе: #1051

**Comment by thoughtspile** [comment]
[Исправлено в v4.0.0-beta.34](https://vkcom.github.io/VKUI/4.0.0-beta.34/#!/Input), пр: https://github.com/VKCOM/VKUI/pull/1138
