### ISSUE TITLE
[Bug] [ActionSheet] На десктопе не работает со скроллом

### ISSUE THREAD

**Issue by 21alexander21** [VKCOM/VKUI#1109]
**Описание**
Если на десктопе откртыть выпадашку и проскроллить страницу/контейнер, то выпадающее меню будет стоять на месте и отрываться от элемента, на котором открылась.

**Шаги воспроизведения**
Использовать ActionSheet на странице со скроллом

**Comment by NekR** [comment]
Привет. Это же не так, там специально сделано абсолютное позиционирование для этого. В этом ПРе даже демка есть: #1106

**Comment by 21alexander21** [comment]
![Запись экрана 2020-11-05 в 11 46 23](https://user-images.githubusercontent.com/12668989/98207347-5b5a5b80-1f5d-11eb-9ce8-5ab9c8e60c8d.gif)
тестил в стайлгайдисте beta32

**Comment by NekR** [comment]
Видимо в стайлгайде и есть баг

**Comment by 21alexander21** [comment]
Причем тут стайлгайд? Если `ActionSheetDropdownDesktop` рендерится в контейнере с `position: fixed;` и его координаты никак не пересчитываются при скролле, то какое поведение ожидается?

**Comment by NekR** [comment]
Нет, ожидаемое поведение что бы ActionSheet находится в `position: absolute` контейнере для декстопа.
Если кажется, что это сейчас не так работает, то нужно предоставить изолированный пример где это воспроизводится, так у меня на данный момент воспроизводится только в стайлгайде, но не в реальных приложениях.

Так же рекомендую всё таки обратить внимание на #1106. Там есть и тест кейс, который опровергает этот баг. И много обсуждения на эту тему.

**Comment by ArthurStam** [comment]
Чтобы не скроллилось, нужно передавать `popout` в `SplitLayout`
