### ISSUE TITLE
[Bug] Фриз панели при 2х быстрых переходах назад

### ISSUE THREAD

**Issue by VictorKolb** [VKCOM/VKUI#1118]
**Описание**
Фриз панели при 2х быстрых переходах назад. Не факт, что это можно считать таким уж багом, но его нашли в отчетах в бета тестировании моего миниаппа.

**Шаги воспроизведения**
Если на андроиде перейти на 2 вложенности вглубь, а потом 2 раза нажать на системную кнопку "назад", то можно получить такую ситуацию, когда видна предыдущая панель (как если бы 1 раз нажал назад) и она не кликабельна.

**Ожидаемое поведение**
Панель не должна хотя бы фризиться.

**Скриншоты**
![photo_2020-11-06 15 22 48](https://user-images.githubusercontent.com/14196649/98365777-f594cf00-2043-11eb-968a-8a59335ee45d.jpeg)

**Пример с воспроизведением**
https://vk.com/app7031064
https://vk.com/app7558896

**Comment by ArthurStam** [comment]
Привет. Такой тикет уже есть. #177

**Comment by VictorKolb** [comment]
@ArthurStam плохо искал, my bad(
