### ISSUE TITLE
[Bug] Кривой ChipsSelect

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1119]
Пробовал импортировать из разных мест, воспроизводится стабильно, хотя в стайлгайде норм почему то)
Версия v4beta32

https://i.imgur.com/Y2hAM1w.jpg

**Comment by ArthurStam** [comment]
Возможно, у тебя нет импорта `import '@vkontakte/vkui/dist/unstable.css'`. Скоро добавим в доку, что нестабильный CSS лежит отдельно

**Comment by SkyGopnik** [comment]
Спасибо, забыл о нём.
