### ISSUE TITLE
[Bug] Инпут в компоненте Search не реагирует на нажатия с правой стороны

### ISSUE THREAD

**Issue by maksimdegtyarev** [VKCOM/VKUI#1130]
**Описание**
Инпут в компоненте Search не реагирует на нажатия с правой стороны. Только на мобильной версии.

**Шаги воспроизведения**
При пустом инпуте, если нажать на место выделенное на скриншоте, то курсор не появляется

**Ожидаемое поведение**
Опционально, если считаете, что из описания ожидаемое поведение понятно.

**Скриншоты**
https://vk.com/doc460284041_572173214?hash=67195edf70ac037590&dl=46a1f4d35c4af01530

**Comment by ArthurStam** [comment]
Дубликат #1082
