### ISSUE TITLE
[Bug] [FormItem] v4-beta32

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1132]
Используем FormItem с любым input внутри, будь-то Input от VKUI или обычный input, при клике на область FormItem включая padding/margin, фокус переходит в input, вызывает кучу проблем при использовании FormItem в собственных компонентах.

**Comment by SkyGopnik** [comment]
Думаю, что это связано с ненужной обёрткой label в FormItem.tsx

**Comment by ArthurStam** [comment]
А что за проблемы вызывает?

**Comment by SkyGopnik** [comment]
Ну вот у меня например есть кастомный FileInput с отображением файлов https://pastebin.com/KARhGAKE, удалять файлы я не могу, из за обёртки label открывается input который спрятан в кнопке, тоже превью файлов я допустим тоже из за лейбла сделать бы не смог.

**Comment by SkyGopnik** [comment]
Просто интересно для чего такой кейс понадобился, случаев как у меня конечно будут единицы, но не все поймут как исправить думаю.

**Comment by ArthurStam** [comment]
Добавим свойство `Component` в `FormItem`, чтобы можно было изменять тег рутового элемента.

**Comment by SkyGopnik** [comment]
Благодарю за понимание)
