### ISSUE TITLE
[Feature] [Alert] v4-beta32

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1134]
Убрать крестик закрытия на версии vkcom, т.к. есть кнопка Отмена + закрытие при клике за пределы, либо просто его поправить и унести в верхний правый угл без обводки, как в вк.

**Comment by ArthurStam** [comment]
Нет, этот компонент выполнен по актуальному дизайну

**Comment by SkyGopnik** [comment]
Кривой крестик это дизайн?

**Comment by ArthurStam** [comment]
Кривой крестик — это субъективная оценка. Мы разрабатываем компоненты, руководствуясь макетами из [фигмы](https://www.figma.com/file/TDK0ARSsxCXRAX8VLIFMS6/VKUI-Web-Library-%C2%B7-Beta?node-id=824%3A31324). Мы доверяем нашим дизайнерам.

**Comment by SkyGopnik** [comment]
Закрыт к сожалению файл дизайн.

**Comment by NekR** [comment]
Вообще тут проблема в том, что этот крестик только для vkcom, а он на самом деле нужен и для Android, но там не сделали.

**Comment by NekR** [comment]
Хотя не, я наврал. Интересно.

**Comment by SkyGopnik** [comment]
Тут проблема в том что он явно кривой и логика его расположения не понятна)

**Comment by eolme** [comment]
@SkyGopnik, можно скриншот? Я что-то не пойму в чем его кривость...

**Comment by SkyGopnik** [comment]
![image](https://user-images.githubusercontent.com/26293210/99315977-8fdee900-2874-11eb-894d-2f21fe9f8460.png)
А хотелось бы
![image](https://user-images.githubusercontent.com/26293210/99316070-c0bf1e00-2874-11eb-898d-085becf4acf0.png)
Может я конечно таких взглядов и не понимаю почему он именно так расположен.
