### ISSUE TITLE
[Bug][Select] Опции с одинаковыми children

### ISSUE THREAD

**Issue by 21alexander21** [VKCOM/VKUI#1137]
**Описание**
Если в `Select` передать несколько `option` с одинаковым свойством `children` то выбрать можно будет только первую. Происходит из-за того, что `children` приводится к строке, а при рендере передается в `title` элемента, далее по этому `title` происходит поиск индекса в массиве `options` и, соответственно, получается баг. Чтобы починить стиот использовать `value` опции, вместо `label`, или индекс в массиве. Тем более непонятно, зачем итеририровать массив опций еще раз, если индекс, как и объект `SelectOption` известен в момент вызова этого хэндлера https://github.com/VKCOM/VKUI/blob/v4.0.0-beta.32/src/components/CustomSelect/CustomSelect.tsx#L240

**Шаги воспроизведения**
```jsx
<Select top="Обычный Select" placeholder="Выберите пол">
  <option value="m">Мужской</option>
  <option value="m2">Мужской</option>
  <option value="f">Женский</option>
</Select>
```

**Comment by ArthurStam** [comment]
Спасибо, поправим.
