### ISSUE TITLE
[Bug][Select] В option можно передать только строку или число в children

### ISSUE THREAD

**Issue by 21alexander21** [VKCOM/VKUI#1139]
**Описание**
`Select` корректно работает только если в `option` передано число или строка. Если в children передать массив или ReactElement, то вместо текста опции будет результат `.toString()`. Такое поведение должно, как минимум, быть описано в документации и отражено в типах.

**Шаги воспроизведения**
Пример с реакт-элементом: в селекте будет "Мужской" и "[object Object]"
```jsx
<Select top="Обычный Select" placeholder="Выберите пол">
  <option value="m">Мужской</option>
  <option value="f"><>Женский</></option>
</Select>
```

Пример с массивом: в селекте будет "Мужской" и "Жен, , ский"
```jsx
<Select top="Обычный Select" placeholder="Выберите пол">
  <option value="m">Мужской</option>
  <option value="f">{'Жен'} {'ский'}</option>
</Select>
```

**Comment by ArthurStam** [comment]
Будет поправлено в следующей бете

**Comment by NekR** [comment]
Похоже что fixed, переоткройте если нет
