### ISSUE TITLE
[Bug][PanelHeader] Cъезжает PanelHeader в VK на iOS

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#1145]
**Описание**
В VKUI-4.0.0-beta.33 `PanelHeader` съезжает при открытии мини-приложения **через нативное приложение VK на iOS**.
Мета-тег из styleguide используется.
`webviewType` через `ConfigProvider` передается.

В вебе все нормально.

**Скриншоты**
<p style="display: flex;">
<img src="https://user-images.githubusercontent.com/42776347/99534924-e7f02980-29f3-11eb-86e6-1bb4d695cbac.png" height="500px">
<img src="https://user-images.githubusercontent.com/42776347/99534937-ec1c4700-29f3-11eb-86a9-6156418631a9.png" height="500px">
</p>

**Пример с воспроизведением**
https://vkcom.github.io/VKUI/4.0.0-beta.33/#panelheadercontent

**Comment by ArthurStam** [comment]
Не смог воспроизвести. Нужен пример с воспроизведением. Форк можно сделать отсюда.
https://codesandbox.io/s/vkui-boilerplate-oj149

**Comment by MrZillaGold** [comment]
https://codesandbox.io/s/vkui-boilerplate-forked-ddf27

**Comment by gbowsky** [comment]
+, на одном из проектов была такая-же проблема.

**Comment by gtishenko** [comment]
+, тоже воспроизводится.

**Comment by gbowsky** [comment]
![image](https://user-images.githubusercontent.com/36237725/99847573-59151580-2b89-11eb-9f04-1db6a98fc5e2.png)
@ArthurStam

**Comment by GrigAnd** [comment]
![dMVv0lYtEmg](https://user-images.githubusercontent.com/69015669/99848424-cf664780-2b8a-11eb-9cf9-bdc8185d9504.jpg)

**Comment by asalisinasa** [comment]
+ воспроизводится

**Comment by ArthurStam** [comment]
Поправлено в `4.0.0-beta.36`
