### ISSUE TITLE
Поддержка box-sizing: border-box

### ISSUE THREAD

**Issue by khovanskiy** [VKCOM/VKUI#115]
При интеграции VKUI в проект возникли баги со смещением некоторых элементов. Вызвано это из-за того, что библиотека предполагает box-sizing: content-box по-умолчанию, в то время, как в проекте используется border-box для всех элементов. Исходя из того, что большинство современных UI-библиотек (например, bootstrap) также используют его ради удобства верстки, предлагаю добавить подключаемый стиль, который перекрывает стили по-умолчанию (или при возможности делать это с помощью JS).

Пример некоторых стилей для фикса:
```
.HeaderButton--android .Icon--24 {
  padding-top: 0;
}

.PanelHeader--ios, .PanelHeader--ios .PanelHeader__in, .PanelHeader--ios .PanelHeader-bg {
  height: 64px;
}
```

Как вариант еще можно прописать box-sizing: content-box для всех классов блоков и их элементов (.View, .Cell, .Panel и т.д.).

**Comment by ArthurStam** [comment]
Стили библиотеки – это ее приватное АПИ. Я выступаю против таких фиксов, особенно в PanelHeader и HeaderButton.

**Comment by khovanskiy** [comment]
Согласен, что это ее приватное API. Поэтому и предлагаю в рамках библиотеки дописать соответствующие стили (box-sizing: content-box) для элементов.

**Comment by ArthurStam** [comment]
А `box-sizing` по умолчанию разве не `content-box`?

**Comment by ArthurStam** [comment]
Чо-т я стремаюсь такие стили добавлять. Мы сторонние либы просто не используем, поэтому для нас такой проблемы нет. Ничего же не мешает на стороне пользователя VKUI дописать этот стиль, если есть потребность.

**Comment by khovanskiy** [comment]
В качестве workaround сейчас и добавляю такие стили.
```
.View,
.View__header,
.PanelHeader,
...
.Cell,
.FixedLayout,
.HeaderButton,
.Icon {
  box-sizing: content-box;
}
```
но просто хотелось бы на уровне библиотеки это прописать, чтобы не зависеть от внутренней реализации.

**Comment by ArthurStam** [comment]
Так я до сих пор не понял, зачем прописывать это на уровне библиотеки, если и так все работает? Или вы совместно используете нашу либу с той, которая использует такие костыли?
```css
* { box-sizing: border-box }
```

**Comment by khovanskiy** [comment]
Да, использую совместно с bootstrap 4.1.3.  Другие популярные фреймворки также используют этот костыль: Foundation, Bulma, Materialize и т.д.

**Comment by ArthurStam** [comment]
Сейчас подумал. Нужно будет явно прописать box-sizing для абсолютно каждого блока. Это too much. Я не хочу идти на поводу у либ, которые явно делают что-то не то. Тем более когда речь идет о раздувании выходного CSS.
