### ISSUE TITLE
[Bug] [DatePicker] Невозможно выбрать 31 число и месяц декабрь, если на странице есть FixedLayout. Последние пункты залезают под FixedLayout.

### ISSUE THREAD

**Issue by gtishenko** [VKCOM/VKUI#1154]
**Описание**
Невозможно выбрать 31 число и месяц декабрь, если на странице есть FixedLayout. Последние пункты залезают под FixedLayout.

**Шаги воспроизведения**
1. Создать DatePicker, чтобы он отображался внизу страницы
2. Добавить FixedLayout 

**Ожидаемое поведение**
Либо создается отступ снизу, чтобы декабрь и 31 число не залезали под FixedLayout, либо Select открывается вверх.

**Пример с воспроизведением**
https://codesandbox.io/s/vkui-boilerplate-forked-cgliv

**Comment by ArthurStam** [comment]
`FixedLayout` — это надстройка над `position: fixed`. Подразумевается, что отступ в панели будет добавляться разработчиком, а не библиотекой. В документации об этом сказано https://vkcom.github.io/VKUI/#/FixedLayout
