### ISSUE TITLE
[Bug] TS2322: Type '"ios"' is not assignable to type 'Platform | undefined'.

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#1157]
**Описание**
TS не воспринимает типы, описанные в `ConfigProvider` для platform, с TS ignore (// @ts-ignore) всё хорошо работает

**Скриншоты**
<img width="795" alt="Снимок экрана 2020-11-20 в 22 44 56" src="https://user-images.githubusercontent.com/45998835/99843092-05eb9480-2b82-11eb-9d07-edfd8e3e027f.png">

 "@vkontakte/vkui": "^4.0.0-beta.34",

**Comment by ArthurStam** [comment]
Он же подсказывает, что нужно использовать не строку, а `Platform`. В твоём случае нужно прописать `Platform.IOS` или просто `IOS`. Все это экспортируются из vkui.

**Comment by ilyapishchulin** [comment]
Странно, что нельзя передавать обычный string, но спасибо)
