### ISSUE TITLE
Поддержка TypeScript

### ISSUE THREAD

**Issue by khovanskiy** [VKCOM/VKUI#116]
Большинство популярных JS библиотек имеют типизированный конфиг (d.ts) внутри пакета для его подключения в TypeScript проекты. Также часто создается дополнительный пакет в NPM вида: @types/my_lib_name, который содержит эту конфигурацию (хотя вариант названия @types/@vkontakte/vkui не очень удачный получается).

Без какой-либо конфигурации использование библиотеки затруднительно, так как не работает  autocomplete в популярных IDE, а постоянно переключаться на документацию или на просмотр исходников крайне неудобно.

**Comment by ArthurStam** [comment]
Изучу этот вопрос и отпушусь. Спасибо.

**Comment by MaxSvargal** [comment]
Есть подвижки?

**Comment by ArthurStam** [comment]
Не добрались еще

**Comment by ArthurStam** [comment]
Так, если кто из желающих выполнения этой фичи еще жив, то го ко мне в лс https://vk.com/arthurstam

**Comment by nt4f04uNd** [comment]
Братья, когда добавите то уже?

**Comment by ArthurStam** [comment]
Приступаем :)

**Comment by ArthurStam** [comment]
Приступили, следите за прогрессом в release notes

**Comment by ArthurStam** [comment]
Полностью переехали на TS в 3-й версии.
