### ISSUE TITLE
Обновления для версий Web и Compact

### ISSUE THREAD

**Issue by 17sobolev** [VKCOM/VKUI#1161]
Обновления VKUI Web Library · Beta:

1. Высота контролов (инпуты, селекты, чекбоксы и радио-кнопки) вместо 40px → 36px.
2. Отступ между лейблом и инпутом/селектом вместо 8px → 6px.
3. Высота Button Large обновилась 40px → 36px.
4. Высота Switch: 44px → 40px.
5. Цвет фона у input и select: steel gray 40 → steel gray 20.
6. Цвет текста empty внутри input и select: steel gray 400 → steel gray 500.

Обновления VKUI Android Library (Compact):

1. Высота контролов (инпуты, селекты, чекбоксы и радио-кнопки) вместо 40px → 36px.
2. Отступ между лейблом и инпутом/селектом вместо 8px → 6px.
3. Высота Button Large обновилась 40px → 36px.
4. Высота Switch: 44px → 40px.

Обновления VKUI iOS Library (Compact):

1. Высота контролов (инпуты, селекты, чекбоксы и радио-кнопки) вместо 40px → 36px.
2. Отступ между лейблом и инпутом/селектом вместо 8px → 6px.
3. Высота Button Large обновилась 40px → 36px.
4. Высота Switch: 44px → 40px.
5. Иконки у чекбоксов и радио заменены на 20 точек (как у андроид).

**Comment by Lihachyov** [comment]
Изменения с пункта 1 по 4 применяется на все платформы и только под sizeY=compact
Пункт №5 в iOS: имеется в виду в макете стало как на всех остальных платформах под sizeY=compact

Насчёт изменений цветов в вебе: осторожно, тут надо сохранить токены. Тут мы должны обновить схему
