### ISSUE TITLE
[Bug] Cell ios на широком экране

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1165]
**Описание**
На широком экране у Cell вылезает контент при удалении.

**Скриншоты**
<img src="https://user-images.githubusercontent.com/11076888/100176947-927fb500-2eea-11eb-8eb3-d1c2ee7c44ad.png" width="600" />
<img src="https://user-images.githubusercontent.com/11076888/100176834-6c5a1500-2eea-11eb-9720-836ddf4b918d.png" width="600" />

**Comment by ArthurStam** [comment]
Известно, спасибо

**Comment by ArthurStam** [comment]
Поправлено в `4.0.0-beta.36`
