### ISSUE TITLE
[Bug]DatePicker на IOS 14 отображает числа не тем цветом

### ISSUE THREAD

**Issue by a1phaZ** [VKCOM/VKUI#1167]
**Описание**
DatePicker на IOS 14 отображает числа не тем цветом

**Шаги воспроизведения**
Включаем темную тему IOS и светлую тему VK, проверяем. И наоборот.
З.ы. возможно цвет чисел берется из стилей темы IOS, а цвет бэкграунда из стилей темы VK

**Ожидаемое поведение**
Числа отображаются нужным цветом при любых вариантах.

**Скриншоты**
![photo_2020-11-25_08-01-21](https://user-images.githubusercontent.com/6966909/100177781-8862b400-2ef4-11eb-8696-ceddb7bae059.jpg)
![photo_2020-11-25_08-01-46](https://user-images.githubusercontent.com/6966909/100177785-88fb4a80-2ef4-11eb-9006-2907fad624c1.jpg)

**Comment by ArthurStam** [comment]
Интересный баг. Спасибо, поизучаем

**Comment by ArthurStam** [comment]
Баг на стороне нашего iOS-клиента. Отнесу им. Тут закрываю.
