### ISSUE TITLE
[Bug] HorizontalCell не поддерживает длинный контент

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1171]
**Скриншоты**
<img src="https://user-images.githubusercontent.com/11076888/100290556-12625980-2f95-11eb-915e-d87a43d111d8.png" width="600">

**Comment by ArthurStam** [comment]
Спасибо, поправим

**Comment by ArthurStam** [comment]
Поправлено в `4.0.0-beta.36`
