### ISSUE TITLE
[Bug] Все props в PanelHeaderContent обязательные

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1172]
https://github.com/VKCOM/VKUI/blob/3043a30eceb390062dbf113b7a52e75d6021d7bb/src/components/PanelHeaderContent/PanelHeaderContent.tsx#L7-L11

**Comment by ArthurStam** [comment]
Спасибо, поправим

**Comment by ArthurStam** [comment]
Поправлено в `4.0.0-beta.36`
