### ISSUE TITLE
[Bug] Отступы в HorizontallCell

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1173]
**Описание**
Слишком маленькие/асимметричные, отступы в HorizontallCell. На скриншотах особенно видно.

**Скриншоты**
<img src="https://user-images.githubusercontent.com/11076888/100293404-067a9580-2f9d-11eb-9386-cd6cddfc864f.png" width="600">
<img src="https://user-images.githubusercontent.com/11076888/100293599-aafcd780-2f9d-11eb-9210-c028c00ac82c.png" width="600">

**Comment by ArthurStam** [comment]
Спасибо, поизучаем
