### ISSUE TITLE
[Bug] [CellButton]: интерфейс не поддерживает атрибут `type`

### ISSUE THREAD

**Issue by 21alexander21** [VKCOM/VKUI#1174]
**Описание**
Интерфейс `CellButton` не поддерживает атрибут `type`, он нужен для кнопки внтури. Если передать его передать, то он все-таки попадет в кнопку благодаря спреду, но типы не сходятся и тайпскрипт ругается.

https://github.com/VKCOM/VKUI/blob/v4.0.0-beta.34/src/components/CellButton/CellButton.tsx#L7

**Версия библиотеки**
v4.0.0-beta.34

**Comment by 21alexander21** [comment]
Возможно имеет смысл по дефолту сделать `type="button"` для кнопки в CellButton или даже для всех кнопок, как это было в 28 бете. После обновления на  v4.0.0-beta.34 у нас взорвались некторые формы

**Comment by ArthurStam** [comment]
Поправлено в `4.0.0-beta.36`
