### ISSUE TITLE
[Bug][ContentCard] Неправильный тип компонента

### ISSUE THREAD

**Issue by 21alexander21** [VKCOM/VKUI#1177]
**Описание**
Компонент `ContentCard` имеет тип `React.FunctionComponent` ([пруф](https://github.com/VKCOM/VKUI/blob/v4.0.0-beta.34/src/components/ContentCard/ContentCard.tsx#L52)), соответсвенно из пропсов принимает только `children`. `ContentCardProps` никак не используется.

При этом в коде тоже ошибка, если явно указан тип переменной, то нельзя присвоить значение другого типа:
```javascript
const foo: number = "2";
const Foo: React.FC = (props: {bar: string, baz: string}) => null;
```
Оба этих примера работать не будут

**Версия библиотеки**
v4.0.0-beta.34

**Comment by ArthurStam** [comment]
Поправлено в `4.0.0-beta.36`
