### ISSUE TITLE
[Bug] Сломался PanelHeader на IOS

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1178]
**Описание**
В PR/MR #1111 в `.PanelHeader__in` добавили `box-sizing: border-box` из-за чего `--safe-area-inset-top` учитывается в высоту блока, что ломает верстку,

**Версия библиотеки**
v4.0.0-beta.34

**Comment by ArthurStam** [comment]
Дубликат #1145

**Comment by eolme** [comment]
@ArthurStam, там `can't reproduce` или я что-то пропустил?)

**Comment by eolme** [comment]
<img src="https://user-images.githubusercontent.com/11076888/100482384-a3117480-3110-11eb-8a22-060dcea01706.png" width="600">
