### ISSUE TITLE
[Feature] UsersStack размером 16

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1179]
Пример использования:
<img src="https://user-images.githubusercontent.com/11076888/100452892-78ed9180-30d3-11eb-81bb-9a59d9c6b893.png" width="600">

**Comment by ArthurStam** [comment]
@wayshev

**Comment by wayshev** [comment]
Обсудили, стоит сделать.

**Comment by fedorov-xyz** [comment]
Предлагаю заменить буквенные размеры `s` и `m` этого компонента на числа с обратной совместимостью. С учётом этого issue, список итоговых значений свойства `size` будет `16 | 24 | 32 | 's' | 'm'`, где `s` – `24`, а `m` – `32`.

**Comment by eugpoloz** [comment]
> Предлагаю заменить буквенные размеры `s` и `m` этого компонента на числа с обратной совместимостью. С учётом этого issue, список итоговых значений свойства `size` будет `16 | 24 | 32 | 's' | 'm'`, где `s` – `24`, а `m` – `32`.

Обсудили, решили не заменять.
