### ISSUE TITLE
Расширение возможностей Button

### ISSUE THREAD

**Issue by khovanskiy** [VKCOM/VKUI#118]
1) Сейчас класс `Button` не может полностью заменить стандартный тег `<button>`, так как не хватает атрибута `disabled` с соответствующим стилем. Это полезено, когда мы хотим заблокировать действие до тех пор, пока не выполнены некоторые условия.
2) Было бы удобно иметь смесь `Link` + `Button` = `LinkButton`, которая будет работать как ссылка, но выглядеть как кнопка. Это полезно, когда хотим перейти на внешний сайт, но с кнопкой это можно сделать только через `window.open` или `document.location.assign`, а такие действия iOS часто блокирует из-за кривой событийной модели Safari (webView).
 3) Возможно, не относится к кнопке, но хотелось бы уметь показывать кнопку с "бегающими тремя точками" (как в веб-версии ВК). Анимированной иконки для этого нет. Это полезно, когда хотим показать пользователю, что запрос/процесс идет, но просто блокировать кнопку не хочется.

**Comment by ArthurStam** [comment]
1. `disabled` есть.
2. Такое тоже есть, пролистайте пример до конца https://vkcom.github.io/vkui-styleguide/#!/Button
3. Либа не имеет отношения к веб-версии ВК, она про iOS и Android клиенты, где нет такого состояния. Если хочется визуализировать выполнение асинхронного процесса, то посмотрите в стороне <ScreenSpinner /> или просто <Spinner />.

**Comment by khovanskiy** [comment]
Спасибо!
