### ISSUE TITLE
[Bug][CardScroll] Не работает при динамическом изменении списка слайдов

### ISSUE THREAD

**Issue by 21alexander21** [VKCOM/VKUI#1180]
**Описание**
Если в `CardScroll` добавлять потомков динамически, то сломается кнопка "Вправо". Если изначально потомков не было, затем мы добавили несколько, то нажатие стрелочки "Вправо" передвинет карусель к началу.
Это происходит из-за того, что в `HorizontalScroll` ширина контейнера сохраняется только 1 раз после первого рендера https://github.com/VKCOM/VKUI/blob/v4.0.0-beta.34/src/components/HorizontalScroll/HorizontalScroll.tsx#L169, соответсвенно, сколько потомков было в первом рендере, такой ширины и будет слайдер.

**Версия библиотеки**
v4.0.0-beta.34

**Comment by ewgenius** [comment]
Было исправлено в #1229, доступно начиная с версии 4.0.8
