### ISSUE TITLE
[Bug] Анимация переключения панелей при структуре Tabs + View Panel в Panel прыгает под Header

### ISSUE THREAD

**Issue by TheRealFaner** [VKCOM/VKUI#1181]
**Описание**
Анимация переключения панелей прыгает под Header и Tabs. Тем временем после окончания анимации панель отображается как положено

**Ожидаемое поведение**
Панель не меняет свою позицию при проигрывании анимации открытия/закрытия панели.

**Скриншоты**
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/22054516/100469657-42326e00-3109-11eb-80e5-3f2d490dd941.gif)

**Пример с воспроизведением**
https://codesandbox.io/s/vkui-boilerplate-forked-uywjf

**Comment by ArthurStam** [comment]
Неправильная структура компонент в приложении. Прочитайте [концепт](http://vkcom.github.io/VKUI/#/Concept).

**Comment by TheRealFaner** [comment]
> Неправильная структура компонент в приложении. Прочитайте [концепт](http://vkcom.github.io/VKUI/#/Concept).

Добавил пример кода.
С концептом повторно ознакомился. Получается лучше будет заменить мой подход отдельными компонентами?

**Comment by ArthurStam** [comment]
Табы переключают содержимое конкретной панели.
