### ISSUE TITLE
[Feature] Кнопка для очистки поля Input

### ISSUE THREAD

**Issue by nickname32** [VKCOM/VKUI#1184]
Сделайте возможным включить крестик для очистки поля у Input (как у Search, внутри поля справа, появляется когда что-то введено)

**Comment by NekR** [comment]
Привет! Какой юзкейс?

**Comment by nickname32** [comment]
> Привет! Какой юзкейс?

В моём приложении (https://vk.com/app7607943) есть поле для открытия профиля по ID, хочется чтоб у него справа была эта кнопка
