### ISSUE TITLE
[Feature] Закрытие popout нажатием системной кнопки "Назад"

### ISSUE THREAD

**Issue by nickname32** [VKCOM/VKUI#1185]
Думаю в названии всё достаточно понятно. Ещё хочу лишь сказать, что я не знал точно куда мне надо было обращаться с этим, и я уже пробовал сам додуматься как это решить (решения, которые я увидел, были вариантом хуже, чем просто ничего не делать).

**Comment by NekR** [comment]
Привет. Спасибо за фича-реквест. Когда нибудь будет. Следите за репозиторием https://github.com/VKCOM/vk-router

**Comment by thoughtspile** [comment]
Закрываю тикет — сам VKUI не работает с роумингом.
