### ISSUE TITLE
[Bug] Прыгает PanelHeader

### ISSUE THREAD

**Issue by nickname32** [VKCOM/VKUI#1187]
Баг происходит в моём мини-приложении ВКонтакте Sociorate - https://vk.com/app7607943
Иходный код открыт - https://github.com/Sociorate/sociorate-vk-mini-app

**Версия библиотеки**
3.13.2

Запущено на IOS

**Шаги воспроизведения**
1.Открыть приложение Sociorate
3.Открыть любой профиль
4. Оттянуть страницу вниз (до состояния, когда страница отпружинивает обратно вверх)
5. Удерживая страницу оттянутой вниз, перейти на предыдущую панель

**Фактическое поведение**
Панель хэдэр дёргается

**Ожидаемое поведение**
Панель хэдэр не дёргается

**Comment by nickname32** [comment]
Хочу также сказать, что он прыгает и ещё в одном кейсе в этом же приложении

Для воспроизведения:
1. Пооткрывать профилей, чтобы наполнился список последних открытых
2. Отматать страницу вниз
3. Перейти в какой-то профиль (не мотая страницу вверх)
4. Вернуться обратно

**Comment by NekR** [comment]
Это известно, спасибо.
Что бы пофиксить, можно начать кешировать контент панели и не запрашивать его снова при возвращении.

**Comment by nickname32** [comment]
> Это известно, спасибо.
> Что бы пофиксить, можно начать кешировать контент панели и не запрашивать его снова при возвращении.

Контент кэшируется. Сначала отображается кэшированая версия, и в фоне запращивается обновлённая.

**Comment by nickname32** [comment]
https://github.com/Sociorate/sociorate-vk-mini-app/blob/c1718253b161cee3ac461ca0fafd985e69903fec/src/panels/Home.js#L144
https://github.com/Sociorate/sociorate-vk-mini-app/blob/c1718253b161cee3ac461ca0fafd985e69903fec/src/panels/Home.js#L151
https://github.com/Sociorate/sociorate-vk-mini-app/blob/c1718253b161cee3ac461ca0fafd985e69903fec/src/panels/Home.js#L159
https://github.com/Sociorate/sociorate-vk-mini-app/blob/c1718253b161cee3ac461ca0fafd985e69903fec/src/panels/Home.js#L415

**Comment by NekR** [comment]
Нужно видео. Так ничего не понять.

**Comment by nickname32** [comment]
Это для второго кейса
http://www.mediafire.com/file/pt4jshuf87ath5t/screencast.webm/file
Для первого, если разрешит тот, кто его снял, пришлю позже

**Comment by nickname32** [comment]
Видео первого кейса
https://vk.com/doc338562982_579836046?hash=f0a437eda0d8602383&dl=1705df5e863a3a3c29

**Comment by ArthurStam** [comment]
Попробуйте версию `4.0.4`

**Comment by eolme** [comment]
Фиксится с #1064
