### ISSUE TITLE
[Bug] Двойная анимация при SwipeBack в браузере IOS

### ISSUE THREAD

**Issue by nickname76** [VKCOM/VKUI#1190]
Происходит в моём приложении Sociorate (https://m.vk.com/app7607943 IOS).

**Версия библиотеки**
3.13.2

**Шаги воспроизведения**
1. Откройте Sociorate через m.vk.com на IOS (https://m.vk.com/app7607943)
2. Откройти чей-нибудь профиль
3. Сделайте свайп бэк

**Ожидаемое поведение**
Должна быть только одна анимация.

**Скриншоты**
https://vk.com/doc214477552_579153388?hash=a7207909f94f706745&dl=921e117c6890b29546

**Comment by kiyasov** [comment]
Планируется ли фикс данного бага? 

**Версия библиотеки**
4.0.3


P.s 
Как костыль можно кидать `bridge.send("VKWebAppSetSwipeSettings", { history: false });` на 1 панель

**Comment by kiyasov** [comment]
@fedorov-xyz Привет, планируется ли фикс данного бага?

**Comment by pfrankov** [comment]
Не открывается https://m.vk.com/app7607943
