### ISSUE TITLE
[Bug] Иногда зависает PullToRefresh

### ISSUE THREAD

**Issue by nickname32** [VKCOM/VKUI#1191]
**Описание**
Происходит в моём приложении в IOS версии ui https://vk.com/app7607943
https://github.com/Sociorate/sociorate-vk-mini-app
Может периодически возникать на любой панели с птр

Спиннер птр продолжает висеть после установки false для isFetching

**Версия библиотеки**
3.13.2

**Comment by nickname32** [comment]
https://github.com/Sociorate/sociorate-vk-mini-app/blob/4f7475575c74609017d6cf08c4e5de8bdd5a0e2c/src/panels/Profile.js#L577

**Comment by ArthurStam** [comment]
Тут без живого примера с воспроизведением не обойтись. Нужен MVP с ошибкой https://codesandbox.io/s/vkui-boilerplate-oj149

**Comment by nickname32** [comment]
Я сам не знаю при каких условиях он происходит. Мне на тестпуле два человека сообщили об этом баге.

**Comment by riledv** [comment]
Тоже появилась эта ошибка, проявляется только в моб версии, использую vkui 3 версии
