### ISSUE TITLE
[Bug] Ломается верстка сервиса после выбора и загрузки фото в горизонтальном режиме

### ISSUE THREAD

**Issue by mike-petrov** [VKCOM/VKUI#1194]
**Шаги воспроизведения:**
1. Открыть сервис с возможностью загрузки фотографии с устройства, например Ловина (https://vk.com/app7058363)
2. Перевернуть телефон в горизонтальный режим
3. Нажать загрузить фото, выбрать фото из гелерее (всё это в горизонтальном режиме)

**Версия библиотеки**
3.13.1

**Фактическое поведение**
Верстка сервиса ломается, все сужается (первый скриншот ниже)

**Ожидаемое поведение**
Корректная работа сервиса (второй скриншот ниже)

**Скриншоты**
![Фактическое поведение](https://user-images.githubusercontent.com/32885629/100630107-30d0a800-333b-11eb-8172-cb443bea0992.PNG)
![Ожидаемое поведение](https://user-images.githubusercontent.com/32885629/100630121-35955c00-333b-11eb-9e3b-3b2256662810.PNG)

**Comment by FlyInk13** [comment]
Это баг iOS 14
Например такое очень просто воспроизвести в Chrome, если повернуть телефон, зайти в "шторку" и повернуть телефон обратно

**Comment by gbowsky** [comment]
Посмотрел, кажется что больше не воспроизводится.
Тестовый пример: https://wrgdg.csb.app
