### ISSUE TITLE
[Bug] Ломается верстка CardGrid в ModalPage

### ISSUE THREAD

**Issue by KaluKali** [VKCOM/VKUI#1200]
**Описание**
margin-left там где его быть не должно в CardGrid который в ModalPage

**Версия библиотеки**
3.13.2

**Шаги воспроизведения**
Для создания используется FormLayout с CardGrid 

**Пример с воспроизведением**
https://codesandbox.io/s/vkui-boilerplate-forked-ifti2?file=/src/index.js

**Comment by eugpoloz** [comment]
Duplicate of #1026.
