### ISSUE TITLE
[Feature][Документация] Ускорить стайлгайд

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#1202]
Документация библиотеки становится все больше, уже в данный момент документация последней беты 4 версии загружается более 20 секунд. Также очень проблематично зайти в консоль разработчика, чтобы, например, посмотреть стили компонентов - документация начинает подвисать от изобилия примеров.
Предлагаю убрать все примеры компонентов под спойлеры и подгружать их только в момент раскрытия.

**Comment by thoughtspile** [comment]
Проблема есть, но прятать примеры кажется слишком суровым решением, потому что это основной полезный контент.
Чтобы играть в консоль разработчика прямо сейчас, советую открывать пример в изолированном режиме через штуку справа от названия компонента: 
<img width="320" alt="Снимок экрана 2020-12-07 в 12 32 59" src="https://user-images.githubusercontent.com/5262915/101334356-cfec2700-3888-11eb-823f-534eb55bd129.png">
