### ISSUE TITLE
[Bug] [PTR] PTR не прячется под шапку

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1207]
Из за фикса https://github.com/VKCOM/VKUI/issues/933, появился другой баг, т.к. раньше PTR уходил под header, то теперь этого не происходит. Более наглядно тут https://youtu.be/EshAMTDz2fY

**Comment by thoughtspile** [comment]
Справедливости ради, PTR никогда не уходил под шапку, хотя и должен. Спасибо, я возьму

**Comment by thoughtspile** [comment]
Исправлено в v4.0.0-beta.37
