### ISSUE TITLE
[Bug] [ChipsInput] Удаляется элемент, если ввести его еще раз

### ISSUE THREAD

**Issue by thoughtspile** [VKCOM/VKUI#1211]
**Шаги воспроизведения**
1. Вводим в ChipsInput текст "123", жмем Enter
ПР: В ChipsInput выбран "123"
2. Еще раз вводим "123", жмем Enter

ОР: "123" остался выбран
ФР: "123" удалился

**Версия библиотеки**
4.0.0-beta34

**Comment by SkyGopnik** [comment]
Не думаю что это было бы хорошей практикой, т.к. пользователь будет недоумевать почему не может добавить ещё один Chip, возможно лучше сделать как в Ant, когда Chip убирается, но слово которое ты вписал остаётся.

**Comment by thoughtspile** [comment]
> пользователь будет недоумевать почему не может добавить ещё один Chip


Как минимум, тут есть что обсудить) Как сейчас мне точно не нравится, потому что терять данные плохо. Еще неплохой вариант — перетаскивать уже введенный чип в конец (так сейчас работает в почте mail.ru)

**Comment by eugpoloz** [comment]
Пофикшено в #1541.
