### ISSUE TITLE
[Bug] Контент заходит под PanelHeader

### ISSUE THREAD

**Issue by LazyTechwork** [VKCOM/VKUI#1216]
**Описание**
Контент заходит под `PanelHeader` при использовании `SplitLayout`

**Версия библиотеки**
v4.0.0-beta.34

**Шаги воспроизведения**
```jsx
    <SplitLayout
            header={<PanelHeader
                shadow fixed style={{zIndex: 150}}
                left={<img style={{maxHeight: 32, marginLeft: 32}} src={LogoNeowave} alt="NeoWave"/>}
                right={<Icon28ChevronDownOutline/>}
            />}
            style={{marginTop: 0}}
        >
```
При использовании `visor` пропа в `PanelHeader` проблема не исчезает. Исследовал из-за чего такое поведение, увидел что у `SplitLayout` появляется свойство `margin-top: -34px;`, установил в `0px` и контент больше не залезает

**Comment by thoughtspile** [comment]
@LazyTechwork возможно, была проблема в теме vkcom — там не должно быть отдельных шапок у колонок. Посмотри, сейчас ничего не должно залезать: https://vkcom.github.io/VKUI/#!/SplitLayout

**Comment by gbowsky** [comment]
Закрываю за отсутствием активности.

**Comment by LazyTechwork** [comment]
> @LazyTechwork возможно, была проблема в теме vkcom — там не должно быть отдельных шапок у колонок. Посмотри, сейчас ничего не должно залезать: https://vkcom.github.io/VKUI/#!/SplitLayout

Да, в этом и была проблема. Спасибо.
