### ISSUE TITLE
[Feature] Epic and Adaptivity

### ISSUE THREAD

**Issue by gbowsky** [VKCOM/VKUI#1230]
Стоит добавить возможность скрыть Tabbar в Epic. Это необходимо для удобной реализации вёрсток адаптивности на основе существующих и будущих мини-приложений.

Текущая реализация Epic подразумевает собой обязательное наличие Tabbar в prop tabbar, если не передавать Tabbar в prop Tabbar, то мы имеем отступы у .Panel__in, вызывающие косметические несоответствия.

**Comment by NekR** [comment]
А какой именно юзкейс тут? Если адаптивность и таббар не нужен, то можно полностью эпик убрать.

**Comment by gbowsky** [comment]
Юзкейс стандартный, незаметны продублировал #134.

Можно конечно вынести контент в отдельный компонент и проносить пропсы, или справиться с дублированием кода (что не есть хорошо), но это не самые лучшие решения.

**Comment by NekR** [comment]
Похоже что тот баг не имеет ничего общего с этим -- тот про модалки, этот про адаптивность.

Если по дизайну адаптивности нет таббара, значит и эпика в коде не должно быть.

**Comment by gbowsky** [comment]
В таком случае приходится использовать наследование при проработке той-же самой навигации, что как по мне — не есть хорошо. Возможно ещё что-то упускаю.

**Comment by gbowsky** [comment]
Возможны случаи, когда контент в Tabbar лучше перенести в SplitCol

**Comment by NekR** [comment]
То есть ты в итоге согласился? А то непонятно.

Ну и нет никаких "может". Есть четкие правила адаптивности и того как компоненты должны быть расположены и где.

**Comment by gbowsky** [comment]
Нет, я не согласился. Вот ещё один пример

![image](https://user-images.githubusercontent.com/36237725/102067984-e821f000-3e0c-11eb-86b5-b3b480529b98.png)
![image](https://user-images.githubusercontent.com/36237725/102067994-ebb57700-3e0c-11eb-865a-57998c74abb7.png)

**Comment by NekR** [comment]
Чего именно это пример?

**Comment by eolme** [comment]
> Чего именно это пример?

Он имеет ввиду, что на мобилках Tabbar, а на десктопе его нет, точнее его заменяет SplitLayout

**Comment by gbowsky** [comment]
Спасибо @eolme, всё именно так)

**Comment by NekR** [comment]
Вы что-то путаете. SplitLayout есть всегда, это раз.
Epic нужно убирать из дерева, когда визуально в структуре его нет, это два.

**Comment by eolme** [comment]
@NekR, он рутовый, ну то бишь находится вверху, менять его не удобно

**Comment by NekR** [comment]
Fixed #1237

Временно сделали так как вы описывали.
