### ISSUE TITLE
[Feature] Перенос строк в subtitle Header

### ISSUE THREAD

**Issue by 21alexander21** [VKCOM/VKUI#1238]
В компоненте `Header`, subtitle рендерится с `white-space: nowrap;`, такого быть не должно и длинный текст должен переноситься.

**Comment by ArthurStam** [comment]
Обсужу это с дизайнерами, спасибо.

**Comment by wayshev** [comment]
В идеале сабтайтл должен переноситься по умолчанию, а тайтл можно сделать флагом (эллипсить/переносить), т.к. это уже не всегда хорошо выглядит
