### ISSUE TITLE
[Bug] Неверно определяется размер слайдов на платформе vkcom

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1241]
Gallery v4.0.0-beta.37
Неверно определяется размер слайдов на платформе vkcom
![image](https://user-images.githubusercontent.com/26293210/102719222-e8832500-42fd-11eb-89ec-de097c96a431.png)
![image](https://user-images.githubusercontent.com/26293210/102719235-f6d14100-42fd-11eb-9673-7c0d23b181a8.png)

Прикол ещё в том что если немного изменить размер (пользуясь средствами разработчика), то размер встаёт на своё место

Вот как это выглядит на телефонах
![image](https://user-images.githubusercontent.com/26293210/102719244-051f5d00-42fe-11eb-8c97-811ce70fce01.png)
![image](https://user-images.githubusercontent.com/26293210/102719251-11a3b580-42fe-11eb-86df-faad0ad0b630.png)

`
<Gallery align="center">
            <div style={{ backgroundColor: 'var(--destructive)' }} />
            <div style={{ backgroundColor: 'var(--button_commerce_background)' }} />
            <div style={{ backgroundColor: 'var(--accent)' }} />
          </Gallery>
`

**Comment by NekR** [comment]
Привет! Пока плохо понятно. Нужна демка где можно посмотреть и воспроизвести проблему.

**Comment by SkyGopnik** [comment]
Просто Gallery используйте без любых отступов и всё.

**Comment by SkyGopnik** [comment]
Для проверки менял platform

**Comment by NekR** [comment]
Нужна демка всё равно, иначе так будем долго тыкаться.

**Comment by SkyGopnik** [comment]
https://youtu.be/tsSz69UDZxM

**Comment by thoughtspile** [comment]
@SkyGopnik я очень старался, но не воспроизвелось :(
Сделал [сандбокс](https://codesandbox.io/s/vkui-gallery-ry9j1?file=/src/index.js) с рабочим примером (можно открыть в браузере на https://ry9j1.csb.app) — там тоже неправильно определяется?

**Comment by SkyGopnik** [comment]
На удивление нет, видимо я где-то накосячил, извиняюсь :c

**Comment by thoughtspile** [comment]
О нет, это баг со случайной воспроизводимостью! Я понял, в чем проблема, сейчас подумаю что делать

**Comment by SkyGopnik** [comment]
> О нет, это баг со случайной воспроизводимостью! Я понял, в чем проблема, сейчас подумаю что делать
> 
> Если что, проблема в динамическом добавлении класса vkui на html: убираются дефолтные маргины, а размеры слайдов не пересчитываются

Там кстати размер правильный, но вот размер остановок слайдов нет.

**Comment by seadinkin2002** [comment]
Приветствую, тоже столкнулся с багом на десктопе...

https://yadi.sk/i/yBV1DlktiDcauw,
завести новую issues?, баг явно не на моей стороне, на мобильной платформе все хорошо.![image](https://user-images.githubusercontent.com/62930989/103653095-d5bb5200-4f85-11eb-823a-f7b73e47f5e0.jpeg)

**Comment by SkyGopnik** [comment]
> Приветствую, тоже столкнулся с багом на десктопе...
> 
> https://yadi.sk/i/yBV1DlktiDcauw,
> завести новую issues?, баг явно не на моей стороне, на мобильной платформе все хорошо.![image](https://user-images.githubusercontent.com/62930989/103653095-d5bb5200-4f85-11eb-823a-f7b73e47f5e0.jpeg)

Лучше не нужно наверное, думаю этого issue хватит

**Comment by ewgenius** [comment]
@SkyGopnik судя по демке, это одно и то же #1337?

**Comment by ewgenius** [comment]
> Если что, проблема в динамическом добавлении класса vkui на html: убираются дефолтные маргины, а размеры слайдов не пересчитываются

изначальная проблема исправлена в #1268 (релиз v4.0.3)

> Приветствую, тоже столкнулся с багом на десктопе...
> 
> https://yadi.sk/i/yBV1DlktiDcauw,
> ...

судя по демке - проблема при навигации, была исправлена в #1332 (релиз v4.0.8)

Последняя возможная проблема с шириной слайдов описана в #1337, поэтому закрываю этот тикет

**Comment by SkyGopnik** [comment]
> @SkyGopnik судя по демке, это одно и то же #1337?

Да. Очень похоже, тоже неровно определяется граница скрола

**Comment by SkyGopnik** [comment]
Но у меня скролл бара не было)

**Comment by ewgenius** [comment]
> Но у меня скролл бара не было) 

Это просто один из случаев, вызывающих этот баг)
