### ISSUE TITLE
[Bug] Первая принудительная смена слайда происходит без анимации

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1243]
Первая принудительная смена слайда происходит без анимации - https://youtu.be/ldq13VS3zgM , воспроизводится на всех платформах.

Если слайд свайпнуть руками и потом уже нажать на кнопку смены, то анимация будет.

v4.0.0-beta.37

**Comment by thoughtspile** [comment]
v4.0.0-beta.37

**Comment by thoughtspile** [comment]
в 4.0.3 будет ок
