### ISSUE TITLE
Cell: onClick и onRemove не работают вместе

### ISSUE THREAD

**Issue by khovanskiy** [VKCOM/VKUI#125]
Если написать для компонента Cell: onClick и onRemove:
```
<Cell onClick={this.onClick} removable={true} onRemove={this.onRemove}>...</Cell>
```
то при удалении происходит вызов события onRemove и после вызов события onClick, что очень странно, так как мы пытаемся перейти по удаленному объекту.

Проверено под Android и iOS.

**Comment by ArthurStam** [comment]
Надо подумать, как правильно должно быть.
