### ISSUE TITLE
[Bug] Нет файла IOSDetections v4.0.1

### ISSUE THREAD

**Issue by sijuz** [VKCOM/VKUI#1252]
**Описание**
Отсутствует файл IOSDetections в /lib/ который подключается в /lib/browser.js на строке 2.

**Версия библиотеки**
v4.0.1

**Шаги воспроизведения**
Запустить проект через npm start на версии v4.0.1 или (v4.0.0) и появится ошибка компиляции.

**Ожидаемое поведение**
Проект успешно запуститься.

**Скриншоты**
https://sun9-71.userapi.com/impf/69r3cyG9N_tqcb04ptRWGlIuwRj6Tjp_EYvfUQ/UCpotm8Biso.jpg?size=929x189&quality=96&proxy=1&sign=715d0230fea712a65b981e51f53ecc43&type=album

**Comment by fedorov-xyz** [comment]
У вас установлена зависимость @vkontakte/vkjs?

**Comment by NekR** [comment]
peer зависимости установлены?

**Comment by sijuz** [comment]
![Screenshot_10](https://user-images.githubusercontent.com/25132437/102793218-a7047f80-43ba-11eb-9aa8-f0de8f7f7bd7.jpg)

**Comment by NekR** [comment]
Это просто список. Их вручную установить надо
