### ISSUE TITLE
[Bug] React does not recognize the `noSlideClick` prop on a DOM element

### ISSUE THREAD

**Issue by LazyTechwork** [VKCOM/VKUI#1253]
**Описание**
Использую следующий код:
```jsx
ReactDOM.render(
    <AdaptivityProvider>
        <AppRoot>
            <App/>
        </AppRoot>
    </AdaptivityProvider>,
    document.getElementById('root')
);
```

**Версия библиотеки**
v4 (Release)

**Скриншот**
![Ошибка в консоли](https://user-images.githubusercontent.com/25130565/102795063-517da200-43bd-11eb-90ad-29bab7ed4b0c.png)

**Comment by thoughtspile** [comment]
Спасибо, фикс в работе

**Comment by ElForastero** [comment]
В `<Touch />` пропс лишний заспредился.

**Comment by russian-proger** [comment]
Ошибка всё равно осталась в версиях 4.0.x

**Comment by russian-proger** [comment]
![image](https://user-images.githubusercontent.com/35803227/103166671-4b1c7980-4846-11eb-935c-395a7eac990d.png)

**Comment by russian-proger** [comment]
Как исправить?

**Comment by ArthurStam** [comment]
Это ворнинг, а не ошибка. На работу библиотеки не влияет. Будет исправлено в ближайшем релизе.

**Comment by russian-proger** [comment]
Хорошо, благодарю!
