### ISSUE TITLE
[Bug] При обёртке компонента в withAdaptivity, предполагаемые свойства undefined

### ISSUE THREAD

**Issue by Roman-Shubnikov** [VKCOM/VKUI#1273]
Я обернул своё приложение в hoc withAdaptivity(App, { viewWidth: true }), но при этом свойство viewWidth undefined

4.0.2

Воспроизвёл ситуацию здесь:
https://codesandbox.io/s/testwithadaptivity-ncvmy

**Comment by thoughtspile** [comment]
Привет! Чтобы завёлся `withAdaptivity`, нужно обернуть приложение в [AdaptivityProvider](https://vkcom.github.io/VKUI/#!/Концепция), примерно [так](https://codesandbox.io/s/testwithadaptivity-provider-y8b6c?file=/src/App.js:77-86)
