### ISSUE TITLE
[Bug] Платформа VKCOM не определяется 

### ISSUE THREAD

**Issue by Roman-Shubnikov** [VKCOM/VKUI#1279]
Я оборачиваю свой компонент в withPlatform. 
Он определяет платформу как ios или android. Получить значение vkcom не удаётся ни при каких условиях.
При каких условиях я смогу получить значение vkcom?

4.0.2

User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.60 Safari/537.36

**Comment by thoughtspile** [comment]
Привет! Чтобы получить vkcom, явно оберни приложение в `<ConfigProvider platform={Platform.VKCOM}>`. Тикет пока оставим.

**Comment by Roman-Shubnikov** [comment]
Ну через ConfigProvider работает нормально, но мне же нужно чтобы платформу определяло автоматически. Из-за чего может некорректно работать withPlatform?

**Comment by kiyasov** [comment]
> Ну через ConfigProvider работает нормально, но мне же нужно чтобы платформу определяло автоматически. Из-за чего может некорректно работать withPlatform?

Он работает корректно, там определяется только [IOS и Android](https://github.com/VKCOM/VKUI/blob/master/src/lib/platform.ts#L20)

Можно определять по ширине экрана через [AdaptivityProvider](https://vkcom.github.io/VKUI/#adaptivityprovider)
```
import {
  ViewWidth,
  withAdaptivity
} from "@vkontakte/vkui";

function App({ viewWidth }) {
    const isDesktop = viewWidth >= ViewWidth.SMALL_TABLET; 
}

export default withAdaptivity(App, { viewWidth: true });

```

**Comment by Roman-Shubnikov** [comment]
> > Ну через ConfigProvider работает нормально, но мне же нужно чтобы платформу определяло автоматически. Из-за чего может некорректно работать withPlatform?
> 
> Он работает корректно, там определяется только [IOS и Android](https://github.com/VKCOM/VKUI/blob/master/src/lib/platform.ts#L20)
> 
> Можно определять по ширине экрана через [AdaptivityProvider](https://vkcom.github.io/VKUI/#adaptivityprovider)
> 
> ```
> import {
>   ViewWidth,
>   withAdaptivity
> } from "@vkontakte/vkui";
> 
> function App({ viewWidth }) {
>     const isDesktop = viewWidth >= ViewWidth.SMALL_TABLET; 
> }
> 
> export default withAdaptivity(App, { viewWidth: true });
> ```
> 
> P.s Можно ещё через [Параметры запуска ](https://vk.com/dev/vk_apps_docs3?f=6.%2B%D0%9F%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D1%8B%2B%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0) поле vk_platform

А так вот оно что! Просто в новой документации активно используется `withPlatform` или hook с выражением `platform !== VKCOM;`. Предполагается что VKCOM должен определятся. Я конечно уже нашёл обходной путь. Маленькая недоработка.

**Comment by ArthurStam** [comment]
Скоро проясним нюансы работы с платформой. Пока что можно воспользоваться возможностью прокинуть vk_platform через ConfigProvider.

**Comment by pfrankov** [comment]
Возможное решение:
https://github.com/VKCOM/VKUI/pull/1632
