### ISSUE TITLE
[Bug] [cmp:chip-input] Повторное значение удаляет и себя, и старое

### ISSUE THREAD

**Issue by iamsergo** [VKCOM/VKUI#1285]
**Описание**
При вводе значения в `ChipInput`, которое уже есть в списке и нажатии enter, оно исчезает из списка.

**Версия библиотеки**
4.0.3

**Шаги воспроизведения**
1. Ввод значения в ChipsInput
2. Нажатие enter
3. Повторение тех же действий с тем же значением
4. Удаляются оба значения - старое и новое

**Ожидаемое поведение**
Новое значение не заносится в поле, старое не удаляется.

**Comment by ArthurStam** [comment]
Дубликат #1211
