### ISSUE TITLE
[Bug] Legacy context API has been detected within a strict-mode tree.

### ISSUE THREAD

**Issue by MerdyNumber1** [VKCOM/VKUI#1289]
Варнинг об устаревшем использовании контекста.
Версия реакта, где пробовал - 16.8.6, 17.x.x
![image](https://user-images.githubusercontent.com/50208720/103692051-483d2980-4fa8-11eb-9ef0-38899411a4d4.png)
![image](https://user-images.githubusercontent.com/50208720/103692063-4c694700-4fa8-11eb-83a0-e4b908da7bca.png)
![image](https://user-images.githubusercontent.com/50208720/103692089-54c18200-4fa8-11eb-8f2e-11eb71a0b888.png)

**Comment by gbowsky** [comment]
Дубликат.
https://github.com/VKCOM/VKUI/issues/817

**Comment by eolme** [comment]
@gbowsky, действительно. А может лучше не использовать устаревший контекст?)

**Comment by ArthurStam** [comment]
Привет. Известно, есть план по выпиливанию старого контекста

**Comment by ArthurStam** [comment]
Пофикшено в #1282, появится в следующем релизе

**Comment by ewgenius** [comment]
legacy context был убран в #1282, исправлено в v4.0.5
