### ISSUE TITLE
[Feature] Добавить пропс after для компонента Input

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#1290]
Хотелось бы иметь возможность отображать справа от Input-a иконку с действием
Пример нашел внутри интерфейса vk.com/editapp?id={APP_ID}

<img width="653" alt="Снимок экрана 2021-01-06 в 13 52 18" src="https://user-images.githubusercontent.com/45998835/103760623-66496f00-5026-11eb-851c-5f74a294bec7.png">

**Comment by ArthurStam** [comment]
Тут тоже что-то подобное просят #1184

**Comment by ArthurStam** [comment]
И тут #529

**Comment by ArthurStam** [comment]
И тут #975

**Comment by ilyapishchulin** [comment]
Окей

**Comment by ArthurStam** [comment]
Зачем же так. Я просто заменшенил, чтобы те ребята не потеряли прогресс.

**Comment by ilyapishchulin** [comment]
Так я подумал ты на дубль намекаешь)

**Comment by ilyapishchulin** [comment]
Спасибо)
