### ISSUE TITLE
[Bug] Активируются инпуты при тапе вне их области на VKUI 4.

### ISSUE THREAD

**Issue by yurachinenov** [VKCOM/VKUI#1302]
**Описание**
При тапе вне инпута инпут активируется, хотя мы не тапали по нему.
Курсор отображается в виде "Default" в этой кликабельной области.

**Версия библиотеки**
VKUI 4

**Шаги воспроизведения**
1. Перейдите в документацию 4 VKUI https://vkcom.github.io/VKUI/#formstatus.
2. Тапайте над инпутами, либо рядом с его областью.

**Ожидаемое поведение**
Либо мы не должны иметь возможность тапнув вне инпута, активировать инпут, либо курсор должен меняться на "Text" в кликабельной области.

**Скриншоты**
![мвк](https://user-images.githubusercontent.com/77573092/104840039-fc5a8080-58d5-11eb-9745-265dad5fc027.PNG)

**Пример с воспроизведением**
https://vkcom.github.io/VKUI/#formitem (Если я правильно понял что нужно вставлять).

**Comment by ArthurStam** [comment]
Привет. Известная проблема, будем исправлять, но вероятно в следующей мажорной версии. Пока можно просто передать в `<FormItem Component="div" />`
