### ISSUE TITLE
[Bug] Слайды галереи имеют неправильную ширину при смене панелей внутри SplitCol

### ISSUE THREAD

**Issue by Melzmr** [VKCOM/VKUI#1315]
**Описание**
Ломаются определение позиции слайдов в галерее при смене панели на другую панель в рамках SplitCol.

**Версия библиотеки**
4.0.4

**Шаги воспроизведения**
У меня есть две колонки в SplitLayout. В первой колонке у меня есть Panel1 и Panel2. Также на этих колонках стоит animate={false}.
При смене колонок, Panel1 и Panel2 становятся шириной во весь экран (в ширину SplitLayout), а не в ширину своей SplitCol. Из-за этого при инициализации слайдов в Gallery, берется неправильный offsetWidth у детей. Из-за этого слайдер потом не правильно высчитывает offset'ы для карусели и мы видим этот баг в сендбоксе.
Однако, при следующем рендере offsetWidth у детей правильный, и Gallery это ловит, и пытается где-то там обновить, но в state это обновленное состояние ширины ребенка не попадает. И берется всегда старый width из this.slidesStore.

**Пример с воспроизведением**
https://codesandbox.io/s/vkui-boilerplate-forked-nl5ho

**Comment by ewgenius** [comment]
Fixed in 4.0.8
