### ISSUE TITLE
[Bug] Стакаются View при быстрой смене

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1338]
**Описание**
В общем, заметил такой прикол, что если на неактивной вкладке менять View, то они начинают себя странно вести и стакаются, тем самым блокируя интерфейс.

Как воспроизвести открываем приложение, уходим на другую вкладку и ждем когда приложение загрузится, возвращаемся обратно и видим заблокированный интерфейс.
Моя история смены View выглядит так:
Минуты : секунды
![image](https://user-images.githubusercontent.com/26293210/106105409-02adef80-6155-11eb-893b-bd485fa666ec.png)

В DOM это выглядит так:
![image](https://user-images.githubusercontent.com/26293210/106105459-16f1ec80-6155-11eb-8cbd-cea669f41341.png)

Он очень странный, если 1 раз поменять View, что у меня происходит например когда подключаются одновременно два игрока и выкидывается ошибка, одному из них, то ничего не происходит.

Но случай сверху у меня воспроизводится стабильно.

Версия: v4.0.8

**Comment by SkyGopnik** [comment]
Вот как история выглядит при нахождении на вкладке, то есть особо никакого различия нет, но и бага нет.
![image](https://user-images.githubusercontent.com/26293210/106106011-f2e2db00-6155-11eb-8737-742baac2a8cb.png)

**Comment by SkyGopnik** [comment]
В общем, при быстрой смене View они ломаются, как я понимаю это происходит из за анимации, которую сейчас нельзя отключить.

**Comment by land47** [comment]
> как я понимаю это происходит из за анимации, которую сейчас нельзя отключить

Анимацию можно отключить с помощью [ConfigProvider](https://github.com/VKCOM/VKUI/blob/1ab22fb3977a3b818e3a92f1d1c5e938d341ddba/src/components/ConfigProvider/ConfigProviderContext.tsx#L50)

**Comment by SkyGopnik** [comment]
Проверю, спасибо, не думал что так далеко унесли.

**Comment by SkyGopnik** [comment]
Спасибо, помогло, но issue всё равно напишу)
