### ISSUE TITLE
[Bug][IconButton] Обязательный проп icon

### ISSUE THREAD

**Issue by 21alexander21** [VKCOM/VKUI#1342]
В интерфейсе пропсов проп `icon` помечен как deprecated и вместо него предполагается использовать `children`.  Но при этом `icon` является обязательным и пытается отрендериться если передан. Приходится передавать туда что-то, что приведется к false, чтоб отрендерить `children`

https://github.com/VKCOM/VKUI/blob/03ef1ec302391c29ed76c5dc9a42784ac3acf3ae/src/components/IconButton/IconButton.tsx#L10

**Comment by fedorov-xyz** [comment]
Спасибо, исправим.

**Comment by fedorov-xyz** [comment]
Будет в ближайшем релизе.
