### ISSUE TITLE
[Bug] Анимация Panel и View

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1343]
Баг наверное с v1 версии VKUI, из за анимации Panel и View, их быстрая смена приводит к багу когда отрендерены сразу две панели или страницы, что вытекает в полностью заблокированный интерфейс и потерю пользователя. Я думаю нужно наконец это исправить, чтобы анимация никак не влияла на смену и прерывалась, если смена идёт в момент анимации.

**Comment by thoughtspile** [comment]
duplicate of #177
