### ISSUE TITLE
[Bug] Failed to compile.

### ISSUE THREAD

**Issue by Keller18306** [VKCOM/VKUI#1346]
**Описание**
Ошибка при компиляции приложения:
Failed to compile.

./node_modules/@vkontakte/vkui/dist/lib/browser.js
Module not found: Can't resolve '@vkontakte/vkjs/lib/IOSDetections' in 'C:\OpenServer\domains\justpro.local\CLI\nodejs\blue_project\blue_coin\mini-app\node_modules\@vkontakte\vkui\dist\lib'

**Версия библиотеки**
4.0.8

**Шаги воспроизведения**
Я обновился до последней версии, запустил реакт и всё.

**Скриншоты**
![image](https://user-images.githubusercontent.com/23178771/106368513-1165f380-635b-11eb-8197-1b9906182c2b.png)

**Comment by Keller18306** [comment]
P.S. смог пофиксить установив отдельно @vkontakte/vkjs

**Comment by Keller18306** [comment]
+ это в только что созданном приложении через create-vk-mini-app
![image](https://user-images.githubusercontent.com/23178771/106370266-66a90180-6369-11eb-9c85-135560568537.png)

**Comment by ewgenius** [comment]
@Keller18306 можешь выложить свой пример на CodeSandbox или просто на GitHub?

Проверил на последней версии create-vk-mini-app и VKUI, все завелось без проблем, все нужные зависимости на месте

**Comment by ewgenius** [comment]
Закрываю, перекройте если будет больше информации или пример кода приложения
