### ISSUE TITLE
[Bug] Св-во id у ModalPage

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1347]
Убрать св-во id у ModalPage, т.к. у того же ModalCard его нет, а их логика работы одинаковая.

**Comment by gbowsky** [comment]
Не понимаю ясной причины убирать id у `ModalPage`, он [чётко требуется](https://github.com/VKCOM/VKUI/tree/v4.0.8/src/components/ModalRoot#описание-работы) для определения activeModal.

Логичнее было бы наоборот его добавить как обязательный проп к `ModalPage`.

**Comment by SkyGopnik** [comment]
Если создать внешнюю обёртку над модалкой, то id прописывается на обёртку, на модалке он уже не нужен, по этому его обязательность бесполезна. У ModalCard он подключен через HTMLAttributes, в ModalPage нужно сделать тоже самое.
