### ISSUE TITLE
[Bug] Неправильное описание типа VK Bridge VKWebAppGetFriends

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1348]
Как сейчас:
![image](https://user-images.githubusercontent.com/26293210/106384593-bffe4880-63dc-11eb-9f34-57c93599398a.png)
Как должно быть:
![image](https://user-images.githubusercontent.com/26293210/106384620-e328f800-63dc-11eb-9231-1b3d109ec3f6.png)

+ Косяк кстати в доке https://vk.com/dev/vk_bridge_events_6?f=Вызов%2Bсписка%2Bдрузей%2Bпользователя
![image](https://user-images.githubusercontent.com/26293210/106384685-2edba180-63dd-11eb-8461-bbe6d1fa0e05.png)
sex - всегда число

Ещё как пожелание, при единичном выборе, возвращать сразу пользователя, а не объект, в котором массив.
+ Ещё, убрать лишнюю обёртку users, при множественном выборе возвращать сразу массив.

**Comment by gbowsky** [comment]
Привет, эта проблема не относится к библиотеке.
Она относится к [vk-bridge](https://github.com/VKCOM/vk-bridge).
