### ISSUE TITLE
[Feature] Возможность отключения анимации View или Panel

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1350]
Сейчас св-ва transitionMotionEnabled у ConfigProvider отключает все анимации. Хочется хотя бы разделить эту возможность, отдельно на View, отдельно на Panel, раз https://github.com/VKCOM/VKUI/issues/177 не хотят фиксить уже 2 года.

**Comment by NekR** [comment]
#117 поправим

**Comment by SkyGopnik** [comment]
Не тот чутка)

**Comment by eolme** [comment]
@SkyGopnik, а зачем закрыл? Не плохой фича-реквест.

**Comment by SkyGopnik** [comment]
Так сказали что то решат, я и подумал, что этот тогда лишний)

**Comment by ArthurStam** [comment]
#177 в процессе, разделять отключение анимации не хочется, это усложнит API.
