### ISSUE TITLE
[Bug] Заморозка страницы

### ISSUE THREAD

**Issue by MrProLopstar** [VKCOM/VKUI#1355]
**Описание**
Я до этого использовал версию библиотеки 3.x.x . У меня есть список, который открывается как ModalPage с помощью кнопки Epic (структура Epic и ModalPage в index.js). После выбора пункта из списка (ModalPage сворачивается) происходило обновление localStorage (стандартного) и Panel (поверх которого и открывалось модальное окно) производило перерендер, т.к. проверка localStorage была в рендере. С новой же версии библиотеки Panel морозится до следующего действия (нажатия кнопки на ней же или чего-то подобного) и не производит перерендеринга. Если это всё же не баг, то просто помогите решить проблему ^_^

**Версия библиотеки**
4.0.8

**Comment by ewgenius** [comment]
> производило перерендер, т.к. проверка localStorage была в рендере

Скорее всего ре-рендер вызывался таббаром или каким-то другим эффектом при открытии/закрытия ModalPage или Epic в старой версии

Сам по себе localStorage не вызовет ре-рендер компонента, и полагаться на это внутри рендера не корректно.
Правильнее будет хранить все данные в стэйте и передавать в панель и модалку через пропсы или контекстом, или использовать любую библиотеку для стейта (redux, mobx, etc.).
Если нужно сохранять стейт в localStorage, то это можно делать внутри useEffect

**Comment by ewgenius** [comment]
Проблема не является багом VKUI, поэтому закрываю
