### ISSUE TITLE
Некорректный размер шапки приложения VK Connect в браузерах Firefox/IE11

### ISSUE THREAD

**Issue by kuhel** [VKCOM/VKUI#136]
**Шаги воспроизведения:**

Перейти в приложение VK App
**Фактический результат:**

Шапка приложения вытягивается по высоте и выглядит не особо
**Ожидаемый результат:**

Шапка приложения не вытягивается по высоте
**Браузер:**
- [ ] Firefox 57.0.4 (64-bit)
- [ ] IE 11

## Firefox
![image](https://user-images.githubusercontent.com/12458667/46480962-f02c8100-c7fa-11e8-97c4-10b22b0ad908.png)

## IE11
![image1](https://user-images.githubusercontent.com/12458667/46480963-f02c8100-c7fa-11e8-8e78-2ee4ce1579ac.png)

## Chrome
![image2](https://user-images.githubusercontent.com/12458667/46480964-f02c8100-c7fa-11e8-9461-e0fe6b63b38d.png)

**Comment by ArthurStam** [comment]
Есть идеи, как это фиксить? Я знаю, что это происходит из-за safe-area-insets. Именно их наличие добавляет отступ сверху.

**Comment by kuhel** [comment]
В VKUI можно определить платформу, на которой запущено приложение? Если да, то можно для веба это как-то фиксить
