### ISSUE TITLE
[Bug] TabbarItem не Tappable

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1361]
**Описание**
Поведение TabbarItem не соответствует поведению аналогичного нативного компонента. В частности, отсутствуют эффекты нажатия.

**Версия библиотеки**
v4.0.8

**Comment by ArthurStam** [comment]
Спасибо, поправим

**Comment by ArthurStam** [comment]
Не нашел дизайн hover/active состояний, поэтому бахнул без ховера и active, уходящий в opacity. Нужна помощь дизайна.

Посмотреть можно тут, установив мобильную ширину: https://vkcom.github.io/VKUI/pull/1512/#/Epic

**Comment by eolme** [comment]
Нативный клиент:
<img src="https://user-images.githubusercontent.com/11076888/113473551-38d05e00-947b-11eb-9c4a-0cbc6ae30fb2.png" width="600" />

**Comment by eolme** [comment]
На iOS, они ещё немного увеличиваются при активном состоянии

**Comment by ArthurStam** [comment]
Подожду макеты от команды дизайна, на глаз не хочется делать.
