### ISSUE TITLE
[Bug] ModalRoot switching не устанавливается при закрытии

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1370]
**Описание**
ModalRoot switching при открытии модалки устанавливается, а при закрытии - нет.

**Версия библиотеки**
v4.0.8

**Comment by ewgenius** [comment]
Должно быть исправлено в #1358
Будет в релизе 4.0.9

**Comment by eolme** [comment]
Почему? В #1358 только `false` значения появились. При открытии также будет `true`, а при закрытии `false`

**Comment by ewgenius** [comment]
А в чем собственно сам баг выражается? Зачем нужен `switching: true` при закрытии?

**Comment by eolme** [comment]
Затем же, зачем при открытии - отоброжает внешние состояние компонента.

Например, можно подвязываться в css:
```css
.ModalRoot--switching + .AwesomeDecorateComponent
```

**Comment by ewgenius** [comment]
> Например, можно подвязываться в css

Внутренний стейт компонентов и классы не являются публичным апи библиотеки, поэтому так делать не стоит

**Comment by ewgenius** [comment]
> Затем же, зачем при открытии - отоброжает внешние состояние компонента.

Если я не ошибаюсь, `switching` не предназначен для полного отображения состояния: этот флаг нужен чтобы отключить закрытие по клику на фоне, в момент пока модалка открывается или переключается на новую.
Если модалка закрывается то в этом нет необходимости

**Comment by eolme** [comment]
> классы не являются публичным апи

Точнее в данный момент являются единственным публичным апи для отображения состояния

**Comment by eolme** [comment]
Я не против, если появятся какие-то callback для анимаций, где-то был по этому поводу issue

**Comment by ewgenius** [comment]
> Точнее в данный момент являются единственным публичным апи для отображения состояния

Я про то, что со стороны VKUI не классы не описаны в документации и нет гарантий что внутреннее поведение компонента может поменяться, поэтому лучше не стоит на это рассчитывать)


> Я не против, если появятся какие-то callback для анимаций, где-то был по этому поводу issue

👍

#680 - можешь добавить туда если есть какие-то дополнения?
