### ISSUE TITLE
[Bug] Ограничение размера снэкбара

### ISSUE THREAD

**Issue by yurachinenov** [VKCOM/VKUI#1371]
**Описание**
Снэкбар при его активации появляется в нижнем левом углу экрана, что выглядит достаточно странно и некрасиво, особенно при маленьком тексте, словно снэкбар обрезан. Пользователь, который ранее не был в мини-приложениях даже не сможет увидеть на пк версии этого снэкбара, как происходит в данном случае, указанном на видео, когда мы нажимаем кнопку в правой части экрана, ничего не происходит в области наших глаз, не появляется никакой надписи рядом с кнопкой, что выглядит достаточно странно, но после мы видим её в левой части экрана. (Как раз со мной такое и случилось, сперва я даже подумал, что кнопка не кликабельна, не увидев этого снэкбара).

**Версия библиотеки**
VKUI4

**Шаги воспроизведения**
1. Зайдите в приложение https://vk.com/app7651248
2. Перейдите в первый таб.
3. Перейдите в "Работа".
4. Тап "Устроиться" на любой недоступной работе.

**Ожидаемое поведение**
Есть два варианта устранения недостатка. 
Первый - растянуть полосу вдоль экрана, как на VKUI3.
Второй - поместить снэкбар посередине.

**Скриншоты**
![мвк3](https://user-images.githubusercontent.com/77573092/107099415-a9178600-6822-11eb-8846-406174225214.PNG)

**Пример с воспроизведением**

https://user-images.githubusercontent.com/77573092/107099558-11666780-6823-11eb-9c5d-460a2618738c.mp4

**Comment by ewgenius** [comment]
> Пользователь, который ранее не был в мини-приложениях даже не сможет увидеть на пк версии этого снэкбара, как происходит в данном случае, указанном на видео, когда мы нажимаем кнопку в правой части экрана, ничего не происходит в области наших глаз, не появляется никакой надписи рядом с кнопкой

Это вопрос к дизайну приложения, а не к VKUI. В данном случае проблемы в компоненте снэкбара нет

> Первый - растянуть полосу вдоль экрана, как на VKUI3.
Второй - поместить снэкбар посередине.

Выглядит так, будто вы хотите мобильный дизайн под десктоп. Этого можно добиться зафорсив ширину экрана - тогда снэкбар растянется на всю ширину:
```tsx
<AdaptivityProvider viewWidth={ViewWidth.MOBILE}>
   ...
</AdaptivityProvider>
```

Отмечу что так делать  не рекомендуется - VKUI 4 подразумевает адаптивное поведение под платформу и размеры экрана, и правильнее будет адаптировать приложение под десктоп

**Comment by ewgenius** [comment]
закрываю, так как это не баг
