### ISSUE TITLE
[Bug] Лишняя пустая область на границах экрана 

### ISSUE THREAD

**Issue by yurachinenov** [VKCOM/VKUI#1372]
**Описание**
Лишняя область с похожей палитрой цвета на #e9ecf1 (233,236,241), которая выглядит достаточно странно на фоне таббара и скролла, словно либо таббар слишком длинный, который растянул окно и отделил скролл от приложения.
Проблема в том, что выглядит это некрасиво, если смотреть с точки зрения UI, т.к над таббаром появляется на границах пустая область, которая кажется срезанной, тем более если смотреть на скролл, то можно заметить, словно он прикреплен к пустой области.
**Версия библиотеки**
VKUI4

**Шаги воспроизведения**
1. Зайдите в приложение https://vk.com/app7651248
2. Перейдите в пятый таб.
3. Присмотритесь на правую/левую/ границы экрана, как размещен таббар и скролл по отношении к этим границам.

**Ожидаемое поведение**
Есть два варианта:
1. Обрезать таббар под эти границы (чтобы скролл прижался к цветовой области приложения, а не границ).
2. Расширить само окно приложения, чтобы цветовой области этих границ не было, а приложение было прикреплено к скроллу.
**Скриншоты**
![мвк](https://user-images.githubusercontent.com/77573092/107100683-2db7d380-6826-11eb-873e-3476979387aa.PNG)
**Пример с воспроизведением**
https://user-images.githubusercontent.com/77573092/107100736-4b853880-6826-11eb-8e55-783f9f67141e.mp4

**Comment by yurachinenov** [comment]
Может конечно и не баг, но мне это кажется достаточно странным решением интерфейса.

**Comment by ewgenius** [comment]
Как и в #1371: видимо вы ожидаете мобильный дизайн на десктопе.
Если зафиксировать viewWidth в AdaptivityProvider (смотрите мой коммент в #1371) у приложения не будет отступов по краям

Компоненты Epic + Tabbar рассчитаны для использования на мобильных устройствах, для десктопа лучше адаптировать навигацию как-то иначе (сайдбар, навбар сверху, etc - это уже вопросы дизайна приложения а не VKUI)
Пример адаптивной навигации с табором и сайдбаром можно посмотреть здесь https://vkcom.github.io/VKUI/#!/Epic

**Comment by ewgenius** [comment]
закрываю, так как это не баг
