### ISSUE TITLE
[Bug] onClose в ActionSheet вызывается несколько раз

### ISSUE THREAD

**Issue by land47** [VKCOM/VKUI#1385]
Если установить состояние не сразу (или вообще оставить onClose пустым), то переданный cb в onClose для ActionSheet будет вызван несколько раз. Баг воспроизводится только в версии с рефами

```typescript
onClose={() => {
  console.log('close')
  setTimeout(() => this.setState({ popout: null }))
}}
```
![image](https://user-images.githubusercontent.com/53087814/107474033-b4e8ac80-6b82-11eb-8f03-79052e134413.png)

**Версия библиотеки**
4.1.0

**Comment by ewgenius** [comment]
Фикс выпущен в 4.2.0

**Comment by ub1x** [comment]
> Фикс выпущен в 4.2.0
Не знаю баг или фича, но если передавать пропс popout в View и SplitLayout то поведение повторяется из ишью.
