### ISSUE TITLE
[Bug] лишние padding в .Icon

### ISSUE THREAD

**Issue by iamsergo** [VKCOM/VKUI#1393]
**Описание**
В классе .Icon присутствуют лишние padding, из-за чего иконка съезжает вниз

**Версия библиотеки**
4.1.0

**Шаги воспроизведения**
Иконка в любом месте. Хоть в  ```<PanelHeaderBack/>```, хоть в ```<Cell after={<Icon28/>}/>```

**Ожидаемое поведение**
Убрать padding.
![0](https://user-images.githubusercontent.com/64886990/107879492-21004300-6eea-11eb-944b-b96839025deb.png)

**Comment by fedorov-xyz** [comment]
Подскажите, нет ли у вас каких-то прочих стилей, потому что у класса `Icon` нет встроенных паддингов?

**Comment by iamsergo** [comment]
@fedorov-xyz 
Вот этот класс, перепутал.
.Icon--28 {
    padding: 10px на андроид и 8px на ios
}

Подключаю только css из документации vkui и импортирую иконки с vk-icons

**Comment by iamsergo** [comment]
У меня ```box-sizing : border-box``` был для всех элементов установлен.
В этом проблема.

**Comment by VitiaCatDragon** [comment]
Проблема воспроизводится на версии 5.0.1
![изображение](https://user-images.githubusercontent.com/60291267/206899980-0ad72c74-564f-4675-8ed0-56fb8eb417f7.png)
