### ISSUE TITLE
Поддержка SSR

### ISSUE THREAD

**Issue by TrueCarry** [VKCOM/VKUI#140]
При попытке подключить библиотеку для ssr рендеринга сыпится огромное количество ошибок.

- Вебпак передает window в инициализацию модулей, а его нет. https://stackoverflow.com/questions/49111086/webpack-4-universal-library-target, пишут что это баг и надо добавить в конфиг `globalObject: 'this'`, вроде помогло
- Дальше то-же самое происходит с иконками, но там нет конфига вебпака, поэтому пересобрать и проверить я не смог, заменил в ручную.
- sprite-svg-loader объявлен в конфиге вебпака, а в нем в свою очередь используется navigator без проверки на undefined.
- в Cell много мест, которые выкидывают ошибку из-за остутствия document.

Тут я уже сдался, потому что дальше править без знания логики библиотеки уже сложно, да и становится долго.

Для воспроизведения достаточно скачать любой демо проект на next.js, добавить туда vkui и добавить в dom любой элемент из него.

**Comment by NOCELL** [comment]
VK UI вообще не предназначена для SSR, потому что если вы бы обратили внимание, то панели и PanelHeader - отдельные элементы в DOM.

**Comment by ArthurStam** [comment]
@TrueCarry спасибо. Посмотрю все описанные кейсы и подумаю, как подружить либу с SSR.

**Comment by ArthurStam** [comment]
Приступили, следите за прогрессом в release notes

**Comment by ArthurStam** [comment]
Done https://github.com/VKCOM/VKUI/releases/tag/v3.5.0
