### ISSUE TITLE
[Bug] Проблема с иконкой часов

### ISSUE THREAD

**Issue by drago-v** [VKCOM/VKUI#1408]
Точнее, с иконкой аж две проблемы.

Первая - опечатка в названии иконки - Icon16ClockOurline (очевидно, должно быть Icon16ClockOu**t**line)
Вторая - эта иконка должна быть квадратной (16х16 пикс.), но она почему-то по ширине на один пиксель больше, чем требуется. Пофиксил проблему с помощью margin-right:-1px , но это конечно такое себе решение.

Использую следующие версии библиотек:
@vkontakte/icons - 1.49.0
@vkontakte/vkui - 4.0.8

<img width="330" alt="icon_bug" src="https://user-images.githubusercontent.com/20705877/108358735-23231400-7200-11eb-9148-2cb4a2980bee.png">

**Comment by fedorov-xyz** [comment]
Спасибо за issue. Сегодня-завтра обновим иконку на исправленную.

**Comment by fedorov-xyz** [comment]
https://github.com/VKCOM/icons/issues/92
