### ISSUE TITLE
Съезжает children у PanelHeader на некоторых версиях Android

### ISSUE THREAD

**Issue by ArthurStam** [VKCOM/VKUI#141]
![dyeac82b00k](https://user-images.githubusercontent.com/5061840/48304905-0e407c00-e533-11e8-8e09-3d6e45ef6b1c.jpg)
![image](https://user-images.githubusercontent.com/5061840/48304913-2a441d80-e533-11e8-8704-72f2fc5c0353.png)
>Последняя версия клиента, Android 8.1.0
>MEIZU M3 note, Android 5.1

**Comment by ArthurStam** [comment]
Пофикшено в `2.16.5`

**Comment by plaxin** [comment]
Рад был помочь репортом. :^)
