### ISSUE TITLE
[Bug] Разваливается ModalRoot

### ISSUE THREAD

**Issue by 21alexander21** [VKCOM/VKUI#1413]
**Описание**
Если в `children` окажется не react-элемент, то рендер развалится. Хотя тип children не переопределен и принимает любые ReactNode

**Ожидаемое поведение**
Ожидается либо ограничение типами, либо какая-то обработка такого кейса, например с помощью `React.isValidElement` здесь https://github.com/VKCOM/VKUI/blob/48a2fa052858a5eefee320ff84a4ac41aa33fe5a/src/components/ModalRoot/ModalRoot.tsx#L111

**Comment by thoughtspile** [comment]
Аналогично в других навигационных контейнерах — Root, View, Epic
