### ISSUE TITLE
[Bug] Вызов родительского хэндлера FormLayout в компоненте File при нажатии

### ISSUE THREAD

**Issue by CapUlDis** [VKCOM/VKUI#1424]
**Описание**
Дочерний текстовый компонент компонента File, который отображается кнопкой с указанным текстом, при нажатии вызывает хэндлер onSubmit родительского компонента FormLayout.

**Версия библиотеки**
Версия 4.0.8

**Шаги воспроизведения**
1. Создаём апп со структурой FormLayout > FormItem > File > Загрузить изображение;
2. Вешаем хэндлер onSubmit с сообщением в консоль 'submit' на FormLayout и хэндлер onChange с сообщением в консоль 'change' на File;
3. Нажимаем на кнопку **Загрузить изображение** - видим, что в консоле уже появилось соощение 'submit'.

**Ожидаемое поведение**
При нажатии на кнопку **Загрузить изображение** хэндлер onSubmit не вызывается.

**Пример с воспроизведением**
https://codesandbox.io/s/wizardly-black-6z2bi?file=/src/App.js

**Comment by ewgenius** [comment]
Спасибо за репорт, фикс будет в следующем релизе
