### ISSUE TITLE
[Bug] Неправильное вычисление позиции ActionSheet

### ISSUE THREAD

**Issue by shastox** [VKCOM/VKUI#1425]
**Описание**
В этой строке https://github.com/VKCOM/VKUI/blob/eb71a062007883f6040a1832142db0c3cfa91620/src/components/ActionSheet/ActionSheetDropdownDesktop.tsx#L46 (а по аналогии и в этой) https://github.com/VKCOM/VKUI/blob/eb71a062007883f6040a1832142db0c3cfa91620/src/components/ActionSheet/ActionSheetDropdownDesktop.tsx#L48 ошибка: 

**top = toggleRect.top - elementRect.height + this.window.pageYOffset;**

При скролле **toggleRect.top** будет уменьшаться на ту жу самую величину, на которую будет расти **this.window.pageYOffset** и это приводит к тому, что **top** будет константой.

**Версия библиотеки**
Последняя, 4.2.0, для Desktop

**Шаги воспроизведения**
1. Размещаем на странице элемент, при клике на который открывается ActionSheet.
2. Скроллим страницу.
3. Кликаем на элемент, которые открывает ActionSheet
4. ActionSheet открывается с неправильно рассчитанным top. Если не скроллить страницу на шаге 2), то все ок.

**Ожидаемое поведение**
Дополнительно: при скролле ActionSheet должен скроллиться вместе с контентом, но это уже "хотелка".

**Comment by fedorov-xyz** [comment]
Привет, можешь собрать на codesandbox минимальный пример, где проблема воспроизводится?

**Comment by shastox** [comment]
Привет! Да, живой пример: https://gi0oy.csb.app
Все ок:
1. Открываем ссылку
2. Кликаем на кнопку "click"
3. ActionSheet откроется в правильном месте

Воспроизведение ошибки:
1. Открываем ссылку
2. Скроллим немного, чтобы кнопка слегка "поднялась"
3. Кликаем на кнопку "click"
4. ActionSheet открывается не на кнопке, а в том месте, где кнопка изначально была.

Песочница с минимальным кодом: https://codesandbox.io/s/vkui-boilerplate-forked-igcfv?file=/src/index.js

**Comment by gbowsky** [comment]
Привет! Попробуй перенести popout в SplitLayout. В скором времени обновим документацию.
https://7dqp7.csb.app
https://codesandbox.io/s/7dqp7?file=/src/index.js

**Comment by ArthurStam** [comment]
Автоматическое позиционирование ActionSheet будет сделано в рамках тикета #1618
