### ISSUE TITLE
[Bug][Docs] Ошибка в документации

### ISSUE THREAD

**Issue by TaoriYu** [VKCOM/VKUI#1427]
**Описание**
В примерах для `ModalRoot` есть кейс полноэкранной модалки. Согласно этому примеру, компоненту ModalPage нужно проставить проп `fullscreen`. У `ModalPage` нет такого пропа, а полноэкранной модалку делает проп `settlingHeight={100}`

**Версия библиотеки**
4.2.0

**Шаги воспроизведения**
1. Зайти в доку к версии 4.2.0 и найти описание для ModalRoot - https://vkcom.github.io/VKUI/#modalrootadaptive
2. Открыть код с примерами под VIEW CODE
3. Найти у `ModalPage` с id `MODAL_PAGE_FULLSCREEN` проп `fullscreen`
4. Посмотреть доку к `ModalPage` - https://vkcom.github.io/VKUI/#modalpage
5. Найти, что в разделе PROPS & METHODS пропа `fullscreen` нет

**Comment by gbowsky** [comment]
Будет исправлено в следующем релизе.
