### ISSUE TITLE
[Bug] Частое открытие модального окна приводит к тому, что предыдущее действие на закрытие не отменяется последующим открытием

### ISSUE THREAD

**Issue by aslanorlov** [VKCOM/VKUI#1429]
**Описание**
В ModalRoot значение activeModal соответствует значению из состояния приложения (mobx), при частом изменении этого значения предыдущее действие на закрытие модального окна не отменяется следующим открытием (возможно, стоит setTimeout или что-то подобное (возможно, [тут ](https://github.com/VKCOM/VKUI/blob/master/src/components/ModalRoot/ModalRoot.tsx#L615)), которое не очищается при открытии модального окна) - таким образом, закрытие предудущего модального окна также закрывает и текущее (хотя состояние находится в "модальное окно открыто"). В некоторых случаях из-за этого приложение может крашится.

**Версия библиотеки**
4.2.0

**Шаги воспроизведения**
Быстро открывать и закрывать модальное окно (я воспроизводил через роутинг с get параметрами (переключал url между /settings и settings?modal=modal_name через Alt + (← →) )

**Ожидаемое поведение**
После первого быстрого открытия / закрытия / открытия модально окно будет все равно закрыто (вопреки последнему действию на её открытие)

**Comment by aslanorlov** [comment]
Вот такая ошибка проиходит в версии 4.2.0
![image](https://user-images.githubusercontent.com/40369740/109359915-f1a8e900-788e-11eb-96b1-a03ef7967e84.png)

**Comment by SkyGopnik** [comment]
Видимо всё так же связано с #177, который скоро пойдёт в школу, т.к. везде логика одинаковая.

**Comment by pfrankov** [comment]
Исправлено в https://github.com/VKCOM/VKUI/pull/2195
