### ISSUE TITLE
[Bug] HorizontalScroll: не работает скролл при зуме в 90%

### ISSUE THREAD

**Issue by gloomweaver** [VKCOM/VKUI#1441]
При выставлении зума в 90% скролл срабатывает только при первом нажатии.

**Версия библиотеки**
4.0.4

**Пример с воспроизведением**
https://codesandbox.io/s/horizontalscroll-zoom-90-bug-929s4

**Comment by SevereCloud** [comment]
Привет, фикс будет доступен в следующей версии v4.33.0
