### ISSUE TITLE
[Bug] -fps при рендере больше 50 SimpleCell/Cell возможно RichCell

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1442]
**Описание**
В общем в чём суть, я сделал для себя панель с получением токена и последующим получением друзей через этот же токен, когда я пытаюсь отрисовать больше 50 Cell, панель или само приложение начинает нереально лагать, то есть банально при возврате назад её фризит, модалка открывается с фризом и т.д

https://pastebin.com/rV1pbzqW

**Версия библиотеки**
"@vkontakte/vk-bridge": "^2.4.1",
    "@vkontakte/vkjs": "^0.6.0",
    "@vkontakte/vkui": "^v4.0.8",

**Comment by eolme** [comment]
`Tappable` слишком сложный, а он является базовым компонентов у `Cell`

**Comment by SkyGopnik** [comment]
Есть идеи как могу отключить временно? Пока не пофиксят, потому что бага очень серьёзная

**Comment by eolme** [comment]
Ну могу посоветовать обернуть в мемоизацию, например, чтобы избежать перерендера

**Comment by eolme** [comment]
related: #1443

**Comment by YriginPetr** [comment]
Можно использовать [SimpleCell](https://vkcom.github.io/VKUI/#simplecell)

**Comment by pfrankov** [comment]
Будет исправлено в https://github.com/VKCOM/VKUI/issues/1443
