### ISSUE TITLE
[Bug] Touch зависает при клике

### ISSUE THREAD

**Issue by danyarubtsov** [VKCOM/VKUI#1444]
**Описание**
Если сделать даблклик на Touch, то он зависнет, потом закрепится за мышкой, и при клике зависнет навсегда.

**Шаги воспроизведения**
1) Дважды кликаем на кружок в Touch
2) Пытаемся его перенести (совершаем третье нажатие мышкой)
3) Он закрепляется за мышкой, и зависает на 4 клик, либо при выводе мышки за "границы" его работы

**Ссылка**
https://vkcom.github.io/VKUI/#touch

**Comment by thoughtspile** [comment]
После одинарного клика кружок тоже не перетаскивается
