### ISSUE TITLE
[Feature] next.js

### ISSUE THREAD

**Issue by nikitapilgrim** [VKCOM/VKUI#1447]
Подскажите  кто-нибудь реализовал SSR с next.js? Можете скинуть пример?

**Comment by ewgenius** [comment]
Пример SSR можно посмотреть здесь https://github.com/ewgenius/vkui-kitchen-sink/blob/main/src/pages/ssr.tsx

Одно замечание: адаптивность не может быть определена на сервере, поэтому это надо предусмотреть в самом приложении

В примере в url передается параметр который определяет viewWidth и hasMouse для AdaptivityProvider
https://vkui-kitchen-sink.vercel.app/ssr?view=desktop
https://vkui-kitchen-sink.vercel.app/ssr?view=mobile

**Comment by nikitapilgrim** [comment]
> Пример SSR можно посмотреть здесь https://github.com/ewgenius/vkui-kitchen-sink/blob/main/src/pages/ssr.tsx
> 
> Одно замечание: адаптивность не может быть определена на сервере, поэтому это надо предусмотреть в самом приложении
> 
> В примере в url передается параметр который определяет viewWidth и hasMouse для AdaptivityProvider
> https://vkui-kitchen-sink.vercel.app/ssr?view=desktop
> https://vkui-kitchen-sink.vercel.app/ssr?view=mobile

Спасибо, а как лучше реализовать роутинг?
Наверное ед способ это иметь компонент VKAPP в который мы передаем view в зависимости от роута

**Comment by eolme** [comment]
@nikitapilgrim, чтобы поддержать deeplink так называемые, просто нужно настроить редирект с hash, на нужный, тогда встроенный роутер будет работать.
То бишь, `awesome.app/#/123` > `awesome.app/123`

**Comment by ewgenius** [comment]
> Спасибо, а как лучше реализовать роутинг?
> Наверное ед способ это иметь компонент VKAPP в который мы передаем view в зависимости от роута

@nikitapilgrim чтобы полноценно обрабатывать роутинг на сервере и использовать `next/link`, можно сделать динамический роут `pages/[panel].tsx` и брать id панели из useRouter

Пример:
https://github.com/ewgenius/vkui-kitchen-sink/blob/ssr-routing/src/pages/ssr/%5Bpanel%5D.tsx
https://vkui-kitchen-sink-git-ssr-routing-ewgenius.vercel.app/ssr/panel1?mode=desktop

И еще стоит добавить редирект на первую панель, чтобы дефолт правильно отрабатывал https://github.com/ewgenius/vkui-kitchen-sink/blob/ssr-routing/next.config.js

**Comment by ewgenius** [comment]
> @nikitapilgrim, чтобы поддержать deeplink так называемые

@eolme причем тут deeplink? Это роутинг из веба в экран нативного приложения

> просто нужно настроить редирект с hash, на нужный, тогда встроенный роутер будет работать.
> То бишь, `awesome.app/#/123` > `awesome.app/123`

Хеш часть не отправляется на сервер, и скорее всего next.js редиректы тут не помогут
Плюс я не вижу никакой проблемы в использовании динамического роутинга, как описал в предыдущем комментарии, и костыли с редиректами там не нужны

Никто не запрещает использовать хеш роутинг сам по себе, правда все это будет только на клиенте работать, без SSR
https://github.com/vercel/next.js/issues/779

**Comment by eolme** [comment]
> редиректы тут не помогут

На клиенте в `Document` или `App`, replace по хешу.
Я просто рассматриваю вопрос, как использовать с Mini Apps, а не в целом как запустить на nextjs.
