### ISSUE TITLE
[feature] Поддержать >2 опций SliderSwitch

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1449]
Во первых у него нет обработки, что приходит в `options`, если запихнуть один объект, то вылетит краш.
Во вторых, кто вообще сделал там два айтема? Они должны рендерится через map от пришедшего `options`

**Comment by ArthurStam** [comment]
К реализации и у меня есть вопросы, но в чём конкретно сейчас проблемы? У компонента есть чётко описанный тип `options`.

**Comment by SkyGopnik** [comment]
Не могу например передать 3 элемента в options, что делает его максимально не адаптивным.

**Comment by ArthurStam** [comment]
Понял, задал вопрос дизайнерам

**Comment by SkyGopnik** [comment]
> Понял, задал вопрос дизайнерам

Нуууу, это не совсем относится к дизайну, просто хочется использовать его по своему, в моем кейсе например он идеально подходит для выбора кол-ва предмета x1, x5, x10, я попробовал сам его переделать, но у меня возникли проблемы с нормальной адаптацией самого элемента слайда (активного айтема)

**Comment by ArthurStam** [comment]
Не согласен, вопрос как раз дизайнерский. У нас пока нет понимания, что этот компонент должен уметь. Я подожду гайдов со стороны команды дизайна и тогда вернусь с ответом.

**Comment by SkyGopnik** [comment]
#1514

**Comment by ArthurStam** [comment]
`SliderSwitch` задепрекейтим. Вместо него будет новый [segmented control](https://www.figma.com/file/kvjzdHwTDO7Vcrh1VglGQ5/VKUI-iOS-Library?node-id=29209%3A53213). Там количество элементов не ограничено.

**Comment by ArthurStam** [comment]
Следите за активностью создания нового компонента тут #2055
