### ISSUE TITLE
При нажатии "отмена" в компоненте Search не вызывается коллбэк onChange

### ISSUE THREAD

**Issue by Ansile** [VKCOM/VKUI#145]
При нажатии "отмена" (на iOS, крестик на Android) в компоненте Search не вызывается коллбэк onChange. https://vk.com/bugtracker?act=show&id=82904

**Comment by ArthurStam** [comment]
Компонент будет переделываться в 3-й версии. Там эта проблема уйдёт.

**Comment by ArthurStam** [comment]
Пофикшено в 3.0.0
