### ISSUE TITLE
[Bug] При выносе View в отдельный функциональный компонент Epic не отображает его

### ISSUE THREAD

**Issue by Alkanores** [VKCOM/VKUI#1458]
**Описание**
Если создать два компонента (допустим, TestView и TestEpic), то при использовании TestView в TestEpic TestView не будет отображён.

**Версия библиотеки**
"@vkontakte/vkui": "^4.2.0"

**Шаги воспроизведения**
1. Создаём тестовый проект с VK UI
2. Создаём компонент TestView и возвращаем <View>:

```javascript
<View activePanel="ddd" id="fff">
        <Panel id="ddd">
          FFFFFF
        </Panel>
 </View>
```

3. Вносим в компонент App следующие изменения:
```javascript
<Epic activeStory="fff">
      <TestView/>
</Epic>
```

4. Наблюдаем то, что панель не отображается. 
5. Изменяем код в компоненте App на этот:
```javascript
<Epic activeStory="fff">
      <View activePanel="ddd" id="fff">
          <Panel id="ddd">
                FFFFFF
          </Panel>
     </View>
</Epic>
```
6. Наблюдаем, что панель отобразилась, хотя она должна была отобразиться уже в 3 шаге.

**Ожидаемое поведение**
Epic должен отображать View вне зависимости от того, вынесен ли View в отдельную функцию

**Пример с воспроизведением**
```javascript

import React from "react";
import ReactDOM from "react-dom";
import {
  View,
  Panel,
  AppRoot,
  AdaptivityProvider,
  ConfigProvider,
  Epic,
} from "@vkontakte/vkui";
import "@vkontakte/vkui/dist/vkui.css";

function TestView() {
  return (
    <View activePanel="ddd" id="fff">
        <Panel id="ddd">
          FFFFFF
        </Panel>
    </View>
  );
}

function App() {
  return (
    <Epic activeStory="fff">
      <TestView/>
    </Epic>
  );
}

ReactDOM.render(
  <ConfigProvider>
    <AdaptivityProvider>
      <AppRoot>
        <App />
      </AppRoot>
    </AdaptivityProvider>
  </ConfigProvider>,
  document.getElementById("root")
);

```

**Comment by SkyGopnik** [comment]
![image](https://user-images.githubusercontent.com/26293210/110854787-861b3e80-82c6-11eb-8ac6-8c9b1016d510.png)
Ты должен накинуть на свой компонент id, внутри компонента у View его можно убрать. Это не баг.

**Comment by Alkanores** [comment]
> ![image](https://user-images.githubusercontent.com/26293210/110854787-861b3e80-82c6-11eb-8ac6-8c9b1016d510.png)
> Ты должен накинуть на свой компонент id, внутри компонента у View его можно убрать. Это не баг.
> 
> `function App() { return ( <Epic activeStory="fff"> <TestView id="fff" /> </Epic> ); }`

Спасибо!
