### ISSUE TITLE
[Feature] Добавить компонент Rate

### ISSUE THREAD

**Issue by Alkanores** [VKCOM/VKUI#1463]
Реализовать компонент <Rate/> по примеру компонентов из библиотек Ant Design и Material UI:

https://ant.design/components/rate/
https://material-ui.com/ru/components/rating/

**Comment by ArthurStam** [comment]
@wayshev что скажешь?

**Comment by Alkanores** [comment]
> @wayshev что скажешь?

Видимо, ничего не скажет.

**Comment by ArthurStam** [comment]
Решили, что такой компонент сейчас в библиотеке не нужен. Предлагаю реализовать самим в том месте, где он понадобился.
