### ISSUE TITLE
[Bug] Баг с иконками

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1464]
Хз что вы там намудрили, на название не обращайте, код один и тот же в панелях.

Было
"@vkontakte/icons": "^1.53.0",
    "@vkontakte/vk-bridge": "^2.4.1",
    "@vkontakte/vkjs": "^0.6.0",
    "@vkontakte/vkui": "^v4.0.8",
![image](https://user-images.githubusercontent.com/26293210/111082349-d1c52680-8518-11eb-9af0-09bcaeb741a5.png)

Стало
"@vkontakte/icons": "^1.83.0",
    "@vkontakte/vk-bridge": "^2.4.1",
    "@vkontakte/vkjs": "^0.6.0",
    "@vkontakte/vkui": "^4.3.0",
![image](https://user-images.githubusercontent.com/26293210/111082392-0d5ff080-8519-11eb-97ec-2d2efb5cd546.png)

**Comment by SkyGopnik** [comment]
Было
![image](https://user-images.githubusercontent.com/26293210/111082418-31233680-8519-11eb-9639-b1bab337c8d0.png)

Стало
![image](https://user-images.githubusercontent.com/26293210/111082428-426c4300-8519-11eb-84ab-fd29af3791b4.png)

**Comment by gbowsky** [comment]
Привет, а что за компонент используешь? Для кнопки назад у нас есть `<PanelHeaderBack/>`

**Comment by SkyGopnik** [comment]
Да обычную свою обёртку 
![image](https://user-images.githubusercontent.com/26293210/111082493-adb61500-8519-11eb-86e5-7e85b0b6e04b.png)

**Comment by SkyGopnik** [comment]
Тут же дело не в этом, с размерами иконки что-то стало

**Comment by SkyGopnik** [comment]
На круге это не заметно будет, то есть у меня есть иконка шестерёнки в профиле, с ней всё ок стало, иконки которые ширина != высота поплыли

**Comment by SkyGopnik** [comment]
Баг кстати именно VKUI, т.к. при откате на "@vkontakte/vkui": "^v4.0.8", всё опять стало в норме

**Comment by ewgenius** [comment]
`Icon24Back` проблема не воспроизводится (icons 1.83.0, vkui 4.3.0) - https://codesandbox.io/s/inspiring-jang-ivo6w?file=/src/App.tsx:382-392

<img width="686" alt="CleanShot 2021-03-14 at 23 32 02@2x" src="https://user-images.githubusercontent.com/827338/111083252-a85ac980-851d-11eb-9c2c-2c4ce5d18f3a.png">

`Icon28ChevronBack` (и любые другие иконки с высота!=ширина)

- если надо, у иконок есть пропсы width, height чтобы проставить размеры отличающиеся от дефолтных

<img width="864" alt="CleanShot 2021-03-14 at 23 37 33@2x" src="https://user-images.githubusercontent.com/827338/111083362-477fc100-851e-11eb-87aa-4e7cea624e51.png">

- сама по себе Icon28ChevronBack ведет себя одинаково как на vkui 4.0.8 + icons 1.53.0 так и 4.3.0 + 1.83.0:

| | |
|-|-|
| https://codesandbox.io/s/falling-leftpad-0oib7 | https://codesandbox.io/s/magical-darkness-li7ez |
| <img width="652" alt="CleanShot 2021-03-14 at 23 40 58@2x" src="https://user-images.githubusercontent.com/827338/111083454-c07f1880-851e-11eb-9218-1df3a9e6d42a.png"> | <img width="669" alt="CleanShot 2021-03-14 at 23 41 52@2x" src="https://user-images.githubusercontent.com/827338/111083472-df7daa80-851e-11eb-8a3e-c24bc739aa93.png"> | 

> Хз что вы там намудрили

Смотри, не намудрил ли ты у себя, либо предоставь более подробный пример с воспроизведением бага

**Comment by SkyGopnik** [comment]
Хз в чём прикол. У меня не накидывается вот этот стиль
![image](https://user-images.githubusercontent.com/26293210/111087899-63429180-8535-11eb-847e-2e0f0e2fd18f.png)

**Comment by SkyGopnik** [comment]
На главной панели он есть, а вот на других уже нет.

**Comment by SkyGopnik** [comment]
Вы уверены что ничего со стилями не делали? Потому что у меня ничего не переопределяется.

**Comment by SkyGopnik** [comment]
Проверьте в Epic, у меня не накладываются новые стили vkuiIcon, это не может просто так происходить.
![image](https://user-images.githubusercontent.com/26293210/111088425-275cfb80-8538-11eb-9c6b-031d2493184c.png)

**Comment by fedorov-xyz** [comment]
@SkyGopnik, подскажи, как ты импортируешь иконки?
Из главного файла (`import {} from '@vkontakte/icons'` или из `'@vkontakte/icons/dist...'`?

**Comment by ewgenius** [comment]
> @SkyGopnik, подскажи, как ты импортируешь иконки?
> Из главного файла (`import {} from '@vkontakte/icons'` или из `'@vkontakte/icons/dist...'`?

судя по всему из dist импорты
@SkyGopnik поменяй импорт на `'@vkontakte/icons'` если это оно

<img width="766" alt="CleanShot 2021-03-15 at 10 20 39@2x" src="https://user-images.githubusercontent.com/827338/111117128-25b32800-8578-11eb-8e74-2e0b15455edd.png">

**Comment by SkyGopnik** [comment]
+, проблема действительно в этом, спасибо) Буду тогда сейчас тыкать в модалки
