### ISSUE TITLE
[Bug] Краш при открытии модалки

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1465]
Моя рабочая сборка
"@vkontakte/icons": "^1.53.0",
"@vkontakte/vkui": "^v4.0.8",

Сборка на которую я обновился
"@vkontakte/icons": "^1.83.0",
"@vkontakte/vkui": "^4.3.0",

Ловим краш при всё той же логике открытии модалки
![image](https://user-images.githubusercontent.com/26293210/111082702-bb1fcf00-851a-11eb-8059-8958240e12cb.png)

**Comment by SkyGopnik** [comment]
Как я понимаю он появился после версии 4.1.0, странно что никто не заметил.
`ModalRoot: исправлено закрытие и одновременный захват модалок`

**Comment by gbowsky** [comment]
Пример воспроизведения?

**Comment by SkyGopnik** [comment]
Да просто состоянии модалка с null на нормальную попробуй сменить, у меня просто всё на Redux завязано и времени нет всё это воспроизводить ради 1 компонента в 4.3.0

**Comment by ewgenius** [comment]
> Как я понимаю он появился после версии 4.1.0, странно что никто не заметил.
ModalRoot: исправлено закрытие и одновременный захват модалок

4.1.0, 4.2.0, 4.2.1 проверял?

> Да просто состоянии модалка с null на нормальную попробуй сменить, у меня просто всё на Redux завязано и времени нет всё это воспроизводить ради 1 компонента в 4.3.0

https://codesandbox.io/s/eager-bogdan-b0m4c?file=/src/App.tsx

ModalPage, ModalCard меняется с null на id, проблема не воспроизводится

Судя по ошибке у тебя не определилась указанная модалка при инициализации, либо id неправильный, либо ее вообще там нет
Хотя бы покажи как ModalRoot/ModalCard инициализируешь, как прокидываются id модалок, а в идеале пример с воспроизведением бага

**Comment by SkyGopnik** [comment]
Хз. Магия значит какая-то.
