### ISSUE TITLE
[Bug] Хук usePlatform на десктопе выдаёт значение android => Интерфейс не адаптируется под разные платформы

### ISSUE THREAD

**Issue by CapUlDis** [VKCOM/VKUI#1473]
**Описание**
Хук usePlatform всё время выдаёт android на десктопе, из-за чего интерфейс не меняется в зависимости от платформы.

**Версия библиотеки**
v.4.3.0

**Шаги воспроизведения**
1. Взять любой компонет библиотеки, который по-разному выглядит в зависимости платформы;
2. Посмотреть на мобильной версии;
3. Посмотреть на десктопной и увидеть, что интерфейс не изменился, а остался такой же как на мобильной.

**Скриншоты**
![image](https://user-images.githubusercontent.com/54175504/111333397-b4f93200-8683-11eb-8235-ac147736c1e8.png)
На скриншоте видно, что компонент PanelHeader ведёт себя так, как он должен вести себя на мобильном устройстве.
Также при выведении в консоль значения переменной platform, полученной из хука usePlatform, видим значение android.

**Пример с воспроизведением**
https://codesandbox.io/s/vkui-boilerplate-forked-q8rem?file=/src/index.js&resolutionWidth=1400&resolutionHeight=800

**Comment by ewgenius** [comment]
iOS, Android автоматически определяются на мобильных устройствах, если не определена (в том числе и на десктопе) - по умолчанию используется Android

> из-за чего интерфейс не меняется в зависимости от платформы

Уточните какие платформы вы имеете в виду?

> Посмотреть на десктопной и увидеть, что интерфейс не изменился, а остался такой же как на мобильной

Для адаптации интерфейса mobile/desktop используется не платформа а хук `useAdaptivity` либо HOC `withAdaptivity` откуда можно получить всю информацию о размерах экрана, наличии курсора на устройстве и тд.
Более подробно можно прочитать здесь https://vkcom.github.io/VKUI/#!/Adaptivity

**Comment by CapUlDis** [comment]
> Уточните какие платформы вы имеете в виду?
Я имею ввиду не меняется с мобильной на десктопную.

Неправильно выразился, извините. Я имел ввиду не меняется дизайн компонента на десктопной версии приложения. На примере копонента PanelHeader: 
1. Дизайн на андроиде выглядит так:
![image](https://user-images.githubusercontent.com/54175504/111484943-4087c700-8747-11eb-968f-74ea48b42e69.png)
2. Дизайн на десктопе должен выглядить так:
![image](https://user-images.githubusercontent.com/54175504/111485097-61e8b300-8747-11eb-8221-4ee02d1f96d3.png)

Вот у меня не получается получить десктопный вариант. И в коде компопента PanelHeader видно, что вид заголовка зависит от хука usePlatform:
![image](https://user-images.githubusercontent.com/54175504/111485488-b55b0100-8747-11eb-80e7-ef66f6d16cd7.png)

Когда я консолю platform на дескотпе у меня показывает андроид, из-за чего я сделал вывод, что хук работает некорректно.

**Comment by ewgenius** [comment]
Это не совсем полноценный desktop, сейчас это для случая отображения внутри vkcom

**Comment by CapUlDis** [comment]
> Это не совсем полноценный desktop, сейчас это для случая отображения внутри vkcom

А как получить полноценный? Когда прикручиваю app к сайту, у меня не происходит смена дизайна. Необходимо деплоить app?
![image](https://user-images.githubusercontent.com/54175504/111486727-c9ebc900-8748-11eb-8d91-05956dd39ef7.png)

**Comment by Roman-Shubnikov** [comment]
Похожая ситуация была у меня #1279.
Можно самому любым способом определить платформу, а затем завернуть приложение в `ConfigProvider` и передать ему произвольный параметр `platform`. Так я временно починил этот баг.

**Comment by ewgenius** [comment]
> а затем завернуть приложение в ConfigProvider и передать ему параметр platform. Так я временно починил этот баг.

Да, с этим пока только так, подумаем как яснее сделать работу с vkcom

Этот тикет пока закрою, так как идентичен #1279
