### ISSUE TITLE
[Feature] Добавить description для Checkbox

### ISSUE THREAD

**Issue by ArthurStam** [VKCOM/VKUI#1479]
По аналогии с компонентом Radio

**Comment by ArthurStam** [comment]
@wayshev нужно ревью. Вот тут накидал пример: https://orueg.csb.app/

**Comment by Lihachyov** [comment]
@ArthurStam сможем сделать один-в-один как в Radio? Если получилось как там, то ревью не нужен

У них абсолютно идентичная вёрстка должна получиться, единственное что отличается это вместо иконки кружка галочка чекбокса
