### ISSUE TITLE
[Bug] DatePicker не имеет фиксированного размера и выходит за пределы контейнера

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1484]
https://vkcom.github.io/VKUI/#datepicker

Выбираем какой-нибудь большой месяц, например Февраля, селект становится больше и выталкивает весь контент вправо, тем самым выходя за главный контейнер.

**Comment by SkyGopnik** [comment]
![image](https://user-images.githubusercontent.com/26293210/111921821-bf626400-8aa7-11eb-8395-6b1bc036e8b1.png)
![image](https://user-images.githubusercontent.com/26293210/111921825-c4bfae80-8aa7-11eb-8ce2-b90b3e7c908d.png)

**Comment by gbowsky** [comment]
[Пофикшено](https://github.com/VKCOM/VKUI/releases/tag/v4.4.0).
