### ISSUE TITLE
Область Tappable

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1485]
Почему она ставится не через абсолютное позиционирование и кривится от любой фигни?
![image](https://user-images.githubusercontent.com/26293210/111951693-0fb3e300-8af5-11eb-96ed-5775230d8d26.png)

**Comment by ewgenius** [comment]
@SkyGopnik подходи к заведению тикетов конструктивнее

Пример кода с воспроизведением, как подключаешь иконку, как делаешь кнопку.
Хотя бы какие компоненты используешь

---

VKUI 4.3.0, icons 1.86.0, SimpleCell + IconButton - все работает как надо
https://codesandbox.io/s/default-example-forked-qd9ys?file=/example.tsx

<img width="803" alt="CleanShot 2021-03-22 at 10 15 27@2x" src="https://user-images.githubusercontent.com/827338/111953352-8a7dfd80-8af7-11eb-88b3-31f280db3659.png">

**Comment by SkyGopnik** [comment]
Ну, это пока не тикет, просто вопрос, но баг заключается в том что у меня есть Card, в котором выставлены padding: 12px например, в нём SimpleCell без боковых отступов. Tappable иконки ломается.

**Comment by ewgenius** [comment]
> в нём SimpleCell без боковых отступов

То есть ты кастомными стилями переопределил отступы?
В чем же тут баг библиотеки, если ты ломаешь дефолтные стили одного компонента, и кладешь в другой компонент с кастомными стилями?

Я здесь могу предложить только стилизовать кнопку и иконку чтобы под твой случай работало, в VKUI варианта SimpleCell без отступов нет, а SimpleCell внутри Card тоже весьма сомнительно

Либо если это какой-то широко используемый случай Card + SimpleCell + IconButton, открыть фича реквест с описанием

---

Если уж совсем придираться, то у меня даже с кастомными отступами внутри карточки Tappable не ломается (хоть и вылезает за границы SimpleCell, но это опять же поломанные отступы ячейки)

<img width="1370" alt="CleanShot 2021-03-22 at 10 39 32@2x" src="https://user-images.githubusercontent.com/827338/111955835-147b9580-8afb-11eb-99f4-f4980a2cd49c.png">
