### ISSUE TITLE
[Bug] PanelHeaderContext при рендере вызывает событие onClose на платформе VKCOM

### ISSUE THREAD

**Issue by danyarubtsov** [VKCOM/VKUI#1487]
**Описание**
на платформе VKCOM PanelHeaderContext сразу же после рендера вызывает событие onClose, на любых других platform ошибка не воспроизводится

**Версия библиотеки**
4.3.0
**Шаги воспроизведения**
В целом все должно быть понятно в описании, просто вызовите рендер PanelHeaderContext 

**Ожидаемое поведение**
onClose должен вызываться только при закрытии, а не при рендере

И ещё хотел бы дополнить, что при открытом PanelHeaderContext работает скроллинг, что не есть хорошо.

**Comment by ub1x** [comment]
Ошибка тут: https://github.com/VKCOM/VKUI/blob/eb71a062007883f6040a1832142db0c3cfa91620/src/components/PanelHeaderContext/PanelHeaderContext.tsx#L44

зачем этот код здесь?

**Comment by ewgenius** [comment]
Спасибо за репорт!

Воспроизводится независимо от платформы https://codesandbox.io/s/default-example-forked-tzs84?file=/example.tsx

**Comment by ub1x** [comment]
> Спасибо за репорт!
> 
> Воспроизводится независимо от платформы https://codesandbox.io/s/default-example-forked-tzs84?file=/example.tsx

Не так выразился, срабатывает при viewWidth >= ViewWidth.SMALL_TABLET, можно проверить прямо в твоей ссылочке сузив фрейм, подразумеваю беда тут: this.props.viewWidth >= ViewWidth.SMALL_TABLET;

**Comment by inomdzhon** [comment]
> на платформе VKCOM PanelHeaderContext сразу же после рендера вызывает событие onClose, на любых других platform ошибка не воспроизводится

@danyarubtsov с версии `v4.3.0` компонент `PanelHeaderContext` претерпел изменения, из-за чего сейчас этот issue не воспроизводится (ниже прикрепляю видео)

https://user-images.githubusercontent.com/5850354/166963795-71ffee12-0354-4722-a639-1239823f145e.mov

Сравнил текущую версию компонента с `v4.3.0`, вижу, что переписал на функциональный компонент и поправили предикаты на установку обработчика на клик.

> И ещё хотел бы дополнить, что при открытом PanelHeaderContext работает скроллинг, что не есть хорошо.

Починили тут https://github.com/VKCOM/VKUI/pull/2421 =) но на десктопе скролл остаётся

---

Я пока закрою issue, но если я не так воспроизвёл и проблема всё ещё актуальна, то переоткрой issue, пожалуйста.

И очередное спасибо за репорт 😌

**Comment by flangapp** [comment]
версия 4.37.4, проблема все еще актуальна
https://codesandbox.io/s/default-example-forked-r8kmkw
