### ISSUE TITLE
Научиться скрывать Tabbar в Epic

### ISSUE THREAD

**Issue by ArthurStam** [VKCOM/VKUI#149]
Сейчас Tabbar всегда показывается, даже в случае открытия модальных окон. В нативных клиентах модальные окна всегда открываются поверх.

**Comment by TheRealFaner** [comment]
По мне это не фича, а баг, потому что в Андроид приложении этот момент работает должным образом!

**Comment by ciricc** [comment]
3 версия вышла, а таббары все еще нельзя скрыть :(

**Comment by ewgenius** [comment]
Исправлено в версии v4
- модальное окно отображается поверх TabBar - [codesandbox](https://codesandbox.io/s/vkui-epic-with-modal-j1dg2?file=/src/App.tsx&resolutionWidth=320&resolutionHeight=675)
- tabbar опционален на ширких экранах: https://vkcom.github.io/VKUI/#!/Epic (#1237)
