### ISSUE TITLE
[Bug] CardScroll не работает в модальном окне

### ISSUE THREAD

**Issue by Keller18306** [VKCOM/VKUI#1494]
**Описание**
Не работает CardScroll в модальном окне на мобильной версии

**Версия библиотеки**
4.3.0

**Шаги воспроизведения**
Открыть https://55g8y.csb.app/ с телефона и попробовать перемещать карды

**Ожидаемое поведение**
Карды должны перемещаться, как в Panel https://vkcom.github.io/VKUI/#cardscroll

**Скриншоты**
https://youtu.be/r47gPZGc_RM

**Пример с воспроизведением**
https://codesandbox.io/s/vkui-boilerplate-forked-55g8y

**Comment by SkyGopnik** [comment]
Замечу, что баг довольно серьёзный - не работает любой скролл в модалке из за конфликта с закрытием свайпом.

**Comment by hoxtonhero** [comment]
Есть новости?

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
