### ISSUE TITLE
[Feature] проп disabled для PullToRefresh

### ISSUE THREAD

**Issue by land47** [VKCOM/VKUI#1501]
Нужна возможность отключить его для десктопа

**Comment by ewgenius** [comment]
Зачем отключать, если его можно не использовать для десктопа?

```tsx

const content = (
  <Group>
    ...
  </Group>
)

return (
  ...
  {isDesktop
    ? content
    : <PullToRefresh onRefresh={...} isFetching={...}>
        {content}
      </PullToRefresh
  }
);

```

**Comment by SkyGopnik** [comment]
Выглядит перегружено, disabled бы больше подошёл мне кажется

> Зачем отключать, если его можно не использовать для десктопа?
> 
> ```tsx
> const content = (
>   <Group>
>     ...
>   </Group>
> )
> 
> return (
>   ...
>   {isDesktop
>     ? content
>     : <PullToRefresh onRefresh={...} isFetching={...}>
>         {content}
>       </PullToRefresh
>   }
> );
> ```

**Comment by ewgenius** [comment]
> Выглядит перегружено, disabled бы больше подошёл мне кажется
> 
> 
> 
> > Зачем отключать, если его можно не использовать для десктопа?
> 
> > 
> 
> > ```tsx
> 
> > const content = (
> 
> >   <Group>
> 
> >     ...
> 
> >   </Group>
> 
> > )
> 
> > 
> 
> > return (
> 
> >   ...
> 
> >   {isDesktop
> 
> >     ? content
> 
> >     : <PullToRefresh onRefresh={...} isFetching={...}>
> 
> >         {content}
> 
> >       </PullToRefresh
> 
> >   }
> 
> > );
> 
> > ```
> 
> 
> 
> 

Если компонент исключительно для мобайла, зачем перегружать дерево и рендерить его впустую, пускай и "отключенный"?
Делать disabled чтобы компонент вернул детей без функционала, такое себе решение, на мой взгляд.
Плюс я не уверен что он перестанет полностью реагировать на изменение пропсов (isFetching) и вызывать ререндер без дополнительного усложнения внутри - компонент сложный, с кучей стейта и хендлерами на документе, все это придется завязывать на изменение disabled.
