### ISSUE TITLE
[Bug] Нельзя выбрать элемент в Select, если за ним находится FormItem с status=error

### ISSUE THREAD

**Issue by xpyctumo** [VKCOM/VKUI#1504]
**Описание**
Фокус курсора наводится на инпут, который находится за дропдауном

**Версия библиотеки**
4.0.7

**Шаги воспроизведения**
1. Открыть https://vk.com/test_vkapp
2. Раскрыть дропдаун с методами
3. Выбрать событие **ShowStoryBox**
4. Дождаться, пока форма с полями соберется
5. Снова раскрыть дропдаун с методами

**Ожидаемое поведение**
Фокус идет в первую очередь на элемент сверху (то, что в дропдауне)

https://user-images.githubusercontent.com/30053565/113181530-920d7700-925a-11eb-991d-d55e7c5b52e4.mov

**Comment by ArthurStam** [comment]
Будет доступно со следующей версии.
