### ISSUE TITLE
[Feature] Св-во disabled для Card

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1506]
Было бы здорово, если бы это было из коробки, только мне кажется opacity: .4 как на инпутах, кнопках и т.д, перебор, в своем кейсе я поставил .5
![Снимок экрана 2021-04-01 в 10 06 59](https://user-images.githubusercontent.com/26293210/113256583-09322200-92d2-11eb-9dfa-a0ba67326c85.png)

**Comment by SkyGopnik** [comment]
Могу PR сам закинуть если норм

**Comment by ArthurStam** [comment]
@wayshev нужно твоё мнение, в текущих гайдах не нашёл.

**Comment by Lihachyov** [comment]
Для больших элементов мы обычно используем opacity 0.6, предлагаю сделать так

И будет по красоте 👍

**Comment by ArthurStam** [comment]
@SkyGopnik сделаешь PR?

**Comment by SkyGopnik** [comment]
Оки :3

**Comment by ArthurStam** [comment]
Тут тоже лейбл design уже не актуален.

**Comment by ArthurStam** [comment]
@SkyGopnik а тут речь про `Card` или `ContentCard`? Просто у `Card` нет состояния `disabled`, у `ContentCard` — есть

**Comment by SkyGopnik** [comment]
> @SkyGopnik а тут речь про `Card` или `ContentCard`? Просто у `Card` нет состояния `disabled`, у `ContentCard` — есть

Вообще речь шла об обычном Card, но даже у ContentCard я не вижу св-ва disabled или оно никак не влияет на дизайн?

**Comment by ArthurStam** [comment]
Обычный Card — это просто контейнер для контента. Внутри ContentCard есть Tappable. Там можно реализовать disabled

**Comment by thoughtspile** [comment]
ничто не мешает обычному Card кликаться

**Comment by ArthurStam** [comment]
Я запутался(

**Comment by SkyGopnik** [comment]
Тут был смысл именно в дизайне, а не чтобы просто событие не вызывалось *грустный смайлик*

> Обычный Card — это просто контейнер для контента. Внутри ContentCard есть Tappable. Там можно реализовать disabled

**Comment by ArthurStam** [comment]
@SkyGopnik Если у тебя в проекте используется обычный Card, то, имхо, opacity и disabled на него стоит навесить самостоятельно. Если ContentCard, то там disabled стилизуем мы (щас стилизации этого состояния нет). Идёт?
