### ISSUE TITLE
[Feature] Обновить Small Button

### ISSUE THREAD

**Issue by OlliGalvita** [VKCOM/VKUI#1508]
Обновился стиль шрифта у Small Button с иконкой. Заменили капс на Subhead Medium.
![image](https://user-images.githubusercontent.com/81754974/113291414-ace3f800-92fb-11eb-87f1-034d396dba7d.png)

**Comment by ArthurStam** [comment]
Обновленные кнопки можно посмотреть тут: https://vkcom.github.io/VKUI/pull/1510/#/Button
