### ISSUE TITLE
Как использовать withModalRootContext и updateModalHeight в хуках?

### ISSUE THREAD

**Issue by Keller18306** [VKCOM/VKUI#1511]
Пример есть тут https://vkcom.github.io/VKUI/#modalrootadaptive , но он для классов, когда я использую хуки. Также там используют два файла, когда мне нужно один.
![image](https://user-images.githubusercontent.com/23178771/113363533-c7e55500-9359-11eb-8e87-464773e64cff.png)

Помогите пожалуйста :)

**Comment by Keller18306** [comment]
https://codesandbox.io/s/cool-bush-k061w
![image](https://user-images.githubusercontent.com/23178771/113367178-02ec8600-9364-11eb-927b-9c3a81e450eb.png)

**Comment by ArthurStam** [comment]
Функциональный компонент ведь точно так же может быть обернуть в HOC.

**Comment by fedorov-xyz** [comment]
```ts
import { ModalRootContext } from '@vkontakte/vkui';

const { updateModalHeight } = useContext(ModalRootContext);
```

**Comment by Keller18306** [comment]
Не получается https://codesandbox.io/s/billowing-frog-mv5vn?file=/src/index.js

**Comment by Keller18306** [comment]
Может кто не понял:
Я хочу чтобы по нажатии "Первый" и "Второй" заменялся код контента, который я указал в функциях. При вызове updateModalHeight ничего не происходит, dynamicContentHeight указано. Вероятнее всего я что-то не так делаю....
https://youtu.be/C9hPJe94ys4

**Comment by ArthurStam** [comment]
Перевесь свойство `dynamicContentHeight` вот сюда `<WITHCONTEXT dynamicContentHeight id="test" />`. Иначе ModalRoot не может до него добраться.

**Comment by Keller18306** [comment]
> Перевесь свойство `dynamicContentHeight` вот сюда `<WITHCONTEXT dynamicContentHeight id="test" />`. Иначе ModalRoot не может до него добраться.

Спасибо, заработало!

**Comment by Keller18306** [comment]
Оставлю рабочий пример: https://codesandbox.io/s/billowing-frog-mv5vn
