### ISSUE TITLE
[Bug] IconButton имеет кривую область Tappable

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1515]
Заходим в доку https://vkcom.github.io/VKUI/#group
Опускаемся до Последняя активность, где SimpleCell
`<SimpleCell 
          after={<IconButton><Icon16MoreVertical /></IconButton>} 
          description="Санкт-Петербург, Россия" 
          before={<Avatar size={32} mode="app" />}
        >
          VK · Приложение для iPhone
        </SimpleCell>`
![image](https://user-images.githubusercontent.com/26293210/113482754-c0809180-94a8-11eb-9468-efd01ffb3963.png)

**Comment by ArthurStam** [comment]
@wayshev можешь подтвердить, что криво?

**Comment by SkyGopnik** [comment]
Так у вас на других иконках ровно всё)
![image](https://user-images.githubusercontent.com/26293210/113575553-b71d3380-9626-11eb-9b46-aefe804523fd.png)
Просто из за того что Icon16MoreVertical имеет не одинаковую высоту и ширину, видимо происходит так.

**Comment by ArthurStam** [comment]
Да, я понимаю, почему так происходит. Я пытаюсь понять, баг ли это.

**Comment by Lihachyov** [comment]
<img width="801" alt="Screenshot 2021-04-26 at 20 11 08" src="https://user-images.githubusercontent.com/3250391/116123322-8da67380-a6cb-11eb-9648-b330418358b9.png">
@ArthurStam это ОК, но форма немного не та. Тут получился овал, а должен быть прямоугольник с закруглёнными краями. [Здесь](https://www.figma.com/file/lLXmjJhnJa4OhgZXzcNJD9/?node-id=3220%3A0) описано
