### ISSUE TITLE
[Вопрос] ActionSheet

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1516]
Для чего ActionSheet нужно св-во toggleRef?

**Comment by ArthurStam** [comment]
Это ссылка на dom-элемент, рядом с которым должен открыться [десктопный](https://github.com/VKCOM/VKUI/blob/master/src/components/ActionSheet/ActionSheet.tsx#L77-L80) ActionSheet.

**Comment by SkyGopnik** [comment]
![image](https://user-images.githubusercontent.com/26293210/113576326-0a43b600-9628-11eb-8bf0-ffdb133e4fa4.png)
Баг получается? Или я что-то не так делаю

**Comment by ewgenius** [comment]
Есть пример https://vkcom.github.io/VKUI/#!/ActionSheet
Либо вот на хуках https://codesandbox.io/s/actionsheet-example-etgee?from-embed=&file=/example.tsx

> `toggleRef={React.createRef().current}`

Про то как пользоваться рефами - https://ru.reactjs.org/docs/refs-and-the-dom.html

**Comment by SkyGopnik** [comment]
Так ничего не изменится если я вынесу рефку в конструктор.

**Comment by SkyGopnik** [comment]
Нашёл в чём трабл, сорьк.
