### ISSUE TITLE
[Bug] ActionSheetItem вызывает onClose два раза, а то и больше

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1518]
**Описание**
Если использовать св-во selectable на ActionSheetItem, onClose заданный на ActionSheet вызывается больше одного раза

**Версия библиотеки**
4.4.0

**Пример с воспроизведением**
https://vkcom.github.io/VKUI/#actionsheet
https://pastebin.com/DfJhrM9j

**Comment by SkyGopnik** [comment]
@ArthurStam а двойной вызов onClick при selectable у Cell это фича?

**Comment by SevereCloud** [comment]
v4.28.1 - не воспроизводится

Насчет двойного вызова у Cell #2376

**Comment by SkyGopnik** [comment]
Прикол что-ли какой то фиксить и писать что не воспроизводится?

**Comment by SevereCloud** [comment]
Видимо где-то, когда то пофиксили, а issue не закрыли
