### ISSUE TITLE
[Enhancement] `PanelHeader`: переименовать `left`/`right` в `before`/`after`

### ISSUE THREAD

**Issue by worldwidebaby** [VKCOM/VKUI#1519]
Рефакторим **PanelHeader**: 
- [ ] добавляем проп `before`
- [ ] добавляем проп `after`
- [ ] депрекейтим проп `left` в пользу `before`
  - [ ] добавляем варнинг
- [ ] депрекейтим проп `right` в пользу `after`
  - [ ] добавляем варнинг

Выкидывать `left` и `right` в v5 будем в рамках https://github.com/VKCOM/VKUI/issues/1522

**Comment by ArthurStam** [comment]
Исторически сложилось.

**Comment by land47** [comment]
Не стоит перейти к единому неймингу подобных пропсов?
