### ISSUE TITLE
iOS: PanelHeader уезжает наверх при открытии клавиатуры

### ISSUE THREAD

**Issue by Aaxenon** [VKCOM/VKUI#152]
При открытии клавиатуры PanelHeader уезжает наверх, накладываясь на статус-бар, в iOS.
![nf4gyuaf1r8](https://user-images.githubusercontent.com/9284067/49931579-3e838d80-fed8-11e8-92af-e0dbde08bf62.jpg)
![yfshigbcda8](https://user-images.githubusercontent.com/9284067/49931577-3e838d80-fed8-11e8-9de4-7761f03f7622.jpg)

Проблема воспроизвелась на:
iPhone 5 + iOS 10
iPhone 5s + iOS 10
iPhone 6 + iOS 12

На iPhone 7 + iOS 12 PanelHeader тоже сдвигается, но на совсем незначительную величину, и не наезжает на статус-бар.

**Comment by ArthurStam** [comment]
Известно. Ясно почему происходит. Неясно как фиксить. Закрываю тикет.
