### ISSUE TITLE
[Bug] Пропали зазоры между иконкой и текстом в SimpleCell и CellButton

### ISSUE THREAD

**Issue by alxgrn** [VKCOM/VKUI#1528]
**Описание**
При помещении иконки в параметр before в компоненте SimpleCell и CellButton пропали зазоры между иконкой и текстом (см. скриншот из проекта и документации).

**Версия библиотеки**
"@vkontakte/vkui": "4.4.0"

![2021-04-08_13-38-46](https://user-images.githubusercontent.com/6928795/114013412-2c2f7980-9870-11eb-9684-e96fee498e5c.png)
![2021-04-08_13-40-44](https://user-images.githubusercontent.com/6928795/114013457-3782a500-9870-11eb-8c23-af787929539d.png)

**Comment by ArthurStam** [comment]
То есть в проекте воспроизводится, а в доке — нет? Если так, то можешь накидать пример с воспроизведением, используя этот шаблон? https://codesandbox.io/s/vkui-boilerplate-oj149

**Comment by alxgrn** [comment]
Я там не зарегистрирован, поэтому не знаю как сохранить, но вот код, который воспроизводит

![2021-04-08_15-48-41](https://user-images.githubusercontent.com/6928795/114029517-3fe3db80-9882-11eb-88f6-582adcc44968.png)

**Comment by ArthurStam** [comment]
https://codesandbox.io/s/elegant-feather-edjg5 вот тут не вижу проблемы. В доке тоже. Пока не знаю, чем помочь.

**Comment by alxgrn** [comment]
Нашел причину: раньше все работало без AppRoot вокруг View, а теперь так не может.
