### ISSUE TITLE
Некорректно рассчитывается высота контента Panel при добавлении FixedLayout top/bottom

### ISSUE THREAD

**Issue by lashevskiy** [VKCOM/VKUI#153]
Содержимое панели скрывается сверху за FixedLayout (top) и снизу за FixedLayout (bottom). По всей видимости необходимо выставлять margin-top равный высоте FixedLayout, а также увеличивать общую высоту контента панели также на высоту FixedLayout. Пример на котором воспроизводится проблема: 
`<View activePanel="main">
    <Panel id="main">
        <PanelHeader>VKUI</PanelHeader>
        <FixedLayout vertical="top">
            <Search />
        </FixedLayout>
        <div>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            123123
            <br/>
            <br/>
            222
            <br/>
            <br/>
            11111
            <br/>
        </div>
        <FixedLayout vertical="bottom">
            <Tabs>
                <TabsItem selected={true}>176 сообществ</TabsItem>
                <TabsItem selected={false}>176 сообществ</TabsItem>
            </Tabs>
        </FixedLayout>
    </Panel>
</View>`

**Comment by ArthurStam** [comment]
Нет. Это стандартное поведение блоков с `position: fixed`. Контроль отступов на стороне разработчика.
