### ISSUE TITLE
[Bug] IconButton игнорирует проп Component

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1535]
**Описание**
https://github.com/VKCOM/VKUI/blob/c2042b234982fce3bcf407207deb146de93b3ead/src/components/IconButton/IconButton.tsx#L22

**Версия библиотеки**
v4.5.0

**Comment by ArthurStam** [comment]
Упс. Поправим.

**Comment by ArthurStam** [comment]
Пофиксится в следующем релизе.
