### ISSUE TITLE
[Bug] ModalPage не скроллится на iOS 

### ISSUE THREAD

**Issue by Denior1** [VKCOM/VKUI#1539]
**Описание**
ModalPage не скроллится на iOS если выставлен settlingHeight={100}, что бы активировался скролл нужно в шапке модалки немного свайпнуть и отпустить

**Версия библиотеки**
4.5.0 и на других 4.*.*

**Шаги воспроизведения**
1. Открыть модалку с settlingHeight={100},
2. Попробовать скроллить

**Ожидаемое поведение**
ModalPage будет скроллиться 

**Скриншоты**
https://f075e36f-c490-4021-9a0d-65d1ec7991da.selcdn.net/modalpage.MP4

**Пример с воспроизведением**
https://codesandbox.io/s/silly-elion-tpqp8

**Comment by inomdzhon** [comment]
Спасибо за PR 🙏 

Фикс доступен с `v4.33.2`
