### ISSUE TITLE
При использовании Epic не отображается FixedLayout (vertical="bottom") на мобильном устройстве

### ISSUE THREAD

**Issue by lashevskiy** [VKCOM/VKUI#154]
При использовании Epic не отображается FixedLayout (vertical="bottom") на мобильном устройстве при этом в браузере все ок.

**Comment by MaxSvargal** [comment]
+1, анимация переключения Root внутри Epic работает некорректно. tabbar пропадает в бОльшинстве случаев. Воспроизводится во всех десктопных браузерах в т.ч. на мобильных.

**Comment by fedorov-xyz** [comment]
> При использовании Epic не отображается FixedLayout (vertical="bottom") на мобильном устройстве при этом в браузере все ок.

Исправили это в `2.16.6`. Теперь на iOS 10, в том числе на iPhone 5, `<FixedLayout vertical="bottom" />` отображается корректно. Плюс, у `<Panel />` в `<Epic />` снизу исправили отсутствующий внутренний отступ.

Напоминаю, что при использовании `<FixedLayout />` вы сами должны определять дополнительные отступы у контента панели.
