### ISSUE TITLE
[Bug] CustomSelect игнорирует defaultValue

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1543]
**Описание**
Почему-то логика обработки defaultValue вынесена в Select:

https://github.com/VKCOM/VKUI/blob/78f4a56c22787087f627f81c9712cc1d12f44a94/src/components/Select/Select.tsx#L13-L15

**Версия библиотеки**
v4.5.0

**Comment by ArthurStam** [comment]
Будет исправлено в следующем релизе.
