### ISSUE TITLE
[Feature] Добавить Icon в SliderSwitch

### ISSUE THREAD

**Issue by danyarubtsov** [VKCOM/VKUI#1549]
SliderSwitchProps.options принимает с себя имя и значение, но структура вполне себе позволяет добавить поддержку и Icon слева от name.
![image](https://user-images.githubusercontent.com/45757192/114972000-36f89880-9e86-11eb-855a-37e9144ae767.png)

**Comment by ArthurStam** [comment]
@wayshev что скажешь?

**Comment by SkyGopnik** [comment]
Так выглядит же не очень...

**Comment by ub1x** [comment]
> Так выглядит же не очень ...

Ну сделаешь красивее, в чем проблема то 🙄

**Comment by ArthurStam** [comment]
Ждём обновлений в Figma, потом можно брать в работу. Fill free to contribute! :)

**Comment by ArthurStam** [comment]
Заменим этот компонент на новый [Segmented control](https://www.figma.com/file/kvjzdHwTDO7Vcrh1VglGQ5/VKUI-iOS-Library?node-id=29209%3A53213)

**Comment by ArthurStam** [comment]
Следите за активностью создания нового компонента тут #2055
