### ISSUE TITLE
[Bug] Radio не focusable

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1552]
**Описание**
Если повесить на Radio required, то при submit'e формы не работает нативный скролл к invalid полю

<img src="https://user-images.githubusercontent.com/11076888/115003160-99698d00-9eb6-11eb-91a4-74f48953987c.png" width="600">

**Версия библиотеки**
v4.5.0

**Comment by ArthurStam** [comment]
Спасибо, изучим и поправим все подобные случаи.

**Comment by BlackySoul** [comment]
https://github.com/VKCOM/VKUI/assets/7431217/01623334-6162-4579-bca4-a479a1807c2c

Похоже, что больше не воспроизводится
