### ISSUE TITLE
[Feature] динамический css-custom-properties для высоты заголовка панели

### ISSUE THREAD

**Issue by denismart** [VKCOM/VKUI#1555]
Сейчас очень неудобно считать высоту контента, из-за того что для ios у <PanelHeader> одна переменная (--panelheader_height_ios: 52px), а для android другая (--panelheader_height_android: 56px)

Хотелось бы динамическую переменную, которая типа --panelheader_default_height, которая будет равна нужной высоте, в зависимости от платформы.

Сейчас приходится лепить велосипеды, дополнительные стили и тд, чтобы считать высоту панели на разных устройствах. Очень неудобно.

Спасибо!

**Comment by BlackySoul** [comment]
Привет! В версии vkui-tokens [4.15.0](https://github.com/VKCOM/vkui-tokens/tree/4.15.0) появился токен `sizePanelHeaderHeight` общий для всех платформ.  Из кода можно обращаться через `--vkui--size_panel_header_height--regular`
