### ISSUE TITLE
[Bug] CustomSelectOption prop option

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1557]
**Описание**
В DOM CustomSelectOption попадает prop option

<img src="https://user-images.githubusercontent.com/11076888/115144116-e470d500-a05b-11eb-97ca-b130d68c16c3.png" width="600">

**Версия библиотеки**
v4.5.0

**Comment by fedorov-xyz** [comment]
Будет исправлено в ближайшем релизе.
