### ISSUE TITLE
[Bug]  На iOS при смене панели прыгает хедер

### ISSUE THREAD

**Issue by r-lubimov-corp-mail-ru** [VKCOM/VKUI#1559]
**Описание**
Прыгает хедер на iOS при переходе назад на панель.
Поломали [здесь](https://github.com/VKCOM/VKUI/pull/1467) 
Вот этой [строкой](https://github.com/VKCOM/VKUI/blob/feature/unstable/view-infinite-transitions/src/components/FixedLayout/FixedLayout.tsx#L108) 

https://user-images.githubusercontent.com/68422265/115214256-02e1d980-a10b-11eb-8626-f407c6ff6a51.mov

**Версия библиотеки**
4.5.0

**Шаги воспроизведения**
1. Перейти с панели, у которой скрол больше экрана, с позиции скрола больше 0
2. Вернуться назад

**Пример с воспроизведением**
Сделать по первому шагу, нужно проверять на iOS, так что наверно мало смысла делать что-то

**Comment by ArthurStam** [comment]
Привет. То есть на 4.4.0 не воспроизводится баг?

**Comment by r-lubimov-corp-mail-ru** [comment]
> Привет. То есть на 4.4.0 не воспроизводится баг?

Воспроизводится

**Comment by ArthurStam** [comment]
Значит, поломали раньше, чем замержили MR, который ты скинул. А у тебя контент панелей кешируется?

**Comment by r-lubimov-corp-mail-ru** [comment]
Ага, в видео которое скинул, намеренно добавил блок высотой 800 пикселей

**Comment by eolme** [comment]
Я хочу напомнить про #1064

**Comment by ArthurStam** [comment]
Добавь пожалуйста пример с воспроизведением, воспользовавшись этим шаблоном. Так нам будет проще понять, где что-то идёт не так.
https://codesandbox.io/s/vkui-boilerplate-oj149

**Comment by r-lubimov-corp-mail-ru** [comment]
Например [так](https://codesandbox.io/s/zealous-leavitt-jwxdj?file=/src/index.js), но проверять надо на iOS, разве это можно как-то в песочнице это сделать?

**Comment by r-lubimov-corp-mail-ru** [comment]
Ребят, выше указана песочница, где можно увидеть как это воспроизводится

**Comment by r-lubimov-corp-mail-ru** [comment]
Все таки кажется, что было и в ранней версии, но есть правда какой-то непонтяный кейз.
В новой стабильно, для себя пока добавил такой фикс `(panelAnimated || isIos)`

**Comment by ArthurStam** [comment]
Исследую в ближайшее время

**Comment by ewgenius** [comment]
> Значит, поломали раньше, чем замержили MR, который ты скинул. А у тебя контент панелей кешируется?

#1467 был залит как раз в 4.4.0, проверил на 4.3.0 - все ок (в сэндбоксе)

Тот фикс был только для Android, косяк в том что iOS я не проверил

> В новой стабильно, для себя пока добавил такой фикс (panelAnimated || isIos)

Это правильный фикс, добавлю в FixedLayout. Все дело в том, что переходы панелей на Android вертикальные и там все работало как надо с фиксом, а на iOS горизонтальные - поэтому оба хедера (на from и to панелях) должны адаптироваться под скролл

**Comment by r-lubimov-corp-mail-ru** [comment]
Там баг все равно есть, но другой, прыгает кнопка снизу, но это не такой крит

**Comment by ewgenius** [comment]
> Там баг все равно есть, но другой, прыгает кнопка снизу, но это не такой крит

Какая кнопка, можешь подробнее описать?
На видео и в сэндбоксе вроде ничего такого не вижу, если это не имеет отношения к PanelHeader, то это отдельный баг

**Comment by ewgenius** [comment]
@r-lubimov-corp-mail-ru обновил пр с фиксом для FixedLayout bottom, вот пример https://codesandbox.io/s/vkui-ios-panel-transition-fix-demo-wnvcz?resolutionWidth=320&resolutionHeight=675
