### ISSUE TITLE
[Bug] iOS Switch отличается от макетов

### ISSUE THREAD

**Issue by wayshev** [VKCOM/VKUI#1560]
https://vkcom.github.io/VKUI/#switch
В реализации неактивный свитч сделан с помощью бордера, в макетах — с фоном
Макет: https://www.figma.com/file/kvjzdHwTDO7Vcrh1VglGQ5/VKUI-iOS-Library?node-id=12248%3A102947

**Comment by ArthurStam** [comment]
Можем пофиксить в рамках #1313
