### ISSUE TITLE
[Bug] DatePicker игнорирует required/не focusable

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1562]
**Версия библиотеки**
v.4.5.0

**Comment by SevereCloud** [comment]
Привет, компонент DatePicker устарел и будет удален в следующей мажорной версии.

На замену ему можно использовать [Input](https://vkcom.github.io/VKUI/#/Input),  [Select](https://vkcom.github.io/VKUI/#/Select) и [DateInput](https://vkcom.github.io/VKUI/#/DateInput). О том что лучше использовать, можно прочитать в обсуждении:

- #7070
