### ISSUE TITLE
[Feature] getRef для DatePicker

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1563]
Для взаимодействия с input

**Comment by thoughtspile** [comment]
@eolme а на вкком (с селектами) где ожидаем реф — на input hidden?

**Comment by eolme** [comment]
Рядом где-то issue лежал, что он не должен быть hidden, но так то на него

**Comment by SevereCloud** [comment]
Привет, компонент DatePicker устарел и будет удален в следующей мажорной версии.

На замену ему можно использовать [Input](https://vkcom.github.io/VKUI/#/Input),  [Select](https://vkcom.github.io/VKUI/#/Select) и [DateInput](https://vkcom.github.io/VKUI/#/DateInput). О том что лучше использовать, можно прочитать в обсуждении:

- #7070
