### ISSUE TITLE
[Bug] DatePicker input имеет некорректный type

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1564]
**Описание**
https://github.com/VKCOM/VKUI/blob/c242a3268b5cfebf268942bd41c48a860e0309bb/src/components/DatePicker/DatePicker.tsx#L203

**Версия библиотеки**
v4.5.0

**Comment by ArthurStam** [comment]
Можешь рассказать, какую проблему сейчас это создаёт?

**Comment by eolme** [comment]
Можно было бы обойти #1562 с помощью CSS, как в случае с Radio, но тут приходится ещё и тип через JS менять. Усугубляет хотфикс ещё #1563

**Comment by ArthurStam** [comment]
Кажется просто, что #1562 пофиксится, когда мы эту же проблему поправим в `CustomSelect`. Потому что DatePicker — это либо набор `<CustomSelect />`, либо `<Input type="date" />`.

**Comment by eolme** [comment]
Проблема еще есть, если обращаться по ref то valueAsDate будет null

**Comment by ArthurStam** [comment]
Проблему понял, спасибо.

**Comment by SevereCloud** [comment]
Привет, компонент DatePicker устарел и будет удален в следующей мажорной версии.

На замену ему можно использовать [Input](https://vkcom.github.io/VKUI/#/Input),  [Select](https://vkcom.github.io/VKUI/#/Select) и [DateInput](https://vkcom.github.io/VKUI/#/DateInput). О том что лучше использовать, можно прочитать в обсуждении:

- #7070
