### ISSUE TITLE
[Feature] Календарь в DatePicker

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1565]
Например, вот [такой](https://happysanta.github.io/vk-app-ui/styleguide/#!/DatePicker):

<img src="https://user-images.githubusercontent.com/11076888/115274729-08aedd80-a152-11eb-9920-0bbb2eabb473.png" width="300">

Или как в ВК при постинге:

<img src="https://user-images.githubusercontent.com/11076888/115274635-f3d24a00-a151-11eb-8854-4968a8ac9f3f.png" width="600">

**Comment by ArthurStam** [comment]
Сделаем, но сроков пока дать не могу.

**Comment by eugpoloz** [comment]
Реализовали в [v4.28.0](https://github.com/VKCOM/VKUI/releases/tag/v4.28.0) разнообразными календарными компонентами благодаря великому @stoope!
