### ISSUE TITLE
[Feature] Состояние загрузки для кнопок

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1566]
Пример из ВК:

<img src="https://user-images.githubusercontent.com/11076888/115275437-d782dd00-a152-11eb-8439-54144d0e1d6e.png" width="300">

**Comment by ArthurStam** [comment]
@wayshev как тебе такой запрос?

**Comment by ArthurStam** [comment]
Будем делать, ждём обновлений в Figma

**Comment by ArthurStam** [comment]
Появится в следующей версии
