### ISSUE TITLE
[Bug] ActionSheet скроллится

### ISSUE THREAD

**Issue by danyarubtsov** [VKCOM/VKUI#1567]
**Описание**
ActionSheet на десктопе через рефы закрепляется за элементом, с которым связан рефом, но если панель длинная, то вместе со страницей начинает скроллиться.
У бага есть и обратный эффект - если кликнуть на элемент, который находится за зоной видимости первого рендера - ActionSheet появится слишком низко, или вовсе за границами экрана.

**Версия библиотеки**
4.0.5

**Comment by ArthurStam** [comment]
Дубликат: #1425 #1109

**Comment by ub1x** [comment]
@ArthurStam фиксы из дубликатов работают только если:
прила открыта вне фрейма вк, или размер фрейма 1000 x 4050, что неудобно для юзера.
В иных случаях баг сохраняется.

**Comment by ub1x** [comment]
Воспроизводится в https://vk.com/app7679912, раздел рейтинг.

**Comment by ArthurStam** [comment]
Там пока нет фиксов. Я закрыл тикет, чтобы не множить обсуждения. Проблему исправим.
