### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by oreshkin-ay** [VKCOM/VKUI#1568]
Сейчас Tooltip - это экспериментальный компонент. Будет ли дорабатываться? И появится ли поведение- отобразить сообщение при наведении курсора на оборачиваемый компонент?

**Comment by ArthurStam** [comment]
Будет. Появится.

**Comment by oreshkin-ay** [comment]
Спасибо! Приблизительно когда?

**Comment by ArthurStam** [comment]
Сейчас сроков дать не можем :(
