### ISSUE TITLE
[Feature] Error status для Radio

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1569]
Например, вот так:

<img src="https://user-images.githubusercontent.com/11076888/115397142-d1ded300-a1f6-11eb-97b5-a1ad0a4688c8.png" width="300">

**Comment by ArthurStam** [comment]
Да, нужная фича. Добавим. @wayshev нужно твоё участие.

**Comment by Lihachyov** [comment]
@eolme идея компонента Radio в том, что он обязан предоставлять варианты, которые пользователь может выбрать. Если опцию выбрать нельзя, её можно отобразить в состоянии disabled

Настоятельно рекомендуем проектировать валидацию форм таким образом, чтобы пользователь не мог ошибиться ещё на этапе ввода, а не после отправки формы. Иначе это как расположить кнопку на которую пользователь нажмёт только ради того чтобы узнать, что на неё нельзя было нажать

Будет здорово если поделишься примерами с отключенными состояниями радио-полей. Мы вот никогда такого не видели :)

**Comment by Lihachyov** [comment]
Если об ошибке никак иначе не узнать кроме как после отправки формы, рекомендую использовать FormStatus с состоянием ошибки и описанием почему нельзя было выбрать этот пункт радио, а также с описанием что пользователь может сделать дальше

**Comment by eolme** [comment]
@Lihachyov так я и прошу status=error для Radio по аналогии с поведением Input 🤔

Если конкретно про данный случай, то я просто не отдаю предпочтение какому-либо варианту. Если смотреть на путь пользователя, то тут спорный момент, если формочка в несколько этапов: оставить какое-то выбранное значение по-умолчанию, и в случае ошибочного предположения возвращение пользователя на шаг назад, либо явно попросить пользователя выбрать нужное ему значение.

**Comment by eolme** [comment]
Про кейс с disabled самому не попадался
