### ISSUE TITLE
При открытии вкладки из tabbar фокус сразу на поисковой строке

### ISSUE THREAD

**Issue by ksydiver** [VKCOM/VKUI#157]
![image](https://user-images.githubusercontent.com/20204025/50907680-06b92880-1439-11e9-85e7-735402994a23.png)

**Comment by ArthurStam** [comment]
В `2.16.5` добавили свойство `autoFocus` компоненту `Search`. По-умолчанию оно установлено в `true`. Соответственно, чтобы проблема пофиксилась, нужно передать `autoFocus={false}`
