### ISSUE TITLE
[Feature] Фиксированные кнопки для ModalPage

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1570]
Примеры реализаций:
<table>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/11076888/115728371-844c9c80-a395-11eb-9870-4eac0ba7b765.png" width="300">
</td>
<td>
<img src="https://user-images.githubusercontent.com/11076888/115728400-8adb1400-a395-11eb-894a-d7a8fcdc8f98.png" width="300">
</td>
<td>
<img src="https://user-images.githubusercontent.com/11076888/115728694-c1b12a00-a395-11eb-8bd7-0c173199f303.png" width="300">
</td>
</tr>
</table>

**Comment by ArthurStam** [comment]
А тут с точки зрения дизайна ничего не нужна. На стороне реализации затык.
