### ISSUE TITLE
[Feature] top/bottom для FormLayoutGroup

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1572]
Пример, как это может выглядеть:

<img src="https://user-images.githubusercontent.com/11076888/115906566-bb47ae80-a478-11eb-9213-ecc760d1499d.png" width="600">

**Comment by ItzNeviKat** [comment]
Может, это я не понимаю, но разве это не то же самое?
```jsx
// https://vkcom.github.io/VKUI/#formlayout
<FormItem top="Тип документа" bottom={purpose ? '' : 'Пожалуйста, укажите тип документа'} status={purpose ? 'valid' : 'error'}>
  <Radio name="type">Паспорт</Radio>
  <Radio name="type">Загран</Radio>
</FormItem>
```
![image](https://user-images.githubusercontent.com/24193020/115908001-44a7b280-a472-11eb-9a8f-1425687d1644.png)

**Comment by ArthurStam** [comment]
Сделаем в рамках RadioGroup #1606

**Comment by SevereCloud** [comment]
Сделали в RadioGroup. В FormLayoutGroup не нужно
