### ISSUE TITLE
[Bug] Стрелочки в HorizontalScroll

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1573]
**Описание**

Если скроллить в начале/конце HorizonalScroll, то стрелочки багуют:

https://user-images.githubusercontent.com/11076888/115907900-88061f00-a47a-11eb-9106-427b13585fdf.mov

**Версия библиотеки**
v4.5.0

**Comment by thoughtspile** [comment]
Я очень старался, но у меня не багуют. Что конкретно происходит на видео — скролл трекпадом во время ховера на стрелке?
