### ISSUE TITLE
[Feature] Tooltip при наведении мыши

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1574]
Автоматическое отображение Tooltip при наведении мыши, пример:

<img width="400" alt="Снимок экрана 2021-04-23 в 21 37 47" src="https://user-images.githubusercontent.com/11076888/115909271-5db56100-a47c-11eb-8bfd-f01fd0cdd321.png">

**Comment by ArthurStam** [comment]
Дизайн в работе
