### ISSUE TITLE
[Bug]: у иконки из vk-icon в PanelHeaderButton нет отступов

### ISSUE THREAD

**Issue by evgeniusorg** [VKCOM/VKUI#1579]
**Описание**
у иконки из vk-icon в правом углу хедера нет отступов в 8px

**Версия библиотеки**
4.5.0

**Шаги воспроизведения**
```
<PanelHeader
   right={(
     <PanelHeaderButton><Icon28MoreHorizontal /></PanelHeaderButton>
  )}
></PanelHeader>
```
  
**Ожидаемое поведение**
у div с иконкой добавляеся класс .vkuiIcon--28, тогда применится стиль 
`.vkuiPanelHeaderButton--ios .vkuiIcon--28 { padding: 8px;} `

**Comment by ArthurStam** [comment]
Проблема на стороне приложения
