### ISSUE TITLE
PanelHeader не отображаются кнопки справа

### ISSUE THREAD

**Issue by spbpavlov** [VKCOM/VKUI#158]
Если сделать так то левая иконка отображается а правая нет, в чем может быть проблема?

`<PanelHeader
  left={<HeaderButton><Icon24Back/></HeaderButton>}
  right={<HeaderButton><Icon24Back/></HeaderButton>}
/>`

**Comment by ArthurStam** [comment]
В VK Apps правая часть шапки зарезервирована под системные кнопки.

**Comment by mahnunchik** [comment]
@ArthurStam напишите, пожалуйста, об этом явно в документации https://vkcom.github.io/vkui-styleguide/#panelheader

> Кнопки могут быть переданы в left или right компонента PanelHeader:
