### ISSUE TITLE
[Bug] Краш при открытии ModalCard

### ISSUE THREAD

**Issue by wigarddev** [VKCOM/VKUI#1585]
Через секунду после смены модалки с **ModalPage** на **ModalCard** краш:

![image](https://user-images.githubusercontent.com/55100874/116743109-1fcab680-aa01-11eb-93f5-4f4a7d29ef17.png)

Сама модалка успевает показаться на секунду после смены.
Код модалки:
```js
<ModalCard
  id='modal-card'
  onClose={() => console.log ('close')}
  icon={<Icon56CakeOutline />}
  header='header'
  subheader='subheader'
  actions={<Button size='l' mode='primary' onClick={() => console.log ('close')}>
    Закрыть
  </Button>}
/>
```

Версия VKUI: **4.6.0**

**Comment by ewgenius** [comment]
Покажите пример как проиницилизирован ModalRoot с ModalPage и ModalCard, а лучше воспроизведение бага в codesandbox

VKUI 4.6.0, переход с модалки на карточку и обратно, проблема не воспроизводится https://codesandbox.io/s/modals-example-forked-is4n4?file=/example.tsx

**Comment by ewgenius** [comment]
> смены модалки с ModalPage на ModalCard

судя по ошибке могу предположить что что-то не так со структурой модалок в ModalRoot, либо с тем как переход реализован

**Comment by wigarddev** [comment]
Забыл сказать, что **ModalPage** мог изменять высоту при помощи **dynamicContentHeight**
Немного изменил ваш пример: https://codesandbox.io/s/modals-example-forked-voidz?file=/example.tsx (34 строка)
Ошибка появляется только на мобильной версии VKUI, т.е. тогда, когда модалки расположены снизу:

![image](https://user-images.githubusercontent.com/55100874/116886492-d0b79800-ac31-11eb-8ba5-1ccffab455b0.png)

**Comment by ewgenius** [comment]
> Забыл сказать, что ModalPage мог изменять высоту при помощи dynamicContentHeight

Да, тут был баг, спасибо за репорт. Фикс в #1610
