### ISSUE TITLE
[Enhancement] Убрать defaultProps в функциональных компонентах

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1586]
У команды React в планах пометить defaultProps у функциональных как [deprecated](https://github.com/reactjs/rfcs/pull/107), возможно стоит использовать предложенную конструкцию при деструктуризации props:

```ts
export const Button = (props: ButtonProps): ReactElement => {
    const {
        color = 'primary',
        component = 'button'
        ...restProps
    } = props;
    //...
}
```

P.S. У hoc React.memo есть оптимизация для функциональных без defaultProps 
P.P.S. В будущем проще будет переходить на новый jsx-runtime

**Comment by ArthurStam** [comment]
Спасибо, учтём.

**Comment by thoughtspile** [comment]
из `defaultProps` подсасываются значения в стайлгайдист — придется как-то это подпирать, признавать неважным или дублировать in jsdoc

<img width="292" alt="Снимок экрана 2021-06-22 в 11 22 38" src="https://user-images.githubusercontent.com/5262915/122890223-295f0380-d34c-11eb-97fc-e1259becdea5.png">
