### ISSUE TITLE
[Feature] Переключение между слайдами с помощью колесика мыши

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1587]
В компоненте Gallery не хватает адаптивного поведения для мыши.

Пример кастомной реализации в [Чекбэке](https://vk.com/coupon#checkback):

<img src="https://user-images.githubusercontent.com/11076888/116878776-de205280-ac30-11eb-9825-493884612d50.png" width="600" />

**Comment by ArthurStam** [comment]
У `Gallery` добавлять реакцию на горизонтальный скролл не хотим. Компонент раздует довольно сложной логикой, а он и так уже довольно жирный. 

Можно в зависимости от условий адаптивности (например по наличию мышки) рисовать либо `HorizontalScroll`, либо `Gallery`. Мне такой подход нравится больше, потому что у тебя два простых компонента и обертка из простого условия.

Пример посмотреть не удалось, потому что у меня там только один элемент.
![image](https://user-images.githubusercontent.com/5061840/131347398-b547b53a-d32a-414f-8d6d-13496280d6c9.png)
