### ISSUE TITLE
[Bug] HorizontallCell связаный рефом с ActionSheet рендерит ActionSheet вне зоны фрейма

### ISSUE THREAD

**Issue by ub1x** [VKCOM/VKUI#1597]
**Описание**
HorizontallCell связаный рефом с ActionSheet рендерит ActionSheet вне зоны фрейма

**Версия библиотеки**
4.6.0

**Скриншоты**
![image](https://user-images.githubusercontent.com/45757192/118208304-2cbebf80-b46f-11eb-9a71-4ec71e398a16.png)

**Comment by ArthurStam** [comment]
Привет. Подскажи пожалуйста, куда передаешь свойство `popout`?

**Comment by ub1x** [comment]
Привет, вот сандбокс приложил: 

https://codesandbox.io/s/horizontalcell-bug-6duob?file=/src/index.js

**Comment by gbowsky** [comment]
Пока жду ответа дизайнеров по этому тикету.

**Comment by ArthurStam** [comment]
Будет исправлено в #1618
