### ISSUE TITLE
[Feature] Поддержка tooltip у Slider и RangeSlider

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1598]
Как reference из ВК:

<img src="https://user-images.githubusercontent.com/11076888/118234884-0451b800-b4a5-11eb-98ff-6816a780b1af.png" width="100" />

**Comment by Zaycevq** [comment]
Клевое улучшение для Slider, но тут нужно потратить время чтобы доработать с таким свойством отображения Tooltip, сейчас не получится взять в работу, но будем иметь ввиду

Учитывая что у Музыкального плеера это уже сделано, можно будет в будущем там подсмотреть и внедрить

<img width="277" alt="tooltip-musicVol" src="https://user-images.githubusercontent.com/91548592/180795735-28b63ffa-d261-4ecc-bd5b-d637bad84fb9.png">

**Comment by Zaycevq** [comment]
Начнём работу над задачей, туть
https://github.com/VKCOM/VKUI/issues/4467
