### ISSUE TITLE
[Bug] Button в aside Header

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1599]
**Описание**
Если передать Button в aside Header, то он имеет неверные отступы:

<img src="https://user-images.githubusercontent.com/11076888/118235547-f8b2c100-b4a5-11eb-81c7-e2d56f3c1889.png" width="600"/>

Примеры из нативного клиента:
<table>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/11076888/118235999-8db5ba00-b4a6-11eb-9806-124a9087c3ad.png" width=300/>
</td>
<td>
<img src="https://user-images.githubusercontent.com/11076888/118236009-93ab9b00-b4a6-11eb-99cb-b3649f072196.png" width=300/>
</td>
</tr>
</table>

**Версия библиотеки**
v4.6.0

**Comment by ArthurStam** [comment]
@wayshev легально ли в правой части `Header` иметь `Button`? Щас там либо текст, либо простая ссылка может быть.

**Comment by ArthurStam** [comment]
Итог обсуждения: согласно гайдам, кнопки там быть не может. Либо ссылка, либо простой текст, либо ничего.
