### ISSUE TITLE
[Feature] Текст + фон в Avatar в качестве заглушки

### ISSUE THREAD

**Issue by land47** [VKCOM/VKUI#1601]
![image](https://user-images.githubusercontent.com/53087814/118246236-6103a180-b4aa-11eb-9333-9f3386d35c48.png)
Выглядеть может так:
`<Avatar fallback='С' />`

**Comment by Alkanores** [comment]
Я думаю, что было бы логичнее сделать так, как это сделано в Ant Design:

<Avatar>C</Avatar>

Или назвать свойство initials, как в UWP:

<Avatar initials="C"/>

**Comment by ArthurStam** [comment]
Дизайн в процессе

**Comment by ArthurStam** [comment]
Доступно начиная с версии 4.22.0
https://vkcom.github.io/VKUI/#/InitialsAvatar
