### ISSUE TITLE
[Bug] InfoRow имеет стили Tappable

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#1603]
**Описание**
Судя из описание компонента `InfoRow`, он не может являться кликабельным, но при этом имеет стили Tappable

**Версия библиотеки**
`4.6.0`

**Скриншоты**
![image](https://user-images.githubusercontent.com/42776347/118654226-aec23600-b82b-11eb-8e52-dd2f30c6508a.png)
![image](https://user-images.githubusercontent.com/42776347/118654253-b681da80-b82b-11eb-81da-d4dbb87df19f.png)

**Пример с воспроизведением**
https://vkcom.github.io/VKUI/#inforow

**Comment by gbowsky** [comment]
InfoRow не имеет стилей Tappable, просто в примере он обёрнут в SimpleCell без `disabled` пропа.
