### ISSUE TITLE
[Feature] RadioGroup

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1606]
Пример использования:

<img src="https://user-images.githubusercontent.com/11076888/118712682-1f6c5100-b832-11eb-925b-ea7bf1173653.png" width="360">

**Comment by ArthurStam** [comment]
Дизайн: https://www.figma.com/file/lLXmjJhnJa4OhgZXzcNJD9/VKUI-Android-Library?node-id=14164%3A286
