### ISSUE TITLE
[Вопрос] Положение ActionSheet

### ISSUE THREAD

**Issue by fab4u-4empion** [VKCOM/VKUI#1607]
Добрый вечер.

Столкнулся с проблемой с ActionSheet в десктопной версии, а конкретнее с возникновением огромных отступов. Можно ли это как-то адекватно пофиксить?

P.s. Я смог что-то сделать путем отлавливания изменения стилей компонента(так как стили менялись после componentDidUpdate, из-за чего я не мог менять стили напрямую), но все же может есть более простые способы это исправить.

![image](https://user-images.githubusercontent.com/66959457/118715159-f6e15880-b82b-11eb-8865-0d2b2474cfcd.png)
![image](https://user-images.githubusercontent.com/66959457/118715363-3740d680-b82c-11eb-8317-b54f308c5d33.png)

**Comment by ArthurStam** [comment]
Привет. Можешь приложить скрин того, как эти отступы в итоге выглядят?

**Comment by fab4u-4empion** [comment]
> Привет. Можешь приложить скрин того, как эти отступы в итоге выглядят?

Примерно вот так, но я немного срезал отступ сверху( ≈100рх) и накинул ≈50 слева.
![Screenshot_2021-05-19-17-17-13-326_com vkontakte android](https://user-images.githubusercontent.com/66959457/118828721-3066a200-b8c6-11eb-8267-854ff71c7581.jpg)

**Comment by fab4u-4empion** [comment]
> Привет. Можешь приложить скрин того, как эти отступы в итоге выглядят?

Кста если речь шла про отступы, которые делает либа, то там ActionSheet не видно вообще, так как отступ почти 4000 пикселей. И подобная проблема возникает и в песочнице стайл гайда. Я накидал перед Cell кучу заголовков и в итоге получается это (прокрутку опустил в самый низ изначально): 
![image](https://user-images.githubusercontent.com/66959457/118868960-7be07680-b8ed-11eb-9bd2-733da0b871e4.png)

**Comment by fab4u-4empion** [comment]
В исходном коде к отступу сверху зачем-то прибавляют _this.window.pageYOffset, ведь var toggleRect = toggleRef.getBoundingClientRect(); и toggleRect.top вернут положение относительно viewport.
 А у десктопного ActionSheet стоит position: absolute, причем у его родителя с классом .vkuiView__popout стоит position: fixed, что делает позиционирование ActionSheet относительно viewport по дефолту, а не относительно page (поэтому прибавление _this.window.pageYOffset скорее всего не нужно)

![image](https://user-images.githubusercontent.com/66959457/118869969-b565b180-b8ee-11eb-9c3e-8d94fce77bb1.png)
![image](https://user-images.githubusercontent.com/66959457/118870656-78e68580-b8ef-11eb-8d50-24df809ce185.png)
![image](https://user-images.githubusercontent.com/66959457/118870686-826fed80-b8ef-11eb-9557-28aad53e4dde.png)

**Comment by ArthurStam** [comment]
`popout` передаешь во `View` или в `SplitLayout`? Нужно в последний. Отразим это в доке скоро.

**Comment by fab4u-4empion** [comment]
> `popout` передаешь во `View` или в `SplitLayout`? Нужно в последний. Отразим это в доке скоро.

Во вьюшку передаю

**Comment by fab4u-4empion** [comment]
Заменил View на SplitLayout. Скажем так, что лучше не стало. все равно отступ сверху 3000рх и ActionSheet отображен где-то под страницей, куда даже долистать нельзя.

Может проблема в том, что я гененрирую компонент с карточками в другом файле из закидываю View в другой View типо:
<View>
	<Panel>
		<Group>
			<View popout="...">
                             //карточки турниров
			</View>
		</Group>
	</Panel>
</View>

**Comment by ArthurStam** [comment]
View во View точно не надо)

**Comment by ArthurStam** [comment]
SplitLayout => SplitCol => View => Panel => 'контент панели'

**Comment by ArthurStam** [comment]
И `popout` сейчас нужно класть в `SplitLayout`, а не во `View` или `Root`. Поправили в доке.
