### ISSUE TITLE
[Feature]  Изменять направление отображения у actionSheet в зависимости от доступного места

### ISSUE THREAD

**Issue by gloomweaver** [VKCOM/VKUI#1618]
При открытии ActionSheet близко к концу скролла происходит расширение документа.

**Пример**
https://codesandbox.io/s/action-sheet-overflow-rfe6l
В десктопной версии кликнуть на один из последних элементов.

**Чего хотелось бы**
Возможность отображать ActionSheet в другую сторону, если недостаточно места.

**Comment by eugpoloz** [comment]
@ArthurStam этот баг не починили с переездом на popper случайно? Или `ActionSheet` на него не переезжал?

**Comment by inomdzhon** [comment]
Обновил в прилагаемой песочница VKUI до `v4.28.0`. Получается благодаря popper проблема поправлена ✅

**Comment by inomdzhon** [comment]
Обновил в прилагаемой песочница VKUI до `v4.28.0`. Получается благодаря popper проблема поправлена ✅
