### ISSUE TITLE
[Feature] Навигация

### ISSUE THREAD

**Issue by dsedinkin** [VKCOM/VKUI#1629]
Существуют сервисы, в которых требуется множество вложений вкладок panel, к примеру, ЛитРес. Там как раз и демонстрируется навигация со множеством вложений, и выглядит это печально. Пора бы роутер свой завести, костыльный, на существующей UI или же просто переписать компонент))

https://vk.com/app7371328 (ЛитРес), перейдите в раздел любой книги где ниже есть "другие книги автора"

**Comment by kiyasov** [comment]
https://github.com/VKCOM/vk-router

**Comment by seadinkin2002** [comment]
Если бы этот роутер давал возможность "бесконечных" вложений одной панели, тогда бы им пользовались

**Comment by thoughtspile** [comment]
Я пока не понимаю, какая фича запрашивается 😞  VKUI можно завернуть в любой роутер (например, [router5](https://router5.js.org/)), при этом оставив плоскую структуру `[Root] -> View -> Panel`. Например, в примере с литресом может быть что-то вроде:

```js
const routes = [
  { name: 'book', path: '/books/:book:' },
  { name: 'author.books', path: '/author/:authorId:/books' }
];
const App = withRoute(({ route }) => (
  <View activePanel={route.name}>
    <Panel nav="book" />
    <Panel nav="author.books" />
  </View>
));
```

@seadinkin2002, что нужно сделать в vkui?

**Comment by seadinkin2002** [comment]
Видимо как-то не так объяснил, окей... 

Кейс таков. К примеру, приложение с фильмами. Мы открыли фильм <panel id='filmview'/>. У фильма внизу страницы находятся рекомендации к фильмам. Они по логике должны открываться также в этой же панели, с анимацией. Но чтоб воплотить такой кейс, надо либо передумывать логику, добавлять еще одну <panel id='filmview2'/>, при том что на следующей панельке нельзя будет отображать эти рекомендации, сами понимаете почему, <panel id='filmview1'/> <panel id='filmview2'/> <panel id='filmview3'/>, бред.

Так вот просьба дать возможность делать бесконечное количество вложений. Про саму реализацию что считаете лучше,  роутер который будет создавать фейк анимацию, а контент менять или же какую-то нормальную логику ui для решения подобных задач?

Примеры подобных кейсов не только в фильмах, в miniapp ЛитРес - там костыльно разрабы выветрились (опять же скажу, там ужасный пример решения этой задачи), в miniapp новости - там я бы мог отображать похожие статьи внизу страницы.

Конечно же Вы можете сейчас предложить альтернативу, но я не хочу показывать контент в модалке какой-то.

**Comment by seadinkin2002** [comment]
В целом понятен кейс? @thoughtspile

**Comment by ewgenius** [comment]
У нас уже есть в планах новая навигация, с более гибким поведением
Добавлять поддержку бесконечных переходов в текущей реализации View/Panel сложно, и в итоге это все равно будет  очень костыльное решение

**Comment by pfrankov** [comment]
Возможное решение:
https://github.com/VKCOM/VKUI/issues/1795
