### ISSUE TITLE
[Bug] Gallery: onClick срабатывает при перетаскивании

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1644]
**Описание**
Было вроде #1136, но воспроизводится до сих пор:

https://user-images.githubusercontent.com/11076888/120103203-8f96a300-c15f-11eb-8052-1b96031b28c8.mov

**Версия библиотеки**
v4.8.0

**Comment by thoughtspile** [comment]
@eolme привет! Давай уточним, `onClick` висит на слайде? Сделал [сандбокс,](https://codesandbox.io/embed/vkui-gallery-click-3eze8?file=/src/index.js&codemirror=1) на Gallery и обертке клик вылетает только при настоящем клике.

**Comment by eolme** [comment]
@thoughtspile да, на самом слайде

**Comment by thoughtspile** [comment]
да, это я упустил
