### ISSUE TITLE
[Bug] нет отступов у текста в PanelHeader

### ISSUE THREAD

**Issue by evgeniusorg** [VKCOM/VKUI#1646]
**Описание**
В компоненте PanelHeader у children нужны отступы слева и справа
<img width="628" alt="" src="https://user-images.githubusercontent.com/11682693/120473387-a3384880-c3af-11eb-924c-2d75d204598f.png">

**Версия библиотеки**
4.8.0

**Шаги воспроизведения**
указать в в компоненте PanelHeader заведомо дилнный текст в children

**Ожидаемое поведение**
текст обрезается через троеточие, слева и права есть отсупы до краев или левого/правого блоков

**Comment by inomdzhon** [comment]
Не воспроизводится

Версия: **v5.0.2**
