### ISSUE TITLE
[Feature] Добавить в компонент Search возможность менять тип для input

### ISSUE THREAD

**Issue by asalisinasa** [VKCOM/VKUI#1648]
Хотелось бы иметь возможность менять атрибут `type` для `input` в компоненте Search или сделать `type="search"` по-дефолту
https://github.com/VKCOM/VKUI/blob/8f99ea18e6a2a9af589ebc40bdef382ba1f7546d/src/components/Search/Search.tsx#L157

Сейчас нет возможности переключения режима клавиатуры
<img width="752" alt="Снимок экрана 2021-06-03 в 16 01 27" src="https://user-images.githubusercontent.com/15110476/120649493-7e160980-c485-11eb-9726-ccd8742df1b2.png">

**Comment by ArthurStam** [comment]
Привет. Сделаем к следующему релизу.
