### ISSUE TITLE
[Bug] Поломалось поведение selectable для Cell

### ISSUE THREAD

**Issue by land47** [VKCOM/VKUI#1654]
```jsx
<Cell selectable>123</Cell>
```
![image](https://user-images.githubusercontent.com/53087814/120943771-ad54a100-c739-11eb-9235-c9a84ce81bc6.png)

**Sandbox**
https://codesandbox.io/s/thirsty-banzai-gyf4z?file=/src/index.js

**Comment by eugpoloz** [comment]
@land47 привет! Спасибо за репорт, в мастере это уже пофикшено, совсем скоро выкатим 4.9.0 — и все починится.

**Comment by eugpoloz** [comment]
Выкатили [v4.9.0](https://github.com/VKCOM/VKUI/releases/tag/v4.9.0) с фиксом, так что закрываю.
