### ISSUE TITLE
[Bug] Не работают модалки с nav пропом

### ISSUE THREAD

**Issue by land47** [VKCOM/VKUI#1661]
```jsx
<ModalRoot activeModal='1'>
  <ModalCard nav='1' />
</ModalRoot>
```

**Comment by thoughtspile** [comment]
@land47 `nav` поддерживаем только с [версии 4.7](https://github.com/VKCOM/VKUI/releases/tag/v4.7.0) — точно такая версия? Сделал [рабтающий сандбокс](https://codesandbox.io/s/vkui-modal-nav-8k4es?file=/src/index.js)

**Comment by land47** [comment]
Точняк
