### ISSUE TITLE
[Bug] Не закрывается на десктопе ActionSheet при клике не по ActionSheetItem

### ISSUE THREAD

**Issue by ekuizhev** [VKCOM/VKUI#1662]
Это происходит из-за этого коммита:
https://github.com/VKCOM/VKUI/commit/eab6da98255acdbbcfe49672b6042271b09615e1

В попаут устанавливается ActionSheet, но не убирается, так как не срабатывает onClose

**Comment by ekuizhev** [comment]
![Selection_013](https://user-images.githubusercontent.com/46845084/121237870-2e2dad00-c8a0-11eb-9290-c674ae0b7b91.png)
![Selection_014](https://user-images.githubusercontent.com/46845084/121237890-3259ca80-c8a0-11eb-9951-939e63100e47.png)

**Comment by ArthurStam** [comment]
На последней версии тоже воспроизводится?
