### ISSUE TITLE
[Bug] DatePicker: некорректная работа min/max

### ISSUE THREAD

**Issue by thoughtspile** [VKCOM/VKUI#1665]
**Описание**

В `DatePicker` на мобильных устройствах `iOS` можно выбрать любую дату все равно

---

В `DatePicker` на десктопе  `min` / `max` значения действуют только на год.

**Ожидаемое поведение**

- в году `max.year` можно выбрать только месяц до `max.month`
- в году `max.year` и месяце `max.month` можно выбрать только день до `max.day`
- `min` — аналогично
- __TBD:__ активен ли селект, если доступно одно значение?
- __TBD:__ сбрасывается ли день / месяц при переключении в месяц / год, для которого он недоступен? Например, `value: 22.05.2018, max: 12.05.2020`, переключаем год в 2020 — сбрасывается ли 22 число?
  - Да, потому что значение должно быть корректным
  - Нет, потому что я мог планировать сменить месяц на апрель, а день выбрал заранее

**Скриншоты**

<img width="1046" alt="Снимок экрана 2021-06-09 в 16 47 52" src="https://user-images.githubusercontent.com/5262915/121366798-700f2f80-c942-11eb-89e8-f865c329aee6.png">

[Пример с воспроизведением](https://codesandbox.io/s/date-picker-limits-nh2ov)

**Comment by SevereCloud** [comment]
Привет, компонент DatePicker устарел и будет удален в следующей мажорной версии.

На замену ему можно использовать [Input](https://vkcom.github.io/VKUI/#/Input),  [Select](https://vkcom.github.io/VKUI/#/Select) и [DateInput](https://vkcom.github.io/VKUI/#/DateInput). О том что лучше использовать, можно прочитать в обсуждении:

- #7070
