### ISSUE TITLE
[Bug] При открытом попапе (ModalCard) клавиатура на ios смещает весь контент страницы на фоне вверх

### ISSUE THREAD

**Issue by ewgenius** [VKCOM/VKUI#1675]
**Шаги воспроизведения**
- открыть модалку с полем ввода
- нажать на поле ввода -> появится клавиатура и сместит весь вьюпорт вверх

**Ожидаемое поведение**
Основной контент под модалкой должен оставаться неподвижным

**Скриншоты**

https://user-images.githubusercontent.com/827338/122223231-a8bb8580-cebb-11eb-8db7-f80e8f9756a0.MP4

Корректное поведение при фокусе поля ввода без модалки:

https://user-images.githubusercontent.com/827338/122223671-0fd93a00-cebc-11eb-937d-6d3bbb1ff022.MP4

**Пример с воспроизведением**
https://codesandbox.io/s/sleepy-feynman-1shw1

**Comment by pfrankov** [comment]
Похоже, что это ограничение, связанное с фиксированием фона.
Если есть идеи, как это может быть исправлено без поломки скролла в модалках — буду премного благодарен.
