### ISSUE TITLE
[Feature] Собирать ES вариант

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1676]
Хочется чистый ES(next?) без преобразований и полифиллов.

Либо как вариант, собирать с
```json
"targets": {
  "esmodules": true
}
```
потому что в module сейчас лежит транспилированный для IE 11 (browserslist default) просто с import/export.

**Comment by thoughtspile** [comment]
как обычно интересное предложение, но чего мы пытаемся этим добиться? Меня пугает перспектива 12 сборок (`(stable + unstable) x (commonjs + esm + esnext) x (css-modules + global-css)`), а IE11 входит в compat target самого вк.

Если очень хочется, можно попробовать нахачить это на стороне приложения:
- module-resolver `@vkontakte/vkui` -> `@vkontakte/vkui/src`
- `babel-loader` с конфигом из `@vkontakte/vkui/babel.config.js`

**Comment by eolme** [comment]
Так повелось, что по полям в package.json (main/module/browser/etc) определяется какая версия предоставляется для использования.

В нашей же ситуации одна и та же версия, но просто с различными способами работы с модулями. Из-за этого польза от разделения конечного бандла на module/nomodule просто нивелируется.

**Comment by thoughtspile** [comment]
`module`-версия с import / export сделана только для поддержки три-шейкинга (три-шейкать require нельзя) —  ["спека" module это и подразумевает](https://nodejs.org/api/packages.html#packages_dual_commonjs_es_module_packages). Кажется,  не-транспилированная публичная версия — отличный способ стрелять себе в ногу, потому что бабель обычно не лезет в node_modules.

**Comment by eolme** [comment]
> отличный способ стрелять себе в ногу, потому что бабель обычно не лезет в node_modules.

По первому варианту понял.  Я про esmodules -- оно включает только те браузеры, которые поддерживают нативные модули.

**Comment by eolme** [comment]
> Меня пугает перспектива 12 сборок

Можно ускорить, версии идентичные, а значит достаточно один раз собрать, скопировать и пройтись заменив все `import/export` на `require` ([тык](https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs))

**Comment by eolme** [comment]
> не рассказал, чего хочешь добиться

> разделения конечного бандла на module/nomodule

**Comment by thoughtspile** [comment]
Я все таки предлагаю сделать вот такой вебпак-конфиг, поставить недостающие бабель-плагины и транспилировать на твой вкус:

```js
{
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        include: /node_modules\/@vkontakte\/vkui\/src/,
        loader: require.resolve('babel-loader'),
        options: {
          // не используем бабель-конфиги аппа
          babelrc: false,
          configFile: false,
          // перенастраиваем preset-env
          presets: require('@vkontakte/vkui/babel.config').presets.map(preset => {
            return preset[0] === 'preset-env' ? [preset[0], { esmodules: true }] : preset;
          }),
          plugins: require('@vkontakte/vkui/babel.config').plugins.map(plugin => {
            // babel-plugin-module-resolver работает только с относительными путями =(
            if (plugin[1] && plugin[1].alias && plugin[1].alias['#jsxRuntime']) {
              return [plugin[0], {
                ...plugin[1],
                alias: {
                  ...plugin[1].alias,
                  "#jsxRuntime": './node_modules/@vkontakte/vkui/src/lib/jsxRuntime.ts',
                }
              }];
            }
            return plugin;
          }).concat([
            // редкий браузер осилит нативный ??
            '@babel/plugin-proposal-nullish-coalescing-operator'
          ]),
          cacheDirectory: true,
          cacheCompression: false,
        },
      },
    ]
  }
  resolve: {
    alias: {
      '@vkontakte/vkui$': '@vkontakte/vkui/src/'
    },
  }
}
```

**Comment by eolme** [comment]
У меня примерно так и выглядит, просто тащить из проекта в проект - такое себе удовольствие

**Comment by thoughtspile** [comment]
Я буду только рад, если на npm вдруг появится пакетик `vkui-next`, в котором vkui пересобран для cutting edge браузеров)

**Comment by eolme** [comment]
@thoughtspile #1679

**Comment by eolme** [comment]
> vkui-next
@thoughtspile, можно потыкать [@mntm/vkui](https://npm.im/@mntm/vkui), сам скрипт сборки [vkui-builder](https://github.com/eolme/vkui-builder)

**Comment by thoughtspile** [comment]
> можно потыкать

Потрясающе) Оставлю ишью на случай если на самом деле все мечтали об этой фиче. В #1679 еще играешься или закроем? (я разок собрал, было весело, но нам нужно стоять на голове)

**Comment by eolme** [comment]
Закрыл
