### ISSUE TITLE
[Feature] Скрывать стрелки в SubnavigationBar

### ISSUE THREAD

**Issue by reyzitwo** [VKCOM/VKUI#1681]
**Описание**
При попытке скрыть стрелки в HorizontalScroll, в котором находится SubnavigationBar, с помощью showArrows={false}, они не скрываются.

**Версия библиотеки**
4.9.0

**Скриншоты**
![image](https://user-images.githubusercontent.com/73870113/122632554-e2bf9e00-d0ec-11eb-8783-8f251ae82d38.png)

**Пример с воспроизведением**
https://codesandbox.io/s/optimistic-leftpad-bcwf9?file=/src/index.js

**Comment by thoughtspile** [comment]
@reyzitwo привет! Я думал, что сошел с ума, когда увидел это) На самом деле секрет прост — в `SubnavigationBar` уже встроен `HorizontalScroll`, оборачивать в еще один не надо. Стрелки внешнего скролла прячутся, а у внутреннего остаются.

Отключить стрелки у `SubnavigationBar` нельзя, и я не уверен что это допускают гайды — возможно, @wayshev скажет точнее.

**Comment by ArthurStam** [comment]
Поговорил с дизайнерами. Мы предлагаем делегировать логику показа/скрыти стрелок компоненту `HorizontalScroll`, который, как правильно подметил @ thoughtspile, уже рисуется внутри `SubnavigationBar`. 

Но мы переделаем компонент `SubnavigationBar` так, чтобы переданный `showArrows` проксировался в `HorizontalScroll`, если очень надо скрыть стрелки.

**Comment by fedorov-xyz** [comment]
Будет в ближайшем релизе.
