### ISSUE TITLE
[Feature] Разделить settlingHeight и fullscreen

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1697]
После #1340 теперь нельзя открывать модалку на максимум:
- при установке в 100, если контент маленький, остается пространство снизу
- если не ставить 100 и контента много, то она по-умолчанию открывается на 75

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
