### ISSUE TITLE
[Bug] После открытия клавиатуры на android модальная страница не возвращает свой размер

### ISSUE THREAD

**Issue by r-lubimov-corp-mail-ru** [VKCOM/VKUI#1698]
**Описание**
После открытия клавиатуры на android модальная страница не возвращает свой размер

**Версия библиотеки**
4.9.1

**Шаги воспроизведения**
1. Открыть модальную страницу с полем
2. Тыкнуть в поле
3. Убрать фокус с поля

**Ожидаемое поведение**
Модалка должна вернуть свой размер к размеру содержимого

**Видео**
https://user-images.githubusercontent.com/68422265/123244805-eb4d1580-d4ec-11eb-826f-3c45028a68e6.mp4

**Пример с воспроизведением**
Надо проверить на телефоне
https://codesandbox.io/s/modern-sea-h090e?file=/src/index.js

**Comment by eugpoloz** [comment]
Возможно, связан с #1739?

**Comment by SevereCloud** [comment]
Похоже проблема в неправильной работе `translate3d` в браузере

https://github.com/VKCOM/VKUI/assets/14944123/80560ef4-1540-4c8b-9930-8e380c0b3cec

**Comment by inomdzhon** [comment]
Не воспроизводится

> [!NOTE]
> Версия на момент тестирования в [v6.7.4](https://github.com/VKCOM/VKUI/releases/tag/v6.7.4)
