### ISSUE TITLE
[Bug] RichCell дублируется вывод after

### ISSUE THREAD

**Issue by s-pivovarov** [VKCOM/VKUI#1699]
**Описание**
В компоненте [RichCell](https://github.com/VKCOM/VKUI/tree/master/src/components/RichCell) дублируется рендер свойства _after_.
Возможно, раньше это использовалось для какой-то более сложной логики, но после обновления библиотеки иконок это ломает компонент. Дело в перекрывающем интайн-стиле установленном на иконке, он перебивает _display: none_ установленный в компоненте.

Не уверен, что дублирование вовсе необходимо.
Возможно связано этим — https://github.com/VKCOM/VKUI/issues/1059

**Версия библиотеки**
VKUI: **v4.6.0+**
VKIcons: **v1.101.0**

**Шаги воспроизведения**
Проблему видно в гайде, _after_ с иконкой выводится дважды: https://vkcom.github.io/VKUI/#richcell

**Скриншоты**
![image](https://user-images.githubusercontent.com/22467200/123277287-a508ae00-d50e-11eb-8e2b-41cf320f3bbd.png)

**Comment by thoughtspile** [comment]
К сожалению иконки v1.100,101,102,103 сломаны из-за `display: block` — стоит обновиться до [1.104](https://github.com/VKCOM/icons/releases)
