### ISSUE TITLE
[Feature] Wide separator in spacing

### ISSUE THREAD

**Issue by gou177** [VKCOM/VKUI#1707]
Сейчас можно использовать wide separator вместе с spacing только 
```
<Spacing .../>
<Separator wide/>
<Spacing .../>
```
Хотелось бы, чтоб можно было использовать параметр wide внутри spacing
```
<Spacing separator wide />
```
Применение: Использование Spacing с сепаратором внутри Div
```
<Div>
  <Spacing separator wide />
</Div>
```

**Comment by ewgenius** [comment]
Вопрос довольно спорный

По дизайну VKUI у нас нет сепараторов без отступов по бокам, `<Separator wide/>` был добавлен для внутреннего использования внутри библиотеки

> Применение: Использование Spacing с сепаратором внутри Div

Компонент [Div](https://vkcom.github.io/VKUI/#Div) предназначен для добавления стандартных отступов вокруг кастомных компонентов, поэтому добавлять совместимость для такого случая кажется избыточным.
Я бы посоветовал посмотреть на вложенные группы для таких задач https://vkcom.github.io/VKUI/#!/Group - тогда автоматически добавится сепаратор с правильными отступами

```tsx
<Group>
  <Group mode="plain">
    ...
  </Group>
  <Group mode="plain">
    ...
  </Group>
</Group>
```

**Comment by thoughtspile** [comment]
> По дизайну VKUI у нас нет сепараторов без отступов по бокам, `<Separator wide/>` был добавлен для внутреннего использования внутри библиотеки

Тогда, возможно, стоит отразить это в документации (и, возможно, типах)?

<img width="912" alt="Снимок экрана 2021-07-05 в 14 52 09" src="https://user-images.githubusercontent.com/5262915/124467497-9472f600-dda0-11eb-8332-0fb60e8e9582.png">
<img width="174" alt="Снимок экрана 2021-07-05 в 14 52 32" src="https://user-images.githubusercontent.com/5262915/124467530-a2287b80-dda0-11eb-9a4c-cf26b7fa359b.png">
