### ISSUE TITLE
[Enhancement] Проверить полифиллы методов

### ISSUE THREAD

**Issue by thoughtspile** [VKCOM/VKUI#1724]
Сейчас полифиллы для `#Element.matches`, `#Element.closest`, `#Array.includes`, `#Array.find` подключаются руками в [polyfills.ts](https://github.com/VKCOM/VKUI/blob/master/src/lib/polyfills.ts). Проблемы:

1. Незаполифилленные методы случайно протекают в код (см. [findIndex](https://github.com/VKCOM/VKUI/search?q=findindex)).
3. Полифиллы не дедуплицируются в конечных аппах (как это произошло бы при `import corejs`)

**Comment by thoughtspile** [comment]
FYI https://github.com/w3ctag/polyfills/issues/6

Коротко: включать в либу глобальные полифиллы очень плохо, потому что они дублируются и могут конфликтовать с другими глобальными полифилами

**Comment by pfrankov** [comment]
Собираемся делать две версии: одна скомпиленная и с полифилами, а другая — нескомпиленная под es6 (es7?)

**Comment by inomdzhon** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
