### ISSUE TITLE
[Bug] Неправильное позиционирование ActionSheet + выходит из фрейма.

### ISSUE THREAD

**Issue by KostyaBobroff** [VKCOM/VKUI#1747]
**Описание**

Нашел проблему, связанную с отображением ActionSheet в контейнере, который скролится. ActionSheet позиционируется неправильно и выходит из фрейма. 

**Версия библиотеки**
4.11.0

**Шаги воспроизведения**
Всего заметил 2 кейса:
1) Проскроливую контейнер, нажимаю на кнопку крестик, появляется popout  не в том месте, т е намного выше/ниже кнопки (parentToggleRef).
2) нажимаю на кнопку крестик -> появляется popout -> popout обрезается слева, но может и снизу (воспроизводится при проскроливании и не проскроливании контейнера)

**Ожидаемое поведение**
2 кейса:
1) т е по нажатию на кнопку крестик снизу, я ожидаю, что popout откроется сверху/снизу (в зависимости от доступного пространства)  + расстояние от кнопки крестик до popout будет меньше (т е popout будет вообще поверх кнопки примерно открываться) + не будет выходить за пределы iframe, т е не будет смещаться влево и обрезаться.
2) Нажимаю на кнопку крестик -> открывается popout поверх кнопки крестик + открывается во viewport, чтобы пользователю был виден popout (здесь учитывается, чтобы popout не обрезался слева и снизу)

P.s передаю popout в SplitLayout, вложенность в аппе такая:  Root -> View -> Panel -> SplitLayout

**Скриншоты**
![telegram-cloud-photo-size-2-5458688736847049804-y](https://user-images.githubusercontent.com/16582207/126462842-9cd1efb2-f975-4963-93d6-48d37f8fe644.jpg)

**Comment by ArthurStam** [comment]
Дубликат #1597. Скоро поправим. Этот тикет закрою.

**Comment by ewgenius** [comment]
> Root -> View -> Panel -> SplitLayout

Не факт что это причина, но такая иерархия не верная.
SplitLayout > SplitCol должны быть в корне (после провайдеров)
Root, View уже внутри них располагаются

**Comment by KostyaBobroff** [comment]
а если у меня разный ui на разные страницы, например, на одном экране есть две колонки, т е логично использовать SplitLayout, а есть где одна колонка на всю ширину, т е просто элемент типа View, тогда как норм сделать? Ну т е попробую этот варик, который ты мне предложил, но из доки непонятно, какая последовательность должна быть + SplitLayout кажется что должен быть внутри Panel

**Comment by ArthurStam** [comment]
> а если у меня разный ui на разные страницы, например, на одном экране есть две колонки, т е логично использовать SplitLayout, а есть где одна колонка на всю ширину, т е просто элемент типа View, тогда как норм сделать? Ну т е попробую этот варик, который ты мне предложил, но из доки непонятно, какая последовательность должна быть + SplitLayout кажется что должен быть внутри Panel

Я рекомендую везде использовать SplitLayout. Он заточен под одноколоночный мобильный layout в том числе. Структура такая: ConfigProvider -> AdaptivityProvider -> AppRoot -> SplitLayout -> SplitCol -> View -> Panel
