### ISSUE TITLE
У ScreenSpinner неправильный цвет при теме bright_light в Android

### ISSUE THREAD

**Issue by NOCELL** [VKCOM/VKUI#175]
iOS
![image](https://user-images.githubusercontent.com/22259080/51419347-4fe94500-1bbc-11e9-9560-f771b2e2b26a.png)
Android
![image](https://user-images.githubusercontent.com/22259080/51419359-6b545000-1bbc-11e9-873a-4ea035074e54.png)

**Comment by ArthurStam** [comment]
Спасибо, поправим.

**Comment by ArthurStam** [comment]
Пофикшено в `2.18.5`
