### ISSUE TITLE
[Bug] Не работает проброс темы в последних версиях

### ISSUE THREAD

**Issue by lexstile** [VKCOM/VKUI#1751]
**Описание**
Не применяется темная тема ко всему, что находится внутри `<Panel />`.

**Версия библиотеки**
Воспроизводится на v. 4.10-4.11
Не воспроизводится на v. 4.3.0

**Шаги воспроизведения**
Развернуть приложение с версией VK UI 4.10-4.11.
Структура должна совпадать с примером, иначе кейс может не воспроизвестись или воспроизвестись некорректно.

**Пример с воспроизведением**
` 
   <ConfigProvider isWebView={true} scheme={Scheme.SPACE_GRAY}>
      <AdaptivityProvider>
        <AppRoot>
          <Root activeView={activeView}>
            <View id={activeView} activePanel={VIEWS.INITIAL.CODE}>
              <Panel id={VIEWS.INITIAL.CODE}>
                <Placeholder header="Заголовок" action={<Button size="m">Кнопка</Button>}>
                  Рыба текст
                </Placeholder>
              </Panel>
            </View>
          </Root>
        </AppRoot>
      </AdaptivityProvider>
    </ConfigProvider>
`

**Comment by ArthurStam** [comment]
Привет. Скопировал твой пример в codesandbox, тема пробросилось.
https://codesandbox.io/s/recursing-meadow-7rbw1

**Comment by lexstile** [comment]
Вы проверяли только в браузере?
Проверено на iOS 14 + Android 10.
Ваш код не меняет тему.

**Comment by lexstile** [comment]
Также, общался с поддержкой вк, у них тоже не работает.
![image](https://user-images.githubusercontent.com/30532019/126756789-c36d8797-1d2e-4a59-8f4a-f7c61a9c0e38.png)

**Comment by ArthurStam** [comment]
Ты заходил в codesandbox? Можешь воспроизвести проблему там?

**Comment by ArthurStam** [comment]
Проверил на iOS 14 в safari и Android 10 в chrome
![image](https://user-images.githubusercontent.com/5061840/126773312-f2b42f30-5c59-489b-918b-f3eb0b02932a.png)
![IMG_2975](https://user-images.githubusercontent.com/5061840/126773331-c67166c3-a17d-41a3-bf02-91bf51be46f2.PNG)

**Comment by ArthurStam** [comment]
Если у тебя мини апп, то возможно где-то в коде происходит перезапись темы

**Comment by lexstile** [comment]
Я вставил ссылку из codesandbox в настройках vk mini apps - https://vk.com/editapp?id=XXXXXX&section=options.
Проблема воспроизводится на мобильных клиентах.

**Comment by lexstile** [comment]
Повторюсь, вы проверяете через браузер, через него отрабатывает.

**Comment by lexstile** [comment]
В настройках прописывал url - https://7rbw1.csb.app/

**Comment by thoughtspile** [comment]
![Screenshot_20210723-143347.png](https://user-images.githubusercontent.com/5262915/126776188-c36ced11-1f0a-4039-b032-ba4e08878b26.png)

Андроид темный

**Comment by lexstile** [comment]
Ребят, попробовал развернуть то же самое локально - https://disk.yandex.ru/d/TScx17tREbkKBA
Не работает.

**Comment by lexstile** [comment]
Вот результат, фон темный, а все, что внутри `<Panel />` - белое
![image](https://user-images.githubusercontent.com/30532019/126790345-0355d8a9-4519-431e-8792-3ff47fea48fb.png)

**Comment by ArthurStam** [comment]
О. Я заметил, что у тебя webpack.config.js устроен таким образом, что css-переменные, отвечающие за раскрашивание интерфейса, навешиваются на `.vkui__root`. Отсюда и чудеса. Это происходит из-за того, что ты обрабатываешь css из библиотеки. Этого делать не стоит, мы поставляем уже готовые стили. То есть тебе нужно написать отдельное правило загрузки стилей из node_modules. И исключить любые модификации этих стилей.

**Comment by lexstile** [comment]
Спасибо, от души.
Половину правил убрал для .css и все встало на свои места.
Прошу прощения, что дернул вас.

**Comment by lexstile** [comment]
Только единственный момент, почему в версии 4.3 все работала с одним и тем же конфигом, а в версиях 4.10-4.11 - нет...

**Comment by thoughtspile** [comment]
> Только единственный момент, почему в версии 4.3 все работало с одним и тем же конфигом, а в версиях 4.10-4.11 - нет...

Думаю, связано с #1477, который поехал в [4.5.0](https://github.com/VKCOM/VKUI/releases/tag/v4.5.0) — мне очень жаль =(

**Comment by lexstile** [comment]
> > Только единственный момент, почему в версии 4.3 все работало с одним и тем же конфигом, а в версиях 4.10-4.11 - нет...
> 
> Думаю, связано с #1477, который поехал в [4.5.0](https://github.com/VKCOM/VKUI/releases/tag/v4.5.0) — мне очень жаль =(

О, уже и не ждал ответа, приятно удивлен)
Спасибо вам, что помогли!
Меня сбило с толку, что при проект не менялся кроме версии vk ui.
И прошу меня извинить, что потратил ваше время.
