### ISSUE TITLE
[Bug] PanelHeader не перекрывает всю ширину приложения при горизонтальном положении в m.vk через Safari

### ISSUE THREAD

**Issue by fab4u-4empion** [VKCOM/VKUI#1752]
**Описание**
В m.vk в горизонтальном положении в браузере Safari PanelHeader не перекрывает всю ширину приложения, из-за чего просматривается контент под ним.

**Версия библиотеки**
4,10,0

**Шаги воспроизведения**
1) Запустить m.vk через сафари на мобильном устройстве
2) Запустить сервис
3) Перевернуть телефон в горизонтальное положение
4) Пролистать контент

**Скриншоты**
![image](https://user-images.githubusercontent.com/66959457/126781334-2c5ed13f-b2f6-4b47-98b5-ff30f7b662f8.png)

К сожалению скрин не мой, поэтому только один. В других браузерах все работает хорошо.
Также хотелось бы узнать, могу ли я как-то пофиксить это на своей стороне (вроде все делаю по гайду, поэтому причина не понятна).

**Comment by inomdzhon** [comment]
@fab4u-4empion привет

Можешь плиз в codesandbox накинуть рыбу того, как у тебя в приложении лэйаут построен на VKUI? 🙏

**Comment by fab4u-4empion** [comment]
https://codesandbox.io/s/priceless-darkness-9gkztg?file=/src/index.js

**Comment by inomdzhon** [comment]
Спасибо 🙏 

Теперь понял о чём речь. Проблема известная 😞 Из-за реализации `FixedLayout` пока сложно эту проблему поправить без брейкинг чендж как для пользователя, так и для кроссбраузерности. Закрою в пользу существующего issue, где уже обсуждалась проблема. Прошу подписаться на него.

---

Duplicate of #2422
