### ISSUE TITLE
Разные цвета у action в Alert на iOS и Android

### ISSUE THREAD

**Issue by NOCELL** [VKCOM/VKUI#176]
![image](https://user-images.githubusercontent.com/22259080/51426110-63c29480-1c18-11e9-9cd1-ca9b46e75b47.png)
![image](https://user-images.githubusercontent.com/22259080/51426112-658c5800-1c18-11e9-9e5f-46ec8670e22d.png)
![image](https://user-images.githubusercontent.com/22259080/51426121-789f2800-1c18-11e9-91e2-fc2869981c58.png)

**Comment by ArthurStam** [comment]
Пофикшено в 2.18.3. Обновлена документация: https://vkcom.github.io/vkui-styleguide/#!/Alert
