### ISSUE TITLE
При быстром переключении панелей во View ломается анимация

### ISSUE THREAD

**Issue by NOCELL** [VKCOM/VKUI#177]
![image](https://user-images.githubusercontent.com/22259080/51436224-e5b7c980-1cbb-11e9-90e0-701db2a27b4c.png)

**Comment by ProgrammingLanguageLeader** [comment]
Аналогичная ситуация при быстром переключении View внутри Root

**Comment by DimaDK24** [comment]
Если нужно программно 2 раза быстро переключить панели, то можно просто выждать таймаут 700ms после первого переключения.

Хак, но работает:
```javascript
this.changePanel(firstPanelId)
setTimeout(() => this.changePanel(secondPanelId), 700)
```
700 вычислил опытным путем. На iOS столько. На Андроиде немного меньше.

P.S. Лучше на время выжидания таймаута навесить ScreenSpinner, чтобы пользователь видел, что что-то грузится и для него не стало сюрпризом переключение панелей.

**Comment by YerinAlexey** [comment]
В некоторых случаях интерфейс вообще умирает. Примером такого поведения был CultureMap (вот [этот отчёт](https://vk.com/bug230508)). Этот баг исправил костылём в виде блокировки перехода и разблокировки его в `onTransition`.

**Comment by SkyGopnik** [comment]
Так может уже пофиксим, а не будем кидать всё в одно issue 2019 года?

**Comment by thoughtspile** [comment]
@SkyGopnik мне очень неловко, что этот ишью скоро пойдет в школу, но он будет един. Я вот воспроизвел в [сандбоксе](https://codesandbox.io/s/vkui-view-transition-ou655)

**Comment by eolme** [comment]
Багу уже 2 года, может что-нибудь сделаем?

**Comment by eolme** [comment]
У меня были наработки для фикса, может чем поможет https://github.com/eolme/VKUI/blob/next/src/components/View/ViewAndroid.tsx

**Comment by land47** [comment]
Репортят баг из продукта в продукт. Неприятно.

**Comment by thoughtspile** [comment]
Поломка `Root` исправлена в `4.16.0` (#1886)
