### ISSUE TITLE
[Bug] Tappable зависает

### ISSUE THREAD

**Issue by dobriy-vecher-vlad** [VKCOM/VKUI#1773]
В версии 4.12.2 сломан эффект Tappable, он не пропадает после клика по другому Cell'у.
Живой пример https://vkcom.github.io/VKUI/#/Epic.
![Скриншот 30-07-2021 215803](https://user-images.githubusercontent.com/56043431/127687013-f93741d6-a15b-4b21-bc98-ac3277f573c2.png)

**Comment by ArthurStam** [comment]
Привет, спасибо за репорт. Поправили в `4.12.3`.

**Comment by ArthurStam** [comment]
Привет, спасибо за репорт. Поправили в 4.12.3.
