### ISSUE TITLE
Работает свайп назад на iOS во View, когда есть popout

### ISSUE THREAD

**Issue by NOCELL** [VKCOM/VKUI#178]
Свойство popout используется для модальных окон, и неправильно, что можно свайпнуть панель назад, когда на есть модальное окно на нем.

![image](https://user-images.githubusercontent.com/22259080/51438370-f9742780-1cdd-11e9-9202-9dda33cfd73e.png)

**Comment by inomdzhon** [comment]
Закрываю в пользу #478

---

Duplicate of #478
