### ISSUE TITLE
[Bug] Сломался проброс параметров в Avatar

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1780]
**Описание**
Сломался проброс параметров в Avatar к img, например, srcSet и тп теперь не установить.

Сломали вот в этом коммите: https://github.com/VKCOM/VKUI/commit/7bce60a61f13d406f6e582fa49f4b408392fe520

**Версия библиотеки**
v4.12.3

**Comment by eolme** [comment]
Как вариант, можно добавить возможность пробрасывать свой компонент заместо img, так как a11y весит на родительском

**Comment by ArthurStam** [comment]
Спасибо. Исправим
