### ISSUE TITLE
[Bug] useKeyboardInputTracker сломан

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1781]
**Описание**
![image](https://user-images.githubusercontent.com/11076888/128111429-b82c4a48-5fb6-4778-9cfd-47cbbe163514.png)

**Версия библиотеки**
v4.12.3

**Comment by ArthurStam** [comment]
Привет. Можешь дать чуть больше контекста? Браузер, операционка, порядок действий. Я в доке посмотрел и cходу воспроизвести не смог.

**Comment by eolme** [comment]
В следующем релизе будет исправлено? А то пока приходится на 4.10 сидеть.

**Comment by ArthurStam** [comment]
Да, все три бага налетевших поправим. Скорее всего завтра.
