### ISSUE TITLE
[Bug] sizeY в AppRoot прокидывается на DOM ноду

### ISSUE THREAD

**Issue by land47** [VKCOM/VKUI#1783]
**Описание**
![image](https://user-images.githubusercontent.com/53087814/128167175-dc85f676-a671-4346-9cdb-db436295941d.png)

```jsx
<AppRoot sizeX={SizeType.COMPACT} sizeY={SizeType.COMPACT}>
  <App />
</AppRoot>
```

**Comment by ewgenius** [comment]
Скорее косяк типов, sizeY внутри компонента не используется и передавать его туда не надо

**Comment by movpushmov** [comment]
> Скорее косяк типов, sizeY внутри компонента не используется и передавать его туда не надо

`AppRootProps`  наследуется от `HTMLAttributes<HTMLDivElement>` и `AdaptivityProps`

`AdaptivityProps` в своём определении, как раз, и содержит sizeY:

```ts
export interface AdaptivityProps {
  sizeX?: SizeType;
  sizeY?: SizeType;
  /**
   * @ignore
   */
  viewWidth?: ViewWidth;
  /**
   * @ignore
   */
  viewHeight?: ViewHeight;
  /**
   * @ignore
   */
  hasMouse?: boolean;
}
```

Чтобы максимально исключить возможность поломки каких-то других компонентов, могу предложить такое решение:

```ts
export interface AppRootProps extends HTMLAttributes<HTMLDivElement>, Omit<AdaptivityProps, 'sizeY'>
```
