### ISSUE TITLE
Сделать обводку 1 pt у выделенного состояния поля ввода

### ISSUE THREAD

**Issue by Lihachyov** [VKCOM/VKUI#179]
У поля ввода у обычного состояния обводка сейчас 0.5 pt, а для выделенного состояния хочется сделать 1 pt (iOS и Android)

Более толстая обводка поможет лучше выделить активное поле.

![screenshot 2019-01-21 at 18 33 27](https://user-images.githubusercontent.com/3250391/51484686-39eea680-1dad-11e9-8e88-fbb8dff85283.png)

**Comment by fedorov-xyz** [comment]
Исправлено в 2.18.5, также обводка 1pt поддержана в остальных компонентах.
