### ISSUE TITLE
Добавить `.idea` в `.gitignore`

### ISSUE THREAD

**Issue by movpushmov** [VKCOM/VKUI#1790]
т.к. эта папка конфигурации IDE от Jetbrains и она напрямую не относится к проекту.

**Comment by ArthurStam** [comment]
Мы частично внесли её в .gitignore. Остальное её содержимое нужно тем, кто так же разрабатывает на webstorm. 
https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

**Comment by movpushmov** [comment]
> Мы частично внесли её в .gitignore. Остальное её содержимое нужно тем, кто так же разрабатывает на webstorm.
> https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

Хорошо

**Comment by inomdzhon** [comment]
Всё же надо добавить `.idea ` в `.gitignore`

Так как:
1. не все исползуют `WebStorm` – с таким успехом нужно хранить и поддерживать файлы конфигураций VSCode, Sublime Text и других IDE;
2. у нас есть другие инструменты для соблюдения Code Style и других соглашений;
3. `WebStorm` обновляется, по ходу работы меняешь настройки под себя из-за чего в `.idea` в любой появляется изменения, которые приходится точечно в `.gitingnore` заносить
    - #2258
    - #2838
    - #2367

**Comment by SevereCloud** [comment]
> Всё же надо добавить .idea в .gitignore

Есть вариант вообще не пихать лишнего в `.gitignore`, а заставлять всех использовать [global .gitignore](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer). Но главная проблема в "заставлять"
