### ISSUE TITLE
[Feature] Заранее неизвестное количество Panel

### ISSUE THREAD

**Issue by Sozonov** [VKCOM/VKUI#1795]
Есть такой кейс: в приложении есть тесты, где юзеру нужно выбрать один из вариантов ответа. При выборе он должен перейти к следующему вопросу. Заранее количество вопросов неизвестно, их может быть 5, а может быть 20. 
Структуру приложения нужно описать заранее и менять ее нельзя. 
Как можно сделать чтоб при переходе между вопросами была анимация смены панелей при динамическом количестве вопросов, а значит и панелей?

**Comment by 13Coconut69** [comment]
Сделать две панели и переключать между ними?

**Comment by Sozonov** [comment]
Не очень понял. У меня к примеру есть 5 вопросов в тесте и чтоб при смене вопросов была анимация справа налево я могу сделать так:

`
<Panel id={PANEL_TEST_QUESTION1} >...</Panel>
<Panel id={PANEL_TEST_QUESTION2}>...</Panel>
<Panel id={PANEL_TEST_QUESTION3}>...</Panel>
`
Но заранее количество вопросов неизвестно. Можно конечно добавить 100 панелек, чтоб уж точно хватило, но должен быть способ попроще :)

**Comment by VMatyagin** [comment]
Создайте две панели и переходите с одной на вторую, например, из 1 во 2, затем с 2 на 1. Общее состояние где угодно выше. 
100 панелек -- это уже, конечно, нарушение всего, что можно  :)

**Comment by ArthurStam** [comment]
Вопрос решен?
