### ISSUE TITLE
Баги анимации PanelHeader при использовании коллекции Root

### ISSUE THREAD

**Issue by MaxSvargal** [VKCOM/VKUI#180]
В документации сказано: 
> Внутри Epic может находиться либо коллекция Root, либо коллекция View

Отлично, хочу засунуть Root внутрь Epic что бы появилась анимация перехода между "табами".
Через Tabbar в Epic устанавливается activeView для Root. Но начинаются баги с анимацией PanelHeader при переходах, причём багует только при наличии контента на странице. Возможно при высчитывании высоты контейнера.

На видео пример: https://www.dropbox.com/s/g6lbu9oe3kk4gjs/Screen%20Recording%202019-01-22%20at%2017.53.08.mov?dl=0

Код ф-ии render:
```  
<Epic
  activeStory='main'
  tabbar={<TabBar { ...{ activeTabBar, changeTabBar } } />}>
  <Root id='main' activeView={activeTabBar}>
    <View id='first'>
      <PanelHeader>First</PanelHeader>
      ...
    </View>
    <View id='second'>
      <PanelHeader>Second</PanelHeader>
      ...
    </View>
    <View id='third'>
      <PanelHeader>Third</PanelHeader>
      ...
    </View>
  </Root>
</Epic>
```

Энивей, даже если не таким способом, то как заставить табы эпика переключаться анимировано?

**Comment by MaxSvargal** [comment]
Те же баги с PanelHeader и при переключении панелей.

**Comment by ArthurStam** [comment]
У вас неправильная структура Epic => Root => View. Почитайте внимательно эту часть документации и изучите пример: https://vkcom.github.io/vkui-styleguide/#!/Epic

**Comment by MaxSvargal** [comment]
@ArthurStam  Так что неправильного? В Root лежат View, в Root передаётся activeView для переключения.
