### ISSUE TITLE
[Bug] Не выполняется клик внутри modalPage/actionSheet

### ISSUE THREAD

**Issue by mclaran** [VKCOM/VKUI#1819]
браузер Safari

**Описание**
На странице со скрытой нижней навигацией, в модалке/action sheet не выполняется клик, вместо этого поднимается панель навигации в браузере
По повторному тапу заявка отправляется

**Версия библиотеки**
4.3 и более новые

**Шаги воспроизведения**
1- С мобильного устройства пролистать список из примера, чтоб исчезла нижняя навигация
2- открыть модалку с кнопкой
3- Нажать на кнопку

**Ожидаемое поведение**
Выполнился клик

**Пример с воспроизведением**
https://codesandbox.io/s/uj88u
есть на гифках (https://github.com/VKCOM/VKUI/pull/1490)

уже заводили это (https://github.com/VKCOM/VKUI/issues/1489)
но почему-то тут только ресайз исправили

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
