### ISSUE TITLE
Не сохраняется состояние скролла прошлой панели при свайпе назад 

### ISSUE THREAD

**Issue by NOCELL** [VKCOM/VKUI#182]
[Запись экрана 2019-01-24 в 9.44.52.zip](https://github.com/VKCOM/VKUI/files/2790500/2019-01-24.9.44.52.zip)

**Comment by ArthurStam** [comment]
Хм. Странное поведение. Там нет никакой перерисовки лишней на первой панели?

**Comment by NOCELL** [comment]
Перерисовки нет. Если поменять поменять панель без свайпа, то состояние скролла останется на прошлой панели.

**Comment by ArthurStam** [comment]
Это вообще во всех случаях свайпа воспроизводится?

**Comment by NOCELL** [comment]
Да, но при простом изменении active_panel такого не происходит.

**Comment by ArthurStam** [comment]
У меня не воспроизводится.
