### ISSUE TITLE
[Bug] Ошибка при закрытии модального окна по клику на кнопке

### ISSUE THREAD

**Issue by Lunarshade1990** [VKCOM/VKUI#1821]
Создаю модальное окно, при закрытии свайпом закрывается нормально, при нажатии на кнопку окно закрывается, но выскакивает ошибка. 

```
const closeModal = () => {
                dispatch(setActiveModal(null));
}


const modal = (
		<ModalRoot
			onClose={closeModal}
			activeModal={activeModal ? activeModal : null}>
			<ModalPage
				id="collectionFilterModal"
				header={
					<ModalPageHeader
						left={platform !== IOS && <PanelHeaderClose onClick={closeModal}/>}
						right={platform === IOS && <PanelHeaderButton onClick={closeModal}><Icon24Dismiss /></PanelHeaderButton>}
					>
						Фильтры
					</ModalPageHeader>
				}
			>
				<CollectionFilterModal/>
			</ModalPage>
		</ModalRoot>
	)
```

![image](https://user-images.githubusercontent.com/41172386/129791291-b5784fa9-1f9b-43e0-af17-20e9e8708ece.png)

**Comment by ewgenius** [comment]
Укажите версию VKUI, а еще лучше минимальный пример с воспроизведением бага в codesandbox
Можно сделать форк отсюда https://codesandbox.io/s/vkui-boilerplate-oj149

**Comment by ewgenius** [comment]
последняя версия vkui, не воспроизводится https://codesandbox.io/s/hopeful-forest-57h2h?file=/src/index.js&resolutionWidth=320&resolutionHeight=675

**Comment by Lunarshade1990** [comment]
Загадочно, но и у меня сегодня перестала ошибка появляться.

**Comment by sitenative** [comment]
Воспроизводится, если используется Root

https://codesandbox.io/s/modal-crash-ug5dn?file=/src/index.js

![image](https://user-images.githubusercontent.com/70588005/140609343-16178062-d16d-4a51-b937-a7847eebaecf.png)

**Comment by sitenative** [comment]
> последняя версия vkui, не воспроизводится https://codesandbox.io/s/hopeful-forest-57h2h?file=/src/index.js&resolutionWidth=320&resolutionHeight=675

В Вашем примере ошибка тоже воспроизводится 

![image](https://user-images.githubusercontent.com/70588005/140609935-7748ded5-0a5a-4b69-8bde-9221e13e3ae3.png)

**Comment by eolme** [comment]
@ewgenius @thoughtspile говорят воспроизводится, может как-нибудь обернем установку стилей?

**Comment by sitenative** [comment]
Проблема наблюдается при использовании PanelHeaderClose в android и web.
Если устанавливать в качестве кнопки закрытия произвольный див - ошибок не будет.
