### ISSUE TITLE
[Bug] Автозаполнение и хук useKeyboardInputTracker

### ISSUE THREAD

**Issue by rodionstaroverov** [VKCOM/VKUI#1823]
Есть проблемы в хуке `useKeyboardInputTracker`: при обычном написании, вставке текста в инпут все работает как надо, но если вставить текст через автозаполнение, то компонент падает с ошибкой `Cannot read property 'toUpperCase' of undefined` - на скриншотах все есть

![Снимок экрана 2021-08-20 в 16 33 57](https://user-images.githubusercontent.com/16692421/130234628-d33aee33-ffd0-40c4-b0f4-4ffcdb5bc6e7.png)
![Снимок экрана 2021-08-20 в 16 33 46](https://user-images.githubusercontent.com/16692421/130234634-f78d82ec-8f11-470c-81c8-ab7a1eba7d37.png)

**Comment by eugpoloz** [comment]
@rodionstaroverov привет! Не вижу, какая это версия VKUI, но баг уже приносили (#1781) и он был пофикшен в v4.12.4. Так что должно полечиться обновлением. 😉
