### ISSUE TITLE
[Bug] Выравнивание контента в элементе Button

### ISSUE THREAD

**Issue by rodionstaroverov** [VKCOM/VKUI#1840]
После изменений в релизе **v4.13.0**:

- `Button`: зафиксировали свойство `Component` у `ButtonTypography` ([#1811](https://github.com/VKCOM/VKUI/pull/1811))

Вертикальное положение контента в `Button` с prop`href` и без него отличается, причем только с prop `size="m"`
![Снимок экрана 2021-08-30 в 14 39 10](https://user-images.githubusercontent.com/16692421/131327283-0c3bffb6-3507-4481-a8d2-8a1cd53bee45.png)

https://codesandbox.io/s/keen-tree-3tqr0

**Comment by eugpoloz** [comment]
@rodionstaroverov привет!

Это дубль #1826, багу уже пофиксили в **v4.14.0**.
