### ISSUE TITLE
If one View have multi Panels, and switch to another View, when come back, part of scroll position of the Panels will lose

### ISSUE THREAD

**Issue by kai-en** [VKCOM/VKUI#185]
I made an example for this, https://codesandbox.io/s/xjq7pnv9pq
It goes like this: V1P1 -> V1P2 -> V1P3 -> V2P1 -back> V1P3(it ok for this page) -back> V1P2(now the problem, it can not remember the position of V1P2)

**Comment by ArthurStam** [comment]
Fixed in `2.18.5`
