### ISSUE TITLE
[Bug] clip-path у UsersStack не работает

### ISSUE THREAD

**Issue by dobriy-vecher-vlad** [VKCOM/VKUI#1850]
На Safari маска просто не работает, в клиенте ios вовсе пустое место вместо UsersStack__photo
v4.14.1

![clip](https://user-images.githubusercontent.com/56043431/131580715-154ecab1-f9e2-4960-a25e-8b2d6f41ab75.jpg)

**Comment by ArthurStam** [comment]
Привет. А какая версия safari и macos?

**Comment by dobriy-vecher-vlad** [comment]
Это всё с телефона, ios 15
Пофиксил у себя, вместо clip-path использую mask

**Comment by ArthurStam** [comment]
А можешь посмотреть, как тут?
https://vkcom.github.io/VKUI/pull/1889/#/UsersStack

**Comment by dobriy-vecher-vlad** [comment]
Вроде всё нормально

![img](https://user-images.githubusercontent.com/56043431/133786463-da57bef1-1aed-445e-9492-b0a9b6556830.jpg)
