### ISSUE TITLE
[Bug] Скругление не применяется к кастомным компонентам в Avatar

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1863]
**Описание**
![image](https://user-images.githubusercontent.com/11076888/132108703-09f82ed2-6b96-4c7e-bc46-8a9a8b8545e4.png)

**Версия библиотеки**
v4.14.12

**Comment by ArthurStam** [comment]
А как выглядит разметка примера? Как-то так?
```jsx
<Avatar>
  <img src={...} />
</Avatar>
```

**Comment by ArthurStam** [comment]
Как-то кастить стили того, что попадет в children — плохая практика. Потому что селектор будет выглядеть как-то так `.Avatar__children > *`. Если у того, что передано, есть свой CSS, то наш стиль его может перебить. Пример:

```jsx
<Avatar>
  <div className="MyBlock" />
<Avatar>
```
```css
/* Avatar.css */
.Avatar__children > * { width: 100% }
```
```css
/* MyBlock.css */
.MyBlock { width: 50% }
```

Наш стиль сильнее. Пользователь грустит.

В `Avatar` картинку можно передать двумя способами: через `style={{ backgroundImage }}` и через `src`. В обоих случаях она встанет чётко. Если же по каким-то причинам хочется прокинуть картинку иначе, то, имхо, следует её стилизовать самому. Особенно учитывая, что наша стилизация может части пользователей действовать во вред.

**Comment by eolme** [comment]
Разметка вот такая:
```jsx
<SimpleCell
  before={(
    <Avatar>
       <CustomImage src={...} /> {/* <img /> */}
    </Avatar>
  })
/>
```

Условно `overflow: hidden` решил бы проблему со скруглением и вываливанием картинки из Avatar

<img src="https://user-images.githubusercontent.com/11076888/132854300-d63de0cb-2e21-48d7-9aeb-9285335360f7.png" width="400" />

**Comment by ArthurStam** [comment]
Жестокое свойство. Как тебе идея бахнуть просто `width: '100%', height: '100%', borderRadius: 'inherit'`?
И расскажи плз, что умеет `CustomImage`? Может мы вообще не ту проблему решаем.

**Comment by eolme** [comment]
Много чего, анимирует загрузку через opacity, проставляет локальную фотку для дефолтных картинок (camera_50, group_50, etc)

**Comment by ArthurStam** [comment]
Учитывая, что Avatar — это надстройка над `img`, не получается реализовать `CustomImage` как враппер над ним?

**Comment by ArthurStam** [comment]
По сабжу. Мне не нравится идея с `overflow: hidden`, потому что это свойство часто стреляет в ногу. Учитывая, что юзкейс единичный, предлагаю стилизовать внутренний компонент самому. Благо можно выехать на процентах и inherit, то есть хардкодить ничо не нужно.

**Comment by thoughtspile** [comment]
> По сабжу. Мне не нравится идея с `overflow: hidden`, потому что это свойство часто стреляет в ногу. 

Мне нравится идея с `overflow: hidden`, и я не вижу как оно может стрелять в ногу в этом случае. 

> Учитывая, что юзкейс единичный, предлагаю стилизовать внутренний компонент самому. Благо можно выехать на процентах и inherit, то есть хардкодить ничо не нужно.

А это привязка к css-реализации нашего компонента, которую мы не рекомендуем.

**Comment by fedorov-xyz** [comment]
> Мне нравится идея с `overflow: hidden`, и я не вижу как оно может стрелять в ногу в этом случае.

Если потребуется поместить в Avatar что-то, что должно "высовываться" из компонента, например, индикатор онлайна или любой другой бейдж, с `overflow: hidden` гарантированно огребём.

**Comment by eugpoloz** [comment]
Хочу здесь заметить, что _AvatarIndicator_ есть в планах на когда-нибудь, так что присоединюсь к @ArthurStam и @fedorov-xyz.

**Comment by eolme** [comment]
@eugpoloz так можно повесить на children, а не на рутовый, тогда спокойно все работать будет

**Comment by ArthurStam** [comment]
Ваще да, я забыл, что у нас для `children` есть обёртка. Но остаются проблемы с шириной и высотой картинки, встроенной таким образом.

**Comment by eolme** [comment]
Так уже там кастомный компонент, это уже не часть библиотеки

**Comment by eolme** [comment]
Можно форснуть по

```css
children > * {
  width: 100%;
  height: 100%;
}
```

если хотим по-умолчанию такое поведение

**Comment by ArthurStam** [comment]
А щас получается эти свойства внутри компонента твоего зашиты?

**Comment by eolme** [comment]
Сейчас и overflow зашит

**Comment by eugpoloz** [comment]
> Ваще да, я забыл, что у нас для children есть обёртка.

Вброшу еще полуночную мысль: `overflow: hidden;` поверх `.Avatar__children` может сломать правильное отображение для тех, кто на его отсутствие сейчас закладывается. Для той же реализации своего кастомного индикатора для аватара, например.

**Comment by ArthurStam** [comment]
Кажется, что раз `overflow` полностью не решит проблему (вложенному блоку всё ещё нужно будет докидывать `width: 100%; height: 100%`) навешивать его бессмысленно и чревато проблемами, о которых сказала Женя.
