### ISSUE TITLE
[Bug] Компонент Search

### ISSUE THREAD

**Issue by oreshkin-ay** [VKCOM/VKUI#1867]
День добрый! В копоненте search белый инпут по середине, воспроизводится только на Safari. Это баг или готовое решение?

![image](https://user-images.githubusercontent.com/17002069/132293036-b3a154bc-a389-4b8b-a0bc-4053956f0c4d.png)

**Comment by ArthurStam** [comment]
Привет. А какая версия safari? Не могу воспроизвести на 14.1.1

**Comment by oreshkin-ay** [comment]
13.1

**Comment by ArthurStam** [comment]
Всё ещё не могу воспроизвести( может у тебя какой-то флаг в сафари включен?

**Comment by oreshkin-ay** [comment]
В двух местах пробовал
Попробуй в https://www.browserstack.com/

**Comment by ArthurStam** [comment]
Если у тебя под рукой эта версия Safari, можешь чекнуть фикс плз?
https://vkcom.github.io/VKUI/pull/1891/
Так, возможно, будет быстрее
