### ISSUE TITLE
[Doc] Сломались свойства

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1906]
Например, SimpleCell:

![image](https://user-images.githubusercontent.com/11076888/133927300-00b4c218-1e50-4ed5-b6db-e9340c3c9cd3.png)

**Comment by thoughtspile** [comment]
Не то чтобы _например,_ в остальных компонентах пропсы вроде на месте.

Тут проблема видимо в пустом `SimpleCellProps extends SimpleCellOwnProps, TappableProps {}`
