### ISSUE TITLE
[Bug] не работает иконка внутри input

### ISSUE THREAD

**Issue by artstylee** [VKCOM/VKUI#1923]
**Описание**
не работает иконка внутри input

**Версия библиотеки**
    "@vkontakte/icons": "^1.128.1",
    "@vkontakte/vk-bridge": "^2.4.8",
    "@vkontakte/vk-miniapps-deploy": "0.0.25",
    "@vkontakte/vkjs": "^0.22.1",
    "@vkontakte/vkui": "^4.5.0",

**Шаги воспроизведения**
копи паст из доков 
```
      <FormItem top="С иконкой">
        <Input type="text" defaultValue="Смирнов" after={<Icon20User aria-hidden="true" />} />
      </FormItem>
```

**Скриншоты**
![Снимок](https://user-images.githubusercontent.com/56781292/134826089-d795ca0c-ad7d-4fe3-b12f-b4146e942127.JPG)

в песочнице все работает

**Comment by ArthurStam** [comment]
Привет. А точная версия либы какая? after появился с 4.6.0
https://github.com/VKCOM/VKUI/releases/tag/v4.6.0

**Comment by artstylee** [comment]
"@vkontakte/vkui": {
      "version": "4.5.0",
      
      =\
      
я ставил пакет vk-mini-apps и надеялся что там последние версии

**Comment by artstylee** [comment]
обновил заработало
