### ISSUE TITLE
[Bug] Увеличение любого места по лонг тапу на iOS 15

### ISSUE THREAD

**Issue by danillas** [VKCOM/VKUI#1927]
Шаги воспроизведения:
1. Открыть приложение Шаги (vk.com/steps)
2. Лонг тап по пункту в Топе друзей (Cell компонент)

ФР: увеличенная область появляется при лонг тапе по любому компоненту, там где она не ожидается
ОР: увеличенная область не появляется

![image](https://user-images.githubusercontent.com/26124760/135079599-1b93f4ee-e2c4-43d8-880b-a5b62373f3b8.png)

**Версия библиотеки** 4.16.0

**Comment by ArthurStam** [comment]
Исправить без лютых костылей невозможно
