### ISSUE TITLE
[Feature] Добавить индикатор завершения анимации открытия модального окна

### ISSUE THREAD

**Issue by trubachev** [VKCOM/VKUI#1935]
Наткнулись на баг что если закрыть модальное окно до завершения анимации открытия - оно зависает.

Если в ModalRoot была бы возможность передавать коллбек для отслеживания завершения анимации таких сценариев можно было бы избежать.

**Comment by inomdzhon** [comment]
Необходимое API будет в ближайшем релизе (`v4.29.0`)
