### ISSUE TITLE
[Bug] После открытия и закрытия клавиатуры появляется черная полоска внизу (ios, mvk)

### ISSUE THREAD

**Issue by mike-chrononaut** [VKCOM/VKUI#1948]
Пример - приложение https://vk.com/coupon

На телефоне должна стоять тёмная тема.
Шаги воспроизведения:
1. Открываем приложение (ios, mvk)
2. Нажимаем на status bar; после этого появляется баннер с предложением использовать приложение
3. Нажимаем на "Поиск", тем самым вызывая клавиатуру.
4. Закрываем клавиатуру, нажимая на ней кнопку "Готово"

Фактический результат:
Внизу приложения появляется полоска.
Ожидаемый результат:
Полоска внизу отсутствует.

Видео:
https://user-images.githubusercontent.com/17556906/136022794-3e2d4eea-970c-4fba-bc17-ffb7c0db58a4.MP4

**Comment by mike-chrononaut** [comment]
![image](https://user-images.githubusercontent.com/17556906/136023203-49d7675d-50fd-4040-b4dd-f2b86fd6f83f.png)

**Comment by SevereCloud** [comment]
Привет, фикс в проде
