### ISSUE TITLE
[Bug] ChipsInput теряет фокус

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1957]
https://user-images.githubusercontent.com/11076888/136411415-efa359c0-002f-4731-977a-b0320df38355.mp4

**Comment by ArthurStam** [comment]
Воспроизводится только в доке. Причина: ремаунт примера при апдейтах. На андроиде из-за поднятия клавы происходит изменение размера окна (нужно предотвращать этот апдейт, тикет есть #1739)

**Comment by eolme** [comment]
Обычный Input то не теряет

**Comment by inomdzhon** [comment]
В следующих песочницах, с учётом того, что существует две обёртки `AdaptivityProvider` (одна над песочницей, вторая непосредственно над компонентом)
- [ChipsInput](https://vkcom.github.io/VKUI/#/ChipsInput)
- [Search](https://vkcom.github.io/VKUI/#/Search)
- [FormField](https://vkcom.github.io/VKUI/#/FormField)

обновление `sizeY` сбрасывает фокус 🤔

>  🙃 [Input](https://vkcom.github.io/VKUI/#/Input) это поведение не распространяется

Если только у одной `AdaptivityProvider` обновляется `sizeY` (для теста обновлял у той, что над компонентом), то проблемы нет.

## Предложение

Предлагаю пока считать, что конечный пользователь не будет оборачивать в два `AdaptivityProvider`.

@ArthurStam @eolme что думаете?

---

#### Примечание

Этот фикс https://github.com/VKCOM/VKUI/pull/2311 предотвращает обновление `sizeY` в песочнице.

https://user-images.githubusercontent.com/5850354/159768779-6d6253a4-1fa4-4f48-8495-69d319b64dc0.mov

**Видео 1.** Визуализация исправления в эмуляторе Android 11

**Comment by SevereCloud** [comment]
Фикс в v5
