### ISSUE TITLE
На андроид 4.4 getBoundingClientRect возвращает объект без x и y

### ISSUE THREAD

**Issue by stels-cs** [VKCOM/VKUI#196]
https://github.com/VKCOM/VKUI/blob/2656b10f75e78ed56b94917eb3b9e9f5f5a39fd8/src/components/Tooltip/Tooltip.js#L53

Эта функция неверно вычисляет x и у на android 4.4.4 из-за того что getBoundingClientRect возвращает объект без ключей x и у

https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect#Notes

> Due to compatibility problems (see below), it is safest to rely on only properties left, top, right, and bottom. 

Скришон из дебагера
![Скришон из дебагера](https://user-images.githubusercontent.com/8437497/52275558-ef4e5c00-2960-11e9-8acd-6b2c79b1580c.png)

Это приводит к вот такой ошибке
![image](https://user-images.githubusercontent.com/8437497/52276017-22ddb600-2962-11e9-92e2-e30bf542e0cb.png)

**Comment by ArthurStam** [comment]
Пофикшено в 2.18.3
