### ISSUE TITLE
[Bug] Не центрирован кружочек в Radio Button на FF

### ISSUE THREAD

**Issue by Melzmr** [VKCOM/VKUI#1960]
**Описание**
Кружочек в радио батоне не центрирован

**Версия библиотеки**
"@vkontakte/vkui": "^4.14.2",

**Шаги воспроизведения**
Обычный радио баттон

**Скриншоты**
![image](https://user-images.githubusercontent.com/38521674/136556826-be010037-14a9-4871-b931-1878fedab350.png)

![image](https://user-images.githubusercontent.com/38521674/136556848-086e40ac-19fc-404c-8dc9-f2d04a03b918.png)

**Comment by ArthurStam** [comment]
Не могу воспроизвести( https://codesandbox.io/s/vkui-boilerplate-oj149 сделайте плез форк отсюда и вставьте код с воспроизведением проблемы. Может какие-то ваши внутренние стили мешают.

**Comment by eolme** [comment]
Воспроизводится на телефоне тоже:

<img src="https://user-images.githubusercontent.com/11076888/136660488-d0817489-9bc2-4a89-a686-ed0efa63c2f9.png" width="400"/>

**Comment by thoughtspile** [comment]
Могу получить похожий эффект в любом браузере при масштабировании

<img width="184" alt="Снимок экрана 2021-10-12 в 18 25 02" src="https://user-images.githubusercontent.com/5262915/136984703-24710b84-30df-43c0-8a54-82ebec9485e3.png">

<img width="260" alt="Снимок экрана 2021-10-12 в 18 25 29" src="https://user-images.githubusercontent.com/5262915/136984775-2db7299e-922d-43fa-adf9-e4feee26008c.png">

**Comment by SevereCloud** [comment]
Привет, переписал иконку на svg. Фикс будет доступен в v4.32.0
