### ISSUE TITLE
[Bug] Иногда залипает vkuiTappable--active-opacity

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#1967]
**Описание**
Иногда `Tappable` (`Button`) залипает в состоянии active и на него вешается `opacity: .7`

Воспроизводилось несколько раз на платформе mvk с мышкой.

<img src="https://user-images.githubusercontent.com/11076888/136805330-5ac13e00-19aa-4869-9472-a81ce160d426.png" width="600" />

**Версия**
v4.17.0

**Comment by inomdzhon** [comment]
Видимо действительно в #1944 поправили

По-крайней мере в `v4.30.0` не воспроизводится

Проверял у `IconButton` в https://vkcom.github.io/VKUI/#/SimpleCell, у которого `activeMode="opacity"` если это iOS

https://user-images.githubusercontent.com/5850354/169255064-cf2df6e4-df61-4fef-a731-873272bf6504.mov

---

Если не прав, то переоткрой, пожалуйста

И спасибо за репорт 🙏
