### ISSUE TITLE
Необходим полифил для matches на андроид 4.4

### ISSUE THREAD

**Issue by stels-cs** [VKCOM/VKUI#197]
https://github.com/VKCOM/VKUI/blob/2d97b531076151423af9e42fa3e408dbd2c3ab5b/src/lib/polyfills.js#L6

https://caniuse.com/#feat=matchesselector
![image](https://user-images.githubusercontent.com/8437497/52277887-ccbf4180-2966-11e9-90d1-8e63db30059c.png)

**Comment by stels-cs** [comment]
![image](https://user-images.githubusercontent.com/8437497/52278262-ae0d7a80-2967-11e9-857f-e32d3f28d788.png)

**Comment by ArthurStam** [comment]
Пофикшено в 2.18.3
