### ISSUE TITLE
[Bug] светлый Search в темной теме

### ISSUE THREAD

**Issue by demark-pro** [VKCOM/VKUI#1972]
**Описание**
Когда деплоишь, вот так выглядит Search

**Скриншоты**
![image](https://user-images.githubusercontent.com/87781788/137219481-17c78886-186a-4ab6-9c07-0831f42b3f50.png)
![image](https://user-images.githubusercontent.com/87781788/137219856-9d90d25a-5663-4a07-afde-29e5726da1eb.png)

**Comment by stoope** [comment]
TODO: обновить репозиторий https://github.com/VKCOM/create-vk-mini-app
