### ISSUE TITLE
Alert и Snackbar сломаны на Chrome Canary

### ISSUE THREAD

**Issue by worldwidebaby** [VKCOM/VKUI#1974]
**Описание**
Не вызывается callback-функция, передаваемая в onClose. Интерфейс зависает.
Посмотреть: https://vkcom.github.io/VKUI/#/Alert

**Версия библиотеки**
4.18.0

**Версия браузера**
97.0.4671.0

**Comment by thoughtspile** [comment]
Все, хром успели [ревертнуть](https://bugs.chromium.org/p/chromium/issues/detail?id=1261155) до выкатки в дев, мы молодцы
