### ISSUE TITLE
[Bug] Maximum update depth exceeded у CustomSelect (DatePicker)

### ISSUE THREAD

**Issue by LazyTechwork** [VKCOM/VKUI#1975]
**Описание**
Вылетает ошибка `Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.` при попытке нажатия на любой select у DatePicker.

**Версия библиотеки**
4.18.0

**Шаги воспроизведения**
Код DatePicker:
```jsx
<DatePicker
    min={{day: 25, month: 1, year: 2020}}
    max={{
        day: currentDate.getDate(),
        month: currentDate.getMonth(),
        year: currentDate.getFullYear()
    }}
    onDateChange={(value) => {
        member.joined = `${value.day}.${value.month}.${value.year}`;
    }}
    dayPlaceholder="ДД"
    monthPlaceholder="ММММ"
    yearPlaceholder="ГГГГ"
    defaultValue={{
        day: parseInt(parsedDate[0]),
        month: parseInt(parsedDate[1]),
        year: parseInt(parsedDate[2]),
    }}
/>
```

**Скриншоты**
![image](https://user-images.githubusercontent.com/25130565/137602631-3b5f9500-8b8e-478d-9794-07258c508d23.png)

**Comment by LazyTechwork** [comment]
Отбой, чисто мой косяк. При передаче неверных значений в `defaultValue` компонент крашит.

**Comment by eolme** [comment]
Так опиши правильно: при передаче NaN компонент крашится

**Comment by LazyTechwork** [comment]
> Так опиши правильно: при передаче NaN компонент крашится

Подтверждаю, при передаче любых, отличных от number, значений компонент крашится.

**Comment by eolme** [comment]
Следовательно, нужно отредактировать и открыть
