### ISSUE TITLE
[Doc] Обновить примеры кода

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#1985]
В документации некоторых компонентов устарел редактируемый код. Например:

- [ActionSheet](https://vkcom.github.io/VKUI/#/ActionSheet): `View` использует устаревшее свойство `popout`
- [Alert](https://vkcom.github.io/VKUI/#/Alert): `View` использует устаревшее свойство `popout`
- [ScreenSpinner](https://vkcom.github.io/VKUI/#/ScreenSpinner): `View` использует устаревшее свойство `popout`

Таких мест может быть довольно много, так что стоит пройтись по доке и их проверить.

**Comment by inomdzhon** [comment]
@eugpoloz а это актуально? вижу в прикрепленном PR `View` больше не использует `popout`

**Comment by eugpoloz** [comment]
@inomdzhon насколько я помню, у нас в доке были не только для View устаревшие примеры, я думала в рамках этой задачки посмотреть в принципе, где что еще нужно обновить.
