### ISSUE TITLE
[Bug][UsersStack] Перекрытие элементов

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#2000]
**Описание**
Воспроизводится только на устройствах с iOS.
Передаем в компонент более 1 ссылки на изображение, компонент рендерит несколько элементов, но все последующие перекрываются первым элементом.

**Версия библиотеки**
4.19.0

**Скриншоты**
https://user-images.githubusercontent.com/42776347/139053991-d7d4455b-e627-4b08-90cb-334145738910.mp4

**Comment by SevereCloud** [comment]
Фикс в [v4.33.0](https://github.com/VKCOM/VKUI/releases/tag/v4.33.0)
