### ISSUE TITLE
[Bug][Cell] Залипает перетаскивание на iOS при зажатии

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#2001]
**Описание**
iOS 15.
Если перетаскивать элемент с зажатием, то на второй раз происходит залипание. 

**Версия библиотеки**
4.19.0

**Скриншоты**
https://user-images.githubusercontent.com/42776347/139057030-3a5d7c1d-538a-4f71-8fd2-fd2b2ac919a6.mp4

**Comment by ArthurStam** [comment]
Но на iOS по идее и так `user-select: none`, потому что он [наследуется](https://github.com/VKCOM/VKUI/blob/master/src/components/AppRoot/AppRoot.css#L19) от `.AppRoot--no-mouse`

**Comment by MrZillaGold** [comment]
Да, так и есть, проблема видимо не в этом, хотя показалось, что фиксит.

**Comment by pfrankov** [comment]
Требуется больше информации для воспроизведения.
