### ISSUE TITLE
[Bug] Некорректный цвет текста у FormStatus на платформе vkcom

### ISSUE THREAD

**Issue by NovaStream2030** [VKCOM/VKUI#2002]
**Описание**
При теме vkcom_light, платформе vkcom и mode="error", текст отображается некорректным красным цветом. Скорее всего, это связано с добавлением новой темы vkcom_dark.

**Версия библиотеки**
4.20.0

**Скриншоты**
![image](https://user-images.githubusercontent.com/21084913/139115666-d2eae962-24bb-492c-b64a-1b46b244157c.png)

**Пример с воспроизведением**
Можно увидеть сразу же в стайлгайде https://vkcom.github.io/VKUI/#/FormStatus

**Comment by ArthurStam** [comment]
Ждём фикс в https://github.com/VKCOM/Appearance
