### ISSUE TITLE
[Bug] Модалки ломаются, если начальная высота контента 0px

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#2008]
**Версия библиотеки**
v4.20.0

**Пример с воспроизведением**
https://codesandbox.io/s/summer-frost-q79ry?file=/src/index.js

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
