### ISSUE TITLE
[Feature] after у ActionSheetItem

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#2017]
По аналогии с `selectable`, чтобы можно было, например, свои иконки туда передавать.

**Comment by ArthurStam** [comment]
Не смогли придумать, зачем это может быть нужно. Есть реальный кейс?

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.0" target="_blank">v5.9.0</a> 🎉
