### ISSUE TITLE
[Feature] Вынести пробрасывание платформы в компонентах

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#2019]
Предлагаю выставлять платформу в каком-нибудь рутовом компоненте и вынести платформы из компонентов. Стили изменятся, например, с `.View--ios` на `.vkui-ios .View`. Это уберет дублирование платформы в каждом компоненте и в теории упростит их стилизацию.

**Comment by thoughtspile** [comment]
_но_ это также увеличит специфичность селекторов и наломает кастомизаций и оверрайдов

**Comment by eolme** [comment]
Можно отложить на v5, как ресерч улучшений

**Comment by ArthurStam** [comment]
Что улучшим? Количество классов уменьшится, но на что это повлияет? На размер приезжающего HTML при SSR? Возможно, но нужно чекнуть, насколько он уменьшится. Поинт про специфичность валидный.

**Comment by thoughtspile** [comment]
Наброшу практичный кейс: сейчас цсс-кастомизации по платформе очень ломкие: наличие платформенного модификатора `--ios / --vkcom / --android` — деталь реализации, он может исчезнуть внутри мажора и сломать кастомизацию.

Наброшу и пойнт против: придется костылять, чтобы рисовать без айфрейма примеры с выбором платформы.

Кажется, лучше было бы всегда пропускать класс блока через `getClassName`.

**Comment by inomdzhon** [comment]
Модификатор платформы в компоненте для меня выглядит приемлемым, т.к.

1. Повторюсь, уменьшается специфичность.
2. Для некоторых компонентов в JS коде так и так необходимо получать `platform` (например, в `Tappable`).
3. Мы не зависим от класса глобального селектора `vkui`
