### ISSUE TITLE
[Bug] При переключении Snackbar старый залипает

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#2021]
Если сменить один `Snackbar` на другой, то старый не меняется на новый.

**Comment by thoughtspile** [comment]
В снекбаре нет никакой логики, чтобы он залипал — вот пример, все заменяется: https://codesandbox.io/s/objective-banach-bmerz?file=/src/index.js:558-576 Значит, проблема в кастомном менеджере снекбаров.

Можно пообсуждать, что таймаут остается от прошлого снекбара и смена происходит без анимации — если это не ок, поможет ремаунт через смену `key` (в том же примере за чекбоксом). Это хорошее поведение — по умолчанию снекбар "обновляется" (например, можно сделать снекбар с обратными отсчетом), но есть и способ "заменять".

**Comment by thoughtspile** [comment]
Ваш ход мистер @eolme, закрываем или я что-то упускаю?

**Comment by eolme** [comment]
Обдумаю на досуге, как будет удобнее, пока пусть закрытый будет
