### ISSUE TITLE
[Bug] Overflow в ModalCard

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#2023]
Если текст в копках больше самой карточки, то она вылезает за пределы экрана

<img src="https://user-images.githubusercontent.com/11076888/139541564-911cf59b-2dfb-4d09-a76f-cbe1932cb34b.png" width="400" />

**Comment by eolme** [comment]
Динамически проставлять `actionsLayout` не всегда возможно, если текст в кнопках прилетает из локализации.

**Comment by thoughtspile** [comment]
+ кейс https://codesandbox.io/s/confident-wozniak-5xf5r
