### ISSUE TITLE
[Bug] ModalPage не закрывается при тапе сбоку

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#2030]
![image](https://user-images.githubusercontent.com/11076888/139561455-1df81668-5506-4a1b-aa93-4905b5ace7d1.png)

**Пример с воспроизведением**
https://codesandbox.io/s/silent-river-emjgk?file=/src/index.js:1021-1035

**Comment by inomdzhon** [comment]
В последней версии `v4.43.0` не воспроизводится, как и в последующих версиях
