### ISSUE TITLE
[Bug] У before и after SimpleCell отсутствуют отступы

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#2031]
Если у `before`/`after` больше чем стандартная высота, то отсутствуют отступы сверху и снизу

<img src="https://user-images.githubusercontent.com/11076888/139561593-827c099f-6af8-4124-b897-52f597a073c8.png" width="400" />

<img src="https://user-images.githubusercontent.com/11076888/139561554-7657420f-e81b-461c-89aa-d283ca392af1.png" width="400" />

**Comment by ArthurStam** [comment]
В SimpleCell по дизайну у нас допускаются аватарки определенных размеров: 28|32|40|48|72. Для них отступы прописаны. Для всех остальных — нет. Думаю, что если хочется использовать аватарки нестандартных для этого контейнера размеров, то можно и стили накинуть самому.
