### ISSUE TITLE
[Bug] Компонент Search неправильно отображается на некоторых iphone (только внутри приложения VK, не m.vk)

### ISSUE THREAD

**Issue by tayurus** [VKCOM/VKUI#2039]
**Описание**
Вот так стал отображаться Search на iOS в приложение vk.com/coupon
![image](https://user-images.githubusercontent.com/15295424/139863703-8d616d4c-f4d3-4c24-b3b5-b11b71e01673.png)
 

**Версия библиотеки**
  "@vkontakte/vkui": "^4.16.0",

**Скриншоты**
Вот так отображается на Iphone 12 Pro
![image](https://user-images.githubusercontent.com/15295424/139863929-9d4eae21-d0e2-41a5-8a9c-724a9333bdd6.png)

На iphone XR все отображается нормально.

У всех, у кого воспроизводится проблема, iOS 15.1

**Пример с воспроизведением**
vk.com/coupon

**Comment by ArthurStam** [comment]
Похоже, в iOS 15.1 закрался баг
http://www.openradar.me/FB9744107
