### ISSUE TITLE
[Bug] WriteBar имеет внутренний скролл со второй по пятую строку

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#2040]
**Описание**
В зависимости от объема веденного текста компонент WriteBar умеет увеличиваться по высоте не более чем на 5 строк, и только начиная с шестой строки должен появляться скролл, но он появляется начиная со второй строки.

**Версия библиотеки**
v4.20.0

**Шаги воспроизведения**
Поочередно вводим от одной до пяти строк. Со второй по пятую строку WriteBar увеличивается, но при этом имеет внутренний скролл. 

**Ожидаемое поведение**
Поочередно вводим от одной до пяти строк. Со второй по пятую строку WriteBar увеличивается, внутреннего скролла нет. Внутренний скролл появляется начиная с шестой строки.

**Скриншоты**
![image](https://user-images.githubusercontent.com/22776192/139863872-3eaaed9a-d2a8-4931-9df8-4fcaf1d166f9.png)
![image](https://user-images.githubusercontent.com/22776192/139863893-ae798479-ce9f-429b-8230-e38e02e12788.png)
![image](https://user-images.githubusercontent.com/22776192/139863914-da52612f-0e56-43d0-a857-9d038395491e.png)
![image](https://user-images.githubusercontent.com/22776192/139863939-92ed6dd5-2ea5-44ae-b1dd-25824ede28f1.png)
![image](https://user-images.githubusercontent.com/22776192/139863952-9864ee8f-8ac9-46b1-8aff-b2330891f59c.png)
![image](https://user-images.githubusercontent.com/22776192/139863967-65deabdd-a259-4586-bc1d-b40c1f8a882d.png)

**Пример с воспроизведением**
Воспроизводится в любом варианте адаптации, можно посмотреть в демо документации.
https://vkcom.github.io/VKUI/#/WriteBar

**Comment by SevereCloud** [comment]
Привет, фикс в [v4.33.2](https://github.com/VKCOM/VKUI/releases/tag/v4.33.2)
