### ISSUE TITLE
[bug][react-18] Моргание экрана после перехода назад

### ISSUE THREAD

**Issue by worldwidebaby** [VKCOM/VKUI#2043]
**Описание**

https://user-images.githubusercontent.com/53087814/140001231-e0af543f-7734-40da-898e-44c530126a77.mp4

**Версии библиотек**
react@alpha
react-dom@alpha

**Пример с воспроизведением**
https://codesandbox.io/s/trusting-tesla-b9oz5

**Comment by ArthurStam** [comment]
Речь про моргание?

**Comment by land47** [comment]
> Речь про моргание?

Да

**Comment by Lunarshade1990** [comment]
Тоже сегодня столкнулась с морганием. У меня есть родительский компонент вью со стейтом, который передаёт данные в дочерние компоненты-панели, и при переходе назад невозможно очистить стейт - возникает ошибка в панели, с которой уходишь.
