### ISSUE TITLE
[Bug] При быстром переключении panel не вызывается onTransition

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#2045]
Видимо связано с зависанием `View` #177

**Comment by thoughtspile** [comment]
В принципе чинится #2052, но интересный вопрос — сколько раз должен вызываться `onTransition` и с какими параметрами?

В кейсе `v1 -> v2 -> v3`: 
- два раза, с `v1 -> v2` + `v2 -> v3`? Если да, то в какой момент вылетает `v1 -> v2` — при начале перехода на `v3` или после окончания всех переходов?
- один `v1 -> v3` (объединенный переход)?
- `v2 -> v3` (последний переход)?

По итогам #2052 и в Root по итогам #1886 будет `v2 -> v3`.

В кейсе `v1 -> v2 -> v1` еще может быть 0, тк никакого перехода на самом деле не произошло.

**Comment by eolme** [comment]
Вообще достаточно один раз после всех быстрых манипуляций, кейс использования вызвать кастомную анимацию, когда все готово.

Вообще, если так посмотреть, можно в этом кейсе использовать хук `useNavTransition`
