### ISSUE TITLE
[app]vk.com

### ISSUE THREAD

**Issue by Admin-AraKanTeam** [VKCOM/VKUI#2049]
#1248 `app`

**Comment by thoughtspile** [comment]
Тут тоже что то не так

**Comment by Admin-AraKanTeam** [comment]
***@***.*** ***@***.***>>,
***@***.*** ***@***.***>*

***@***.*** ***@***.***>, Yarzar
Kyawthein ***@***.*** ***@***.***>>*


၂၀၂၁၊ နို ၈၊ တနင်္လာ ညနေ ၃:၅၉ တွင် Vladimir Klepov ***@***.***>
က ရေးခဲ့သည်−
