### ISSUE TITLE
[Bug] HorizontalScroll не работает при правом скролбаре

### ISSUE THREAD

**Issue by ajikcey** [VKCOM/VKUI#2078]
**Описание**
Если пролистать список до конца, то в обратную сторону перестает реагировать. 
Важное замечание: в body должен быть правый скролбар или overflow: scroll

**Версия библиотеки**
v.4.21.0

**Шаги воспроизведения**
1. в body добавить overflow: scroll
2. пролистать горизонтальный список вправо до конца
3. перестает реагировать на пролистывание влево
(воспроизводится даже в айфрейме https://vkcom.github.io/VKUI/#/HorizontalScroll)

**Ожидаемое поведение**
Корректного пролистывание горизонтального списка.

**Скриншоты**
http://c2n.me/4dXbxKr

**Comment by ajikcey** [comment]
Добавлю уточнение - проблема замечена на Windows. На macOS проблемы нет, так как там скролбар не занимает место.

**Comment by ajikcey** [comment]
Вот этот элемент тоже перестает работать, если пролистать до конца.
https://vkcom.github.io/VKUI/#/CardScroll
Кстати пролистывание ломается после пролистывания с помощью стрелок.

**Comment by rodionstaroverov** [comment]
> Вот этот элемент тоже перестает работать, если пролистать до конца. https://vkcom.github.io/VKUI/#/CardScroll Кстати пролистывание ломается после пролистывания с помощью стрелок.

в моем кейсе скролл перестает работать после первого прокручивания вперед с помощью стрелок, так же только на windows

**Comment by SevereCloud** [comment]
Привет, фикс будет доступен в следующей версии v4.33.0
