### ISSUE TITLE
[Doc] Сломалось меню на мобильных

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#2082]
<img src="https://user-images.githubusercontent.com/11076888/141644107-ca32974a-0f6f-4ad2-82d7-2c171a2e527b.png" width="400">

**Comment by eugpoloz** [comment]
@eolme спасибо за репорт! 

Подскажи, пожалуйста, какой у тебя девайс и браузер? В эмуляторе не могу воспроизвести.

**Comment by eolme** [comment]
У меня PIxel 5 с канарейкой хрома, возможно что-то поменяли

**Comment by eugpoloz** [comment]
@eolme возможно! Пока звучит как баг мобильной канарейки, мы нигде не смогли воспроизвести. Попробуй на стабильной версии хрома, там ок?

**Comment by eolme** [comment]
Закрываю, потому что больше не воспроизводится
