### ISSUE TITLE
[Doc] Передача параметра vk_platform в ConfigProvider

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#2083]
Из https://vkcom.github.io/VKUI/#/PlatformsAndThemes складывается ощущение, что можно взять параметр vk_platform и передать его в ConfigProvider, но это не так.

`Исключением является кейс встраивания вашего мини-приложения в vk.com. В этом случае пока нужно передавать платформу явно. Значение платформы можно получить из query-параметра vk_platform.`

**Comment by inomdzhon** [comment]
С [v4.29.1](https://github.com/VKCOM/VKUI/releases/tag/v4.29.1) VKCOM теперь определяется автоматически.

Доку поправили 👍 

---

Спасибо за репорт 🙏
