### ISSUE TITLE
[Bug] Не работает пролистывание TextArea в ModalPage или ModalCard

### ISSUE THREAD

**Issue by ajikcey** [VKCOM/VKUI#2086]
**Описание**
Если TextArea расположен в ModalPage или ModalCard, то не работает пролистывание поля ввода. Вместо этого модальное окно закрывается.

**Версия библиотеки**
4.21.0

**Шаги воспроизведения**
1. Открыть ModalPage или ModalCard с TextArea
2. Ввести достаточно текста, чтобы появился скролбар.
3. Попытаться проскролить содержимое TextArea

**Результат**
Модальное окно закрывается.

**Ожидаемое поведение**
Скрол в TextArea работает корректно и модальное окно не закрывается.

**Comment by ajikcey** [comment]
Реализовал модальное окно с помощью PopoutWrapper, которое не закрывается смахиванием. Окно перестало закрываться, однако Textarea по прежнему не скролится.

**Comment by MrZillaGold** [comment]
Дубль #335
