### ISSUE TITLE
[Bug] Warning: `NaN` is an invalid value for the `marginTop` css style property.

### ISSUE THREAD

**Issue by land47** [VKCOM/VKUI#2087]
**Описание**
Выбрасывается предупреждение после перехода на предыдущую панель, после первого рендера приложения.

**Версия библиотеки**
4.21.1

**Пример с воспроизведением**
https://codesandbox.io/s/hopeful-sky-q33md?file=/src/app.js

**Comment by shastox** [comment]
В версии 4.24.0 проблема по прежнему присутствует, fix не помог.

**Comment by stoope** [comment]
@shastox фикс не попал в 4.24.0, будет доступен в следующем релизе
