### ISSUE TITLE
[Bug] Switch имеет cursor: default на десктопе

### ISSUE THREAD

**Issue by Mashtapok** [VKCOM/VKUI#2096]
**Описание**
Компонент Switch не имеет `cursor: pointer` на десктопе

**Версия библиотеки**
4.20.0

**Пример с воспроизведением**
[песочница](https://codesandbox.io/s/funny-darkness-8eylc?file=/src/index.js)

**Comment by MrZillaGold** [comment]
https://github.com/VKCOM/VKUI/commit/6b470597e76652a2f95fbfd5d030e45e34ca7bd6 Поправили в 4.22.0

**Comment by eugpoloz** [comment]
Даже в [4.21.0](https://github.com/VKCOM/VKUI/releases/tag/v4.21.0). Обновила release notes, чтобы это отразить.

@MrZillaGold, спасибо огромное за бдительность! 🤗
