### ISSUE TITLE
FormLayout с вложенным массивом children падает с ошибкой

### ISSUE THREAD

**Issue by avinograd0v** [VKCOM/VKUI#210]
Если в FormLayout поля создаются итерацией по какому-то массиву, и при этом есть другие дети, то код падает с ошибкой.
Ошибка:
![image](https://user-images.githubusercontent.com/22392706/53032831-b219bc00-3480-11e9-983f-800af0be19f9.png)

Код приводящий к ошибке:
![image](https://user-images.githubusercontent.com/22392706/53032802-a0d0af80-3480-11e9-8b74-ad3a1c44edf5.png)

Проблема в итерации по массиву детей, решается с помощью React.Children.map

**Comment by fedorov-xyz** [comment]
Исправлено в версии 2.18.4
