### ISSUE TITLE
[Bug] Progress: полоска прогресса выезжает за интерфейс если указать значение >100

### ISSUE THREAD

**Issue by Roman-Shubnikov** [VKCOM/VKUI#2105]
Если указать больше 100% полоска прогресса ведёт себя непредсказуемо и уходит за интерфейс

4.22.0

Добавьте компонент на страницу и укажите ему атрибут value больше 100

![Screenshot_34](https://user-images.githubusercontent.com/62247180/142762767-307284c7-2393-41c4-99b9-f99ed5a00a89.png)
.

**Comment by MrZillaGold** [comment]
#2104

**Comment by MrZillaGold** [comment]
#2103

**Comment by ArthurStam** [comment]
Спасибо за репорт и фикс! Появится в следующем релизе.
