### ISSUE TITLE
[Bug] PanelHeader не отображает то, что предано в right

### ISSUE THREAD

**Issue by hripunov** [VKCOM/VKUI#2111]
**Описание**
В PanelHeader при передаче чего-либо (иконка, текст, и т. д.) в prop **right** ничего не передаётся и, как следствие, не отрисовывается.

**Версия библиотеки**
4.22.2
под Windows 10, Chrome/Firefox

**Шаги воспроизведения**
Берём один из стандартных PanelHeader из [документации](https://vkcom.github.io/VKUI/#/PanelHeader) и используем в самой простой структуре экранов. Дополнительно пробуем передать в right текст или что-то ещё - тишина.

**Пример с воспроизведением**
<details>

```javascript
import React from "react";
import ReactDOM from "react-dom";
import {
  AdaptivityProvider,
  ConfigProvider,
  AppRoot,
  View,
  Panel,
  PanelHeader,
  Header,
  Group,
  SimpleCell,
  PanelHeaderButton,
  PanelHeaderBack,
  Counter
} from "@vkontakte/vkui";
import {
  Icon28PictureOutline
} from "@vkontakte/icons";
import "@vkontakte/vkui/dist/vkui.css";
 
const App = () => {
 
  return (
    <AppRoot>
      <View activePanel="main">
        <Panel id="main">
          <PanelHeader
            left={<PanelHeaderBack />}
            right={<PanelHeaderButton label={<Counter size="s" mode="prominent">21</Counter>}><Icon28PictureOutline/></PanelHeaderButton>}
          >
            Панель
          </PanelHeader>
          <Group header={<Header mode="secondary">Items</Header>}>
            <SimpleCell>Hello</SimpleCell>
            <SimpleCell>World</SimpleCell>
          </Group>
        </Panel>
      </View>
    </AppRoot>
  );
};
 
ReactDOM.render(
  <ConfigProvider>
    <AdaptivityProvider>
      <App />
    </AdaptivityProvider>
  </ConfigProvider>,
  document.getElementById("root")
);
```
</details>

**Comment by MrZillaGold** [comment]
Необходимо явно указать, что ваше приложение это не VK Mini App, делается это через компонент [ConfigProvider](https://vkcom.github.io/VKUI/#/ConfigProvider) `webviewType` параметр. Если `webviewType` === WebviewType.VKAPPS, `PanelHeader` игнорирует `right` параметр, так как там рисуются системные кнопки для управления приложением.

**Comment by hripunov** [comment]
Моя вина. Закрываю.
