### ISSUE TITLE
[Bug] В Яндекс Браузере не отображается Tabbar (Epic) на Android.

### ISSUE THREAD

**Issue by Zaur-Lumanov** [VKCOM/VKUI#2114]
**Описание**
В Яндекс Браузере не отображается Tabbar внутри Epic.

**Версия библиотеки**
4.16.0

**Шаги воспроизведения**
Можно увидеть в приложении m.vk.com/checkback, открыв в Яндекс Браузере.

**Скриншоты**
![image](https://user-images.githubusercontent.com/12500042/143588457-be8cce4f-ba7b-4495-9914-030be9345d66.png)

**Comment by thoughtspile** [comment]
Интересно, почему при скорее не исчезает браузерный навбар

**Comment by eolme** [comment]
Это скорее баг мвк нежели VKUI

**Comment by SevereCloud** [comment]
Баг m.vk.com

https://user-images.githubusercontent.com/14944123/163860079-b73f426b-9b5d-48b1-9a99-d5ba5a26c4fa.mp4

**Comment by SevereCloud** [comment]
Привет, фикс в проде
