### ISSUE TITLE
[Bug] Некорректный padding в PanelHeader на Android-устройствах без поддержки CSS переменных

### ISSUE THREAD

**Issue by k-egor-smirnov** [VKCOM/VKUI#2116]
**Описание**
Из-за того, что фоллбек CSS-переменной `safe-area-inset-top` установлен в 20px, на старых Android устройствах ставится такой же padding-top, и PanelHeader растягивается сильно вверх. Нужно либо сделать на [этой строчке](https://github.com/VKCOM/VKUI/blob/feb221d5cace221b157b578d9ae25d5b9ae7a232/src/components/PanelHeader/PanelHeader.css#L163) отдельный фоллбек в 0px, либо убрать этот фоллбек из переменной совсем, если он уже не нужен (был добавлен во 2 версии 3 года назад)

**Версия библиотеки**
4.22.2 (на самом деле, любая)

**Шаги воспроизведения**
1. Открыть PanelHeader в Android Browser 4.4

**Ожидаемое поведение**
Корректный фоллбек padding-top для старых устройств

**Comment by pfrankov** [comment]
Исправлено в 4.29.1
