### ISSUE TITLE
[Bug][Cell] Кликабельный removable элемент при disabled статусе

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#2148]
**Описание**
Вешаем на Cell removable и disabled, ячейка перестает быть кликабельной, но с removable элементом все еще можно взаимодействовать и удалять саму ячейку.

**Версия библиотеки**
4.23.0

**Ожидаемое поведение**
Либо убираем крестик удаления, либо делаем его некликабельным.

**Скриншоты**
![image](https://user-images.githubusercontent.com/42776347/145795215-c21248d7-2c37-4b9d-9132-b8b9a6d4b641.png)

**Comment by ArthurStam** [comment]
Решили, что это не баг. Если ячейка `disabled, то не нужно делать её `removable` и наоборот.

**Comment by eolme** [comment]
@ArthurStam так автоматически тогда нужно выключать `removable`?

**Comment by ArthurStam** [comment]
Оставлю это на откуп разработчикам
