### ISSUE TITLE
[Bug] После свайпа галлереи теряется фокус на слайде

### ISSUE THREAD

**Issue by PhantomDC** [VKCOM/VKUI#2158]
**Описание**
После свайпа галлереи, теряется фокус на следующем слайде, после чего кнопка кликается со второго раза. Воспроизводится только на мобильных девайсах.

**Версия библиотеки**
4.23

**Шаги воспроизведения**
- Создать галлерею как минимум из 2х слайдов
- Добавить кнопки к каждому слайду
- Свайпнуть галлерею
- Нажать на кнопку
- Кнопка нажимается со второго раза

**Ожидаемое поведение**
Фокус на слайде остается и кнопка нажимается с первого раза

**Пример с воспроизведением**
[Форк](https://codesandbox.io/s/romantic-rui-5xs1j)

**Comment by PhantomDC** [comment]
Поресерчили еще и поняли, что дело скорее в компоненте Button, потому что с обычной нативной кнопкой все работает как надо

https://user-images.githubusercontent.com/15895396/146174110-bb4369fb-c8ac-429b-be55-4169c6754632.mp4

**Comment by Melzmr** [comment]
https://codesandbox.io/s/focused-ardinghelli-60uvx

сендбокс послед. видео

**Comment by inomdzhon** [comment]
Фух, это было потно....

Нашёл виновника торжества

https://github.com/VKCOM/VKUI/blob/5ea23593f58fad218def1a558cc2a0326367f9a6/src/components/Button/Button.tsx#L214-L220

У кнопки `stopPropagation` по умолчанию `true` (см. 219 строчку).

## Решение

На примере [форка](https://codesandbox.io/s/romantic-rui-5xs1j?file=/src/index.js:963-1083), добавьте кнопках `stopPropagation={false}`

```jsx
<Button stopPropagation={false} size="m" onClick={improveClickHandler}>
  Кнопка
</Button>
```

и всё заработает 🎉 

---

PS: С ребятами из VKUI обсудим как это задокументировать.
