### ISSUE TITLE
[bug][react-18] В режиме StrictMode со Strict Effects удаляется класс vkui

### ISSUE THREAD

**Issue by worldwidebaby** [VKCOM/VKUI#2177]
**Описание**
Из-за чего не применяются стандартные стили приложения
Про Strict Effects https://github.com/reactwg/react-18/discussions/19

**Версия библиотеки**
4.24.0

**Скриншоты**
![image](https://user-images.githubusercontent.com/53087814/147371131-d5c127e5-bb16-4895-8b98-657b7124f372.png)

**Comment by land47** [comment]
Временный хак: вынести StrictMode под AppRoot
Strict Effect сейчас включаются по умолчанию, их не отключить
