### ISSUE TITLE
[Bug] TypeError: modalState is undefined

### ISSUE THREAD

**Issue by CursedWizard** [VKCOM/VKUI#2184]
**Описание**
При двойном нажатии вне модальной страницы, возникает ошибка описанная в заголовке.

Воспроизводится на [странице документации для ModalRoot](https://vkcom.github.io/VKUI/#/ModalRoot).

Ошибка в функции onTouchEnd в ModalRoot.tsx (пик снизу). modalState не определен ввиду того, что this.props.activeModal равен null. Воспроизводится только в случае, если модалка единственна в истории.
![modal_func_bug](https://user-images.githubusercontent.com/67508707/147828649-840d30c5-a470-4972-8486-201976fa20b6.png)

Видел, что до этого использовался хак с "if (!modalState) return", так что такой фикс в данном случае кажется вполне валидным.

Готов сделать PR с фиксом.

**Версия библиотеки**
4.24.0

**Скриншот ошибки**
![vk_bug](https://user-images.githubusercontent.com/67508707/147828616-e1bc63b5-42e8-42ce-b27c-12eea3fd153b.png)

**Comment by thoughtspile** [comment]
См #2182

**Comment by inomdzhon** [comment]
Пофикшено в `v4.25.0`
