### ISSUE TITLE
[Bug] Gallery дергается после асинхронной установки активного слайда

### ISSUE THREAD

**Issue by worldwidebaby** [VKCOM/VKUI#2185]
**Шаги воспроизведения**
Можно посмотреть в доке, в секции с контролируемым компонентом, изменив свойство `onChange` на пример ниже
https://vkcom.github.io/VKUI/#/Gallery

```jsx
<Gallery
  onChange={index => setTimeout(() => setSlideIndex(index), 50)}
/>
```

**Кейс**
useDeferredValue/startTransition c React 18

**Версия библиотеки**
4.24.0

**Comment by inomdzhon** [comment]
Не прикрепляется ссылка к PR. Попробую закрыть и переоткрыть issue

**Comment by inomdzhon** [comment]
Не получилось...
Кароче вот PR https://github.com/VKCOM/VKUI/pull/2686
