### ISSUE TITLE
[Bug] Не применяются стили к children в компоненте PanelHeader

### ISSUE THREAD

**Issue by lexstile** [VKCOM/VKUI#2188]
**Описание**
При передаче компоненту PanelHeaderBack в children более одной текстовой ноды не применяются стили.

Так не работает:
`<PanelHeader left={<PanelHeaderBack onClick={goBack} />}>Проект {projectId}</PanelHeader>`
Так работает:
`<PanelHeader left={<PanelHeaderBack onClick={goBack} />}>{'Проект ${projectId}'}</PanelHeader>`
(Обратную кавычку заменил на одинарную, иначе некорректно отображается)

**Версия библиотеки**
4.22.2

**Ожидаемое поведение**
Стили применяются ко всем текстовым нодам.

**Скриншоты**
![image](https://user-images.githubusercontent.com/30532019/149171212-dd094acc-6d96-4708-a4dc-f4631d2d7665.png)
![image](https://user-images.githubusercontent.com/30532019/149171450-24d6f7a2-bcaa-4116-96ad-63f0bf96a27d.png)

**Comment by eugpoloz** [comment]
Привет! Это поведение было пофикшено в #2175 и войдет в ближайший релиз (v4.25.0).
