### ISSUE TITLE
[Bug][Doc] Не подтягивается комментарий для deprecated свойств

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#2198]
В документации не подтягивается комментарий для deprecated свойств. Вместо него отображается `null`.

Пример с воспроизведением — [документация Cell](https://vkcom.github.io/VKUI/#/Cell):
![image](https://user-images.githubusercontent.com/22026957/150529348-d1526ddd-26f8-4930-8ddd-36769a79abc3.png)

**Comment by SevereCloud** [comment]
Пофиксилось с появлением 4 тайпскрипта


![Image](https://user-images.githubusercontent.com/14944123/208512756-469c10b8-c0de-4c2c-92ae-5ced93252d4c.png)
