### ISSUE TITLE
[Bug] Ломается навигационная история при нажатии кнопки "Назад" после запуска из каталога мини-приложений

### ISSUE THREAD

**Issue by yurachinenov** [VKCOM/VKUI#2201]
**Описание**
Ломается навигационная история приложений при нажатии кнопки "Назад" после запуска из каталога сервисов - либо предлагает закрыть приложение, либо блокирует сервисную навигацию "Назад".

**Шаги воспроизведения**
1. Зайдите в приложение "Питомцы ВКонтакте" после перехода по прямой ссылке через каталог "https://vk.com/services".
2. Тап браузерную "Назад".
3. Тап "Отмена".
4. Перейдите к любому питомцу (у вас он должен быть).
5. Тап кнопку "Назад" в приложении

**Ожидаемое поведение**
Кнопка "Назад" при запуске из каталога сразу закрывает приложение, как реализовано, к примеру в "vk.com/app7634582" либо не приводит к нарушению работы сервисной кнопки "Назад".

**Скриншоты**
![мвк1](https://user-images.githubusercontent.com/77573092/150579744-6fa5fd81-df3d-4246-a226-4939eb01c588.JPG)
![мвк2](https://user-images.githubusercontent.com/77573092/150579765-7685c596-69d8-4b4a-b861-7b6d410b4a51.JPG)

**Пример с воспроизведением**
https://user-images.githubusercontent.com/77573092/150579914-00636726-9c7a-4596-901c-620fe2e3b41c.mp4

**Comment by yurachinenov** [comment]
Добрый день.

В #2194 совсем другой баг, связанный с тем, что приложение не успевает обрабатывать быстрые 2 перехода, в результате чего считает, словно мы перешли дважды назад, но нам отображает, что мы перешли всего 1 раз, из-за чего всё становится некликабельно.
В данном случае ломается сама навигационная история (как браузерная, так и приложения), но при этом ничего не зависает.

**Comment by SevereCloud** [comment]
Привет, это баг vk.com, а не библиотеки. В VKUI не обрабатывается браузерная история
