### ISSUE TITLE
[Bug] Нет отступа между аватаркой VK ID и всплывающим меню

### ISSUE THREAD

**Issue by 23-yo-designer-from-san-francisco** [VKCOM/VKUI#2206]
**Описание**
При нажатии на иконку VK ID открывается плашка, отступ которой не соответствует макету в фигме
(вместо margin отступ сделан через padding, при изменении на padding все выглядит должным образом)

**Версия библиотеки**
4.24.0

**Шаги воспроизведения**
1. Перейти на https://id.vk.com/account/#/personal
2. Нажать на аватар в правом верхнем углу
3. Появившаяся плашка располагается прямо под аватаркой, без отступа

**Скриншоты**
![image](https://user-images.githubusercontent.com/42890090/150787560-241b9f80-53c6-4885-9faa-99ea52bc2fd9.png)
![image](https://user-images.githubusercontent.com/42890090/150787440-c4b28730-b0e6-416f-9fd1-cc32246f5963.png)
![image](https://user-images.githubusercontent.com/42890090/150787615-9bd8c3c4-1c39-4dd4-9718-33bef37776b7.png)
![image](https://user-images.githubusercontent.com/42890090/150787638-38de6c4c-44e1-403f-b8fb-1529cc9be755.png)

**Comment by inomdzhon** [comment]
- closed by #3445
