### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by nexvilllll** [VKCOM/VKUI#2221]
**Описание**
При использовании данной библиотеки с планшетом в сервисах можно увидеть элементы старого экрана на новом.

**Версия библиотеки**
Неизвестно

**Пример с воспроизведением**
https://disk.yandex.ru/i/a0Rn_VruN5ELow

**Comment by eugpoloz** [comment]
Dublicates #2264.

Закрываю этот баг в пользу более нового: #2264 описан внятнее.
