### ISSUE TITLE
[Bug] ContentCard вылезают за границу блока приложения с использованием CardScroll

### ISSUE THREAD

**Issue by FunNikita** [VKCOM/VKUI#2236]
**Описание**
ContentCard вылезают за границу блока приложения с использованием CardScroll.

**Версия библиотеки**
4.24.0

**Ожидаемое поведение**
ContentCard при CardScroll не должен выходить за пределы Group.

**Скриншоты**
[Видео](https://disk.yandex.ru/i/XDlSFxAzWH_fPQ), [отчёт](https://vk.com/bug346109)

**Comment by SevereCloud** [comment]
Привет, фикс доступен в `4.33.1`
