### ISSUE TITLE
[Bug] Ошибка при свайпе Snackbar

### ISSUE THREAD

**Issue by VitiaCatDragon** [VKCOM/VKUI#2247]
**Описание**
При свайпе Snackbar в Firefox появляется ошибка в консоли: Uncaught TypeError: target.closest is not a function

**Версия библиотеки**
4.25.2

**Шаги воспроизведения**
1. Вызвать Snackbar
2. Свайпнуть его влево
3. Snackbar закроется, но с ошибкой в консоли

**Скриншоты**
![image](https://user-images.githubusercontent.com/60291267/153708179-be21a66c-3c7f-47c7-a6bf-1491330ace70.png)
![image](https://user-images.githubusercontent.com/60291267/153708259-8f7e6bc8-9259-4ae4-9aa8-eae580c110f5.png)

**Comment by VitiaCatDragon** [comment]
Я заметил, если свайпать быстро, то ошибки нету. А если остановится в конце, то ошибка будет.

**Comment by SevereCloud** [comment]
Спасибо, поправил(в следующей версии `v4.29.0`)
