### ISSUE TITLE
[Feature] Анимации у выпадающих меню

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#2250]
https://user-images.githubusercontent.com/11076888/153710051-80028ba4-9fa5-43c4-8eb3-683c5c4885a0.mov

See: #2249

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.0" target="_blank">v6.2.0</a> 🎉
