### ISSUE TITLE
[Bug] Просвечивается предыдущая страница при переходе на следующую

### ISSUE THREAD

**Issue by FunNikita** [VKCOM/VKUI#2264]
**Описание**
В случае, когда новые панели не совпадают по размеру с карточками предыдущего экрана, между панелей просвечивается контент предыдущего экрана, а после пропадает.

**Версия библиотеки**
4.27.0

**Скриншоты**
[Видео](https://disk.yandex.ru/i/V5Oppg96yFrWQg), [баг](https://vk.com/bug349192)

**Comment by fedorov-xyz** [comment]
Добавьте минимальный пример с воспроизведением, сделав форк отсюда https://codesandbox.io/s/vkui-boilerplate-oj149.

**Comment by FunNikita** [comment]
https://codesandbox.io/embed/dawn-smoke-i3jror?fontsize=14&hidenavigation=1&theme=dark

Необходимо расширить фрейм, пролистнуть вниз и нажать на любой SimpleCell. [Новое видео](https://disk.yandex.ru/i/EYVwXq3fL1iWMA).

**Comment by fedorov-xyz** [comment]
Не увидел в структуре приложения `SplitLayout` и `SplitCol`. Колонка должна быть как минимум одна, как указано на этой странице: https://vkcom.github.io/VKUI/#/Adaptivity

**Comment by FunNikita** [comment]
Посмотрите сейчас. Правда я до сих пор не догоняю суть данных компонентов, и про какие колонки идёт речь?

**Comment by fedorov-xyz** [comment]
Скорее всего в широком интерфейсе вообще не нужна анимация переходов между экранами. Она отключается опцией у `<SplitCol animate={viewWidth <= ViewWidth.MOBILE} />`.

**Comment by FunNikita** [comment]
Но без анимации выглядит некрасиво.

**Comment by fedorov-xyz** [comment]
Отсутствие анимации в широком интерфейсе — задуманное поведение. Предлагаю включать анимацию только по этому условию: `viewWidth <= ViewWidth.MOBILE`.

**Comment by FunNikita** [comment]
Но ведь анимация-то присутствует. Если задумано, что она там не должна быть, то, наверное, нужно по умолчанию со стороны библиотеки ее отключать.

**Comment by fedorov-xyz** [comment]
Обсудим и скорее всего сделаем автоматическое отключение анимаций. Пока предлагаю исправить баг локально.
