### ISSUE TITLE
[Bug] При переключении View в Root на десктопе появляется скролл

### ISSUE THREAD

**Issue by Andrey-Kuzmichev** [VKCOM/VKUI#2274]
**Описание**
Если использовать компонент Root для переключения View, то на несколько миллисекунд появляется скролл.
Не всегда воспроизводится.
Баг проявляется на любой платформе.

**Версия библиотеки**
Этот баг проявляется начиная с версии 4.16.0.

**Пример с воспроизведением**
https://codesandbox.io/s/vkui-issues-bug-2fkkp1

**Comment by SevereCloud** [comment]
Спасибо за issue, фикс будет доступен в `v4.28.2`
