### ISSUE TITLE
Alert на Android: мелкие вертикальные отступы между кнопками

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#228]
Alert на Android: мелкие вертикальные отступы между кнопками.

Пример: https://vkcom.github.io/vkui-styleguide/#alert

![image](https://user-images.githubusercontent.com/780935/54107420-0aa30000-4414-11e9-92d3-f5ece37b1d0d.png)

В гайдлайнах материал дизайна: https://material.io/design/components/dialogs.html#

![image](https://user-images.githubusercontent.com/780935/54107457-36be8100-4414-11e9-9480-ceaba7e8941e.png)

И похоже что-то с цветами не то из этого тикета: https://github.com/VKCOM/VKUI/issues/176

v2.19.0

**Comment by ArthurStam** [comment]
Мы не следуем material на 100%. Дизайн алертов скоро будет переделан.

**Comment by mahnunchik** [comment]
@ArthurStam скоро, это когда?
