### ISSUE TITLE
Нажатие кнопки назад в Android

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#229]
Добрый день,

Как поймать нажатие кнопки назад в Android?

**Comment by ArthurStam** [comment]
Добрый. Вопрос не относится к библиотеке. Здесь только набор компонентов и утилит для них.

**Comment by mahnunchik** [comment]
@ArthurStam зачем тогда реализовано в библиотеке iOS swipe back?

Если я правильно понимаю, то вебвью перехватывает нажатие кнопки назад, также как и происходит со свайпом на iOS. Возможно есть аналог VKWebAppEnableSwipeBack/VKWebAppDisableSwipeBack которые, кстати, нигде не документированы кроме примера кода https://vkcom.github.io/vkui-styleguide/#view

**Comment by mahnunchik** [comment]
@ArthurStam `VKWebAppEnableSwipeBack/VKWebAppDisableSwipeBack` упоминается в документации но нигде не специфицирован. Это относится к этой либе?
