### ISSUE TITLE
[Doc] Некорректные параметры у свойств Pagination

### ISSUE THREAD

**Issue by 13Coconut69** [VKCOM/VKUI#2302]
[https://vkcom.github.io/VKUI/#/Pagination](https://vkcom.github.io/VKUI/#/Pagination)
>К примеру, если выставить siblingCount={0} или boundaryCount={0}, то многоточие появится уже при > 5. Если выставить и siblingCount={0}, и boundaryCount={0}, то > 4

Некорректные параметры у siblingCount и boundaryCount

**Comment by inomdzhon** [comment]
Привет,
Можно чуть  подробней? А то не совсем понял в чём проблема(
Спасибо

**Comment by 13Coconut69** [comment]
В тексте документации подразумевается два примера - один для того, чтобы многоточие было при кол-ве страниц > 5, другой - при кол-ве страниц > 4. В обоих случаях предлагается выставить siblingCount={0}, и boundaryCount={0}, что, вероятно, является ошибкой в документации.
