### ISSUE TITLE
[Bug] UsersStack отображает только первый элемент внутри CardScroll 

### ISSUE THREAD

**Issue by VzdutieJivota** [VKCOM/VKUI#2306]
**Описание**
UsersStack отображает только первый элемент, когда находится внутри CardScroll. Остальные элементы появляются при наведении курсора на стрелку скроллинга

**Версия библиотеки**
4.28.0

**Шаги воспроизведения**
Поместить UsersStack из 2 и более фотографий в Card, которая находится внутри CardScroll. Без CardScroll работает нормально

**Ожидаемое поведение**
Отображение всех элементов

**Скриншоты**
<img width="440" alt="image" src="https://user-images.githubusercontent.com/18591051/159360903-2870df63-7c5c-41b1-825e-6a41a01b4bbb.png">
<img width="446" alt="image" src="https://user-images.githubusercontent.com/18591051/159360953-a8914cf7-2d79-4c95-9173-19da46d75bec.png">

**Пример с воспроизведением**
https://codesandbox.io/s/5ber7u

**Comment by fedorov-xyz** [comment]
Подскажите, пожалуйста, браузер и его версию.

**Comment by VzdutieJivota** [comment]
> Подскажите, пожалуйста, браузер и его версию.

Safari 15.1 (17612.2.9.1.20)

**Comment by stoope** [comment]
В примере с воспроизведением все работает верно
