### ISSUE TITLE
При переходе между панелями мигают иконки в PanelHeader

### ISSUE THREAD

**Issue by Akurganow** [VKCOM/VKUI#231]
При переходе между экранами, неприятно мигают иконки в PanelHeader

```jsx
<Panel key={id} id={id}>
  <PanelHeader
    left={
      isDefault ? null : (
        <HeaderButton onClick={this.goBack(1)}>
          {osname === IOS ? <Icon28ChevronBack /> : <Icon24Back />}
        </HeaderButton>
      )
    }
    right={
      current !== 'top' ? (
        <HeaderButton onClick={this.goTo('top')}>
          <Icon24Users />
        </HeaderButton>
      ) : null
    }
  >
    {params.header}
  </PanelHeader>
  {/* ... */}
</Panel>
```

[Видео](https://dsc.cloud/akurganow/Screen-Recording-2019-03-13-14-13-04.mp4)

**Comment by mmarkelov** [comment]
@Akurganow действительно, в  **PanelHeaderTransitions** анимируется **PanelHeader** и изменить это не представляется возможным. Тут как вариант, можно завести под это дело проп, чтоб отключать анимацию, но тут уже как авторы посчитают нужным и правильным:

https://github.com/VKCOM/VKUI/blob/master/src/components/PanelHeader/PanelHeaderTransitions.css#L98

**Comment by ArthurStam** [comment]
На видео видно, что они прямо неприятно моргают. @Akurganow можете подсказать, что за браузер?

**Comment by Akurganow** [comment]
@ArthurStam повторяется в Chrome и Safari на iOS, на Android не проверял

**Comment by ArthurStam** [comment]
В общем, переходите на PanelHeaderSimple, там этих странностей точно не будет :)
