### ISSUE TITLE
[Bug] В CustomSelect нельзя выбрать первое значение при асинхронном поиске

### ISSUE THREAD

**Issue by pashakka1** [VKCOM/VKUI#2315]
**Описание**
В компоненте CustomSelect при асинхронном поиске нельзя выбрать первое значение из выпадающего списка тапом (мышкой норм).

**Версия библиотеки**
4.28

**Шаги воспроизведения**
Открыть документацию на компонент CustomSelect VKUI в мобилке или в режиме мобилки в браузере на компьютере, в последнем примере с асинхронным поиском ввести 3 любых символа и в выпадающем списке попробовать выбрать самое верхнее значение, как-будто оно перекрывается каким-то другим элементом.

**Ожидаемое поведение**
Можно выбрать любое значение из выпадающего списка

**Comment by inomdzhon** [comment]
Дополню, что мышкой тоже есть такая проблема если оставлять курсор на выпадающем списке во время поиска

Вот демо

https://user-images.githubusercontent.com/5850354/160094281-8cd5ce65-df4d-4d6b-84c3-14919e362592.mov

Смотрю в чём проблема

**Comment by JhonPsina** [comment]
Небольшое дополнение: в асинхронном customSelect на мобильных вообще сейчас нельзя нормально тапом выбрать элемент откуда-то иначе, кроме центра списка. Если выбрать один элемент удалось, то поменять выбор не выйдет.

https://user-images.githubusercontent.com/26603858/160601053-75d2fe78-5dce-4d05-9cd9-b9f655351a7c.MP4

.

**Comment by inomdzhon** [comment]
Поправил, жду апрува

Пока вот тут можно проверить https://vkcom.github.io/VKUI/pull/2328/#/CustomSelect
