### ISSUE TITLE
[Bug] объект Select type=city с id=1337 выглядит некорректно (пустой)

### ISSUE THREAD

**Issue by evgq** [VKCOM/VKUI#2318]
Описание:
Объект селекта с типом города с id=1337 выглядит некорректно. ячейка пустая и незаметная, но при этом полностью кликабельная

**Версия библиотеки**
4.28.0

**Шаги воспроизведения**
Создать селект типа города
Добавить элементы городов с разными id и с id 1337

**Ожидаемое поведение**
Пустое название города заменяется на DELETED

**Скриншоты**
![OdABnMt7c2Q](https://user-images.githubusercontent.com/88859639/160236148-3d421442-e35b-4037-a18b-d54676aa8dd7.jpg)

**Comment by evgq** [comment]
Огавошапогарл

**Comment by SevereCloud** [comment]
Нужен пример кода и больше описания. Ожидаемое поведение не является нормой для VKUI

**Comment by evgq** [comment]
С радостью бы предоставил код, но не могу владеть им. Проблема возникла в сервисе погоды ВКонтакте (сейчас такой версии нет). Продукт https://vk.com/bugs?act=product&id=21, баг https://vk.com/bug352813. Модератор просит завести отчёт сюда, ссылаясь на проблему VKUI. Как я понял, список городов заложен в том компоненте (хз). Но могу сказать то, что данный город вообще везде отображается как пустая строка или DELETED

**Comment by SevereCloud** [comment]
Проблема приложения погоды, не библиотеки VKUI
