### ISSUE TITLE
Свой роутинг или рекомендации по использованию стороннего модуля

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#232]
Добрый день,

Столкнулся с тем, что один из самых популярных роутеров https://github.com/ReactTraining/react-router не очень хорошо интегрируется с системой vkui activeView/activePanel.

Было бы здорово иметь роутер подходящий для использования с vkui или рекомендации по интеграции со сторонним модулем.

**Comment by mmarkelov** [comment]
@mahnunchik запил [репо с примером](https://github.com/mmarkelov/react-router-vkui) - не супер идеально, можно еще докрутить. Но думаю идею поймешь.

**Comment by mahnunchik** [comment]
@mmarkelov спасибо! Ага, этот подход уже подсмотрел в где шаверма https://github.com/arsich/vk-apps-gde-shaverma

Использую похожий подход, но не нравится, что переключение через activeView/activePanel мы оборачиваем ещё раз в логику переключения от роутера.

**Comment by mmarkelov** [comment]
@mahnunchik я согласен, что это не самый лучший вариант, но пока на ум не приходит ничего другого.

**Comment by mahnunchik** [comment]
@mmarkelov спасибо, ага, пока так.

Может получиться взять функционал работы хешем/адресом/состоянием из готового модуля, а логику переключения на activeView/activePanel построить.

**Comment by ArthurStam** [comment]
Вопрос роутинга не имеет отношения к либе. Мы юзаем router5, он удобный и абстрактный. Закрываю тикет. Давайте тут обсуждать то, что касается непосредственно кодовой базы либы.

**Comment by mahnunchik** [comment]
@ArthurStam где тогда обсуждать улучшения?

> Было бы здорово иметь роутер подходящий для использования с vkui или рекомендации по интеграции со сторонним модулем.

Перефарзирую запрос на улучшение: Было бы здорово иметь пример интеграции router5 с особенностями работы activeView/activePanel из vkui.

Это относится к документации к библиотеки, а она пока в этом репозитории.

**Comment by mmarkelov** [comment]
@mahnunchik Я придумал другой вариант без сторонних роутов на основе браузерной истории - не теряем анимацию переходов и не тянем сторонних библиотек. Есть еще идеи как ее можно подкрутить, но в принципе и в таком виде можно заюзать:
[Ветка](https://github.com/mmarkelov/react-router-vkui/tree/Using_history)
[Поддержка history в браузерах](https://caniuse.com/#search=history)

**Comment by mahnunchik** [comment]
@mmarkelov начал именно с такого варианта, только с адресом типа `/${activeView}/${activePanel}`. Казалось всё просто, но столкнулся с проблемой с перехода по кнопке назад, когда необходимо подтверждение перехода (например "вы действительно хотите забыть изменения?").

В react-router это реализовано в `getConfirmation`, с нативной `history` видимо нужно кешировать переходы и возвращать к предыдущему состоянию при отмене перехода. Но с ходу не получилось...

Поддержка history, насколько я понял, для VK Apps получается почти 100%, так как сами VK Apps поддерживаются только в современных ВК клиентах.

**Comment by mmarkelov** [comment]
@mahnunchik Я может не уловил до конца проблему, но в принципе ``getConfirmation`` это всего лишь обертка над ``window.confirm``. Обновил репу
```javascript
...
  const back = e => {
    const cofirm = window.confirm('Are you sure?');
    if (cofirm) {
      go(e);
    }
  };

  return (
    <Panel id={id}>
      <PanelHeader
        left={
          <HeaderButton onClick={back} data-to="/">
           ...
        }
      >
```

**Comment by mahnunchik** [comment]
@mmarkelov при нажатии хардверной/браузерной кнопки "назад" история отматывается на один шаг назад, то есть для работы андроидной кнопки назад мы должны подвязать переключение экранов на событие `popstate` https://developer.mozilla.org/ru/docs/Web/API/WindowEventHandlers/onpopstate

Вот тут то и не встраивается нормально подтверждение перехода, так как история уже отмотана на шаг назад.

**Comment by mmarkelov** [comment]
@mahnunchik да, с этим тяжелее - могу предложить такой костыль:
```javascript
     window.onpopstate = e => {
      if (window.location.pathname === '/') {
        const confirm = window.confirm('Are you sure?');
        if (confirm) {
          this.setState({ activePanel: window.location.pathname });
        } else {
          const { activePanel } = this.state;
          window.history.pushState({ activePanel }, activePanel, activePanel);
        }
      } else {
        this.setState({ activePanel: window.location.pathname });
      }
    };
```

**Comment by mahnunchik** [comment]
@mmarkelov точно, у нас же текущее состояние лежит в `this.state`, поэтому есть откуда взять его, чтобы вернуть history при отмене перехода назад.

**Comment by mmarkelov** [comment]
@mahnunchik просто все что связанно с переходами по "кнопкам браузера" достаточно тяжело менять и переопределять. Пока я не вижу что и как можно сделать лучше.
