### ISSUE TITLE
[Bug][Tappable] Не изменяется стиль курсора при отключении возможностей компонента

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#2321]
**Описание**
Оборачиваем кастомный компонент в Tappable, при этом у компонента есть prop active, который отвечает за активное состояние компонента.
Если компонент активен, то логично отключать ему Tappable возможности через hasActive и hasHover prop:

```
const { active } = props;

<Tappable
    hasActive={!active}
    hasHover={!active}
/>
```

При таком сценарии, при наведении на компонент курсор всегда будет pointer, хотя по логике компонент уже активен и дополнительное нажатие ничего не поменяет.
В данный момент приходится переопределять стили библиотеки для решения проблемы.

**Ожидаемое поведение**
Дефолтный стиль курсора при hasActive === false && hasHover === false.

**Пример с воспроизведением**
https://codesandbox.io/s/staging-bush-o5xjib

**Comment by inomdzhon** [comment]
Правка будет в версии `v4.28.2`

Спасибо за Issue 🖖
