### ISSUE TITLE
[Enhancement] Задепрекейтить излишние свойства в `Separator` и `Spacing`

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#2322]
<details>
  <summary>Старое описание</summary>
Из комментариев #1707:

> По дизайну VKUI у нас нет сепараторов без отступов по бокам, `<Separator wide/>` был добавлен для внутреннего использования внутри библиотеки

В связи с этим есть идея:
- правильно задепрекейтить `Separator`
- избавиться от него внутри библиотеки и примеров: везде перейти на `Spacing`, чтобы уменьшить энтропию
- убрать `Separator` в v5
</details>

**Comment by SevereCloud** [comment]
Переосмыслили компоненты и теперь они должны делать то, что от них ожидаешь.

Компонент [Spacing](https://vkcom.github.io/VKUI/#/Spacing) делает только отступы
Компонент [Separator](https://vkcom.github.io/VKUI/#/Separator) делает только полоску

---

Делаем излишние свойства устаревшими

- [ ] `expanded` в компоненте [Separator](https://vkcom.github.io/VKUI/#/Separator)
- [ ] `separator` в компоненте [Spacing](https://vkcom.github.io/VKUI/#/Spacing)
