### ISSUE TITLE
[Bug] Проблемы со списками при появлении клавиатуры на ios

### ISSUE THREAD

**Issue by Yar56** [VKCOM/VKUI#2329]
**Описание**
Есть проблема на ios. В safari виртуальная клавитура не толкает body наверх а накладывается сверху, из за этого списки невозможно нормально скролить.(нижний Tabbar соотвественно тоже скрывается)  На android данной проблемы конечно же нет.

**Версия библиотеки**
4.28.0

**Ожидаемое поведение**
Есть ли варианты в рамках библиотеки реализовать поведение как на андроид? у меня на проекте есть много таких мест и это проблема. может есть идеи, как это вообще можно исправить локально.

**Скриншоты**
пример работы на ios - https://disk.yandex.ru/i/IPPIFvhmVBp8Yw
пример работы на adnroid - https://disk.yandex.ru/i/HhHKPmqQDibPMw

**Пример с воспроизведением**
https://codesandbox.io/s/test-modal-ios-3fhvj2?file=/src/index.js
можно открыть на мобилке https://3fhvj2.csb.app/

**Comment by SevereCloud** [comment]
Это можно реализовать через [VisualViewport](https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport), но к сожалению этот способ не идеален

**Comment by inomdzhon** [comment]
На эту тему вот создана дискуссия https://github.com/VKCOM/VKUI/discussions/3792. Закрою эту задачу в пользу неё.
