### ISSUE TITLE
[Bug] Некорректное отображение label в Epic

### ISSUE THREAD

**Issue by JhonPsina** [VKCOM/VKUI#2333]
Если в эпике содержится TabbarItem с коротким текстом, то относящийся к этому Item-у label обрубает по ширине текста

![изображение](https://user-images.githubusercontent.com/26603858/161062847-26afeae9-11f2-4e46-a5fa-844302851a76.png)

![изображение](https://user-images.githubusercontent.com/26603858/161062327-bd6ab41c-8d0a-46b5-b448-516c4f8fded6.png)

**Comment by SevereCloud** [comment]
Спасибо за отчет, багфикс будет доступен в следующей версии(`v4.29.0`)
