### ISSUE TITLE
[Bug] Input & Textarea меняют цвет на белый после нажатия на них в тёмной теме

### ISSUE THREAD

**Issue by FunNikita** [VKCOM/VKUI#2336]
**Описание**
В последней версии (4.28.1) при нажатии на Input или Textarea и начать вводить там что-то, то в тёмной теме они начинают становиться белыми, что затрудняет чтение содержимого.

**Версия библиотеки**
4.28.1

**Шаги воспроизведения**
1. Изменить тему пользователя под его устройства ([pastebin.com/tDgrLZ2U](https://pastebin.com/tDgrLZ2U));
2. Нажать на поля ввода и попробовать ввести там текст.

Стоит уточнить, что пытался воспроизвести на [codesandbox.io](https://codesandbox.io/) — всё безуспешно. Аналогично и на локалке и туннели. Получается только при билде и деплое.

**Ожидаемое поведение**
В версии 4.27.2 всё работает нормально: при нажатии поля ввода не становятся белыми.

**Скриншоты**
Воспроизводится как на iOS, так на Android и mvk: [видео](https://disk.yandex.ru/i/UQHM9lser5KNcA).

**Comment by SevereCloud** [comment]
Эти компоненты частично используют [vkui-tokens](https://vkcom.github.io/VKUI/#/Customize), которые не зависят от изменения `body[scheme]`.

### Решение

Определять тему, как описано в документации - [PlatformsAndThemes](https://vkcom.github.io/VKUI/#/PlatformsAndThemes).

```jsx
const [appearance, setAppearance] = useState('light');

bridge.send('VKWebAppInit');
bridge.subscribe((e) => {
    switch (e.detail.type) {
        case 'VKWebAppUpdateConfig':
            // appearance возвращается только под iOS, Android
            if (data.appearance) {
              setAppearance(data.appearance)
            }
            break;
        default:
    }
});

// ....

<ConfigProvider appearance={appearance}>
  <AdaptivityProvider>
    <AppRoot>
      <SimpleCell>Вечереет...</SimpleCell>
    </AppRoot>
  </AdaptivityProvider>
</ConfigProvider>
```

### P.S.

Думаю нужно обновить пример в [create-vk-mini-app](https://github.com/VKCOM/create-vk-mini-app/blob/ae554d376b32da835ee5c11c02803c16c057b502/src/App.js#L16-L20)

**Comment by stoope** [comment]
TODO: обновить репозиторий https://github.com/VKCOM/create-vk-mini-app

**Comment by SevereCloud** [comment]
Починили в #2389
