### ISSUE TITLE
Добавить атрибут status к Checkbox и Radio

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#234]
Было бы удобно иметь атрибут `status` у `Checkbox` и `Radio` как у других инпутов.

**Comment by ArthurStam** [comment]
Идея хорошая. Подумаем с дизайнерами.

**Comment by Lihachyov** [comment]
У радио и чекбоксов не должно быть неверных вариантов 🤔

Форму следует составлять так, чтобы все доступные опции контролов Radio и Checkbox были валидными, из которых пользователь может выбирать. Лучше сразу не показывать или отключать вариант, который приведёт к неверному результату формы
