### ISSUE TITLE
[Bug] Input autoFocus ломает css анимации

### ISSUE THREAD

**Issue by 23-yo-designer-from-san-francisco** [VKCOM/VKUI#2340]
**Описание**
При использовании <Input autoFocus> в <ModalPage> в мобильной версии карточка выезжает почти до конца наверх. При отсутствии autoFocus карточка выезжает по высоте контента

**Версия библиотеки**
4.24.0

**Шаги воспроизведения**
В мобильном устройстве открываем компонент `<ModalPage>` с контентом `<Input autoFocus>`.

**Ожидаемое поведение**
Карточка выезжает по высоте контента

**Скриншоты**
С autoFocus: 

<img width="505" alt="image" src="https://user-images.githubusercontent.com/42890090/161514389-ab52b0f2-a992-408d-99df-e4ad2da60228.png">

**Comment by inomdzhon** [comment]
@23-yo-designer-from-san-francisco в PR выше добавил св-во `onOpen`

В песочнице создал FAQ про `autoFocus` https://vkcom.github.io/VKUI/pull/2386/#/ModalRoot?id=props

Буду благодарен за фидбек 🙏

**Comment by inomdzhon** [comment]
Выкатим в ближайшем релизе (`v4.29.0`) фикс.
Надо будет подписаться на `onOpened` и вызывать `focus()` на элемент.
Подробности будут в документации [ModalRoot](https://vkcom.github.io/VKUI/pull/2386/#/ModalRoot).
