### ISSUE TITLE
[Breaking changes] Удалить deprecated props и components

### ISSUE THREAD

**Issue by stoope** [VKCOM/VKUI#2341]
Удалить `props`, `components` и другие части проекта помеченные как `deprecated`.
Такие места можно найти поиском по `5.0.0`, `TODO`, `@deprecated` и `⚠️`

---

- [x] [View](https://vkcom.github.io/VKUI/pull/2381/#/View) удален `popout` и `modal`
- [x] [Root](https://vkcom.github.io/VKUI/pull/2381/#/Root) удален `popout` и `modal`
- [x] [BannerData](https://vkcom.github.io/VKUI/pull/2381/#/PromoBanner) удален `ageRestriction`
- [x] [ContentCard](https://vkcom.github.io/VKUI/pull/2381/#/ContentCard) удален `image`
- [x] [IconButton](https://vkcom.github.io/VKUI/pull/2381/#/IconButton) удален `icon`
- [x] [TabbarItem](https://vkcom.github.io/VKUI/pull/2381/#/TabbarItem) удален `label`
- [x] [Cell](https://vkcom.github.io/VKUI/pull/2381/#/Cell) удален `removable` и `selectable`
- [x] [AppRoot](https://vkcom.github.io/VKUI/pull/2381/#/AppRoot) удален `embedded`
- [x] [CustomSelect](https://vkcom.github.io/VKUI/pull/2381/#/CustomSelect) обновлен `onInputChange`
- [x] [Button](https://vkcom.github.io/VKUI/pull/2381/#/Button) удалены устаревшие `mode`
- [x] Удалить компонент `SliderSwitch`
- [x] Удалить `IS_PLATFORM_ANDROID` и `IS_PLATFORM_IOS`
- [x] Удалить css переменную `--font-tt`
- [x] #2625
- [ ] #2500
- [ ] #2378

### ⛔️ Блокирующие проблемы

- [x] #2359 (Для удаления свойств у Separator и Spacing)
- [x] #2372
- [x] #2501
- [x] Обновление компонентов Typography на токены(мешает обновить NativeSelect,SelectMimicry,Radio,TabsItem)

**Comment by eugpoloz** [comment]
Связанная задачка со списком пропсов: https://github.com/VKCOM/VKUI/issues/1522

**Comment by SevereCloud** [comment]
Закрываю в пользу более четких задач:
- https://github.com/VKCOM/VKUI/issues/2500
- https://github.com/VKCOM/VKUI/issues/2378
