### ISSUE TITLE
[Breaking changes] Перейти на react@17

### ISSUE THREAD

**Issue by stoope** [VKCOM/VKUI#2345]
Поднять минимальную версию `react` до `17`
Поднять версию `types` #1440

**Comment by inomdzhon** [comment]
А почему issue 1519 прикреплён? 🤔 Он же там про про `left/right` -> `before/after`

**Comment by stoope** [comment]
> А почему issue 1519 прикреплён? 🤔 Он же там про про `left/right` -> `before/after`

Ага, спасибо, поменял
