### ISSUE TITLE
[BREAKING CHANGE] Убрать стили внешней геометрии

### ISSUE THREAD

**Issue by stoope** [VKCOM/VKUI#2347]
- [ ] убрать с внешних оберток компонентов стили внешней геометрии:
  - display
  - position
  - top/left/right/bottom
  - transform
  - margin
  - padding (если используется как внешний отступ)
- [ ] решить, стоит ли сбрасывать `margin` и `padding` в компонентах типографики. Связанная задача — https://github.com/VKCOM/VKUI/issues/4696

Зачем: чтобы разработчики могли переопределять внешнюю геометрию. Сейчас можно навесить на компонент, в котором ставятся, например, кастомные `margin`, свой className, но не факт, что это сработает: будет зависеть от того, какой `.css`-файл подключается последним в проекте — наш или свой. Приходится ставить `!important` или использовать другие хаки.

**Comment by inomdzhon** [comment]
> Решить, стоит ли сбрасывать margin в типографии. Стоит ли использовать в качестве Component span вместо h1..h6 по умолчанию

1. Как на счёт параметра `noGap`, который будет сбрасывать отступы, чтобы по умолчанию отступы были?
2. Или же наоборот, `withGap` 🤔 Этот вариант меньше ударит по пользователям)

**Comment by stoope** [comment]
> 1. Как на счёт параметра `noGap`, который будет сбрасывать отступы, чтобы по умолчанию отступы были?
> 2. Или же наоборот, `withGap` 🤔 Этот вариант меньше ударит по пользователям)

Мне нравится идея по умолчанию ставить `margin: 0` и добавлять свойства `withGap/bottomGap/topGap`. Возможно эти пропсы и не нужны, люди сами могут передать нужный `margin` в `styles`

**Comment by inomdzhon** [comment]
> > 1. Как на счёт параметра `noGap`, который будет сбрасывать отступы, чтобы по умолчанию отступы были?
> > 2. Или же наоборот, `withGap` 🤔 Этот вариант меньше ударит по пользователям)
> 
> Мне нравится идея по умолчанию ставить `margin: 0` и добавлять свойства `withGap/bottomGap/topGap`. Возможно эти пропсы и не нужны, люди сами могут передать нужный `margin` в `styles`

Хм, исходил из логики, что люди будут использовать компоненты для стилизации статей, но не уверен, что стоит их применять для этого 🤔 Там классический `.post > h1 { ... }` подойдёт)

Пропсы, которые ставят отступы полезны лишь в том случае, если на уровне дизайн системы они декларируются, но я так понял у нас нет токенов на отступы между текстовыми блоками. @Zaycevq подскажи, плез, так ли это?

**Comment by NekR** [comment]
Было бы хорошо в каждую такую задачу писать от куда берётся мотивация, потому что сейчас выглядит как задачи из воздуха и даже если примерно понятны плюсы, то обсуждению отсутствие информации не способствует.

Например, какая мотивация убирать у компонентов display? То есть перестанем flex использовать? Не понятно что имеется ввиду.

**Comment by NekR** [comment]
Класс. Можешь вынести это в сам пост, что бы сразу было понятно о чем задача?

Про display кстати до сих пор не понятно

**Comment by stoope** [comment]
> Про display кстати до сих пор не понятно

Про display я тоже не уверен, пункты выше это просто набросок. Когда начнем делать уже разберем каждый более подробно

**Comment by inomdzhon** [comment]
Будем по запросу заводить параметры `noMargin`, `noPadding` и т.п.
