### ISSUE TITLE
[Feature] Создать компонент, объединяющий `AppRoot`, `ConfigProvider` и `AdaptivityProvider`

### ISSUE THREAD

**Issue by stoope** [VKCOM/VKUI#2348]
- [ ] Подумать над созданием компонента, который будет оборачивать `AppRoot`, `ConfigProvider` и `AdaptivityProvider` в правильном порядке (и упростить тем самым путь до `HelloWorld`). Пример: `Init` в `vkui-common`. 
- [ ] Порисерчить, можно ли сделать `AppRoot` опциональным

**Comment by NekR** [comment]
> Поресерчить можно ли отказаться от обязательного оборачивания в AppRoot

А какая мотивация отказываться?

**Comment by stoope** [comment]
> А какая мотивация отказываться?

Главная - что бы было легче использовать vkui новым людям, не нужно было писать ни каких лишних обёрток для hello world

**Comment by NekR** [comment]
Тогда и от всех провайдеров нужно избавляться, что вряд ли получится. У AppRoot есть конкретное задача. Думаю стоит с начала какие есть альтернативы, чем они лучше/хуже, итд. и только потом решать, удалять или нет

**Comment by stoope** [comment]
> Тогда и от всех провайдеров нужно избавляться, что вряд ли получится. У AppRoot есть конкретное задача. Думаю стоит с начала какие есть альтернативы, чем они лучше/хуже, итд. и только потом решать, удалять или нет

Отказываться от обязательного оборачивания, речь идет не об удалении `AppRoot` и других провайдеров а об том что бы сделать их не обязательными. Если человек просто хочет использовать одну кнопку ему не нужно было оборачивать все приложение в 3 провайдера.

**Comment by NekR** [comment]
Можешь описать подробнее чем оно будет отличаться от сейчас? Может есть примеры из других дизайн систем?

Сейчас точно можно подключить кнопку просто так, если подключены нужные стили и переменные. А адаптивностью можно рулить на каждом компоненте индивидуально, что кстати, в соседнем issue ты предлагаешь убрать (sizeX/sizeY).

**Comment by stoope** [comment]
> Можешь описать подробнее чем оно будет отличаться от сейчас? Может есть примеры из других дизайн систем?
> 
> Сейчас точно можно подключить кнопку просто так, если подключены нужные стили и переменные. А адаптивностью можно рулить на каждом компоненте индивидуально, что кстати, в соседнем issue ты предлагаешь убрать (sizeX/sizeY).

Мы уходим немного не туда)  Этот issue не про адаптивность. Основная мотивация - упростить https://github.com/VKCOM/VKUI#hello-world . Сейчас там используются `AppRoot`, `ConfigProvider` и `AdaptivityProvider`, причем их порядок тоже важен. Хочется по максимуму отказаться от оборачивания, использовать провайдеры только если тебе действительно нужно перебить значения, например, конфига или адаптивности

**Comment by inomdzhon** [comment]
Давайте Issue назовём
```
Упростить путь до `Hello World`
```
?

А пункт  "Объединить AppRoot, ConfigProvider и AdaptivityProvider в один компонент." ->  "Подумать над созданием компонента, который будет оборачивать `AppRoot`, `ConfigProvider` и `AdaptivityProvider`"

**Comment by NekR** [comment]
Давайте обновим, да :)

**Comment by eugpoloz** [comment]
Обновила еще и название, потому что ничего из этого на самом деле не тянет на breaking changes.

**Comment by inomdzhon** [comment]
Решили в целом попробовать сделать провайдеры необязательными и возможно отказаться от некоторых, в связи с этим нет потребности создавать такой компонент.
