### ISSUE TITLE
[Breaking changes] Модульный CSS

### ISSUE THREAD

**Issue by stoope** [VKCOM/VKUI#2349]
**UPD**

### Описание

Чтобы избавится от `vkuiClass`, переходим на CSS Modules.

Вместо хеширования, будем сокращать имена классов до 3-х символов. Это позволит:
- Сократить вес бандла
- Останется возможность обращаться от одного блока к другому
- Останется возможность привязываться к этим классам у пользователей бибилиотеки

Подробнее тут https://github.com/VKCOM/VKUI/issues/2398 

### Чеклист

- [x] #2607
- [x] Перейти на модульный CSS (`tree shaking`/`code splitting`)
- [x] #2397
- [ ] https://github.com/VKCOM/VKUI/issues/2399
- [ ] [Docs] Написать гайд по тому, как использовать https://github.com/umijs/babel-plugin-import — и как вручную добавлять CSS файлы, если Babel не используется

### Исправит

- [x] https://github.com/VKCOM/VKUI/issues/2442

### Под вопросом
- ~способ задавать стили для дочерних компонентов (например, через `context`) — кажется, что такие вещи лучше решать самим CSS~
- ~хеширование классов~

## Референс:
- https://github.com/VKCOM/VKUI/pull/1335
- https://github.com/VKCOM/VKUI/issues/1643

**Comment by eugpoloz** [comment]
Не стоит ли сюда же вписать хеширование классов?

**Comment by stoope** [comment]
> Не стоит ли сюда же вписать хеширование классов?

Добавил)

**Comment by eolme** [comment]
Почему просто вручную не прописать префиксы?
Чем CSS модули помогут tree-sharking?
Зачем хэшировать классы?

**Comment by eugpoloz** [comment]
@eolme 
> Чем CSS модули помогут tree-shaking?

Прямо сейчас мы не можем нормально тришейкать классы, потому что у нас слишком много обращений компонентов к компонентам, а гарантировать правильную очередь загрузки css-файлов при тришейкинге мы не можем.

> Зачем хэшировать классы?

Классы — не публичное API и таким никогда не подразумевались. Кажется, что хеширование решит проблему, когда пользователи библиотеки завязываются на классы VKUI (особенно внутренние, типа `.Counter__in`), а потом обжигаются, когда мы эти классы меняем или убираем вместе с оберткой при разработке и рефакторинге.

> Почему просто вручную не прописать префиксы?

Этот вопрос не поняла, можешь чуть его раскрыть?

**Comment by ItzNeviKat** [comment]
> Классы — не публичное API и таким никогда не подразумевались. Кажется, что хеширование решит проблему, когда пользователи библиотеки завязываются на классы VKUI (особенно внутренние, типа `.Counter__in`), а потом обжигаются, когда мы эти классы меняем или убираем вместе с оберткой при разработке и рефакторинге.

Ну, теперь можно попрощаться, когда нужно что-то подправить? Зачем так ломать жизнь пользователю? Может, ему стоит самому решать, использовать такое или нет?

**Comment by eugpoloz** [comment]
@ItzNeviKat повторюсь: классы — не публичное VKUI и таким никогда не подразумевались. Сейчас, подвязываясь на них, каждый пользователь делает это на свой страх и риск.

Для кастомизации есть другие инструменты. Возможность прокинуть свой класс на рутовую обертку компонента и что-то поменять с его помощью останется всегда. А еще можно:
- поменять дизайн так, чтобы он соответствовал существующему компоненту VKUI, 
- сделать в приложении свой кастомный компонент, если ни один из предоставленных не подходит настолько, что его приходится костылить — особенно через внутренние классы. 😉

**Comment by ItzNeviKat** [comment]
@eugpoloz к сожалению, я не умею так красиво говорить, но попытаюсь как-нибудь объяснить свои мысли.

У меня, как разработчика, использующего VKUI, частенько происходят такие ситуации: компонент полностью подходит, но нужно что-то изменить или подправить. Что-нибудь мелкое, но бросающееся в глаза, мешающее, а ждать по несколько дней пока пофиксят в библиотеке - ну, не всегда хорошо, особенно, когда придрались модераторы, а иногда что-то, зависящее от платформы/браузера. Вот несколько примеров:

1) Фикс Elastic Scroll на IOS: `position: fixed` на класс `Panel__in`.
2) Поэкспериментировать с Gallery, сделать красивое перелистывание.
...и ещё множество, так сходу и вспомнить не могу.

> А еще можно:
> - поменять дизайн так, чтобы он соответствовал существующему компоненту VKUI,
> - сделать в приложении свой кастомный компонент, если ни один из предоставленных не подходит настолько, что его приходится костылить — особенно через внутренние классы. 😉

- Несвобода разработчикам, ура! Библиотека же идеальна, в ней нет ни багов, ни несоответствия реальным компонентам из нативных клиентов/десктопа и так далее! Согласен, библиотеку гении создавали и развивали, она автоматически лучшая.
- И что, теперь во всех случаях создавать свой компонент? Копировать компонент, JS, кучу стилей, чтобы поменять одну строку? Очень удобно, знаете ли! И ведь что самое главное - костылями даже не пахнет!

А то, что вы придумали, извините меня, называется вредительством - нет никакой практической выгоды, удобства, смысла в этом ограничении, даже наоборот, оно очень помешает. Но зато "пользователь не сможет использовать закрытое апи классов", браво!

Пообщавшись со знакомыми разработчиками, использующими VKUI, я пришёл к выводу, что ограничение бессмысленное и только принесёт неудобно, а так же по идее увеличит размер конечного CSS (поправьте, если не прав). Как можно заметить по реакциям на моё прошлое сообщение, люди поддерживают моё мнение.

Типичный VKUI и его разработчики.

**Comment by eolme** [comment]
Полностью поддерживаю @ItzNeviKat, зачем ломать то что УЖЕ работает? Зачем навороты с контекстами для проброса стилей, если УЖЕ все есть?

Вам так сложно признать, что библиотеку используют не так как вы хотите?

**Comment by eolme** [comment]
>> Почему просто вручную не прописать префиксы?

> Этот вопрос не поняла, можешь чуть его раскрыть?

Все очень просто, у вас есть PR, в котором в результате получается JSON с классами, которые мапятся в классы с префиксом `vkui`

Так вот вопрос, почему просто не пройтись по библиотеке и не проставить сразу классы с префиксом?

**Comment by stoope** [comment]
> А то, что вы придумали, извините меня, называется вредительством - нет никакой практической выгоды, удобства, 
смысла в этом ограничении, даже наоборот, оно очень помешает. Но зато "пользователь не сможет использовать закрытое апи классов", браво!
> 
> Пообщавшись со знакомыми разработчиками, использующими VKUI, я пришёл к выводу, что ограничение бессмысленное и только принесёт неудобно, а так же по идее увеличит размер конечного CSS (поправьте, если не прав). Как можно заметить по реакциям на моё прошлое сообщение, люди поддерживают моё мнение.

Ограничение использование внутренних классов не является главной целью. Главная цель - добавить `code splitting` для `css`, это очень сильно уменьшит размер css файла подключаемого на страницу. Для этого мы хотим переходить на `CSS modules`. Хеширование классов это скорее побочный эффект.

> Полностью поддерживаю @ItzNeviKat, зачем ломать то что УЖЕ работает? Зачем навороты с контекстами для проброса стилей, если УЖЕ все есть?
> 
> Вам так сложно признать, что библиотеку используют не так как вы хотите?

Сейчас мы не можем сделать `code splitting` в том числе из за того что компоненты в стилях ссылаются друг на друга, это никак не связано кроме как по имени класса и имеет значение порядок подключения стилей. Контекст хотим использовать для того что бы ссылаться на один компонент из другого в рамках `CSS modules`. Если есть другое решение то давай конечно обсудим.
Мы не ломаем то что работает а хотим заставить работать `code splitting`.
Повторюсь, главной целью было не ограничить разработчиков потому что они используют `VKUI` не так как мы хотим, у нас есть проблемы со стилями и статические имена классов нам мешают ее решить. поэтому мы делаем это в рамках мажора.
Если есть такая острая проблема что нужно править стили внутренних компонентов то давайте добавим проброс стилей/классов на них, какие еще варианты вы видите?

**Comment by eolme** [comment]
Например, как это решено с antd или material-ui
https://github.com/umijs/babel-plugin-import

**Comment by eugpoloz** [comment]
@ItzNeviKat 

> Пообщавшись со знакомыми разработчиками, использующими VKUI, я пришёл к выводу, что ограничение бессмысленное и только принесёт неудобно, а так же по идее увеличит размер конечного CSS (поправьте, если не прав). Как можно заметить по реакциям на моё прошлое сообщение, люди поддерживают моё мнение.
> 
> Типичный VKUI и его разработчики.

Разработчиков у VKUI довольно много — совершенно точно больше пятерых — и у всех разные нужды и боли.

Размер конечного CSS хеширование уменьшит: хешированные классы всяко будут короче именованных.


@eolme @ItzNeviKat 

Ребята, шаг назад и глубокий вдох, пожалуйста. Как написал Степа, сейчас в любом случае первостепенный вопрос — это тришейкинг, остальное мы еще будем исследовать и обсуждать. Ваше мнение мы услышали; спасибо, что его приносите нам и заботитесь о судьбе библиотеки. Давайте только немного умерим токсичность высказываний, окей? "Типичные разработчики VKUI", как и все остальные люди, намного лучше реагируют на конструктивный диалог вместо набросов. 

Нам не сложно признать, что люди не пользуются библиотекой так, как мы задумали. Люди вообще весьма изобретательны, это регулярная история. 🙃 Но есть вещи, которые мы при этом точно не станем поощрять. Завязывание на внутренние классы компонентов — одна из таких, и она не зависит от того, хешируем мы классы или нет.

**Comment by stoope** [comment]
> Например, как это решено с antd или material-ui
> https://github.com/umijs/babel-plugin-import

Хм, у material-ui с эти все хорошо, плагин помогает в случае если не хочешь писать полный путь при импорте?
Выглядит как усложнение, зачем создавать лишний плагин когда можно все решить "стандартными" средствами? Возможно это упростит жизнь "старым" разработчикам но, в то же время, усложнит новым а мы движемся в сторону упрощения подключения VKUI, что бы людям приходилось делать как можно меньше телодвижений для создания своего "hello world"

**Comment by eolme** [comment]
@eugpoloz @stoope просто объясните мне, пожалуйста, как вынос имён классов в JSON помогает tree-shaking?

Да и смысл свами спорить нет, вы все равно все лучше знаете (выполняете KPI), и пользователей не спросите.

**Comment by stoope** [comment]
> @eugpoloz @stoope просто объясните мне, пожалуйста, как вынос имён классов в JSON помогает tree-shaking?
> 
> 
> 
> Да и смысл свами спорить нет, вы все равно все лучше знаете (выполняете KPI), и пользователей не спросите.

Я все ещё не понял про какие имена классов в JSON идёт речь

**Comment by eolme** [comment]
Как по вашему CSS-модули работают? #2294

**Comment by stoope** [comment]
> Как по вашему CSS-модули работают? #2294

Я ещё не смотрел этот pr, возможно поменяется реализация. Если пока не смотреть на конкретную реализацию в pr, то какие варианты ещё есть сделать code splitting?

**Comment by evtn** [comment]
> Размер конечного CSS хеширование уменьшит: хешированные классы всяко будут короче именованных.

А можно с более конкретными цифрами? Просто уменьшение размера CSS на 3% вряд ли стоит того, чтобы ломать способы изменения стилей, которыми пользуются разработчики.

> классы — не публичное VKUI [может имелось ввиду API?]

Предложите решение лучше, которое позволит на **любую** часть компонента навешать стили.    
Проброс классов работает ровно до тех пор, пока нам нужно навешать стили на какой-то условно основной компонент внутри компонента VKUI, а это вовсе не покрывает все юзкейсы

**Comment by stoope** [comment]
> А можно с более конкретными цифрами? Просто уменьшение размера CSS на 3% вряд ли стоит того, чтобы ломать способы изменения стилей, которыми пользуются разработчики.

Например, если разработчик подключает только кнопку ему попадает только css кнопки(пару кб) а не весь css файл (42кб)

**Comment by evtn** [comment]
> > А можно с более конкретными цифрами? Просто уменьшение размера CSS на 3% вряд ли стоит того, чтобы ломать способы изменения стилей, которыми пользуются разработчики.
> 
> Например, если разработчик подключает только кнопку ему попадает только css кнопки(пару кб) а не весь css файл (42кб)

Ну это же не привязано к хешированию, мой вопрос именно про него. Про разделение ничего не говорю.

**Comment by stoope** [comment]
> > > А можно с более конкретными цифрами? Просто уменьшение размера CSS на 3% вряд ли стоит того, чтобы ломать способы изменения стилей, которыми пользуются разработчики.
> 
> > 
> 
> > Например, если разработчик подключает только кнопку ему попадает только css кнопки(пару кб) а не весь css файл (42кб)
> 
> 
> 
> Ну это же не привязано к хешированию, мой вопрос именно про него. Про разделение ничего не говорю.

Повторюсь, хеширование мы делаем не из за того что нас жалко что кто использует классы, мы хотим сделать code splitting а для этого нужно перейти на css modules. Хеширование это скорее вынужденная мера. Если есть варианты как это сделать без хеширования и модулей то давайте обсудим

**Comment by stoope** [comment]
Старческие классы никогда не были публичным апи а это значит что разработчик использует их на свой страх и риск и после очередного релиза все может сломаться. Как сейчас, например, нам необходимо поменять логику классов. Делаем мы это не ради того что бы набивать kpi на новых issues из за того что люди не могут поменять стили а ради code splitting и упрощения дальнейшего развития и поддержки

**Comment by eolme** [comment]
> mui

Дело в том, что у них стили не в css и не привязаны к классам, там аналог styled-components (если мне не изменяет память) используется

**Comment by stoope** [comment]
> > mui
> 
> Дело в том, что у них стили не в css и не привязаны к классам, там аналог styled-components (если мне не изменяет память) используется

Да, в конечном итоге получаются захешированные имена классов и code splitting. Почему у нас не будет работать если мы сделает так же? (пусть даже через css-in-js, не суть)

**Comment by inomdzhon** [comment]
Очуметь!

Наблюдать такую реакцию от сообщества очень радует ✊ Спасибо, что Вам не всё-равно 🙏  Это помогает переосмыслить решения ☝️

Когда обсуждали **хеширование**, мы упоминали, что пользователям захочется лезть во внутренности компонента, дабы переопределить некоторые св-ва. Для этого есть решения. Об этом далее.

## Черный ящик

Но давайте для начала вспомним почему обращаться к "скрытым" свойствам это не совсем хорошо, будь это хоть CSS, JS или кофемашина 👉 **нарушение целостности**.

В нашем случае, компонент это не просто разметка и стилизация приправленная небольшой логикой, а зачастую это сложно композиционный код, который покрывает требования, прежде всего, дизайн-системы, а потом требования разнообразнейших платформ. Ещё стоит упомянуть требования для реализации доступности. Внутри, в зависимости от CSS свойства ребёнка, могут быть пересчёты или при определенный входных параметрах свойство может играть ключевую роль, чтобы не поехала вёрстка.

Для пользователя что конкретный компонент, что целая библиотека, что огромный фреймворк, должен быть чёрным ящиком, который имеет **публичный интерфейс**. Вообще это всё не я придумал, а умные дядьки.

Чтобы в VKUI компонент был чёрным ящиком, мы и хотим хешировать CSS как трюк для инкапсуляции. Есть, конечно, менее костыльный **shadow dom**, но не во всех браузерах поддерживается.

## Некоторые решения

Пошагово

1. **Токены.** В идеале мы бы хотели, чтобы большинство требований по кастомизации покрывалось токенами.
2. **Постепенное расширение API по требования пользователей.** Пользователи говорят, что не хватает того или иного параметры – компонент расширяется.
    > 📝 Конечно, хотелось бы, чтобы компоненты не выходили за рамки **дизайн-системы**, которое задаёт конечное кол-во состояний. Если мы будем покрывать кейсы вне дизайн-системы, добавляя параметры, которые не подразумевались, повышаем вес библиотеки.
3. ⚠️ **Добавление параметра для доступа к элементам компонента.** Самая крайняя мера.
     Сделать что-то по типу (как в MUI)
     ```
     <Counter classes={{ inner: "custom-inner-classname", before: "custom-before-classname" }}
     ```

**Comment by eolme** [comment]
@inomdzhon, спасибо, вы втроем говорите "мы не используем библиотеку, но знаем как лучше", так вот, так не бывает, опросите пользователей (разработчиков) библиотеки компонентов и все вам скажут одно и тоже

**Comment by stoope** [comment]
> Черный ящик -- не про Open Source, если вы считаете иначе, то вы не правы.
> 
> Да и к тому же, наверное супер удобно делать костыль на каждое ограничение со стороны разработчиков VKUI. Просто поймите простую вещь -- чем больше вы ограничиваете, тем больше будут залазить и менять ваш "черный ящик". Отличная идея форкать целый репозиторий, чтобы поменять вид какого-нибудь индикатора в слайдере. А потом поддерживать еще это -- ух, сказка!

Комбинации токенов + прокидывания классов не будет хватать что бы закрыть потребности по кастомизации? Да, будет больно переходить на v5 тем кто активно завязывался на классы но новые приложения сложнее будет делать? Какие костыли имеются ввиду?
У хеширования есть минусы, если есть другой вариант решения проблемы с code splitting то давай обсудим и выберем самый оптимальный. Можно много критиковать но какой в этом смысл если не предлагать альтернативу?

**Comment by worldwidebaby** [comment]
> Классы — не публичное API и таким никогда не подразумевались.

Тогда зачем вы предлагаете фиксить баги библиотеки, опираясь на классы? Нужно, наверное, напомнить вам и процитировать одного из ваших бывших разработчиков:

> Пока используем воркераунд:
> ```css
> .vkuiGallery--noAnimation .vkuiGallery__layer {
>   transition: none !important;
> }
> ```

https://github.com/VKCOM/VKUI/issues/2186#issuecomment-1008285312

**Comment by worldwidebaby** [comment]
Нормализовать Box Model:
```css
:not([class^="vkui"]),
:not([class^="vkui"])::before,
:not([class^="vkui"])::after {
  box-sizing: border-box;
}
```

Теперь не получится

**Comment by inomdzhon** [comment]
> @eolme Черный ящик -- не про Open Source, если вы считаете иначе, то вы не правы.

Сейчас в этом Issue мы и занимается Open Source, мы обсуждаем какие должно быть API у этого чёрного ящика.

---

Вообще то, что в проекте навешаны костыли сверх библиотеки, это в ответственности команды, которая реализовывала проект. За их прогрехи, сейчас на нас наваливается волна хейта.

---

Вообще я не думаю, что мы сможем о чём то договориться, потому что кроме критики я не вижу никаких предложений. Более того, нет комментариев на наши предложения. Например, я написал под заголовком про **Некоторые решения** [тут](https://github.com/VKCOM/VKUI/issues/2349#issuecomment-1096615729) и никакого фидбека не получил.

Обо всём можно договориться, если перестать тыкать человека носом.

**Comment by eolme** [comment]
> Обо всём можно договориться, если перестать тыкать человека носом в прошлое.

А чего вы ожидали от "мы сделаем вам больно, но это для вашего же блага"?

> волна хейта

Это явление не новое, баги фиксятся годами (посмотрите количество моих issue), фичи завозятся годами, полнейшее отставание от вашей же "дизайн системы". Все предложения по улучшению кладутся в дальний ящик. Полнейшее отсутствие коммуникаций даже среди дизайнеров между продуктовыми и VKUI.

> Сейчас в этом Issue мы и занимается Open Source

Решая внутри VKUI-core ни к кому не прислушиваясь. Лицемерие да и только.

А теперь по поводу решений:

1. Токены -- неадекватно длинные токены, просто сравните вес бандла до и после внедрения, а потом представьте сколько добавляет их переопределение на местах.
2. Не является решением, например, календарь пилили больше года после моего же issue, и то я его завел потому что ваш же дизайнер заверял, что "там все есть".
4. Спасибо за костыль, ведь раньше же нельзя было по "инкапсулированным" именам классов, что-то добавить, нет же.

**Comment by eolme** [comment]
Если уже так говорить, процесс разработки самой библиотеки просто неадекватный: e2e тесты просто чтобы были (#2261), ревью та же песня, никакого регресс тестирования, один раз запустили тесты производительности сравнив с другими библиотеками, и то схитрив, используя более простые компоненты, чем у конкурентов, и без реальных сценариев, нет никакой приоритезации задач, разве только если кто-то сверху постучит.

Не буду говорить ещё сколько всего, что просто неприлично рассказывать.

**Comment by eolme** [comment]
[Комментарий](https://github.com/VKCOM/VKUI/blob/7fda9814d2041354e930ff6caa356a2bd6a35ce6/src/components/Tappable/Tappable.tsx#L229) который коротко описывает продумывание "сложного композиционного кода" и архитектуры компонентов в целом.

**Comment by eolme** [comment]
Знаете почему я участвую в code review и вообще начинаю все эти холевары? Мне просто жалко ребят и комьюнити, которые поддерживают и развивают свои проекты на платформе. И я продолжаю, и буду продалжать это делать, пока у меня есть время и силы, только по этой причине, хотя сам уже ушел с платформы.

**Comment by stoope** [comment]
> Решая внутри VKUI-core ни к кому не прислушиваясь. Лицемерие да и только.

Я не знаю как было раньше так как не так давно занимаюсь VKUI но я уже который раз пытаюсь вывести диалог в конструктивное русло и попытаться найти решение которое всех устроит

> У хеширования есть минусы, если есть другой вариант решения проблемы с code splitting то давай обсудим и выберем самый оптимальный. 

В ответ оскорбления и критика без каких либо альтернатив. Может по этой причине вопросы решаются внутри VKUI-core?

> Знаете почему я участвую в code review и вообще начинаю все эти холевары? Мне просто жалко ребят и комьюнити, которые поддерживают и развивают свои проекты на платформе. И я продолжаю, и буду продалжать это делать, пока у меня есть время и силы, только по этой причине, хотя сам уже ушел с платформы.

Как такие холивары помогают ребятам и комьюнити? Они наоборот отбивают желание что то обсуждать вне VKUI-core. Если в ответ опять пойдет хейт боюсь и этот вопрос придется решать внутри.
Большинство ребят в команде VKUI (включая меня) пришли недавно. Мы хотим развивать библиотеку,  сделать ее использование удобнее для пользователя. Да, многие вещи сделаны плохо но какой смысл поливать все грязью? Большинство людей которые это сделали уже не работают в VK, поэтому у нас тоже есть вопросы почему было так сделано. Если ты хочешь действительно помочь то предлагай конкретные решения, давай обсуждать проблемы, мы открыты к диалогу. Я если честно не понимаю откуда столько агрессии, возможно у тебя были конфликты с людьми которые работали над VKUI но зачем выливать это все на нас? Что бы отбить у нас желания обсуждать решения с комьюнити?

**Comment by eolme** [comment]
@stoope, все что я от вас слышу -- это как же вам тяжело. Если не хотите получать обратную связь от комьюнити, то давно бы закрыли репозиторий. Повторюсь, вы ещё ни разу не прислушались к комьюнити.

Течка кадров лишний раз доказывает, насколько плохи внутренние процессы -- люди не уходят от хорошей жизни.

Хотите чтобы вас благодарили? Не поверите, нужно начать исправлять проблемы, до сих пор issue висят от 2018 года. И вместо того, чтобы заниматься тем, что болит, вы выдвигаете огромные речи о не конструктивном диалоге. Может все же стоит начать с себя?

Существует множество бесед, которые так или иначе относятся к платформе (Технологии ВКонтакте, Библиотека VKUI и тп), но вас там просто нет. Ни одного опроса, ни помощи новичкам, вы ровном счётом ничего не сделали. "Мы хотим развивать библиотеку ... сделать удобнее", а нас вы спросили как нам удобно? Правильно, нет. "Отбить у нас желания обсуждать решения с комьюнити", так это, вы и не обсуждали, вы просто ставите нас перед фактом.

**Comment by stoope** [comment]
> @stoope, все что я от вас слышу -- это как же вам тяжело. Если не хотите получать обратную связь от комьюнити, то давно бы закрыли репозиторий. Повторюсь, вы ещё ни разу не прислушались к комьюнити.
> 
> Течка кадров лишний раз доказывает, насколько плохи внутренние процессы -- люди не уходят от хорошей жизни.
> 
> Хотите чтобы вас благодарили? Не поверите, нужно начать исправлять проблемы, до сих пор issue висят от 2018 года. И вместо того, чтобы заниматься тем, что болит, вы выдвигаете огромные речи о не конструктивном диалоге. Может все же стоит начать с себя?
> 
> Существует множество бесед, которые так или иначе относятся к платформе (Технологии ВКонтакте, Библиотека VKUI и тп), но вас там просто нет. Ни одного опроса, ни помощи новичкам, вы ровном счётом ничего не сделали. "Мы хотим развивать библиотеку ... сделать удобнее", а нас вы спросили как нам удобно? Правильно, нет. "Отбить у нас желания обсуждать решения с комьюнити", так это, вы и не обсуждали, вы просто ставите нас перед фактом.

Все что я прошу это конструктивно обсудить проблему и найти решение

> У хеширования есть минусы, если есть другой вариант решения проблемы с code splitting то давай обсудим и выберем самый оптимальный.

Что мне для этого нужно сделать?

**Comment by eolme** [comment]
> Что мне для этого нужно сделать?

У вас уже все есть, нужно немного поправить CSS, распределив кроссзависимые классы в нужные места.

Напишите гайд, как использовать https://github.com/umijs/babel-plugin-import, и как вручную добавлять CSS файлы, если Babel не используется в проекте.

Избавьтесь наконец от `vkuiClass`, это супер просто, нужно добавить везде префикс `vkui`.

**Comment by eolme** [comment]
Если реально хотите уменьшить вес CSS, то сократите имена классов и токенов, уберите [подобные](https://github.com/VKCOM/VKUI/blob/7fda9814d2041354e930ff6caa356a2bd6a35ce6/src/components/Tappable/Tappable.css#L19) костыли, избавьтесь от [специфичности](https://github.com/VKCOM/VKUI/blob/7fda9814d2041354e930ff6caa356a2bd6a35ce6/src/components/Tappable/Tappable.css#L41)

**Comment by eugpoloz** [comment]
Друзья, я залочу комментарии на время, чтобы все немножечко остыли. Но сначала кое-что скажу, раз у меня получается красиво. (%

Мы сейчас перестраиваем процессы и стараемся делать разработку библиотеки более прозрачной. Именно поэтому вы, во-первых, увидели наши планы на v5 и в принципе имеете возможность их о(б)судить. 😉 Во-вторых, лично мне действительно не хватает фидбека по тому, как, кто и где использует либу, поэтому — спасибо, что его принесли. Отдельное спасибо @evtn за взвешенные и спокойные комментарии. 🤗

Мы хотим наладить диалог. Я рада, что несмотря на то, что до этого мы ни разу не прислушались к коммьюнити, вы все же пришли и что-то сказали. Это дает мне надежду на прекрасное будущее. Я очень люблю VKUI, верю в него и хочу, чтобы он был самой классной либой на свете. Прямо сейчас у нас нет своих developer advocates, которые могут заниматься и помощью новичкам, и опросами коммьюнити, и контролем того, чтобы боли этого самого коммьюнити не зависали на несколько лет в бэклоге — есть только мы.

По сабжу!

Пока что я, чтобы получить больше мнений с разных сторон, тоже сама поспрашивала знакомых разработчиков, которые часто пилят миниаппы на VKUI. Мы с @inomdzhon стряхнули пыль со старого роадмапа модульного CSS и посмотрим, что можно с ним сделать. Все конкретные предложения по реструктуризации CSS мы тоже учтем. Я вернусь с выходного и постараюсь превратить их как минимум в задачи на рисерч, если ребята меня с этим не обгонят. Мы также проверим, насколько сильно хеширование уменьшает вес CSS, чтобы говорить уже с цифрами. Тут я согласна: если мы выигрываем от него условные 3%, которые здесь фигурировали, то смысла и правда мало.

Мы также недавно в тестовом режиме создали раздел [дискуссий](https://github.com/VKCOM/VKUI/discussions). Туда можно приходить, задавать вопросы, хвастаться своими мини-приложениями, просить помощи и так далее. У меня есть мысль закинуть ссылку на него в ближайший релиз, чтобы его увидело как можно больше разработчиков, пользующихся VKUI. Возможно, так нам всем будет чуть проще услышать друг друга.

**Comment by inomdzhon** [comment]
relate #2442
