### ISSUE TITLE
[Breaking changes] SSR

### ISSUE THREAD

**Issue by stoope** [VKCOM/VKUI#2350]
Сделать возможном использовать `VKUI` при `SSR`
- [x] Отказаться от адаптивности через `js` и перейти на `css media queries`
   - [x] Переделать sizeX
   - [x] Переделать sizeY
   - [x] Переделать viewWidth
   - [x] Переделать viewHeight
   - [x] Переделать hasMouse
   - [x] Переделать deviceHasHover
- [x] Добавить возможность переопределять параметры адаптивности из родительского окна, через добавление `class` к рутовому элементу
- [x] Избавиться от `withAdaptivity`, перейти на `useAdaptivity` (возможно при переходе на `css media queries` отпадет надобность и в нем)
- [x] Проверить работу SSR

**Comment by NekR** [comment]
> Добавить возможность переопределять параметры адаптивности из родительского окна, через добавление class к рутовому элементу

Переключения адаптивности на каждом компоненте так же должна быть

> Избавиться от withAdaptivity, перейти на useAdaptivity (возможно при переходе на css media queries отпадет надобность и в нем)

Не очень понятно пока почему

**Comment by stoope** [comment]
> Переключения адаптивности на каждом компоненте так же должна быть

Ага, класс можно докинуть с помощью провайдера на сам компонент отдельно тоже

**Comment by stoope** [comment]
> Не очень понятно пока почему

Хотим избавиться от возможности переопределения sizeX/sizeY через хок withAdaptivity, плюс перейти на хуки

**Comment by NekR** [comment]
> Хотим избавиться от возможности переопределения sizeX/sizeY через хок withAdaptivity, плюс перейти на хуки

Два ответа предидущих как будто не соответствуют друг другу. sizeX/sizeY как раз нужны для переопределения адаптивности на каждом компоненте.

**Comment by stoope** [comment]
> Два ответа предидущих как будто не соответствуют друг другу. sizeX/sizeY как раз нужны для переопределения адаптивности на каждом компоненте.

Останется один способ переопределения - обернуть его в `AdaptivityProvider `

**Comment by NekR** [comment]
Ну вот и непонятно зачем и не особо это что-то упрощает. Плюс в соседнем issue ты как раз предлагаешь дать возможность использовать что-то без AdaptivityProvider, а тут по факту он обязателен становится для импорта одиночного компонента.

**Comment by stoope** [comment]
> Ну вот и непонятно зачем и не особо это что-то упрощает. Плюс в соседнем issue ты как раз предлагаешь дать возможность использовать что-то без AdaptivityProvider, а тут по факту он обязателен становится для импорта одиночного компонента.

Он не становится обязательным. Он нужен если ты хочешь перебить параметры адаптивности, например если приложение в iframe и параметры адаптивности приходят сверху - тогда можно обернуть в AdaptivityProvider

**Comment by NekR** [comment]
Сейчас можно перебить вот так: `<Button sizeY="regular" />`. Хочется что бы такая возможность и оставалась

**Comment by eugpoloz** [comment]
@NekR а чем плох вот этот вариант?

```
<AdaptivityProvider sizeY="regular">
  <Button />
</AdaptivityProvider>
 ```

**Comment by NekR** [comment]
Тем что тот удобнее и он уже есть. В чем смысл смены?

**Comment by stoope** [comment]
> Тем что тот удобнее и он уже есть. В чем смысл смены?

Не хочется поддерживать оба варианта, для `<Button sizeY="regular" />` приходится оборачивать каждый компонент в `hoc` а мы хотим уходить на хуки. Основной смысл в этом

**Comment by inomdzhon** [comment]
> Сейчас можно перебить вот так: `<Button sizeY="regular" />`. Хочется что бы такая возможность и оставалась

Насколько часто к приходится прибегать к такому?

**Comment by pfrankov** [comment]
Связано https://github.com/VKCOM/VKUI/issues/1739
