### ISSUE TITLE
[Bug] В элемент Input[type='number'] можно записать букву "e"

### ISSUE THREAD

**Issue by pekanboy** [VKCOM/VKUI#2355]
**Описание**
При вводе в элемент Input с пропсом type='number' можно записать английскую букву e. ИМЕННО первым символом

**Версия библиотеки**
```
"@vkontakte/vk-bridge": "^2.5.3",
"@vkontakte/vkui": "^4.28.1",
"@vkontakte/vkui-tokens": "^4.5.1",
```

**Шаги воспроизведения**
1) Кликаете на намбер инпут
2) Нажимаете на клавиатуре английскую букву E в любом регистре

**Ожидаемое поведение**
Английская буква E не будет вводиться

**Скриншоты**
<img width="277" alt="Screenshot 2022-04-05 at 23 11 19" src="https://user-images.githubusercontent.com/57917516/161840785-01cb59ec-13de-4aac-ace7-7d5979be5e49.png">
<img width="383" alt="Screenshot 2022-04-05 at 23 11 37" src="https://user-images.githubusercontent.com/57917516/161840829-70e26e8f-0517-4534-b352-0c1a766669e1.png">

**Comment by SevereCloud** [comment]
Это не зависит от VKUI. В обычном `<input type="number"/>` также можно ввести символ `e` или `E`, для [экспоненциальной записи](https://ru.m.wikipedia.org/wiki/%D0%AD%D0%BA%D1%81%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D1%8C)

Больше пояснений с инпутом и буквой `e` [тут](https://stackoverflow.com/questions/31706611/why-does-the-html-input-with-type-number-allow-the-letter-e-to-be-entered-in)
