### ISSUE TITLE
[Bug] При клике на Switch внутри Cell обработчик клика Cell срабатывает дважды

### ISSUE THREAD

**Issue by 23-yo-designer-from-san-francisco** [VKCOM/VKUI#2366]
**Описание**
При клике на Switch без обработчика клика внутри Cell, обработчик клика по Cell срабатывает дважды, при этом currentTarget - Cell

**Версия библиотеки**
4.28.1

**Шаги воспроизведения**
В приложенном сандбоксе кликнуть по ячейке (не по Switch) - в консоль будет выведено одно сообщение. Кликнуть точно по Switch - в консоль будет выведено два сообщения.

**Ожидаемое поведение**
Срабатывает обработчик клика по Cell, т.к. обработчика у Switch нет

**Пример с воспроизведением**
https://codesandbox.io/s/priceless-surf-8s2f45?file=/src/index.js:0-1198

**Comment by SevereCloud** [comment]
`Cell` с `mode="selectable"` также срабатывает дважды 

```jsx
<Cell mode="selectable" onClick={handleSomething}>
  Test content
</Cell>
```

**Comment by inomdzhon** [comment]
@23-yo-designer-from-san-francisco подскажи, плиз, для чего ты используешь `onClick` по всему `Cell`?

**Comment by inomdzhon** [comment]
Пон, спасибо за оперативный ответ 🙏 

Тогда тебе действительно стоит использовать компонент так, как @SevereCloud подсказал, чтобы на уровне браузера это работало. С нашей стороны, надо добавить доку и тесты, что это в будущем не сломается. Доку @SevereCloud уже намутил. @SevereCloud сможешь ещё, плиз, в своём PR https://github.com/VKCOM/VKUI/pull/2376 тест на этот кейс запилить?

> Вообще если использовать `SimpleCell` и `Switch`, то лучше так
> 
> ```js
> <SimpleCell Component="label" after={<Switch />}>
>   Test content
> </SimpleCell>
> ```

Если в будущем тебе нужна будет, например, аналитика, то я бы подписался на `onChange` непосредственно у `Switch`
```js
<SimpleCell Component="label" after={<Switch onChange={...}>
  Test content
</SimpleCell>
```

---

Это решает твою задачу?

**Comment by inomdzhon** [comment]
Ой, сорри, поторпился, про этот момент

> На iOS это поведение не распространяется (но и тумблеры всегда были больше, чем в Android <12, который мимикрирует VKUI)

Если на iOS тебе это поведение не нужно, то в этом случае нужно будет вручную отключать

```jsx
<SimpleCell Component="label" disabled={platform === "ios"} after={<Switch />}>
  Test content
</SimpleCell>
```

как в примере доки [SimpleCell](https://vkcom.github.io/VKUI/#/SimpleCell)

<img width="780" alt="image" src="https://user-images.githubusercontent.com/5850354/167124397-15f1892e-72f2-4368-9235-7934cd237899.png">

**Comment by SevereCloud** [comment]
> Это решает твою задачу?

@23-yo-designer-from-san-francisco

**Comment by 23-yo-designer-from-san-francisco** [comment]
> > Это решает твою задачу?
> 
> @23-yo-designer-from-san-francisco

Да, спасибо! Сори, завал был по задачам

**Comment by SevereCloud** [comment]
Для переключение различных чекбоксов, радиокнопок и прочего рекомендуется использовать html элемент `<label>`. Использование`<label>` совместно с переключателями улучшает a11y.

```jsx
<SimpleCell Component="label" after={<Switch />}>
  Test content
</SimpleCell>
```

Двойной вызов обработчика клика является нормой для браузеров. Если вам все же необходимо обработать клик, то просто отфильтруйте `e.target`
