### ISSUE TITLE
[Feature] Поддержать @types/react@18 и @types/react-dom@18

### ISSUE THREAD

**Issue by worldwidebaby** [VKCOM/VKUI#2368]
Подробную информацию можно найти здесь:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46691

Известные проблемы:
- ```TS2559: Type '{ children: Element[]; }' has no properties in common with type 'IntrinsicAttributes & AdaptivityProps'.```
- ```TS2559: Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & ConfigProviderProps'.```

**Comment by SevereCloud** [comment]
Привет, поддержка типов будет в `v4.34.0`
