### ISSUE TITLE
[Breaking changes] Удаляем scheme

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#2378]
Установка платформы и темы через свойство `scheme` устарела, вместо него [необходимо использовать](https://vkcom.github.io/VKUI/#/PlatformsAndThemes) `platform` и `appearance` компонента [ConfigProvider](https://vkcom.github.io/VKUI/#/ConfigProvider).

**проблема:** поддержка наследования темы
**проблема:** нет поддержки `appearance` в vk.com и m.vk.com

**Comment by inomdzhon** [comment]
relate https://github.com/VKCOM/VKUI/issues/2351
