### ISSUE TITLE
[Bug] Counter в indicator TabbarItem обрезается, если задан слишком короткий текст

### ISSUE THREAD

**Issue by pashakka1** [VKCOM/VKUI#2380]
**Описание**
Counter в indicator TabbarItem обрезается, если задан слишком короткий текст

**Версия библиотеки**
4.28.1

**Шаги воспроизведения**
1. Найти пример использования TabbarItem в документации
2. Поправить прямо в браузере текст у элемента "Мессенджер", оставить, например, только "М".
3. Иконка с каунтером наполовину обрезается.

**Ожидаемое поведение**
Иконка с каунтером показывается полностью

**Скриншоты**
![image](https://user-images.githubusercontent.com/15343067/162917835-ade52d4d-0fd0-4779-af2b-3c59cae93a7d.png)

**Пример с воспроизведением**
Воспроизводится в примере из документации

**Comment by SevereCloud** [comment]
Дубликат #2333
