### ISSUE TITLE
[Bug][SegmentedControl] Не отключается активный таб

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#2394]
**Описание**
Активный таб SegmentedControl реагирует на наведение мышкой и нажатия. 

**Версия библиотеки**
4.28.1

**Скриншоты**
![image](https://user-images.githubusercontent.com/42776347/163433282-e90e47de-1864-4081-b881-ef3fd37f37a1.png)
![image](https://user-images.githubusercontent.com/42776347/163433295-767931f4-79db-49c0-9f5d-4e8f60c2a8da.png)

**Comment by SevereCloud** [comment]
Спасибо за отчет, багфикс будет в следующей версии(`v4.29.0`)
