### ISSUE TITLE
[Breaking changes] Отказаться от классов без префиксов

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#2397]
- [x] отказываемся от классов без префиксов
- [x] отказываемся от `vkuiClass`

---

- [ ] Добавить в #2351

**Comment by inomdzhon** [comment]
Переезд на CSS Modules может помочь придти к этому #2294

**Comment by eugpoloz** [comment]
@inomdzhon это если мы будем на модули переезжать. Если мы заведем код-сплиттинг по мотивам пуллов Вовы, может, оно и не понадобится.

**Comment by inomdzhon** [comment]
> @inomdzhon это если мы будем на модули переезжать. Если мы заведем код-сплиттинг по мотивам пуллов Вовы, может, оно и не понадобится.

Для начала надо в любом случае выпилить `vkuiClass`. 

Есть альтернатива сделать в одну итерацию, в отличии от #2294:
1. Ручками везде переводим `vkuiClass` на `className` (без префикса `vkui`)
2. Настраиваем [babel-plugin-react-css-modules](https://www.npmjs.com/package/babel-plugin-react-css-modules) (c `vkuiClass` мне подружить не получилось)

**Comment by inomdzhon** [comment]
- closed this as [completed](https://github.com/VKCOM/VKUI/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in #3318
