### ISSUE TITLE
[Enhancement][Breaking changes?] Сократить имена css-классов/названия компонентов

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#2398]
По мотивам обсуждения в #2349.

> Если реально хотите уменьшить вес CSS, то сократите имена классов и токенов

Имена новых токенов мы не можем сократить из-за дизайн системы, а вот сократить имена классов — вполне. Например: `CustomSelectDropdown__CustomScrollView` => `CustomSelectDropdown__view`

Возможно, стоит также подумать над тем, чтобы сократить названия некоторых компонентов, поскольку имена классов зависят от них напрямую. Например: `CustomScrollView` => `ScrollView` или `Scrollable`.

**Comment by inomdzhon** [comment]
В случае с `CustomSelectDropdown__CustomScrollView` это для того, чтобы явно показать, что мы модифицируем компонент `CustomScrollView`, при разработке это может быть полезно
Поэтому не уверен, что стоит менять на `view` именно в таких случаях

**Comment by eugpoloz** [comment]
@inomdzhon но в других случаях с вложенными компонентаси мы такой логики не придерживаемся, а тут почему-то да.

**Comment by inomdzhon** [comment]
> @inomdzhon но в других случаях с вложенными компонентаси мы такой логики не придерживаемся, а тут почему-то да.

В этом случае я коммент прост оставлял на ревью Calendar, когда он только выкатывался 😁 
Предложил там идею так обходиться
Но если это не имеет смысла, то можно забить или писать комментарий над таким блоком, кстати

**Comment by eugpoloz** [comment]
@inomdzhon 
> В этом случае я коммент прост оставлял на ревью Calendar, когда он только выкатывался 😁
Предложил там идею так обходиться

Проблема в том, что это реально имена классов раздувает. Я как раз хотела в том числе в `Calendar` предложить их поменять.) К тому же у нас куча мест, где все уже не так. Например:

<img width="437" alt="image" src="https://user-images.githubusercontent.com/22026957/163596694-afc04417-dfc9-4637-a54a-780bd9f81721.png">

<img width="260" alt="image" src="https://user-images.githubusercontent.com/22026957/163596914-70332c8e-44e1-43f2-a40a-f6ce015fad43.png">

> Но если это не имеет смысла, то можно забить или писать комментарий над таким блоком, кстати

А зачем комментарий?

**Comment by inomdzhon** [comment]
> Проблема в том, что это реально имена классов раздувает. Я как раз хотела в том числе в Calendar предложить их поменять.) К тому же у нас куча мест, где все уже не так. Например:

Согласен, это не стоит того 👍  Давайте сокращать

> > Но если это не имеет смысла, то можно забить или писать комментарий над таким блоком, кстати
>
> А зачем комментарий?

Чтобы добавить прозрачности для разработчиков VKUI, мы будем понимать кто кого немного "модифицирует"

**Comment by inomdzhon** [comment]
Провёл ресёрч на тему сокращения имён классов

Подробнее в этом репозитории https://github.com/inomdzhon/test-vkui-css-hash. Ссылка сразу на [итоги](https://github.com/inomdzhon/test-vkui-css-hash#%D0%B8%D1%82%D0%BE%D0%B3%D0%BE).

**Comment by inomdzhon** [comment]
Предлагаю закрыть issue в пользу автоматизации этого дела
Будем сокращать имена при сборке `.vkuiButton` -> `.vkuibtn`, что, надеюсь, нас ждёт в `v5`

**Comment by eugpoloz** [comment]
В принципе это еще и очень обширная задача, так что да, поддерживаю. Лучше потом точечных наплодить при необходимости переименования тех же компонентов, например.
