### ISSUE TITLE
[BREAKING CHANGE][Enhancement] Реструктурируем CSS

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#2399]
Сюда можно накидывать задачки по реструктуризации CSS.

- [x] https://github.com/VKCOM/VKUI/issues/2384 — выпиливаем все `deprecated`-стили
- [ ] https://github.com/VKCOM/VKUI/discussions/5421

---

- related to https://github.com/VKCOM/VKUI/issues/2349#issuecomment-1097138823

**Comment by inomdzhon** [comment]
- related to https://github.com/VKCOM/VKUI/discussions/5421

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.0" target="_blank">v7.0.0-beta.0</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
