### ISSUE TITLE
[Bug] При смене ориентации не пересчитывается высота

### ISSUE THREAD

**Issue by ponchicken** [VKCOM/VKUI#2406]
**Описание**
При смене ориентации (или при ресайзе) не пересчитываются размеры приложения, или расчитываются с опозданием (возможно, в AdaptivityProvider)
На iOS в chrome во всех миниприложениях

**Версия библиотеки**
на версии 4.27.2 воспроизводилось стабильно, на 4.28.1 гораздо реже, но всё равно ловится

**Шаги воспроизведения**
На iOS в chrome в любом миниприложении (напр. https://vk.com/pets) сменить ориентацию на горизонтальную, затем обратно на вертикальную (можно повторить повороты несколько раз, если не воспроизводится)

https://user-images.githubusercontent.com/12897276/163796646-c38b29c7-de61-4ed2-8b62-434c9ffe857a.mov

**Comment by SevereCloud** [comment]
Выглядит как баг m.vk.com -- там высота фрейма устанавливается через js, после ресайза. У на размер панели через css устанавливается в 100%. Воспроизвести не получилось

**Comment by SevereCloud** [comment]
Привет, фикс в проде
