### ISSUE TITLE
[Bug] Некорректное отображение CustomSelect внутри ModalCard

### ISSUE THREAD

**Issue by lexstile** [VKCOM/VKUI#2425]
**Описание**
При использовании внутри компонента `<ModalCard />` компонента `<CustomSelect />` выпадающий список на некоторых экранах уезжает в сторону.
Опытным путем вычислил - проблема воспроизводится при ширине экрана более 456px (отлично видно при 600px)

**Версия библиотеки**
4.28.1

**Скриншоты**
![image](https://user-images.githubusercontent.com/30532019/164286486-b7d3dfb8-d64c-4472-a62f-495bff11b1a2.png)

**Пример с воспроизведением**
`
    <ModalCard
      id={id}
      onClose={onCloseModal}
      header="Вывод"
      actions={
        <Button stretched size="l" mode="primary" disabled={!amount}>
          Вывести
        </Button>
      }
    >
      <FormLayout>
        <FormItem top="Выберите карту">
          <CustomSelect placeholder="Не выбран" options={CARDS} value={CARDS[0].value} />
        </FormItem>
      </FormLayout>
    </ModalCard>
`

**Comment by inomdzhon** [comment]
@lexstile а у вас, случайно `overflow: hidden` не выставляется на html или body?

Подобный вопрос был и там помогло корневому элементу выставить `overflow-y: scroll`, в том случае это был тег `<body>`. Предполагаю это из-за того, что выпадающее меню смещенно на ширину скроллбара. Пока руки не дошли глянуть в каком месте кода.

**Comment by lexstile** [comment]
Ширина scrollbar статична, как я понимаю, а сдвиг в выпадающем списке меняется в зависимости от ширины экрана.
![image](https://user-images.githubusercontent.com/30532019/164443330-1c08c988-9196-4528-8546-1f2dccf8c201.png)

**Comment by inomdzhon** [comment]
Хм, интересно
Перекинь, пожалуйста, пример воспроизведения чуть детальней 🙏   А то в данный момент просто не копипастнешь 😄

**Comment by lexstile** [comment]
https://codesandbox.io/s/green-https-enn63z

**Comment by inomdzhon** [comment]
> https://codesandbox.io/s/green-https-enn63z

В данном примере решается через `overflow-y: scroll`. В видео для заметки особенность MacOS привожу, что по умолчанию `scroll` не занимает место на экране

https://user-images.githubusercontent.com/5850354/164497783-5740d00b-186a-4a72-a5e3-0fbd99d429ee.mov


Проверь, пожалуйста, указан ли он всё же у вас?

**Comment by lexstile** [comment]
Я работаю под виндой, смотрю из браузера chrome.
Еще раз проверил вариант с `overflow-y: scroll;` для `body` - не работает.
Есть ли возможность проверить в `chrome`?

**Comment by inomdzhon** [comment]
> Я работаю под виндой, смотрю из браузера chrome. Еще раз проверил вариант с `overflow-y: scroll;` для `body` - не работает. Есть ли возможность проверить в `chrome`?

🤔 я тоже в `chrome` смотрю, вот на винде глянуть проблемней

Так-с, а если ты здесь https://codesandbox.io/s/green-https-enn63z ставишь `overflow-y: scroll` на `body`, то всё ок? Если будет ок, то мне потребуется больше данных по твоему проекту, если не ок, то буду винду искать

**Comment by lexstile** [comment]
![image](https://user-images.githubusercontent.com/30532019/164971051-3fecf4bd-32d2-4e12-92ff-e125a02a2eb4.png)
Да, действительно все выровнялось с помощью `overflow-y: scroll;`.

**Comment by inomdzhon** [comment]
> ![image](https://user-images.githubusercontent.com/30532019/164971051-3fecf4bd-32d2-4e12-92ff-e125a02a2eb4.png) Да, действительно все выровнялось с помощью `overflow-y: scroll;`.

А у тебя в проекте?

**Comment by inomdzhon** [comment]
> У меня в проекте тоже работает `overflow-y: scroll;`, только не совсем понял, зачем скролл, когда он не нужен?

Пока это самый быстрый фикс. Я сейчас потыкал и обнаружил несколько интересных особенностей. Создам отдельное issue на эту тему привяжусь к твоей.

Спасибо 🙏
