### ISSUE TITLE
[Enhancement][Gallery] Добавить возможность выполнять коллбэки при клике по стрелкам

### ISSUE THREAD

**Issue by NebSehemvi** [VKCOM/VKUI#2426]
Сейчас возможно отслеживать куда пользователь свайпает слайды галереи, но нет возможности отследить клики по стрелкам (onChange не гарантирует, что это были именно они).

**Comment by inomdzhon** [comment]
Смержил)
Только надо будет немного подождать ближайший релиз (`v4.29.0`)

**Comment by NebSehemvi** [comment]
Спасибо!

Хорошо, подождем)
