### ISSUE TITLE
[Feature] Добавить новый тип селекта: `accent`

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#2428]
Документируем вид селекта, который есть у нас в календаре.

**Comment by inomdzhon** [comment]
Под `accent` вот это имеется ввиду?

![image](https://user-images.githubusercontent.com/5850354/164618269-557412b3-f8c2-482a-a991-a42377443fd4.png)

![image](https://user-images.githubusercontent.com/5850354/164618337-1fb47a44-778e-4bc1-991c-d5276a3cc752.png)

И так понимаю речь идёт об про расширении `selectType`, так?

**Comment by eugpoloz** [comment]
@inomdzhon ага, все так.
