### ISSUE TITLE
[Bug][PanelHeader] Не пересчитывается размер компонента при использовании колонок

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#2429]
**Описание**
Используется интерфейс c двумя колонками, при ресайзе одна из колонок пропадает, но у второй не пересчитывается размер PanelHeader в момент пропадания и он остается такого же размера как и до пропадания первой колонки.

**Версия библиотеки**
4.28.1

**Скриншоты**
До пропадания:
![image](https://user-images.githubusercontent.com/42776347/164673577-54d798cb-e2ce-4bfa-b018-9f3ea820b6d7.png)
После: 
![image](https://user-images.githubusercontent.com/42776347/164673621-313054b4-ac75-4d60-83e8-d86a71b81bdf.png)
После пропадания и дополнительного ресайза:
![image](https://user-images.githubusercontent.com/42776347/164673676-645583d6-d860-44f7-90aa-5c9562d27a7a.png)

**Comment by SevereCloud** [comment]
**Пример с воспроизведением**
https://codesandbox.io/s/cranky-ptolemy-d2y6db?file=/src/index.js

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.0" target="_blank">v6.2.0</a> 🎉
