### ISSUE TITLE
Можно добавить onTransition к Panel?

### ISSUE THREAD

**Issue by ciricc** [VKCOM/VKUI#243]
Не знаю, надо ли, но я пока что не смог найти способа сделать скролл к верхней части экрана после смены панели. window.scrollTo(0,0) не работает даже в didMount. 

В View для такого вроде как есть onTransition, чтобы после всех анимаций выполнить скролл к верху. В Panel такого не нашел.

Ну или изначально как-то можно до анимации установить позицию скролла панели?

**Comment by ciricc** [comment]
Проблема решается достаточно легко. Но, только, если зайти в исходники vkui.
Хотелось бы узнать, будут другие способы установки позиции скролла?

```javascript
this.refs.panelRef.state.scrolls.panelId = 0;
```

**Comment by mmarkelov** [comment]
@ciricc А в чем проблема то использовать **View** и **onTransition**?
И Ваше решение не совсем правильное и крайне не советовал бы его использовать - Вы получается напрямую мутируете стэйт, а это совсем нехорошо

**Comment by ArthurStam** [comment]
@ciricc вы мутируете `state` компонента через `ref` – это дважды плохо) 
Со скроллом ситуация следующая – когда мы идем вперед, скролл у новых панелей всегда наверху, когда назад – скролл панелей берется из стейта вью. Мы повторяем поведение нативного клиента и считаем, что пользователю так проще ориентироваться в приложении. `window.scrollTo` не будет работать, потому что на время перехода из одной панели в другую, панелям ставится `overflow: hidden`.

**Comment by ciricc** [comment]
Да, уже нашел решение. Спасибо. Сделал через scrollTo в итоге
