### ISSUE TITLE
[Bug] Не прокрас компонента `Gradient` в теме `vkcom_dark`

### ISSUE THREAD

**Issue by ItzNeviKat** [VKCOM/VKUI#2434]
**Описание**
Если поставить `scheme` в `vkcom_dark` (или `appearance` в `dark`), то компонент `Gradient` остаётся белого цвета и не красится в тёмный.

**Версия библиотеки**
Последняя:
```
"@vkontakte/vkui": "^4.29.0"
```

**Шаги воспроизведения**
1. Поставить `scheme` в `vkcom_dark` (или `appearance` в `dark`).
2. Наблюдать баг.

**Скриншоты**

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/24193020/165108547-85020af5-b6a1-44c1-baf0-57fa82f7eba1.png">

**Пример с воспроизведением**
Можно наблюдать в документации: ставим `platform` в `vkcom` и `appearance` в `dark` https://vkcom.github.io/VKUI/#/Gradient

**Comment by SevereCloud** [comment]
Привет, фикс будет доступен в следующей версии
