### ISSUE TITLE
Slider в Gallery баг

### ISSUE THREAD

**Issue by idbolshakov** [VKCOM/VKUI#244]
Если добавить слайдер в один из экранов галереи, то при попытке покрутить слайдер, вместе с ним будет свайпаться и экран галереи

**Comment by fedorov-xyz** [comment]
А что за кейс, когда нужно помещать Slider в Gallery?

**Comment by idbolshakov** [comment]
А почему нет?

**Comment by idbolshakov** [comment]
Если это почему то запрещено, напишите про это куда нибудь

Перестану помещать

**Comment by mmarkelov** [comment]
@idbolshakov тут два варианта либо в компоненте Слайдера вызывать **stopPropagation**, я не уверен, правда, что это ничего не поломает. Либо в проп **onChange** вместе со значением передавать эвент и уже там вызвать **stopPropagation**. Я могу сделать ПР, но не уверен, что его оперативно зальют в мастер

**Comment by ArthurStam** [comment]
У нас пока нет стайлгайдов, но я уже сейчас могу сказать, что `Slider` в `Gallery` – это плохой UX.

**Comment by idbolshakov** [comment]
А можно узнать почему?) мы в галерее делаем шаги регистрации в  сервисе, 1 действие 1 шаг 1 экран

**Comment by mmarkelov** [comment]
@ArthurStam я как и @idbolshakov ничего плохого в этом не вижу. Есть же Emoji Slider в сторизах инстаграма, чем это плохой ux?

**Comment by mmarkelov** [comment]
@idbolshakov вышла новая версия - теперь в слайдере в функции **onChange** передаётся event в качестве второго аргумента. Надеюсь Вам поможет)
