### ISSUE TITLE
[Bug] В название CSS классов, переданных в проп `activeMode`, добавляется подстрока `vkui`

### ISSUE THREAD

**Issue by OkciD** [VKCOM/VKUI#2442]
**Описание**
Если передать в проп `activeMode` название  класса, в него доклеится подстрока `vkui`. Из-за этого у пользователя VKUI не работают CSS-селекторы 

**Версия библиотеки**
`4.28.1`

**Шаги воспроизведения**
1. Берём компонент, поддерживающий проп `activeMode` (в моём случае - [`RichCell`](https://vkcom.github.io/VKUI/#/RichCell))
2. Прокидываем ему в проп `activeMode` название CSS-класса
3. Селектор не работает, тк название применённого CSS-класса отличается от того, что мы передали (в него добавлена подстрока `vkui`)

**Ожидаемое поведение**
Название класса будет соответствовать тому, которое передал пользователь

**Скриншоты**
![image](https://user-images.githubusercontent.com/24460253/165393050-a1e2432f-805d-4e0c-bb8b-2a12ff7a86f2.png)
![image](https://user-images.githubusercontent.com/24460253/165393099-196c07b7-6faf-4d5b-8efe-8b939a5fed55.png)

**Comment by inomdzhon** [comment]
Проверил. К сожалению, в версии `v4` нельзя поправить это из-за `vkuiClass`, который выставляет префиксы.

Если горит, могу обсудить с командой создание отдельных параметров `activeModeClassName` и `hoverModeClassName` **только для `v4`**

**Comment by inomdzhon** [comment]
@OkciD ping

**Comment by OkciD** [comment]
Да не, мне фикс не горит. Я нашёл выход из положения обычными псевдоклассами `:hover` и `:active`, благо в `RichCell` на hover и active ничего, кроме перекраски, не происходит

**Comment by inomdzhon** [comment]
> Да не, мне фикс не горит. Я нашёл выход из положения обычными псевдоклассами `:hover` и `:active`, благо в `RichCell` на hover и active ничего, кроме перекраски, не происходит

В `v5` префикс `vkui` в класс в `activeMode` выставляться не будет благодаря задаче https://github.com/VKCOM/VKUI/issues/2349

**Comment by inomdzhon** [comment]
reopen caused by https://github.com/VKCOM/VKUI/discussions/2487

**Comment by inomdzhon** [comment]
Снова закрываю xD

Если тебе интерес прогресс по задаче, то подпишись, пожалуйста, на #2349, я добавил туда ссылку на твоё issue
