### ISSUE TITLE
[Bug] Отсутствуют константы для VK Sans

### ISSUE THREAD

**Issue by egorprnn** [VKCOM/VKUI#2448]
**Описание**
В 4.29.0 релизе была добавлена поддержка VK Sans шрифта, но констант нету в билде.

![image](https://user-images.githubusercontent.com/42776347/165768220-371f67cf-dcf5-4925-b213-2c0ffb18e25a.png)

**Comment by eolme** [comment]
<details>
    <summary>А воз и ныне там</summary>
    <blockquote>    
... e2e тесты просто чтобы были (#2261), ревью та же песня ...
    </blockquote>
</details>

**Comment by stoope** [comment]
VK Sans Text это не публичный шрифт, пока что не решился вопрос можем ли мы его отдавать в open source с юридический точки зрения. В 4.29.0 была добавленна поддержка для использования внутри vk, как только мы все протестируем изнутри и получим разрешения на использования то добавим в доку все инструкции по подключению и использованию.

**Comment by stoope** [comment]
> @stoope у вас файлы шрифта лежат под MIT, о чём идёт речь?

У нас лежит VK Sans **Display** а тут речь идет о VK Sans **Text**

**Comment by eolme** [comment]
В PanelHeader лежит Text с letter-spacing --vk-sans-ls-17

**Comment by stoope** [comment]
> В PanelHeader лежит Text с letter-spacing --vk-sans-ls-17 и font-family: --font-display
Как я уже написал, поддержка пока сделана для внутреннего использования внутри vk. Если после релиза у вас ничего не сломалось значит все идет по плану. Как только все будет готово мы напишем, пока не стоит обращать внимание на эти переменные

**Comment by MrZillaGold** [comment]
@stoope Сломалось. В доке говорится о поддержке VK Sans Display для PanelHeader, константа с шрифтом отсутствует - шрифт не подтягивается.
![image](https://user-images.githubusercontent.com/42776347/169766617-a9fb3234-6a7f-4e69-9f4f-3ffffe80a176.png)
