### ISSUE TITLE
[Feature] Переписать модальные окна

### ISSUE THREAD

**Issue by stoope** [VKCOM/VKUI#2449]
Текущая реализация модальных окон требует много времени на поддержку со стороны разработчиков и содержит много багов. Необходимо подумать как можно упростить модальные окна

**UPD**
Необходимо задепрекейтить `ModalRoot` и создать вместо него `ModalManager`.

**Comment by stoope** [comment]
> Хороший пример в AntD есть: https://ant.design/components/modal/. Модалка вызывается из любого места. Конечно, тут нужно придумать, как предотвратить открытие сразу нескольких модалок одновременно, но это точно решаемая проблема

Ага, что то подобное планирую. А открытие нескольких модалок одновременно стоит контролировать со стороны VKUI или дать возможность разработчику это контролировать? У нас есть какие то кейсы когда это нужно?

**Comment by inomdzhon** [comment]
> Текущая дизайн система не предусматривает открытие сразу нескольких модалок. Так что, как мне кажется, тут есть два варианта:
> 
> 1. При открытии второй модалки скрывать предыдущую в стэк и возвращать при закрытии текущей.
> 2. Кидать warn в консоль и ничего не делать, пока не закроется предыдущая

Возможно стоит с дизайном обсудить этот момент

**Comment by thoughtspile** [comment]
Напомню что я уже делал подход к этому вопросику: https://github.com/VKCOM/VKUI/pull/2182

**Comment by k-egor-smirnov** [comment]
Вот чего очень не хватает в текущих модалках:

1. Динамического добавления. Это самая важная хотелка. Если оставлять в текущем виде ModalRoot, то хочется научить его работать с модалками, которые динамически в него подключаются. С этим хотя бы можно будет как-то работать через контексты.
2. Декларативного рендера. Хочется прямо внутри JSX панели иметь возможность рендерить модалку в любом месте внутри структуры компонента. Это можно подвязать к a11y: можно будет обернуть кнопку в компонент модалки, и кнопка будет знать, что по её клику будет открыт какой-то попап.
3. Возможности использовать FixedLayout внутри модалки. Юзкейс: панель нового комментария.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
