### ISSUE TITLE
Съезжает чекбокс в selectable cell

### ISSUE THREAD

**Issue by aplinxy9plin** [VKCOM/VKUI#245]
На анроиде съезжает checkbox в selectable cell, если присутствует asideContent. На iOS все хорошо, в силу того, что на iOS чекбокс находится слева, было бы хорошо, если бы checkbox и на андроиде был слева
```javascript
<Cell 
 selectable 
 checked={this.state.group_checked}
 onChange={this.groupChange}
 description="15 196 подписчиков"
 asideContent="Бесплатно" 
 before={ <Avatar size={40} src="https://pp.userapi.com/c637125/v637125406/26313/KPzr3LVzHFI.jpg" /> }>
 Рерайт Копирайт
</Cell>
```
<img src="https://pp.userapi.com/c850132/v850132187/10aea1/2yBTgFw0YaY.jpg" /><img src="https://sun4-1.userapi.com/c849232/v849232187/159691/BmBmdni2ekM.jpg" />``

**Comment by fedorov-xyz** [comment]
Попробуйте заменить asideContent на indicator, кажется, это свойство в данном случае больше подойдёт.

**Comment by ArthurStam** [comment]
Да. Мы в `asideContent` в Android версии рисуем галочку для `selectable` режима. Поэтому едет верстка. @fedorov-xyz прав, свойство `indicator` как раз нужно, чтобы рисовать в правой части ячейки
