### ISSUE TITLE
[Bug][Typography] Компоненты не наследуют `letter-spacing` от vkui-tokens

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#2450]
**Описание**
Все компоненты типографии имеют константы `letter-spacing` в vkui-tokens, но в самой библиотеке они не используются, хотя в доке заявлена поддержка.

**Comment by stoope** [comment]
upd: Токены `letter-spacing` для типографики нужно использовать только при `VK Sans Text`, ждем согласования публичного использования `VK Sans Text`

**Comment by inomdzhon** [comment]
см. #3561
