### ISSUE TITLE
[Bug][SegmentedControl] Отсутствует `s` размер

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#2463]
**Описание**
У компонента может быть состояние размера `s` с высотой в 32px, но библиотека его не поддерживает.

**Comment by SevereCloud** [comment]
Привет. Компонент делается с учетом размеров **Button** (Medium 36px, Large 44px) и **Forms** (Regular 44px, Compact 36px). При высоте `32px`, SegmentedControl получается слишком маленьким(в сравнении с другими компонентами формы)

![Group 5 (1)](https://user-images.githubusercontent.com/14944123/166660244-9e19755b-b05d-4eab-96a5-eab5704e2855.png)

Если очень хочется такой размер, можно задать его через стили

```tsx
<SegmentedControl style={{height:32}} />
```
