### ISSUE TITLE
[Bug] Большие кнопки обрезаются в RichCell

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#2466]
**Версия библиотеки**
v4.29.0

**Скриншоты**
<img width="338" alt="image" src="https://user-images.githubusercontent.com/14944123/166879961-4f4ed7b5-2e72-4315-a3e4-ec53a9646b55.png">

**Пример с воспроизведением**
[RichCell](https://vkcom.github.io/VKUI/#/RichCell)

**Comment by inomdzhon** [comment]
Хммм

Я вот в этой ветке [2469-button-cleanup-styles](https://github.com/VKCOM/VKUI/tree/2469-button-cleanup-styles) реализовал то, что тут https://github.com/VKCOM/VKUI/pull/2090 ты сделал и там есть фикс данной проблемы

Единственное, для этого случае надо доку поправить, добавить `stretched` ко всем `ButtonGroup`

https://github.com/VKCOM/VKUI/blob/db6d125ee45c4330f3a8202d9c336e053075cdad/src/components/RichCell/Readme.md?plain=1#L13-L18

Тогда будет в многоточие уходить

<img width="415" alt="image" src="https://user-images.githubusercontent.com/5850354/169240964-6df67bf8-4952-4263-89cc-707663f45b68.png">

**Рис. 1.** Размер iframe уменьшен на `319px`.`ButtonGroup` внутри верхнего `RichCell` имеет `stretched`

---

Вообще эти изменения не брейкинг чендж, поэтому я отдельной веткой их в `master` в затащу
