### ISSUE TITLE
[Bug] CustomSelect -> асинхронный onInputChange 

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#2470]
Вываливает варнинг, что onInputChange больше не поддерживает возвращаемое значение хотя ему вернулся обычный Promise который никак и не должен влиять при этом игнорируя filterFn={false} все равно пытается совершить поиск
![image](https://user-images.githubusercontent.com/26293210/167246266-23dabe9d-4e20-4a5c-addb-2c1bb88e997e.png)

**Comment by BlackySoul** [comment]
Привет! Раньше мы безусловно обрабатывали результат исполнения `onInputChange`, ожидая, что вернется отфильтрованный список опций. 

В новой версии `v6` такой проблемы не будет. Подробнее:

- resolved #6152
