### ISSUE TITLE
[Bug][PanelHeader] Съезжает хеадер в многоколончатом интерфейсе

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#2475]
**Описание**
В многоколончатом интерфейсе хеадер панели правой колонки съезжает в начало страницы и перекрывает контент левой

**Версия библиотеки**
4.30.0

**Скриншоты**
[4.29.0](https://vkcom.github.io/VKUI/4.29.0/#/SplitLayout)
![image](https://user-images.githubusercontent.com/42776347/168070955-c5a139ce-2f7a-483c-b081-7b26c3de7af5.png)

[4.30.0](https://vkcom.github.io/VKUI/4.30.0/#/SplitLayout)
![image](https://user-images.githubusercontent.com/42776347/168070923-ac383598-3011-4fd4-b4f4-e8ff384c3960.png)

**Пример с воспроизведением**
https://vkcom.github.io/VKUI/4.30.0/#/SplitLayout

**Comment by SevereCloud** [comment]
Привет, спасибо за issue

- Дубликат #2422
- Может быть поправлено в #2472

**Comment by inomdzhon** [comment]
Не совсем дубликат
В PR #2472 описал из-за чего возникла проблема
