### ISSUE TITLE
[Bug] CustomSelect уезжает Dropdown, если экран меньше элемента

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#2480]
**Описание**

Если, например, зазумить на MacOS, то Dropdown позиционируется неправильно

**Скриншоты**

При зуме:

<img width="782" alt="image" src="https://user-images.githubusercontent.com/11076888/168346547-c85b2254-28cf-4766-9bbc-622ddcd618d9.png">

При восстановлении после зума:

<img width="784" alt="image" src="https://user-images.githubusercontent.com/11076888/168346917-66dc8e00-0b03-4a6c-acfa-2242e487e132.png">

**Comment by SevereCloud** [comment]
Привет, фикс доступен в `4.33.1`
