### ISSUE TITLE
[Bug] CustomSelect изменяется размер placeholder при фокусе

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#2482]
**Описание**

font-size меняется с 15px на 16px

**Скриншоты**

<img width="115" alt="image" src="https://user-images.githubusercontent.com/11076888/168359989-912ce424-4299-495a-99db-03edd52aad21.png">

<img width="121" alt="image" src="https://user-images.githubusercontent.com/11076888/168360328-341bd16f-c486-4356-a90b-9f16f34c87c6.png">

**Comment by inomdzhon** [comment]
@eolme на `v4.31.0` не могу воспроизвести

Можешь предоставить следующее, плиз
1. Какая у тебя версия библиотеки?
2. Если это возможно, то ссылочку на воспроизведение в codesandbox

Заранее спасибо 🙏

**Comment by eolme** [comment]
В styleguide почему-то sizeY-compact на vkcom вне зависимости от высоты фрейма, если убрать compact, то воспроизовдится

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/11076888/170497421-18aa69c0-43f7-4ef9-8387-5dc1b9e580ec.png">

**Comment by eolme** [comment]
CustomSelect имеет 15px и меняет внутри себя на Input у которого 16px

**Comment by inomdzhon** [comment]
> CustomSelect имеет 15px и меняет внутри себя на Input у которого 16px

@eolme так... я запутался...

По заголовку issue, я понял, что изменяется размер placeholder при `фокусе`, но я не могу это воспроизвести. По коду `font-size: 15px` выставляется только при `sizeY="compact"`.

А случайно не вот эта бага воспроизводится у тебя https://github.com/VKCOM/VKUI/issues/1739?

**Comment by inomdzhon** [comment]
@eolme 👆 🙏
