### ISSUE TITLE
[Bug / Feature] Не поддержан вложенный ConfigProvider

### ISSUE THREAD

**Issue by worldwidebaby** [VKCOM/VKUI#2483]
Простая задача: использовать кастомный конфиг для какого-то компонента:
https://codesandbox.io/s/ecstatic-wiles-w3p73u?file=/src/_app.js

### Что нужно изменить
1. Убрать предупреждение о необходимости передать свойство scheme, которое помечено как устаревшее
2. Наследовать установленные выше значения
3. Не прокидывать классы на дочерний компонент (`vkuibright_light vkui--vkIOS--light`)

**Comment by worldwidebaby** [comment]
https://github.com/VKCOM/VKUI/blob/85b4edd3b377a2a8c32a38e0dab7cd24aff2dc64/src/components/ConfigProvider/ConfigProvider.tsx#L27-L31

**Comment by eolme** [comment]
На самом деле проблема в том, что вложенные ConfigProvider поддерживаются некорректно
