### ISSUE TITLE
[Bug] SplitCol уезжает вверх при открытии модального окна/попаута

### ISSUE THREAD

**Issue by ItzNeviKat** [VKCOM/VKUI#2496]
**Описание**
В многоколончатом интерфейсе при открытии модального окна или попаута происходит сдвиг вверх фиксированной колонки. Судя по [Release Notes](https://github.com/VKCOM/VKUI/releases/tag/v4.29.1) версии `4.29.1` - это связано с #2421, как раз там появился лок скролла.

**Версия библиотеки**
`4.29.1` и `4.30.0`. На `4.29.0` не воспроизводится, все хорошо.

**Шаги воспроизведения**
Проскроллить страницу вниз и открыть модальное окно или попаут.

**Скринкаст**
https://user-images.githubusercontent.com/24193020/169008041-c25165a0-1289-4e9f-9ae2-dc41a3899d1d.mov

**Пример с воспроизведением**
Исходный код - https://github.com/ItzNeviKat/vkma-template
Приложение, чтобы потыкать - https://vk.com/app8082788

**Comment by SevereCloud** [comment]
Привет, фикс будет доступен в v4.32.0

Сейчас у компонента SplitCol выставлен `top: auto`. При блокировке скролла, `top` высчитывается через js от его текущего положения.  С v5.0.0 мы выставим `top: 0`, чтобы избежать лишних расчетов через js
