### ISSUE TITLE
[Feature] Токенизировать `ActionSheetItem`

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#2505]
- [документация компонента](https://vkcom.github.io/VKUI/#/ActionSheetItem)
- [гайд по миграции на `vkui-tokens`](https://github.com/VKCOM/VKUI/blob/master/VKUI_TOKENS_MIGRATION_GUIDE.md)

**Comment by SevereCloud** [comment]
Смотри также #2018
