### ISSUE TITLE
Нет иконки крестика для удаления введенного текста в iOS UI

### ISSUE THREAD

**Issue by Rickflar** [VKCOM/VKUI#251]
Зайти в любой сервис через устройство с iOS.

ФР: В сервисах, запускаемых на iOS в полях ввода, где предусмотрена кнопка стирания текста, отсутствует иконка стирания (крестик), но область рабочая - тапнув в конце строки, текст сотрется. Тем не менее, она есть в этих же сервисах, при запуске на Android. 
ОР: Иконка крестика есть в iOS, как и на Android
Ссылка со скриншотами: [тап](https://drive.google.com/drive/folders/1AOnOUxzS9WEBi-XF2_Hjd96xWK6PWI9n?usp=sharing)

**Comment by mmarkelov** [comment]
@Rickflar так есть же кнопка **отменить**? Вообще либа повторяет нативные интерфейсы. И в iOS вроде как и нет этой иконки. Но я посмотрю можно ли это поменять

**Comment by Rickflar** [comment]
@mmarkelov дело в том, что есть и кнопка "Отменить", и область в конце поля ввода, куда можно тапнуть и стереть все (то бишь там, где, по идее, должен располагаться крестик)

**Comment by mmarkelov** [comment]
@Rickflar я понял про что идет речь. Полагаю, что правильным вариантом будет - убрать логику стирания с области в конце строки.

**Comment by ArthurStam** [comment]
Замержено. Попадет в следующий релиз.

**Comment by mmarkelov** [comment]
@Rickflar проверьте последний релиз **v2.21.0**

**Comment by Rickflar** [comment]
@mmarkelov проблема решена, но текст скрывается за этой областью, теперь там просто неактивная пустота.

**Comment by mmarkelov** [comment]
@Rickflar прости за столь долгий ответ. По какой-то причине не пришло уведомление о новом комментарии. Я не совсем понимаю, что хочется в итоге? Можно сократить эту область. Устроит ли такой вариант?
![пример](http://dl3.joxi.net/drive/2019/06/03/0026/1598/1717822/22/c4a6f92b85.jpg)

**Comment by Rickflar** [comment]
@mmarkelov Абсолютно, то, что привели на скриншоте, будет выглядеть лучше. Сейчас, там, в виду отсутствия кнопки удаления введенного текста на iOS, осталось пустое пространство - на скриншоте выше его гораздо меньше. Поэтому, да - решение выше будет выглядеть гораздо лучше.
