### ISSUE TITLE
[Feature] Токенизировать `ChipsInput`

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#2516]
- [документация компонента](https://vkcom.github.io/VKUI/#/ChipsInput)
- [гайд по миграции на `vkui-tokens`](https://github.com/VKCOM/VKUI/blob/master/VKUI_TOKENS_MIGRATION_GUIDE.md)

**Comment by SevereCloud** [comment]
Уже затокенизировано
