### ISSUE TITLE
[Enhancement][ChipsSelect] Сделать стабильным

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#2518]
- [ ] определиться с API

**Comment by eugpoloz** [comment]
(Рыба задачи; хочется войти в v5 без нестабильных компонентов)

**Comment by inomdzhon** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
