### ISSUE TITLE
[Enhancement][Popover] Сделать стабильным

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#2523]

**Comment by inomdzhon** [comment]
# Переименовать `Dropdown` в `Popover`

Название `Dropdown` предполагает под собой, что это некий список, например, пункты меню. А в текущей документации говорится, что можно в него добавлять всё что угодно. Под такое описание подходит название `Popover`.

Имя `Dropdown` нам может пригодиться.

**Comment by inomdzhon** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
