### ISSUE TITLE
Доработать компонент Button [Feature]

### ISSUE THREAD

**Issue by Fliqle** [VKCOM/VKUI#2528]
Нужно привести компонент Button в соответствие с библиотекой Figma. Сейчас типографика не соответствует тому что в макетах. Сейчас для Compact и Regular версии кнопок одного размера используются разные компоненты типографики, а в макетах один(значение регулируется токенами vkui-tokens). 
Паддинги внутри кнопок тоже нужно токенизировать. Токены на размеры расписаны в документации компонента в Notion.

**Comment by pfrankov** [comment]
Расширяет основную задачу #2510
Эту прикрою.
