### ISSUE TITLE
Некорректные атрибуты type у button

### ISSUE THREAD

**Issue by pepelsbey** [VKCOM/VKUI#253]
Похоже, что `<button>` у вас [может иметь](https://github.com/VKCOM/VKUI/blob/master/src/components/Button/Button.js#L59) атрибуты `type="default"` и `type="cell"`, но таких значений [не существует](https://w3c.github.io/html/sec-forms.html#the-button-element). Правильным [дефолтом](https://github.com/VKCOM/VKUI/blob/master/src/components/Button/Button.js#L71) был бы `type="button"`, поскольку по умолчанию это `type="submit"` и может отправить какую-нибудь случайную форму.

```
<button type="default" role="button">…</button>
```

**Comment by mmarkelov** [comment]
@pepelsbey 
- **type** в данном случае случае отвечает за то, какой компонент отрендерится https://github.com/VKCOM/VKUI/blob/75094ec198677d42f0a1047248cb0c0d0b2bcd2d/src/components/Button/Button.js#L28-L46
- В комментарии к пропам сказано 

> Свойство `type` будет удалено в 3.0.0

**Comment by pepelsbey** [comment]
Я понимаю, что эта штука делает в коде компонента, но почему она оказывается в финальном HTML?

**Comment by mmarkelov** [comment]
@pepelsbey С **restProps** передается, уже залили ПР. На счет сделать **type** по умолчанию - хорошая идея.

**Comment by kuhel** [comment]
> Я понимаю, что эта штука делает в коде компонента, но почему она оказывается в финальном HTML? Что вы скажете насчёт значения button по умолчанию, это сделает использование компонента безопаснее.

Спасибо за важное замечание, поправили и запушили

**Comment by kuhel** [comment]
https://github.com/VKCOM/VKUI/pull/255

**Comment by fedorov-xyz** [comment]
Спасибо за ишью. Пока убрали некорректный атрибут `type`, попадающий в HTML. В третьей версии свойство `type` у компонента будет отвечать за тип кнопки, который устанавливает ее поведение в форме.

**Comment by ArthurStam** [comment]
Мы перестали использовать свойство type для разделения типов кнопок. Теперь <Button type="submit" /> отрисовывается в <button type="submit" />. Доступно в 3-й версии.
