### ISSUE TITLE
[Enhancement][a11y] Добавить доступность для Tabs

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#2533]
Документация [tabpanel role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tabpanel_role)

**Компоненты:**
- [ ] `Tabs`
  - [ ] документация по доступности (https://github.com/VKCOM/VKUI/issues/3035)
- [ ] `TabsItem`
  - [ ] документация по доступности (https://github.com/VKCOM/VKUI/issues/3035)

**Comment by inomdzhon** [comment]
@k-egor-smirnov зарелизим в `v4.38.0`. Ещё раз спасибо :)
