### ISSUE TITLE
[Enhancement][a11y] Добавить доступность для `Checkbox`

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#2534]
- [ ] документация по доступности (https://github.com/VKCOM/VKUI/issues/3035)

------- 
Документация [checkbox role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/checkbox_role)

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/14944123/169663422-59dbe9bf-05e7-473d-99d2-a95cd8aa7fa1.png">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.3.0" target="_blank">v6.3.0</a> 🎉
