### ISSUE TITLE
[Enhancement][a11y] Добавить доступность для SimpleCheckbox

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#2535]
[SimpleCheckbox](https://vkcom.github.io/VKUI/#/SimpleCheckbox)

Документация [checkbox role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/checkbox_role)

**Comment by eugpoloz** [comment]
Связанная задача: https://github.com/VKCOM/VKUI/issues/2534

**Comment by SevereCloud** [comment]
[SimpleCheckbox](https://vkcom.github.io/VKUI/#/SimpleCheckbox) устарел
