### ISSUE TITLE
[Bug] Переполнение текста Tabs работает неверно Firefox

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#2536]
**Описание**
Переполнение текста Tabs работает неверно Firefox

**Версия библиотеки**
v4.31.0

**Версия браузера**
Firefox 100.0.1

**Шаги воспроизведения**
Открыть страницу с Tabs и слишком длинным текстом внутри TabsItem в Firefox

**Скриншоты**
<img width="367" alt="image" src="https://user-images.githubusercontent.com/14944123/169663697-f023d8e5-19a9-4da7-a5dd-4d15940eabae.png">

**Пример с воспроизведением**
[Tabs](https://vkcom.github.io/VKUI/#/Tabs)
[Counter](https://vkcom.github.io/VKUI/#/Counter)

**Comment by eolme** [comment]
#1963
