### ISSUE TITLE
[Feature] Токенизировать `FixedLayout`

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#2539]
- [документация компонента](https://vkcom.github.io/VKUI/#/FixedLayout)
- [гайд по миграции на `vkui-tokens`](https://github.com/VKCOM/VKUI/blob/master/VKUI_TOKENS_MIGRATION_GUIDE.md)
------
~будем ли мы вообще оставлять `FixedLayout`? Очень хотели от него избавиться~ (https://github.com/VKCOM/VKUI/issues/2674)

**Comment by inomdzhon** [comment]
>  будем ли мы вообще оставлять FixedLayout? Очень хотели от него избавиться

Была идея `fixed` на `sticky`, но там оч, много багов с ним. В любом случае минимум в `v5` стоит изучить вопрос.
