### ISSUE TITLE
[Research] Исследовать swc, как альтернативу Babel

### ISSUE THREAD

**Issue by pfrankov** [VKCOM/VKUI#2564]

**Comment by inomdzhon** [comment]
В первую очередь интересует есть ли плагин для SWC, который будет преобразовывать CSS Modules из
```jsx
import styles from "./Comp.module.css"
const Comp = () => <div className={styles.Comp} />
```
в
```jsx
require("./Comp.module.css");
var Comp = function () {
  return React.createElement("div", { className: "vkuiComp" });
}
```
но тщетно

> SWC doesn't support CSS-Module yet. you should create your own plugin for SWC to support CSS-Module.
> (c) [SWC with JavaScript: How to handle CSS imports and how to absolute imports?](https://stackoverflow.com/a/70964676/2903061)

так или иначе нужно писать своё решение для преобразования кода с CSS Modules в тот, в который мы хотим.

---

Задачу пока перемещаю в **Backlog**

**Comment by inomdzhon** [comment]
Задачу закрываю, чтобы не висела. В данный момент **Babel** удовлетворяет всем потребностям.

**Comment by inomdzhon** [comment]
@SevereCloud предложил всё же перейти на SWC, а проблему с плагинами решить написав свои

- Вот прирост скорости

    <img width="200" src="https://user-images.githubusercontent.com/5850354/215800734-0661a13c-0ca5-45f9-91b0-00447bbf2a0a.png" />
    
    <img width="200" src="https://user-images.githubusercontent.com/5850354/215800900-1d2bbb5e-1fc6-4202-8786-d481beece682.png" />
    
    <img width="200" src="https://user-images.githubusercontent.com/5850354/215800867-2ec6ed4b-ce30-4bbe-9684-0d54e45d0e13.png" />

Поэтому закрываю задачу как решенную.

---

- related to #4080
- related to #4074
