### ISSUE TITLE
Область right у PanelHeader в примерах

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#258]
Зачем в примерах повсеместно используется область `right` у `PanelHeader`, когда у VK Apps эта область зарезервирована под системное использование?

```jsx
<PanelHeader
  left={<PanelHeaderBack onClick={() => this.go(HOME_VIEW, MAIN_PANEL)} />}
  right={
    <PanelHeaderEdit
      isActive={editing}
      editLabel="Изменить"
      doneLabel="Готово"
      onClick={() => this.onHeaderEditClick()}
    />
  }
>
```

**Comment by fedorov-xyz** [comment]
Область применения VK UI не ограничивается VK Apps.

**Comment by mahnunchik** [comment]
@fedorov-xyz это понятно, что не ограничивается, но предлагать почти в каждом примере использовать правую область, которую не могут использовать VK APPS как-то не круто

**Comment by ArthurStam** [comment]
@mahnunchik отвечаю на вопрос: VKUI используется не только в VK Apps.

**Comment by mahnunchik** [comment]
@ArthurStam вы специально вставляете примеры которые НЕ работают в ОСНОВНОЙ области применения VK UI?
