### ISSUE TITLE
[Feature] Токенизировать `Tabs`

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#2584]
- [документация компонента](https://vkcom.github.io/VKUI/#/Tabs)
- [гайд по миграции на `vkui-tokens`](https://github.com/VKCOM/VKUI/blob/master/VKUI_TOKENS_MIGRATION_GUIDE.md)

**Comment by inomdzhon** [comment]
related #2351 

> ## Tabs
> - `mode="segmented"` удалён
