### ISSUE TITLE
Дефолтные импорты

### ISSUE THREAD

**Issue by polRk** [VKCOM/VKUI#260]
Уберите export default. Это плохой кейс, так как пользователи могут по разному написать импорт одного и того же компонента. Используйте export const .

**Comment by fedorov-xyz** [comment]
Сейчас и есть два способа импорта компонентов.

Предпочтительнее второй, так как при первом способе почти всегда в результирующий бандл приложения попадает вся библиотека.

```js
import { SelectMimicry } from '@vkontakte/vkui';
```

```js
import SelectMimicry from '@vkontakte/vkui/dist/components/SelectMimicry/SelectMimicry';
```

**Comment by polRk** [comment]
Лучше было-бы сделать 1 способ импорта, вот такой
`import { SelectMimicry } from  '@vkontakte/vkui/dist/components/SelectMimicry/SelectMimicry';`
Сразу решаем проблемы с неймингом и импортом всей библиотеки.

Ибо в вашем случаем можно сделать так 
```
import SelectMimisry from '@vkontakte/vkui/dist/components/SelectMimicry/SelectMimicry';
import SelectMinicry from '@vkontakte/vkui/dist/components/SelectMimicry/SelectMimicry';
import SelectMimicri from '@vkontakte/vkui/dist/components/SelectMimicry/SelectMimicry';
```
Случайная опечатка и головная боль для всех остальных членов команды .

**Comment by fedorov-xyz** [comment]
IDE обычно подсказывает импорт, то есть `SelectMinicry` вместо `SelectMimicry` не получится.

**Comment by polRk** [comment]
А мы ограничиваемся только ide ? Да даже если руками  неправильно написать компонент <SelectMinicry, то идее не найдет такой компонент. Плюс можно вручную написать импорт и ide не будет ругаться.

**Comment by mmarkelov** [comment]
@polRk я совсем в этом плохого кейса не вижу. 90 процентов либ использует export default и головной боли по этому поводу никто не высказывал

**Comment by ArthurStam** [comment]
Очень странное предложение. export default помогает избегать лишней писанины и не принуждает запоминать имена экспортируемых сущностей.
