### ISSUE TITLE
Apple IPhone SE - Съезжает навбар 

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#261]
https://vk.com/bug115006

Пока воспроизвелось только на Apple IPhone SE

![DBKvn2j3knw](https://user-images.githubusercontent.com/780935/55652741-1dcba480-57f5-11e9-8368-38568201893f.jpg)

**Comment by fedorov-xyz** [comment]
Привет. Спасибо за ишью. Проблема известная, и удалось выяснить вот что: такое происходит из-за неправильной минификации CSS, которая вырезает часть свойств, необходимых для корректного отображения шапки на iPhone SE и iOS 10 в целом. Попробуем решить эту проблему со стороны библиотеки.

**Comment by mahnunchik** [comment]
@fedorov-xyz спасибо! Вот ещё https://vk.com/bug115104 Теперь надо понять как мне правильно закрыть эти тикеты  моём проекте в трекере.

**Comment by ArthurStam** [comment]
Закрываю тикет, это не проблема либы.

**Comment by mahnunchik** [comment]
@ArthurStam а на чьей стороне проблема? Как собрать так, чтобы работало на iOS 10?

**Comment by kuhel** [comment]
> @ArthurStam а на чьей стороне проблема? Как собрать так, чтобы работало на iOS 10?

Есть подозрение, что устарели зависимости. Поробуйте обновить их. Пример актуальных — https://github.com/VKCOM/create-vk-app/blob/master/package.json

**Comment by mahnunchik** [comment]
@kuhel спасибо за рекомендацию, проверил, зависимости обновлены, похоже проблема глубже.

**Comment by mahnunchik** [comment]
@ArthurStam @fedorov-xyz не подскажите, какие CSS свойства портит сборщик?

**Comment by mahnunchik** [comment]
В `react-scripts` не будут убирать настройку `no-2009` которая ломает сборку библиотеки VKUI для iOS 10.

@ArthurStam предлагают решение, наставить комменты в самой библиотеки: https://github.com/postcss/autoprefixer/issues/1141#issuecomment-431280891

Или уберите поддержку VK Apps на iOS 10, что тоже решит проблему.
