### ISSUE TITLE
[Feature][a11y] Отойти от `aria-label` в пользу скрытого визуально текста

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#2673]
Поскольку изначально мы хотели реализовать базовую доступность библиотеки как можно скорее, мы пошли коротким путем и во многих местах (например, в кнопках-иконках) воспользовались `aria-label`. Это не лучший подход. В идеале внутри кнопок лучше размещать скрытый `span` с текстом-названием.

- `aria-label` не всегда консистентно озвучивается,
- инструменты автоперевода могут не справляться с `aria-label`, потому что про него часто забывают.

(Статья об этом: [Revisting aria-label versus a visually hidden class](https://gomakethings.com/revisting-aria-label-versus-a-visually-hidden-class/))

## Приблизительный план:
- [x] https://github.com/VKCOM/VKUI/issues/4639
- [ ] заменить текущие использования `aria-label` на скрытый только для скринридеров текст
- [ ] добавить варнинги-подсказки для разработчиков

**Comment by inomdzhon** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
