### ISSUE TITLE
[Bug] Пропала тень у PanelHeader для VKCOM

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#2675]
**Описание**
Пропала тень и закругления у PanelHeader для VKCOM

https://github.com/VKCOM/VKUI/pull/2382/files#diff-24c96a961741eda19a80f3fa2f271d1ba98e8aa38ae2c8f652d24a5b7b92c997L234-L241

**Версия библиотеки**
v4.32.0

**Скриншоты**
<img width="613" alt="image" src="https://user-images.githubusercontent.com/14944123/172234812-5482d5aa-54f2-4381-b39c-a1e4fabde967.png">

**Пример с воспроизведением**
https://vkcom.github.io/VKUI/#/SplitLayout

**Comment by eugpoloz** [comment]
Получается, у нас были изначально неправильные скриншоты? На них не было тени и закруглений для vkcom.

**Comment by SevereCloud** [comment]
Сейчас там скриншоты для адаптивности по ширине < 768px. 
Нужно бы добавить скриншотов для адаптивности по `x`
