### ISSUE TITLE
описание компонента Touch в документации

### ISSUE THREAD

**Issue by Gaserd** [VKCOM/VKUI#268]
### Что нужно сделать?

Сделать описание для компонента Touch в документации, аналогичным способом, как сделаны и другие компоненты

### Результат

Документация к компоненту

**Comment by mmarkelov** [comment]
@Gaserd она действительно нужна? В большей степени это внутренний компонент. Есть кейсы, когда его использование необходимо?

**Comment by Gaserd** [comment]
@mmarkelov 
Да, например если кто то захочет сделать канвас с рисовалкой или сделать компонент шторку снизу.

**Comment by ArthurStam** [comment]
[Done](https://vkcom.github.io/vkui-styleguide/#!/Touch)
