### ISSUE TITLE
Обрезается шапка при загрузке страницы

### ISSUE THREAD

**Issue by VladAnesov** [VKCOM/VKUI#269]
Воспроизведение:
1) Открыть приложение
2) Вертикальный скрол (вниз/вверх)
3) Перейти к новой странице (изменить Panel)

![image](https://user-images.githubusercontent.com/20639636/55799526-47791a00-5ada-11e9-979e-8b92041c1633.png)

**Comment by ciricc** [comment]
Скорее всего проблема возникает из-за того, что вы меняете цвет панели на кастомный.

Фиксится самостоятельно, ищите в сторону `.PanelHeader--ios .PanelHeader-bg::after `
