### ISSUE TITLE
[Bug][Doc] FormField некорректно отображается в Compact режиме

### ISSUE THREAD

**Issue by Zaycevq** [VKCOM/VKUI#2690]
**Описание**
— При переключение на Compact не меняется высота из-за Паддингов текста.
— Не меняется размер текста
— Большой отступ от иконки слева до текста (так же из-за паддингов) (в обеих версиях Regular / Compact)

<img width="899" alt="form-field" src="https://user-images.githubusercontent.com/91548592/172882138-29a61448-fd64-4193-9e2e-8bcc7c1bf81c.png">

**Дизайн**
https://www.figma.com/file/2sQl2eaxsp7RDRdMOeneEC/%F0%9F%92%A0-VKUI-Common-Library-(Alpha)?node-id=18881%3A101329

**Comment by inomdzhon** [comment]
Так, проблема в том, что `FormField` это базовый компонент, который не задаёт размеры шрифта и высоты

Перенесу реализацию песочницы в доку `Input`, а здесь уберу этот пример
