### ISSUE TITLE
[Bug][BREAKING CHANGE] Исправить вызов коллбэк-функций компонента Gallery

### ISSUE THREAD

**Issue by BlackySoul** [VKCOM/VKUI#2698]
**Описание**
Компонент Gallery неверно вызывает коллбэк onDragStart + содержит два по сути одинаковых коллбэка onDragEnd и onEnd (оставляем один onDragEnd с добавлением второго параметра - индекса слайда) 

**Версия библиотеки**
Latest

**Шаги воспроизведения**
- пролистывая слайды, можно увидеть, что onDragStart вызывается на каждое движение мыши, а onDragEnd и onEnd практически идентичны по семантике

**Ожидаемое поведение**
-

**Скриншоты**
Опционально.

**Пример с воспроизведением**
https://vkcom.github.io/VKUI/#/Gallery - добавить сюда коллбэки onDragStart, onDragEnd и onEnd

**Comment by inomdzhon** [comment]
relate #2351
