### ISSUE TITLE
[Feature] Упрощение анимаций при `preferes-reduced-motion`

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#2703]
В зависимости от [prefers-reduced-motion](https://developer.mozilla.org/ru/docs/Web/CSS/@media/prefers-reduced-motion) необходимо уменьшить анимации с перемещением и с изменением размеров. Благодаря такому подходу пользователи с проблемами с вестибулярным аппаратом смогут пользоваться приложениями на VKUI без спецэффектов.

> [!NOTE]
>  
> Так как `prefers-reduced-motion` лишь частично покрывает наш [.browserslistrc](https://github.com/VKCOM/VKUI/blob/v6.1.0/.browserslistrc), то на старых устройствах анимации упрощаться не будут.

## Ссылки

- [Designing With Reduced Motion For Motion Sensitivities](https://www.smashingmagazine.com/2020/09/design-reduced-motion-sensitivities/)
- [Animation from Interactions (Level AAA)](https://www.w3.org/WAI/WCAG21/Understanding/animation-from-interactions)
- [Short note on `prefers-reduced-motion` and puzzled (Windows) users](https://www.tpgi.com/short-note-on-prefers-reduced-motion-and-puzzled-windows-users/)

**Comment by eugpoloz** [comment]
Пример, где это уже сделано (с опорой на `prefers-reduced-motion: no-preference `):

https://github.com/VKCOM/VKUI/blob/a01501173c28f718e87d1580361e55ecf17f14cd/src/components/FocusVisible/FocusVisible.css#L22-L28

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.0" target="_blank">v6.2.0</a> 🎉
