### ISSUE TITLE
[Feature] Прямоугольные изображения, переданные в Avatar растягиваются

### ISSUE THREAD

**Issue by danillas** [VKCOM/VKUI#2780]
Компонент Avatar всегда квадратный, но изображения которые в него передаются чаще прямоугольные и растягиваются по вертикали или горизонтали.

Предложение - умолчанию добавить 
```
.vkuiAvatar__img { 
     object-fit: cover; 
}
```

Как есть сейчас:
<img width="110" alt="без object-fit " src="https://user-images.githubusercontent.com/26124760/176920499-1f46f7c2-5e76-4f07-855b-45b65a9d6b3e.png">

Станет по умолчанию. Сейчас приходится добавлять фикс в проекте:
<img width="107" alt="с object-fit" src="https://user-images.githubusercontent.com/26124760/176920586-0c528b20-aa08-4919-b60a-b512ce631bb5.png">

**Comment by SevereCloud** [comment]
Привет, фикс доступен в [v4.33.4](https://github.com/VKCOM/VKUI/releases/tag/v4.33.4)
