### ISSUE TITLE
[Doc] Добавить информацию для сопровождающих 

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#2790]
Добавить информацию для сопровождающих в [CONTRIBUTING.md](https://github.com/VKCOM/VKUI/blob/master/docs/CONTRIBUTING.md)

- Обновление скриншотов (https://github.com/VKCOM/VKUI/actions/workflows/update_screens.yml)
- Создание релизов (https://github.com/VKCOM/VKUI/actions/workflows/publish.yml)
- Создание патчей (#2759)

**Comment by SevereCloud** [comment]
> 2. Я бы про патчи, драфты релизов и релизы сделала отдельный док (RELEASE.md или что-то в этом роде), а в CONTRIBUTING.md дала бы на него ссылку. Что скажешь?

Можно сделать отдельно в `MAINTAINERS.md`

**Comment by eugpoloz** [comment]
Связанный пулл: https://github.com/VKCOM/VKUI/pull/3269
Без него эта задача пока заблочена (не описать полноценный флоу для релизов).
