### ISSUE TITLE
PanelHeader в Microsoft Edge

### ISSUE THREAD

**Issue by aplinxy9plin** [VKCOM/VKUI#280]
В Microsoft Edge 42.17134.1.0 некорректно отображается PanelHeader.
![image](https://user-images.githubusercontent.com/6073897/56467850-6ec2d600-644e-11e9-8324-22526ac72a75.png)

**Comment by ArthurStam** [comment]
Либа на сегодняшний день стабильно работает только в ios >= 9 и android >= 4.4. Во всех остальных браузерах могут быть какие угодно артефакты.
