### ISSUE TITLE
[BREAKING CHANGE][Tappable] Навести порядок в свойствах

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#2801]
**Проблема:**

Сейчас у `Tappable` (и у `Touch`, на котором он основан) вместо родных `onMouseLeave` и `onMouseEnter` используются алиасы `onLeave` и `onEnter`. При этом типы описаны неконсистентно. У `Tappable` исключен `onMouseLeave`, но `onMouseEnter` остался:
https://github.com/VKCOM/VKUI/blob/a9e67427b473e487348b923ca565e53759900a08/src/components/Tappable/Tappable.tsx#L25-L36

У `Touch` вообще ничего не исключается:
https://github.com/VKCOM/VKUI/blob/a9e67427b473e487348b923ca565e53759900a08/src/components/Touch/Touch.tsx#L15-L16

**Comment by eugpoloz** [comment]
Звучит как связанная с https://github.com/VKCOM/VKUI/issues/1443

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
