### ISSUE TITLE
[Bug] На iOS двигается страница при закрытии модалки в браузере

### ISSUE THREAD

**Issue by k-egor-smirnov** [VKCOM/VKUI#2806]
**Описание**
Если закрывать модалку ближе к адресной строке, то Safari начинает анимацию перезагрузки страницы.

**Версия библиотеки**
4.33.3

**Шаги воспроизведения**
1. Открыть ModalPage во всю высоту на iOS >= 15
2. Зажать палец на ModalPageHeader
3. Провести пальцем вниз

**Ожидаемое поведение**
При закрытии модалки не будут начинаться системные жесты вроде перезагрузки страницы

**Скриншоты**
![image](https://user-images.githubusercontent.com/17943083/177732909-108f710c-a50c-4b0e-9f04-375a99d94646.png)

**Пример с воспроизведением**
https://codesandbox.io/s/distracted-napier-h50949

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.4" target="_blank">v5.9.4</a> 🎉
