### ISSUE TITLE
Styleguide / Если ввести не цифровой символ в поле ввода слайдера, произойдет ошибка

### ISSUE THREAD

**Issue by VladAnesov** [VKCOM/VKUI#281]
В input где установлено float значение слайдера вводим любой символ.

![image](https://user-images.githubusercontent.com/20639636/56738496-6ed81400-6775-11e9-86f6-a7a8de5a30da.png)

![image](https://user-images.githubusercontent.com/20639636/56738515-75668b80-6775-11e9-9825-4d43a8e225ff.png)

**Comment by mmarkelov** [comment]
@VladAnesov залил фикс для styleguide. Но проблема, на самом деле еще глубже. ИМХО в самом компоненте стоит проверять валидность данных:
https://github.com/VKCOM/VKUI/blob/aa07f2893ba11d0bbfd9524bb12c2631bddd266e/src/components/Slider/Slider.js#L138
Если **value** **NaN** уйдет в бесконечный ререндеринг

**Comment by mmarkelov** [comment]
@ArthurStam про проверку входных данных что скажешь? есть смысл ограничивать цифрами?
