### ISSUE TITLE
Баг c Range Slider

### ISSUE THREAD

**Issue by kovalyovkirill** [VKCOM/VKUI#283]
Не получается выставить значения min=0 и max=1.

Как воспроизвести:
Левый ползунок выставить на 0, максимум влево. Двигать правый, как только правый ползунок приближается к 1, левый прыгает на 1 а правый на 2. Визуально можно проверить на https://vkcom.github.io/vkui-styleguide/#rangeslider.

**Comment by mmarkelov** [comment]
@kovalyovkirill я почему-то не могу воспроизвести

**Comment by ArthurStam** [comment]
+, тоже не воспроизводится.

**Comment by thoughtspile** [comment]
FYI #600
