### ISSUE TITLE
Экранируются параметры ссылки при переходе в мобильный клиент

### ISSUE THREAD

**Issue by abaranovskii** [VKCOM/VKUI#284]
Если параметры ссылки содержат экранируемые символы (/, & и т.д), то при переходе в мобильный клиент (IOS, Android) они заменяются:

https://vk.com/app111111#page/1 -> https://vk.com/app111111#"page%2F1

На десктопе такой проблемы нет.

**Comment by ArthurStam** [comment]
Это явно не проблема фреймворка.

**Comment by abaranovskii** [comment]
@ArthurStam подскажи куда писать? Это баг, который подтвердили разработчики в чате

**Comment by ArthurStam** [comment]
Если речь про VK Apps окружение, то лучше обратиться к разрабам этой платформы, они подскажут. Я сомневаюсь, что в либе что-то может ломать ссылки.
