### ISSUE TITLE
Ломается анимация при смене параметра header и activePanel у View

### ISSUE THREAD

**Issue by zhekaso** [VKCOM/VKUI#285]
Если сделать, что-то типа такого
`<View activePanel={this.state.activePanel} header={(this.state.activePanel) === 'home' ? false : true}>`

, то при переходе от панели без шапки к панели с шапкой (и наоборот), наблюдаются глюки в анимации, связанные с появлением пустой шапки (или скрытием рабочей шапки) перед началом анимации

**Comment by mmarkelov** [comment]
@zhekaso не удалось воспроизвести - скрытие хедера происходит без видимых косяков. Нужно больше информации как воспроизвести 
![test](https://media.giphy.com/media/SUu8lqMCCRrHHr3J3A/giphy.gif)

**Comment by zhekaso** [comment]
На вашей гифке в принципе тоже видно, когда идет переход от Персика к Домашней странице, сначала появляются отступы под шапку на панели персика, потом идет анимация сдвига. В хроме есть возможность смотреть покадрово анимацию(через вкладку Perfomance).

**Comment by zhekaso** [comment]
Наверное странным было архитектурное решение относить шапку к View, и чтобы PanelHeader подключался через портал

**Comment by mmarkelov** [comment]
@zhekaso возможно это было связано с тем, что это достаточно нечастый кейс. Подумаю что можно с этим сделать

**Comment by ArthurStam** [comment]
Вообще сейчас в пределах одного View либо у всех панелей должен быть header, либо ни у одной. У нас есть issue по этому поводу. Постараемся сделать так, чтобы можно было скрывать шапки не у всех панелей.

**Comment by ArthurStam** [comment]
Закрываю этот тикет. За скрытием шапки у панели следите тут: #101
