### ISSUE TITLE
iOS12.2 web view, графические артефакты

### ISSUE THREAD

**Issue by casper1149** [VKCOM/VKUI#287]
Здравствуйте,

заметил появление следующих графических артефактов при использовании сервиса из приложения ВК. При работе с сервисом с помощью браузера все отрабатывает корректно без каких либо графических артефактов.

```
    "@vkontakte/icons": "^1.4.3",
    "@vkontakte/vkui": "^2.21.3",
    "@vkontakte/vkui-connect": "^1.1.3",
    "core-js": "^2.6.5",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "2.1.8"
```

Браузер:
![Screen Shot 2019-05-10 at 10 43 07 AM](https://user-images.githubusercontent.com/4508785/57536500-50941b80-7312-11e9-8cc9-95131e8262b1.png)

Мобильный клиент:
![IMG_8857](https://user-images.githubusercontent.com/4508785/57536564-6c97bd00-7312-11e9-8f81-57d7f61fbfca.PNG)

![IMG_8858](https://user-images.githubusercontent.com/4508785/57536576-70c3da80-7312-11e9-9542-20a57e41a1f5.PNG)

![IMG_8856](https://user-images.githubusercontent.com/4508785/57536583-74576180-7312-11e9-8e95-d3e40a2d4d97.PNG)

И еще один
![IMG_8859](https://user-images.githubusercontent.com/4508785/57536655-9c46c500-7312-11e9-800e-5c17ac1c7e69.PNG)

Вероятно что-то не так с iOS web view.

**Comment by Gaserd** [comment]
А могли бы скинуть код к вашим карточкам? @casper1149

**Comment by casper1149** [comment]
```
<Div>
    <Group className="card" title={...} description={...}>
        <Div className="cardContent">
            {story}
        </Div>
    </Group>
</Div>
```

```
.card {
  border-radius: 8px;
  filter: drop-shadow(0 8px 8px rgba(0,0,0, 0.4));
}

.card_content {
  line-height: 1.5;
  overflow-y: auto;
  white-space: pre-wrap
}
```

**Comment by ArthurStam** [comment]
Вы уверены, что артефакты не из-за фильтров в `.card`?

**Comment by ArthurStam** [comment]
Закрываю за отсутствием активности.
