### ISSUE TITLE
Как можно решить проблему неработающих CSS переменных на старых устр-вах?

### ISSUE THREAD

**Issue by ciricc** [VKCOM/VKUI#288]
React компилирует стили конечно с подстановкой реальных значений перед стилем с var(--v),
но он это делает корректно только для светлой темы, а на темной теме он не учитывает то, что есть body[scheme="client_dark"]. Получается так, что он поросто игнорирует эту тему для старых браузеров.

Как можно это исправить? postcss тоже не хочет понимать это никак

**Comment by ciricc** [comment]
Выход вижу простейшим дублированием стилей для разных цветовых схем, но так получится в два раза больше CSS

`
body .block { color: var(--primary-color); }
body[scheme="client_dark"] .block { color: var(--primary-color-dark);  }
`

**Comment by ArthurStam** [comment]
Мы сознательно так сделали. Реальное значение перед var – это фоллбэк, чтобы на совсем старых устройствах, типа Android < 4.4 и iOS < 9. Иначе придется хранить несколько css-бандлов и подкачивать их при изменении схемы. Это как-то очень жирно для фоллбэка.

**Comment by ciricc** [comment]
Проблема в том, что на Android 4.4 и 5.1 темная тема вообще не работает

**Comment by ArthurStam** [comment]
Хм. На девайсах нашего тестового парка таких проблем нет. Можете сказать, что за девайсы?

**Comment by ArthurStam** [comment]
Закрываю, потому что так и не получил инфу о девайсах с багами.
