### ISSUE TITLE
Компонент календарь в стандартную библиотеку компонентов

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#290]
Столкнулся с тем, что HTML инпут для выбора даты [`<input type="date">`](https://developer.mozilla.org/ru/docs/Web/HTML/Element/Input/date) достаточно глючный, а именно:

1. Не поддерживает атрибуты min/max на iOS.
2. Форматирует дату в зависимости от локали вебвью открывшей страницу.
3. На Android иногда не влазит весь месяц О_о

Было бы здорово иметь в библиотеке компонентов календарь:

* Выбор конкретной даты
* Выбор диапазона дат

**Comment by mmarkelov** [comment]
@mahnunchik как вариант могу предложить существующие решения на Реакте, к примеру [react-dates](https://github.com/airbnb/react-dates)

**Comment by mahnunchik** [comment]
@mmarkelov спасибо за отличный вариант, попробую кастомизировать.

Но если будет элемент в комплекте, то будет ещё лучше ;)

**Comment by mmarkelov** [comment]
@mahnunchik просто, думаю, что если он и появится, то не в скором времени - так что пока так)

**Comment by ArthurStam** [comment]
Хороший реквест, но нам пока хватает нативных HTML инпутов. С min/max конечно засада, но не настолько критичная, чтобы пилить свой компонент.
