### ISSUE TITLE
Есть возможность скролить страницу с открытым HeaderContext

### ISSUE THREAD

**Issue by ciricc** [VKCOM/VKUI#291]
В идеале при начале скрола он должен сам закрываться, вызывая за этим onClose

**Comment by mmarkelov** [comment]
@ciricc А мне кажется при открытом **HeaderContext** стоит блочить возможность скроллить основной экран

**Comment by ciricc** [comment]
Возможно, но в клиенте ВК сделано именно так, что скролл не блочится. В общем-то, решать вам

**Comment by mmarkelov** [comment]
@ciricc смотрю нативный клиент и он при открытом **HeaderContext** не дает скроллить страницу:
![IMG_72B50122F26F-1](https://user-images.githubusercontent.com/22371328/58863960-8a133900-86bc-11e9-9cce-10332eef97bf.jpeg)

**Comment by mmarkelov** [comment]
@ArthurStam @fedorov-xyz что скажете?

**Comment by ArthurStam** [comment]
Я б сказал, это баг и его надо поправить :) я поговорю с дизайнерами, чтобы понять, какое из предложенных поведений лучше.

**Comment by fedorov-xyz** [comment]
https://vk.com/bug127870
