### ISSUE TITLE
[Feature] Добавить поле `status` для FormField

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#2912]
Для компонентов ввода задать статус можно только через [FormItem](https://vkcom.github.io/VKUI/#/FormItem), но нельзя задать отдельно(например когда поля сгруппированы)

**Comment by inomdzhon** [comment]
Думаю стоит удалить возможность передавать `status` в `FormItem`, пусть `FormField` умеет.

Кажется `status` появился у `FormItem` как раз для того, чтобы избежать проброса `status` в каждый компонент, который использует `FormField` внутри себя.

**Comment by SevereCloud** [comment]
> Думаю стоит удалить возможность передавать `status` в `FormItem`, пусть `FormField` умеет.
> 
> Кажется `status` появился у `FormItem` как раз для того, чтобы избежать проброса `status` в каждый компонент, который использует `FormField` внутри себя.

`status` в `FormItem` не только влияет на `FormField`, но и изменяет цвет у `bottom` текста

<img width="341" alt="image" src="https://user-images.githubusercontent.com/14944123/182099379-86508d8b-e6d3-496e-a133-cfcb301cbffb.png">
<img width="348" alt="image" src="https://user-images.githubusercontent.com/14944123/182099510-243b552a-12c1-43d8-931d-043140a0d089.png">

**Comment by inomdzhon** [comment]
> > Думаю стоит удалить возможность передавать `status` в `FormItem`, пусть `FormField` умеет.
> > Кажется `status` появился у `FormItem` как раз для того, чтобы избежать проброса `status` в каждый компонент, который использует `FormField` внутри себя.
> 
> `status` в `FormItem` не только влияет на `FormField`, но и изменяет цвет у `bottom` текста
> 
> <img alt="image" width="341" src="https://user-images.githubusercontent.com/14944123/182099379-86508d8b-e6d3-496e-a133-cfcb301cbffb.png">
> 
> <img alt="image" width="348" src="https://user-images.githubusercontent.com/14944123/182099510-243b552a-12c1-43d8-931d-043140a0d089.png">

Я чуть не написал параметр `caption` у `FormField`, НО! Меня осенило...

По идее у нас не должно быть отдельных компонентов `InputGroup`, `SelectGroup` и подобных. У нас есть `FormLayoutGroup`, который умеет группировать `FormItem`. Вот он пусть продолжает всем этим заниматься. 

Создавая компоненты такие как `InputGroup` (#2869) мы куда-то не туда идём. Вот пример UI из PR:

<img alt="image" width="348" src="https://user-images.githubusercontent.com/5850354/182104068-eb93c7d3-b45e-4779-a2ea-1dda700e09aa.png">

1. В блоке **Введите ФИО**, если я захочу показать текст ошибки, то мне надо будет динамически менять `<FormItem bottom="<текст_ошибки>">`. Надо будет также динамически менять `aria-describedby`, чтобы скринридер понимал к какому полю относится ошибка.
2. В блоке **Выберите дату рождения** тоже самое. Но если использовать на `FormLayoutForm` с `FormItem`, то будет отдельная ошибка для каждого поля ввода.

Это "слипание" можно только для горизонтального режима включить в `FormLayoutGroup`.

В общем вкину всё выше написаное на созвоне дизайнерам.
