### ISSUE TITLE
[Bug] Некорректные отступы у before элемента в SimpleCell

### ISSUE THREAD

**Issue by lexstile** [VKCOM/VKUI#2928]
**Описание**
При добавлении `<Switch />` в `<SimpleCell before={<Switch />} />` и `<Cell before={<Switch />} />` некорректные отступы.

**Версия библиотеки**
4.33.4

**Ожидаемое поведение**
Справа от `<Switch />` есть отступ.

**Скриншоты**
![image](https://user-images.githubusercontent.com/30532019/182840372-a8d719fc-a04c-44f3-b94b-bf5d82babf95.png)

**Comment by SevereCloud** [comment]
Фикс будет доступен в v4.34.2
