### ISSUE TITLE
[Bug]: Разное поведение длинного текста у Select компонентов

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#2950]
### Описание

У компонентов NativeSelect, CustomSelect, ChipsSelect разное поведение когда в `placeholder` длинный текст

### Версия

4.34.2

### В каких браузерах воспроизводится проблема?

Firefox, Chrome, Safari

### Ожидаемое поведение

Одинаковое поведение для Select компонентов

### Скриншоты

<img width="216" alt="image" src="https://user-images.githubusercontent.com/14944123/183469526-52311f8e-9321-4f36-b8d8-ee13a21dc898.png">

### Пример с воспроизведением

https://codesandbox.io/s/selects-8d0nh5?file=/src/index.js

**Comment by winterzz-dev** [comment]
Какой из селектов брать, как эталон? Предположу, что `CustomSelect`, поскольку в его стилях есть выражение `after && styles['Select--hasAfter']`, и оно убирает `padding-right` для плейсхолдера (само условие можно убрать, поскольку в пропсах принимается значение по умолчанию).
В таком случае нужно убирать `padding-right` для плейсхолдера в `NativeSelect`
С ChipsSelect сложнее, поскольку зависит от стилей `ChipInput` и эти стили расходятся с другими селектами (другие отступы и размер шрифта в плейсхолдере)

**Comment by SevereCloud** [comment]
Да, как в CustomSelect. Эталон -- это [дизайн](https://www.figma.com/community/file/1176983742890268380)
