### ISSUE TITLE
Будет ли синхронизация с VK UI который был раньше от Happy Santa? (Для ПК версии)

### ISSUE THREAD

**Issue by ciricc** [VKCOM/VKUI#296]
Я не использовал эту либу раньше, но в ней, как я понял, есть поддержка отображения компонентов для ПК, что было бы круто и для VK UI на сегодняшний день (речь о https://happysanta.github.io/vk-app-ui/styleguide/)

**Comment by NOCELL** [comment]
Вы можете сделать библиотеку, в которой объедините vkui и hsui, чтобы делать UI для mobile и web в одном бандле.
