### ISSUE TITLE
[Bug]: ошибка при нажатии на селектор <Select>

### ISSUE THREAD

**Issue by debl0w** [VKCOM/VKUI#2967]
### Описание

Если нажать на тэг \<Select\>, то приключается такая ошибка:
![image](https://user-images.githubusercontent.com/111088619/184235081-63a5ce94-df61-4d8a-b2a1-dd551d25a322.png)

### Версия

4.35.1

### В каких браузерах воспроизводится проблема?

Yandex Browser

### Шаги воспроизведения

1. Нажать на Select

### Ожидаемое поведение

ошибки в консоли быть не должно

### Скриншоты

![image](https://user-images.githubusercontent.com/111088619/184235191-2cd24712-39f0-4bf6-8860-6b49e9b62216.png)

> Popper: modifier "customSelectChildrenChange" provided an invalid "fn" property, expected "function" but got "undefined"
> in Popper (created by CustomSelectDropdown)
> in CustomSelectDropdown (created by CustomSelectComponent)
> in CustomSelectComponent (created by AdaptivityConsumer)
> in AdaptivityConsumer (created by SelectComponent)
> in SelectComponent (created by Select)
> in Select (at src/​index.js:34)
> in App (at src/​index.js:59)

### Пример с воспроизведением

https://codesandbox.io/s/issue2967-9ijf23?file=/src/index.js

**Comment by stoope** [comment]
@debl0w исправлено в v4.35.2
