### ISSUE TITLE
[Bug]: В Calendar не выбирается январь

### ISSUE THREAD

**Issue by danillas** [VKCOM/VKUI#2971]
### Описание

В календаре не выбирается январь. Со всеми остальными месяцами проблем нет

### Версия

4.35.1

### В каких браузерах воспроизводится проблема?

Chrome 104.0.5112.79 (актуальная), macOS

### Шаги воспроизведения

Предусловия: текущий месяц выбран отличный от января

1. Открыть календарь
2. Выбрать январь
3. Ничего не происходит

Вопроизводится тут https://vkcom.github.io/VKUI/#/Calendar

### Ожидаемое поведение

Выбираются все месяца, в том числе январь

### Пример с воспроизведением

```shell
https://codesandbox.io/s/ecstatic-austin-jvn4sf?file=/src/index.js
```

**Comment by stoope** [comment]
@danillas исправлено в v4.35.2
