### ISSUE TITLE
[Bug]: Dropdown с Calendar закрывается при выборе года или месяца

### ISSUE THREAD

**Issue by danillas** [VKCOM/VKUI#2972]
### Описание

При выборе года или месяца закрывается Dropdown, внутри которого размещен Calendar. Год или месяц при этом не меняются

### Версия

4.35.1

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

1. Открыть Calendar кликом на Input
2. Выбрать месяц | Выбрать год
3. Dropdown с Calendar закрылся, значения не изменились

### Ожидаемое поведение

Dropdown не закрывается при выборе года или месяца
Выбранные значения применяются

### Пример с воспроизведением

```shell
https://codesandbox.io/s/vkui-calendar-in-dropdown-rgpm2k
```

**Comment by stoope** [comment]
@danillas Привет! Спасибо за issue)
У нас есть специальный компонент [DateInput](https://vkcom.github.io/VKUI/#/DateInput) для таких случаев, он не подходит?

**Comment by danillas** [comment]
@stoope Да, он нам подходит, но ждём фикс https://github.com/VKCOM/VKUI/issues/2971

Пожелание по доку: Было бы хорошо упомянуть про DateInput в описании Calendar (https://vkcom.github.io/VKUI/#/Calendar)
