### ISSUE TITLE
[Bug]: Ошибка при открытии CustomSelect

### ISSUE THREAD

**Issue by SelenZzz** [VKCOM/VKUI#2975]
### Описание

При нажатии на CustomSelect в консоле возникает ошибка: `Popper: modifier "customSelectChildrenChange" provided an invalid "fn" property, expected "function" but got "undefined" `

### Версия

4.35.1

### Шаги воспроизведения

1. Нажать на CustomSelect

### Скриншоты

<img width="683" alt="изображение" src="https://user-images.githubusercontent.com/58228495/184400242-55ccbf48-d77e-4bfb-9d75-9afdb975d5a7.png">

### Пример с воспроизведением

[https://codesandbox.io/s/objective-noyce-fkexop?file=/src/index.tsx](https://codesandbox.io/s/objective-noyce-fkexop?file=/src/index.tsx)

**Comment by SevereCloud** [comment]
- Duplicate of #2967
