### ISSUE TITLE
[Feature] Перенести анимацию на vkui-tokens

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#2997]
Необходимо заменить `--android-easing` и `--ios-easing` на `--vkui--animation_easing_default`. 

- [x] Обновить `--vkui--animation_easing_default` для IOS в vkui-tokens
- [x] Заменить `--android-easing` и `--ios-easing` на `--vkui--animation_easing_default`

**Comment by BlackySoul** [comment]
Длительность анимаций сделаем в рамках #3332
