### ISSUE TITLE
[v5] Обновить примеры codesandbox

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#2998]
Необходимо обновить все примеры на codesandbox для версии v5 и 18 реакт

- [x] Создать новую team `VKCOM`
- [x] Версия TypeScript [.codesandbox/ci.json](https://github.com/VKCOM/VKUI/blob/master/.codesandbox/ci.json)
- [x] Версия JavaScript [.github/ISSUE_TEMPLATE/bug_report.yml](https://github.com/VKCOM/VKUI/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml)

Хорошей идеей будет поставить зависимости на `latest`

**Comment by inomdzhon** [comment]
- closed this as [completed](https://github.com/VKCOM/VKUI/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in #3562

**Comment by inomdzhon** [comment]
>  Создать новую team `VKCOM`

это акк в **codesandbox**?
