### ISSUE TITLE
[Bug]: Компонент ChipSelect. Проблема со скролом выпадающего списка при использовании в мобильном приложении.

### ISSUE THREAD

**Issue by ghost** [VKCOM/VKUI#3028]
### Описание

Выпадающий список компонента ChipSelect не прокручивается при использовании в мобильном приложении. ОС Andriod (проверено в разных версиях ОС Andriod), версия vkui 4.35.3

### Версия

4.35.3

### В каких браузерах воспроизводится проблема?

Другое (укажите в описании)

**Comment by dimapsss** [comment]
Использую следующим образом: 

`import { ChipsSelect } from '@vkontakte/vkui/dist/unstable';`

`<FormItem top="Форматы">
                    <ChipsSelect
                      value={createOptions( formats )}
                      placeholder="Выберите форматы"
                      options={createOptions( search_store.formats )}
                      onChange={e => onChangeFormats(e)}
                      creatable={false}/></FormItem>`

Какая еще информация была бы полезна?

**Comment by dimapsss** [comment]
Данная проблема происходит при использовании внутри компонента модального окна.

**Comment by BlackySoul** [comment]
@dimapsss, привет! Подскажи, решит ли проблему добавление пропа `forceDropdownPortal=false`?

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
