### ISSUE TITLE
Закрывается клавиатура в input

### ISSUE THREAD

**Issue by AndreiKomarovRu** [VKCOM/VKUI#3082]
С версии 4.35.0+ во всех компонентах с присутствуем input при фокусе клавиатура открывается и тут же закрывается.

**Comment by SevereCloud** [comment]
Привет, нужен пример с воспроизведением на [codesandbox](https://vk.cc/cg9NLV)

https://user-images.githubusercontent.com/14944123/187364656-e0fe3b7a-ec66-4fa9-b75e-00f6869e5046.mov

**Comment by SevereCloud** [comment]
Воспроизвел https://codesandbox.io/s/input-test-nn1k29?file=/src/index.js

Проблема в modal и popout в компоненте View. Сейчас можно просто перенести modal и popout в SplitLayout
