### ISSUE TITLE
[Bug]: onSubmit в FormLayout вызывает перезагрузку страницы

### ISSUE THREAD

**Issue by reyzitwo** [VKCOM/VKUI#3105]
### Описание

При прокидывании **onSubmit** в компоненте теряется **e.preventDefault()**, которое спасает от перезагрузки страницы
![image](https://user-images.githubusercontent.com/73870113/187505156-28c388a2-9bff-4dfd-bf9f-074b422eef35.png)

### Версия

4.36.0

**Comment by SevereCloud** [comment]
> По-умолчанию в onSubmit происходит e.preventDefault(), чтобы избежать перезагрузки страницы

https://vkcom.github.io/VKUI/#/FormLayout

Если прокинуть `onSubmit`, то вы должны сами, при необходимости, вызвать e.preventDefault(). Это ожидаемое поведение описанное в документации
