### ISSUE TITLE
[Feature]: Header доработка After части компонента

### ISSUE THREAD

**Issue by Zaycevq** [VKCOM/VKUI#3132]
### Описание

Требуется добавить свойство для After правой части Hedaer, которое умеет отображать Button или IconButton, не ломая отступы вокруг себя. Это требуется для различных вариантов Header, с контролами  

Сейчас если подставить другой контент в After, его уносит с базовой линии:
![bad_after](https://user-images.githubusercontent.com/91548592/188167484-bfa37549-5eb6-4a93-94d1-686dac81391f.jpeg)

 Как хочется:
<img width="877" alt="good_after" src="https://user-images.githubusercontent.com/91548592/188167613-56fa5597-1765-4234-b3ef-3289967bd0ff.png">

 
Фигма:
 Android / Web — 
 https://www.figma.com/file/2sQl2eaxsp7RDRdMOeneEC/%F0%9F%92%A0-VKUI-Common-Library-%5BBeta%5D?node-id=23681%3A180833
 
   iOS — 
   https://www.figma.com/file/jvJUbY10EFMYTkbxNIIPqd/%F0%9F%92%A0-VKUI-iOS-Library-%5BBeta%5D-%C2%B7-In-Work-%F0%9F%9B%A0?node-id=23681%3A180833

**Comment by MimJS** [comment]
Хм

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.0" target="_blank">v5.9.0</a> 🎉
