### ISSUE TITLE
Определение платформы.

### ISSUE THREAD

**Issue by Aspedm** [VKCOM/VKUI#314]
Не определяется платформа "веб", с мобильного устройства.

**Как воспроизвести:**
- Зайти в сервис по урлу https://m.vk.com/app*
- Попробовать определить платформу через platform или IS_PLATFORM_IOS, IS_PLATFORM_ANDROID

**Ожидаемый результат:**
платформа не ios и не android

**Фактический результат:**
Для ios это ios

Почему это важно. Например метода vkConnect VKWebAppGetPersonalCard нет в вебе.

**Comment by fedorov-xyz** [comment]
Спасибо за ишью, посмотрим.

**Comment by slmatthew** [comment]
Доступность событий VK Connect можно проверить так:

```js
if (connect.supports("VKWebAppResizeWindow")) { 
    connect.send("VKWebAppResizeWindow", {"width": 800, "height": 1000}); 
}
```

**Comment by Aspedm** [comment]
> Доступность событий VK Connect можно проверить так:
> 
> ```js
> if (connect.supports("VKWebAppResizeWindow")) { 
>     connect.send("VKWebAppResizeWindow", {"width": 800, "height": 1000}); 
> }
> ```

Спасибо, за решение. Тоже нашел. Но issue актуальна.

**Comment by fedorov-xyz** [comment]
Мы поддерживаем сейчас всего две платформы: iOS и Android, определяются они по user-agent'у браузера. Веб и мвк мы не поддерживаем. Возможно, это изменится в будущем.
