### ISSUE TITLE
[Bug]: Пропала тень у Popover(Dropdown)

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#3168]
### Описание

Пропала тень у Dropdown

### Версия

v5

### Скриншоты

![image](https://user-images.githubusercontent.com/14944123/188578083-680dc2ad-cabf-4e26-ae11-2389ed5a6c7d.png)
![image](https://user-images.githubusercontent.com/14944123/188578180-93e91e57-6c21-4acd-a32b-fa655a79d003.png)

**Comment by inomdzhon** [comment]
На скриншотах это не `Popover`, а `Popper`. У `Popover` своя дока

<img width="320" alt="image" src="https://user-images.githubusercontent.com/5850354/188590735-f821cfbd-2ec9-4c1e-a7ce-2fb977277a90.png">

**Рис. 1** [Popover](https://vkcom.github.io/VKUI/pull/3135/#/Popover)

---

Тем не менее у меня не воспроизводится на стенде `v5`

<img width="320" alt="image" src="https://user-images.githubusercontent.com/5850354/188590218-26a03f98-707f-40aa-866a-68444ee6b80d.png">

**Рис. 2** [ButtonGroup](https://vkcom.github.io/VKUI/pull/3135/#/ButtonGroup)
