### ISSUE TITLE
[Bug][Header]: сломана типографика

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#3177]
### Описание

Cломана типографика

### Версия

v5

### Скриншоты

![image](https://user-images.githubusercontent.com/14944123/188587799-f2848161-c604-4439-9b13-4f00a25a404a.png)

↓ Старые токены

![image](https://user-images.githubusercontent.com/14944123/188587846-cd06cf81-556a-4ee8-87e1-617763029519.png)

**Comment by inomdzhon** [comment]
Проблема **TT commons**, который объявлен `--vkui--font_family_accent` – это объявление будет удалено в одной из версий **vkui-tokens**.
