### ISSUE TITLE
[Bug]: Размер Subtitle в Cell = Compact режим (vk.com / web) нужно изменить

### ISSUE THREAD

**Issue by Zaycevq** [VKCOM/VKUI#3206]
### Описание

Нужно изменить токен для Subtitle / Extra Subtitle в Cell, при проектировании уменьшили в Compact версии размер до 12px, оказалось это перебор, нужно оставить токен такой же как в Android / iOS версии vkui--font_footnote--font_size--regular,13px)

Макеты обновлены:
https://www.figma.com/file/jvJUbY10EFMYTkbxNIIPqd/%F0%9F%92%A0-VKUI-iOS-Library-%5BBeta%5D-%C2%B7-In-Work-%F0%9F%9B%A0?node-id=2134

<img width="435" alt="size_text_regular" src="https://user-images.githubusercontent.com/91548592/188899757-af0f7f9e-1476-4106-9c42-b386dcf1e9a4.png">
<img width="416" alt="size_text_compact" src="https://user-images.githubusercontent.com/91548592/188899764-e48848a2-2006-488b-905b-9e43aa8c3df9.png">
9%3A146400

### Версия

v4.37.0

**Comment by BlackySoul** [comment]
Исправлено в версии v5
