### ISSUE TITLE
[Bug]: В PanelHeaderContext панель открывается и сразу закрывается

### ISSUE THREAD

**Issue by BlackySoul** [VKCOM/VKUI#3209]
### Описание

https://user-images.githubusercontent.com/7431217/188909478-90f541f3-0468-4670-a50d-9e1566fa4424.mov

### Версия

v5

**Comment by stoope** [comment]
Баг начинается c `react >= 17.0.0`

**Comment by SevereCloud** [comment]
FYI: #1487
