### ISSUE TITLE
[Bug][View]: Ломается верстка панели в момент SwipeBack при открытой клавиатуре на iOS

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#3268]
### Описание

**Окружение**
IOS, Нативный vkclient, не браузер

### Версия

4.37.0

### В каких браузерах воспроизводится проблема?

Другое (укажите в описании)

### Шаги воспроизведения

**Предусловия**
- Имеется панель с длинным содержимым (имеется скролл), в конце которого есть поле ввода
- С панели можно вернуться на предыдущую с помощью VKUI IOS SwipeBack (history и onSwipeBack у View)

**Шаги**
1. Скролл панели в нижнем положении
2. Открыть нативную IOS клавиатуру кликом по полю ввода
3. Сделать жест IOS SwipeBack 

**ФР**
Ломается верстка
- Содержимое текущей панели уезжает вверх на высоту клавиатуры
- Образуется прозрачное содержимое текущей панели, за которым становится видна предыдущая

### Ожидаемое поведение

**ОР**
Верстка не ломается. IOS SwipeBack работает как без поднятой клавиатуры.

### Скриншоты

<img width="482" alt="image" src="https://user-images.githubusercontent.com/22776192/189880045-9f5fcb1a-c3be-4f5b-8689-2b0ca687b13d.png">

https://user-images.githubusercontent.com/22776192/190080520-ab931330-736d-42da-8ca8-b695fa4af978.mp4

**Comment by inomdzhon** [comment]
@shevchux фикс будет в ближайшем патче (`v4.37.1`)
