### ISSUE TITLE
[Feature]: Перевод компонентов на css-modules

### ISSUE THREAD

**Issue by BlackySoul** [VKCOM/VKUI#3276]
### Описание

- [x] ActionSheet
- [x] ActionSheetItem
- [x] Alert
- [x] AppRoot
- [x] Avatar
- [x] Badge
- [x] Banner
- [x] BaseGallery
- [x] Button
- [x] ButtonGroup
- [x] Calendar
- [x] CalendarDay
- [x] CalendarDays
- [x] CalendarHeader
- [x] CalendarRange
- [x] CalendarTime
- [x] Caption
- [x] Card
- [x] CardGrid
- [x] CardScroll
- [x] Cell
- [x] CellButton
- [x] CellCheckbox
- [x] CellDragger
- [x] Checkbox
- [x] Chip
- [x] ChipsInput
- [x] ChipsInputBase
- [x] ChipsSelect
- [x] ContentCard
- [x] Counter
- [x] CustomScrollView
- [x] CustomSelect
- [x] CustomSelectDropdown
- [x] CustomSelectOption
- [x] DateInput
- [x] DatePicker
- [x] DateRangeInput
- [x] DeviceConditionalRender
- [x] Div
- [x] Dropdown
- [x] Epic
- [x] FixedLayout
- [x] FocusVisible
- [x] Footer
- [x] Footnote
- [x] FormField
- [x] FormItem
- [x] FormLayout
- [x] FormLayoutGroup
- [x] FormStatus
- [x] Gradient
- [x] GridAvatar
- [x] Group
- [x] Header
- [x] Headline
- [x] HorizontalCell
- [x] HorizontalScroll
- [x] HorizontalScrollArrow
- [x] IconButton
- [x] Image
- [x] ImageBase
- [x] ImageBaseBadge
- [x] ImageBaseOverlay
- [x] InfoRow
- [x] InitialsAvatar
- [x] Input
- [x] InputLike
- [x] InputLikeDivider
- [x] Link
- [x] List
- [x] MiniInfoCell
- [x] ModalCard
- [x] ModalCardBase
- [x] ModalDismissButton
- [x] ModalPage
- [x] ModalPageHeader
- [x] ModalRoot
- [x] Pagination
- [x] Panel
- [x] PanelHeader
- [x] PanelHeaderBack
- [x] PanelHeaderButton
- [x] PanelHeaderContent
- [x] PanelHeaderContext
- [x] Paragraph
- [x] Placeholder
- [x] PopoutRoot
- [x] PopoutWrapper
- [x] Popover
- [x] Popper
- [x] PopperArrow
- [x] Progress
- [x] PromoBanner
- [x] PullToRefresh
- [x] Radio
- [x] RadioGroup
- [x] Removable
- [x] RichCell
- [x] RichTooltip
- [x] Root
- [x] ScreenSpinner
- [x] Search
- [x] SegmentedControl
- [x] SegmentedControlOption
- [x] Select
- [x] Separator
- [x] SimpleCell
- [x] SizeXConditionalRender
- [x] SizeYConditionalRender
- [x] SimpleCheckbox
- [x] Slider
- [x] SliderSwitch
- [x] Snackbar
- [x] Spacing
- [x] Spinner
- [x] SplitCol
- [x] SplitLayout
- [x] Subhead
- [x] SubnavigationBar
- [x] SubnavigationButton
- [x] Switch
- [x] Tabbar
- [x] TabbarItem
- [x] Tabs
- [x] TabsItem
- [x] Tappable
- [x] Text
- [x] TextTooltip
- [x] Textarea
- [x] Title
- [x] Tooltip
- [x] UsersStack
- [x] View
- [x] ViewIOS
- [x] ViewWidthConditionalRender
- [x] VisuallyHiddenInput
- [x] WriteBar
- [x] WriteBarIcon

---

- related to #2607

**Comment by inomdzhon** [comment]
- closed this as [completed](https://github.com/VKCOM/VKUI/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in #3289
