### ISSUE TITLE
Изменения для компонента HorizontalScroll на десктопе

### ISSUE THREAD

**Issue by drago-v** [VKCOM/VKUI#334]
Было бы неплохо немного изменить поведение компонента  HorizontalScroll на десктопах, а именно:
1. Сделать возможным скроллинг при прокрутке колесом мыши без нажатия кнопки Shift. Сейчас прокрутка с помощью комбинации Shift и колеса мышки очень неочевидна для большинства юзеров, многие думают, что прокрутка попросту не работает. В идеале прокрутка должна работать просто при наведении курсора на компонент и скроллинге, при этом вертикальный скролл самой страницы должен предотвращаться.
2. Также было бы неплохо сделать возможным перетаскивание вправо-влево с помощью курсора при зажатой ЛКМ. Хотя если будет работать обычная прокрутка, это не так критично.

**Comment by ArthurStam** [comment]
Привет. Мы [не поддерживаем](https://vk.com/dev/vk_apps_docs3?f=7.%2B%D0%9F%D0%BB%D0%B0%D1%82%D1%84%D0%BE%D1%80%D0%BC%D1%8B%2B%D1%81%2B%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D0%BE%D0%B9%2BVK%2BMini%2BApps) VKUI на десктопе.
![image](https://user-images.githubusercontent.com/5061840/63100407-b5998600-bf7f-11e9-90fa-59f0c60c55dd.png)
