### ISSUE TITLE
[Bug] В модалках не работают внутренние скроллы

### ISSUE THREAD

**Issue by fedorov-xyz** [VKCOM/VKUI#335]
Актуально для HorizontalScroll, Input и тач-событий.

**Comment by fax1ty** [comment]
Что со скроллом в модалках на данный момент? Вижу коммит который должен был это исправить. Но даже с использованием дополнительных свойств на данный момент (у меня) не работает HorizontalScroll внутри ModalPage.

**Comment by hoxtonhero** [comment]
> Что со скроллом в модалках на данный момент? Вижу коммит который должен был это исправить. Но даже с использованием дополнительных свойств на данный момент (у меня) не работает HorizontalScroll внутри ModalPage.

Есть какие-то новости?)

**Comment by ArthurStam** [comment]
Планируем исправить в ближайшие месяцы

**Comment by slevamatveev** [comment]
Есть какие новости по фиксу? HorizontalScroll до сих пор не работает (без мышки на мобильном устройстве, по крайней мере)

**Comment by SevereCloud** [comment]
Скорее всего будем переделывать модальные окна полностью 

- #2449

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
