### ISSUE TITLE
[Bug]: Белый Search:hover в темной теме vk.com

### ISSUE THREAD

**Issue by fab4u-4empion** [VKCOM/VKUI#3350]
### Описание

Белый цвет наведения у Search в теме vkcom_dark 

![Безымянный](https://user-images.githubusercontent.com/66959457/192635642-864cb467-2313-4a03-ba68-684c0ad416cc.png)

Проблема не наблюдается, если установить appearance у ConfigProvider в значение dark. 

### Версия

4.37.4

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

1) 
```jsx
<ConfigProvider platform={platform === VKCOM ? "android" : platform}>
```
2) Навести курсор на Search

### Ожидаемое поведение

Цвет будет соответствовать выбранной теме

**Comment by SevereCloud** [comment]
Won't fix -- в v5 мы откажемся от scheme, эта проблема будет не актуальна

Рекомендую передавать в ConfigProvider свойство `appearance`
