### ISSUE TITLE
[Bug]: PanelHeaderContext при рендере вызывает событие onClose на платформе VKCOM

### ISSUE THREAD

**Issue by flangapp** [VKCOM/VKUI#3363]
### Описание

На платформе VKCOM PanelHeaderContext сразу же после рендера вызывает событие onClose, на любых других platform ошибка не воспроизводится

### Версия

4.37.4

### Шаги воспроизведения

В целом все должно быть понятно в описании, просто вызовите рендер PanelHeaderContext

### Ожидаемое поведение

onClose должен вызываться только при закрытии, а не при рендере

### Пример с воспроизведением

https://codesandbox.io/s/default-example-forked-r8kmkw на широком экране

Закрытое ишью https://github.com/VKCOM/VKUI/issues/1487

**Comment by BlackySoul** [comment]
Привет! Спасибо за ищью, бага воспроизводится в приложениях с версией react >= 17.*
