### ISSUE TITLE
Можно сделать stopPropagation в Button настраиваемым

### ISSUE THREAD

**Issue by ciricc** [VKCOM/VKUI#337]
В некоторых случаях нужно, чтобы долгое нажатие на кнопку работало корректно. `Tappable` в `Button` настроен на жесткое отключение `propogation`

```javascript
<Button stopPropagation={false}>Help me</Button>
```

**Comment by ArthurStam** [comment]
Спасибо за реквест. Подумаем, почему мы решили прописать его жестко. Кажется, на то было причины.
