### ISSUE TITLE
[Bug]: Классы иконок должны быть обернуты в `:global`

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#3378]
### Описание

Классы иконок не должны изменятся. Классы иконок необходимо обернуть в `:global`

```diff
-.Cmp .Icon {
+.Cmp :global(.vkuiIcon) {
```

### Версия

v5

**Comment by inomdzhon** [comment]
- closed this as [completed](https://github.com/VKCOM/VKUI/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in #3289
