### ISSUE TITLE
В модальных окнах не хочет появлятся скролл при вводе с клавиатуры

### ISSUE THREAD

**Issue by ciricc** [VKCOM/VKUI#338]
![image](https://user-images.githubusercontent.com/20687373/62391465-8e998800-b56d-11e9-9e18-c4ffb22457fc.png)

Как я понял там должна появляться панелька сверху и вертикальный скролл. Но его нет. 

![localhost_10888_ (3)](https://user-images.githubusercontent.com/20687373/62391519-b688eb80-b56d-11e9-84f8-c56233e9ff00.png)

**Comment by ArthurStam** [comment]
@fedorov-xyz призываю тебя

**Comment by fedorov-xyz** [comment]
Посмотрю, спасибо за репорт.

**Comment by SevereCloud** [comment]
Задача решится в #2449

**Comment by inomdzhon** [comment]
К сожалению, это особенность работы мобильных браузеров.

Попытки решить проблему через **VisualViewports**, приводят к ещё большим проблемам **UX**.

- подробнее см. [**Решение** -> _Поля ввода_](https://github.com/VKCOM/VKUI/pull/6759#solves_text_inputs)
