### ISSUE TITLE
[Bug]: при изменении высоты ChipsSelect не меняется положение списка опций

### ISSUE THREAD

**Issue by alex-panin** [VKCOM/VKUI#3386]
### Описание

При селекте нескольких опций высота компонента может измениться, однако при этом позиция переданных в проп renderOption опций остаётся неизменной. из-за этого компоненты либо наползают друг на друга, либо между ними образуется разрыв.

### Версия

4.29.1

### Скриншоты

<img width="291" alt="image" src="https://user-images.githubusercontent.com/50754158/194059720-0128cf74-5d51-451a-81bb-d35a5eeb0c6d.png">
<img width="305" alt="image" src="https://user-images.githubusercontent.com/50754158/194060066-cb9f1a65-9eaf-45e1-af30-c5fc9817f83c.png">

### Пример с воспроизведением

https://codesandbox.io/s/quirky-edison-mj7scx?file=/src/index.js

**Comment by BlackySoul** [comment]
Привет! На последней актуальной версии (4.37.4) не воспроизводится, поэтому предложение обновиться 🙂

**Comment by alex-panin** [comment]
@BlackySoul спасибо! проглядел версию в песочнице
