### ISSUE TITLE
Предлагаю для андроидовских Tappable Waves сделать корректную анимацию

### ISSUE THREAD

**Issue by ciricc** [VKCOM/VKUI#339]
В качестве примера хорошей, на мой взгляд, анимации волн, предлагаю посмотреть этот пен
https://codepen.io/dongato/pen/pjpvwe

Подход прост: вы используете тот же scale, но ширину и высоту волны устанавливаете самостоятельно, исходя из размера родительского контейнера (this.container). Изинги и delays, соответственно тоже другие. Я пробовал делать сам это, но руки не дошли делать Pull Request.

Сейчас просто анимация волн очень резкая.

**Comment by ArthurStam** [comment]
Привет. А можешь всё-таки доделать PR?)

**Comment by ArthurStam** [comment]
#327 и вот это тоже можно всё в одном PR. Было бы круто
