### ISSUE TITLE
[Enhancement][a11y] Доступность для `SegmentedControl`

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#3392]
### Описание

- [ ] `SegmentedControl`
  - [ ] документация по доступности (https://github.com/VKCOM/VKUI/issues/3035)

---

## 🐛 Bugs

Комментарий от команды мини-приложения [VK Чекбек](https://vk.com/checkback).

> Столкнулись с тем, что во включенном **Talkback** на Android появляются доп. элементы, которые озвучиваются как `"отмечено"/"не отмечено"`, но нет выделения элемента на экране.
>
> Ссылка на баг в VK Testers с подробностями – https://vk.com/bug762353

**Comment by mendrew** [comment]
Проблема с фокусом в Android Takback исправлена в https://github.com/VKCOM/VKUI/pull/6365

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.1" target="_blank">v5.10.1</a> 🎉
