### ISSUE TITLE
Отсутствует placeholder в Select с версии v4.35.2

### ISSUE THREAD

**Issue by AndreiKomarovRu** [VKCOM/VKUI#3395]
С версии v4.35.2, Select при пустом value - автоматически присваивает в value первый элемент списка.

**Comment by BlackySoul** [comment]
Привет! Такое поведение было и до версии 4.35.2 при условии что мобильное устройство (`hasMouse = false`) и не указан `placeholder`.

P.S.: на будущее, желательно пользоваться шаблонами заведения issue

**Comment by AndreiKomarovRu** [comment]
Речь идет про десктоп. Перепроверено. В 4.35.1 проблемы нет, начиная с 4.35.2 и всех далее есть.

**Comment by BlackySoul** [comment]
Есть возможность предоставить работающий пример ([шаблон](https://codesandbox.io/s/vkui-boilerplate-oj149)) или исходный код? Сходу не удалось воспроизвести.

**Comment by BlackySoul** [comment]
В рамках данного [issue](https://github.com/VKCOM/VKUI/issues/2971) за пустое считается теперь `undefined` или `null`, а не любое falsy values. Возможно, в этом причина?

**Comment by AndreiKomarovRu** [comment]
Да, в этом и оказалась причина. Если иначе, то автоматически срабатывает onChange присвоив первый элемент
