### ISSUE TITLE
message: null is not an object (evaluating 'n.props.history.length')

### ISSUE THREAD

**Issue by metalfm** [VKCOM/VKUI#342]
В логах с завидной регулярностью попадаются ошибки 
message: null is not an object (evaluating 'n.props.history.length')
name: TypeError

Очень похоже что стреляет в vk-ui вот в этом месте
https://github.com/VKCOM/VKUI/blob/f0c07d1a78651e4db327c36c34eea57fbe549518/src/components/View/View.js#L322-L334

Если поможет, могу приложить трейс обфусцированного кода.

ua 
Mozilla/5.0 (iPhone; CPU iPhone OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16D57
Mozilla/5.0 (iPhone; CPU iPhone OS 12_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

К сожалению воспроизвести не получается.

**Comment by ArthurStam** [comment]
Вероятно, передаваемый вами history невалидный. Почитайте вот [тут](https://vkcom.github.io/vkui-styleguide/#!/View) секцию iOS swipe back.

**Comment by ArthurStam** [comment]
Закрываю тикет за отсутствием активности
