### ISSUE TITLE
[Feature]: Добавить в проект @vkontakte/prettier-config

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#3426]
### Описание

Необходимо подключить [@vkontakte/prettier-config](https://github.com/VKCOM/prettier-config)

**Comment by inomdzhon** [comment]
Давайте после мержа `v5`? Если в `v4`, то будет больно мержить `v4` в `v5`

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
