### ISSUE TITLE
[Doc]: В секции FormLayoutGroup поломалось отображение компонентов

### ISSUE THREAD

**Issue by mzingwrld** [VKCOM/VKUI#3436]
### Описание

Привет!

На странице https://vkcom.github.io/VKUI/#/FormLayoutGroup поехало отображение компонентов:

![image](https://user-images.githubusercontent.com/17254926/195358169-0ead20ae-dcec-4fee-8afe-ef6e4bc972c0.png)

Не критично, но вдруг)

**Comment by BlackySoul** [comment]
Привет! Спасибо за внимательность 🙂
