### ISSUE TITLE
[Bug]: Избавиться от `clip-path: path()` в UsersStack

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#3444]
### Описание

У `clip-path: path()` пока [плохая поддержка в браузерах](https://caniuse.com/mdn-css_properties_clip-path_path). Необходимо перенести маски из css в svg

### Версия

v4.38.0

### В каких браузерах воспроизводится проблема?

Firefox

### Скриншоты

![image](https://user-images.githubusercontent.com/14944123/195564109-90f846ee-4a56-4364-a2f2-a221ff550d82.png)

### Пример с воспроизведением

https://vkcom.github.io/VKUI/#/UsersStack

**Comment by inomdzhon** [comment]
Судя по **caniuse**, не только Firefox

<img width="320" alt="image" src="https://user-images.githubusercontent.com/5850354/195582536-ee7c0d08-e4ab-438a-ac49-4fafc95ac3db.png">

А у нас поддержка вот такая:

https://github.com/VKCOM/VKUI/blob/f46fbd77dd02d2f2782a4ab0c58edf7c4b32af73/.browserslistrc#L2-L3
