### ISSUE TITLE
[Bug]: Button with href + disabled

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#3446]
### Описание

Если выставить параметр disabled на кнопку которая имеет href, клик все равно будет происходить.

С одной стороны кейс довольный странный, кто будет дизейблить ссылку, с другой все же баг, решать вам.

Решение для этого прикола
![image](https://user-images.githubusercontent.com/26293210/196027053-df53e831-38b5-43c6-8d3a-0a8befa759dd.png)

### Версия

4.38.0

### В каких браузерах воспроизводится проблема?

Firefox, Chrome, Safari, Microsoft Edge, Yandex Browser

### Шаги воспроизведения

1. Параметр disabled
2. Параметр href
3. Кликаем на ссылку, происходит ее открытие

### Ожидаемое поведение

3. Открытие ссылки не происходит при параметре disabled

### Пример с воспроизведением

https://vkcom.github.io/VKUI/#/Button

**Comment by RusAnonym** [comment]
Думаю неправильной логикой вешать это на весь Tappable, от которого зависят также и другие контролы

Например, в Cell и SimpleCell такая логика неправильна, поскольку в доке сказано, что флаг disabled отключает анимацию нажатия, а не в принципе любое взаимодействие пользователя с компонентом
![image](https://user-images.githubusercontent.com/45464902/198985731-fa07e15e-2d58-41de-b742-61a695b63dbf.png)

**Comment by SevereCloud** [comment]
Закрою в пользу #3599 с большем описанием проблемы и ее решением
