### ISSUE TITLE
[Feature][View]: добавить возможность блокировки свайп бэка

### ISSUE THREAD

**Issue by a-byzova** [VKCOM/VKUI#3458]
### Описание

После внесения изменений (например в VKID в разделе личные данные) и свайпе назад, невозможно вывести предупреждение о несохраненных изменениях и заблокировать свайп
onSwipeBack и onStartSwipeBack отрабатывают с началом свайпа и для вывода alert не подходят

### Версия

5.0.0-beta.1

### В каких браузерах воспроизводится проблема?

Другое (укажите в описании)

### Шаги воспроизведения

VKID
Раздел "Личные данные"
Вносим любые изменения
Делаем свайп назад

### Ожидаемое поведение

Возможность передать состояние заблокированного свайпа и callback c выводом предупреждения

**Comment by inomdzhon** [comment]
@a-byzova в описание PR https://github.com/VKCOM/VKUI/pull/3468 добавил инфу как реализовал фичу

## Пример

На момент написания коммента, у нас песочница для PR лежит, поэтому создал пример в CodeSandbox, вот [ссылка](https://codesandbox.io/s/vkui-3468-view-prevent-swipe-back-cmrqq2?file=/example.tsx)

**Comment by inomdzhon** [comment]
@a-byzova проверила у себя в проекте, что фича покрывает потребность ✅

@VKCOM/vkui перевёл задачу в **In Review**.
