### ISSUE TITLE
[BREAKING CHANGE][Feature]: Сделать onClose обязательным для Alert

### ISSUE THREAD

**Issue by BlackySoul** [VKCOM/VKUI#3464]
### Описание

Добавить явную необходимость указывать `onClose` для компонента `Alert` (сделать поле обязательным)

**Comment by inomdzhon** [comment]
- closed this as [completed](https://github.com/VKCOM/VKUI/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in #3465
