### ISSUE TITLE
[Bug]: При закрытии второй панели, применяется скрол первой панели

### ISSUE THREAD

**Issue by AndreiKomarovRu** [VKCOM/VKUI#3500]
### Описание

Скролим первую панель, открываем вторую, закрываем вторую.
С версии v4.35.0 при закрытии второй панели, ему присваивается позиция скролла первой панели. (именно при анимации закрытия).
В версиях ранее такой проблемы нет.
Сохраняется до последней.

### Версия

4.35.0

### Шаги воспроизведения

Скролим первую панель, открываем вторую, закрываем вторую.

### Скриншоты

Видео, момент нажатия Назад.
Видно как вторая панель сразу применяет позицию скрола первой панели и начинается уходить.
https://disk.yandex.ru/i/DleyljltcRhQfw

**Comment by BlackySoul** [comment]
Привет! В новой версии `vkui v6`  воспроизвести не удалось. Есть возможность проверить на обновленной версии в приложении из видео?
