### ISSUE TITLE
[Bug]: Наполовину не видно indicator у SimpleCell

### ISSUE THREAD

**Issue by SelenZzz** [VKCOM/VKUI#3521]
### Описание

Если в SimpleCell поместить слишком длинное содержимое, индикатор будет частично скрыт  

### Версия

4.38.1

### Скриншоты

<img width="251" alt="Screenshot 2022-10-28 at 13 24 28" src="https://user-images.githubusercontent.com/58228495/198565600-a314d534-89d5-4de2-bc99-6a6b2a34f005.png">

### Пример с воспроизведением

https://codesandbox.io/s/focused-worker-vq7goc?file=/src/index.js

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.1" target="_blank">v6.0.1</a> 🎉
