### ISSUE TITLE
[Feature][Alert]: Разрешить передачу `target` на уровне типов

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#3536]
### Описание

Если для кнопки со ссылкой передать `target`, то получаем варнинг, хотя свойство передается кнопке.

### Скриншоты

<img width="271" alt="Снимок экрана 2022-11-01 в 00 36 11" src="https://user-images.githubusercontent.com/42776347/199114967-13b33169-94a8-4f12-ba30-c78aef30cd9a.png">

**Comment by SevereCloud** [comment]
Привет, будет доступно в v5.0.2
