### ISSUE TITLE
[Bug][Select]: Нет возможности очистить состояние извне

### ISSUE THREAD

**Issue by KusokBanana** [VKCOM/VKUI#3542]
### Описание

Собственно, сабж.
У компонентов Select невозможно программно вернуть состояние к изначальному, до выбора значения

**Comment by BlackySoul** [comment]
FYI: переделала на баг, потому что проставление `value=null` позволяло очистить поле до версии [v4.34.2](https://github.com/VKCOM/VKUI/releases/tag/v4.34.2) включительно
