### ISSUE TITLE
[Bug][a11y][Select]: Скринридер игнорирует `Select`

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#3547]
Не удается взаимодействовать со всеми компонентами, в которых есть кастомный `Select`:
- `CustomSelect`
- `Select`
- `SelectMimicry`

**Comment by SLVor** [comment]
Очень хочется эту фичу! По ней есть какие-то подвижки?

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.0" target="_blank">v5.10.0</a> 🎉
