### ISSUE TITLE
[Bug][DateInput] Скринридер при табе на DateInput фокусируется некорректно

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#3548]
Сейчас скринридер при табе внутрь DateInput фокусируется на вводе месяца вместо ввода дня.

**Comment by SevereCloud** [comment]
Не смог воспроизвести

<img width="526" alt="image" src="https://github.com/VKCOM/VKUI/assets/14944123/042d46c4-d36b-44eb-a23b-6c77430289b6">

**Comment by vkcom-publisher** [comment]
Задача закрыта из-за отсутствия активности в течение последних 14 дней. Если это произошло по ошибке или проблема все ещё актуальна, откройте задачу повторно.
