### ISSUE TITLE
[Enhancement] Оптимизировать скриншотные тесты

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#3560]
## Проблема

Некоторые скриншоты становятся слишком большими для гитхаба. Например, в https://github.com/VKCOM/VKUI/pull/3557:

![image](https://user-images.githubusercontent.com/22026957/199679776-60400c29-dc55-4652-a116-19bc5c6d977e.png)

![image](https://user-images.githubusercontent.com/22026957/199679992-4d98a906-6da6-45cf-b0da-29e1d679755b.png)

## Решение

Пройтись по скриншотным тестам и уменьшить количество кейсов в скриншотных тестах до реально необходимого.

**Comment by SevereCloud** [comment]
Скриншоты теперь не показываются на гитхабе, ишью не актуально
