### ISSUE TITLE
Добавить возможность отключать анимацию перехода к странице у View

### ISSUE THREAD

**Issue by promo4ka** [VKCOM/VKUI#358]
![na2G8qbQn6](https://user-images.githubusercontent.com/16706667/63463438-db35fc00-c465-11e9-9203-fe9f8d9b2514.gif)

Привет, добавьте если есть возможность отключать анимацию перехода как показано на гифке, допустив animated="false" и если указано значение числовое, можно использовать для время анимации.

**Comment by ArthurStam** [comment]
Привет, нет, это противоречит нашим гайдлайнам
