### ISSUE TITLE
[BREAKING CHANGE]: Изменить импорт нестабильных компонентов

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#3581]
### Проблема

Текущий подход к нестабильным компонентам вызывает некоторые проблем:

- при использовании cjs разработчики не понимают почему сборщик ругается на `export`
- необходимо отдельно генерировать типизацию для cjs
- импортирование из `dist/unstable` похоже на импортирование internal кода

### Решение

Необходимо использовать подход, который используется в React

> **API с приставкой unstable_.** Они добавляют экспериментальные возможности, в API которых мы не уверены до конца. Выпуская такие возможности с приставкой unstable_, мы можем их обновлять и переходить к стабильному API быстрее.

Подключение теперь будет выглядеть следующим образом

```diff
- import { ChipsSelect } from "@vkontakte/vkui/dist/unstable";
+ import { unstable_ChipsSelect as ChipsSelect } from "@vkontakte/vkui";
```

Также стоит избавиться от отдельного подключения нестабильного css

```diff
import "@vkontakte/vkui/dist/vkui.css";
- import "@vkontakte/vkui/dist/unstable.css";
```

**Comment by inomdzhon** [comment]
Мб апперкейсом `UNSTABLE_`? Как React делает с `UNSAFE_` для депрекейтит или нестабильных фич

**Comment by SevereCloud** [comment]
> Мб апперкейсом `UNSTABLE_`? Как React делает с `UNSAFE_` для депрекейтит или нестабильных фич

React для нестабильных фич [использует](https://reactjs.org/docs/faq-versioning.html#what-counts-as-a-breaking-change) `unstable_`

**Comment by inomdzhon** [comment]
> > Мб апперкейсом `UNSTABLE_`? Как React делает с `UNSAFE_` для депрекейтит или нестабильных фич
> 
> React для нестабильных фич [использует](https://reactjs.org/docs/faq-versioning.html#what-counts-as-a-breaking-change) `unstable_`

А, лол) Не перепроверил себя прежде чем писать, сорре
