### ISSUE TITLE
[Feature][Modal]: Запрет закрытия модального окна

### ISSUE THREAD

**Issue by KusokBanana** [VKCOM/VKUI#3592]
### Описание

Не хватает возможности запретить закрывать модалку при выполнении определённых действий.
Было бы здорово не давать закрыть при передаче определённых параметров.
Сейчас удалось придумать как предотвратить закрытие только наложив поверх экрана ещё один слой, но тогда пользователь вообще ничего сделать не сможет :(

**Comment by inomdzhon** [comment]
Спасибо за issue 🙏 

Закрыл в пользу #3628, т.к. там идёт уже обсуждение.

---

Duplicate of https://github.com/VKCOM/VKUI/issues/3628
