### ISSUE TITLE
[Bug][HorizontalCell]: Выделение накладывается на контент ячейки

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#3597]
### Описание

При наведении ячейки ее выделение накладывается сверху контента, а не снизу. Искажаются цвета изображения.

### Версия

4.39.0

### В каких браузерах воспроизводится проблема?

Chrome

### Ожидаемое поведение

Выделение накладывается фоном под контент.

### Скриншоты

<img width="415" alt="Снимок экрана 2022-11-09 в 16 03 06" src="https://user-images.githubusercontent.com/42776347/200837512-4ba3b519-63e4-48a5-b81e-3a42ebe45b43.png">
<img width="405" alt="Снимок экрана 2022-11-09 в 16 03 51" src="https://user-images.githubusercontent.com/42776347/200837670-bd332760-9aad-496d-a2b8-0361fb41e5f3.png">

### Пример с воспроизведением

https://vkcom.github.io/VKUI/#/HorizontalCell

**Comment by SevereCloud** [comment]
Привет, фикс будет в v5.0.1
