### ISSUE TITLE
[BREAKING CHANGE]: Отключение анимации наведения 

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#3599]
### Отключение анимации наведения

Многие для отключения анимации наведения передают `disabled` (так было в примерах и сам параметр так описан)

Но на деле это была плохая идея, поскольку ломает семантику

```html
<SimpleCell
  disabled
  after={
    <Button>Эта кнопка не доступна для скринридера</Button>
  }
>
  Статичный текст
</SimpleCell>
```

### Cell `mode="removable"` или `draggable` использует `disabled` для отключения анимаций

Cell `mode="removable"` или `draggable` использует `disabled` для отключения анимаций, что неверно для доступности

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/14944123/200852844-95b64dfd-f657-4ad1-b3b2-51aad82bfc15.png">

## Предложения

Если в компонент ячейки не передан `onClick` или `href`, то анимация отсутствует. Свойство disabled полностью отключает события нажатий внутри(смотри #3447)

**Comment by SevereCloud** [comment]
Не забыть поправить role при отсутствии `onClick`

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
