### ISSUE TITLE
[Bug]: Некорректный выбор значения у CustomSelect

### ISSUE THREAD

**Issue by lexstile** [VKCOM/VKUI#3600]
### Описание

При клике на option выбирается некорректное значение.

### Версия

4.39.0

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

0. предварительно обновить страницу
1. Фокусируемся на поле ввода
2. Вводим "Кат"
3. Выбираем "Категория 2"
Результат - выбирается "Категория 3"

### Пример с воспроизведением

https://codesandbox.io/embed/vkui-hello-world-forked-wedn89?fontsize=14&hidenavigation=1&theme=dark

**Comment by lexstile** [comment]
Добрый день, есть ли какие-то подвижки в данном направлении?

**Comment by inomdzhon** [comment]
> Добрый день, есть ли какие-то подвижки в данном направлении?

Привет!

Извини за задержку с ответом и спасибо за issue)

Нашёл где бажит, прикрепил PR с исправлением.

Единственное, фикс можно будет получить обновившись до **VKUI v5** (https://vkcom.github.io/VKUI/5.0.1/#/Migration).
