### ISSUE TITLE
[Bug]: 4.39.0. Cell draggable неактивен. Стоит аттрибут disabled

### ISSUE THREAD

**Issue by merexo** [VKCOM/VKUI#3605]
### Описание

И в приложении с версией 4.39.0, и в документации https://vkcom.github.io/VKUI/#/Cell. Не активны mouse events для элемента с draggable.

### Версия

4.39.0

### В каких браузерах воспроизводится проблема?

Firefox, Chrome, Safari, Microsoft Edge, Yandex Browser

### Скриншоты

![изображение](https://user-images.githubusercontent.com/26488688/201155590-57f42ad9-fee8-4767-bdbf-88ae68a6769a.png)

**Comment by SevereCloud** [comment]
Duplicate of #3550

Привет, исправление в мастере, будет доступно в версии 4.39.1

См. также #3599
