### ISSUE TITLE
[Bug]: iOS SwipeBack при эластичном скролле панели работает некорректно

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#3616]
### Описание

Platfrom: iOS

Если не дожидаться окончания завершения анимации эластичного скролла и сделать попытку iOS SwipeBack, то получаются некорректные отступы у панели. Проблема есть как с эластиком к нижней границе экрана, так и к верхней.

См. видео.

Решения:
1. Дешевое и хорошее: учесть случай отрицательного скролла (эластик вверх) и случай, когда scrollTop больше полученного, просто обрамить запоминаемое значение скролла в Min(Max(value))
2. Дешевое и как нативный ВК: не разрешать свайпбек, пока анимация эластик скролла не успокоится
3. Сложное и крутое: не делать резкий overflow: hidden в процессе свайп-бека, дать анимации эластик скролла завершиться, не мешать параллельной работе свайп-бека, превентить вертикальные touchmove
4. Среднее и крутое: когда скролл блокируется вместе с overflow: hidden в неправильной позиции, доводить эластик скролл до стандартного состояния программным образом (requestAnimationFrame + srollTop assign), не мешать параллельной работе свайп-бека

### Версия

4.39.0

### В каких браузерах воспроизводится проблема?

Другое (укажите в описании)

### Скриншоты

https://user-images.githubusercontent.com/22776192/201864299-155b5886-8b90-44ae-bf9f-6dd9333c64d9.MOV

https://user-images.githubusercontent.com/22776192/201864376-dc425257-8f83-4625-965a-2b8b22e12bd0.MOV

**Comment by inomdzhon** [comment]
Спасибо за подробное описание проблемы и список вариантов с решениями 🙏 

---

Текущая проблема никак не портит пользовательский опыт, поэтому нет причин увеличивать и усложнять кодовую базу проекта.

Если говорить про "красоту", то она имеет обратную сторону – ресурсы устройства не безграничны, 
с каждым лишним скриптингом будет требоваться всё больше мощностей, а это может бить по FPS и по заряду устройства.

Прокомментирую решение

> 2. Дешевое и как нативный ВК: не разрешать свайпбек, пока анимация эластик скролла не успокоится

Во-первых, это как раз бьёт по пользовательскому опыту. Приоритет надо отдавать в первую очередь отзывчивости интерфейса. Пользователь будет пытаться сделать свайпек и будет удивлён, что этого не произошло. И он не скоро поймёт, что это из-за того, что он "как-то не так проскролил и мы его за это наказываем".

Во-вторых, приложение ВКонтакте это обособленный бизнес-продукт, а VKUI это Open Source библиотека. Решения ВКонтакте не распространяются на VKUI.
