### ISSUE TITLE
[Bug]: HorizontalScroll не работают некоторые свойства

### ISSUE THREAD

**Issue by MrPikokon-creator** [VKCOM/VKUI#3624]
### Описание

Не работает getScrollToLeft, getScrollToRight и scrollAnimationDuration. Не знаю почему, на сайте всё работает, в моём коде нет. Хочу сделать прокрутку дальше, чем по умолчанию.

### Версия

4.39.0

### В каких браузерах воспроизводится проблема?

Firefox

### Шаги воспроизведения

`<HorizontalScroll showArrows getScrollToLeft={(i) => i - 1000} getScrollToRight={(i) => i + 1000}>`
Не работает

**Comment by SevereCloud** [comment]
К сожалению, мы тоже не знаем почему в вашем коде не работает. Сделайте форк отсюда https://codesandbox.io/s/vkui-boilerplate-oj149 и пришлите ссылку с воспроизведением проблемы

**Comment by MrPikokon-creator** [comment]
https://codesandbox.io/s/romantic-forest-9jxh9h?file=/src/index.js
В примере https://vkcom.github.io/VKUI/#/HorizontalScroll всё работает, в форке нет(

**Comment by MrPikokon-creator** [comment]
Аааа. Я использую SubnavigationBar внутри, у которого тоже есть это свойство 🤦‍♂️.
