### ISSUE TITLE
[Feature]: Добавить возможность отключать сворачивание ModalCard и ModalPage жестом вниз

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#3628]
### Описание

Если в ModalCard и ModalPage есть поле ввода и клавиатура открыта, сталкиваемся с конфликтами работы свайпа вниз, который закрывает модалку, и скролла. Особенно на iOS, где вьюпорт не сжимается при открытии клавиатуры. Так же есть конфликты, когда на iOS работаешь с кареткой выделения текста – можно случайно свернуть модалку.

Предлагается решить вопрос шире, не только с поднятой клавиатурой. Предоставить разработчикам data- аттрибут для оборачивания области, которая будет безопасной и не позволять сворачивать модалку. Такой подход похож на data- аттрибут, который запрещает работу iOS Swipe Back.

**Comment by pfrankov** [comment]
Было бы правильно не добавлять data-атрибут, а не закрывать модалку, когда идёт взаимодействие с инпутами.

**Comment by shevchux** [comment]
> Было бы правильно не добавлять data-атрибут, а не закрывать модалку, когда идёт взаимодействие с инпутами.

Не всегда дело может быть в модалке. Это может быть HorizontalScroll, или еще чего более кастомное (вертикальный скролл-барабан выбора года). Просится гибкое решение.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
