### ISSUE TITLE
[Bug]: Полоса между стрелкой и бабблом в tooltip Android

### ISSUE THREAD

**Issue by piretskiy** [VKCOM/VKUI#3639]
### Описание

У компонента tooltip в android может быть видна полоса между прямоугольником и стрелкой. Например, в песочнице появляется при масштабировании. Воспроизводится в MacOS Chrome, Android клиенте VK.

### Версия

4.39.0

### В каких браузерах воспроизводится проблема?

Chrome, Другое (укажите в описании)

### Шаги воспроизведения

1. Открыть пример использования тултипа из документации https://vkcom.github.io/VKUI/#/Tooltip
2. Масштабировать страницу (в Android артефакт может быть заметен без масштабирования)

### Ожидаемое поведение

Тултип отображается без полосы между стрелкой и прямоугольником

### Скриншоты

![Screenshot_20221122-110550](https://user-images.githubusercontent.com/118801769/203259176-9b92dcba-139a-4339-8e74-9674550920dd.png)

**Comment by BlackySoul** [comment]
- duplicate #2123
