### ISSUE TITLE
[Feature]: Добавить Accent Invariable-кнопку

### ISSUE THREAD

**Issue by 8coon** [VKCOM/VKUI#3646]
### Описание

Из-за различий в дизайн-системах Paradigm и VKUI, для того, чтобы мигрировать на VKUI в проектах на Paradigm, необходимо поддержать новый вид кнопки.

Вид хочется включать по пропу `appearance="accent_invariable"`.

Нужные для вида токены указаны на скриншоте (спасибо @Fliqle)

### Скриншоты

![image](https://user-images.githubusercontent.com/12988120/203609689-24679459-287a-4ca8-bc41-b1e1b6014f5b.png)

**Comment by SevereCloud** [comment]
Привет, будет в v5
