### ISSUE TITLE
[Bug]: ModalPage: не сбрасывается сотояние при закрытии модалки

### ISSUE THREAD

**Issue by ermolaevalexey** [VKCOM/VKUI#3683]
### Описание

При повторном открытии модалка раскрывается на полную высоту, а не значение пропа settlingHeight.

### Версия

4.38.1

### Ожидаемое поведение

При закрытии и повторном открытии модальной страницы, она должна заново приниматься установленное значение settlingHeight

### Пример с воспроизведением

https://codesandbox.io/s/happy-leavitt-70l52g?file=/src/index.js&resolutionWidth=252&resolutionHeight=715

**Comment by SevereCloud** [comment]
5.5.1 Все еще воспроизводится
