### ISSUE TITLE
[Tests] Хранить скриншоты в S3

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#3712]
Необходимо хранить скриншоты в S3, вместо lfs

**Comment by inomdzhon** [comment]
Решили пока остаться на `lfs`, т.к. переписывание на хранение скриншотов в S3 больше похоже на написание велосипеда.

---

Также была идея запускать скриншотные тесты под `master` только в e2e экшене, чтобы локально не хранить ссылки на актуальные скриншоты для сравнения с целевой веткой. В S3 хранились бы актуальные скриншоты под `master`, чтобы не собирать под каждый PR по новому, инвалидировать S3 по последнему хэшу коммита в `master`.

Но есть две проблемы, которые надо решать:

1. Как следить за актуальностью `master` в каждом PR?
    > Идеи:
    > 1. либо перезапускать e2e при каждом PR после обновления `master` (звучит ресурсозатратно)
    > 2. либо включить настройку, которая не даёт смержить PR, пока не подтянешь себе актуальный `master`
3. Как тестировать e2e локально?

**Comment by polRk** [comment]
> Как тестировать e2e локально?

Папку со скриншотами в gitignore и скрипт для синхронизации s3 и локальной папки. Теперь это папка будет в роли эталонных скриншотов (expected)

**Comment by polRk** [comment]
> Как следить за актуальностью master в каждом PR?
Rebase или в CI делать промежуточный merge и запускать проверки

**Comment by SevereCloud** [comment]
Мы пришли к выводу что S3 это велосипед, который необходимо еще и отдельно поддерживать. Для git lfs уже есть готовые инструменты как на гитхабе, так и в IDE

Вот примерный список того, чего бы нам пришлось писать и поддерживать:
- визуальное сравнение скриншотов с веткой
- проверка на конфликты с веткой
- требование ребейса на последний коммит ветки(выедает время)

Идея о переходе на s3 возникла из-за ограничений гитхаба на lfs, но смогли их победить с помощью кэширования скриншотов
