### ISSUE TITLE
ConfigProvider сбивает выравнивание PanelHeader

### ISSUE THREAD

**Issue by lightalex** [VKCOM/VKUI#372]
**Без использования ConfigProvider**:

![IMG_6124](https://user-images.githubusercontent.com/15173237/64076582-5a7dc800-cccf-11e9-8c95-718adb8167ec.PNG)

**С использованием ConfigProvider** в качестве обертки View:

![IMG_6125](https://user-images.githubusercontent.com/15173237/64076584-65d0f380-cccf-11e9-903c-af43ce00f2a2.PNG)

Видно, что на втором скриншоте, заголовок заходит за элементы управления самого WebView. В то время когда на первом скришоте данные элементы управления не выделяются и совместимы с заголовком.

Возможно конечно это не является багом. Но документации к компоненту ConfigProvider я не нашел. Только косвенное описание данного компонента в документации к компоненту View.

**Comment by ArthurStam** [comment]
Привет. Для корректного отображения шапки в VK Mini Apps нужно в `ConfigProvider` передать свойство `webviewType="vkapps"`. Доки действительно нет. Поправим это дело, спасибо.
