### ISSUE TITLE
Uncaught SyntaxError: Unexpected string в Hello World

### ISSUE THREAD

**Issue by Sirozha1337** [VKCOM/VKUI#373]
Здравствуйте!

Создал новый проект(npx create-react-app), установил VK UI (npm install @vkontakte/vkui), добавил необходимое правило в index.html(viewport-fit=cover) и скопировал код примера HelloWorld в App.js. 

При запуске(react-scripts start) приложение стартует, но отображается белый экран и в консоль выводится ошибка "Uncaught SyntaxError: Unexpected string" с указанием на строку: import './lib/polyfills';

При попытке сбилдить приложение (react-scripts build) выводится та же ошибка и приложение не билдится. 

Подскажите, пожалуйста, в чем может быть проблема.

**Comment by ArthurStam** [comment]
Привет. Без примера кода будет сложно понять, что пошло не так.

**Comment by ArthurStam** [comment]
Попробуйте версию `2.29.0`

**Comment by Sirozha1337** [comment]
Код скопированный из документации, секция "Hello World". Проблема была в настройках babel и webpack, которые создает задает "npx create-react-app".

Решил проблему, создав приложение с нуля(через npm init и добавление всех пакетов в ручную в package.json), видимо дефолтное приложение не добавляет какие-то нужные настройки для babel в следствие чего приложение не работает.
