### ISSUE TITLE
before Props in ActionSheetItem

### ISSUE THREAD

**Issue by antoxxxa-2** [VKCOM/VKUI#376]
Было бы удобно иметь такой пропс, чтобы добавлять иконки к элементам.
![image](https://user-images.githubusercontent.com/1327258/64264856-a6807500-cf3a-11e9-9382-6c74ffb1b456.png)

**Comment by fedorov-xyz** [comment]
Ещё стоит учитывать, что на Андроиде ActionSheet выглядит иначе, и иконки там не предусмотрены.

**Comment by ArthurStam** [comment]
В работе
