### ISSUE TITLE
[Bug]: Иконки 28 съезжают вниз

### ISSUE THREAD

**Issue by VitiaCatDragon** [VKCOM/VKUI#3772]
### Описание

В классе .Icon присутствуют лишние padding, из-за чего иконка съезжает вниз

### Версия

5.0.1

### В каких браузерах воспроизводится проблема?

Firefox

### Шаги воспроизведения

Иконка в PanelHeader before: <PanelHeaderBack/> <PanelHeaderClose/>, или другие 28 иконки

### Ожидаемое поведение

Убрать padding

### Скриншоты

![изображение](https://user-images.githubusercontent.com/60291267/206900078-d613cf77-79e1-4d98-bc09-6138edd273b9.png)

**Comment by VitiaCatDragon** [comment]
Обновил у себя @vkontakte/icons и иконка стала маленькой, убрав padding у иконки она становится нормальной.
![изображение](https://user-images.githubusercontent.com/60291267/206901826-096263b3-e135-4849-b8c2-a99f928bfa44.png)

**Comment by SevereCloud** [comment]
Все еще нужен пример воспроизведения. Также хорошо бы указать версию @vkontakte/icons

**Comment by VitiaCatDragon** [comment]
Убрал у всех элементов box-sizing и все стало нормально. tailwindcss ставит box-sizing, извините за дубликат.
