### ISSUE TITLE
[Bug]: Input. Некорректное расположение нативного инпута внутри компонента

### ISSUE THREAD

**Issue by OkciD** [VKCOM/VKUI#3786]
### Описание

При использовании компонента `Input` были найдены три проблемы:
1. При использовании `Input` для ввода пароля и настройке автокомплита
    ```tsx
    <Input type="password" autoComplete="current-password" />
    ```
    браузер (по крайней мере,  Chrome) подсвечивает нативный элемент `<input>`. Поскольку нативный инпут занимает не 100% высоты компонента `Input`, появляются белые поля сверху, снизу и в данном случае справа (из-за использования пропа `after`)
![image](https://user-images.githubusercontent.com/24460253/207248594-7f50ba4e-b25e-401b-a756-0ba46b2948bf.png)
2. В аналогичном сценарии так же подсвеченный браузером нативный инпут перекрывает border у компонента 
![image](https://user-images.githubusercontent.com/24460253/207248848-9be2e2aa-0b82-41ad-b1a3-800cba5389df.png)
(на скриншоте в инпут установлен фокус)
3. При наведении мышкой на компонент по-разному отображается курсор: https://cloud.mail.ru/public/gns6/NtmX2VkVD

Предположительно все три проблемы решаются одинаково: нужно растянуть нативный инпут на размер всего компонента

### Версия

5.0.0-beta.3

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

1. Иметь в вёрстке своего приложения
    ```tsx
    <Input type="password" autoComplete="current-password" />
    ```
2. В менеджере паролей Chrome (chrome://settings/passwords) иметь сохранённый логин и пароль на адрес вашего приложения
3. Установить фокус в этот инпут (возможно, браузер не подставит пароль сразу сам, тогда нужно будет сначала выбрать его в браузерном тултипе)
![image](https://user-images.githubusercontent.com/24460253/207251137-73230a9b-d94f-48ff-92a5-40503e8da881.png)

### Ожидаемое поведение

1. Инпут будет подсвечен браузером равномерно "по всей площади"
2. Бордер не будет перекрыт
3. `cursor: text` будет установлен на всём компоненте

### Пример с воспроизведением

https://codesandbox.io/s/vkui-input-issue-08ltbl

Чтобы воспроизвести, нужно добавить в менеджер паролей Chrome любую запись по адресу `iframe`а

![image](https://user-images.githubusercontent.com/24460253/207251941-9feadcb2-2f0f-480b-bf3a-c8ae89be4f75.png)

![image](https://user-images.githubusercontent.com/24460253/207252118-afb7be2c-aef0-4854-96b7-8940dd220d6e.png)

**Comment by zelflod** [comment]
В Safari та же проблема + сами саджесты перекрывают инпут 
<img width="566" alt="image" src="https://user-images.githubusercontent.com/25909486/209110437-5d0183a2-2bd8-4446-8280-7e9182f89fc6.png">

<img width="559" alt="image" src="https://user-images.githubusercontent.com/25909486/209111001-a7698037-21b8-4b51-9f68-f2b01ff22360.png">

**Comment by SevereCloud** [comment]
Привет, фикс будет доступен в v5.1.0
