### ISSUE TITLE
[Doc]: Неподходящий цвет ::selection в блоках кода документации

### ISSUE THREAD

**Issue by aleksanderlamkov** [VKCOM/VKUI#3791]
### Описание

В блоках кода документации (прим.: https://vkcom.github.io/VKUI/#/Tabs) при браузерном поиске найденный текст в блоках кода выделяется ярко-желтым, на белом фоне блока кода текст буквально не виден: https://tppr.me/uFCNu. 

Предлагаю скорректировать цвет текста через селектор '::selection' для блоков кода.

**Comment by BlackySoul** [comment]
Создано issue на [react-simple-code-editor](https://github.com/react-simple-code-editor/react-simple-code-editor/issues/109)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.1" target="_blank">v6.0.1</a> 🎉
