### ISSUE TITLE
Отсутствует атрибут onClick на компоненте Button

### ISSUE THREAD

**Issue by mvshmakov** [VKCOM/VKUI#382]
`Type '{ children: string; level: "primary"; size: "m"; stretched: true; onClick: Function; }' is not assignable to type 'IntrinsicAttributes & ButtonProps & { children?: ReactNode; }'.
  Property 'onClick' does not exist on type 'IntrinsicAttributes & ButtonProps & { children?: ReactNode; }'.`

![image](https://user-images.githubusercontent.com/28868855/64566752-50a73500-d35f-11e9-9f6b-6c4862358488.png)

[Здесь](https://github.com/VKCOM/VKUI/blob/dddcf612d2660d1168eb309638ca9be8ada91baf/src/components/Button/Button.tsx#L9) нужно добавить HasOnClick, который должен содержать в себе `onClick: Function`.
Сделал бы пулреквест, но прав нет.

**Comment by ArthurStam** [comment]
Спасибо за репорт, поправим
