### ISSUE TITLE
[Bug]: Компонент `Button` некорректно работает числами в качестве дочерних элементов

### ISSUE THREAD

**Issue by ekabolotina** [VKCOM/VKUI#3825]
### Описание

Если в пропсы `before` / `after` / `children` передать число `0`, то верстка кнопки сломается. А именно: внутри кнопки отрисуются просто нули без оберток.

Связно с тем, что проверки на наличие пропсов `before` / `after` / `children` реализованы некорректно. 

### Версия

4.40.0

### В каких браузерах воспроизводится проблема?

Другое (укажите в описании)

### Шаги воспроизведения

- Импортировать компонент `Button`
- Отрисовать кнопку №1 с пропсами: `before={0}`, `after={0}`, `children={0}`.
- Отрисовать кнопку №2 с пропсами: `before="0"`, `after="0"`, `children="0"`.

Результат: кнопки отрендерелись по-разному.

### Ожидаемое поведение

Кнопка отрисовывается одинаково независимо от того, строка или число передаётся в пропсы `before` / `after` / `children`.

### Скриншоты

<img width="293" alt="image" src="https://user-images.githubusercontent.com/8043216/208078051-acbc0ba6-5b54-43e9-8bae-e380e66a2afd.png">

### Пример с воспроизведением

https://codesandbox.io/s/snowy-dew-0n5ycw?file=/src/App.tsx

**Comment by inomdzhon** [comment]
- blocked by #3949
