### ISSUE TITLE
[Bug]: Лишний отступ у тени ActionSheet (platform=ios)

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#3866]
### Описание

Лишний отступ у тени ActionSheet (platform=ios)

[https://vkcom.github.io/VKUI/#/ActionSheet](https://vk.com/away.php?utf=1&to=https%3A%2F%2Fvkcom.github.io%2FVKUI%2F%23%2FActionSheet)

![image](https://user-images.githubusercontent.com/22776192/208873153-514ba46f-b414-4a71-b366-d45265134e11.png)

### Версия

5.0.2

**Comment by mendrew** [comment]
Всё ещё актуально и про это спрашивают. Добавил в ближайший milestone.
