### ISSUE TITLE
[Feature]: Добавить default placement для `Popper`

### ISSUE THREAD

**Issue by ekabolotina** [VKCOM/VKUI#3900]
### Описание

У компонента `Popper` есть пропс `placement`, который управляет положением выпадающего блока. Сейчас он работает так: если пропс `placement` не задан, то выпадающий блок располагается снизу слева. При этом если блок не помещается на экран в этом положении, то он смещается таким образом, чтобы контент выпадающего блока был виден целиком. Если же передать значение в пропс `placement`, то автоматическое подстраивание перестает работать. 

Хотелось бы чтобы при переданном значении в пропс `placement` автоматическое подстаривание продолжало работать. Либо добавить новый пропс `defaultPlacent`, который будет задавать предпочтительное расположение выпадающего блока.

**Comment by BlackySoul** [comment]
Привет! А есть минимальный пример с воспроизведением? Сейчас `placement` - это по сути "желаемое" дефолтовое местоположение, но оно может измениться, если места хватать не будет

**Comment by ekabolotina** [comment]
> Привет! А есть минимальный пример с воспроизведением? Сейчас `placement` - это по сути "желаемое" дефолтовое местоположение, но оно может измениться, если места хватать не будет

Привет! Вот пример — https://codesandbox.io/s/nostalgic-franklin-eu2l0l?file=/src/App.tsx

«Пример 1»: пропс `placement` не задан, поэтому положение выпадающего блока выбирается автоматически таким образом, чтобы блок был виден целиком.

«Пример 2»: пропс `placement` имеет значение `bottom`. Автоматическое позиционирование не работает, часть блока скрыта за пределами видимой области.

**Comment by inomdzhon** [comment]
Кажется до этого PR https://github.com/VKCOM/VKUI/pull/2733 всё работало так как надо.

Попробую вернуть в рамках задачи https://github.com/VKCOM/VKUI/issues/3030.
