### ISSUE TITLE
[Bug] На размонтированной кнопке вызывается setState

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#3901]
Варнинг генерируется preact при переключении между панелями

> Can't call "this.setState" on an unmounted component. This is a no-op, but it indicates a memory leak in your application.

https://github.com/VKCOM/VKUI/blob/f0d32233291b95e415e56a3e2e906a20d4c62e73/src/hooks/useFocusVisible.ts#L16-L22

**Comment by levtsypanov** [comment]
Может надо добавить условие, проверяющее находится ли элемент в DOM-дереве, перед тем как вызывать функцию setState.

```ts
const onBlur = useCallback(
  (event: FocusEvent) => {
    event.stopPropagation();
    if (ref.current) { // добавлено условие проверки на существование элемента в DOM-дереве
      setIsFocused(false);
    }
  },
  [setIsFocused, ref]
);
```

**Comment by BlackySoul** [comment]
Данный варнинг удален в [react](https://github.com/reactwg/react-18/discussions/82) и [preact](https://github.com/preactjs/preact/pull/3576)
