### ISSUE TITLE
[Feature]: События CustomScrollView

### ISSUE THREAD

**Issue by NicoBurno** [VKCOM/VKUI#3963]
### Описание

Сейчас у CustomScrollView нет возможности навесить события на скролящийся контейнтер: onScroll, onWheel и другие
Также нет возможности навесить события на ползунок скроллбара: старт перемещения, само перемещение и конец перемещения

Такой функционал необходим, как вариант, когда нужно определить тип скролла: программный или пользовательский

**Comment by inomdzhon** [comment]
Решено в #7699 – теперь можно прокидывать события onScroll, onWheel и другие
