### ISSUE TITLE
Некорректные тайпинги для ActionSheet

### ISSUE THREAD

**Issue by mvshmakov** [VKCOM/VKUI#400]
`No overload matches this call.
  Overload 1 of 2, '(props: Readonly<ActionSheetProps>): ActionSheet', gave the following error.
    Property 'insets' is missing in type '{ children: Element[]; onClose: () => void; }' but required in type 'Readonly<ActionSheetProps>'.
  Overload 2 of 2, '(props: ActionSheetProps, context?: any): ActionSheet', gave the following error.
    Property 'insets' is missing in type '{ children: Element[]; onClose: () => void; }' but required in type 'Readonly<ActionSheetProps>'.`

Почему-то [insets](https://github.com/VKCOM/VKUI/blob/650f71ec1b380aed20cfa1424c588a68af3d4639/src/components/ActionSheet/ActionSheet.tsx#L29) стали обязательными.

**Comment by ArthurStam** [comment]
Спасибо, сейчас поправим

**Comment by ArthurStam** [comment]
Должно быть пофикшено с `2.30.6`
