### ISSUE TITLE
[Enhancement][a11y] Улучшить доступность `FormLayout` 

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#4004]
**История задачи:**

Сначала мы хотели добавить доступность скрытой кнопке сабмита внутри `FormLayout` (см. #4005).

Потом пришли к выводу, что скрытой кнопки не должно быть вообще — в форме всегда должна быть какая-то очевидная и доступная всем кнопка с `type="submit"`. В итоге решили, что лучше всего будет сделать новый компонент, а старый задепрекейтить.

**Comment by inomdzhon** [comment]
Прикладываю коммент из PR сюда https://github.com/VKCOM/VKUI/pull/4576#discussion_r1162520306

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
