### ISSUE TITLE
Добавить в Snackbar таймер или перекрывание.

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#401]
У меня Snackbar открывается при нажатии на кнопку "Добавить в избранное", потом она становится "Удалить из избранного" и если это произошло в течении 5 секунд - остается гореть самый первый Snackbar. Хотелось бы видеть перекрывание или возможность таймера.

**Comment by fedorov-xyz** [comment]
https://vkcom.github.io/vkui-styleguide/#!/Snackbar

> Не нужно показывать это уведомление, если в приложении каким-то другим образом видно, что действие совершено. Например, когда заменяется текст в кнопке, или в список на странице добавился элемент.

Кажется, что тут снекбар и не нужен.

**Comment by ilyapishchulin** [comment]
Он туда хорошо вписывается) 
Попробую сам подредактировать, спасибо!
