### ISSUE TITLE
Поиск реагирует при зажиме другого элемента.

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#403]
Заходим в панель с поиском.
Зажимаем любое место и тянем вверх.

ФР: Поиск активируется.

**Comment by ArthurStam** [comment]
Зашел. Зажал. Не активировался.

**Comment by ilyapishchulin** [comment]
А вверх свайпнули?

**Comment by ilyapishchulin** [comment]
![F41AD7D6-D40E-4438-A8DE-C9190C899F4E](https://user-images.githubusercontent.com/45998835/65346295-16eaef80-dbe5-11e9-832b-f1b9b991ae31.png)

**Comment by ilyapishchulin** [comment]
vk.com/books_app - зайди, зажмите TappTable и потяните вверх.

**Comment by ArthurStam** [comment]
@ilyapishchulin зашел, зажал, потянул – поиск не активируется. iOS 12.4.1, iPhone 8

**Comment by ArthurStam** [comment]
Закрываю за отсутствием активности

**Comment by ilyapishchulin** [comment]
Сори, держи https://vk.com/video338598380_456239103?api_access_key=e8c4d934df0c4fc1ea

**Comment by ilyapishchulin** [comment]
@ArthurStam

**Comment by ArthurStam** [comment]
Не помешала бы версия iOS и модель айфона

**Comment by ilyapishchulin** [comment]
Телефон: IPhone 6s Plus и IPhone XR.
Версия IOS: 13.1.3
Версия сборки: 17A878

**Comment by ArthurStam** [comment]
У меня всё равно не воспроизводится :(

**Comment by ilyapishchulin** [comment]
Прям зажимаешь элемент и тянешь вверх?

**Comment by ilyapishchulin** [comment]
Попробуй в vk.com/rezept_app зажать первый cell и зажатым потянуть вверх.

**Comment by ArthurStam** [comment]
@fedorov-xyz ваш выход

**Comment by ArthurStam** [comment]
У него тоже не получилось

**Comment by ilyapishchulin** [comment]
Щас свои козыри выпущу.

**Comment by ilyapishchulin** [comment]
У https://vk.com/dobermn получилось.

**Comment by ArthurStam** [comment]
Нам это вряд ли поможет)

**Comment by ilyapishchulin** [comment]
Нууу, остаётся записать вид сверху, чуть позже)

**Comment by ilyapishchulin** [comment]
В новой теме не воспроизводится.
