### ISSUE TITLE
[Bug][Button]: Лишний отступ при параметрах `before`/`after` и `stretched`

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#4049]
### Описание

При использование параметров `before`/`after` и `stretched` для `Button` у контейнеров `before`/`after` появляется отступ слева/справа, из-за чего переданный компонент сдвигается

### Версия

5.1.0

### Шаги воспроизведения

1. Использовать параметры `before` (или `after`) и `stretched`
2. Чтобы было нагляднее, ограничить контейнер

```jsx
<Div style={{ width: 70 }}>
  <Button before={<Icon24Add />} stretched />
</Div>
```

### Скриншоты

<img width="320" alt="image" src="https://user-images.githubusercontent.com/5850354/214817384-24da884b-02f0-494b-9ef2-0dc18e2b69e2.png">

_см. кнопку слева снизу_

### Пример с воспроизведением

https://vkcom.github.io/VKUI/5.1.0/#/ButtonGroup

---

- related to #3971

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.2" target="_blank">v5.9.2</a> 🎉
