### ISSUE TITLE
Не работает full screen при просмотре видео через iframe

### ISSUE THREAD

**Issue by WinZip17** [VKCOM/VKUI#407]
При просмотре видео с Android телефона через приложение ВК, которое добавлено через iframe невозможно развернуть видео на весь экран, приложение стопается (может вылетает). Само приложение ВК остается работать, а приложение ВК мини не реагирует не на что после нажатие на "развернуть"

**Comment by ArthurStam** [comment]
Привет. Я правильно понимаю, что у тебя есть какое-то VK Mini App приложение, внутри которого есть видео? Сниппет с кодом и скринкаст бы не помешали.

**Comment by WinZip17** [comment]
В коде выглядит при записи видео так:
```
<Div>
<iframe src="https://blog3425.ru/2345.html" width="350" height="250" frameBorder="0"
allowFullScreen></iframe>
</Div>
```

Пробовал другие плееры, результат такой же. При нажатии на развернуть экран содержимое "подвисает", хотя само приложение продолжает работать. По менюшке приложения я клацнул поссле попытки разворота видео

Ссылка на видео:
https://vk.com/video15267742_456239096

**Comment by WinZip17** [comment]
Но это баг, а не нужна помощь. НА IOS работает нормально, на компе тоже. Баг только на android

**Comment by ArthurStam** [comment]
Выглядит не как трабла библиотеки.

**Comment by WinZip17** [comment]
Без использования библиотеки та же проблема... Судя по всему это проблема приложения Вконтакте. Ткните плз носом куда написать, что б дошло адресату

**Comment by danakt** [comment]
Данную проблему в приложении решают :)
