### ISSUE TITLE
User и Group ID в компонентах Avatar и UsersStack

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#408]
Было бы очень удобно иметь возможность использовать ID пользователей и групп в качестве `src` и `photos` в компонентах Avatar и UsersStack.

Возможно это может быть хелпер/дополнение к VKUI.

**Comment by ArthurStam** [comment]
Думаю, такой компонент-надстройку стоит реализовывать на уровне приложения, а не библиотеки) вещь прикольная, но это уже другой слой абстракции и не хочется держать его в либе.

**Comment by mahnunchik** [comment]
`vkui-helpers` :+1:
