### ISSUE TITLE
Возможность свайпа на панель назад при открытом модальном окне. 

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#409]
https://youtu.be/8eaXiADdVvk
Пример кода: https://github.com/iSa1vatore/vk-mini-app-boilerplate/blob/master/src/AppWithoutEpic.js

**Comment by MrZillaGold** [comment]
https://github.com/VKCOM/VKUI/issues/178

**Comment by ArthurStam** [comment]
Привет. У тебя View ссылается на одни и те же `activePanel` и `history`. Отсюда и странное поведение) каждая View должна иметь собственную `history` и `activePanel`
