### ISSUE TITLE
Модальная страница в раскрытом виде заезжает под кнопки управления VK Mini Apps

### ISSUE THREAD

**Issue by nbarinov** [VKCOM/VKUI#411]
Если модальную страницу раскрыть на весь экран, то ее шапка заезжает под кнопки управления VK Mini Apps. Проверял на iPhone 7, 7+, XR. На первых двух баг присутствует, на XR – нет.

**Comment by ArthurStam** [comment]
Привет, тикет без скриншота и ссылки на код вряд ли будет когда-либо рассмотрен.

**Comment by fedorov-xyz** [comment]
Привет, используется ли ConfigProvider?

**Comment by nbarinov** [comment]
@nbarinov https://github.com/clickpick/qr-game/blob/master/src/modals/RequestFunding.js
![IMG_0191](https://user-images.githubusercontent.com/12908670/66350322-0ddf7980-e96c-11e9-90eb-87e619394c66.png)

**Comment by nbarinov** [comment]
@fedorov-xyz, да, использую.

**Comment by nbarinov** [comment]
@ArthurStam, пример: https://github.com/clickpick/qr-game/blob/master/src/modals/RequestFunding.js

iPhone 7:
![IMG_0191](https://user-images.githubusercontent.com/12908670/66350412-467f5300-e96c-11e9-837f-4c7c9651d14b.png)

**Comment by fedorov-xyz** [comment]
```js
<ConfigProvider webviewType="vkapps">
```
Тогда всё будет корректно работать.
