### ISSUE TITLE
[Doc]: Неверный параметр для PanelHeaderBack

### ISSUE THREAD

**Issue by dd114** [VKCOM/VKUI#4144]
### Описание

`PanelHeaderBack` используется с параметром `left` для `PanelHeader`, а не с параметром `before` как об этом пишется в документации
С параметром `before` кнопка не появляется

https://vkcom.github.io/VKUI/#/PanelHeaderBack

**Comment by BlackySoul** [comment]
Привет! Можно поподробнее, где именно проблема? 
В примере [PanelHeader](https://vkcom.github.io/VKUI/#/PanelHeader) (вторая панель) используется `PanelHeaderBack` в параметре `before`.

Возможно, вы используете версию библиотеки ниже `4.32.0`, только начиная с неё появляется параметр `before`. 

Найти документацию нужной версии можно здесь:
<img width="1018" alt="Снимок экрана 2023-02-07 в 10 33 03" src="https://user-images.githubusercontent.com/7431217/217141789-2f1d3004-446b-4ebb-a42c-540b3022d309.png">

**Comment by dd114** [comment]
Да, действительно, проблема была в старой версии библиотеки
Спасибо
