### ISSUE TITLE
[Enhancement][a11y] Доступность карточек

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#4186]
Есть [отличная статья про то, как сделать карточки доступными](https://inclusive-components.design/cards/) (да, она 2018 года); хорошо бы взять ее за основу и прокачать доступность наших карточек.

**Предложения**
- `CardGrid`, `CardScroll`: сделать рутовым элементом `<ul>` вместо `<div>`
  - возможно — дать возможность пробросить `Component`
- `Card`, `ContentCard`: сделать рутовым элементом `<li>` вместо `<div>`
  - возможно — дать возможность пробросить `Component`
- попробовать отвязать `ContentCard` от `Tappable` (связано с https://github.com/VKCOM/VKUI/issues/1443). Сложность `Tappable` в принципе с точки зрения доступности очень сильно мешает

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.6.0" target="_blank">v6.6.0</a> 🎉
