### ISSUE TITLE
Помогите. Как лучше закрывать снеки при обновлении страницы?

### ISSUE THREAD

**Issue by ciricc** [VKCOM/VKUI#419]
Есть такой кейс: снек открылся, но за ним, пока он ещё не закрылся, можно поменять панельку. Снек при этом сохранится. 

Вот я и думаю, можете ли вы прописать ему willUnmount -> onClose, чтобы не вызывать в каждой панельке закрытие самостоятельно? Да, я немного ленивый. Но в целом, это же ничего не испортит? Или все же при возврате на эту же страницу (если снек хранится в стейте storage), будет нормально если юзер опять его увидет и подождёт, пока он сам закроется (или закроет его)

Ещё раз
1. Храним снеки в storage
2. Открываем панельку
3. Открываем снек
4. Закрываем панельку (снек остался, если я не прописал закрытие при unmount)
5. Открываем панельку через время
6. Видим тот же снек, потому что я его не удалил (удаление идёт в onClose)

Или все же лучше это самому делать в каждой панельке, где есть снеки (много где)?

**Comment by fedorov-xyz** [comment]
Считаю, что лучше контролировать их самому, да. Если компонент будет вызывать onClose при componentWillUnmount, это может привести к странным последствиям.

**Comment by ciricc** [comment]
Спасибо
