### ISSUE TITLE
В примере FormStatus не жирный текст у title.

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#422]
1. Переходим по ссылке https://vkcom.github.io/vkui-styleguide/#formstatus
2. Ставим bright_light или client_light (Что бы было лучше видно)

Получаем:
Title у FormStatus не жирный.

**Comment by ilyapishchulin** [comment]
![image](https://user-images.githubusercontent.com/45998835/67105568-a62df780-f1d1-11e9-8114-e8ade99af5a9.png)

**Comment by ArthurStam** [comment]
Привет. В каком браузере смотришь?

**Comment by ilyapishchulin** [comment]
Google. 
Версия 76.0.3809.132 (Официальная сборка), dev (64 бит)

**Comment by ArthurStam** [comment]
А что за OS?

**Comment by ArthurStam** [comment]
Если это винда, то в её системном шрифте может не поддерживаться начертание `font-weight: 500`. Но нас это не волнует, потому что мы поддерживаем iOS и Android браузеры.

**Comment by ilyapishchulin** [comment]
Ну, значит пофиг)
