### ISSUE TITLE
[Bug]: Epic отрисовывает Tabbar и SplitCol

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#4279]
### Описание

Related to https://github.com/VKCOM/VKUI/issues/3210

### Версия

5.2.0

### В каких браузерах воспроизводится проблема?

Safari

### Шаги воспроизведения

1. Открыть https://vkcom.github.io/VKUI/#!/Epic

### Ожидаемое поведение

Для приведенных ниже параметров должен отрисовываться только Таббар

platform: android
appearance: light
Высота окна: 667
Ширина окна: 320

### Скриншоты

<img width="360" alt="Screenshot 2023-02-18 at 7 41 33 PM" src="https://user-images.githubusercontent.com/45998835/219862421-44fc9b34-00e1-4c6b-a5f1-99ce92989221.png">

### Пример с воспроизведением

Форк не нужен, так как воспроизводится в сандбоксе документации

**Comment by SevereCloud** [comment]
Привет, фикс будет доступен в 5.2.1
