### ISSUE TITLE
Очень нужно отказаться от % в css анимациях.

### ISSUE THREAD

**Issue by ciricc** [VKCOM/VKUI#430]
Знаю, что в некоторых местах при перемещении без `%` не обойтись, но почти все можно считать через JS. CSS плохо работает с процентами в анимациях. Даже тот же 100vh работает куда быстрее и плавнее. А когда происходит еще и двойная анимация (например, нажал кнопку - открылся popout), то начинается вообще полный ужас (% в одной анимации, % во второй и т.д, и это все одновременно).

И да, translate3d здесь не спасет

Спасибо.

**Comment by ArthurStam** [comment]
Спасибо, подумаем :)

**Comment by eolme** [comment]
>  CSS плохо работает с процентами в анимациях. 

@ciricc, где можно об этом найти информацию? Первый раз вижу, чтобы писали, что JS анимации быстрее. На сколько знаю, даже FF раньше (или все ещё) писал, что рекомендуется заменить JS анимации на CSS по возможности.

**Comment by ciricc** [comment]
> > CSS плохо работает с процентами в анимациях.
> 
> JS анимации быстрее.

Я про то, что, если вам что-то нужно посчитать через процентное соотношение, то лучше это считать заранее, а в css подставлять уже готовое значение в px или в vh/vw, потому что иначе этот % будет считать каждый кадр, тем самым, замедляя обработку. Я же не говорю, что надо все анимации переписывать на JS. 

Об этом где-то писали, но я не смогу скинуть ссылку, просто чисто из практики знаю, что это работает, можете сами проверить.

**Comment by inomdzhon** [comment]
Я потестил в двух соответствующих песочницах
- [animation-with-percentage](https://glitch.com/~animation-with-percentage)
- [animation-with-px](https://glitch.com/~animation-with-px)

И профайлер расхождение особого не показал

<img width="1792" alt="animation-percent-vs-px" src="https://user-images.githubusercontent.com/5850354/159292051-71727904-3ea7-43a0-9fe1-a1036f4a929b.png">

> ### Среда
>
> **Браузер:** `"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36"`
> **OC:** `MacOS 12.2.1`

Конечно, это всё в чистую проверялось, без скиптинга на фоне и других пользовательских взаимодействий.

Также
1. По коду глянул все `@keyframes` и:
    1. Не нашёл ничего преступного. Только [Snackbar](https://github.com/VKCOM/VKUI/blob/master/src/components/Snackbar/Snackbar.css#L141-L159) использует значение больше 100%.
    2. `infinite` нашёл у [PullToRefresh](https://github.com/VKCOM/VKUI/blob/master/src/components/PullToRefresh/PullToRefresh.css#L70) и [Spinner](https://github.com/VKCOM/VKUI/blob/master/src/components/Spinner/Spinner.css#L11)
3. В интернете проблематику найти не смог.

---

@ciricc подскажи, пожалуйста, насколько эта проблема актуальна?

**Comment by ciricc** [comment]
Честно говоря, я не знаю уже. Давно не пользовался библиотекой. Я думаю, можно закрыть уже этот issue, если будет снова актуально, люди откроют
