### ISSUE TITLE
Нужен code review

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#434]
В файле [touch.ts](https://github.com/VKCOM/VKUI/blob/master/src/lib/touch.ts):
```ts
function rubber(offset: number, /* ... */) {
  if (/* ... */ || offset < 0) return offset;
  const result = /* ... */
  return offset < 0 ? -result : result;
}
```

Почему при отрицательном offset он же и возвращается? И, соответственно, последняя проверка не имеет смысла - всегда возвращается положительный result.

**Comment by fedorov-xyz** [comment]
Вероятно, платформа -- Android, поэтому offset возвращается в исходном виде.

**Comment by eolme** [comment]
Подробнее о чем я говорю: допустим, у нас offset равен -1, тогда сразу вернется -1 и значение result не будет подсчитано. В противоположном случае, когда offset неотрицателен, будет подсчитано значение result, и, так как и так offset неотрицателен, вернется result в исходном виде.

**Comment by eolme** [comment]
#435

**Comment by ArthurStam** [comment]
Оставил комментарий
