### ISSUE TITLE
[Bug]: Прямоугольные Image

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#4346]
### Описание

Компонент Image может быть только квадратным. Необходимо дать возможность сделать его прямоугольным

### Версия

5.2.1

### Пример с воспроизведением

https://vkcom.github.io/VKUI/#/Image

**Comment by inomdzhon** [comment]
Возможно нужно сначала отдать @VKCOM/vkui-design на доработку макета

**Comment by MrZillaGold** [comment]
@SevereCloud поговорил с дизайном, алгоритм закруглений оставляем как у текущего квадратного Image, но считаем по меньшей стороне если это прямоугольник

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.0" target="_blank">v5.10.0</a> 🎉
