### ISSUE TITLE
FixedLayout слетает при возврате на предыдущий View

### ISSUE THREAD

**Issue by ciricc** [VKCOM/VKUI#438]
Если в одном View поставить FixedLayout (любой, нижний, верхний), а затем сделать переход на другой View (В текущем Root), то получится, что при возврате на прошлый View, FixedLayout превращается в position: absolute, соответственное, слетает фиксирование.

Примерный код:

```javascript
<Root id="mainRoot" activeView={activeView}>
 <View id="mainView1" activePanel={activePanel}>
  <Panel id="mainPanel1">
   <FixedLayout vertical="top"><Search/></FixedLayout>
   <Group style={{height: 3200}}>
     <Button onClick={() => setPage(view: "mainView2", panel:"mainPanel2")}>Go</Button>
   </Group>
  </Panel>
 </View>
 <View id="mainView2" activePanel={activePanel}>
   <Panel id="mainPanel2">
     <Group style={{height: 3200}}>
       <Button onClick={() => setPage(view: "mainView1", panel:"mainPanel1")}>Go back</Button>
     </Group>
   </Panel>
 </View>
</Root>
```

**Comment by ArthurStam** [comment]
Там absolute не случайно стоит. На время перехода мы fixed заменяем на absolute. Подробности тут: https://bugs.chromium.org/p/chromium/issues/detail?id=20574
Если что-то скачет, то стоит записать и прислать сюда скринкаст.

**Comment by ciricc** [comment]
Я понимаю зачем это сделано, почему absolute. Но тут другой переход. Я посмотрел код FixedLayout, он ловит событие, когда переход между Panel завершается и он ставит себя в `fixed` (null), но нет ловли события перехода между View'шками, поэтому он как бы остается в `absolute`, даже, когда анимация завершается. Я вот про что. С панельками все ок. С виюшками - все плохо.


(Я про переходы в Root nextView, prevView и т.д)

**Comment by ArthurStam** [comment]
При переходе между View FixedLayout ваще ничего не должен делать (по идее). У тебя activePanel у обоих View смотрят на одно и то же значение в state?

**Comment by fedorov-xyz** [comment]
Подтверждаю, есть такой баг.

**Comment by ArthurStam** [comment]
Видео мне пришлите) ни разу не смог воспроизвести.

**Comment by drago-v** [comment]
При следующей структуре приложения  у FixedLayout будет баг, как на [видео](https://vk.com/video-186031647_456239017)

```
<Root id="mainRoot" activeView={this.state.activeView}>
  <View id="mainView1" activePanel={this.state.activePanel}>
    <Panel id="mainPanel1">
      <PanelHeader>mainView1 > mainPanel1</PanelHeader>
      <Group style={{height: 3200}}>
        <Div>
          <Button size="xl" onClick={() => this.setPage({view: "mainView2", panel: "mainPanel2"})}>
            Следующий View
          </Button>
        </Div>
      </Group>
      <FixedLayout vertical="bottom"><Search/></FixedLayout>
    </Panel>
  </View>
  <View id="mainView2" activePanel={this.state.activePanel}>
    <Panel id="mainPanel2">
      <PanelHeader>mainView2 > mainPanel2</PanelHeader>
        <Group style={{height: 32003}}>
          <Div>
            <Button size="xl" onClick={() => this.setPage({view: "mainView1", panel: "mainPanel1"})}>
              Вернуться назад
            </Button>
          </Div>
        </Group>
      </Panel>
  </View>
</Root>
```

**Comment by ArthurStam** [comment]
Так и не воспроизвел. Закрываю тикет за отсутствием активности. Переоткрывай, если до сих на последней стабильной версии баг проявляется
