### ISSUE TITLE
Свайп приводит к белому экрану.

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#439]
1. Не подключаем никакого свайпа.
2. Делаем конструкцию:
<Root>
 <View>
  <Panel/>
 </View>
  <View>
    <Panel/>
  </View>
</Root>
3. Из панели в 1 View, меняем активный View и ActivePanel на панель во втором View, все гуд.
4. Свайпаем назад после открытия.

Итог: белый экран.

**Comment by ilyapishchulin** [comment]
![9DEFB202-BA11-462D-8511-F72D9F5925C9](https://user-images.githubusercontent.com/45998835/68618242-f569fe00-04d9-11ea-844b-b8bee0848961.png)
![FC880FD7-242F-4B02-9B5F-C2339F3F148D](https://user-images.githubusercontent.com/45998835/68618276-07e43780-04da-11ea-9d93-c4230ca8418f.jpeg)

**Comment by ArthurStam** [comment]
Привет. Полный листинг кода в студию, плиз

**Comment by ilyapishchulin** [comment]
`</div>
            <Button className="fidbackcomment" before={<Icon24CommentOutline/>} stretched
        onClick={() => love.commentsGet(love.state.selected_book['id'])}
        >Рецензии</Button>
        </div>`

**Comment by ilyapishchulin** [comment]
`commentsGet(book_id) {
		this.setState({popout: 
			<div className="loader">
             <div className="l_main">
               <div className="l_square"><span></span><span></span><span></span></div>
               <div className="l_square"><span></span><span></span><span></span></div>
               <div className="l_square"><span></span><span></span><span></span></div>
               <div className="l_square"><span></span><span></span><span></span></div>
             </div>
             </div> 
		})
		fetch(this.state.api_url + "method=comments.get&book_id=" + book_id+ "&" + window.location.search.replace('?', ''))
		.then(res => res.json())
		.then(result => {
			if(result.response) {
				this.setState({selected_book_comments: result.response})
				this.setState({ popout: null, activeView: "bookscomment", activePanel: "bookscomment", helpnavigation_array: "bookinfo"})
			}
			else {
				this.setState({errorcodeforalert: result.error.message});
				this.showZaprosFailedAun();
			}
		})
		.catch(err => {
			this.showZaprosFailedAun();
		});
	}`

**Comment by ilyapishchulin** [comment]
<Root activeView={this.state.activeView}>
				<View id="home" activePanel={this.state.activePanel} popout={this.state.popout} header={false} modal={modal}>
				    <Home id="home" go={this.go} this={this} />
				    <Biography id="biography" go={this.go} this={this} />
				    <Bookinfo id="bookinfo" go={this.go} this={this}/>
				    <AuthorInfo id="authorinfo" go={this.go} this={this}/>
				</View>
				<View id="bookscomment" activePanel={this.state.activePanel} popout={this.state.popout} header={false}>
					<Bookscomment id="bookscomment" go={this.go} this={this}/>
				</View>
				<View id="reader" activePanel={this.state.activePanel} popout={this.state.popout} header={false}>
					<Reader id="reader" go={this.go} this={this}/>
				</View>
			</Root>

**Comment by ArthurStam** [comment]
У вас у каждой VIew activePanel – это одно и то же значение. Правильно – это когда каждая View.activePanel ссылается на отдельное значение в state.

**Comment by ilyapishchulin** [comment]
Эмм, ну ладно, спасибо.
