### ISSUE TITLE
[Doc]: Описанный в документации функционал пропа count у компонента UsersStack не соответствует действительности

### ISSUE THREAD

**Issue by obergodmar** [VKCOM/VKUI#4440]
### Описание

В доке сказано: 

Число, которое будет указано в счетчике. По умолчанию высчитывается по формуле photos.length - visibleCount. **Если число больше 99, то счетчик скроется.**

Однако любое число, большее 99 не вызывает описанного скрытия счетчика.

116 строка файла `packages/vkui/src/components/UsersStack/UsersStack.tsx`
```javascript
  const canShowOthers = count > 0 && size !== 's';
```
не содержит в себе указанного в доке ограничения.

**Comment by TUTOR03** [comment]
Поддерживаю. Можно получить неожиданное поведения у компонента просто передав счетчик больше 99.
![image](https://user-images.githubusercontent.com/43278213/224089020-aadac716-a798-4e15-b7c7-e4a4628dd53b.png)
