### ISSUE TITLE
Не срабатывает onChange на Switch

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#447]
`<Switch
   onChange={() => { console.log('test') }}
   defaultChecked
/>`
При переводе из положения Вкл в Выкл, onChange не срабатывает, при повтором (из Выкл в Вкл), всё норм.

**Comment by fedorov-xyz** [comment]
Привет. Кажется, всё дело в `defaultChecked`.
Если передавать в компонент `checked={true}` или `checked={false}` и `onChange`, который и будет менять это передаваемое значение, то всё должно быть хорошо.

**Comment by ArthurStam** [comment]
@fedorov-xyz не прав. Всё должно работать так же, как с обычным `<input type="checkbox" />`. Я проверил, у меня работает. @SkyGopnik пришлите пожалуйста ссылку на живой пример с багом.

**Comment by ArthurStam** [comment]
Закрываю за отсутствием активности. Рабочий пример: https://0y3261z1pw.csb.app/
