### ISSUE TITLE
ModalRoot не обновляет высоту ModalPage при включенном dynamicContentHeight

### ISSUE THREAD

**Issue by stels-cs** [VKCOM/VKUI#448]
Выполнение не доходит сюда
https://github.com/VKCOM/VKUI/blob/4d6d1792d792708e9bb16d3870e7d3b644199348/src/components/ModalRoot/ModalRoot.tsx#L167

из-за условия выше this.props.children !== prevProps.children (всегда будет false если не менять детей в ModalRoot)
https://github.com/VKCOM/VKUI/blob/4d6d1792d792708e9bb16d3870e7d3b644199348/src/components/ModalRoot/ModalRoot.tsx#L164

**Comment by fedorov-xyz** [comment]
Привет, высота у ModalCard и не будет меняться, `dynamicContentHeight` сделан для модальных страниц, где вопрос изменения контента, а значит и возможности раскрыть на весь экран, стоит острее.

**Comment by stels-cs** [comment]
Перепутал названия, про ModalPage и речь изначально

**Comment by fedorov-xyz** [comment]
А что ты делаешь, что должно обновлять высоту модалки, но при этом children не меняется?

**Comment by stels-cs** [comment]
Выношу саму панель в отдельный файл

Вот пример:
https://github.com/stels-cs/demo-panel-bug 
https://vk.com/app7242088

**Comment by fedorov-xyz** [comment]
Спасибо, буду смотреть.
Мб есть идеи, как сделать это правильнее, чтобы такие случаи тоже работали?

**Comment by stels-cs** [comment]
Проверил еще раз, все-же это у меня неверный пример, высота не пересчитывается потому что нет ререндера ```ModalRoot```. В реальном проекте его нет из-за redux'a и "умных компонентов".

Может сделать через контекст, что-то типа  ```withHeightUpdate(Component)``` и в нужных местах вызвать ```this.props.updateHeight()``` (фактически на любом ```componentDidUpdate```)

**Comment by fedorov-xyz** [comment]
Исправлено в версии 3.3.5
Подробности в документации – https://vkcom.github.io/vkui-styleguide/#!/ModalRoot
