### ISSUE TITLE
Не переключаются слайды в Gallery 

### ISSUE THREAD

**Issue by Winexcel** [VKCOM/VKUI#449]
Версия VKUI самая последняя, загрузил пример с проблемой по ссылке https://vk.com/app6904385, если с десктопа открыть и пытаться переключить слайды у галереи с 2-мя вложениями, то слайды не будут переключаться.

Вот весь код одной галереи с 2-мя вложениями(остальные сделаны аналогично, только там больше div блоков):

```
<Gallery
slideWidth="40vh"
align="center"
style={ { height: '40vh', overflow: 'hidden' } }
>
<div className="Gallery-Item Gallery-Item__red">1</div>
<div className="Gallery-Item Gallery-Item__blue">2</div>
</Gallery>
```

**Comment by fedorov-xyz** [comment]
Действительно похоже на баг.
Спасибо, будем смотреть.

**Comment by ArthurStam** [comment]
Это не баг. Свайп в Gallery отключается, если сумма ширин всех элементов галереи меньше, чем ширина самой галереи. В вашем примере в какой-то момент так и происходит: галерея занимает всю ширину экрана, а слайда всего два и их суммарная ширина меньше ширины экрана.

**Comment by lonadels** [comment]
> Это не баг. Свайп в Gallery отключается, если сумма ширин всех элементов галереи меньше, чем ширина самой галереи. В вашем примере в какой-то момент так и происходит: галерея занимает всю ширину экрана, а слайда всего два и их суммарная ширина меньше ширины экрана.

невозможно увидеть второй слайд, но не баг, а фича

**Comment by ArthurStam** [comment]
@lonadels его невозможно увидеть, потому что вы навесили `overflow: hidden` на `Gallery`.
