### ISSUE TITLE
[Bug]: Сломано выравнивание DatePicker (Safari)

### ISSUE THREAD

**Issue by BlackySoul** [VKCOM/VKUI#4549]
### Описание

`DatePicker` не выровнен по центру в `Safari` при заданном `hasPointer=false`
<img width="791" alt="image" src="https://user-images.githubusercontent.com/7431217/226659453-7ecea880-ac4f-4e62-9766-66cad6de58b9.png">

### Версия

v5

### В каких браузерах воспроизводится проблема?

Safari

**Comment by SevereCloud** [comment]
В chrome dev версии тоже сломалось(в стабильной ок)
<img width="766" alt="image" src="https://user-images.githubusercontent.com/14944123/226672950-dce1ad5a-3ddb-40fd-b681-b61c526cee37.png">
