### ISSUE TITLE
Поддержать href у ActionSheetItem.

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#455]
Не возможно всякие костыли уже делать, поддержите, пожалуйста.

**Comment by ArthurStam** [comment]
Звучит, как нужная фича. Спасибо, добавим.

**Comment by ArthurStam** [comment]
Пофикшено в 3.0.0-alpha.4

**Comment by ilyapishchulin** [comment]
@ArthurStam и как скоро выйдет альфа?
