### ISSUE TITLE
Возможно ли менять цвет текста в Cell indicator

### ISSUE THREAD

**Issue by a1phaZ** [VKCOM/VKUI#457]
При навешивание style={{ fontSize: '...' }} на компонент Cell размер шрифта в индикаторе меняется, при навешивании color: '#......' ни чего не происходит, в чем подвох? Возможно ли вообще поменять цвет у индикатора?

**Comment by a1phaZ** [comment]
Решил проблему через добавление в indicator своего компонента 
```javascript
import React from 'react';
import prepare from "../handlers/prepare";

const ColoredSum = ({sum}) => {
	const stl = sum > 0 ? {color: '#28a745'} : {color: '#dc3545'};
	return(
		<span style={stl}>{prepare.sum(sum)}</span>
	)
};

export default ColoredSum;
```

11 строк вместо 1ой %)

**Comment by ArthurStam** [comment]
Привет. Библиотека не предусматривает стилизацию текста индикатора.
