### ISSUE TITLE
<Link> не принимает атрибут `href`, который принимается HTMLAnchorElement

### ISSUE THREAD

**Issue by handlerug** [VKCOM/VKUI#458]
В документации указано, что компонент `<Link>` принимает все атрибуты, которые принимает тег `<a>` в HTML (то есть `HTMLAnchorElement`). Однако TypeScript ругается на то, что `href` не относится к пропсам `<Link>` (`IntrinsicAttributes & LinkProps & { children?: ReactNode; }`).

![Eke6EoxdL4c](https://user-images.githubusercontent.com/24986597/71545347-a3fbcc80-29bc-11ea-8cf9-771cd6082500.jpg)

`@vkontakte/vkui`: `3.0.0-alpha.3`

**Comment by ArthurStam** [comment]
Спасибо, поправим

**Comment by ArthurStam** [comment]
Пофикшено в 3.0.0-alpha.4
