### ISSUE TITLE
Пожелание: поддержать false, null и undefined в тайпинге lib/classNames(...)

### ISSUE THREAD

**Issue by handlerug** [VKCOM/VKUI#459]
Сейчас эта функция принимает параметры типов `number`, `string` и `ObjectClassNames`.

Так как эта функция отсеивает классы с помощью проверки на `false` (`if (!item) ...`), то удобно было бы передавать ей:
 - булевы значения (например, `isOpened && "Modal--opened"`);
 - `null` и `undefined` (например, доставать `className` из `...restProps` и передавать его вместе со своими классами в `classNames(...)`).

**Comment by ArthurStam** [comment]
Привет. Спасибо, подумаем.

**Comment by ArthurStam** [comment]
MR принят, фича доступна с 3.0.0-alpha.5
