### ISSUE TITLE
[Doc]: `aria-label` помечен как необязательный атрибут, но без него компонент не рендерится

### ISSUE THREAD

**Issue by scffs** [VKCOM/VKUI#4595]
### Описание

[doc link](https://vkcom.github.io/VKUI/#/TabbarItem)

В примере нет ни одного `aria-label` и в атрибутах он помечен как `?`

![изображение](https://user-images.githubusercontent.com/67464545/227555862-5e7514cf-adc4-4325-83a3-d2c1896b8534.png)

P.S. Либо я не туда кидаю aria-label, либо почему я всё равно получаю ту же ошибку?
![изображение](https://user-images.githubusercontent.com/67464545/227556022-fa809d93-698d-4b24-9238-2ea097eb2c8a.png)

**Comment by eugpoloz** [comment]
@scffs привет! Спасибо за бдительность, в примерах действительно не хватает `aria-label` — в тех, где никак не задан `text` (то есть внутреннего текстового содержимого у компонента нет никакого).

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/22026957/228254974-62abcfec-0cee-4767-b042-d291484e120f.png">

Вот тут можно посмотреть фикс: https://github.com/VKCOM/VKUI/pull/4629

Как только он заедет — issue закроется.
