### ISSUE TITLE
[Bug]: Неправильный токен у компонента Counter

### ISSUE THREAD

**Issue by Andrew-dushes** [VKCOM/VKUI#4596]
### Описание

<img width="175" alt="Снимок экрана 2023-03-27 в 01 47 27" src="https://user-images.githubusercontent.com/70465331/227803707-0e18a330-a69c-4680-aba1-55bf4e7d91e9.png">

Отличаются в разных местах цвет каунтера на проде 
Правильный токен - (допольниться)

### Версия

V4?

**Comment by eugpoloz** [comment]
Привет! Вопрос не к нам, каунтеры в мессенджере и в боковом меню ВКонтакте (пока) берутся не из VKUI.

Задачу закрываю.
