### ISSUE TITLE
Неправильные типы пропсов у Switch

### ISSUE THREAD

**Issue by handlerug** [VKCOM/VKUI#460]
Экстендить `React.HTMLAttributes<HTMLInputElement>` недостаточно, вместо него нужно экстендить `React.InputHTMLAttributes<HTMLInputElement>`, который включает в себя такой нужный проп, как `checked`, и другие специфичные для `<input>` атрибуты.

`@vkontakte/vkui`: `3.0.0-alpha.3`

**Comment by ArthurStam** [comment]
Спасибо, поправим.

**Comment by ArthurStam** [comment]
Спасибо за MR. Выкатил апдейт в 3.0.0-alpha.4
