### ISSUE TITLE
[Bug]: У Input type=date на iOS отсутствует вертикальное выравнивание

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#4614]
### Описание

Компонент VKUI Input с пропсом type="date" имеет неправильное вертикальное выравнивание. 

![image](https://user-images.githubusercontent.com/22776192/228143331-66f9066d-b80b-42c7-89b5-dd35f6f72939.png)

### Версия

5.2.4

**Comment by SevereCloud** [comment]
Duplicate of #4549
