### ISSUE TITLE
[Doc][Bug]: DatePicker не заменяется на input type=date на мобильном виде

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#4619]
### Описание

DatePicker не заменяется на input type=date на мобильном виде, как заявлено в первом абзаце (см скриншот).

![image](https://user-images.githubusercontent.com/22776192/228143606-c4fefcdd-c705-489b-8677-ffd63db58c56.png)

### Версия

5.2.4

**Comment by SevereCloud** [comment]
Проблема документации, не ошибка библиотеки
