### ISSUE TITLE
Неправильные типы пропсов у Input

### ISSUE THREAD

**Issue by handlerug** [VKCOM/VKUI#463]
Экстендить React.HTMLAttributes<HTMLInputElement> недостаточно, вместо него нужно экстендить React.InputHTMLAttributes<HTMLInputElement>, который включает в себя `value` и другие специфичные для <input> атрибуты. (та же ошибка, что и в #460)

`@vkontakte/vkui`: `3.0.0-alpha.3`

**Comment by ArthurStam** [comment]
Спасибо, поправим.

**Comment by ArthurStam** [comment]
Пофикшено в 3.0.0-alpha.4
