### ISSUE TITLE
При использование PanelHeader падает приложение

### ISSUE THREAD

**Issue by nikitabudkovskiy** [VKCOM/VKUI#464]
При использовании PanelHeader приложение падает с ошибкой: 
Target container is not a DOM element. 

```
The above error occurred in the <PanelHeader> component:
    in PanelHeader (at TastesTobacco/index.tsx:22)
    in div (created by Touch)
    in Touch (created by Panel)
    in div (created by Panel)
    in Panel (created by WithInsets)
    in WithInsets (created by WithPlatform)
    in WithPlatform (at TastesTobacco/index.tsx:21)
    in TastesTobacco (at beginningWork/index.tsx:45)
    in Route (at beginningWork/index.tsx:43)
    in BeginningWork (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (at App.tsx:27)
    in div (created by Touch)
    in Touch (created by Panel)
    in div (created by Panel)
    in Panel (created by WithInsets)
    in WithInsets (created by WithPlatform)
    in WithPlatform (at App.tsx:25)
    in div (at App.tsx:24)
    in App (created by ConnectFunction)
    in ConnectFunction (at src/index.tsx:18)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.tsx:17)
    in Provider (at src/index.tsx:16)

```
Если же задеплоить приложение
```
backend.js:6 Error: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.fu [as createPortal] (react-dom.production.min.js:285)
    at t.value (PanelHeader.js:84)
    at Zo (react-dom.production.min.js:181)
    at Jo (react-dom.production.min.js:180)
    at Ms (react-dom.production.min.js:261)
    at Ol (react-dom.production.min.js:230)
    at Al (react-dom.production.min.js:229)
    at El (react-dom.production.min.js:223)
    at react-dom.production.min.js:121
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
```
Использую React, Redux и для роутинга react-router-dom
Не подскажите, как решить?

**Comment by ArthurStam** [comment]
Привет. Без сниппета с кодом будет сложно разобраться.

**Comment by nikitabudkovskiy** [comment]
Привет, Артур.
https://github.com/nikitabudkovskiy/hookah-mixer
Вот сам проект, в любой компонент можно добавить PanelHeader и приложение упадет.
Ну или вот на codesandbox: https://codesandbox.io/s/proud-wood-0fi5x
К примеру, в песочнице PanelHeader добавлен в компонент IntroContainer
![image](https://user-images.githubusercontent.com/7972703/72104126-2634ab00-3344-11ea-830d-18b7902cd946.png)

**Comment by ArthurStam** [comment]
У вас очень специфическая JSX-структура приложения. Дело в том, что PanelHeader будет работать только если структура такая: View => Panel => PanelHeader.

**Comment by nikitabudkovskiy** [comment]
Я в поддержке спрашивал, можно ли использовать сторонний роутинг, мне ответили да, поэтому и такая структура.
А View я не использую, потому что использую React + TypeScript, если я добавлю View, то компилятор TS сразу говорит, что нужно добавить поле actiePanel, но я использую сторонний роутинг поэтому мне не нужно это свойство, я делаю его пустым и получаю белый экран, что логично, потому что в свойстве activePanel пусто.

Не подскажите, как это можно обойти?

**Comment by ArthurStam** [comment]
Не подскажу) либо не принуждает использовать какое-то конкретный роутинг, но в то же время ваша реализация переходов должна быть сопряжена со свойствами activePanel или activeView. В противном случае, работоспособность либы не гарантируется)

**Comment by ArthurStam** [comment]
На всякий — вот тут есть описание необходимой структуры приложения: https://vkcom.github.io/vkui-styleguide/#!/Concept. Закрываю тикет.

**Comment by FireworksX** [comment]
У меня такая же проблема. vkui: 3.2.1

**Comment by FireworksX** [comment]
У меня такая же проблема. vkui: 3.2.1 
Скрин ошибки: https://yadi.sk/i/g1j8o_AJPfVNHA

**Comment by FireworksX** [comment]
У меня такая же проблема. vkui: 3.2.1
Скрин ошибки: https://yadi.sk/i/g1j8o_AJPfVNHA
Вот код `
export default class Header extends React.Component {

	constructor(props) {
		super(props);
	}

	render() {
		return (
			<Panel id="test">
				<PanelHeader>
					Header
				</PanelHeader>
			</Panel>
		);
	}

}
`
Если я пишу в JS файле, то всё работает, а если я напишу то же самое в tsx файле, то ломается

**Comment by FireworksX** [comment]
Разобрался, у View в котором отображается Panel не был указан activePanel.
