### ISSUE TITLE
Gallery: TypeError: e.originalEvent.target.tagName is undefined

### ISSUE THREAD

**Issue by lonadels** [VKCOM/VKUI#465]
При вытягивании слайдов (особенно за пределы фрейма) возникает **TypeError "x" is (not) "y"** ([developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type)). 

Ошибка возникает даже в демонстрационном примере на [vkcom.github.io/vkui-styleguide/#gallery](https://vkcom.github.io/vkui-styleguide/#gallery). 

Повторение ошибок происходит до тех пор, пока ты не отпустишь слайд. Т.е. на странице таким образом за момент вытягивания слайда может возникнуть более 100+ ошибок в консоли на странице, а во время разработки это вообще мешает отладке приложения, поскольку приводит к остановке работы приложения.

**Comment by ArthurStam** [comment]
Привет. С какого браузера смотришь пример? https://vkcom.github.io/vkui-styleguide/#!/Gallery У меня мак, смотрю в хроме и в сафари — всё ок, ошибок нет.

**Comment by lonadels** [comment]
Использую Firefox. Если потянуть элемент за пределы браузера, возникает ошибка.

**Comment by ArthurStam** [comment]
Спасибо, воспроизвелось. Будет пофикшено в следующей версии.
