### ISSUE TITLE
[Bug]: В ButtonGroup не удается выровнять несколько кнопок по правую сторону 

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#4651]
### Описание

Тут кажется align-items и justify-content перепутали. В ButtonGroup не удается выровнять несколько кнопок по правую сторону (передавая align=right). Пытаюсь организовать футер модалки, где кнопки по правую сторону.

![image](https://user-images.githubusercontent.com/22776192/228815527-a1507a01-5b73-497b-90ca-b1b0208c81f2.png)

### Версия

5.3.0

**Comment by mendrew** [comment]
@inomdzhon возьму в работу.
