### ISSUE TITLE
[Bug]: Group без mode должен вести себя как mode=plain

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#4655]
### Описание

В Group если не передать mode, то образуется селектор vkuiGroup--mode-**none**. Отображение получается особенным незадокументированным, неприятным, в вебе появляется рамка. Хотя по доке mode=plain по-умолчанию. 

Можно попробовать убрать mode=plain из примера https://vkcom.github.io/VKUI/#/Group в адаптике vkcom

<img width="320" src="https://user-images.githubusercontent.com/22776192/228867487-8354c8e7-f2f5-4e37-9e79-9117b45f4a87.png" /> <img width="320" src="https://user-images.githubusercontent.com/22776192/228867512-20f9fc08-88a6-491e-b526-a34d86c9affb.png" />

Я ленивый, по пусту не привык писать mode=plain, если это дефолтное состояние. Ожидаю одинаковое поведение.

### Версия

5.3.0

**Comment by inomdzhon** [comment]
Проблема решилась за счёт корректировки документации, что добавило ясность

- closed this as [completed](https://github.com/VKCOM/VKUI/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in #5370
