### ISSUE TITLE
[Bug]: AdaptivityProvider по-умолчанию на vkcom имеет особую отрисовку Group в ModalPage

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#4656]
### Описание

VKCOM
AdaptivityProvider. ModalPage, комбинации Group и Cell.

ФР
1. sizeX Compact -- в порядке

<img width="477" alt="image" src="https://github.com/VKCOM/VKUI/assets/22776192/c100c954-00a6-4e3f-a0c8-30ffa01ebe73">

2. sizeX не указан -- в порядке

<img width="494" alt="image" src="https://github.com/VKCOM/VKUI/assets/22776192/c0cda93d-0470-4bd7-86e2-b7f72e529d06">

3. sizeX Regular -- не в порядке. Сепаратор имеет правильный боковой. Группы боковой отступ не имеют. Получилась комбинация двух вариантов выше

<img width="474" alt="image" src="https://github.com/VKCOM/VKUI/assets/22776192/720e3b1e-a338-4618-a662-398b1cdf91a5">

### Что сделать

Сделать чтобы sizeX Regular вел себя так же как sizeX не указан.

### Версия

5.10.0

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.5.0" target="_blank">v6.5.0</a> 🎉
