### ISSUE TITLE
[3.0.0] Неправильные отступы при помещении в Header aside div с flex

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#466]
Если в свойство aside в Header засунуть div с display: flex, то он отображается не на том уровне относительно контента в Header.
![Аннотация 2020-01-17 155131](https://user-images.githubusercontent.com/42776347/72587576-5fbb7680-3941-11ea-8c51-e0f836250ed5.png)

В версии 2.34.1 такая конструкция располагается правильно.
![Аннотация 2020-01-17 155154](https://user-images.githubusercontent.com/42776347/72587589-63e79400-3941-11ea-8939-4fa8c044e323.png)
```
<Header level="secondary" aside={
    <div style={{display: "flex"}}>
        <Icon24Cancel style={{marginRight: "5px"}}/>
        <Icon24Done/>
    </div>}>
История запросов
</Header>

**Comment by ArthurStam** [comment]
Спасибо, проверим :)

**Comment by thoughtspile** [comment]
вы продолжаете меня радовать

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.0" target="_blank">v5.9.0</a> 🎉
