### ISSUE TITLE
[Enhancement][a11y][Footer]: Добавить `role="contentinfo"`

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#4692]
Из аудита невизуальной доступности VKUI:
> Нужно тегу `<footer />` задать `role="contentinfo"`. В принципе теги семантических областей лучше дублировать ролями, потому что в некоторых ситуациях они просто не считываются.

Поскольку `Footer` у нас используется как минимум внутри `Group` и `role="contentinfo"` повторяется, то каждый `Footer` [требует обязательного `aria-label`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/contentinfo_role). Соответственно, нужен какой-то временный пропс для `Group`, использующийся вместе с `description`.
UPD(@mendrew): это не верно, в [Group](https://vkcom.github.io/VKUI/#/Group) [Footer](https://vkcom.github.io/VKUI/#/Footer) не используется, там используется [Footnote](https://vkcom.github.io/VKUI/#/Footnote), так что такой проблемы нету.
https://github.com/VKCOM/VKUI/blob/0f313a6b8c8a94b05ca21279098a027dfe02f1ca/packages/vkui/src/components/Group/Group.tsx#L152-L154

**Что я вижу как решение:**

- `Footer`: добавляем дефолтную `role="contentinfo"`, даем возможность переопределять ее вместе с `Component`
- `Group`: создаем подкомпонент `Group.Description`, описываем, как его использовать и как сделать доступным https://github.com/VKCOM/VKUI/issues/5758
- `Group`: депрекейтим проп `description` в пользу `Group.Description`.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.5.2" target="_blank">v6.5.2</a> 🎉
