### ISSUE TITLE
[BREAKING CHANGE][ActionSheet]: Сделать `toggleRef` обязательным

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#4694]
https://github.com/VKCOM/VKUI/blob/c40333bf90149e6e1016d6d5f3733e7bfa53b2b6/packages/vkui/src/components/ActionSheet/types.ts#L12-L17

Собирались сделать это еще в v5, но потеряли. 🙈

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
