### ISSUE TITLE
[BREAKING CHANGE][Epic][a11y]: Доступность заголовков

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#4696]
Исследование невизуальной доступности выявило много проблем с заголовками, в частности:

- `ActionSheet`: значения не должны быть заголовками
- `Group`: заголовок не является заголовком
- `Header`: нет заголовка и подзаголовка
- `ModalCardBase`: второй заголовок не нужен
- `Placeholder`: header и children оборачиваются в заголовки `h2` и `h4`, которые, возможно, не нужны
- `Search`: под полем присутствует заголовок `h4` "Поиск", надобность которого не ясна
- `Snackbar`: `subtitle` оборачивается в `h5` заголовок, хотя не является им с точки зрения семантики

### В чем глобальная проблема?

Некоторые типографические компоненты используют в своей основе теги заголовков, несмотря на то, что в реальности эти компоненты чисто визуальные:

- `Headline`: дефолтный `Component = 'h4'`,
- `Subhead`: дефолтный `Component = 'h5'`,
- `Title`: `Component` привязан к `level`, хотя не должен быть.

При этом в абсолютном большинстве случаев этот `Component` изнутри компонента переопределить невозможно. Как выглядит, например, вышеупомянутый `Placeholder`: https://github.com/VKCOM/VKUI/blob/c40333bf90149e6e1016d6d5f3733e7bfa53b2b6/packages/vkui/src/components/Placeholder/Placeholder.tsx#L53-L62

### Как можно решить?

Сейчас решить эту проблему можно только прокидыванием дополнительных пропсов практически к каждому компоненту (например, `headerComponent` — к `header`), в котором используется типографика.

```diff
-<Placeholder header="Уведомления от сообществ">
+<Placeholder
+  header="Уведомления от сообществ"
+  headerComponent="h2"
+>
  Подключите сообщества, от которых Вы хотите получать уведомления
</Placeholder>
```

Как промежуточное решение оно имеет право на существование, но по итогу — очень сильно замусорит пропсы и ухудшит DX.

Поэтому идеальный вариант — это переход на подкомпонентный подход к v6. Тогда, например, в тот же `Placeholder` вместо пропа `header` можно будет передавать `<Placeholder.Header />` и задавать ему абсолютно все нужные пропсы:

```diff
-<Placeholder header="Уведомления от сообществ">
+<Placeholder>
+  <Placeholder.Header Component="h2">Уведомления от сообществ</Placeholder.Header>
  Подключите сообщества, от которых Вы хотите получать уведомления
</Placeholder>
```

Подкомпоненты мы можем делать уже сейчас, сохраняя обратную совместимость.

Также нужно подфиксить все проблемы конкретных типографических компонентов.

 ## Что делаем?

- [x] #4698
- [x] #4697
- [x] #4700
- [ ] #4699

И переводим сами компоненты на подкомпонентный подход, конечно. (%

**Comment by mendrew** [comment]
В v6 ситуация исправлена. Смотри https://vkcom.github.io/VKUI/6.0.0-beta.3/ и все прилинкованные к этой задачи PRs.

Но решено добавлением новых пропсов и заменой тэгов по умолчанию. Подкомпонентный подход будет вводится постепенно и отдельно в https://github.com/VKCOM/VKUI/issues/4699

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
