### ISSUE TITLE
Двойной вызов onClose у Alert на андроид

### ISSUE THREAD

**Issue by stels-cs** [VKCOM/VKUI#470]
Метод onClose компонента Alert вызывается дважды на андроид, из за того что дважды приходит событие webkitTransitionEnd

**Воспроизведение:**
Выбираем платформу adnroid
https://vkcom.github.io/vkui-styleguide/#alert добавляем логилования в метод закрытия
<img width="373" alt="Снимок экрана 2020-01-21 в 17 17 25" src="https://user-images.githubusercontent.com/8437497/72813907-35d1bf00-3c75-11ea-86e2-721221fd262c.png">

Закрываем попап, получаем две записи в консоли

Так так происходит из-за двойного вызова события завершения анимации transform и opacity
<img width="398" alt="Снимок экрана 2020-01-21 в 17 19 09" src="https://user-images.githubusercontent.com/8437497/72814109-9103b180-3c75-11ea-8bd7-a485e98ee948.png">

**Comment by lonadels** [comment]
А Вы проверку добавьте в начало метода closePopout, и Ваш баг исправится ¯\_(ツ)_/¯
`if( ! this.state.popout ) return;`

**Comment by ArthurStam** [comment]
@stels-cs спасибо! Чекнем и поправим.
