### ISSUE TITLE
[3.0.0] Отсутствует отступ у Separatorа с использованием его под List

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#474]
Располагаем Separator под List.
При таком расположении у Separator нет отступа и происходит наложение элементов друг на друга.
![image](https://user-images.githubusercontent.com/42776347/73059011-83059900-3ee0-11ea-9d02-89c9c3b60b9a.png)
![image](https://user-images.githubusercontent.com/42776347/73059039-9284e200-3ee0-11ea-9e2d-b179d8d5c7a8.png)

***

В версии 2.34.1 такая конструкция располагается правильно. 
![image](https://user-images.githubusercontent.com/42776347/73059176-e1327c00-3ee0-11ea-8fc3-d1a3388700ce.png)
![image](https://user-images.githubusercontent.com/42776347/73059241-07581c00-3ee1-11ea-9a2d-e2bcc642137b.png)
```js
<Group title="Test">
  <List>
    <Cell expandable onClick={() => console.log(123)}>Учетная запись</Cell>
  </List>
  <Separator/>
  Content
</Group>
```

**Comment by ArthurStam** [comment]
Вот ваш пример в sandbox, не вижу наложения
https://codesandbox.io/embed/vkui-boilerplate-hop2r?fontsize=14&hidenavigation=1&theme=dark
В каком браузере и на какой операционке тестите?

**Comment by MrZillaGold** [comment]
Да, протестил в такой комбинации не работает.
Необходимо обернуть мой пример в FormLayout.
https://codesandbox.io/s/vkui-boilerplate-11yln?fontsize=14&hidenavigation=1&theme=dark

**Comment by ArthurStam** [comment]
Ваш пример падает с ошибкой 
![image](https://user-images.githubusercontent.com/5061840/74167337-2cff5800-4c39-11ea-9fbc-2d4093f55965.png)

**Comment by MrZillaGold** [comment]
Кажется проблема в самом codesandbox.io, ваш пример выше тоже не запускается.

Вот сам код, протестируйте его в том же самом https://vkcom.github.io/vkui-styleguide.
```
<FormLayout>
       <Group>
            <List>
              <Cell removable>
                Учетная запись
              </Cell>
            </List>
            <Separator/>
               Content
       </Group>
</FormLayout>

**Comment by ArthurStam** [comment]
В `FormLayout` `Group` лучше не засовывать. `FormLayout` — обертка для компонентов, описанных вот тут https://vkcom.github.io/vkui-styleguide/#!/Forms
