### ISSUE TITLE
[Feature]: Кастомная стрелка для Tooltip и RichTooltip

### ISSUE THREAD

**Issue by zelflod** [VKCOM/VKUI#4748]
### Описание

Нужен дополнительный параметр для кастомизации стрелочки у Tooltip

Например так: 
<img width="519" alt="image" src="https://user-images.githubusercontent.com/25909486/230375307-20191763-6a74-4178-9018-5a4d20d40fb3.png">

Сейчас svg стрелочки берется из PopperArrow, нужно сделать возможность заменить этот svg кастомным вариантом. Для кастомной стрелки нужно указать требования: направление стрелки, макс/мин размеры

Нужно синхронизиорвать border-radius у тултипа и расположение стрелки чтобы недопустить такого:
<img width="244" alt="image" src="https://user-images.githubusercontent.com/25909486/230375430-63da50cd-5d63-467e-88eb-e6f8273ea4b4.png">

**Comment by Fliqle** [comment]
Вот такая идея, а что если:
1. Дать возможность загружать свою стрелку в свг
2. Отступ от края до стрелки можно будет перебивать 
3. Можно будет вручную поменять радиусы углов у тултипа

Так сможем сделать?
