### ISSUE TITLE
[Bug]:  SimpleCell не выводит содержимое на ос андроид

### ISSUE THREAD

**Issue by revidovich** [VKCOM/VKUI#4754]
### Описание

![image](https://user-images.githubusercontent.com/63742797/230553689-383d3f6b-aace-483f-984a-ff3fbcd2342a.png)

### Версия

5.0.3

**Comment by BlackySoul** [comment]
Привет! Можешь подробнее описать, что и куда не выводится, какие пропы?)

**Comment by revidovich** [comment]
> Привет! Можешь подробнее описать, что и куда не выводится, какие пропы?)

какую информацию вам нужно? могу созвониться и показать код, я через map рендерю массив, каждая итерация - отдельный SimpleCell. данные выводятся на десктопе и на иос. а вот андроид выдаёт пустой скелет аватарок (пустых) без подписей и без текста.

**Comment by revidovich** [comment]
чем различаются компоненты для андроида от компонентов других платформ? например сейчас эта же проблема выявилась с RichCell

**Comment by revidovich** [comment]
![image](https://user-images.githubusercontent.com/63742797/232423129-121f9375-9b92-46cb-aee6-1d5ac6db7562.png)

**Comment by revidovich** [comment]
@BlackySoul

**Comment by revidovich** [comment]
@SevereCloud  простите, а что значит статус Blocked?...   
![image](https://user-images.githubusercontent.com/63742797/232424391-38475ca1-8ab5-4921-a2ca-ce35645cc642.png)

**Comment by SevereCloud** [comment]
Привет, можешь сделать пример с воспроизведением? Сделал [пример](https://codesandbox.io/s/issue4754-szvums) по твоему описанию, не воспроизводится

<details><summary>Скриншот с Google Pixel 6</summary>
<p>

![Screenshot_20230417-112128](https://user-images.githubusercontent.com/14944123/232427288-86dc4a0c-4ae8-4e6f-bde3-8b852c839973.png)

</p>
</details> 

Нужно больше подробностей. Если это воспроизводится на определенном устройстве, не мешает описать его. Возможно стоит посмотреть что происходит в DOM или глянуть на стили

---

> что значит статус Blocked?

Необходимо больше информации о проблеме

**Comment by revidovich** [comment]
![image](https://user-images.githubusercontent.com/63742797/232439476-6ef1140b-69b7-475d-bd09-6f3bf75441d1.png)

**Comment by revidovich** [comment]
переписала с условием для андроида -- нормально отобразилось.

**Comment by revidovich** [comment]
в кодсандбоксе у ребят нормально отображается, код 1-в-1, видимо дело именно в том, чтобы отрисовать во фрейме, внутри приложения вк

**Comment by revidovich** [comment]
пробовали без компонентов - проблема остаётся..  
![image](https://user-images.githubusercontent.com/63742797/232441318-60f6678c-0106-446b-b9c7-b71613573ea4.png)

**Comment by revidovich** [comment]
в приложении из маркета компоненты не отображаются, а на других платформах всё хорошо. мы делаем приложение на аутсорсе для вк, и у нас его не примут с этим багом, ребята, прошу помощи, я не знаю что это, подскажите

**Comment by SevereCloud** [comment]
> могу созвониться и показать код

Написал на рабочую почту

**Comment by revidovich** [comment]
> > могу созвониться и показать код
> 
> Написал на рабочую почту

я ответила там, либо можешь написать в телеграм https://t.me/revidovich
