### ISSUE TITLE
[Feature][CustomScrollView]: Не заменять стили полосы прокрутки для мобильных устройств

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#4756]
### Описание

Сейчас `CustomScrollView` полностью заменяет полосу прокрутки обернутого компонента, на мобильный устройствах взаимодействовать с ней невозможно - например на ios можно зажать полоску и подвинуть скролл в любое положение.
Предлагаю не заменять полосу прокрутки для мобильный устройств - добавить проверку по hasMouse.

Убирать обертку на стороне внешнего компонента не всегда удобно - придется дублировать стили для создания скролла в элемента.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.1" target="_blank">v6.0.1</a> 🎉
