### ISSUE TITLE
iOS SwipeBack работает при открытом modal у View

### ISSUE THREAD

**Issue by NOCELL** [VKCOM/VKUI#478]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/22259080/73184712-f2bc9380-412d-11ea-9097-72950b717f5b.gif)

**Comment by mahnunchik** [comment]
Ещё Swipe back срабатывает:

1) При откртом попапе https://vkcom.github.io/vkui-styleguide/#section-popouts
2) Поверх Slider https://vkcom.github.io/vkui-styleguide/#slider

**Comment by mahnunchik** [comment]
Скорее всего связано https://github.com/VKCOM/VKUI/issues/601

**Comment by inomdzhon** [comment]
Не воспроизводится

> [!NOTE]
> Версия на момент тестирования в [v6.7.4](https://github.com/VKCOM/VKUI/releases/tag/v6.7.4)
> <details><summary>Тестовая вёрстка</summary>
> <p>
>
> ```tsx
> import { useState, useCallback } from "react";
> import {
>   ModalRoot,
>   ModalPage,
>   ModalPageHeader,
>   Input,
>   Select,
>   Separator,
>   Group,
>   Panel,
>   PanelHeader,
>   SimpleCell,
>   SplitLayout,
>   SplitCol,
>   View,
> } from "@vkontakte/vkui";
> 
> export default function App() {
>   const [history, setHistory] = useState(["main"]);
>   const activePanel = history[history.length - 1];
> 
>   const go = useCallback((panel: string) => {
>     setHistory((prevHistory) => [...prevHistory, panel]);
>   }, []);
> 
>   const goBack = useCallback(() => {
>     setHistory((prevHistory) => prevHistory.slice(0, -1));
>   }, []);
> 
>   const [activeModal, setActiveModal] = useState(null);
> 
>   const modal = (
>     <ModalRoot
>       activeModal={activeModal}
>       onClose={() => {
>         setActiveModal(null);
>       }}
>     >
>       <ModalPage
>         id="modalPage"
>         header={<ModalPageHeader>Header</ModalPageHeader>}
>       >
>         <Group>
>           Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga
>           excepturi soluta at necessitatibus ex voluptate fugiat consectetur
>           vero ullam omnis dignissimos, accusantium praesentium nam a totam
>           optio iusto inventore placeat?
>         </Group>
>       </ModalPage>
>     </ModalRoot>
>   );
>   return (
>     <SplitLayout modal={modal}>
>       <SplitCol>
>         <View activePanel={activePanel} history={history} onSwipeBack={goBack}>
>           <Panel id="main">
>             <PanelHeader>VKUI</PanelHeader>
>             <Group>
>               <SimpleCell
>                 onClick={() => {
>                   go("profile");
>                 }}
>               >
>                 Hello
>               </SimpleCell>
>             </Group>
>           </Panel>
>           <Panel id="profile">
>             <PanelHeader>VKUI</PanelHeader>
>             <Group>
>               <SimpleCell
>                 onClick={() => {
>                   setActiveModal("modalPage");
>                 }}
>               >
>                 world
>               </SimpleCell>
>             </Group>
>           </Panel>
>         </View>
>       </SplitCol>
>     </SplitLayout>
>   );
> }
> ```
> 
> </p>
> </details>
