### ISSUE TITLE
[Bug][a11y][Badge]: Компонент недоступен для скринридеров

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#4783]
**Из аудита невизуальной доступности:**

> В принципе не могу понять, что это. Отображается для NVDA также, как простой кликабельный спан, но изображения, кажется, нет.

**Как исправить:**
- добавить дефолтный текст, доступный для скринридера (а-ля "Есть обновления")
- и дать возможность этот текст менять, конечно

**Comment by SevereCloud** [comment]
- closed by #6168
