### ISSUE TITLE
ModalPage: если выставить свойство settlingHeight={100}, контент скроллится только со второго раза.

### ISSUE THREAD

**Issue by kachemirova** [VKCOM/VKUI#480]
Если у ModalPage выставить свойство settlingHeight={100} (при этом контента на странице достаточно, чтобы был скролл), то после открытия этой модалки проскроллить контент получится только со второго раза, так как первая попытка проскроллить, видимо, воспринимается как раскрытие модалки на весь экран (хотя она и так уже раскрыта).

**Comment by fedorov-xyz** [comment]
Спасибо! Исправлено в версии `3.4.3`.
