### ISSUE TITLE
Обрезается текст если задать отрицательный marginBottom у InfoRow 

### ISSUE THREAD

**Issue by manaenckow** [VKCOM/VKUI#481]
Если задать отрицательный marginBottom у InfoRow, то текст внутри будет обрезаться. [https://sun9-67.userapi.com/c857536/v857536223/162b75/CN4dV4dbcFE.jpg](url)

**Comment by manaenckow** [comment]
Было бы не плохо, если значение InfoRow будет иметь свой класс, чтобы можно было задать ему стиль.

**Comment by ArthurStam** [comment]
Это не текст обрезается, это друг на друга `InfoRow` залезают из-за отрицательного `marginBottom`. То есть это не баг, это штатная работа CSS. Про класс — почти во все компоненты библиотеки можно прокидывать `className`, который будет вешаться на корневой элемент компонента.

**Comment by ArthurStam** [comment]
Тут 12 дней ничего не происходило, тикет закрываю.
