### ISSUE TITLE
[Bug][BREAKING CHANGE][ConfigProvider]: В режиме `embedded` класс с названием платформы (темы) добавляется на `body`

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#4810]
**Проблема:**

В режиме `mode="embedded"` класс с названием платформы (темы) добавляется все равно на `body`

**Как решить:**

Перенести навешивание класса из `ConfigProvider` в `AppRoot`.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
