### ISSUE TITLE
[Bug]: После открытия фокуса инпута контейнер приложения обрезается

### ISSUE THREAD

**Issue by flangapp** [VKCOM/VKUI#4822]
### Описание

На платформе m.vk.com на некоторых устройствах после фокуса на инпут и открытия клавиатуры, контейнер приложения обрезается на высоту клавиатуры.

### Версия

4.37.4

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

https://user-images.githubusercontent.com/105984772/231589241-116aa19b-da5c-4a8a-ba03-efaf6d1f56d8.mp4

**Comment by SevereCloud** [comment]
Баг миниаппов на m.vk.com, не vkui

**Comment by SevereCloud** [comment]
Duplicate of #1948
