### ISSUE TITLE
[Bug]: VK Music

### ISSUE THREAD

**Issue by assetkad** [VKCOM/VKUI#4847]
### Описание

Во время прослушивания мызыки во ВК, проигрывание стопится на треках, которые недоступны(видать из-за региона) и дальше плейер не играет музыку, хотя под недоступным треком еще есть доступные. Раньше проблемы такой не было, если плейер дошел до недоступного трека, то он просто его перешагивает, сейчас же, на нем все стопится, от слова вообще.

### Версия

то что в продакшане

### В каких браузерах воспроизводится проблема?

Chrome

**Comment by inomdzhon** [comment]
Привет, @assetkad

**VKUI** это библиотека компонентов.

По вопросам и проблемам **VK Music** тебе стоит создать запрос через эту форму https://vk.com/support?act=new&from=top ;)
