### ISSUE TITLE
ModalPage: игнорируется settlingHeight 

### ISSUE THREAD

**Issue by xpyctumo** [VKCOM/VKUI#485]
В **@vkontakte/vkui** версии _2.34.1_ игнорируется `settlingHeight` для установки высоты модалки. Тем самым, если контента внутри модалки много, то при разворачивании шапки будет налазить на системные кнопки в Mini Apps.

<img width="168" alt="image" src="https://user-images.githubusercontent.com/30053565/73483276-31fa1700-43b0-11ea-9f7b-ca19bee079c7.png">

ConfigProvider
```js
<ConfigProvider isWebView={true}>
```

Вырезка из кода...
```js
<ModalPage
    id="reviews"
    settlingHeight={60}
...
```

**Comment by fedorov-xyz** [comment]
Повторяется ли проблема на новой версии библиотеки? Если да, то фикс в любом случае будет только для неё.

**Comment by xpyctumo** [comment]
Актуально и в последней версии __3.0.2__.

**Comment by xpyctumo** [comment]
Хм. 

Проблема, похоже, кроется вот в этих вот строках: https://github.com/VKCOM/VKUI/blame/f0c07d1a78651e4db327c36c34eea57fbe549518/src/components/ModalRoot/ModalRoot.css#L36-L46

Получилось поправить у себя, пробросив, отступ самостоятельно.
```js
.ModalRoot__viewport {
    top: calc(var(--safe-area-inset-top) + var(--panelheader_height_ios)) !important;
}
```

**Comment by fedorov-xyz** [comment]
Тебе нужно указать
`<ConfigProvider isWebView={true} webviewType="vkapps">`

**Comment by xpyctumo** [comment]
Lol!
