### ISSUE TITLE
Нерабочая ссылка на чат в https://vkcom.github.io/vkui-styleguide/

### ISSUE THREAD

**Issue by khkjhjyu** [VKCOM/VKUI#488]
Ссылка на чат https://vk.me/join/AJQ1d8dLkgTUYRPPQ/Wa6Jmd нерабочая: https://sun1-28.userapi.com/0B86cO9IP1VFLxe5_jyO4Ux-Qi0bo9GBqfhL1g/-VchWItjGe0.jpg

**Comment by ArthurStam** [comment]
Привет! Да, вы правы, ссылка битая. Уберу её сейчас с сайта документации. За рабочей ссылкой обращайтесь в vk.me/vkappsdev
