### ISSUE TITLE
Улучшить описание в релизах.

### ISSUE THREAD

**Issue by deadit** [VKCOM/VKUI#489]
Привет!
Вышел релиз vkui 3. Хотелось бы вместо текста:
> Все изменения вы найдете тут: https://github.com/VKCOM/VKUI/releases, начиная с v3.0.0-alpha

Получить сразу список изменений, собранный с v3.0.0-alpha.

На примере реакта - есть версии предшествующие релизу 16.9.0, но как только вышла 16.9.0 тут же список чем отличается от предыдущей.
https://github.com/facebook/react/releases/tag/v16.9.0-rc.0
https://github.com/facebook/react/releases/tag/v16.9.0-alpha.0
https://github.com/facebook/react/releases/tag/v16.9.0

**Comment by ArthurStam** [comment]
Привет! Спасибо, сделаем.

**Comment by ArthurStam** [comment]
Собрал все изменения, начиная с первой alpha-версии: https://github.com/VKCOM/VKUI/releases/tag/v3.0.0

**Comment by deadit** [comment]
Спасибо!
