### ISSUE TITLE
[Bug]: Свойство RichCellProps.multiline не работает в модальном окне

### ISSUE THREAD

**Issue by quick6response** [VKCOM/VKUI#4899]
### Описание

Создаем модальное окно в которое помещаем группу и RichCell, в качестве пропса text = длинный текст, чтобы он перестал помещаться в рамку окна. Получаем поведение при котором содержимое не переносится, а уходит за край (прокурутки нет) 

### Версия

5.3.1

### В каких браузерах воспроизводится проблема?

Chrome, Safari, Yandex Browser

### Шаги воспроизведения

1. Модальное окно
2. Группа в нем
3. RichCell с содержимым text или children больше н символов (например 255)

### Ожидаемое поведение

Текст переносится по строкам, как это существует на страницах. 

### Скриншоты

![image](https://user-images.githubusercontent.com/64421792/233483907-7a05024d-e9e9-4ded-871d-58ef2a337a4b.png)

### Пример с воспроизведением

https://codesandbox.io/s/dreamy-brook-otozhu

**Comment by quick6response** [comment]
Такая же проблема с <MiniInfoCell
          before={<Icon24Link />}
          textWrap="full"
        />

**Comment by SevereCloud** [comment]
> Такая же проблема с `<MiniInfoCell before={} textWrap="full" />`

- #4979
