### ISSUE TITLE
Убрать лишнюю строку в релизе.

### ISSUE THREAD

**Issue by deadit** [VKCOM/VKUI#490]
Привет! 
https://github.com/VKCOM/VKUI/releases/tag/v3.0.0

Group автоматически вставляет Separator, эта строка не нужна - 
![image](https://user-images.githubusercontent.com/26635501/73739744-e2bd3900-4757-11ea-8573-c0797bef2676.png)

**Comment by ArthurStam** [comment]
Поправили, спасибо :)
