### ISSUE TITLE
Отсутствует css переменная header_text в Android теме

### ISSUE THREAD

**Issue by xpyctumo** [VKCOM/VKUI#491]
Для iOS применима css переменная _header_text_, однако, для Android будет применяться только _text_primary_, что будет затрагивать намного больше стилей в сервисе.

Всплыло на версии __3.0.2__

Рабочий костыль
```js
<PanelHeader><span style={{color: 'white'}}>ServiceName</span></PanelHeader>
```

**Comment by ArthurStam** [comment]
Привет. Смотрю вот [тут](https://vkcom.github.io/vkui-styleguide/#!/PanelHeader) — баг не воспроизводится при смене тем и платформ. Можешь прислать скриншот с багом?

**Comment by xpyctumo** [comment]
Переключаемся на iOS и видим это.
![image](https://user-images.githubusercontent.com/30053565/74741612-30649600-526e-11ea-8a33-8f28e5b465e4.png)

Затем на Android и повторяем процедуру поиска.
![image](https://user-images.githubusercontent.com/30053565/74741732-69046f80-526e-11ea-8c19-821b63a839a9.png)

При этом, если руками задать цвет переменной, то подсказка даёт ответ на всё.

![image](https://user-images.githubusercontent.com/30053565/74741840-98b37780-526e-11ea-9d2c-e50766818b27.png)

**Comment by ArthurStam** [comment]
Мне бы скриншот с багом, а не из девтулов

**Comment by ArthurStam** [comment]
У меня `header_text` ищется при обеих платформах

**Comment by xpyctumo** [comment]
```css
body[scheme="space_gray"] {
    --header_text: blue;
}
```

Данный стиль будет применяться только для iOS, не для Android.

iOS

![image](https://user-images.githubusercontent.com/30053565/74754793-39ac2d80-5283-11ea-8107-9be58baa5910.png)


Android
![image](https://user-images.githubusercontent.com/30053565/74754737-1f724f80-5283-11ea-84d0-e1a4bf1d5cbf.png)

**Comment by ArthurStam** [comment]
Спасибо!
