### ISSUE TITLE
Отображение контента в компоненте PanelHeader vkminiapps

### ISSUE THREAD

**Issue by deadit** [VKCOM/VKUI#492]
Привет.

При обновлении vkui на 3 версию, из-за того что приложение vkminiapps (кнопки справа всегда есть), заголовок улетает влево в компоненте PanelHeader. Получается, что где-то, где кнопка слева есть, он по центру, где-то, где кнопки слева нету, он влево улетает. Пофиксите, пожалуйста.

<img width="374" alt="Снимок экрана 2020-02-05 в 11 49 10" src="https://user-images.githubusercontent.com/26635501/73834426-bb7c6f80-481c-11ea-8ec5-a4f7727bcf13.png">
<img width="1440" alt="Снимок экрана 2020-02-05 в 11 50 23" src="https://user-images.githubusercontent.com/26635501/73834358-9e47a100-481c-11ea-9217-6eb8b5cb0578.png">
<img width="366" alt="Снимок экрана 2020-02-05 в 11 53 07" src="https://user-images.githubusercontent.com/26635501/73834343-9556cf80-481c-11ea-87c3-f63f9e83c78b.png">

**Comment by deadit** [comment]
Если удалить элемент PanelHeaderContent__width то все становится нормальным.

**Comment by ArthurStam** [comment]
Привет, спасибо, чекнем.

**Comment by ArthurStam** [comment]
Пофикшено в 3.3.2
