### ISSUE TITLE
[Docs][a11y][Button]: Исправить примеры кнопок в Storybook

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#4929]
**Из аудита невизуальной доступности**

`Button`:
> В основном демо и во втором есть неподписанные кнопки, возможно они с изображениями?
> Подписаны только Button и Button (stretched).

`IconButton`:
> Нет текста, соответственно роль img тоже не объявляется скринридеру. Сейчас пустая кнопка без подписи.

-----
**Как исправить:**

Подписать кнопки в примерах.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.2" target="_blank">v6.0.2</a> 🎉
