### ISSUE TITLE
Роутер для VK Mini Apps

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#493]
Подымаю вопрос [второй раз](https://github.com/VKCOM/VKUI/issues/232). В прошлый раз @ArthurStam закрыл ишью как выходящее за рамки VKUI. В настоящее время VKUI вырос и может иметь тройную вложенность вью `<Epic><Root><View><Panel>`, помимо алертов и модалок.

**Фичревест:** Роутер подходящий для работы со структурой`<Epic><Root><View><Panel>` и алертами/модалками  VKUI (или созданный специально для VKUI).

---

@ArthurStam рекомендовал к использованию router5. Для простой структуры он отлично подходит, но на алертах/модалках и [Preventing navigation](https://router5.js.org/advanced/preventing-navigation) модуль увы не вывозит Android back button. А попытки восстановить историю браузера не ломая сам router5 становятся слишком сложными и неподдерживаемыми.

---

Также наткнулся на реализацию роутера для VKUI вот проекте тут https://github.com/iSa1vatore/vk-mini-app-boilerplate/ (мотороллер не мой). 

В подходе поддерживается навигация по всей структуре `<Epic><Root><View><Panel>`, истории модалок и алертов, а также действие назад, даже по iOS swipe back и Android back button.

---

В общем, было бы здорово иметь модуль роутера подходящий для приложений активно использующих VKUI. Возможно, авторы VKUI могут подсказать как улучшить подход [vk-mini-app-boilerplate](https://github.com/iSa1vatore/vk-mini-app-boilerplate/) до состояния полноценного роутера.

**Comment by mahnunchik** [comment]
Возможно этот тикет будет интересен @mmarkelov и @iSa1vatore

**Comment by MrZillaGold** [comment]
Чем не устраивает https://github.com/hit2hat/vkui-navigator?

**Comment by ArthurStam** [comment]
Привет, спасибо, подумаем

**Comment by mahnunchik** [comment]
Хочу попросить команду VKUI потыкать вот это приложение https://vk.com/app7333418

Если логика переходов по вью, панелям, табам и модалкам соответсвует предполагаемой логике VK Mini Apps, то готов выложить роутер как модуль.

**Comment by ArthurStam** [comment]
Подумали, что тащить роутер в либу не будем. Мы не хотим, чтобы библиотека диктовала то, как должен быть устроен роутинг.

**Comment by mahnunchik** [comment]
@ArthurStam никто не говорил про тащить роутер **в** либу.

**Comment by NekR** [comment]
Привет. Следите за репозиторием: https://github.com/VKCOM/vk-router

Позже появится документация и рекомендации по интеграции с VKUI.
