### ISSUE TITLE
[Enhancement][a11y][Tabs]: Добавить возможность навигироваться по табам через ArrowUp/ArrowDown

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#4936]
**Рекомендации после аудита невизуальной доступности:**
> Кроме того, желательно давать возможность навигироваться по вкладкам еще и стрелками вверх/вниз. Вниз = вправо, вверх = влево.

Сейчас навигироваться можно только стрелочками влево-вправо.

**В чем может быть подвох?**

Сейчас в коде есть комментарий на тему стрелочки вниз и следующая логика:
https://github.com/VKCOM/VKUI/blob/6721eff968c9e03b5bc38556aa82e74c619b688a/packages/vkui/src/components/Tabs/Tabs.tsx#L95-L123

Надо обдумать, как это совместить.

**Comment by inomdzhon** [comment]
По W3C `ArrowUp`/`ArrowDown` должны работать при `aria-orientation="vertical"`, а при `aria-orientation="horizontal"` надо переключать на `ArrowLeft`/`ArrowRight`.

<img width="320" src="https://github.com/VKCOM/VKUI/assets/5850354/1506ecc1-674c-4a18-a83c-5c311b8422eb" />

_https://www.w3.org/WAI/ARIA/apg/patterns/tabs/_

Т.к. у нас нет вертикального расположения табов, предлагаю задачу на текущий момент закрыть

### Дополнительные ссылки

- https://mui.com/material-ui/react-tabs/
