### ISSUE TITLE
Одновременное отображение алерта и модалки

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#495]
Библиотека позволяет одновременно отобразить `popout` и `modal`. В настоящее время модалки показываются выше алертов.

![image](https://user-images.githubusercontent.com/780935/74152994-33310c80-4c18-11ea-863e-6b468e7844a5.png)

По логике вещей алерты должны быть показаны выше модалок: подтверждение, ScreenSpinner и Snackbar. Или текущие поведение следует указать в документации.

**Comment by ArthurStam** [comment]
Спасибо, пофиксим

**Comment by mahnunchik** [comment]
Как вариант, запретить одновременный показ `popout` и `modal`. Snackbar поверх модалки — очень странно. Но это уже больше вопрос к архитектуре библиотеки.

**Comment by ArthurStam** [comment]
Теперь `p`opout находится выше `modal`. Доступно с 3.3.4
