### ISSUE TITLE
[Feature]: Улучшить компонент Snackbar

### ISSUE THREAD

**Issue by Zaycevq** [VKCOM/VKUI#4951]
### Описание

Добавляем новые свойства и корректируем визуал.

Помогает с этим дизайнер [Вадим Казанцев](https://vk.com/vadimguaje), есть его наброски тут: https://vk.cc/cnhFFY

– Включать режим без фиксированной ширины Snackbar'а
– Добавить возможность включать button-icon справа

<img width="329" alt="update-snack" src="https://user-images.githubusercontent.com/91548592/234841154-3889be5b-8a87-4b6a-8afb-3374a79c609b.png">

**Comment by SevereCloud** [comment]
Когда будет новый дизайн, то можно переоткрыть
