### ISSUE TITLE
[Feature]: Кнопка «Show More» для завершения HorizontalScroll

### ISSUE THREAD

**Issue by Zaycevq** [VKCOM/VKUI#4952]
### Описание

Добавляем кнопку для открытия всего списка, когда завершается HorizontalScroll. Компонент отрисован командой Маркета. Нужно доработать состояния и проверить токены, также подготовить задачу для разработки.

<img width="851" alt="show-more-scr" src="https://user-images.githubusercontent.com/91548592/234842060-9224a9a0-f8d9-44b0-97f7-4c972bfb562a.png">

**Comment by inomdzhon** [comment]
Duplicate of #5328
