### ISSUE TITLE
[Bug]: ModalRoot застревает в состоянии switching

### ISSUE THREAD

**Issue by oskemarkup** [VKCOM/VKUI#4954]
### Описание

Если открыть модальное окно асинхронно, то в webview андроида (например, в мини-аппе) модальное окно застревает в состоянии 'switching' и не закрывается по тапу на оверлей. 

### Версия

5.3.0

### В каких браузерах воспроизводится проблема?

Другое (укажите в описании)

### Скриншоты

<img width="320" alt="image" src="https://user-images.githubusercontent.com/4083991/234849481-8de65798-8086-4885-b212-172748c18198.png">

### Пример с воспроизведением

[codesandbox](https://codesandbox.io/s/elastic-leftpad-u7txvy?file=/src/App.js)
[mini-app для воспроизведения бага на устройстве](https://vk.com/app51625864)

**Comment by inomdzhon** [comment]
Не воспроизводится

> [!NOTE]
> Версия на момент тестирования в [v6.7.4](https://github.com/VKCOM/VKUI/releases/tag/v6.7.4)
