### ISSUE TITLE
[Doc]: Ломается наполнение разделов после ввода в строку поиска "Header"

### ISSUE THREAD

**Issue by quick6response** [VKCOM/VKUI#4963]
**Версия:** >= 5.4.0

### Описание

Переходим на сайт и вводим в поиск необходимый компонент

![image](https://user-images.githubusercontent.com/64421792/235262205-c9473137-d2e5-47b2-80c6-4e00a4eaea2c.png)

**Comment by inomdzhon** [comment]
Спасибо за issue 🙏 

Обнаружил, что бага связана с PR #4808, проблема из-за установки `displayName`

```
PanelHeaderContent.displayName = 'PanelHeaderContent';
```

Из-за чего создаётся коллизия с уже существующим компонентом `PanelHeaderContent`. При этом только в `production` сборке 🤔 

Поправим.
