### ISSUE TITLE
[Feature]: Научиться сохранять скролл блоков с overflow scroll при возврате к предыдущей панели

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#4980]
### Описание

**Предусловие**

Имеется приложение со структурой

```
View
  Panel1 (тут бокс с overflow scroll)
  Panel2
```

На Panel1 размещен блок с `oveflow: scroll` (это может быть кастомный элемент, или, например, VKUI `HorizontalScroll`). Также на Panel1 есть возможность перейти к Panel2 (более вложенная внутри View), а на панели Panel2 есть возможность вернуться обратно к Panel1.

**Шаги**
```
1. Panel1 
2. Поскроллили блок внутри Panel1
3. Переход к Panel2 
4. возврат на Panel1
```

**Фактический результат**
Скролл блока внутри Panel1 не сохранился

**Feature Request:** Хочется научиться сохранять положение бокса с `oveflow: scroll` внутри предыдущей панели. Чтобы при возврате к ней позиция скролла в дочернем боксе восстанавливалась. 

**Комментарий**
Сделать это можно, предоставив пользователям некий ```VKUI ScrollBox```, который будет иметь в себе механизм сохранения скролла в зависимости от перехода между панелями и вью (можно опереться на логику, как мы понимаем, какую анимацию рисовать: открытия или закрытия панели или вью)

**Комментарий 2**

Хотелось бы так же уметь восстанавливать скролл бокса при возврате к панели, размещенной в другой вью.

```
ViewА
  PanelА1 (тут бокс с overflow scroll)
ViewB
  PanelB1
```

**Comment by inomdzhon** [comment]
Duplicate of #3750
