### ISSUE TITLE
[Bug][a11y][Image]: Отсутствует альтернативный текст

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#4987]
**Из аудита невизуальной доступности:**

> Нет текста, соответственно роль img тоже не объявляется скринридеру.

Дополнительная проблему у `ImageBase.Overlay`:

> Сейчас пустая кнопка без подписи.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.2" target="_blank">v6.0.2</a> 🎉
