### ISSUE TITLE
Заголовок в PanelHeader при отсутствии TT Commons слишком большой и жирный

### ISSUE THREAD

**Issue by Lihachyov** [VKCOM/VKUI#499]
При отсутствии TT Commons сейчас есть две проблемы:
1. Заголовок слишком жирный — нужно поправить font-weight на 600 (Semibold/Demibold). Сейчас 800 — это heavy, то есть он толще чем Bold, именно поэтому заголовок настолько жирный 
2. Заголовок большеват. В идеале применять размер шрифта 20 px, а line-height 24 px в случае, если нет TT Commons.

**Comment by wayshev** [comment]
Всё ещё актуально.

Но для VK Sans размеры 21/26, а не 20/24

**Comment by pfrankov** [comment]
Отказываемся от TT Commons
Похоже на https://github.com/VKCOM/VKUI/issues/2217
