### ISSUE TITLE
[Bug]: Select: не вызывается onChange там где ожидается

### ISSUE THREAD

**Issue by alexpach63** [VKCOM/VKUI#5010]
### Описание

компонент Select
Прокидываем ему options, onChange и value
Если при выборе опции в onChange мы не изменили value - то следующий тап по этому же опшену не вызывает onChange event

### Версия

5.2.3

### Ожидаемое поведение

Многогратный тап по конкретному опшену вызывает onChange событие если мы не прокидываем новое value от этого пропа в Select

**Comment by mendrew** [comment]
@inomdzhon возьму в работу.
