### ISSUE TITLE
[Docs][a11y][WriteBar]: Исправить пример в Storybook

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#5013]
**Из аудита невизуальной доступности:**
> Если все кнопки, в том числе для прикрепления аттача, не должны нажиматься, то все ок.

**Comment by mendrew** [comment]
> Если все кнопки, в том числе для прикрепления аттача, не должны нажиматься, то все ок.

В целом так и есть, у всех кнопок-иконок проставлены лэйблы, особенно благодаря [WriteBarIcon](https://vkcom.github.io/VKUI/#/WriteBarIcon), а события по нажатию именно в примере быть не должно, разве что какого-нибудь рафинированного.
Предлагаю пока что в Storybook проставить noop в onClick у WriteBarIcon, чтобы они были кликабельными, и всё на этом.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.5.1" target="_blank">v6.5.1</a> 🎉
