### ISSUE TITLE
[Bug][a11y][Calendar]: Доступность `Calendar` и `CalendarRange`

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#5018]
**Из аудита невизуальной доступности:**

> Между кнопками предыдущего и следующего месяца есть два элемента, читаемые скринридером как "по щелчку". Обычно это спаны с онкликом. В коде я не разобрался, там очень много пустых `<span aria-hidden="true">`, обнуления ролей у и так текстовых элементов `<div role="presentation">` и использование `aria-label` на текстовых блоках, из-за чего метки не озвучиваются.
> Все кнопки не доступны для фокусирования с клавиатуры, а из-за того, что `tabindex` есть у некоторых пустых элементов, табордер ломается в принципе наглухо.
> Кроме того, все дни недели нужно поместить в таблицу для упрощения навигации.

**Comment by SevereCloud** [comment]
Этими элементами были CustomSelect

- closed by #3547
