### ISSUE TITLE
[Docs][a11y][CustomSelectOption]: Исправить пример в Storybook

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#5021]
**Из аудита невизуальной доступности:**

> Отображается такой текст. Так и должно быть?
>
> Игорь Федоров
> Россия, Санкт-Петербург

Кажется, что все хорошо, но из примера получается неочевидно, так ли это.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.2" target="_blank">v6.0.2</a> 🎉
