### ISSUE TITLE
[Bug]: ChipsSelect. Некорректная высота саджестов при открытии сверху

### ISSUE THREAD

**Issue by Betchika99** [VKCOM/VKUI#5039]
### Описание

При использовании ChipsSelect в нижней части вьюпорта некорректно высчитывается отступ для саджестов, появляющихся сверху. В момент установки фокуса в инпут отступ корректный (данных в саджестах много), но при вводе редко встречающегося символа (для которого будет 1-2 саджеста) высота саджестов остается той же самой, поэтому появляется "дырка" между ними и инпутом. 

Детальнее описала ниже с видео и песочницей.

Предполагаю, что дело в высчитывании inline-стиля "inset" через JS.

Стабильно ловим в случаях, когда инпут находится в нижней части вьюпорта.

### Версия

latest (у нас в проекте 5.2.3, но на 5.4.1 в песочнице тоже воспроизводится)

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

1) поместить компонент вниз вьюпорта, чтобы саджесты открывались сверху от инпута
2) ввести в инпут символ, для которого будет один саджест

### Ожидаемое поведение

саджест открывается прямо над инпутом

### Скриншоты

Видео, как воспроизводится: https://cloud.mail.ru/public/uPop/KCXN7pUR2

### Пример с воспроизведением

Песочница: https://codesandbox.io/s/quizzical-yalow-7svoec

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.1" target="_blank">v5.10.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.1" target="_blank">v6.0.1</a> 🎉
