### ISSUE TITLE
Не работает SwipeBack, если свайпать находясь на элементе iframe

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#504]
1. Создаем панель вида:
<img width="809" alt="Снимок экрана 2020-02-16 в 18 18 22" src="https://user-images.githubusercontent.com/45998835/74607286-c373c380-50e8-11ea-9ab7-784ff81b9e30.png">
2. Добавляем все элементы для работы onSwipeBack.
3. Тянем в области с iframe.

Свайп не работает, возможно оттянуть только за separator у PanelHeader

**Comment by ArthurStam** [comment]
Привет. Мы не можем ловить события, которые происходят внутри iframe. Точнее, не мы не можем, а браузер. Это его политика безопасности. Жесты внутри фреймов не всплывают выше `<iframe />`

**Comment by ilyapishchulin** [comment]
Понял
