### ISSUE TITLE
SelectMimicry и tsx

### ISSUE THREAD

**Issue by FireworksX** [VKCOM/VKUI#505]
В интерфейсе SelectMimicryProps нет поля top. При использовании данного свойства ошибка компиляции. При использовании js всё работает, реализация есть и типа нет.
<img width="1187" alt="Снимок экрана 2020-02-16 в 23 19 16" src="https://user-images.githubusercontent.com/22668125/74612048-ca173080-5112-11ea-97f7-7eacaae8cc1b.png">

**Comment by ArthurStam** [comment]
Привет. Спасибо, поправим в ближайшей версии.

**Comment by ArthurStam** [comment]
Поправлено в `3.3.0`
