### ISSUE TITLE
[Feature][Slider]: разработать состояния `hover` и `active`

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#5050]
### Описание

Сейчас не хватает состояний `hover` и `active`. В PR #4961 пока сделал так, что для состояния `active` используется состояние `focus` (см. **Видео 1**).

#### Дизайн

- [ ] Добавить состояние `hover` (для `web`)
- [ ] Добавить состояние `active` (для `web`/`mobile`)
- [ ] Продумать поведение, когда пользователь нажимает на шкалу (см. **Видео 2**). Учесть `web` и `mobile`.

### Примечание

<details><summary>Видео 1</summary>

https://github.com/VKCOM/VKUI/assets/5850354/adb7c9e6-0b03-4ee3-b750-7e8b4e91b3ad
</details>

<details><summary>Видео 2</summary>

https://github.com/VKCOM/VKUI/assets/5850354/84ae51c0-9a87-460f-95f4-aa27082c0e3b
</details>

---

- related #4961

**Comment by qurle** [comment]
Как вариант — оставить обводку только для `focus`, а для `hover` и `active` использовать генерируемые токены: `color_background_contrast--hover` и `color_background_contrast--active` + `transition` на цвета.

При нажатии на шкалу — перемещение слайдера и изменение цвета на `color_background_contrast--active`.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.0" target="_blank">v6.2.0</a> 🎉
