### ISSUE TITLE
[Feature]: Добавить свойство appearance для Progress

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#5067]
### Описание

Необходимо добавить свойство `appearance` для компонента Progress

### Скриншоты

<img width="605" alt="image" src="https://github.com/VKCOM/VKUI/assets/14944123/7ad1ba5c-40a3-4eb1-96bb-63f11b71c6ae">

**Comment by Fliqle** [comment]
@SevereCloud в библиотеке добавил
