### ISSUE TITLE
Как сделать так чтобы Header не прилипал к статус бар и сливался с основным цветом?

### ISSUE THREAD

**Issue by nikitabudkovskiy** [VKCOM/VKUI#507]
Здравствуйте, столкнулся с такой проблемой, разрабатываю приложение, столкнулся с такой проблемой, что на Androud header не берется цвет от родителя, то есть статус бар постоянно синего цвета, а на IOS шапка едет: 

![image](https://user-images.githubusercontent.com/7972703/74735431-2345a800-526a-11ea-862b-855f4c5c3966.png)

Не подскажете, как это решить?

Вот непонятно, как сделать так, чтобы статус-бар на Android брал цвет header
На IOS такой беды нет
![image](https://user-images.githubusercontent.com/7972703/74722778-ef12bd00-5252-11ea-8117-84a2620ecd14.png)
![image](https://user-images.githubusercontent.com/7972703/74722805-f76af800-5252-11ea-8222-9d4d08fd0baf.png)

Вот ссылка на приложение: https://vk.com/app7244237_122457137

P.S Не использую нативный компоненты

**Comment by ArthurStam** [comment]
Привет, я ничего не понял :(

**Comment by nikitabudkovskiy** [comment]
Привет, теперь вроде понятно объяснил)

**Comment by xpyctumo** [comment]
Для этого есть событие VK Connect. 

https://vk.com/dev/vk_connect_events_10?f=Работа%20со%20статус-%20и%20экшн-баром

`connect.send("VKWebAppSetViewSettings", {"status_bar_style": "dark", "action_bar_color": "#fff"}); `

**Comment by ArthurStam** [comment]
Про съезжающую шапку на iOS: https://vkcom.github.io/vkui-styleguide/#!/HTML
