### ISSUE TITLE
В PanelHeader и PanelHeaderSimple едет верстка у кнопок, если поставить несколько штук

### ISSUE THREAD

**Issue by drago-v** [VKCOM/VKUI#511]
В документации указано, что можно сделать в хедере несколько кнопок, для этого нужно передать в left или right массив из PanelHeaderButton

Если так сделать, то у кнопок ломается выравнивание и они ставятся вертикально.

![image](https://user-images.githubusercontent.com/20705877/74681300-1b3b2900-51d4-11ea-99bc-d6e6cedd0980.png)

![image](https://user-images.githubusercontent.com/20705877/74681282-0eb6d080-51d4-11ea-830f-d201205e5214.png)

**Comment by ArthurStam** [comment]
Привет. Слева не допускается несколько иконок. Справа сейчас они становятся в один ряд, но там есть баг с отступами. Поправлю его в ближайшее время.

**Comment by ArthurStam** [comment]
Привет, спасибо, поправим :)

**Comment by ArthurStam** [comment]
Пофикшено в 3.3.2
