### ISSUE TITLE
[Feature]: Заменить реврайт font-size и line-height на css переменные для TabbarItem

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#5166]
### Описание

В компоненте `TabbarItem` свойства реврайтятся напрямую, а не через реврайт переменных, предлагаю это импрувнуть

https://github.com/VKCOM/VKUI/blob/d755f81394250c074e1047a8bfd1cf048e90c191/packages/vkui/src/components/TabbarItem/TabbarItem.module.css#L72-L73

**Comment by inomdzhon** [comment]
issue закрыл https://vk.com/scffs (@scffs)
