### ISSUE TITLE
ModalPage в отдельном компоненте

### ISSUE THREAD

**Issue by FireworksX** [VKCOM/VKUI#519]
Когда я создаю ModalPage сразу внутри ModalRoot всё ОК! Но когда много этих модалок, то появляется желание разделить на компоненты, но появляется проблема с закрытием окна
<img width="1133" alt="Снимок экрана 2020-02-18 в 23 03 19" src="https://user-images.githubusercontent.com/22668125/74773448-f2359980-52a2-11ea-990f-647c692fd10c.png">
В компонент прокидываю метод для закрытия модалки
В самом компоненте
<img width="1210" alt="Снимок экрана 2020-02-18 в 23 04 49" src="https://user-images.githubusercontent.com/22668125/74773566-2a3cdc80-52a3-11ea-9736-218f048b5996.png">
Когда я кликаю на "готово", то всё окей, а когда на пустую область возникает ошибка
<img width="759" alt="Снимок экрана 2020-02-18 в 23 05 53" src="https://user-images.githubusercontent.com/22668125/74773763-961f4500-52a3-11ea-849b-3ccea8d5f452.png">

<img width="1226" alt="Снимок экрана 2020-02-18 в 23 07 48" src="https://user-images.githubusercontent.com/22668125/74773743-856ecf00-52a3-11ea-97b8-758634280e7e.png">

**Comment by ArthurStam** [comment]
Привет. Вот такой код у меня не вызывает ошибок. Уверен, что нигде не теряешь `this`?

```jsx
import { ModalRoot } from '@vkontakte/vkui';

...

<ModalRoot activeModal={this.state.activeModal}>
  <MyModalCard onClose={this.onModalClose} id="my-modal-card" />
</ModalRoot>
```

MyModalRoot:

```jsx
import { ModalCard } from '@vkontakte/vkui';

...

<ModalCard onClose={this.props.onClose} id={this.props.id} />
```

**Comment by FireworksX** [comment]
Я тоже подумал что this потерял, но если в метод написать alert и попробовать закрыть, то алерт не выведется, значит и до моего метода не доходит
<img width="1123" alt="Снимок экрана 2020-02-18 в 23 51 54" src="https://user-images.githubusercontent.com/22668125/74777121-e7323780-52a9-11ea-9d24-bf0480d1b211.png">

**Comment by ArthurStam** [comment]
Можешь форкнуться https://codesandbox.io/s/vkui-boilerplate-oj149 и набросать пример, где будет воспроизводиться ошибка?

**Comment by FireworksX** [comment]
Набросал https://codesandbox.io/embed/vkui-boilerplate-9lh48?fontsize=14&hidenavigation=1&theme=dark
Но я похоже понял в чём проблема, когда я прокидываю props в мой компонент, я его называю **close**, и внутри компонента я его прокидываю в **onClose**, нужно чтобы метод назывался не close, а onClose когда я импортирую свой компонент, не совсем явная ошибка
<img width="1249" alt="Снимок экрана 2020-02-19 в 00 12 45" src="https://user-images.githubusercontent.com/22668125/74778421-9839d180-52ac-11ea-9c70-c2546697b2e8.png">

**Comment by ArthurStam** [comment]
Да, всё так) ModalRoot читает свойства дочернего компонента и ждет, что оно будет названо определенным образом. Согласен, что неочевидно. Подумаем, что можно с этим сделать.
