### ISSUE TITLE
[Bug][View] При свайпбеке нет тени (WebView, iOS)

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#5194]
При свайпбеке на iOS нет затемнения нижней панели 

ОР|ФР
-|-
![image](https://github.com/VKCOM/VKUI/assets/7431217/c1943771-1d21-4436-a333-9270f53d01dd)|![image](https://github.com/VKCOM/VKUI/assets/7431217/298e7292-a960-46f5-86d9-3cb09e20337e)

**Comment by shevchux** [comment]
Не хватает затемнения нижней панели. 

Тень вдоль левой границы верхней панели лишняя.

Обратите внимание, пожалуйста, на нативные приложения.

**Comment by shevchux** [comment]
Так же нужно свериться с областью экрана, которая инициирут свайпэк. Сейчас это левые 70 пикселей экрана.

Обратите внимание, пожалуйста, на нативное приложение ВКонтакте. В нем можно инициировать свайпэк в любой области экрана. Это входит в привычку использования ВКонтакте, но в мини-приложениях навигироваться сложнее.
