### ISSUE TITLE
[Bug]: Индикатор скролла ModalPage не учитывает нижний инсет

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#5205]
### Описание

Индикатор скролла ModalPage не учитывает --vkui_internal--safe_area_inset_bottom. Контент виден нормально, но скролл уходит ниже. Как будто для блока с overflow: auto требуется не внутренний, а внешний отступ.

Смотреть через мини-приложение внутри клиента ВКонтакте. Именно там передаются инсеты. Удобнее в интернал приложении (например поиск артистов в ред профиля в VK Знакомства).

### Версия

5.4.3

### В каких браузерах воспроизводится проблема?

Safari

### Скриншоты

https://github.com/VKCOM/VKUI/assets/22776192/33955a89-d0f1-4110-b2b6-c019a68aa523

**Comment by inomdzhon** [comment]
Duplicate of #5604
