### ISSUE TITLE
Используется includes без полифила 

### ISSUE THREAD

**Issue by kachemirova** [VKCOM/VKUI#521]
https://github.com/VKCOM/VKUI/blob/77aa1189300a45c5790a64d1c2a09a64ea04fc5d/src/components/Root/Root.tsx#L162
https://github.com/VKCOM/VKUI/blob/77aa1189300a45c5790a64d1c2a09a64ea04fc5d/src/components/Root/Root.tsx#L133

Из-за этого ломается на старых андроидах
<img width="706" alt="Снимок экрана 2020-02-20 в 10 43 23" src="https://user-images.githubusercontent.com/14996653/74911560-e5619480-53cd-11ea-8c47-fc4a3b96501a.png">

**Comment by ArthurStam** [comment]
Спасибо, исправим в ближайшем релизе

**Comment by ArthurStam** [comment]
Пофикшено в 3.3.5
