### ISSUE TITLE
[Bug]: Поправить логику включения user-select: none

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#5216]
### Описание

Одна из особеннойстей библиотеки — мимикрия под натив в оболочке WebView (именно в оболочке вебвью). В нативе обычно не приятно давать пользователю возможность выделять текст базового интерфейса. Такая реализация есть в коде. Но тем не менее встречаются неточности

1. На Pixel 7 , Android 13 получается выделять
https://bugs.chromium.org/p/chromium/issues/detail?id=1384181

2. Вне вебвью выделение текста тоже недоступно. Например мини-приложение внутри mvk. Там выделение должно остаться -- не стоит задача мимикрии под натив. Если посмотреть большинство сайтов (и даже разделов mvk), выделение там присутствует.

3. Пожалуйста, просится старый известный фикс https://github.com/VKCOM/VKUI/issues/3507

### Версия

5.5.0

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.0" target="_blank">v6.2.0</a> 🎉
