### ISSUE TITLE
[Doc]: обновить пример кода в быстром старте

### ISSUE THREAD

**Issue by scffs** [VKCOM/VKUI#5217]
### Описание

Сейчас [там](https://vkcom.github.io/VKUI/#/QuickStart) пример с `ReactDOM.render`, но этот метод больше не поддерживается и [офф. дока](https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis) React рекомендует перейти на `createRoot`

Пример обновленного кода:

```jsx
import {
    AdaptivityProvider,
    AppRoot,
    ConfigProvider, Group, Header,
    Panel,
    PanelHeader, SimpleCell,
    SplitCol,
    SplitLayout,
    View,
} from '@vkontakte/vkui';
import '@vkontakte/vkui/dist/vkui.css';
import { createRoot } from 'react-dom/client';
import App from './App';
import React from "react";

const App = () => {
    return (
        <AppRoot>
            <SplitLayout header={<PanelHeader separator={false} />}>
                <SplitCol autoSpaced>
                    <View activePanel='main'>
                        <Panel id='main'>
                            <PanelHeader>VKUI</PanelHeader>
                            <Group header={<Header mode="secondary">Items</Header>}>
                                <SimpleCell>Hello</SimpleCell>
                                <SimpleCell>World</SimpleCell>
                            </Group>
                        </Panel>
                    </View>
                </SplitCol>
            </SplitLayout>
        </AppRoot>
    );
};

createRoot(document.getElementById('root')).render(
    <ConfigProvider>
        <AdaptivityProvider>
            <App />
        </AdaptivityProvider>
    </ConfigProvider>
);
```

UPD.
В том же быстром старте старая ссылка на доку, которая больше не обновляется

![image](https://github.com/VKCOM/VKUI/assets/67464545/f913beb9-52a6-4b60-9121-403abaa98f09)

**Comment by scffs** [comment]
А этот метод есть в 17-ой версии? Если нет, то придется доку тоже обновить, что теперь реакт от 18-ой версии нужен

**Comment by inomdzhon** [comment]
> А этот метод есть в 17-ой версии?

Нет, в 17 версии этого метода нет

>  Если нет, то придется доку тоже обновить, что теперь реакт от 18-ой версии нужен

Необязательно, VKUI требует React 17 или React 18. Пользователь с React 17 сам адаптирует пример под свою версию

**Comment by inomdzhon** [comment]
> > Необязательно, VKUI требует React 17 или React 18. Пользователь с React 17 сам адаптирует пример под свою версию
> 
> Просто если человек возьмёт код из примера в свой проект, но у него 17 версия, то будет ошибка. Может стоит дописать, что код из примера актуален для 18-ой версии?

Хм, и в правду, не каждый сразу сможет понять причину в чём ошибка

@SevereCloud допишешь плиз про React 18 в PR? 🙏

**Comment by SevereCloud** [comment]
А давайте оставим пока как есть, пока не поднимим минимальную версию реакта до 18. Сейчас при использовании текущего кода и 18 реакта, пользователю прилетит варнинг с инструкцией как правильно переписать код

**Comment by inomdzhon** [comment]
Резоно, тогда issue закрою до поры времени

**Reason** https://github.com/VKCOM/VKUI/issues/5217#issuecomment-1592732184
