### ISSUE TITLE
[Feature]: Научить Gradient менять цвет при смене Light / Dark темы

### ISSUE THREAD

**Issue by Zaycevq** [VKCOM/VKUI#5218]
### Описание

Сейчас компонент не умеет менять цвет когда переключается тема оформления Light / Dark.
Нужно добавить варианты токенов которые в светлой теме дают White градиент, а в тёмной оттенок серого  (background_content)

Кейсы где это требуется:
<img width="1998" alt="vkZnk" src="https://github.com/VKCOM/VKUI/assets/91548592/3b04fa89-b8f7-4890-aaa8-c5dbecea8e35">
<img width="1000" alt="showMore" src="https://github.com/VKCOM/VKUI/assets/91548592/fe80bb68-cd12-4b1b-9302-2448aca9ff0b">

**Comment by smirnova-o** [comment]
Убираем градиенты Black и White, вместо них оставляем просто Gradient (всего будет два: Gradient и Gradient_tint):
— Gradient переключается в светлой теме на оттенки белого, в темной - на оттенки background_content
— Gradient_tint остается без изменений
— формула градиента остается без изменений, меняются только цветовые значения


**Light**
--vkui--gradient:
hsla(0,0%,100%,0) 0%,
hsla(0,0%,100%,.036) 13%,
hsla(0,0%,100%,.15) 27%,
hsla(0,0%,100%,.79) 68%,
hsla(0,0%,100%,.95) 84%,
#fff 100%;

--vkui--gradient_tint:
hsla(0,0%,98%,0) 0%,
hsla(0,0%,98%,.036) 13%,
hsla(0,0%,98%,.15) 27%,
hsla(0,0%,98%,.79) 68%,
hsla(0,0%,98%,.95) 84%,
#f9f9f9 100%;

**Dark**
--vkui--gradient:
transparent 0%,
rgba(25,25,26,.014) 13%,
rgba(25,25,26,.06) 27%,
rgba(25,25,26,.316) 68%,
rgba(25,25,26,.38) 84%,
rgba(25,25,26,.4) 100%;

--vkui--gradient_tint:
rgba(32,32,33,0) 0%,
rgba(32,32,33,.036) 13%,
rgba(32,32,33,.15) 27%,
rgba(32,32,33,.79) 68%,
rgba(32,32,33,.95) 84%,
#202021 100%;

[Макеты в Figma](https://www.figma.com/file/a5AyFuTcjyjE15Y3AbrPai/Gradients-(https%3A%2F%2Fgithub.com%2FVKCOM%2FVKUI%2Fissues%2F5218)?type=design&node-id=2-1598&mode=design&t=txfb6TKChpqcq9q4-4)
