### ISSUE TITLE
[Doc]: Отсутствует страница с описанием HoverPopper

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#5223]
### Описание

На странице https://vkcom.github.io/VKUI/#/Popper есть диплинк с ссылкой на компонент https://github.com/VKCOM/VKUI/blob/master/packages/vkui/src/components/HoverPopper/HoverPopper.tsx, при переходе на страницу компонента -- 404. Хотелось бы видеть описание компонента, либо убрать диплинк

**Comment by inomdzhon** [comment]
Спасибо за issue 🙏 

Уберу ссылку
