### ISSUE TITLE
[Bug]: Не работает prop after у PanelHeader 

### ISSUE THREAD

**Issue by flangapp** [VKCOM/VKUI#5247]
### Описание

При передачи пропса after в компонент PanelHeader переданное значение не отображается.

### Версия

5.5.1

### Пример с воспроизведением

https://codesandbox.io/s/frosty-williams-2vtx2v?file=/src/App.js

**Comment by SevereCloud** [comment]
Привет, это [фича](https://vkcom.github.io/VKUI/#/LegacyPanelHeaderContent)

> Важно
> 
> Правая часть шапки скрыта по умолчанию, если требуется показать её, передайте в [ConfigProvider](https://vkcom.github.io/VKUI/#/ConfigProvider) свойство webviewType={WebviewType.INTERNAL}.

**Comment by david-shiko** [comment]
Дебильная фича.

**Comment by BlackySoul** [comment]
> Дебильная фича.

На момент версии `v7` правая часть `PanelHeader` теперь <ins>**не**</ins> скрывается по умолчанию. Но её всё ещё можно скрыть, используя свойство `hasCustomPanelHeaderAfter` у `ConfigProvider ` (это необходимо для [мини-приложений](https://dev.vk.com/ru/mini-apps/overview)).
