### ISSUE TITLE
[Doc]: Отсутсвует описание компонента PanelHeader

### ISSUE THREAD

**Issue by flangapp** [VKCOM/VKUI#5248]
### Описание

https://vkcom.github.io/VKUI/#/PanelHeader тсраница 404

**Comment by SevereCloud** [comment]
Привет, сейчас документацию можно найти на https://vkcom.github.io/VKUI/#/LegacyPanelHeaderContent

**Comment by SevereCloud** [comment]
Исправление  будет доступно в 5.5.2

Для истории: В #5209 упал патч, перезапустил(коммит a09b00133c22194aae4cd56da7134bbc288fde7c).
