### ISSUE TITLE
Page not found Grid

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#526]
Некорректная ссылка на Grid везде, где есть надпись "Сетка для Grid"
На данный момент https://vkcom.github.io/vkui-styleguide/#!/Grid **
А нужно: https://vkcom.github.io/vkui-styleguide/#card 

** Ну или пофиксить, что при переходе по данной ссылке Page Not Found

**Comment by ArthurStam** [comment]
Спасибо, исправим в ближайшем релизе

**Comment by ArthurStam** [comment]
Исправили)

**Comment by ilyapishchulin** [comment]
Угу, фикс
