### ISSUE TITLE
[Feature]: Добавить возможность работы Gallery как карусель

### ISSUE THREAD

**Issue by kaspian122** [VKCOM/VKUI#5264]
### Описание

Нужно сделать возможность бесконечной прокрутки галереи в каждую сторону.
Нужно доработать либо компонент Gallery добавив в него флаг для включения режима карусели либо создать новый компонент

### Скриншоты

<img width="574" alt="Снимок экрана 2023-07-04 в 16 09 49" src="https://github.com/VKCOM/VKUI/assets/39019501/7fa9a8bb-5128-422d-93cc-693c160fc4d8">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.0" target="_blank">v5.9.0</a> 🎉
