### ISSUE TITLE
[Bug]: Slider не доходит до конца

### ISSUE THREAD

**Issue by pasha-nikitin-2003** [VKCOM/VKUI#5283]
### Описание

Slider в режиме multiple не доходит до конца если длина slider(разница между максимальным и минимальным значением) не кратна step(шагу)

### Версия

5.5.2

### Шаги воспроизведения

задайте slider co следующими props:
{
  multiple
  step={500}
  min={250}
  max={20000}
}

слайдер остановится на значении 19750 и не дойдет до края

### Ожидаемое поведение

дойдет до 20000 а не остановится на значении 19750

### Скриншоты

![image](https://github.com/VKCOM/VKUI/assets/131760633/1cba71ac-b3cd-4107-93d4-6faf30b7b501)

**Comment by inomdzhon** [comment]
> **Note**
>
> Проблема локализовал в файле https://github.com/VKCOM/VKUI/blob/master/packages/vkui/src/helpers/math.ts
>
> Вынес в [песочницу](https://www.typescriptlang.org/play?#code/MYewdgzgLgBMA2BDAtgBxgXhgCgG6PgFcBTALhjEOQCNiAnAGhmQEsxzKb6nlEAPDlVp0AlJgB8AKBgwAsoigALAHS8+2VmCbylqtngIke-ESIDckyQDNCYYFBbgYqOsWAsIjsACUQtgCbYnMKCXIzOru6eTlgAjGIA3tIw8MSwVoj2IHSYcgoqqCAA7tixAAxMLm4eXubJrlCEdGB5unR+YIHB9DAAVDAZWaIwAPQDmVDZFgC+ljZ2Dk5VUV5BQvShwon1aU0t2AAGACQJ3XTTB8oQqPAsUNgA5MoPIgDasQC6MAA+3zAPL2UqTAAHMlDM5rZ7F4YP5qrwoMR-ABhJBoAzwTbcZhsLHhNR4pjQYioAD8eO2MhYVhwxPQGCwlHg8B+fzpMAAPFgypSZDAGns4GjUBieGxjHw6jJZjJQJBYMtcssauBsHSpaMxr4AjB8ERiDBJhRiIhXNAcS0ANQwADWsT6MDpyTl5rh7gRSIA8lYrBA0krIiqfB1AjoVO0AtgMTAALQWsRjdUOumVSIakZakP8xCgg3AsGKGAAfX8xTARcNIGNpuI5s0MGtNoATMnEahneBXfCFEjvDmQQasMrosHI2HlFZ4CBslG1LH46NHW2xP0UxE3BqBc0LQ2hSgRW6WB7-N7fWkmBVYd3Ef4+7m6rNrFDFi0zcACMRsMk9SRCckrO0yDkK8ZxMGcHwMMkkzAaBFDrHQEHJCAqAvhA5AJEuJLknBYQwNMuQJNMkG8i6sAQO+qT+LkUY-gacYASAyCvGUHwJjgDFMZ884ccxrErjgkzvF8caCSxYjWqJHwWDIW4tIex6ovuaoUUiTCSWpIBCUwyGoVcy4QpILogKkQIgCC2Bvh+pRlJezFMOULFMK8TYAKyXk2Nk2RBMAYXS5Cufa0ymEAA). При клике на Run можно увидеть лог справа.
>
> <img width="320" src="https://github.com/VKCOM/VKUI/assets/5850354/06dc6c61-62fd-4495-ba13-919a7f9453e1" />

**Comment by scffs** [comment]
![image](https://github.com/VKCOM/VKUI/assets/67464545/68a19af8-9368-4748-a5d0-36c926c093fb)

![image](https://github.com/VKCOM/VKUI/assets/67464545/fb2b63d6-b89a-4069-b9e9-f1d9c5b24212)

**Comment by inomdzhon** [comment]
issue закрыл https://vk.com/scffs (@scffs)
