### ISSUE TITLE
[TypeScript] [ModalPage] Некорректный тайпинг для onClose

### ISSUE THREAD

**Issue by wolframdeus** [VKCOM/VKUI#531]
В данный момент некорректный тайпинг для `ModalPage.onClose`. Сейчас он требует возвращения пустого объекта.
![image](https://user-images.githubusercontent.com/34907325/75157694-79b55980-5736-11ea-8717-cc7415ca01ba.png)

**Comment by wolframdeus** [comment]
PR: https://github.com/VKCOM/VKUI/pull/532

**Comment by ArthurStam** [comment]
Спасибо, чекнем

**Comment by ArthurStam** [comment]
Ждите в следующем релизе 😊

**Comment by ArthurStam** [comment]
Выкачено в 3.3.7
