### ISSUE TITLE
[TypeScript] [ModalRoot] Некорректный тайпинг для свойства activeModal.

### ISSUE THREAD

**Issue by wolframdeus** [VKCOM/VKUI#533]
Сейчас activeModal не может принимать null, но другими способами нет возможности скрыть ВСЕ модалки. Можно указать undefined но тогда происходит что-то страшное внутри и сыпятся варнинги в консоль.

PR: https://github.com/VKCOM/VKUI/pull/532

**Comment by ArthurStam** [comment]
Спасибо, чекнем

**Comment by ArthurStam** [comment]
Ждите в следующем релизе 😊

**Comment by ArthurStam** [comment]
Выкачено в 3.3.7
