### ISSUE TITLE
[Bug]: Не реализован автоскролл компонента Cell 

### ISSUE THREAD

**Issue by VladimirGlinskiy** [VKCOM/VKUI#5368]
### Описание

* Добавить в список более 15 компонентов (так чтобы список уходил за пределы вьюпорта) 
* Драг-н-дропом перетащить компонент ниже линии вьюпорта 
**Ожидаемый результат:** При перетаскивании компонента List автоматически скроллится 
**Фактический результат:** Автоскролл не работает 

### Версия

5.5.4

### В каких браузерах воспроизводится проблема?

Firefox, Chrome, Safari, Yandex Browser

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.0" target="_blank">v5.10.0</a> 🎉
