### ISSUE TITLE
[TypeScript] [ModalPage] ModalPage требует указания свойства updateModalHeight, который должен получать из контекста.

### ISSUE THREAD

**Issue by wolframdeus** [VKCOM/VKUI#537]
![image](https://user-images.githubusercontent.com/34907325/75281389-0a706000-5831-11ea-9695-ef7e46a10ebb.png)

В данный момент исходя из тайпинга ModalPage, требуется указывать updateModalHeight который прокидывается из контекста создаваемого, судя по всему, ModalRoot.

Необходимо изменить тайпинг для `withModalRootContext` и на выходе отдавать компонент без этого свойства. Сейчас он выглядит как заглушка TypeScript.

Кину PR как только появится свободное время.

**Comment by ArthurStam** [comment]
Спасибо! @fedorov-xyz это по твоей части :)

**Comment by wolframdeus** [comment]
Проблема до сих пор остается открытой. Тот скрин который скидывал выше показывался с уже залитым фиксом (то есть, с `@ignore`). К сожалению, по моему мнению, это нельзя считать решением. Необходимо либо делать поле опциональным, либо добавлять проверку внутри на его существование, иначе вызовем undefined. Мы ведь делаем изолированный компонент и не думаем о том, мол "этот компонент можно всегда использовать только с этим". Стоит позволить компонент хотя бы существовать самостоятельно.

PR: https://github.com/VKCOM/VKUI/pull/542

**Comment by ArthurStam** [comment]
Так мы его и сделали опциональным. Поставь 3.3.8 и проверь.

**Comment by ArthurStam** [comment]
https://github.com/VKCOM/VKUI/blob/master/src/components/ModalPage/ModalPage.tsx#L29

**Comment by wolframdeus** [comment]
Речь об этом https://github.com/VKCOM/VKUI/blob/bacd1090c4117518c9347f41848061ffe8cd0407/src/components/ModalPage/ModalPage.tsx#L35

В данном случае 2 выхода:
1. Делать свойство опциональным, НО добавить проверку на существование этого свойства, потому что когда я пишу комопнент я не расчитываю на то, что он всегда будет в контексте там какого-то другого компонента, оттого и нужна проверка. Скажем так, это неправильный подход к построению компонента. Да, не отрицаю, есть полностью зависимые компоненты, но считаю что это не тот случай.
2. Не делать свойство опциональным в случае, когда оно жизненно необходимо. По данному коду выглядит так, будто оно жизненно необходимо из-за отстутствующей проверки на установленность.

То есть я рекомендовал бы следовать одному из этих путей. Делать так или нет - дело ваше, но единственное чем я подкреплен - сделать библиотеку лучше.

**Comment by ArthurStam** [comment]
Про это свойство разработчикам знать не нужно. Поэтому мы поставили ignore и сделали его опциональным. Такой подход у нас много где применяется. Для `platform` и `insets`, например.

**Comment by ArthurStam** [comment]
Сейчас же у тебя typescript не ругается, когда ты юзаешь `ModalPage`? Если ошибки нет, то тикет можно закрывать.

**Comment by wolframdeus** [comment]
Хорошо. Тогда проблема закрыта.
