### ISSUE TITLE
[Bug]: Отступы в кнопках не соответствуют дизайн-системе

### ISSUE THREAD

**Issue by BlackySoul** [VKCOM/VKUI#5372]
### Описание

Привести в соответствие отступы в кнопках

### Версия

5.5.4

**Comment by mendrew** [comment]
@BlackySoul а про какие кнопки тут идёт речь? `IconButton`? 
Если да, то по ним есть [задача](https://github.com/VKCOM/VKUI/issues/5130) и дизайнеры работают над отступами в дизайн-системе.

**Comment by BlackySoul** [comment]
> @BlackySoul а про какие кнопки тут идёт речь? `IconButton`? Если да, то по ним есть [задача](https://github.com/VKCOM/VKUI/issues/5130) и дизайнеры работают над отступами в дизайн-системе.

Не, в обычных у нас разъехалось с дизайн-системой 🙂
