### ISSUE TITLE
[Bug]: <TextTooltip> не исчезает во время скролла

### ISSUE THREAD

**Issue by Curiosity1337** [VKCOM/VKUI#5393]
### Описание

Если после наведения курсора на children компонента <TextTooltip /> скроллить страницу, то тултип исчезает только при окончании скролла или при перемещении курсора

https://vkcom.github.io/VKUI/#/TextTooltip тут в примере тоже воспроизводится

### Версия

5.5.4

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

1. наводим курсор на children
2. скроллим страницу не двигая курсор
3. Тултип не исчезает

### Ожидаемое поведение

1. Видимо, исчезает, когда курсор во время скролла выезжает за пределы children

### Скриншоты

![2023-06-29 18 37 42](https://github.com/VKCOM/VKUI/assets/26797516/edf86b50-a0b1-4592-b9f2-809da1b2a046)

**Comment by inomdzhon** [comment]
Это нельзя назвать багом. Если бы тултип не исчезал бы вообще, тогда другой вопрос.

<details><summary>Видео для дополнительного контекста</summary>
<p>

https://github.com/VKCOM/VKUI/assets/5850354/9fcb66fc-2ded-4ad7-8456-22efb6e476cf

</p>
</details>
