### ISSUE TITLE
[Contributing] Невозможно контрибьютить через обычные коммиты.

### ISSUE THREAD

**Issue by wolframdeus** [VKCOM/VKUI#541]
Ввиду того, что библиотека использует eslint, в ней установлено правило проверки переходов на следующую строку. IDE подсказывает что в данный момент эти переходы не соответствуют правилу:
![image](https://user-images.githubusercontent.com/34907325/75422133-b31bde00-595d-11ea-8240-a6ddfd6956a2.png)

При попытке коммита запускается хук проверки соответствия правилам который, из-за некорректных переходов не дает запушить коммит. 

Сообщите, пожалуйста, если проблема на моей стороне.

**Comment by ArthurStam** [comment]
Привет. Судя по ошибкам, у тебя каждая строчка заканчивается ненужным пробелом.

**Comment by wolframdeus** [comment]
@ArthurStam проблема в том, что я просто склонировал либу и там уже сыпет этими ошибками. Вероятно, IDE их сама подменяет. Сейчас буду смотреть

**Comment by wolframdeus** [comment]
Да, проблема на моей стороне. Гит автоматически подменял LF на CRLF. Решение проблемы:
https://stackoverflow.com/a/5834094

`git config --global core.autocrlf input`
