### ISSUE TITLE
[Enhancement][ModalCardBase]: удалить стили задающие отступы через каскад, в пользу использования `Spacing`

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#5419]
### Описание

1. Выпилить следующие строки из стилей `ModalCardBase`:
    https://github.com/VKCOM/VKUI/blob/bb226ff2edbf0b7954fca56e8e181ee575486306/packages/vkui/src/components/ModalCardBase/ModalCardBase.module.css#L51-L58
  Следует использовать компонент [Spacing](https://vkcom.github.io/VKUI/#/Spacing).
2. Добавить в документацию пример использования [Spacing](https://vkcom.github.io/VKUI/#/Spacing) c `actions`.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
