### ISSUE TITLE
[Enhancement][a11y][FormLayoutGroup]: Улучшить доступность

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#5420]
## Как?

[FormLayoutGroup](https://vkcom.github.io/VKUI/#/FormLayoutGroup) должен по умолчанию оборачивать в [`<fieldset>`](https://developer.mozilla.org/ru/docs/Web/HTML/Element/fieldset), а не в `<div>`.

### Нюанс про `<legend>`

<details><summary>Спойлер</summary>
<p>

[`<fieldset>`](https://developer.mozilla.org/ru/docs/Web/HTML/Element/fieldset) позволяет добавлять заголовок через тэг `<legend>`.

Сейчас при

```jsx
<FormLayoutGroup>
  <legend> <Subhead>Заголовок</Subhead> </legend>
  <FormItem top="Имя">...</FormItem>
  <FormItem top="Фамилия">...</FormItem>
</FormLayoutGroup>
```

Заголовок будет выровнен некорректно.

<img width="1002" alt="image" src="https://github.com/VKCOM/VKUI/assets/5850354/4dec9e30-70ce-43e9-804a-9b1190e1279d">

_Пример_

Можно создать подкомпонент `<FormLayoutGroup.Legend>`, который будет использовать такие же токены для `padding`, как и у `FormItem`:

https://github.com/VKCOM/VKUI/blob/bb226ff2edbf0b7954fca56e8e181ee575486306/packages/vkui/src/components/FormItem/FormItem.module.css#L1-L5

```jsx
<FormLayoutGroup>
  <FormLayoutGroup.Legend> <Subhead>Заголовок</Subhead> </FormLayoutGroup.Legend>
  <FormItem top="Имя">...</FormItem>
  <FormItem top="Фамилия">...</FormItem>
</FormLayoutGroup>
```

Но это можно сделать отдельной задачей, т.к. здесь требуется работа со стороны дизайна. Сейчас можно без `<legend>`.

</p>
</details>

**Comment by scffs** [comment]
А так и должно быть? 

![image](https://github.com/VKCOM/VKUI/assets/67464545/71a58c68-bdde-42ba-b710-d0bec24c6056)

**Comment by inomdzhon** [comment]
> А так и должно быть?
> 
> ![image](https://user-images.githubusercontent.com/67464545/251045748-71a58c68-bdde-42ba-b710-d0bec24c6056.png)

На iOS, да

**Comment by scffs** [comment]
> На iOS, да

спасибо богу за андроид

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.3.0" target="_blank">v6.3.0</a> 🎉
