### ISSUE TITLE
[Feature]: Высчитывание высоты PanelHeader по контенту

### ISSUE THREAD

**Issue by evgeniy-strel** [VKCOM/VKUI#5466]
### Описание

Сейчас высота задается фиксированная через переменную --vkui--size_panel_header_height--regular, есть ли вариант сделать ее по содержимому?

Задать className PanelHeader и переопределить через стили не получилось, ведь в VkUiRoot лежит еще один PanelHeader на всю ширину.

**Comment by inomdzhon** [comment]
@evgeniy-strel привет)

Ты же можешь перебить `--vkui--size_panel_header_height--regular` на желаемый

После подключения стилей VKUI, написав:

```css
:root {
   --vkui--size_panel_header_height--regular: 100px;
}
```

Это поможет решить твою задачу?

**Comment by evgeniy-strel** [comment]
А как тогда у разных Panel сделать свою высоту шапки? Если перебивать, и делать разную высоту шапки у разных Panel, будут подергивания в шапке при плавной анимации. 

Пример: шапка panel 1 - 50px. шапка panel2 - 150px. При начале показа panel2 в mount меняю переменную, и шапка panel1 становится тоже 150, хотя panel1 еще не произошел unmount.

**Comment by evgeniy-strel** [comment]
Получилось воссоздать нужный эффект через FixedLayout top. Подскажите еще пожалуйста, можно ли сделать выравнивание fixed по меню слева а не шапки?
![image](https://github.com/VKCOM/VKUI/assets/82458628/c5732ba9-1390-4780-89e0-1499aec48edc)

**Comment by evgeniy-strel** [comment]
Получилось воссоздать нужный эффект через FixedLayout top

**Comment by inomdzhon** [comment]
> А как тогда у разных Panel сделать свою высоту шапки? И если перебивать, и делать разную высоту шапки у разных Panel, будут подергивания в шапке при плавной анимации.
> 
> Пример: шапка panel 1 - 50px. шапка panel2 - 150px. При начале показа panel2 в mount меняю переменную, и шапка panel1 становится тоже 150, хотя у panel1 еще не произошел unmount.

Можно локально перебивать токен для каждой панели, но, к сожалению, из-за этого могут быть проблемы с другими компонентами, которые, вне контекста `Panel`, используют этот токен, чтобы сместить своё положение на высоту `Panel` :(

> Получилось воссоздать нужный эффект через FixedLayout top

А ты мог бы скинуть скрин про свой кейс?

**Comment by evgeniy-strel** [comment]
> > А как тогда у разных Panel сделать свою высоту шапки? И если перебивать, и делать разную высоту шапки у разных Panel, будут подергивания в шапке при плавной анимации.
> > Пример: шапка panel 1 - 50px. шапка panel2 - 150px. При начале показа panel2 в mount меняю переменную, и шапка panel1 становится тоже 150, хотя у panel1 еще не произошел unmount.
> 
> Можно локально перебивать токен для каждой панели, но, к сожалению, из-за этого могут быть проблемы с другими компонентами, которые, вне контекста `Panel`, используют этот токен, чтобы сместить своё положение на высоту `Panel` :(
> 
> > Получилось воссоздать нужный эффект через FixedLayout top
> 
> А ты мог бы скинуть скрин про свой кейс?

Мне нужно было отобразить табы под/внизу шапки

![vk-panel-header](https://github.com/VKCOM/VKUI/assets/82458628/e5446572-d03a-44e6-9c89-3af555c0908b)

**Comment by inomdzhon** [comment]
А, вот оно как

У нас как раз задача есть на тему добавления возможности передавать компонент под `PanelHeader` https://github.com/VKCOM/VKUI/issues/4892

Но круто, что ты смог решить свою задач через `FixedLayout` 👍
