### ISSUE TITLE
Не обновились до VK Bridge.

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#547]
Пора обновлять.

Creating an optimized production build...
Failed to compile.

./node_modules/@vkontakte/vkui/dist/hooks/useInsets.js
Cannot find module: '@vkontakte/vk-connect'. Make sure this package is installed.

You can install this package by running: npm install @vkontakte/vk-connect.

**Comment by ArthurStam** [comment]
Обновимся, спасибо. Но vk-connect должен еще существовать.

**Comment by ilyapishchulin** [comment]
Не спорю, но идут конфликты :)

**Comment by ilyapishchulin** [comment]
Плохо поправили, ошибки

**Comment by ArthurStam** [comment]
Если ты ошибку на версии vk-bridge@2.0.1, то обновись до 2.0.2. Ребята выкатили версию с ошибокй, но уже задепрекейтили её. Если у тебя проблема не в этом, то нужно больше инфы.

**Comment by ilyapishchulin** [comment]
Вроде, фикс

**Comment by ilyapishchulin** [comment]
Вот такая была.

![](https://sun1-88.userapi.com/c853528/v853528956/1f5ca3/dV7gc1AeSC8.jpg)

**Comment by ArthurStam** [comment]
Да, в 2.0.2 её поправили.
