### ISSUE TITLE
[Feature]: Tabbar добавить поддержку vertical: "top" | "bottom" | undefined

### ISSUE THREAD

**Issue by dsedinkin** [VKCOM/VKUI#5476]
### Описание

Простым решением для адаптации было бы добавление Prop name vertical со значениями "top" | "bottom" | undefined, прямо как у компонента FixedLayout, за исключением. Tabbar должен быть выше PanelHeader.

Объясню кейс. На VKCOM, в полной версии веб сайта. Есть возможность использовать bridge VKWebAppResizeWindow. И если не будет сделана адаптация с использованием SplitCol и Cell, то при динамической высоте приложения в зависимости от контента, получится так что tabbar будет всегда в самом низу в не зоны досягаемости.

**Comment by eugpoloz** [comment]
Привет! Такое делать не планируем. По двум причинам: 
1. на VKCOM Tabbar использоваться вообще-то не должен: подразумевается, что это компонент меню для мобилок, а в десктопе должно быть что-то другое. 😉 
2. VKUI уже используется далеко не только для миниаппов, поэтому мы в v6 будем избавляться от привязки VKUI к бриджу и его событиям.
