### ISSUE TITLE
[Bug]: Не кликается IconButton при включенной функции TalkBack на андроиде

### ISSUE THREAD

**Issue by uku1e1e** [VKCOM/VKUI#5484]
### Описание

Есть такой компонент с тремя точками, он почему то не кликается при включенной функции TalkBack на андроиде. В других читалках эта кнопка нормально работает, не работает только в TalkBack.
![image](https://github.com/VKCOM/VKUI/assets/139744853/1a8d5b26-dac8-4b19-80b4-8a6fee3bc197)

Пример кода
` 
       <Cell
          key={id}
          mode={false ? 'removable' : undefined}
          after={(
            <IconButton
              onClick={onTokenEditClick(id, credential_id, name)}
              aria-label="edit-token-button"
            >
              {moreIcon}
            </IconButton>
          )}
        >
          {name}
        </Cell>
`

### Версия

5.3.2

**Comment by inomdzhon** [comment]
Сейчас проблема, что у тебя кнопка внутри кнопку, что не валидно.

Попробуй перебить в `Cell` роль через, например, `role="textbox"`, тогда у тебя `IconButton` останется единственной кнопкой

**Comment by inomdzhon** [comment]
> Сейчас проблема, что у тебя кнопка внутри кнопку, что не валидно.
> 
> Попробуй перебить в `Cell` роль через, например, `role="textbox"`, тогда у тебя `IconButton` останется единственной кнопкой

Решило проблему
