### ISSUE TITLE
[Feature][TextTooltip]: добавить проп для отображения тултипа толька на активных / выключенных кнопках 

### ISSUE THREAD

**Issue by scffs** [VKCOM/VKUI#5488]
### Описание

Сейчас `TextTooltip` показывается на любой кнопке не зависимо от её состояния, но иногда нужно, чтобы тултип срабатывал только на `disabled` кнопке, сейчас такого функционала нет

**Comment by BlackySoul** [comment]
Привет! Кажется, что такое поведение проще решить на стороне пользователя.
Либо оборачивать кнопку в `TextTooltip` только для случая `disabled` у кнопки, либо управлять флажком `shown` у `TextTooltip`, например:

```
<TextTooltip shown={buttonDisabled ? undefined : false}>
  <Button disabled={buttonDisabled} ... />
</TextTooltip>
```

Что думаешь?

**Comment by scffs** [comment]
Вполне чистое решение, тогда проп для этого будет оверхедом
