### ISSUE TITLE
[Bug]: Search Input padding

### ISSUE THREAD

**Issue by johnneon** [VKCOM/VKUI#5499]
### Описание

Поисковая строка резервирует себе место под 2 кнопки паддингами, а по идее должна быть динамична, тк теряется слишком много полезного пространства под текст.

### Версия

4.43.1-alpha.0

### Шаги воспроизведения

В строку поиска (в которой не используется доп кнопка) пишем что-то, текст обрезается почти на середине строки, если ширина не сильно большая.

### Ожидаемое поведение

Текст начинает обрезаться возле крестика очистки.

### Скриншоты

https://github.com/VKCOM/VKUI/assets/53760291/5d9747ee-01ef-4c8e-880f-bf2fd75211ef

### Пример с воспроизведением

https://codesandbox.io/s/quiet-water-h59pf5

**Comment by SevereCloud** [comment]
Привет, в v5 не воспроизводится
