### ISSUE TITLE
[Feature]: Cделать styles={{ width: something }} приоритетнее max-content в Popper

### ISSUE THREAD

**Issue by daniil-kaverzin** [VKCOM/VKUI#5504]
### Описание

[v5.6.2](https://github.com/VKCOM/VKUI/releases/tag/v5.6.2)

Если мы сейчас сделаем `<Popover style={{ width: 100 }} />`, то в результате получим width: max-content вместо желаемых 100px, чтобы получить желаемые 100px – необходимо передать sameWidth={true}, что не очень очевидно. Хочется сделать `style={{ width: something }}` приоритетнее без sameWidth.

**Comment by inomdzhon** [comment]
Закрыли ввиду того, что задача решается вот так:

```tsx
<Popover>
  <div style={{ width: 100 }}>
     ...
  </div>
</Popover>
```
