### ISSUE TITLE
Перфикционист плачет в сторонке.

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#551]
В примере Tooltip (дока)
<img width="1440" alt="Снимок экрана 2020-02-29 в 19 03 27" src="https://user-images.githubusercontent.com/45998835/75610857-2c662d00-5b26-11ea-8ce4-7b4ed5af0a1b.png">

Чернота то какая, поправьте пробелы)

**Comment by ArthurStam** [comment]
Не хочешь отправить нам PR с исправлениями?)

**Comment by ilyapishchulin** [comment]
Я бы с огромным счастьем, но чет не выходит :(

**Comment by ilyapishchulin** [comment]
Готово

**Comment by fedorov-xyz** [comment]
Будет исправлено в документации с публикацией следующего релиза. Спасибо!
