### ISSUE TITLE
[Feature]: Добавить в компонент HorizontalCell новый булен компонента Badge 

### ISSUE THREAD

**Issue by Andrew-dushes** [VKCOM/VKUI#5526]
### Описание

Нужно добавть новый компонент Badge для компонента HorizontalCell. 

### Скриншоты

![Снимок экрана 2023-07-26 в 12 35 45](https://github.com/VKCOM/VKUI/assets/70465331/00b24eb7-0b5d-4c0a-8e1c-d171171fe0e5)

**Comment by inomdzhon** [comment]
Будем дорабатывать компонент `Avatar`, чтобы была возможность передавать иконки сверху-справа, сверху-слева, снизу-слева.
