### ISSUE TITLE
[Bug][Header]: Не выравнивается aside контент 

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#5531]
### Описание

В Header компоненте любой aside контент не выравнивается относительно контента в компоненте

Хорошо это заметно с size=large

### Версия

5.0.0

### В каких браузерах воспроизводится проблема?

Firefox, Chrome, Safari, Microsoft Edge, Yandex Browser

### Скриншоты

![r17rZtLQmfI](https://github.com/VKCOM/VKUI/assets/42776347/70af966f-5b38-4333-8565-9178ed3dc77d)

**Comment by mendrew** [comment]
Я думаю, что поведение вполне в рамках ограничений которые накладываются на проп `aside` в данный момент.
Согласно [документации](https://vkcom.github.io/VKUI/#/Header?id=props) в `aside`:
> допускаются иконки, текст, Link

Поведение кнопки внутри `aside` без текста не определено. Плюс кнопку в aside передавать не стоит, чтобы не нарушить семантику, aside обёрнут в `span`.
https://github.com/VKCOM/VKUI/blob/8c27b6111e57cd89fb7b17932b044976fe6507d4/packages/vkui/src/components/Header/Header.tsx#L135-L139

А если передавать текст или Link, то смотрится вполне как в дизайне.
<img width="328" alt="Снимок экрана 2023-08-17 в 12 49 03" src="https://github.com/VKCOM/VKUI/assets/5443359/6bf7ccd2-e405-4366-8003-fa73af942d71">

@inomdzhon @MrZillaGold что думаете?

**Comment by MrZillaGold** [comment]
если в aside действительно можно пихать только текст, тогда нужен какой-нибудь проп для кнопок и прочего контента, который будет центроваться

**Comment by mendrew** [comment]
О, похоже у нас есть issue по этому поводу. https://github.com/VKCOM/VKUI/issues/3132
Пардон, не заметил.

**Comment by MrZillaGold** [comment]
Закрываю, спасибо!
