### ISSUE TITLE
Нет анимации тапа/клика у компонента Link

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#554]
У нас есть компонент Link и мы можем юзать его везде.
Добавляем анимацию на клик и решаем все проблемы, еще желательно убрать выделение

**Comment by ArthurStam** [comment]
Привет. Перед созданием PR фичи или улучшения, лучше сначала обсудить реализацию. В конкретном случае непонятно, откуда ты взял стили для активного состояния ссылки. В нативном клиенте ВК стили другие.

**Comment by ilyapishchulin** [comment]
Окей, обычно везде применяют прозрачность.

**Comment by ilyapishchulin** [comment]
Но анимку желательно добавить, не очень смотрится при таре

**Comment by ArthurStam** [comment]
Добавим, спасибо. PR можно закрывать, он задачу не решает.

**Comment by ilyapishchulin** [comment]
Закрыл же уже)

**Comment by ArthurStam** [comment]
Есть, начиная с версии [4.0.0](https://github.com/VKCOM/VKUI/releases/tag/v4.0.0)
