### ISSUE TITLE
[Bug]: На мобильных устройствах не работает скролл выпадающего списка компонента CustomSelect (React v18.2.0)

### ISSUE THREAD

**Issue by Ascurse** [VKCOM/VKUI#5540]
### Описание

На мобильных устройствах в компоненте CustomSelect библиотеки VKUI наблюдается неработоспособность прокрутки выпадающего списка с помощью touch ивентов. При попытке прокрутить список пальцем вниз или вверх, ничего не происходит, и пользователь не может выбрать элементы, которые не видны на экране.
В данный момент компонент используем внутри модального окна.

Одним из предложенных решений для этой проблемы было использование компонента Select вместо CustomSelect, который переключает между NativeSelect и CustomSelect в зависимости от ширины экрана. Однако NativeSelect не обладает свойством "searchable", что является крайне важным функционалом.

### Версия

v5.6.2 

### В каких браузерах воспроизводится проблема?

Chrome, Safari

### Шаги воспроизведения

1. Откройте веб-приложение, содержащее компонент CustomSelect, на мобильном устройстве.
2. Откройте выпадающий список CustomSelect, который содержит большое количество элементов, так что список выходит за пределы экрана устройства.
3. Попробуйте прокрутить список пальцем вниз или вверх.

На мобильных устройствах прокрутка выпадающего списка CustomSelect не работает с помощью touch ивентов. Пользователь не может выбрать элементы, которые не видны на экране, так как список остаётся неподвижным.

### Ожидаемое поведение

При прокрутке пальцем вниз или вверх по выпадающему списку CustomSelect, список должен плавно прокручиваться, позволяя пользователю выбрать элементы, которые не видны на экране.

**Comment by eugpoloz** [comment]
@Ascurse привет! Точно v4.6.2, а не v5.6.2?

**Comment by Ascurse** [comment]
@eugpoloz Пардон, v5.6.2

**Comment by Ascurse** [comment]
Дополнение: скролл выпадающего списка на мобильных устройствах в компоненте СustomSelect не работает ТОЛЬКО когда компонент находится внутри модального окна ModalRoot -> ModalPage
Если подключить компонент на обычную страницу все работает как ожидалось

**Comment by inomdzhon** [comment]
[CustomSelect](https://vkcom.github.io/VKUI/#/CustomSelect) стоит использовать для десктоп, а для мобилок [NativeSelect](https://vkcom.github.io/VKUI/#/NativeSelect). У нас есть компонент [Select](https://vkcom.github.io/VKUI/#/Select), который переключает эти два компонента в зависимости от того, есть ли указатель мыши или нет.

Вот тут писал почему https://github.com/VKCOM/VKUI/issues/4844#issuecomment-1531859744

**Comment by Ascurse** [comment]
@inomdzhon да, читал про это решение, но она к сожалению не совсем подходит когда нужен селект с возможностью поиска (searchable)
B опять же повторюсь - проблема присутствует только когда СustomSelect находится внутри модального окна
