### ISSUE TITLE
[Bug][Typography]: Отличается жирность шрифта относительно Figma

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#5565]
### Описание

https://www.figma.com/file/z8VQmj9Foh2Pcw5nLIHE6o/Signals?type=design&node-id=1152-245025&mode=design&t=iTC3U7RB5BewPk5a-0

https://forum.figma.com/t/why-does-a-font-weight-in-figma-seem-lighter-than-the-same-weight-in-the-browser/2207/2

Предположительное решение: `-webkit-font-smoothing: antialiased`, но при установки этого значение в доке vkui все очень сильно меняется, ок ли это для дизайн системы? Возможно стоит применить это свойство только для начертаний жирность которых больше 400

### Версия

5.0.0

### В каких браузерах воспроизводится проблема?

Chrome

https://github.com/VKCOM/VKUI/assets/42776347/f247b33a-2577-41d5-9e30-026409d8a6bb

**Comment by SevereCloud** [comment]
Решили вообще не использовать font-smoothing и использовать системное значение. Разницу между фигмой и на сайтах [можно считать нормой](https://forum.figma.com/t/why-does-a-font-weight-in-figma-seem-lighter-than-the-same-weight-in-the-browser/2207/2)
