### ISSUE TITLE
[Feature]: Расширить область триггера SwipeBack

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#5583]
### Описание

Нужно свериться с областью экрана, свайп по которой может инициировать свайпэк. Сейчас это левые 70 пикселей экрана.

Обратите внимание, пожалуйста, на нативное приложение ВКонтакте. В нем можно инициировать свайпэк в любой области экрана. Это входит в привычку использования ВКонтакте, но в мини-приложениях навигироваться сложнее.

Корнер: горизонтальные скроллбары с ненулевым scrollX не должны конфликтовать со свайпбеком. Наверное, можно оставить на ответственности разработчика, но стоит упомянуть в документации. Где-нибудь рядом с data-vkui-swipe-back={false}

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.0" target="_blank">v5.9.0</a> 🎉
