### ISSUE TITLE
[Tech]: обновить Yarn до v3

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#5594]
### Описание

Ответ на почему есть в статье от **Yarn** – [Why should you upgrade to Yarn Modern?](https://yarnpkg.com/getting-started/qa#why-should-you-upgrade-to-yarn-modern)

## Дополнительные преимущества

Помимо этого, появится возможность решить задачу #5593 более элегантно, расширив `packages/vkui/package.json` вот таким образом:

```json
{
  "files": [
    "dist",
    "src",
    "!src/**/*.png",
    "!src/**/*.*.ts",
    "!src/**/*.*.tsx",
    "!src/vkui.js",
    "!src/testing/",
    "!src/storybook/"
  ]
}
```

## Ссылки

- https://github.com/VKCOM/vk-bridge/issues/347
- https://github.com/VKCOM/icons/issues/572

**Comment by mendrew** [comment]
Только надо проверить, не будет ли проблемы с публикованием пакета, которая была в [icons](https://github.com/VKCOM/icons/pull/640/files).
Там в yarn 3 файлы перечисленные как `files: [ "src/svg" ]` не включались в пакет, в то время как  при такой записи `files: [ "src" ]` включались.

Не будет ли проблем с исключение отдельных файлов. 
И не попадём ли мы впросак в будущем, если надо будет что-то конкретно включить в пакет в виде `files: [ "src/svg" ]`.
Я бы поостерёгся использовать `files` и продолжил с `.npmignore` (при переходе на yarn 3) даже если нету проблемы использовать оба метода одновременно, `.npmignore` для публикования и `files` в package.json для https://github.com/VKCOM/VKUI/issues/5593

**Comment by inomdzhon** [comment]
> Только надо проверить, не будет ли проблемы с публикованием пакета, которая была в [icons](https://github.com/VKCOM/icons/pull/640/files). Там в yarn 3 файлы перечисленные как `files: [ "src/svg" ]` не включались в пакет, в то время как при такой записи `files: [ "src" ]` включались.

Как раз вчера проверял

```json
{
  "files": [
    "/dist",
    "/src/svg"
  ],
}
```

идентичные артефакты получаются

<img width="613" alt="image" src="https://github.com/VKCOM/VKUI/assets/5850354/ec579675-c5c2-4a24-b15c-2bbe6b643147">

_Сравнение двух артефактов. **new** на 52 байта больше, т.к. в `package.json` есть поле `"files"`._

> Не будет ли проблем с исключение отдельных файлов. И не попадём ли мы впросак в будущем, если надо будет что-то конкретно включить в пакет в виде `files: [ "src/svg" ]`. Я бы поостерёгся использовать `files` и продолжил с `.npmignore` (при переходе на yarn 3) даже если нету проблемы использовать оба метода одновременно, `.npmignore` для публикования и `files` в package.json для #5593

Если будут затруднения, то заменим `files` на `.npmignore`. Сейчас через `.npmignore` не получается решить #5593. Там либо надо забить на тестовые файлы, либо точечно исключение в `.npmignore` добавлять, но тогда нужно ещё дополнительно валидацию прикручивать, т.к. очень легко забыть актуализировать `.npmignore`.

**Comment by inomdzhon** [comment]
> @inomdzhon
> 
> > Как раз вчера проверял
> 
> Спасибо, что проверил!
> 
> Я просто боюсь что той багой c [files](https://github.com/VKCOM/icons/pull/640/files) в yarn v3 дело может не ограничится. И не очень хочется уповать на инструмент в котором мы уже наткнулись на неожиданное поведение.
> 
> С .npmignore всё более предсказуемо.
> 
> Как тебе вариант с `.npmignore` который я показал в этом [комментарии](https://github.com/VKCOM/VKUI/pull/5392#discussion_r1289887540) (c примером)? Что-то вроде
> 
> ```
> # Exclude all
> *
> 
> # Include partially
> # package.json, README.md and LICENSE can't be ingored
> !dist/**
> !src/**/*.js
> !src/**/*.tsx
> 
> # Exclude parts we don't want to see from partially included
> src/**/*.test.ts
> src/**/*.test.tsx
> src/**/*.e2e.tsx
> src/**/*.e2e-playground.tsx
> src/**/*.stories.tsx
> ```
> 
> Выглядит как заманчивая альтернатива. Я не думаю, что мы забудем про `.npmignore`, если совсем откажемся от `package.json#files`. Больше и некуда будет смотреть, кроме как в `.npmignore`.
> 
> Что думаешь?

Ответил https://github.com/VKCOM/VKUI/pull/5392#discussion_r1289910913

Надо проверить этот варик с **Yarn v3**, тогда может быть хорошей альтернативой 👍

**Comment by mendrew** [comment]
> Ответил [#5392 (comment)](https://github.com/VKCOM/VKUI/pull/5392#discussion_r1289910913)
> 
> Надо проверить этот варик с **Yarn v3**, тогда может быть хорошей альтернативой 👍

@inomdzhon 

Я проверил)) Не работает https://github.com/VKCOM/VKUI/pull/5392#discussion_r1289943355
А что если как в [icons](https://github.com/VKCOM/icons/blob/8c17d076dd754335807d086696091815490c6ce5/.github/workflows/publish_icons.yml#L103-L106) использовать `npm` вместо `yarn` для публикации пакетов?

**Comment by inomdzhon** [comment]
> > Ответил [#5392 (comment)](https://github.com/VKCOM/VKUI/pull/5392#discussion_r1289910913)
> > Надо проверить этот варик с **Yarn v3**, тогда может быть хорошей альтернативой 👍
> 
> @inomdzhon
> 
> Я проверил)) Не работает [#5392 (comment)](https://github.com/VKCOM/VKUI/pull/5392#discussion_r1289943355) А что если как в [icons](https://github.com/VKCOM/icons/blob/8c17d076dd754335807d086696091815490c6ce5/.github/workflows/publish_icons.yml#L103-L106) использовать `npm` вместо `yarn` для публикации пакетов?

При переходе на **Yarn v3** по-любому придётся использовать **NPM** для публикации 🌚  В рамках **Yarn v1** подумывал попробовать **NPM** заюзать, но таки не решился 🤔

Переезд на **Yarn v3**, в целом, неплохая мысля
