### ISSUE TITLE
[Bug]: неправильно отрабатывает последний `Group` с `separator="show"`

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#5603]
### Описание

Последний Group (если их несколько в панели) с явно переданным separator="show" делает конский отступ до сепаратора.

первый скрин: две Group (гориз карусель и вертикальный список). Первая с явным separator="show". Тут ок.
![image](https://github.com/VKCOM/VKUI/assets/22776192/d2608241-b9af-4319-962b-fa01de2a6caa)

второй скрин: одна Group (гориз карусель) с явным separator="show", огораживаемся от плейсхолдера. Тут не ок. Над сепариком большая дырка.
![image](https://github.com/VKCOM/VKUI/assets/22776192/8ebd2ee7-00d4-4b71-93be-d10bb638bb33)

___

Лишний воздух в моем примере показывается по причине форсирования пропсом separator=show. А спейсинг по причине что это последняя панель (кажется умышленно). Наложились условия, получилось неприятное. 

шаг 1. Поменять местами спейс и сепаратор в коде
![image](https://github.com/VKCOM/VKUI/assets/22776192/6defd180-44d5-454e-bc21-35cba9502e1d)

шаг 2. убрать в коде возможность присваивать Group__separator--force для спейсинга. Только для сепаратора.
https://github.com/VKCOM/VKUI/blob/master/packages/vkui/src/components/Group/Group.tsx#L130

### Версия

5.7.1

**Comment by inomdzhon** [comment]
- caused by https://github.com/VKCOM/VKUI/pull/2974
