### ISSUE TITLE
[Feature]: Режим для Button = Rounded полное скругление

### ISSUE THREAD

**Issue by Zaycevq** [VKCOM/VKUI#5625]
### Описание

Хотим добавить режим кнопки когда она полностью круглая и напоминает таблетку.

Это будет дополнительный параметр – Rounded, для тех кому это нужно. Включается по тоглу в коде, в дизайне меняется токен для Button – sizeBorderRadiusRounded, который так же есть в vkui-tokens

Дизайн:
https://vk.cc/cqaGH8
<img width="1394" alt="rounded-button" src="https://github.com/VKCOM/VKUI/assets/91548592/547f88b3-04f4-4184-a4e7-97d64f4245a0">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.0" target="_blank">v5.9.0</a> 🎉
