### ISSUE TITLE
[Feature]: Повысить доступность для компонента Placeholder

### ISSUE THREAD

**Issue by rodionstaroverov** [VKCOM/VKUI#5628]
### Описание

Было бы хорошо добавить возможность прокидывать кастомные пропы для обертки `children` - `<Headline />`, так как сейчас нет возможности добавить, например, кастомный `aria-label` для `children`, так как выше - компонент заголовка h4

Так же можно обойтись кастомным пропом `aria-label` для `<Headline />` внутри `<Placehoder />`

**Comment by SevereCloud** [comment]
Duplicate of #4696
