### ISSUE TITLE
[Feature][Separator]: Вертикальный режим Sepatator

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#5636]
### Описание

Проп mode = horizontal | vertical для separator, который будет отвечать за направление отрисовки компонента

### Скриншоты

![Снимок экрана 2023-08-17 в 14 06 56](https://github.com/VKCOM/VKUI/assets/42776347/2df63e84-2aa3-40da-9940-23415c0110c5)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
