### ISSUE TITLE
[Feature]: Фокус на ModalCard

### ISSUE THREAD

**Issue by rodionstaroverov** [VKCOM/VKUI#5646]
### Описание

При открытии `ModalCard` без элемента с автофокусом внутри, например `Input`, фокус остается снаружи модалки, и пользователь с голосовым помощником при переключении между элементами не может сразу зайти внутрь модалки - ему придется отдельно фокусироваться на ней

Просьба сделать фокус на открытую модалку, если нет фокуса на элементе внутри нее

### Скриншоты

<img width="602" alt="Снимок экрана 2023-08-18 в 15 06 27" src="https://github.com/VKCOM/VKUI/assets/16692421/46e115d3-1cfb-4dee-99c7-d0dc5a3e77cf">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.6" target="_blank">v5.9.6</a> 🎉
