### ISSUE TITLE
Иконка большого размера слишком близко расположена в before

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#565]
```
<Div>
       <Button before={<Icon28MoneyCircleOutline/>} size="xl" mode="secondary">Купить за 300 монеток</Button>
</Div>

```
Получаем результат:
![](https://sun9-32.userapi.com/c857236/v857236190/108304/-j1WOm_CqeQ.jpg)

Смотрится слишком близко, мб фича

**Comment by ArthurStam** [comment]
Привет. Спасибо, поправим

**Comment by fedorov-xyz** [comment]
Спасибо! Исправлено в версии `3.4.3`.

**Comment by manaenckow** [comment]
Актуально

**Comment by manaenckow** [comment]
![image](https://user-images.githubusercontent.com/48844646/77943212-8abd3180-72c5-11ea-8c65-590825273d9b.png)
