### ISSUE TITLE
Поправить стиль шрифта заголовка в ModalPage

### ISSUE THREAD

**Issue by Lihachyov** [VKCOM/VKUI#566]
![_LInHcGhEKo](https://user-images.githubusercontent.com/3250391/76406087-3d226880-639a-11ea-96af-e23e0cec5e09.jpg)

Сейчас стиль заголовка в модальных страницах меньше, чем у обычного PanelHeader, а должен быть одинаковый (большего размера и TT Commons)

**Comment by ArthurStam** [comment]
Поправим, спасибо Миша :)

**Comment by fedorov-xyz** [comment]
Спасибо! Исправлено в версии `3.4.3`.
