### ISSUE TITLE
Bug: [Search][IOS] при сбросе контента по нажатию на крестик, в инпуте остается выделение на IOS устройствах

### ISSUE THREAD

**Issue by deadit** [VKCOM/VKUI#567]
Привет. Собственно, компонент Search, IOS. Ввожу текст, т9 помогает закончить -> я нажимаю на крестик -> выделение остается. Раньше, по нажатию на кнопку "отмена", оно сбрасывалось и выделения не было. (Вероятно, так как внутри компонент Input, с ним такая же проблема.)

## Текущее поведение

![image](https://user-images.githubusercontent.com/26635501/76420324-fdb44600-63b2-11ea-9b96-8b9233d3783d.png)

## Фактическое поведение

Никакого выделения нету.

**Comment by ArthurStam** [comment]
Привет. Можно видео с воспроизведением?

**Comment by deadit** [comment]
Привет! Да, держи:

**Comment by ArthurStam** [comment]
Не могу воспроизвести. Попробовал на двух айфонах в том же приложении

**Comment by ArthurStam** [comment]
Закрываю тикет за отсутствием активности.
