### ISSUE TITLE
[Bug]: PullToRefresh на мобильном сафари нестабильно работает

### ISSUE THREAD

**Issue by rflban** [VKCOM/VKUI#5670]
### Описание

Проблема с компонентом PullToRefresh в мобильном сафари - через раз вместо него срабатывает нативный

### Версия

5.7.1

### В каких браузерах воспроизводится проблема?

Safari

### Шаги воспроизведения

Потянуть экран вверх. Иногда срабатывает нативный pull-to-refresh, иногда - vkui,  а иногда - оба

### Ожидаемое поведение

Всегда должен срабатывать vkui

### Скриншоты

<img width="1512" alt="image" src="https://github.com/VKCOM/VKUI/assets/24281074/bd9f6cb9-7081-4115-98d8-e2e668a252c8">

<img width="1512" alt="image" src="https://github.com/VKCOM/VKUI/assets/24281074/d57f8460-775b-47bc-9d02-964fd48b52f2">

<img width="1512" alt="image" src="https://github.com/VKCOM/VKUI/assets/24281074/4fad6353-9dcc-4afb-9f43-83ec2a414fd4">

### Пример с воспроизведением

https://codesandbox.io/embed/sleepy-banach-j3fsm5?fontsize=14&hidenavigation=1&theme=dark

смотреть на реальном айфоне или на эмуляторе xcode

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.3" target="_blank">v5.9.3</a> 🎉
