### ISSUE TITLE
[Bug][FormItem]: Неверный размер типографики

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#5673]
### Описание

В компоненте figma у FormItem есть параметр `Size Class` у `Subhead` (= Title) со значениями compact/regular, предполагаю что в коде это `sizeY = compact | regular`.

![Снимок экрана 2023-08-21 в 19 25 08](https://github.com/VKCOM/VKUI/assets/42776347/e229f139-5498-40cb-abdc-ffb9b2723637)

При установке значения compact в figma размер шрифта становится 13px = Footnote, но в коде при значении `sizeY = compact` типографика никак не меняется и зафиксирован компонент Subhead, что неверно относительно ДС.

### Версия

5

### Ожидаемое поведение

Типографика менятся заголовка меняется на Footnote при sizeY = compact, проверить bottom на соответствие макету

**Comment by SevereCloud** [comment]
> При установке значения compact в figma размер шрифта становится 13px = Footnote

Он становится Compact Subhead (13px)

<img width="644" alt="image" src="https://github.com/VKCOM/VKUI/assets/14944123/3038e780-0a91-4409-bfb0-2a0e9e44bbbf">

>  но в коде при значении sizeY = compact типографика никак не меняется и зафиксирован компонент Subhead, что неверно относительно ДС.

Subhead меняется в зависимости от sizeY 

<img width="353" alt="image" src="https://github.com/VKCOM/VKUI/assets/14944123/b91d3be9-051b-4a93-b4e5-4a87a56b5c48">
