### ISSUE TITLE
[Bug]: Не работает клик по NativeSelect на Android 

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#5683]
### Описание

Иногда не работает клик по NativeSelect на Android. Помогает перезаход в клиент.

Только Android.
Шаги воспроизведения локализовать не удалось.

Воспроизводилось как у разработчиков/QA, так и были жалобы от пользователей.
______
Продуктовая жалоба в VK Знакомствах:

Нет возможности поменять цель знакомства в модалке фильтров. Клик не реагирует.

![image](https://github.com/VKCOM/VKUI/assets/22776192/21b8d657-3e0d-48fb-9edb-119f60d390b9)
_____

Точно получалось воспроизводить на Sumsung A51 (клик только добавляет outline и не более)

![image](https://github.com/VKCOM/VKUI/assets/22776192/2ab76994-d0af-430b-abc7-5e2694db78c0)
![image](https://github.com/VKCOM/VKUI/assets/22776192/b63008a0-5511-48c3-9cb7-5d1c66ff8030)

____

Есть догадка, что так может быть, когда NativeSelect внутри ModalPage

### Версия

5.7.1

### В каких браузерах воспроизводится проблема?

Другое (укажите в описании)

**Comment by inomdzhon** [comment]
Вот этот PR https://github.com/VKCOM/VKUI/pull/6087, который попал в [v5.10.0](https://github.com/VKCOM/VKUI/releases/tag/v5.10.0) предположительно должен поправить багу.

Поэтому закрою issue, но если всё ещё будет воспроизводиться, то переоткроем.
