### ISSUE TITLE
[Bug]: В Checkbox'е не работает line-clamp/text-overflow: ellipsis

### ISSUE THREAD

**Issue by andres-kovalev** [VKCOM/VKUI#5687]
### Описание

Внутри Checkbox'а не работает стандартный `<div style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>...</div>`. Судя по всему не хватает `min-width: 0` на `Checkbox__content` и `Checkbox__content > Text`

### Версия

5.6.2

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

```
<Checkbox style={{ width: 100 }}>
  <div style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>Длииииииииииииииииииииииииииииииинный текст</div>
</Checkbox>
```

### Ожидаемое поведение

<img width="135" alt="image" src="https://github.com/VKCOM/VKUI/assets/2773159/87e70600-27bf-4631-b78f-aa4b6d828889">

### Скриншоты

<img width="383" alt="image" src="https://github.com/VKCOM/VKUI/assets/2773159/915cb060-583b-4fc3-b775-9bdd035dcd28">

**Comment by andres-kovalev** [comment]
Как предложение:
Вы можете затащить к себе `TextClamp` и положить его в `Checkbox`, чтобы можно было делать `<Checkbox lines={1}>`

**Comment by inomdzhon** [comment]
> Как предложение: Вы можете затащить к себе `TextClamp` и положить его в `Checkbox`, чтобы можно было делать `<Checkbox lines={1}>`

Мы можем создать `TextClamp` (это отдельный фича-реквест), чтобы можно было делать композицию

```tsx
<Checkbox>
  <TextClamp />
</Checkbox>
```
