### ISSUE TITLE
[Feature]: Cинкануть токены для компонента Modal Page + Modal Cadr

### ISSUE THREAD

**Issue by Dushart** [VKCOM/VKUI#5688]
### Описание

Сейчас встречаются кейсы на проде, токены в компонентах Modal различаются, нужно привести все варианты к одному токену - `colorBackgroundModal` ([upd](https://github.com/VKCOM/VKUI/issues/5688#issuecomment-2189010759))

### Скриншоты

![image](https://github.com/VKCOM/VKUI/assets/139550547/567da30c-ddeb-4d25-9a74-a861638d048e)

**Comment by qurle** [comment]
> нужно привести все варианты к одному токену - colorBackgroundContrastThemed

Все варианты должны быть приведены к токену `colorBackgroundModal`. В VKUI отвязываем от этого токена ненужные элементы (#6956) и затемняем его в [VKUI Tokens](https://github.com/VKCOM/vkui-tokens/pull/933) для повышения контрастности.

**Comment by mendrew** [comment]
> > нужно привести все варианты к одному токену - colorBackgroundContrastThemed
> 
> Все варианты должны быть приведены к токену `colorBackgroundModal`. В VKUI отвязываем от этого токена ненужные элементы (#6956) и затемняем его в [VKUI Tokens](https://github.com/VKCOM/vkui-tokens/pull/933) для повышения контрастности.

Cудя по коментарию мы отвязали ненужные компоненты от colorBackgroundModal в #6956 и уже обновили vkui-tokens https://github.com/VKCOM/VKUI/pull/7107.

Кажется, что на стороне VKUI уже сделано всё, что надо было.
Как думаешь, @qurle, мы можем закрывать эту задачу?

**Comment by qurle** [comment]
> Как думаешь, @qurle, мы можем закрывать эту задачу?

На самом деле, на стороне VKUI у нас уже всё было привязано к нужному токену, теперь мы его чуть улучшили, чтобы он стал удобным для всех.

Думаю, можно закрывать.
