### ISSUE TITLE
[Bug]: Поправить токен для текста в Tabbar

### ISSUE THREAD

**Issue by Dushart** [VKCOM/VKUI#5689]
### Описание

У нас сейчас отличается токен иконки и текста в Tabbar - нужно синкануть + понять, откуда такое пошло

### Скриншоты

<img width="292" alt="Снимок экрана 2023-08-24 в 12 52 10" src="https://github.com/VKCOM/VKUI/assets/139550547/f4d3db18-b5c0-4a23-9898-269bd4f95ffc">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.8.1" target="_blank">v5.8.1</a> 🎉
