### ISSUE TITLE
[Feature][Web]: Реализовать возможность создания динамических переменных

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#5697]
Для Web хочется иметь возможность создавать динамические переменные, чтобы на выходе получали CSS с медиа-выражениями.

На примере проблемы с бордерами это будет выглядеть так:

```css
:root {
  --vkui--size_border: 1px;
}

@media (min-resolution: 2dppx) {
  :root {
    --vkui--size_border: 0.5px;
  }
}

@media (min-resolution: 3dppx) {
  :root {
    --vkui--size_border: 0.33px;
  }
}
```

## Возможные проблемы

Затрудняет перебивание таких переменных через CSS – если пользователю необходимо перебить значения в медиа-выражении, то ему необходимо копировать это медиа-выражение к себе.

**Comment by 8coon** [comment]
Решили пойти другим путём и добавить в vkui-tokens три статических токена с разной толщиной бордера, а в стили VKUI добавить внутреннюю css-переменную, значение в которую задавать одним из трёх токенов в рутовом классе под media query. При этом в вёрсте предусмотреть фоллбеки, чтобы компоненты с бордерами не ломались, если их использовать вне рутового класса.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.0" target="_blank">v5.9.0</a> 🎉
