### ISSUE TITLE
[Feature]: Предоставить возможность для импорта типов Placement и ElementProps

### ISSUE THREAD

**Issue by Pavel1711** [VKCOM/VKUI#5699]
### Описание

Из-за отсутствия возможности импорта приходится использовать импорты 
`import type { Placement } from '@vkontakte/vkui/dist/lib/floating';`
`import type { ElementProps } from '@vkontakte/vkui/dist/hooks/useAdaptivityConditionalRender/types';`
Такие импорты нарушают изоляцию библиотеки.
Если не указать тип ElementProps, у нас появляются проблемы со сборкой, так как есть предупреждение

### Скриншоты

<img width="689" alt="Снимок экрана 2023-08-25 в 15 09 20" src="https://github.com/VKCOM/VKUI/assets/45904265/787a1cc5-1ab0-45c7-8ff8-f369e4ce4145">

**Comment by mendrew** [comment]
@Pavel1711 
Привет.

По поводу проблемы с `ElementProps` есть предположение, что `deviceType` возвращающийся из хука, используется неправильно.
Следует писать 
```jsx
{deviceType.desktop && <SplitCol className={deviceType.desktop.className} />}
```
Тогда не должно быть проблем со сборкой.

Посмотри пример из документации по [адаптивности](https://vkcom.github.io/VKUI/#/Adaptivity).
>  Теперь мы должны сообщить приложению, что левая колонка нужна только на больших экранах. Для этого нам нужно использовать хук useAdaptivityConditionalRender в своих компонентах. Далее будет пример, а следом объяснение, что делает хук.
 ```jsx
function App() {
  const platform = usePlatform();
  const isVKCOM = platform === Platform.VKCOM;
  const { viewWidth } = useAdaptivityConditionalRender();

  // ...

  <SplitLayout header={!isVKCOM && <PanelHeader separator={false} />}>
    {viewWidth.tabletPlus && (
      <SplitCol width={280} className={viewWidth.tabletPlus.className}>
        <Panel id="nav">Navigation</Panel>
      </SplitCol>
    )}
    <SplitCol autoSpaced>
      <View activePanel="profile">
        <Panel id="profile">Profile</Panel>
      </View>
    </SplitCol>
  </SplitLayout>;
  // ...
}
```
