### ISSUE TITLE
[Feature]: Добавить поддержку задания фиксированной высоты для десктоп версии модального окна

### ISSUE THREAD

**Issue by makevilface** [VKCOM/VKUI#5712]
### Описание

Сейчас на mvk существует модалка с динамическим содержимым, используется vkui версия модалки, для мобильной версии в компоненте предусмотрен проп settlingHeight для определения процента открытия окна, для дектоп версии он не дает ожидаемого результата. Необходимо добавить поведение для декстоп версии, чтобы содержимое могло иметь фиксированную высоту

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.0" target="_blank">v5.9.0</a> 🎉
