### ISSUE TITLE
[Feature]: Улучшить семантику FixedLayout

### ISSUE THREAD

**Issue by mainsmirnov** [VKCOM/VKUI#5714]
### Описание

Хотелось бы иметь возможность передать свойство Component в FixedLayout, так как он может являться кастомной шапкой, либо секций (например, когда блок является баннером)

Сразу можно импрувнуть семантику у PanelHeader
https://github.com/VKCOM/VKUI/blob/38a57c69222d86a184ed33fd937029c888631cc4/packages/vkui/src/components/PanelHeader/PanelHeader.tsx#L167-L170

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.5.0" target="_blank">v6.5.0</a> 🎉
