### ISSUE TITLE
[Feature][FormLayoutGroup]: vertical segmented

### ISSUE THREAD

**Issue by wd055** [VKCOM/VKUI#5716]
### Описание

В макетах есть вертикальный сгруппированный вариант FormLayoutGroup, но нет в VKUI

https://www.figma.com/file/2sQl2eaxsp7RDRdMOeneEC/%F0%9F%92%A0-VKUI-Common-Library?type=design&node-id=25142-202567&mode=design&t=U1C5ZLgc2UIMleH0-11

### Скриншоты

<img width="459" alt="image" src="https://github.com/VKCOM/VKUI/assets/35567000/4fdfec66-13f0-4972-8249-ede5cef00c10">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.0" target="_blank">v5.9.0</a> 🎉
