### ISSUE TITLE
ScreenSpinner не блокирует скролл в приложении

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#574]
Просто сделать скролл на странице (добавить много контента)
Установить в popout={ScreenSpinner} и скролить страницу.
Как видим она скроллится

https://youtu.be/Wh7HQEJhXlM

**Comment by ArthurStam** [comment]
Спасибо, поправим

**Comment by gbowsky** [comment]
Проблема неактуальна для мобильных устройств.

**Comment by ewgenius** [comment]
Перепроверил, все еще воспроизводится на десктопе

**Comment by SevereCloud** [comment]
Теперь со следующей версии точно будет блокировать
