### ISSUE TITLE
Новый мини-ад перфекциониста 

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#575]
Поправьте черноту, пожалуйста

Гитхаб отказался грузить изображение, поэтому вот:
https://sun9-24.userapi.com/c857120/v857120056/11f8c7/jtNEq1feRuA.jpg

**Comment by ilyapishchulin** [comment]
+ немножко в PanelHeaderContext

**Comment by ArthurStam** [comment]
Мы используем react-styleguidist для отрисовки документации. Можешь им этот issue отправить) у них какое-то время вообще всё плохо было с подсветкой кода. Щас получше. Но не идеально.

**Comment by ilyapishchulin** [comment]
Можно же поправить

**Comment by ArthurStam** [comment]
На нашей стороне? Как?

**Comment by ilyapishchulin** [comment]
А зачем юзать if, можно же коротким замутить и будет по красоте
`                  onClick={() => {
                    this.state.activeTab1 === 'news' ? 
                      this.setState({contextOpened: !this.state.contextOpened})
                    : null
                    this.setState({activeTab1: 'news'})
                  
                  }}`

**Comment by ilyapishchulin** [comment]
A Issue им тоже нужно завести, в PanelHeaderContext можно просто пропсы местами поменять)

**Comment by ArthurStam** [comment]
Я считаю, что вносить такие фиксы, чтобы было "по красоте" — неправильно. Правильнее пофиксить проблему на стороне либы.

**Comment by ilyapishchulin** [comment]
Ждем-с ответа, с тобой согласен
