### ISSUE TITLE
[Bug]: Сломали попапы

### ISSUE THREAD

**Issue by ZhukDmitryOlegovich** [VKCOM/VKUI#5759]
### Описание

При открытие попап рендериться в "нулях" левом верхнем углу, а потом прилетает куда надо

### Версия

5.8.0

### Шаги воспроизведения

Открываем попап

### Ожидаемое поведение

Попап отрисовался где надо и не моргает

### Скриншоты

<img width="1609" alt="Снимок экрана 2023-09-07 в 18 28 46" src="https://github.com/VKCOM/VKUI/assets/93006259/5fa60c99-6b88-4ed1-9d22-455651edab05">
<img width="1616" alt="Снимок экрана 2023-09-07 в 18 29 19" src="https://github.com/VKCOM/VKUI/assets/93006259/7ffcf9d4-e300-455a-afe0-bc5f64c0a539">

### Пример с воспроизведением

https://codesandbox.io/s/quiet-currying-jyyzlk

**Comment by ZhukDmitryOlegovich** [comment]
https://cloud.mail.ru/public/MDru/v4NVD42Rz видео с демо

**Comment by Fliqle** [comment]
help @inomdzhon

**Comment by ZhukDmitryOlegovich** [comment]
И уже не относиться к баге - но было бы славно, если бы на попап Select-а можно было бы свой className засетить - типо popupClassName =)

**Comment by inomdzhon** [comment]
Открыл PR с фиксом, затащим в **v5.8.2**

> И уже не относиться к баге - но было бы славно, если бы на попап Select-а можно было бы свой className засетить - типо popupClassName =)

А для какой кастомизации требуется? 🤔
