### ISSUE TITLE
[Bug][Tappable]: используется отсутствующий проп в доке

### ISSUE THREAD

**Issue by scffs** [VKCOM/VKUI#5760]
### Описание

TS2322: Type
{  borderRadiusMode: string; }
is not assignable to type  IntrinsicAttributes & TappableProps 
Property  borderRadiusMode  does not exist on type  IntrinsicAttributes & TappableProps 

https://vkcom.github.io/VKUI/#/Tappable?id=props

### Версия

5.7.2

**Comment by BlackySoul** [comment]
Привет! Документация всегда указывает по умолчанию на самую актуальную документацию, вижу, что указана версия `5.7.2`. Необходимую версию документации можно выбрать в шапке:

![image](https://github.com/VKCOM/VKUI/assets/7431217/428cdbd8-0725-4013-8649-3169cc086130)

**Comment by scffs** [comment]
А, этот проп добавили в новой? Тогда сорри, а то думал, что снова старое что-то..
