### ISSUE TITLE
[Bug]: Сломали сборку в Vite

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#5767]
### Описание

В коммите https://github.com/VKCOM/VKUI/commit/8050b03aa32916830a8a8980b52265f200da3d63 появилось использование не стандатной переменной окружения `process.env.NODE_ENVIRONMENT`

Всегда и везде используется `process.env.NODE_ENV`

Из за того, что переменная не стандартная ломается сборка в Vite, так как не срабатывает замена строк.

### Версия

v5.8.0

### В каких браузерах воспроизводится проблема?

Firefox, Chrome, Safari, Microsoft Edge, Yandex Browser, Другое (укажите в описании)

### Шаги воспроизведения

Собрать любое приложения используя vkui с помощью https://vitejs.dev/

### Ожидаемое поведение

Собирается

### Скриншоты

> Uncaught ReferenceError: process is not defined

**Comment by mahnunchik** [comment]
@inomdzhon твой коммит

**Comment by mahnunchik** [comment]
В 5.7.2 всё работает

**Comment by BlackySoul** [comment]
Привет, спасибо за бдительность, уже [знаем](https://github.com/VKCOM/VKUI/pull/5766) х)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.8.1" target="_blank">v5.8.1</a> 🎉
