### ISSUE TITLE
[Feature]: Добавить VerticalScroll

### ISSUE THREAD

**Issue by Dryzhakovv** [VKCOM/VKUI#5789]
### Описание

Добавить новый компонент или обновить уже существующий HorizontalScroll, чтобы работал не только по горизонтали, но и по вертикали, а также вынести ArrowScroll, для VerticalScroll.

### Скриншоты

<img width="1131" alt="image" src="https://github.com/VKCOM/VKUI/assets/37025364/5adb1970-22cd-4362-9009-7eaecf8a1db0">

**Comment by inomdzhon** [comment]
Спасибо за issue 🙏 

Но в рамках VKUI мы не планируем создавать такой компонент https://github.com/VKCOM/VKUI/issues/2499#issuecomment-1273231414.
