### ISSUE TITLE
PanelHeaderContext некорректно отображается на IOS 

### ISSUE THREAD

**Issue by mrqiz** [VKCOM/VKUI#579]
Если в PanelHeaderSimple поместить PanelHeaderButton, и добавить PanelHeaderContext, то на IOS контекст растянется на всю доступную ширину. Текст внутри сдвигается вправо, но должен оставаться в центре. 
![image](https://user-images.githubusercontent.com/49580687/76955255-e92bfc80-6922-11ea-837f-43790c8feb5c.png)

**Comment by ArthurStam** [comment]
Привет. А можно сниппет с кодом?

**Comment by mrqiz** [comment]
> Привет. А можно сниппет с кодом?

Держите:
`<PanelHeaderSimple separator={false} left={<PanelHeaderButton><Icon28Menu width="24" height="24" /></PanelHeaderButton> }>
    <PanelHeaderContent aside={<Icon16Dropdown />} >Москва</PanelHeaderContent>
</PanelHeaderSimple>`

**Comment by YerinAlexey** [comment]
> Если в PanelHeaderSimple поместить PanelHeaderButton, и добавить PanelHeaderContext, то на IOS контекст растянется на всю доступную ширину. Текст внутри сдвигается вправо, но должен оставаться в центре.
> ![image](https://user-images.githubusercontent.com/49580687/76955255-e92bfc80-6922-11ea-837f-43790c8feb5c.png)

Это соответствует поведению в нативом приложении?

**Comment by mrqiz** [comment]
@YerinAlexey, нет. Пример:
![C70D4468-6869-45C4-BDEE-9FC8EFE22649](https://user-images.githubusercontent.com/49580687/76960333-45dfe500-692c-11ea-8013-f86a4b914bcc.jpeg)

**Comment by ArthurStam** [comment]
Спасибо, поправим
