### ISSUE TITLE
[Bug]: ModalPage ломается скролл на iOs

### ISSUE THREAD

**Issue by JhonPsina** [VKCOM/VKUI#5793]
### Описание

**Платформа**: IOs

Если открыть ModalPage на iOs устройстве на весь экран, то при повторном открытии модалка сразу откроется на весь экран и скролл контента работать не будет. Если закрыть модалку со сломанным скроллом и открыть заново - бага исправится на одну итерацию, а потом снова воспроизведется.

[screen-recording.webm](https://github.com/VKCOM/VKUI/assets/26603858/bad600aa-fb82-4bc9-9bb8-5d621659254c)

### Версия

5.7.2 и новее

### Шаги воспроизведения

- Открыть MadalPage
- Свайпнуть ее на весь экран (скролл контента в MadalPage работает)
- Закрыть модалку
- Открыть снова -> модалка раскрывается сразу на весь экран, ModalPage__content не имеет скролла тк overflow-y: hidden

**Comment by inomdzhon** [comment]
Исправлено в [v5.9.0](https://github.com/VKCOM/VKUI/releases/tag/v5.9.0) ✅
