### ISSUE TITLE
[Feature]: Обновить border-radius для компонента Image

### ISSUE THREAD

**Issue by makevilface** [VKCOM/VKUI#5796]
### Описание

Сейчас у компонента Image максимальный border-radius для size <= 48 составляет 10px. Возникла необходимость в передаче 12px. С дизайнерами значения согласованы. Необходимо чтобы компонент мог поддержать border-radius 12px для соответствующих размеров, либо добавить возможность передать значение через style/className

**Comment by SevereCloud** [comment]
Оставляем 10px
