### ISSUE TITLE
[Suggestion] Подстраивать текст в TabbarItem под label.

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#580]
На данный момент label будет перекрывать текст при двух TabbarItem.

Соответственно можно подстраиваться и отодвигать его немного дальше, но не критично.

Мой вариант:
<img width="380" alt="Снимок экрана 2020-03-18 в 16 33 14" src="https://user-images.githubusercontent.com/45998835/76965926-39f92080-6936-11ea-880f-08a314126acd.png">
На данный момент:
<img width="381" alt="Снимок экрана 2020-03-18 в 16 34 08" src="https://user-images.githubusercontent.com/45998835/76966014-5f862a00-6936-11ea-91fb-4d53f76d4071.png">

**Comment by ArthurStam** [comment]
Надо бы посоветоваться с нашими дизайнерами

**Comment by Lihachyov** [comment]
По ощущениям, будет не очень выглядеть в динамике при сбросе счётчика. Сбрасываешь счётчик, а у тебя скачет текст в таббаре. Также хочется вкладку содержать компактной, чтобы не отнимать место у других табов в таббаре.

**Comment by ilyapishchulin** [comment]
Хорошо, я же говорю об отступе только для трех символов, дальше пусть накладывается, а у других табов место не будет отнимать, т.к. их всего два)

Спасибо
