### ISSUE TITLE
[Bug]: прозрачный слой поверх товаров и услуг

### ISSUE THREAD

**Issue by vladcliffe** [VKCOM/VKUI#5806]
### Описание

<div class="vkuitooltip__overlay"></div> 
Поверх товаров и услуг какой то прозрачный слой, все товары и услуги не активны

### Версия

unknown

### В каких браузерах воспроизводится проблема?

Chrome, Yandex Browser

**Comment by SevereCloud** [comment]
Привет, из описания не понятно о каком баге VKUI идёт речь
