### ISSUE TITLE
[Feature]: Мультиязычность в компонентах с выбором месяца

### ISSUE THREAD

**Issue by dsedinkin** [VKCOM/VKUI#5807]
### Описание

Например в компоненте DatePicker, можно использовать:
new Intl.DateTimeFormat("RU-ru", { day: "numeric", month: "short" }).format(date)

На текущий момент названия месяцев только на русском:
const DefaultMonths: string[] = [
  'Января',
  'Февраля',
  'Марта',
  'Апреля',
  'Мая',
  'Июня',
  'Июля',
  'Августа',
  'Сентября',
  'Октября',
  'Ноября',
  'Декабря',
];

**Comment by SevereCloud** [comment]
Привет, компонент DatePicker устарел и будет удален в следующей мажорной версии.

На замену ему можно использовать [Input](https://vkcom.github.io/VKUI/#/Input),  [Select](https://vkcom.github.io/VKUI/#/Select) и [DateInput](https://vkcom.github.io/VKUI/#/DateInput). О том что лучше использовать, можно прочитать в обсуждении:

- #7070
