### ISSUE TITLE
[Bug]: Не уходят варнинги @vkontakte/vk-bridge's deprecated

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#5811]
### Описание

Почему после добавления `isWebView`, `appearance` и `adaptivity` как описано в инструкции не уходят варнинги?

```
VKUI/ConfigProvider] [@vkontakte/vk-bridge's deprecated] Если вы используете VK Bridge, то:

1. используйте хук useAppearance() из @vkontakte/vk-bridge-react и результат передайте в параметр appearance;
2. передайте bridge.isWebView() в параметр isWebView;

Подробности см. https://github.com/VKCOM/VKUI/issues/5049

[VKUI/AdaptivityProvider] [@vkontakte/vk-bridge] Интеграция VKUI с @vkontakte/vk-bridge устарела и будет удалена в v6. Используйте хук `useAdaptivity()` из @vkontakte/vk-bridge-react и результат передайте в компонент (см. https://github.com/VKCOM/VKUI/issues/5049)

[VKUI/AppRoot] [@vkontakte/vk-bridge] Интеграция VKUI с @vkontakte/vk-bridge устарела и будет удалена в v6. Используйте хук `useInsets()` из @vkontakte/vk-bridge-react и результат передайте в параметр `safeAreaInsets` (см. https://github.com/VKCOM/VKUI/issues/5049)
```

### Версия

v5.8.1

### В каких браузерах воспроизводится проблема?

Firefox, Chrome, Safari, Microsoft Edge, Yandex Browser, Другое (укажите в описании)

### Шаги воспроизведения

Добавить требуемые изменения:

```js
  const adaptivity = useAdaptivity();
  const appearance = useAppearance();
  return (
    <React.StrictMode>
      <ConfigProvider isWebView={bridge.isWebView()} appearance={appearance}>
        <AdaptivityProvider adaptivity={adaptivity}>
```

### Ожидаемое поведение

Варнингов нет, так как приложение подготовлено к v6

**Comment by inomdzhon** [comment]
Спасибо за issue 🙏 

Где было возможно, сделано так, что варнинг не показывается если было выполнено условие. Это для `webviewType` в `ConfigProvider`, частично при передаче `safeAreaInsets` в `AppRoot` (нужно передать пустой объект по умолчанию). Есть ещё в `AdaptivityProvider` проверки, но они не срабатывают из-за особенности работы **vk-bridge** – он асинхронен, поэтому при первом рендере значений из него нет.

В остальных случаях варининги перманентны, т.к. нет возможности проверить, что используется **vk-bridge**, также не все св-ва являются обязательными, поэтому проверять на `undefined` не всегда вариант. Так же особенность работы **vk-bridge**, о котором написал выше.

> В описании issue опечатка:
>  ```diff
>   const adaptivity = useAdaptivity();
>   const appearance = useAppearance();
>   return (
>     <React.StrictMode>
>       <ConfigProvider isWebView={bridge.isWebView()} appearance={appearance}>
>  -          <AdaptivityProvider adaptivity={adaptivity}>
>  +          <AdaptivityProvider {...adaptivity}>
>  ```
>

Ближе к концу года выпустим **v6** – там этих варнингов не будет.
