### ISSUE TITLE
Разное поведение на платформах при очищении поля ввода

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#582]
Создаем Input с type="number"

На Android:
1. Тапаем по полю
2. Нажимаем удалить (Поле очищается)
На iOS:
1. Тапаем по полю
2. Нажимает "Очистить" (Нет реакции)

**Comment by ArthurStam** [comment]
Вот тут есть тикет на эту тему https://github.com/facebook/react/issues/8938

**Comment by ilyapishchulin** [comment]
Закрываем?

**Comment by ArthurStam** [comment]
Да
