### ISSUE TITLE
Добавьте, пожалуйтса компонент для остановки двойных кликов

### ISSUE THREAD

**Issue by ciricc** [VKCOM/VKUI#583]
Очень часто надо сделать какие-то дейтствие при клике (открыть ссылку, вызвать окно для публикации истории и т.д). Приложение ВК считает каждый клик как правильный, даже, если на данный момент клиент уже занят другим таким же кликом (то есть, например, открывает браузер два раза, если быстро нажать по внешней ссылке несколько раз, а не один).

Было бы удобно иметь компонент-обертку, который бы эти клики предотвращал. Просто из проекта в проект одна и та же проблема. А как я понимаю, ВК в приложении это фиксить не собираются.

Это просто для удобства, возможно это лишнее именно для VKUI, но фиг знает, решать вам.

**Comment by ArthurStam** [comment]
Второй клик можно игнорить, если у вас запущен долгий асинхронный процесс. Например, можно использовать `ScreenSpinner` или атрибут `disabled`. Не вижу смысла в таком компоненте.

**Comment by ciricc** [comment]
> Второй клик можно игнорить, если у вас запущен долгий асинхронный процесс. Например, можно использовать `ScreenSpinner` или атрибут `disabled`. Не вижу смысла в таком компоненте.

В этом и прикол, что disabled можно поместить в такой компонент-обертку, чтобы было проще в любом месте сделать такое.

**Comment by ArthurStam** [comment]
И всё ещё мне кажется, что это не тот кейс, который должна покрывать библиотека.
