### ISSUE TITLE
Сепаратор уходит под панель, а не исчезает.

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#584]
<PanelHeaderSimple separator={false}></PanelHeaderSimple>

При таком коде сепаратор прячется под шапку, а не исчезает.
Мне сказали это баг

**Comment by ilyapishchulin** [comment]
Я затупил

**Comment by ilyapishchulin** [comment]
Это баг или нет, вот в чем вопрос

**Comment by ArthurStam** [comment]
А в `Panel` передаешь `separator={false}`?

**Comment by ilyapishchulin** [comment]
Нет, свойство же PanelHeaderSimple принял

**Comment by ArthurStam** [comment]
Нет. В документации указано, что так как мы пока поддерживаем два типа шапки, разработчикам нужно всегда указывать separator={false} у Panel, если они используют PanelHeaderSimple. В 4-й версии это уйдет. Пока так.

**Comment by ilyapishchulin** [comment]
Ух, тогда прошу прощения, я подумал, что теперь можно только в 1 компонент передавать
