### ISSUE TITLE
[Doc]: В чем разница между `Text` и `Paragraph`?

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#5849]
### Описание

Хочется понять в чем разница между `Text` и `Paragraph`? Где использовать одно, а где другое.

Документация у этих двух элементов идентичная, хотя реализация немного различна.

**Comment by mahnunchik** [comment]
Собственно можно даже задать вопрос шире: зачем представлено многообразие `Title`, `Headline`, `Subhead`? Ведь это всё заголовки, почему нельзя было обойтись одним элементом с разными уровнями?

**Comment by SevereCloud** [comment]
Различие между типографикой в основном визуальное. Название типографических элементов соответствует своему предназначению

- Title для заголовков.
- Headline для подзаголовков
- Subhead для подзаголовков 2 уровня

Добавили минимальную информацию для типографики
- closed by #5968
