### ISSUE TITLE
[Android] Разное поведение на платформах InfoRow

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#585]
```
            <Cell>
                <InfoRow header="Описание:">
				    <div className="info_images_NASA">
					    {props.this.state.image_info_NASA.data[0].description}
				    </div>
                </InfoRow>
            </Cell>
```
Такой код не обрезается на iOS, а на Android требуется свойство multiline, может стоит сделать одинаковое поведение на платформах?

**Comment by ArthurStam** [comment]
Поправим, спасибо

**Comment by ilyapishchulin** [comment]
А можно тут вопрос задам? Как можно перекрасить зону эластик скролла?

**Comment by ArthurStam** [comment]
Как это относится к тикету? Если никак, то не стоит эту дискуссию тут продолжать.
