### ISSUE TITLE
[Doc]: Куда делаcь дока по `PanelHeaderBack`?

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#5850]
### Описание

https://github.com/VKCOM/VKUI/blob/v5.8.1/packages/vkui/src/components/PanelHeaderBack/PanelHeaderBack.tsx

А по ссылке https://vkcom.github.io/VKUI/#/PanelHeaderBack "Page not found"

**Comment by BlackySoul** [comment]
Привет! Так как не было смысла держать на такие атомарные компоненты по отдельной странице, вынесли их в общую [здесь](https://vkcom.github.io/VKUI/#/PanelHeaderButton)

Ссылки на актуальную документацию [поменяли](https://github.com/VKCOM/VKUI/pull/5851)

Спасибо за бдительность х)
