### ISSUE TITLE
[Bug]: в CardScroll стрелочка "влево" тригеррит onSubmit

### ISSUE THREAD

**Issue by svyatoslavpavlov** [VKCOM/VKUI#5852]
### Описание

При использовании CardScroll в форме клик по стрелочке влево тригеррит отправку форму, со стрелочкой "вправо" все ок

### Версия

5.8.0

### В каких браузерах воспроизводится проблема?

Chrome

**Comment by mendrew** [comment]
Привет, @svyatoslavpavlov!

Спасибо за обращение!

Действительно, внутри `CardScroll` используется `ScrollArrow`, который представляет собой кнопку, но без явного задания типа `button`. 
Скоро решим эту проблему.
