### ISSUE TITLE
[Feature][Image]: transparent режим для фона

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#5865]
### Описание

Хочется получить что-то типо пропа transparent, который будет отключать серый фон у Image, полезно для отображения картинок с прозрачностью 

### Скриншоты

![Снимок экрана 2023-09-25 в 13 19 39](https://github.com/VKCOM/VKUI/assets/42776347/3c9249dc-1bbb-4686-9794-fbcd3a3e3d55)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.0" target="_blank">v5.10.0</a> 🎉
