### ISSUE TITLE
[Feature][Tabs]: Доскролл на активный элемент при выборе 

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#5870]
### Описание

Хочется получить доскролл до активного таба в Tabs при выборе пользователем, хочется получить три состояния:

- start - выравнивание активного элемента слева в видимой области
- center - выравнивание активного элемента в центре видимой области
- end - выравнивание активного элемента справа видимой области

**Comment by eugpoloz** [comment]
> * left - выравнивание активного элемента слева в видимой области
> * center - выравнивание активного элемента в центре видимой области
> * right - выравнивание активного элемента справа видимой области

На всякий случай сразу хочу прокомментировать, что вместо left и right лучше думать про start и end, чтоб потом чуть меньше мучиться с поддержкой RTL.

**Comment by MrZillaGold** [comment]
@eugpoloz звучит круто, поправил в исходном варианте

**Comment by mendrew** [comment]
@MrZillaGold

> Хочется получить доскролл до активного таба в Tabs при выборе пользователем

Скажи, пожалуйста, когда ты говоришь про скролл ты имеешь ввиду пример из документации где можно доскроллить до невидимых `TabItems`?
https://vkcom.github.io/VKUI/#/Tabs

Я спрашиваю, потому что там `TabItems` лежат внутри `HorizontalScroll` компонента.
```tsx
      <Tabs mode={mode}>
        <HorizontalScroll arrowSize="m">
          <TabsItem
            selected={selected === 'groups'}
            disabled={disabled}
            onClick={() => setSelected('groups')}
          >
            Сообщества
          </TabsItem>
```
 
Если ты именно эту конфигурацию имеешь ввиду, то тогда, наверное, стоит это добавить в HorizontalScroll.
Или идея в том, чтобы сделать это универсально для Tabs?

Если есть какой-то пример кода, отличный от того, что есть в документации, было бы здорово на него посмотреть.

**Comment by MrZillaGold** [comment]
@mendrew привет! Да. Это вроде легко делается нативным api брузера, вот небольшой сниппет как это можно прикрутить

`
export const TabsItem = ({ className, ...restProps }: TabsItemProps): JSX.Element => {
  const { selected } = restProps;

  const ref = useRef<HTMLElement>(null);

  const { centered } = useTabsContext();

  useEffect(() => {
    if (!centered || !selected) {
      return;
    }

    ref.current?.scrollIntoView({
      inline: 'center',
      behavior: 'smooth',
    });
  }, [selected, centered]);
...
`

**Comment by mendrew** [comment]
> @mendrew привет! Да. Это вроде легко делается нативным api брузера - даже без доработок HorizontalScroll, вот небольшой сниппет как это можно прикрутить. Проп направления доскролла вешаем на Tabs и пробрасываем через контекст
> 
> ```
> export const TabsItem = ({ className, ...restProps }: TabsItemProps): JSX.Element => {
>   const { selected } = restProps;
> 
>   const ref = useRef<HTMLElement>(null);
> 
>   const { centered } = useTabsContext();
> 
>   useEffect(() => {
>     if (!centered || !selected) {
>       return;
>     }
> 
>     ref.current?.scrollIntoView({
>       inline: 'center',
>       behavior: 'smooth',
>     });
>   }, [selected, centered]);
> ...
> ```

Да, про `scrollIntoView` и контекст я сразу подумал, но не понравилось, что `scrollIntoView` при необходимости будет скроллить и вертикально, так как 'nearest' по умолчанию, а полностью отключить вертикальный скролл нельзя. Потому стал думать о том, как этого избежать и напридумывал сложности с другими API.

Сейчас поиграл с `nearest` ещё раз и могу сказать, что без надобности не скроллит и для большинства ситуаций должно с лихвой хватить простого `scrollIntoView`.

Спасибо, что снова на эту мысль навел!

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.0" target="_blank">v5.10.0</a> 🎉
