### ISSUE TITLE
[Bug]: FocusVisible иногда является причиной появления скролла в родительском элементе

### ISSUE THREAD

**Issue by mendrew** [VKCOM/VKUI#5871]
### Описание

Если расположить компоненты `Button` в элементе с фиксированной высотой, равной сумме высоты всех кнопок, то у этого элемента при `overflow: auto` появится скролл, хотя кнопки в отдельности имеют фиксированную высоту которая должна позволить уместить их в таком родителе.

Это происходит из-за специального компонента `FocusVisible`, который есть в каждом интерактивном компоненте.
Он позволяет рисовать при навигации с клавиатуры фокус на активном элементе.
`FocusVisible` имеет разные режимы (у `Button` режим по умолчанию `outline`)
В режиме `outline` фокус рисуется вокруг компонента, для этого абсолютно позиционированному `FocusVisible` задаются отрицательные значение `top/right/bottom/left` чтобы он вылезал за пределы родителя и рисовал фокус снаружи. Эта особенность и вызывает появление скролла у родителя интерактивного элемента.

Проблема в том, что эта особенность влияет даже без активного состояния `focused`, что неправильно.
То есть `FocusVisible` не используется, а на родителя интерактивного элемента влияет.

Что интересно, в версиях библиотеки 5.0.x такого не наблюдается, потому что `top/right/bottom/left` применяется к `FocusVisible` только когда есть фокус на элементе.
https://github.com/VKCOM/VKUI/blob/10872a431b583569f4f4714891d4aae3f69217e8/src/components/FocusVisible/FocusVisible.module.css#L1-L20

В последних версиях `top/right/bottom/left` задан сразу, потому так и влияет, даже без фокуса.
https://github.com/VKCOM/VKUI/blob/11c3e0a81b7523323c98fc36c22b6c3e0ee8450d/packages/vkui/src/components/FocusVisible/FocusVisible.module.css#L1-L16

### Версия

5.8.2

### Ожидаемое поведение

FocusVisible не должен быть причиной появления скролла у родителя интерактивного элемента.

### Скриншоты

<img width="718" alt="FocusVisible mode='outside'" src="https://github.com/VKCOM/VKUI/assets/5443359/4588a514-b336-4bb4-bbe4-3edaa1c7c37d">
<img width="718" alt="FocusVisible mode='inside'" src="https://github.com/VKCOM/VKUI/assets/5443359/0c60dae4-9c14-4089-9610-7f8d4ead439d">

### Пример с воспроизведением

https://codesandbox.io/s/epic-feather-r8dsg2?file=/src/App.tsx

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.0" target="_blank">v5.10.0</a> 🎉
