### ISSUE TITLE
Неправильные отступы в хедере

### ISSUE THREAD

**Issue by wayshev** [VKCOM/VKUI#588]
— Стрелка назад на пару точек правее, чем нужно;
— Тайтл на точку выше, чем нужно;
— Кроме того отличается размер и/или леттерспейсинг у тайтла.

![image](https://user-images.githubusercontent.com/61538408/77330207-0bad8380-6d30-11ea-908a-0534a64dc14c.png)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.2" target="_blank">v5.9.2</a> 🎉
