### ISSUE TITLE
[Bug]: .vkuiHorizontalCell__content присутствует в компоненте всегда

### ISSUE THREAD

**Issue by 3all** [VKCOM/VKUI#5883]
### Описание

Мы часто используем HorizontalCell, но не всегда прокидываем header, subtitle и тд. Но .vkuiHorizontalCell__content присутствует всегда и забирает 10px пространства. Приходится делать margin-bottom: -10px для компонента внутри HorizontalCell.

### Версия

5.7.2

### В каких браузерах воспроизводится проблема?

Firefox, Chrome, Safari, Microsoft Edge, Yandex Browser

### Шаги воспроизведения

создать `<HorizontalCell` size="l">` без остальных пропсов, проверить DOM на наличие .vkuiHorizontalCell__content

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.0" target="_blank">v5.9.0</a> 🎉
