### ISSUE TITLE
В PanelHeaderSimple ломается верстка, если в проп right передать компонент Avatar

### ISSUE THREAD

**Issue by shalfey41** [VKCOM/VKUI#589]
Компонент с `PanelHeader`

<img width="395" alt="Снимок экрана 2020-03-23 в 18 06 07" src="https://user-images.githubusercontent.com/9959518/77331233-7f03c500-6d31-11ea-888c-053a13808793.png">

А вот с `PanelHeaderSimple`

<img width="397" alt="Снимок экрана 2020-03-23 в 18 07 40" src="https://user-images.githubusercontent.com/9959518/77331220-7a3f1100-6d31-11ea-9bb9-c11687e941ff.png">

<img width="993" alt="Снимок экрана 2020-03-23 в 18 08 00" src="https://user-images.githubusercontent.com/9959518/77331229-7d3a0180-6d31-11ea-89ed-69d1d5f87048.png">

**Comment by ArthurStam** [comment]
Окей, добавим
