### ISSUE TITLE
[Bug][ModalPage]: Cкролл иногда остается даже в свернутом состоянии модалки

### ISSUE THREAD

**Issue by mendrew** [VKCOM/VKUI#5901]
https://github.com/VKCOM/VKUI/assets/7431217/731ccb19-1df8-4a5d-9576-f8e32c48eb11

_Originally posted by @BlackySoul in https://github.com/VKCOM/VKUI/issues/5845#issuecomment-1739533345_

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.2" target="_blank">v5.9.2</a> 🎉
