### ISSUE TITLE
[Bug]: у Button отступ слева stretched и before

### ISSUE THREAD

**Issue by mclaran** [VKCOM/VKUI#5904]
### Описание

У компонента Button, указать параметры: stretched и before, в before добавить иконку, текст при этом не указывать
Кнопка становится на всю ширину, но иконка со сдвигом слева, есть лишний padding

### Версия

5.1.0 и выше

### Шаги воспроизведения

У компонента Button, указать:
- stretched
- before
- текст при этом не указывать

### Ожидаемое поведение

Кнопка на всю ширину, before  по центру, текста нет

### Скриншоты

https://ibb.co/7YhgKC8

### Пример с воспроизведением

https://vkcom.github.io/VKUI/5.1.0/#/Button

**Comment by BlackySoul** [comment]
[Duplicate](https://github.com/VKCOM/VKUI/issues/4049)
