### ISSUE TITLE
[Feature]: В элементе Select/CustomSelect показывать options без скролла

### ISSUE THREAD

**Issue by EgorTarnaev** [VKCOM/VKUI#5915]
### Описание

Добавить в элементы Select/CustomSelect возможность при фокусе показывать все options без скролла

### Скриншоты

<img width="369" alt="Снимок экрана 2023-10-04 в 16 06 16" src="https://github.com/VKCOM/VKUI/assets/95924830/ccf48b49-2d90-48fc-bd57-186edbd9d9de">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.0" target="_blank">v5.10.0</a> 🎉
