### ISSUE TITLE
[Feature]: Расширить HorizontalCellProps до TappableProps

### ISSUE THREAD

**Issue by vakolesnikov** [VKCOM/VKUI#5917]
https://github.com/VKCOM/VKUI/blob/b15428df97b48a988cd932f1f179861f43824826/packages/vkui/src/components/HorizontalCell/HorizontalCell.tsx#L29

Необходимо расширить HorizontalCellProps до TappableProps. Например сейчас нет возможности отключить поведение  hasHover, hasActive

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.0" target="_blank">v5.10.0</a> 🎉
