### ISSUE TITLE
Выделение компонентов

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#592]
Часть компонентов VKUI доступна для выделения (user-select), часть недоступна.

В рамках тикета хотелось бы:

1. Привести это поведение VKUI к единообразию.
2. Дать подсказку разработчикам в документации, как работать с `user-select` у кастомных компонентов.

Свазанные тикеты:

* https://vk.com/bug111903
* https://vk.com/bug211306 (обсуждение в скрытых)

**Comment by ArthurStam** [comment]
Привет, спасибо, подумаем

**Comment by mahnunchik** [comment]
[20200319_185431.mp4.zip](https://github.com/VKCOM/VKUI/files/4893510/20200319_185431.mp4.zip)

Перезалил скринкаст проблемы. Доступ к трекеру продукта закрыт от всех, а ссылка на видео протухла.

**Comment by ArthurStam** [comment]
Логика следующая — мы разрешаем `user-select: text` только у `Header` и `InfoRow`, потому что это наиболее популярные компоненты в плане выделения. Всё остальное по-умолчанию выделять нельзя, но разработчик может сам произвольно проставить `user-select: text` там, где ему это нужно. 

Описывать этот момент в документации не вижу смысла, так как это основы CSS, а мы все тут фронтендеры.
