### ISSUE TITLE
ModalPageHeader залезает на системные кнопки VK Mini Apps

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#593]
Шаги воспроизведения:

1. Открыть приложение использующее модальные окна https://vkcom.github.io/vkui-styleguide/#section-modals
2. Открыть модальное окно
3. Развернуть свайпом на весь экран

Текст ModalPageHeader залезает на системные кнопки

Варианты решения:

1. Не разворачивать модалку на отступ равный хедеру страницы.
2. Рекомендации разработчику в документации о размере заголовка ModalPageHeader.

Связанные тикеты:

* https://vk.com/bug211329
* https://vk.com/bug211916

**Comment by fedorov-xyz** [comment]
Добрый день. Прочтите внимательно вот эту страницу – https://vkcom.github.io/vkui-styleguide/#!/ModalRoot

Часть про `ConfigProvider`.

**Comment by mahnunchik** [comment]
@fedorov-xyz Супер! Как быстро нашлось решение, а то ждал и никто не отвечал в трекере.

**Comment by fedorov-xyz** [comment]
Отлично :)
Рекомендую читать документацию.

**Comment by mahnunchik** [comment]
@fedorov-xyz ну дык, не всегда по глазам.

Плюс для этого и существует публичный трекер (тут), а не как получилось с https://vk.com/bugs?product=189 когда вопросы годами висят и их никто не просматривает. Хотя фикс в документации.
