### ISSUE TITLE
Модальные окна и скролл в вебе

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#594]
1. Открыть модальное окно с количеством контента требующего прокрутку.
2. Прокрутить (мышь, трекпад).

Фактический результат: Прокручивается страница "на фоне"
Ожидаемый результат: Прокручивается контент модалки.

Оригинальный тикет:

* https://vk.com/bug211917
* https://vk.com/bug211334 
* https://vk.com/bug211456

**Comment by fedorov-xyz** [comment]
Мы не поддерживаем библиотеку на десктопах.

Но эту проблему постараемся исправить, к тому же, такой тикет уже есть – https://github.com/VKCOM/VKUI/issues/331

**Comment by mahnunchik** [comment]
@fedorov-xyz как я понимаю, тикет можно переоткрывать, даёшь VKUI для десктопа! https://github.com/VKCOM/VKUI/pull/865/files

**Comment by mahnunchik** [comment]
пинг

**Comment by SevereCloud** [comment]
Фикс в [v4.29.1](https://github.com/VKCOM/VKUI/releases/tag/v4.29.1)
