### ISSUE TITLE
[Bug]: Modal + accessibility + Windows + NVDA

### ISSUE THREAD

**Issue by ntvsx193** [VKCOM/VKUI#5943]
### Описание

Не устанавливается фокус в модальное окно на Windows + NVDA. Остается висеть на кнопке, с которой вызывали модальное окно.
На macOS с включенным VoiceOver в хроме фокус корректно перемещается в модальное окно.

### Версия

5.8.2

### В каких браузерах воспроизводится проблема?

Другое (укажите в описании)

**Comment by inomdzhon** [comment]
Duplicate of #5646
