### ISSUE TITLE
[Feature]:  В элементы CustomSelect и CustomSelectOption добавить multiline

### ISSUE THREAD

**Issue by SLVor** [VKCOM/VKUI#5949]
### Описание

Если внутри CustomSelect у компонентов есть длинный title, нужно иметь возможность разбивать его на несколько строк, нужна поддержка multiline по аналогии с обычным Select. Также нужна возможность разместить в несколько строк подзаголовок пункта. Пример на скриншоте, с небольшими допущениями.

### Скриншоты

<img width="404" alt="image" src="https://github.com/VKCOM/VKUI/assets/15837771/65f9e3d9-864f-4018-90c8-5d3289a16201">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.2" target="_blank">v5.9.2</a> 🎉
