### ISSUE TITLE
[Feature][Separator]: Возможность покраски компонента

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#5955]
### Описание

Сейчас есть три цветовых токена сепаратора - primary/primary_alpha/secondary, хочется получить проп для установки этих токенов в качестве цвета компонента

`mode = 'primary' | 'secondary' | 'primary-alpha'` (?)

### Скриншоты

![Снимок экрана 2023-10-11 в 11 18 32](https://github.com/VKCOM/VKUI/assets/42776347/895bc787-6949-462a-9c70-5a176b2a40a4)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.3.0" target="_blank">v6.3.0</a> 🎉
