### ISSUE TITLE
Аватарка выше тени шапки у ModalPageHeader

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#596]
Шаги воспроизведения: Открыть модалку в которой присутвует аватарка.

Фактический результат: Аватарка выше тени шапки у ModalPageHeader.
Ожидаемый результат:  Весь контент ниже тени шапки при промотке.

Оригинальные тикеты:

* https://vk.com/bug211448
* https://vk.com/bug211919

**Comment by fedorov-xyz** [comment]
Приложите скриншот проблемы, пожалуйста. Нет доступа к отчёту.

**Comment by mahnunchik** [comment]
По поводу доступа к отчётам в ВК трекере тоже заведена бага (в ВК трекере).

Продукты:

* https://vk.com/bugs?act=product&id=189
* https://vk.com/bugs?act=product&id=592

---

Оригинальный скринкаст: https://vk.com/doc73391172_540429171?hash=75d85731d64a5b027b&dl=a6158f20f44cafc703

**Comment by mahnunchik** [comment]
[SVID_20200319_200253_1.mp4.zip](https://github.com/VKCOM/VKUI/files/4893506/SVID_20200319_200253_1.mp4.zip)

Перезалил скринкаст проблемы. Доступ к трекеру продукта закрыт от всех, а ссылка на видео протухла.

**Comment by gbowsky** [comment]
Неактуально в v4.
