### ISSUE TITLE
Закрытие модалки: курсор инпута остаётся на экране

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#598]
Шаги воспроизведения:
1. Открыть модалку содержащую инпут (Search https://vkcom.github.io/vkui-styleguide/#search)
2. Подвинуть модалку (свернуть/развернуть)

Фактический результат: До тех пор пока модалка полностью не закрыта, курсор ввода будет моргать на экране, где уже по факту нет инпута.

Ожидаемый результат: Курсора нет.

Скринкаст: https://vk.com/doc327617_542976655?hash=efe40996e3f28253e6&dl=5548211b6878e5c1d4

Оригинальный тикет:

* https://vk.com/bug211610
* https://vk.com/bug211921

**Comment by mahnunchik** [comment]
[IMG_2461.mp4.zip](https://github.com/VKCOM/VKUI/files/4893497/IMG_2461.mp4.zip)

Перезалил скринкаст проблемы. Доступ к трекеру продукта закрыт от всех, а ссылка на видео протухла.

**Comment by pfrankov** [comment]
https://stackoverflow.com/questions/20737503/mobile-safari-input-caret-does-not-scroll-along-with-overflow-scrolling-touch
Кажется, что баг мобильного Сафари
https://bugs.webkit.org/show_bug.cgi?id=138201
