### ISSUE TITLE
Не скролится модалка пока открыта клавиатура

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#599]
Шаги воспроизведения:

1. Открыть длинную модалку с инпутом (search).
2. Открыть клавиатуру.
3. Попытаться проскроллить модалку.

Фактический результат: Модалка не скроллится. до тех пор, пока мы не закроем клавиатуру.

Ожидаемый результат: Модалка скроллится.

Скринкаст:

* https://vk.com/doc327617_542976920?hash=22e3f0f057cb404099&dl=75c0e6d9d409322552
* https://vk.com/doc327617_542976978?hash=77b41806b574c00751&dl=c25c1d99b72a685115

Оригинальный тикет:

* https://vk.com/bug211611
* https://vk.com/bug211923

**Comment by mahnunchik** [comment]
[IMG_2463.mp4.zip](https://github.com/VKCOM/VKUI/files/4893485/IMG_2463.mp4.zip)
[IMG_2464.mp4.zip](https://github.com/VKCOM/VKUI/files/4893486/IMG_2464.mp4.zip)

Перезалил скринкаст проблемы. Доступ к трекеру продукта закрыт от всех, а ссылка на видео протухла.

**Comment by inomdzhon** [comment]
Частично исправилось в #6759 – можно скроллить сам контент. Когда открывается клавиатура, отключается возможность закрывать свайпом модалку.

- подробнее см. [**Решение** -> _Поля ввода_](https://github.com/VKCOM/VKUI/pull/6759#solves_text_inputs)
