### ISSUE TITLE
[Bug]: отсутствует hover эффект при наведении стилусом

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#5997]
### Описание

При попытке навести на элемент стилус нет hover эффекта.

### Версия

5.9.2

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

1. Взять активный стилус(в моем случае стилус поддержки USI 2.0)
2. Взять устройство поддерживающее стилус(в моем случае Pixel Tablet)
3. Попробовать навести стилус на элемент, с которым можно взаимодействовать

### Ожидаемое поведение

Появится ховер

**Comment by SevereCloud** [comment]
На текущий момент ситуация следующая:

- В хроме для стилусов USI 2.0 вообще не работает наведение(нужно найти/создать баг хроумиме)
- Файрфокс наведение стилусом работает, но hover эффекты от Tappable не работают

---

Как оказалось `pointerout` и `pointerleave` для стилусов работают неправильно и в хроме и в файрфоксе:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1608938
- https://bugs.chromium.org/p/chromium/issues/detail?id=1492111

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.4" target="_blank">v5.9.4</a> 🎉
