### ISSUE TITLE
[Bug]: CSS before в Popover

### ISSUE THREAD

**Issue by wd055** [VKCOM/VKUI#5998]
### Описание

При каких-то условиях `:before` у `Popover` перекрывает content и делает его некликабельным.

### Версия

5.5.0

**Comment by inomdzhon** [comment]
Правили в [v5.7.0](https://github.com/VKCOM/VKUI/releases/tag/v5.7.0), в этом PR https://github.com/VKCOM/VKUI/pull/5555

Попробуешь обновиться плиз?
