### ISSUE TITLE
[Bug]: Длинный контент в Alert выходит за границу

### ISSUE THREAD

**Issue by wd055** [VKCOM/VKUI#5999]
### Описание

Длинный контент в `Alert` выходит за границу

### Версия

5.9.2 (любая)

### Шаги воспроизведения

Добавить в алерт длинный `header` или `text`.

### Ожидаемое поведение

Длинное слово должно переноситься. Возможно другое поведение, кроме выхода за границу

### Скриншоты

<img width="620" alt="image" src="https://github.com/VKCOM/VKUI/assets/35567000/ea79e015-78a5-4c0e-8451-459c24963854">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.3" target="_blank">v5.9.3</a> 🎉
