### ISSUE TITLE
[Feature]: Rename Select to AdaptiveSelectRender

### ISSUE THREAD

**Issue by dsedinkin** [VKCOM/VKUI#6003]
### Описание

https://vkcom.github.io/VKUI/#/Select

Не совсем сразу понятно что это не обычный Select как Native. Тут же речь больше про то что универсальность поддерживается

**Comment by inomdzhon** [comment]
Спасибо за issue

Годная идея, рассмотрим изменение в **v6** 👍

**Comment by inomdzhon** [comment]
Решили, что переименовывать пока не будем.

К следующей мажорной версии рассмотрим вариант оставить только один компонент со свойством, например, `enableNativeDropdown`.

```tsx
<Select enableNativeDropdown />
// или
<Select enableNativeDropdown="on-mobile" />
```
