### ISSUE TITLE
[Feature]: Добавить анимацию в Accordion

### ISSUE THREAD

**Issue by Pavel1711** [VKCOM/VKUI#6007]
### Описание

Элементы в компоненте Accordion "прыгают" при нажатии. Хотелось бы добавить анимацию, чтобы пользователю было приятнее пользоваться этим элементом. Ожидается что-то похожее на элемент Collapse из Bootstrap. (https://getbootstrap.com/docs/4.0/components/collapse/)

**Comment by inomdzhon** [comment]
Спасибо за issue 🙏 

Занимаемся этим https://github.com/VKCOM/VKUI/pull/5206

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
