### ISSUE TITLE
[Feature][CustomScrollView]: Возможность установки zIndex

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6008]
### Описание

Сейчас у CustomScrollView нет возможности менять zIndex, при реализации блоков со sticky элементами скроллбар попадает под закрепленные элементы, из-за того что им устанавливается zIndex = 1, чтобы предотвратить наслаивание контента.

https://github.com/VKCOM/VKUI/assets/42776347/7dcfa33a-4a70-4632-ae05-5c9fc7e0b9aa

**Comment by SevereCloud** [comment]
Что насчет [изоляции](https://developer.mozilla.org/en-US/docs/Web/CSS/isolation) внутреннего контента?

**Comment by MrZillaGold** [comment]
@SevereCloud не помогает

**Comment by SevereCloud** [comment]
@MrZillaGold можешь дать [минимальный пример](https://vk.cc/vkuits)
