### ISSUE TITLE
Конфу: Закрытие модалки и Swipe Back одним тачем

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#601]
Закрытие модалки и Swipe Back одним тачем

Шаги воспроизведения:

1. Открыть вью поддерживающее Swipe Back.
2. Поверх открыть "длинную" модалку.
3. Совершить свайп из **верхнего левого** в **нижний правый** угол.

Фактический результат: Закрывается модалка и вью.

Ожидаемый результат: Жест ловит только модалка и закрывается.

Скринкаст: https://vk.com/doc337094267_541389839?hash=03dd54b5b875a3507c&dl=7929e3a9e880e7b934

Оригинальный тикет:

* https://vk.com/bug212373
* https://vk.com/bug212373

**Comment by ArthurStam** [comment]
Привет. А это точно баг библиотеки, а не приложения?

**Comment by mahnunchik** [comment]
Привет.

То что в библиотеки, вот такие соображения:

1. В модалках нет ничего слишком кастомного.
2. Воспроизводится на обеих длинных модалках
3. Тем более жесты кастомные нигде в приложении не слушаются.

В оригинальном репорте https://vk.com/bug212373 в симптомах ещё перечислено залипание интерфейса, кроме таббара. Похоже на экране остаётся прозрачная подложка.

**Comment by ArthurStam** [comment]
У меня нет туда доступа

**Comment by mahnunchik** [comment]
На время ломается меню подписок при определенных действиях.

Шаги воспроизведения:
1. Открыть раздел подписок.
2. Начать создавать подписку.
3. На выборе города (прибытия/отправления, без разницы) вытянуть меню на максимум, а потом свайпом из левого верхнего угла в правый нижний закрыть и меню выбора города, и черновик создания подписки. (именно одним свайпом, не двумя, на видео видно)
4. В окне которое предлагает сохранить или потерять подписку выбираем «потерять».

Фактический результат:
Когда закрываем черновик таким образом, перестаёт откликаться на нажатия меню подписок. Работает только таббар, посредством которого можно воскресить сервис, но если после нажатия на «горячие» или «ещё» вернуться в меню подписок, мы увидим там ту самую подписку, которую удалили с помощью свайпа.

Ожидаемый результат:
Когда я свайпаю с левого верхнего угла в правый нижний, сначала закрывается меню выбора города, а потом создание подписки (то есть надо сделать два свайпа). И при нажатии «потерять» подписка удаляется, а не сохраняется.

**Comment by mahnunchik** [comment]
[FullSizeRender.mov.zip](https://github.com/VKCOM/VKUI/files/4893470/FullSizeRender.mov.zip)

Перезалил скринкаст проблемы. Доступ к трекеру продукта закрыт от всех, а ссылка на видео протухла.

**Comment by pfrankov** [comment]
Кажется, что так и не должно работать
