### ISSUE TITLE
Зависание интерфеса при свайпе внизу длинной модалки на iOS

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#602]
Зависание интерфеса при свайпе внизу длинной модалки на iOS

Шаги воспроизведения:

1. Открыть длинную модалку.
2. Домотать до низа.
3. Дождаться остановки анимации.
4. Свайпнуть **внизу** экрана снизу вверх.

Фактический результат: Интерфес блокируется.

Если сама View длинная, то появляется второй скролл и скрллится View под модалкой.

Разблоаировть интерфес иногда получается кликами в верхней области экрана.

Ожидаемый результат: Свайп модалки вверх

Скринкаст: https://vk.com/doc304358149_540962497?hash=59c07e2324f20b9941&dl=a5dec713cfabd39095

Оригинальный тикет:

* https://vk.com/bug212453
* https://vk.com/bug212381

**Comment by mahnunchik** [comment]
[IMG_0334.mp4.zip](https://github.com/VKCOM/VKUI/files/4893467/IMG_0334.mp4.zip)

Перезалил скринкаст проблемы. Доступ к трекеру продукта закрыт от всех, а ссылка на видео протухла.

**Comment by pfrankov** [comment]
Кажется, что проблема приложения, а не VKUI
