### ISSUE TITLE
Зависание интерфейса при быстром закрытии модалок и алертов

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#603]
Элементы которые имеют "подложку" (алерт, модалка) при достаточно быстром клике на закрыть/отменить/скрыть скрывают визуально свой элемент, но не закрывает "подложку" из за чего интерфейс блокируется.

Очень долго ловил багу сам, но поймал.

* https://vk.com/doc346244785_542035527?hash=2f5b1b2ef0a446a573&dl=fd5a8ee16634eea181
* https://vk.com/doc346244785_542100565?hash=4c72143cea31dec554&dl=20ebf88370558053d9
* https://vk.com/doc346244785_542006430?hash=c60e1743881601d821&dl=a1e9147c5df2050ca4
* https://vk.com/doc346244785_541642029?hash=b8e5f1a6e46a2aeb87&dl=96f7bafd7038b0f9ee
* https://vk.com/doc346244785_541584986?hash=601f3a9c423f06d408&dl=61ccd8fd76091c1f47
* https://vk.com/doc346244785_542099469?hash=c1c7006ed0d20a1a40&dl=643ec70f18dd0f04e9
* https://vk.com/doc346244785_542035333?hash=533554170d7c5dc612&dl=b50ffc226e99308102

Оригинальные репорты (много обсуждений и подробностей):

* https://vk.com/bug212410
* https://vk.com/bug211835

**Comment by mahnunchik** [comment]
Скорее всего связанная проблема https://github.com/VKCOM/VKUI/issues/482

**Comment by ilyapishchulin** [comment]
Именно, дубликат

**Comment by mahnunchik** [comment]
[bandicam_2020-03-21_02-49-38-910.mp4.zip](https://github.com/VKCOM/VKUI/files/4893454/bandicam_2020-03-21_02-49-38-910.mp4.zip)
[bandicam_2020-03-21_15-24-28-388.mp4.zip](https://github.com/VKCOM/VKUI/files/4893455/bandicam_2020-03-21_15-24-28-388.mp4.zip)
[bandicam_2020-03-23_21-19-14-787.mp4.zip](https://github.com/VKCOM/VKUI/files/4893456/bandicam_2020-03-23_21-19-14-787.mp4.zip)
[bandicam_2020-03-24_14-22-46-519.mp4.zip](https://github.com/VKCOM/VKUI/files/4893457/bandicam_2020-03-24_14-22-46-519.mp4.zip)
[bandicam_2020-03-24_14-27-50-256.mp4.zip](https://github.com/VKCOM/VKUI/files/4893459/bandicam_2020-03-24_14-27-50-256.mp4.zip)
[SVID_20200324_010956_1.mp4.zip](https://github.com/VKCOM/VKUI/files/4893460/SVID_20200324_010956_1.mp4.zip)
[SVID_20200324_011810_1.mp4.zip](https://github.com/VKCOM/VKUI/files/4893461/SVID_20200324_011810_1.mp4.zip)

Перезалил скринкаст проблемы. Доступ к трекеру продукта закрыт от всех, а ссылка на видео протухла.

Если у вас получится получить доступ к оригинальным тикетам, то там обсуждение и подробности от тестеров.

**Comment by ilyapishchulin** [comment]
Можешь закрывать ишью, это полностью #482

**Comment by mahnunchik** [comment]
нда, с модалками беда...

**Comment by gbowsky** [comment]
Дубликат #482
