### ISSUE TITLE
На ios некорректно работает скролл в модальном окне.

### ISSUE THREAD

**Issue by duceum** [VKCOM/VKUI#604]
В длинном модальном окне первый скролл после раскрытия не срабатывает. Иногда нужно 1-4 свайпа вниз, чтобы скролл в модалке заработал.

Воспроизведение бага можно посмотреть на видео:
https://www.youtube.com/watch?v=jhpxeKEdcSQ&t=0s

**Comment by ArthurStam** [comment]
Таких тикетов уже несколько. Пожалуйста, проявите терпение и поищите уже заведенные issue перед публикацией своего. Спасибо.

**Comment by duceum** [comment]
Больше всего был похож этот #594 ,но тут похожая проблема проявляется и на ios.
