### ISSUE TITLE
[Вопрос] Slider с большим диапазоном значений

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#605]
Решил задать вопрос тут, возможно у команды VKUI есть что порекомендовать.

[Slider](https://vkcom.github.io/vkui-styleguide/#slider) хорошо работает, если в нём до 100 дискретных значений. Если больше, то пользоваться им уже не удобно.

Оригинальная задача: указать пороговую цену тура.

* Валидный диапазон значений от 1000 (тысячи рублей тур в Сочи без перелета) до 10.000.000 (миллион рублей за тур на Сейшелы для семьи из 5 человек).
* Точные числа не важны. Поэтому не подходит текстовый/числовой инпут.

---

В настоящее время реализовал слайдером с динамической верхней границей и шагом. Задачу решает, но ползунок прыгает https://vk.com/doc248201193_540571807?hash=f2bd3113db5594aa94&dl=7f31818fce96c2bddc

Оригинальный репорт: https://vk.com/bug211360

Может быть есть рекомендации, как решить эту задачу?

**Comment by mahnunchik** [comment]
[SVID_20200319_190547_1.mp4.zip](https://github.com/VKCOM/VKUI/files/4893445/SVID_20200319_190547_1.mp4.zip)

Перезалил скринкаст проблемы. Доступ к трекеру продукта закрыт от всех, а ссылка на видео протухла.

**Comment by ArthurStam** [comment]
Не уверен, что наш слайдер годится для такой задачи. Можно попробовать написать слайдер с логарифмической шкалой, либо использовать текстовые поля с type="number". Не понимаю, почему ты считаешь, что они не подходят.

**Comment by mahnunchik** [comment]
Поле с type="number" не подходит, так как не нужно точное значение.

**Comment by ArthurStam** [comment]
Не понял, куда смотреть. Посмотрел пример в приложении cian, там стоимость выставляется двумя инпутами, например. Энивей, мы в слайдере не планируем вводить логарифмическую шкалу.
