### ISSUE TITLE
[Bug][IconButton]: Растягивается компонент в режиме ссылки

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6057]
### Описание

Сейчас ширина IconButton не закреплена свойством, при использовании компонента в режиме ссылки в ячейки таблицы, он растягивается.

### Версия

5

### В каких браузерах воспроизводится проблема?

Chrome

### Ожидаемое поведение

Свойство  `width: fit-content;` на компоненте

### Скриншоты

![Снимок экрана 2023-10-26 в 18 02 12](https://github.com/VKCOM/VKUI/assets/42776347/28016af2-f63a-4ff9-a274-20f03dbffb1a)

### Пример с воспроизведением

https://codesandbox.io/s/stupefied-kapitsa-fl2tpr?file=/src/App.js

**Comment by inomdzhon** [comment]
@MrZillaGold в **5.10.1** занести фикс?

**Comment by MrZillaGold** [comment]
@inomdzhon вообще это edge-case с отображением в таблицах, пока никто с таким не приходил, если будете еще что-то закидывать помимо этого исправления, то можно. А так мы к себе можем просто перенести изменения, без выпуска новой версии
