### ISSUE TITLE
[Bug]: ModalPage mobile - застревает модальное окно в мобильной версии и на m.vk

### ISSUE THREAD

**Issue by bks-kristin** [VKCOM/VKUI#6069]
### Описание

Используется в приложение элементы ModalRoot, ModalPage. При нажатие на кнопку должно открываться модальное окно, но в мобильном клиенте оно не открывается полностью, очень похоже на описанный в другом issues баг, который так и не был решён, ссылка - https://github.com/VKCOM/VKUI/issues/4954 
Аналогично с  приведённым багом при нажатие на серую маску не закрывается модальное окно и оно вообще с трудом закрывается после нескольких попыток сдвинуть его с места. Если же удаётся открыть модалку полностью,
 и потом закрыть, то при повторном нажатие на кнопку ошибка не повторяется, однако если перезагрузить приложение и начать заново - всё повторяется.

### Версия

5.8.2

### В каких браузерах воспроизводится проблема?

Safari, Microsoft Edge

### Шаги воспроизведения

https://m.vk.com/app51628025 - приложение на котором можно протестировать
1. откройте приложение в мобильном клиенте или на m.vk
2. зайдите в баттл
3. нажмите на стрелочку в строке с именем пользователя
Всплывает шапка модального окна, при нажатие на маску серую окно не закрывается(!), при нажатие на модальное окно не получается никак его убрать, выдвинуть так же не получается(!), только если его сначала потянуть вниз, а потом наверх, оно раскрывается/закрывается. 

### Ожидаемое поведение

модальное окно открывается полностью, закрывается при тапе за его пределами, не мешает пользоваться приложением

### Скриншоты

<img width="467" alt="Screenshot 2023-11-01 130725" src="https://github.com/VKCOM/VKUI/assets/106806211/e282b617-2549-4709-9efb-b5d7942d8fee">

и вот в таком состояние оно и висит

### Пример с воспроизведением

https://codesandbox.io/s/magical-smoke-rfktrd?file=/src/App.js

Попробовала воспроизвести баг в песочнице, получилось что-то похожее, при наличие переполняющего контента не отображается полностью модальное окно, и скролл появляется только если получается вытянуть модальное окно.

**Comment by mendrew** [comment]
Привет @bks-kristin! Спасибо за issue!

Обязательно посмотрим.

Скажи, пожалуйста, передаются ли ещё какие-то пропы в ModalPage?

**Comment by bks-kristin** [comment]
@mendrew
 только id кидаем, пыталась settlingHeight={100} задать, но не помогло

**Comment by mendrew** [comment]
@bks-kristin 

А у вас случайно не динамически подгружается контент при открытии? 
В таком случае очень может быть, что мы открываем `ModalPage` на высоту известную при рендере, а это изначально только высота заголовка.
Если контент динамический, то стоит использовать prop `dynamicContentHeight`, а если и это не помогло, то можно попробовать использовать хук `useModalRootContext` и вызвать `updateModalHeight` после действий, которые могут привести к смене высоты содержимого, например, после загрузки данных. (из документации по [ModalRoot](https://vkcom.github.io/VKUI/#/ModalRoot))

Ещё можно попробовать задать фиксированную высоту модалке в процентах с помощью свойства `height`, чтобы она сразу открывалась на определённую высоту (не забыть поставить settlingHeight={100}).
Но свойство `height` появилось только в [v5.9.0](https://github.com/VKCOM/VKUI/releases/tag/v5.9.0) [ModalPage](https://vkcom.github.io/VKUI/5.9.0/#/ModalPage) 

Тем не менее это не объясняет почему клик по оверлею не закрывает модалку. 👀 
А вот что объясняет.
На класс `.vkuiPopoutRoot__modal` добавлено свойство `pointer-events: none;`, которое как раз и не даёт оверлею обрабатывать событие клика. Это свойство явно добавлено не библиботекой VKUI. Так что надо у вас по коду поискать откуда это берётся и для чего нужно. Вижу, что с ModalCard на вкладке с "Лидерами" та же проблема.

---

По поводу примера воспроизведения.
> Попробовала воспроизвести баг в песочнице, получилось что-то похожее, при наличие переполняющего контента не отображается полностью модальное окно, и скролл появляется только если получается вытянуть модальное окно.

То, что модальное окно не отображается полностью это ожидаемое поведение, мы действительно показываем его по умолчанию на 75%, чтобы пользователь мог развернуть полностью, если надо. В этот момент скролл не работает, пока не развернуть модальное окно на 100%. Для того чтобы отключить это поведение можно использовать проп settlingHeight={100}.


---

Обязательно пишите, подошел ли вариант со свойствами для динамической высоты. И очень интересно для чего нужен `pointer-events: none;`.

**Comment by bks-kristin** [comment]
@mendrew 

**Спасибо большое!)** И вправду подгружаем контент динамически, на другие модальные окна поставили dynamicContentHeight, а тут проглядели) Этот проп помог, так что проблема решена)

Про _pointer-events_ - в тюнинге авто у нас взаимодействие с 3д окружением идёт, пришлось ставить none, чтобы была возможность одновременно крутить машину и кастомить её, там на модальных окнах строится взаимодействие пользователя, соответственно при попытках повернуть машину закрывается модальное окно и нет возможности одновременно редактировать и использовать все прелести 3д модели. Поэтому такую радикальную штуку сделали))))
Спасибо большое за оперативность и такое подробное объяснение причины и варианты решения проблемы, очень помогли! Я второй день сидела голову ломала, что там такое происходит, что она не открывается👻

**Comment by mendrew** [comment]
> Спасибо большое!) И вправду подгружаем контент динамически, на другие модальные окна поставили dynamicContentHeight, а тут проглядели) Этот проп помог, так что проблема решена)

Спасибо за объяснение, был рад помочь! 🙂
