### ISSUE TITLE
[Bug]: Ошибка при попытке расширить CustomSelectOptionInterface

### ISSUE THREAD

**Issue by Hellek** [VKCOM/VKUI#6072]
### Описание

Тут пример кода
https://codesandbox.io/s/hopeful-cookies-vt4q29?file=/src/App.tsx

### Версия

Вроде бы где то с 5.9.2, но на 5.9.5 точно воспроизводится

### В каких браузерах воспроизводится проблема?

Yandex Browser

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.9.6" target="_blank">v5.9.6</a> 🎉
