### ISSUE TITLE
[Bug]: Alert: перестает работать action с опцией autoClose=true

### ISSUE THREAD

**Issue by b0gok** [VKCOM/VKUI#6089]
### Описание

Если очень быстро нажать на кнопку с action, у которого autoClose = true, то action не срабатывает и всё записает

https://github.com/VKCOM/VKUI/assets/4283162/7ea0d8c1-2572-432c-8c6c-3a48d9938ce2

### Версия

5.9.5

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

Быстро, до завершения анимации нажать на кнопку, для которой `autoClose=true`

_No response_

**Comment by mendrew** [comment]
Большое спасибо за bug report, особенно за видео!
Очень интересно, посмотрим!

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.0" target="_blank">v6.2.0</a> 🎉
