### ISSUE TITLE
[Bug][Header]: Не реализованы некоторые стейты из ДС

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6104]
### Описание

В ДС у header можно класть иконку 16 и 28 размера слева от основного текста, `Icon Left` на скриншоте

![Снимок экрана 2023-11-13 в 12 12 48](https://github.com/VKCOM/VKUI/assets/42776347/2932c0aa-843c-4d6e-9b5e-93782cf894f2)

Также у компонента есть multiline поле - в коде оно не реализовано

![Снимок экрана 2023-11-14 в 11 57 58](https://github.com/VKCOM/VKUI/assets/42776347/9de56c13-5b48-4083-a4a3-4b436e078e8c)

### Версия

5.0.0

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.6.0" target="_blank">v6.6.0</a> 🎉
