### ISSUE TITLE
С релиза 3.5.* появилась ошибка импорта

### ISSUE THREAD

**Issue by manaenckow** [VKCOM/VKUI#611]
Attempted import error: 'OSType' is not exported from './lib/platform'.

![image](https://user-images.githubusercontent.com/48844646/77620224-eea0cc80-6f4a-11ea-893d-eeb46a940883.png)

**Comment by ArthurStam** [comment]
Спасибо за репорт, действительно, такая проблема есть. 
Нашел тикет с описанием: https://github.com/webpack/webpack/issues/7378
В следующей версии будет фикс

**Comment by ArthurStam** [comment]
Поправили в 3.5.4
Можете проверить?

**Comment by xeoo** [comment]
А нахуя мне эта информация

чт, 26 мар. 2020 г., 11:15 Artur Stambultsian <notifications@github.com>:

**Comment by manaenckow** [comment]
Проверил, исправлено, спасибо!
