### ISSUE TITLE
[Bug]: Modal height with Select form

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#6113]
### Описание

Chrome: Если в модальном окне содержится обычный Select, то снизу появляется неизвестный отступ.
Safari: Модальному окну всегда плохо, отступ есть даже без контента.

Пример для Chrome:
```
<ModalPage id={id}>
      <ModalPageHeader after={<Button mode="link">Очистить</Button>}>
        Фильтры
      </ModalPageHeader>
      <FormLayout onSubmit={handleSubmit}>
        <FormItem top="Возраст">
          <Select
            placeholder="От"
            options={[
              {
                label: "1",
                value: "1"
              },
              {
                label: "1",
                value: "1"
              },
              {
                label: "1",
                value: "1"
              },
              {
                label: "1",
                value: "1"
              },
              {
                label: "1",
                value: "1"
              }
            ]}
          />
          <Select
            placeholder="До"
            options={[
              {
                label: "1",
                value: "1"
              }
            ]}
          />
        </FormItem>
      </FormLayout>
    </ModalPage>
```

<img width="569" alt="image" src="https://github.com/VKCOM/VKUI/assets/26293210/c25ef018-b9d6-4472-bf3a-3b6d2347c687">
<img width="564" alt="image" src="https://github.com/VKCOM/VKUI/assets/26293210/b801b103-afa2-4c85-bf29-32aea2dbe040">

Пример для Safari:
```
<ModalPage id={id}>
      <ModalPageHeader after={<Button mode="link">Очистить</Button>}>
        Фильтры
      </ModalPageHeader>
      1
    </ModalPage>
```

![image](https://github.com/VKCOM/VKUI/assets/26293210/f24ebfe2-c284-4e63-95cc-f0a96beee272)

### Версия

5.9.6

### В каких браузерах воспроизводится проблема?

Chrome, Safari

**Comment by SkyGopnik** [comment]
P.S. проблемы не было на версии библиотеки 4.43.0

**Comment by inomdzhon** [comment]
Привет

По селекту уже была такая бага https://github.com/VKCOM/VKUI/issues/5584, которую поправили 🤔  Правда там об одном селекте шла речь. Глянем, спасибо 🙏 

А это мобильный Chrome или через DevTools эмулуриется?

**Comment by EldarMuhamethanov** [comment]
Поправлено в #7147
