### ISSUE TITLE
[Feature]: show zero in counter for TabsItem

### ISSUE THREAD

**Issue by GreatFix** [VKCOM/VKUI#6119]
### Описание

Хотим выводить в счетчике TabsItem число 0. 

Из-за проверки на truthy в https://github.com/VKCOM/VKUI/blob/107c29dd8664621a6a025b656124e80650fbea9b/packages/vkui/src/components/TabsItem/TabsItem.tsx#L78 , 0 не выводится

### Скриншоты

<img width="894" alt="image" src="https://github.com/VKCOM/VKUI/assets/61346501/d21c1342-71d9-4b4a-b197-7960dfc7e39b">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.0" target="_blank">v5.10.0</a> 🎉
