### ISSUE TITLE
[Bug]: Не работает переход по ссылке (компонент Link)

### ISSUE THREAD

**Issue by lexstile** [VKCOM/VKUI#6120]
### Описание

Получил баг от тестеров вк, что не работает переход по ссылке через компонент Link.
Самому воспроизвести не удалось, использовал более новые версии Android/iOS.

Пишут, что воспроизводится на:
Xiomi Mi 8 Lite Mi 8 Lite
Android 10.0 Q
Версия вк приложения: 8.56

Посмотреть можно здесь: https://vk.com/bug796946

### Версия

5.9.6

### В каких браузерах воспроизводится проблема?

Другое (укажите в описании)

### Шаги воспроизведения

1. Перейти по ссылке: https://vk.com/app51769365
2. Пройти онбординг до последнего шага
3. Нажать на любую ссылку: "Пользовательским соглашением" или "Политикой конфиденциальности"

### Ожидаемое поведение

Осуществляется переход по ссылке.

### Пример с воспроизведением

`<Link href="https://dev.vk.com/ru/user-agreement" target="_blank">
   Пользовательским соглашением
</Link>`

**Comment by SevereCloud** [comment]
Привет воспроизвел на Pixel Tablet (Android 14)

Проблема не в VKUI, а в обработке ссылок `vk.com` на клиенте

**Comment by lexstile** [comment]
Не совсем понял, чья это зона ответственности?

**Comment by SevereCloud** [comment]
Mini Apps

**Comment by lexstile** [comment]
Спрошу немного другими словами.
Это нужно исправлять в моем приложении или это общая проблема всех vk mini apps?

**Comment by SevereCloud** [comment]
Общая проблема всех vk mini apps
