### ISSUE TITLE
[Feature]: Добавить кнопку полной очистки в ChipsSelect

### ISSUE THREAD

**Issue by mendrew** [VKCOM/VKUI#6128]
### Описание

В компоненте [ChipsSelect](https://vkcom.github.io/VKUI/#/ChipsSelect) можно легко удалять отдельные выбранные элементы, но нельзя полностью сбросить все выбранные элементы, как это можно сделать в компоненте [Select](https://vkcom.github.io/VKUI/#/Select).

Требуется добавить кнопку очистки [ChipsSelect](https://vkcom.github.io/VKUI/#/ChipsSelect). Визуально должна полностью повторять такую же кнопку из компонента [Select](https://vkcom.github.io/VKUI/#/Select).

<img width="369" alt="Screenshot 2023-11-21 at 11 56 08" src="https://github.com/VKCOM/VKUI/assets/5443359/471a3ff7-706b-436a-b8ea-c8464586b328">

### Скриншоты

![file vndMSu(1)](https://github.com/VKCOM/VKUI/assets/5443359/4a17aaeb-ef10-4598-be20-1e0e3c221af9)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.3.0" target="_blank">v6.3.0</a> 🎉
