### ISSUE TITLE
Кнопка в PromoBanner съезжает при длинном тексте

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#613]
Ставим в title длинный текст
<img width="1440" alt="Screenshot 2020-03-26 at 15 33 31" src="https://user-images.githubusercontent.com/45998835/77647260-26be0480-6f77-11ea-95fe-4d1ed9bc247f.png">

**Comment by ArthurStam** [comment]
@danakt ваш выход :)
