### ISSUE TITLE
[Feature]: Сделать булевые пропы по умолчанию falsy

### ISSUE THREAD

**Issue by BlackySoul** [VKCOM/VKUI#6149]
### Discussed in https://github.com/VKCOM/VKUI/discussions/5332

<div type='discussions-op-text'>

<sup>Originally posted by **andres-kovalev** June 22, 2023</sup>
**Мотивация:** для булевых пропов в JSX предусмотрен особый синтаксис, который выглядит настолько удобным, что нет причин им не пользоваться. Просто сравните: `<Input readonly={true} >` и `<Input readonly />`

**Что делать:** Не добавлять булевые пропы на поведение по умолчанию, а наоборот - для особых вариантов поведения. Если состояние, для которого существует булевый проп должно быть состоянием по умолчанию - скорее всего смысл пропа надо инвертировать. Например, я хочу добавить возможно контролировать видимость кнопки. Если я добавлю проп `visible`, это будет равносильно заявлению "я хочу добавить возможность сделать кнопку видимой". Но ведь кнопка итак по умолчанию видна. Правильно сформулированное требование будет выглядеть так: "я хочу добавить возможность скрывать кнопку". Из такого требования уже понятно, что нужно добавить проп `hidden`. Таким образом, мы инвертировали смысл пропа, чтобы компонентом было удобнее пользоваться:
```
<Button>Видимая кнопка</Button>
<Button hidden>Скрытая кнопка</Button> </>
```
вместо
```
<Button>Видимая кнопка</Button>
<Button visible>Тоже видимая кнопка</Button>
<Button visible={false}>Скрытая кнопка</Button>
```

</div>

```[tasklist]
### Tasks
- [ ] https://github.com/VKCOM/VKUI/issues/6264
```

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
