### ISSUE TITLE
[BREAKING CHANGE] Удалить `<VisuallyHiddenInput />`

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#6155]
https://github.com/VKCOM/VKUI/blob/b75794feb9250abb2baf35efd080233b10620594/packages/vkui/src/components/VisuallyHiddenInput/VisuallyHiddenInput.tsx#L13-L18

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
