### ISSUE TITLE
[BREAKING CHANGE]: удалить зависимость `@vkontakte/vk-bridge`

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#6169]
### Описание

Удаляем зависимость и его оставшиеся упоминания в коде.

- related to #5049
- related to #5868

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
