### ISSUE TITLE
[Feature]: Добавить в Popper возможность передавать position = {x, y}

### ISSUE THREAD

**Issue by b0gok** [VKCOM/VKUI#6174]
### Описание

Есть задача добавить меню по правой кнопки мыши. Чтобы меню всегда помещалось на экране хотелось бы использовать тот код, который используется в Popper для позиционирования

### Скриншоты

**Как сейчас выглядит**
<img width="1273" alt="image" src="https://github.com/VKCOM/VKUI/assets/4283162/b5e0b4b2-51bf-441c-a459-bd6aca44fe3c">

**Что хотелось бы пофиксить**
<img width="1306" alt="image" src="https://github.com/VKCOM/VKUI/assets/4283162/6849b3e6-2c02-4af1-98d9-b78512f76c0b">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
