### ISSUE TITLE
[Feature]: Добавить возможность прокидывать test-id для крестика в Alert

### ISSUE THREAD

**Issue by b0gok** [VKCOM/VKUI#6175]
### Описание

Для автотестов нужна возможность идентифицировать крестик в компоненте Alert. В данные момент нет возможности передать тестовый id именно для этого элемента формы.

В качестве workaround был использовал prop `dismissLabel`, в который передано слово `закрыть`. Соответственно в тесте используется поиск по button[aria-label="закрыть"].

**Comment by b0gok** [comment]
FYI пример концепции перезаписи пропсов от Uber https://baseweb.design/guides/understanding-overrides/#override-the-entire-subcomponent. Есть ещё такой вариант https://t.me/artalog/1131

**Comment by mendrew** [comment]
> FYI пример концепции перезаписи пропсов от Uber https://baseweb.design/guides/understanding-overrides/#override-the-entire-subcomponent. Есть ещё такой вариант https://t.me/artalog/1131

Спасибо за ссылки. Да, особенно понравился подход со `slot`. в MaterialUI как раз такой, рассматривал его в своё время. Думаю, что нам стоит в этом направлении двигаться.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.1" target="_blank">v5.10.1</a> 🎉
