### ISSUE TITLE
Табы разной высоты на m.vk.com

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#620]
При переходе по табам [`Epic`](https://vkcom.github.io/vkui-styleguide/#epic) разной высоты на m.vk.com интерфейс уезжает вверх.

Оригинальный тикет: https://vk.com/bug212959

Оригинальное видео: https://vk.com/doc304358149_541481427?hash=7072ed1b93f1380804&dl=c9f9be1ab60ec622cb

**Comment by mahnunchik** [comment]
[IMG_0342.mp4.zip](https://github.com/VKCOM/VKUI/files/4893432/IMG_0342.mp4.zip)

Перезалил скринкаст проблемы так как почти ни у кого нет доступа к трекеру продукта и прямая ссылка на видео протухла.

**Comment by gbowsky** [comment]
Посмотрел в [codesandbox](https://f8mgh.csb.app), проблему не обнаружил.
Вероятно была версия v3.x.x
