### ISSUE TITLE
[Bug]: У ActionSheetItem некорректная подсветка

### ISSUE THREAD

**Issue by BlackySoul** [VKCOM/VKUI#6204]
### Описание

<img width="818" alt="image" src="https://github.com/VKCOM/VKUI/assets/7431217/9ffe21e9-314a-4c45-981f-afaef4eb8614">
<img width="840" alt="image" src="https://github.com/VKCOM/VKUI/assets/7431217/8f4f3af4-413c-4271-996d-82dca0a567ce">

Теперь на десктопе подсветка с закруглениями, а должна быть без них 

### Версия

v5

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.1" target="_blank">v5.10.1</a> 🎉
