### ISSUE TITLE
[Bug]: CustomSelect на iOS, при открытии появляется тултип «Автозаполнение»

### ISSUE THREAD

**Issue by danillas** [VKCOM/VKUI#6205]
### Описание

Не помогли:
autoCorrect="off"
autoComplete="off"

### Версия

5.1.10

### В каких браузерах воспроизводится проблема?

Safari

### Шаги воспроизведения

1. Открыть выпадающее меню
2. Выбрать один из пунктов
3. Повторить шаги 1-2, воспроизводится со второго раза

### Ожидаемое поведение

Тултип "Автозаполнение" не показывается

### Скриншоты

![image](https://github.com/VKCOM/VKUI/assets/26124760/a413e06b-b3ca-41d3-94be-3d8ba1482da0)

### Пример с воспроизведением

Воспроизводится в доке [https://vkcom.github.io/VKUI/?msgid=1152882#/CustomSelect](https://vk.com/away.php?to=https%3A%2F%2Fvkcom.github.io%2FVKUI%2F%3Fmsgid%3D1152882%23%2FCustomSelect&cc_key=)

**Comment by inomdzhon** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.1" target="_blank">v5.10.1</a> 🎉
