### ISSUE TITLE
[Bug]: Ошибка с гидрацией компонента SimpleCell при использовании его на SSR с использованием параметра vk_platform

### ISSUE THREAD

**Issue by Pavel1711** [VKCOM/VKUI#6211]
### Описание

Я использую Next.js. Если указать в урле ?vk_platform=desktop_web, то вылетает ошибка с гидрацией

<img width="964" alt="Снимок экрана 2023-12-05 в 12 59 24" src="https://github.com/VKCOM/VKUI/assets/45904265/bc530ec9-d302-4932-81e7-93729abe6e03">
### 

### Версия

5.9.1

### В каких браузерах воспроизводится проблема?

Firefox, Chrome, Safari

### Шаги воспроизведения

```
import { SimpleCell, Text } from '@vkontakte/vkui';

const Test = () => {
  return (
    <SimpleCell>
      <Text weight="3">Помогать регулярно</Text>
    </SimpleCell>
  )
}

export default Test;
```
Добавить такой код на страницу на Next.js и открыть с GET-параметром vk_platform=desktop_web

**Comment by inomdzhon** [comment]
Нашёл проблему :(

https://github.com/VKCOM/VKUI/blob/ea30d1ed049a07e4c4e4fe657555865c7ecd12bd/packages/vkui/src/lib/platform.ts#L36C68-L36C76

Из-за `canUseDOM`  получается, что на сервере `platform` неопределён, а на клиенте он становится `platform="vkcom"` из-за урла.

Какой Workaround, попробуешь навесить на `SimpleCell` атрибут `suppressHydrationWarning` https://nextjs.org/docs/messages/react-hydration-error#solution-3-using-suppresshydrationwarning ?

В VKUI v6 уже можно самостоятельно будет это дело поправить.
