### ISSUE TITLE
[Doc]: DateRangeInput в сторибуке не реагирует на изменения 

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#6214]
### Описание

DateRangeInput в [сторибуке](https://vkcom.github.io/VKUI/playground/?path=/story/forms-daterangeinput--playground) контролируется из кода и изменить его можно только с помощью контролов `startDate` и `endDate`

Кажется что DateRangeInput сломан, но это не так

**Comment by mendrew** [comment]
@SevereCloud Тоже заметил и сделал недавно фикс, только пока что его не оформил. https://github.com/VKCOM/VKUI/pull/6215

**Comment by inomdzhon** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.1" target="_blank">v5.10.1</a> 🎉
