### ISSUE TITLE
[Enhancement][HorizontalCellShowMore]: Сделать стабильным

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#6227]
### Описание

Был нестабильным, т.к. было неясно как ограничить его использование только в рамках `HorizontallScroll`.

Сделаем стабильным и добавим в документацию информацию, что должен быть использован в рамках `HorizontallScroll`.

--- 

- caused by #5367

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
