### ISSUE TITLE
[iOS] Отключается Pull To Refresh

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#624]
### Шаги воспроизведения:

1. Открыть сервис.
2. Попробовать обновить.
3. При следующем обновлении информации зацепить верхнюю шторку. (два раза)
4. Попробовать обновить.

#### Фактический результат:

После выполнения шага 3, обновить с помощью свайпа не получается.

#### Ожидаемый результат:

После выполнения шага 3 шторка сразу же отцепляется и я могу делать обновление свайпом.

Видео: https://vk.com/doc337094267_542986212?hash=5af2bcdc90bcefe88c&dl=a23a94978a5870c5a3
Оригинальный репорт: https://vk.com/bug214509

**Comment by mahnunchik** [comment]
[IMG_1448.mp4.zip](https://github.com/VKCOM/VKUI/files/4893424/IMG_1448.mp4.zip)

Перезалил скринкаст проблемы так как почти ни у кого нет доступа к трекеру продукта и прямая ссылка на видео протухла.

**Comment by gbowsky** [comment]
Смотрел на актуальных версиях, не нашёл проблему. Что-то похожее возникает, когда тянешь PanelHeader, но это не баг.
https://7z46f.csb.app
