### ISSUE TITLE
[Bug]: v6.0.0-beta.1 сломан SSR для appearance

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#6240]
### Описание

```
Server Error
TypeError: Cannot read properties of undefined (reading 'matchMedia')

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
matchMedia
node_modules/@vkontakte/vkui/dist/cssm/hooks/useAutoDetectAppearance.js (15:22)
```

### Версия

6.0.0-beta.1

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

Использовать ConfigProvider не передавая свойств

### Пример с воспроизведением

https://github.com/VKCOM/VKUI/blob/e421dcb3890191bc44350e6472375c545faa9c1e/packages/vkui/src/hooks/useAutoDetectAppearance.tsx#L19

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
