### ISSUE TITLE
[Bug]: проблема пересчёта размеров ModalPage при изменении ориентации мобильного устройства

### ISSUE THREAD

**Issue by vdudenkov** [VKCOM/VKUI#6242]
### Описание

при открытии модалки в горизонтальном положении и последующем повороте в вертикальное, модалка растягивается

### Версия

5.10.0

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

1. открыть модальное окно (с небольшим содержимым) в горизонтальном положении мобильного устройства (МУ)
2. повернуть МУ, в вертикальное положение

после перерисовки модальное окно растягивается на большую часть экрана, не взирая на небольшое содержимое модального окна

### Ожидаемое поведение

при изменении ориентации мобильного устройства размер модального окна должен пересчитываться

### Скриншоты

![Modal Page landscape issue](https://github.com/VKCOM/VKUI/assets/5443359/47d3d2b2-e209-4b48-882e-1496ff7a34a5)

### Видео с воспроизведением

https://github.com/VKCOM/VKUI/assets/5443359/0eec53a8-1d28-491c-a750-95814664b004

### Пример с воспроизведением

https://codesandbox.io/p/sandbox/vkui-v5-10-0-modalpage-landscape-behavior-s7sr5h

**Comment by mendrew** [comment]
К сожалению, так и не получилось адекватно поправить эту проблему. Попробуем выделить больше времени в будущем. Успокаивает то, что контент остаётся доступным.

Немного деталей:
- дело в AppRoot. После переворота логика компонента считывает размеры элементов и они в момент переворота оказываются больше, чем если бы модалка просто открывалась уже в вертикальном положении. 
- к сожалению эта проблема присутствует и в новом компоненте модалок [ModalSheet](https://github.com/VKCOM/VKUI/pull/5092), потому что там также используется AppRoot.

**Comment by PoltP** [comment]
У нас в Мобильной Почте Octavius я столкнулся со схожей проблемой.

1) Есть модалка, которая показывается либо на динамическую высоту, либо на весь экран в зависимости от ориентации экрана мобильника:
```
...(orientation === "landscape"
          ? {
              settlingHeight: 100,
            }
          : {
              dynamicContentHeight: true,
            })
```
2) Если из "портрета" повернуть мобильник в "альбом" ('rotate' в браузерном эмуляторе мобилы), то в портрете она показывается на всю высоту, несмотря на то, что я прокидываю `dynamicContentHeight: true` и зову хук обновления высоты.

Код и сама демка сразу сделал в сендбокс (окружение конечно отличается от нашего, но у нас примерно так):
https://qxg973.csb.app/
https://codesandbox.io/p/sandbox/objective-maxwell-qxg973?file=%2Fsrc%2Findex.js

Проверял на живой мобиле и наш вариант и демку в сендбоксе - поведение такое, не могу понять, как будто игнорит свойство динамической высоты потом после первого задания.

Вот в коде песочницы видно, что я пробовал играться тут, обновлял высоту на смену ориентации или свойств:
```
  const { updateModalHeight } = useModalRootContext();
  useEffect(() => {
    setTimeout(updateModalHeight, 0);
  }, [props.settlingHeight, props.dynamicContentHeight]);
```
но не помогает - проблема остаётся...


Видео поведения демо:
https://github.com/VKCOM/VKUI/assets/41975596/8d9db731-6891-4511-a6ff-4658878ac2d5

Видел поведения из реального приложения:
https://github.com/VKCOM/VKUI/assets/41975596/ca640200-1d5a-4154-b8a6-1ceb12537ab6

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.1" target="_blank">v5.10.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.1" target="_blank">v6.0.1</a> 🎉
