### ISSUE TITLE
[Bug][DateInput]: Не сбрасывается фокус с календаря после клика на кнопку "Готово"

### ISSUE THREAD

**Issue by mendrew** [VKCOM/VKUI#6244]
### Описание

Если закрыть `DateInput` календарь кликом по кнопке "Готово", а потом переключить свойство `disabled` c `false` на `true`, потом снова на `false`, то календарь автоматически снова откроется.

### Версия

5.10.0

### Шаги воспроизведения

`DateInput` должен иметь `closeOnChange={false} enableTime={true}` свойства.

1. Открыть календарь кликом по `DateInput`
2. Выбрать дату и кликнуть на кнопку "Готово" возле выбора времени.
3. Имитировать клик по кнопке "Submit", в результате на пару секунд надо переключить свойство `disabled` на `true`, потом на `false`.
4. После того как `disabled` вернётся в `false` автоматически откроется календарь `DateInput`.

### Ожидаемое поведение

После переключения `disabled` с `true` на `false` календарь не должен открываться.

### Скриншоты

https://github.com/VKCOM/VKUI/assets/5443359/a88f2f48-3b0a-4da0-9fd7-37a343f8f861

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.1" target="_blank">v5.10.1</a> 🎉
