### ISSUE TITLE
Cell: правки по вёрстке

### ISSUE THREAD

**Issue by Lihachyov** [VKCOM/VKUI#625]
1. Сделать на Android высоту ячейки как на iOS — 48 точек. Сейчас 52

2. Для iOS: если в Before стоит Icon, стоит добавить отступ слева в 4 точки для симметричности и достаточного количества воздуха

3. Посмотреть, возможно ли реализовать для iOS особенную логику ячеек. 
Из-за того что у нас это один большой компонент, он в себе совместил два стиля: ячейки с иконками/без иконок (ячейки настроек), и ячейки для контетнтных списков с Avatar. У первых мы используем шрифт 17 точек, а у вторых 16. 
Чтобы этого достичь, предлагаю попробовать сделать следующее: 
- По умолчанию в iOS ячейках применять шрифт 17 pt
- Если в Cell содержится Avatar, применять шрифт 16 pt

![Screenshot 2020-04-08 at 11 16 00](https://user-images.githubusercontent.com/3250391/78760800-55ca7200-798a-11ea-8a99-9b49ce9f6d58.png)

Макет можно найти в Figma: VK Design Team / VKUI Internal / Github Issues

**Comment by ArthurStam** [comment]
[Поправил](https://vkcom.github.io/vkui-styleguide/#!/SimpleCell)
