### ISSUE TITLE
Cell: добавить возможность вставлять иконку или бейдж справа от заголовка

### ISSUE THREAD

**Issue by Lihachyov** [VKCOM/VKUI#626]
Бейдж справа от заголовка может использоваться, чтобы выделить новый раздел в меню. Похожим образом мы у ячеек можем вставлять бейдж verified для верифицированных пользователей в списках. Можем ли предусмотреть в компоненте Cell?

![dBF_xyrxhOE](https://user-images.githubusercontent.com/3250391/78761901-e6558200-798b-11ea-908e-3422d4acdcf0.jpg)

Макет можно найти в Figma: VK Design Team / VKUI Internal / Github Issues

**Comment by ArthurStam** [comment]
[Поправил](https://vkcom.github.io/vkui-styleguide/#!/SimpleCell)
