### ISSUE TITLE
[Feature]: Текст для компонента ScreenSpinner

### ISSUE THREAD

**Issue by Zaycevq** [VKCOM/VKUI#6267]
### Описание

Текущая реализации предлагает добавлять лишь иконку в компоненте, у нативного кода iOS / Android существует вариант где ScreenSpinner отображает описательный текст под иконкой. Нужно доабвить такую же возможность в React компоненте.

Дизайн:
https://vk.cc/ctbT4Y

![dark-screen-spinner](https://github.com/VKCOM/VKUI/assets/91548592/c4e65fe2-a9b6-477a-8ca0-cc398b71b316)
![light-screen-spinner](https://github.com/VKCOM/VKUI/assets/91548592/09c5fa59-000c-4e18-9f07-a3ab3d5c715d)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.7.0" target="_blank">v6.7.0</a> 🎉
