### ISSUE TITLE
[Feature]: Добавить текст для ScreenSpinner

### ISSUE THREAD

**Issue by trigolos** [VKCOM/VKUI#6271]
### Описание

Добавить в ScreenSpinner возможность выводить текст по аналогии с нативной частью.

Пример:
![image](https://github.com/VKCOM/VKUI/assets/7376989/ce740cb4-5a8d-4672-a94b-ccdc0ebc3aa1)

**Comment by SevereCloud** [comment]
Duplicate of #6267
