### ISSUE TITLE
Документация: поправить название темы client_dark → space_gray

### ISSUE THREAD

**Issue by Lihachyov** [VKCOM/VKUI#628]
В секции Themes в примере указана тема "client_dark", которую нужно заменить на "space_gray"
https://vkcom.github.io/vkui-styleguide/#section-themes

![DbWWIB2cIAw](https://user-images.githubusercontent.com/3250391/78763537-efdfe980-798d-11ea-96bc-2221cbac45c3.jpg)

**Comment by fedorov-xyz** [comment]
Поправили, со следующей версией обновится и в документации.
