### ISSUE TITLE
[Bug]: Нативные подсказки в формах перекрывают элементы

### ISSUE THREAD

**Issue by BlackySoul** [VKCOM/VKUI#6283]
### Описание

Подробнее в этом [комменте](https://github.com/VKCOM/VKUI/issues/2562#issuecomment-1856502369)

Похоже, что для Chrome & Firefox проблему можно решить, если проставить `bottom: 0`, 

https://github.com/VKCOM/VKUI/assets/7431217/df4d23cd-e451-463f-9627-71be07aa1fdf

Но Safari 🥇 наоборот сейчас показывает все верно:

https://github.com/VKCOM/VKUI/assets/7431217/a638b12d-aaae-49c2-a305-89261d5e795d

### Версия

v5

**Comment by SevereCloud** [comment]
- closed by #6365
