### ISSUE TITLE
[Bug]: Компоненты на основе Clickable не интерактивны

### ISSUE THREAD

**Issue by BlackySoul** [VKCOM/VKUI#6284]
### Описание

- [x] `Button` в форме больше не реагирует на взаимодействие
У нас сейчас контролы без обработчиков неактивные, и если мы раньше могли просто расположить `<Button type="submit">Submit</Button>` внутри `<form>`, то оно бы просто вызывало сабмит формы, сейчас тоже вызывает, но `active`/`hover` состояний на кнопке нет.  (resolved by #6381)

- [ ] Отсутствует `hover`-состояние на `Avatar` c `overlay=onHover`

- [ ] `RichCell` показывает неверный курсор

https://github.com/VKCOM/VKUI/assets/7431217/7efbd15e-9ca3-4e86-a033-28f04f371c84

### Версия

v6

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
