### ISSUE TITLE
[Bug]: Анимации появления и скрытия снекбара не учитывают оффсеты

### ISSUE THREAD

**Issue by Anastasia951** [VKCOM/VKUI#6285]
### Описание

Пример из доки https://vkcom.github.io/VKUI/#/Snackbar с большим оффсетом

https://github.com/VKCOM/VKUI/assets/77168808/7c415e0a-28a1-43e3-984e-5056f56584f6

### Версия

5.10.0

### Шаги воспроизведения

Установить большое значение offsetY компоненту снекбара

### Ожидаемое поведение

Снекбар уходит с анимацией за границы, учитывая offsetY

**Comment by EldarMuhamethanov** [comment]
Исправлено в [v6.1.0](https://github.com/VKCOM/VKUI/releases/tag/v6.1.0) за счет модификации анимации - добавили изменение прозрачности
