### ISSUE TITLE
[Feature]: Пометить компоненты как клиентские

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#6288]
### Описание

https://react.dev/reference/react/use-client

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
