### ISSUE TITLE
[Feature]: Snackbar скомпенсировать отступ снизу от action

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#6306]
### Описание

Отступы от кнопки должны быть одинаковыми

### Скриншоты

<img width="428" alt="image" src="https://github.com/VKCOM/VKUI/assets/14944123/5f221010-0db7-4e14-9b8b-7fb8ba2bf565">

**Comment by inomdzhon** [comment]
@akcent1132
