### ISSUE TITLE
[Feature][Textarea]: after проп

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6307]
### Описание

Нужен after проп для Textarea, для расположения кнопок в правом верхнем углу, такой же как и у Input.

### Скриншоты

![Снимок экрана 2023-12-18 в 14 06 12](https://github.com/VKCOM/VKUI/assets/42776347/6a797667-dbc4-4a1b-855e-f86d14dc53d1)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.3.0" target="_blank">v6.3.0</a> 🎉
