### ISSUE TITLE
Изменить стиль Disabled FormField

### ISSUE THREAD

**Issue by wayshev** [VKCOM/VKUI#631]
Вместо opacity 0.6 у текста text_primary должно быть:

токен текста: text_secondary
opacity 0.4 у всего инпута (и background и placeholder)

Скриншот: было — стало
![Screenshot 2020-04-08 at 20 14 22](https://user-images.githubusercontent.com/61538408/78813336-8b487d00-79d5-11ea-8c60-0d60e7a1aed1.png)

**Comment by fedorov-xyz** [comment]
Исправлено в версии 3.6.0.
