### ISSUE TITLE
Проблема с динамическим формированием ModalRoot

### ISSUE THREAD

**Issue by a1phaZ** [VKCOM/VKUI#632]
Формирую ModalRoot исходя массива(ответ с сервера) подставляю во View, запускаю все работает, но после изменения ответа от сервера(переход на другой месяц) выдает ошибку
`[ModalRoot.componentDidUpdate] nextModal 5e71fc7fc6207925c825d498 not found`

"5e71fc7fc6207925c825d498" это id для модалки, модалка формируется только после ответа от сервера. Но формируется получается один раз, при первоначальном запросе, более не изменяется.

При выводе в консоль стэйта модалки данный id присутствует в props.activeModal.

![modalRoot](https://user-images.githubusercontent.com/6966909/78874352-b37fbc80-7a65-11ea-8c3b-9a9591342c79.png)

ps. Обязательно ли использовать modalHistory как в [этом примере](https://vkcom.github.io/vkui-styleguide/#modalroot)  ?

**Comment by ArthurStam** [comment]
Привет, модалки, как и панели, нельзя формировать динамически. Это декларация вашего приложения, которая должна быть задана на старте и не меняться в рантайме.

**Comment by a1phaZ** [comment]
> Привет, модалки, как и панели, нельзя формировать динамически. Это декларация вашего приложения, которая должна быть задана на старте и не меняться в рантайме.

Тогда другой вопрос, что, хотя бы отдаленно напоминающее модалки есть в VKUI?

**Comment by ArthurStam** [comment]
Вопрос не понятен) вы можете динамически генерировать содержимое модальной страницы. Рассматривайте их, как роуты в приложении. Роут статичен, но его содержимое может быть каким угодно.

**Comment by a1phaZ** [comment]
> Вопрос не понятен) вы можете динамически генерировать содержимое модальной страницы. Рассматривайте их, как роуты в приложении. Роут статичен, но его содержимое может быть каким угодно.

Интересная мысль, не думал в эту сторону. Буду пробовать. Спасибо)

**Comment by ArthurStam** [comment]
Закрываю тикет?

**Comment by a1phaZ** [comment]
> Закрываю тикет?

Да, конечно. Спасибо за идею.
