### ISSUE TITLE
[Bug][View][iOS]: Теряется скролл при отмене swipeback

### ISSUE THREAD

**Issue by ivansekisov-vk** [VKCOM/VKUI#6320]
### Описание

https://github.com/VKCOM/VKUI/assets/149587335/64ee97ae-4355-4d4a-8a16-5b09a1f9b9f3

### Версия

5.10.0

### Шаги воспроизведения

1. перейти на панель, где много контента
2. немного проскроллить
3. начать свайпбек
4. отменить свайпбек пальцем (обязательно в ручную довести панель обратно)

### Ожидаемое поведение

Позиция скролла не меняется

**Comment by mendrew** [comment]
@ivansekisov-vk спасибо за понятные шаги для воспроизведения!

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.1" target="_blank">v5.10.1</a> 🎉
