### ISSUE TITLE
[BUG]: заедает состояние с вложенными Clickable

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#6322]
Вот такое ещё словила - как будто `active`/`hover`-состояние остается

https://github.com/VKCOM/VKUI/assets/7431217/4c190193-ff2a-4044-954f-5a9d8b0e1c8d

_Originally posted by @BlackySoul in https://github.com/VKCOM/VKUI/issues/6321#issuecomment-1864655028_
            

Вот здесь воспроизводится стабильнее  - https://codesandbox.io/p/sandbox/vkui-typescript-forked-hqgnqr

https://github.com/VKCOM/VKUI/assets/7431217/abb682ae-bf98-4c07-a290-f0eff8c2eb91

            
Шаги воспроизведения
1. Найти вложенные Clickable 
2. Тыкнуть на внешний Clickable
3. Повести мышку через внутренний

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.1.2" target="_blank">v6.1.2</a> 🎉
