### ISSUE TITLE
[Feature]: Возможность красить Panel градиентом через css переменную

### ISSUE THREAD

**Issue by danillas** [VKCOM/VKUI#6327]
### Описание

Для этого предлагается задавать цвет через свойство background:

```
.vkuiPanel .vkuiPanel__in, .vkuiPanel:before {
    background-color: #fff;
    background: var(--vkui--color_background_content);
}
```

Использование
```
.MyCustomPanel {
  --vkui--color_background_content: linear-gradient(135deg, #66adff 0%, #0077ff 100%)
}
```

### Скриншоты

![image](https://github.com/VKCOM/VKUI/assets/26124760/4d3469cd-d774-425c-a953-87d191bc2068)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.2" target="_blank">v6.0.2</a> 🎉
