### ISSUE TITLE
Проблема с типами в Snackbar

### ISSUE THREAD

**Issue by Nix1304** [VKCOM/VKUI#633]
При использовании следующего кода
```
<Snackbar
    onClose={() => this.setState({ snackbar: null })}
    before={<Avatar size={24}><Icon16Done/></Avatar>}
>
    Ты успешно купил {name}!<br/>
    Тебы выпало {res.dropped_item.name}!
</Snackbar>
```
Получаем такую ошибку `TS2322: Type 'void' is not assignable to type '{}'.`

**Comment by ArthurStam** [comment]
Привет, спасибо, поправим

**Comment by Nix1304** [comment]
before имеет подобный баг
`TS2322: Type 'Element' is not assignable to type 'ComponentClass<{}, any> | FunctionComponent<{}> | undefined'.`

**Comment by ArthurStam** [comment]
Вы правы, тоже пофиксим, спасибо

**Comment by Nix1304** [comment]
#634

**Comment by fedorov-xyz** [comment]
Спасибо за issue и PR! Фикс доступен в версии 3.6.0.
