### ISSUE TITLE
[Bug][PanelHeader,Tabbar][iOS]: Изменились hover-эффекты

### ISSUE THREAD

**Issue by eugpoloz** [VKCOM/VKUI#6330]
### Описание

**PanelHeader:**

> Привет, с недавних пор на ios изменился hover эффект по иконкам в шапке.
>
> Раньше был просто opacity эффект. Теперь opacity + background. При чем background без закруглений.
> 
> Предположу, что это баг. Так как в нативных клиентах не так.

**Tabbar:**

> Еще на ios у таббара появился hover. Раньше не было, не знаю по плану появилось или нет

### Версия

5.10.0

### Скриншоты

![panelheader icons on ios](https://github.com/VKCOM/VKUI/assets/22026957/8cc73c09-c6be-4047-b7ea-67016737fd1b)
![tabbar hover on ios](https://github.com/VKCOM/VKUI/assets/22026957/d5cc8fe6-af68-4bb8-97ea-32b97d2edcbd)

**Comment by inomdzhon** [comment]
- closed this as [completed](https://github.com/VKCOM/VKUI/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in #6602

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.1" target="_blank">v5.10.1</a> 🎉
