### ISSUE TITLE
[Bug][Cell]: в `draggable` режиме не работает автоскролл если у родителя нет `height: 100%`

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#6338]
### Описание

Если нет повсеместного `height: 100%`, начинаю с `html` и `body`, то в `<Cell draggable />` не работает автоскролл при перетаскивании к низу области видимости.

<details><summary>Видео с воспроизведением</summary>
<p>

https://github.com/VKCOM/VKUI/assets/5850354/79e1ffc3-3b11-49e0-893e-edf2cb89a9bf

</p>
</details> 

## Нюанс

Если расставить  `height: 100%`, то автоскролл починиться, но это решение подходит для всех приложений. На видео ниже пример, где `height: 100%` ломает страницу.

<details><summary>Видео c воспроизведением, где расставленн  `height: 100%`</summary>
<p>

https://github.com/VKCOM/VKUI/assets/5850354/e338a40e-c88e-4505-ab45-ad77d9b1ffd9

</p>
</details> 

### Версия

>= 5.10.0

### Шаги воспроизведения

1. Использовать `<App mode="partial" />`.
2. Создать список элементов из `<Cell draggable />`, чтобы на странице появился скролл.
3. Попробовать перетащить один из элементов `<Cell draggable />` к нижнему краю области видимости
4. ❌ Страница не автоскролится вниз.

### Ожидаемое поведение

Страница автоскролится вниз.

**Comment by inomdzhon** [comment]
<details><summary>Workaround</summary>
<p>

```js
/**
 * TODO [@vkontakte/vkui>=5.10.1] Удалить этот патч.
 *
 * [Workaround для VKUI v5.10.0]
 *
 * В VKUI v5.10.0 у `Cell` в режиме `draggable` добавили вертикальный автоскролл страницы, если мы тащим элемент к краю области видимости.
 *
 * НО! Текущая реализация не учитывает, что на странице может не использоваться `html, body { height: 100% }` (или `height: 100vh`).
 *
 * Поэтому мы временно, пока ждём фикса от VKUI, перебиваем `height` у `document.documentElement.getBoundingClientRect()` на `document.documentElement.clientHeight`.
 *
 * @see https://github.com/VKCOM/VKUI/releases/tag/v5.10.0
 */
const patchDocumentElementGetBoundingClientRectFn = () => {
  const origin = document.documentElement.getBoundingClientRect.bind(document.documentElement);
  
  Object.defineProperty(document.documentElement, 'getBoundingClientRect', {
    writable: true,
    value: () => {
      const patchedHeight = document.documentElement.clientHeight;
  
      const { x, y, width } = origin();
  
      return DOMRect.fromRect({ x, y, width, height: patchedHeight });
    },
  });

  return function cleanup() {
    Object.defineProperty(document.documentElement, 'getBoundingClientRect', {
      writable: true,
      value: origin,
    });
  };
}
```

</p>
</details>

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.1" target="_blank">v5.10.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.1" target="_blank">v6.0.1</a> 🎉
