### ISSUE TITLE
SelectMimicry. При disabled={true}, срабатывает onClick. 

### ISSUE THREAD

**Issue by semgoSE** [VKCOM/VKUI#635]
[bandicam 2020-04-12 16-01-07-779.zip](https://github.com/VKCOM/VKUI/files/4466372/bandicam.2020-04-12.16-01-07-779.zip)
P.S В архиве видео.

**Comment by fedorov-xyz** [comment]
Спасибо за issue! Исправлено в версии 3.6.0.
