### ISSUE TITLE
[Bug][ModalCard]: Не реализован крестик для закрытия 

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6362]
### Описание

В figma есть параметр (Close button) для включения крестика у компонента в правом верхнем углу, в коде не реализовано

### Версия

5.10.0

### Скриншоты

![Снимок экрана 2024-01-10 в 15 54 26](https://github.com/VKCOM/VKUI/assets/42776347/81e2b972-a770-48b1-b402-ddd2c82e0bfc)

**Comment by BlackySoul** [comment]
Привет! Вот здесь есть [пример](https://vkcom.github.io/VKUI/#/ModalCardBase?id=example3) или это что-то не то?

**Comment by MrZillaGold** [comment]
Привет, да оно, спасибо, проглядел(

**Comment by MrZillaGold** [comment]
в vkui common крестик есть у мобилок, но в доке он для android скрывается

**Comment by BlackySoul** [comment]
> в vkui common крестик есть в мобильной версии, но в доке он для android скрывается

По дизайн-системе по умолчанию (`dismissButtonMode='outside'`) у нас крестик рисуется вне модалки для `compact`-режима, для `regular`-режима в андроиде скрывается, в iOS форсится отрисовка внутри.  Если задать `dismissButtonMode='inside'`, то во всех режимах на всех платформах крестик показывается внутри. Какой у вас кейс?

**Comment by MrZillaGold** [comment]
опять проглядел, все норм, спасибо!
