### ISSUE TITLE
[Doc]: в миграции для Accordion не совсем правильный код

### ISSUE THREAD

**Issue by scffs** [VKCOM/VKUI#6368]
### Описание

[Дока](https://vkcom.github.io/VKUI/6.0.0-beta.3/#/Migrations) предлагает использовать это:

![image](https://github.com/VKCOM/VKUI/assets/67464545/9439a14c-8e15-4c5b-9ff7-525a3549ea37)

Но при 
```tsx 
onChange={(open) => open && setOpenId(id)}
```
открытый элемент аккордиона нельзя закрыть (свернуть) при клике на него, а только после открытия любого другого 

В то же время сама [страница](https://vkcom.github.io/VKUI/6.0.0-beta.3/#/Accordion) в доке компонента `<Accordion />` использует другой код, с помощью которого компонент можно спокойно закрыть (свернуть)

![image](https://github.com/VKCOM/VKUI/assets/67464545/93bf8187-4e93-4fa9-940f-b550a77573b9)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉
