### ISSUE TITLE
[Bug]: required работает некорректно с CustomSelect

### ISSUE THREAD

**Issue by svyatoslavpavlov** [VKCOM/VKUI#6371]
### Описание

required требует заполнения поля даже если оно заполнено
в версии 5.9.6 все работает корректно

### Версия

5.10.0

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

добавить required и выбрать опцию

### Ожидаемое поведение

форма отправляется

### Скриншоты

![image](https://github.com/VKCOM/VKUI/assets/7815563/bb38d30f-d914-4448-a1a4-eb31a6b82d47)

**Comment by mendrew** [comment]
Спасибо за issue! Действительно, не туда передаём `required`. Должны передавать на скрытый нативный `select`, а передаем на инпут, нужный для поиска по списку.

**Comment by inomdzhon** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.0" target="_blank">v6.0.0</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.1" target="_blank">v5.10.1</a> 🎉
