### ISSUE TITLE
[Bug]: WriteBarIcon ворнинг при наличии aria-label

### ISSUE THREAD

**Issue by Anastasia951** [VKCOM/VKUI#6383]
### Описание

Ворнинг в консоли у компонента WriteBarIcon с указанным aria-label

### Версия

5.10.0

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

```
<WriteBarIcon mode="send" aria-label="test" />
```

### Ожидаемое поведение

Нет ворнинга в консоли

### Скриншоты

<img width="532" alt="image" src="https://github.com/VKCOM/VKUI/assets/77168808/ab0ae16a-7da5-4d20-8f1d-666dbd471d55">

**Comment by mendrew** [comment]
@Anastasia951 Спасибо за issue!
Действительно, ошиблись в условии. В v6 уже [переделали](https://github.com/VKCOM/VKUI/blob/22111f79ea4f13e24136794ddcddc269b06d90d7/packages/vkui/src/components/WriteBarIcon/WriteBarIcon.tsx#L95-L105). Для v5 надо будет поправить.

**Comment by inomdzhon** [comment]
- closed this as [completed](https://github.com/VKCOM/VKUI/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in #6385

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.1" target="_blank">v5.10.1</a> 🎉
