### ISSUE TITLE
[Feature][HorizontalCellShowMore]: stretched проп

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6387]
### Описание

В кейсах с динамической высотой контента нам нужно располагать по центру HorizontalCellShowMore не просчитывая size, сейчас мешает margin-bottom у контейнера, который прижимает контент к верху родителя.

### Скриншоты

![image](https://github.com/VKCOM/VKUI/assets/42776347/920ce6c9-2e5b-4394-8b8b-bcf06e15e668)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.3.0" target="_blank">v6.3.0</a> 🎉
