### ISSUE TITLE
[Bug][DateInput]: Перестает работать фокус в DateInput после нажатия на кнопку "Готово"

### ISSUE THREAD

**Issue by anatrobina** [VKCOM/VKUI#6392]
related: https://github.com/VKCOM/VKUI/issues/6244

### Описание

Если DateInput со временем, и нажимать на кнопку "Готово" после выбора даты, то в некоторых случаях пропадает фокус, и календарь не открывается.

### Версия

6.0.0
Желательно поправить и в v5.10.0

### Шаги воспроизведения

1. Выбрать DateInput с выбором времени
2. Нажать в него и выбрать любую дату и время
3. Нажать на кнопку "Готово"
4. Попытаться нажать в инпуте на пустое пространство чтобы вызвать пикер
![telegram-cloud-photo-size-2-5276237246212724597-x](https://github.com/VKCOM/VKUI/assets/139476024/24ef859f-8c4f-4d21-8bea-e102158f4f67)
5. Календарь не открывается
ИНОГДА календарь открывается в первый раз, тогда баг воспроизводится если повторить снова шаги 2-4.

### Ожидаемое поведение

Календарь будет открываться одинаково по клику во всей области инпута вне зависимости от того, закрыли мы его кликом извне или нажали на кнопку "Готово".

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.1" target="_blank">v5.10.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.1" target="_blank">v6.0.1</a> 🎉
