### ISSUE TITLE
[Bug]: Gallery в режиме looped с timeout при возвращении на вкладку пееключает слайды подряд

### ISSUE THREAD

**Issue by kaspian122** [VKCOM/VKUI#6397]
### Описание

Постоянно стал воспоизводиться баг что Gallery в режиме looped с timeout  
`<Gallery slideWidth="95%" align="center" timeout={15000} isDraggable looped showArrows>`
при возвращении на давно открытую вкладку (порядка минут 5) начинает подряд переключать слайды  

### Версия

5.10.0

### Шаги воспроизведения

Создать галерею `<Gallery slideWidth="95%" align="center" timeout={15000} isDraggable looped showArrows>`
и добавить в неё более 2 слайдов

### Ожидаемое поведение

При возвращении нет быстрой прокрутки галереи и тамер для автопереключения слайдов запускается заново на текущем слайде

### Скриншоты

https://github.com/VKCOM/VKUI/assets/39019501/d9e631c9-813e-4458-b6e8-220faddb3c22

**Comment by mendrew** [comment]
Спасибо @kaspian122!
Вижу, что уже есть такая задача, по более младшей версии. Перенёс важную часть описания туда и ссылку на эту задачу.

А эту закрою как дубликат.

Странно, что не воспроизводится в документации.
