### ISSUE TITLE
[Feature][Typography]: Экспортировать наружу TypographyProps 

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6400]
### Описание

При создании компонентов, которые завязаны на компоненты типографики используем `ComponentType<TypographyProps>`, чтобы ограничить передаваемый компонент внешне.

<img width="770" alt="Снимок экрана 2024-01-18 в 13 02 39" src="https://github.com/VKCOM/VKUI/assets/42776347/7d6d1678-a066-491e-8c57-d986918c3b4a">

Сейчас этот тип не экспортируется наружу библиотеки - приходится обращаться напрямую к файлу, в котором находится этот интерфейс.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.1.0" target="_blank">v6.1.0</a> 🎉
