### ISSUE TITLE
[Feature][CustomScrollView]: Возможность изменения overscroll-behavior

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6407]
### Описание

В некоторых случаях нужно заблокировать возможность прокрутки body, по достижении границ прокрутки CustomScrollView - например всплывающие меню поверх основного интерфейса. Это можно сделать через `overscroll-behavior: none`, но из-за реализации компонента, нужно писать сложный селектор, чтобы дойти до элемента с прокруткой. Нужно внешнее api для изменения этого свойства.

Проп `noOverscroll: boolean` (?)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.3.0" target="_blank">v6.3.0</a> 🎉
