### ISSUE TITLE
[Bug]: Контент в Accordion перестает скрываться

### ISSUE THREAD

**Issue by BlackySoul** [VKCOM/VKUI#6414]
### Описание

При достаточно большом контенте в `Accordion` при первом рендере перестает скрываться часть контента. 

### Версия

v6

### Шаги воспроизведения

Зайти на на документацию компонента [Accordion](https://vkcom.github.io/VKUI/#/Accordion)
Вставить в качестве контента достаточно большой контент, например:
`
Mr and Mrs Dursley, of number four, Privet Drive, were proud to say that they were perfectly normal, thank you very much. They were the last people you’d expect to be involved in anything strange or mysterious, because they just didn’t hold with such nonsense. Mr Dursley was the director of a firm called Grunnings, which made drills. He was a big, beefy man with hardly any neck, although he did have a very large moustache. Mrs Dursley was thin and blonde and had nearly twice the usual amount of neck, which came in very useful as she spent so much of her time craning over garden fences, spying on the neighbours. The Dursleys had a small son called Dudley and in their opinion there was no finer boy anywhere. The Dursleys had everything they wanted, but they also had a secret, and their greatest fear was that somebody would discover it. They didn’t think they could bear it if anyone found out about the Potters. Mrs Potter was Mrs Dursley’s sister, but they hadn’t met for several years; in fact, Mrs Dursley pretended she didn’t have a sister, because her sister and her good-for-nothing husband were as unDursleyish as it was possible to be. The Dursleys shuddered to think what the neighbours would say if the Potters arrived in the street. The Dursleys knew that the Potters had a small son, too, but they had never even seen him. This boy was another good reason for keeping the Potters away; they didn’t want Dudley mixing with a child like that. 
`

### Пример с воспроизведением

Можно увидеть воспроизведение здесь - https://scffs.github.io/portfolio/

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.1" target="_blank">v6.0.1</a> 🎉
