### ISSUE TITLE
[Feature]: Добавить в Banner возможность контролировать цвет типографии

### ISSUE THREAD

**Issue by Dryzhakovv** [VKCOM/VKUI#6432]
### Описание

сейчас в данном компоненте цвет текста по дефолту - серый, нет возможности прокинуть Paragraph или Title, со своим исходным цветом, тк наследуется стили (на скрине - пример, как выглядит с другим цветом текста) 

### Скриншоты

<img width="496" alt="image" src="https://github.com/VKCOM/VKUI/assets/37025364/88a073a3-b402-4d6b-948d-9acd66d134ff">

**Comment by BlackySoul** [comment]
Привет! Пока цвет текста можно переопределить, передав `className` компоненту `Banner` и задав `css`-переменным, которые отвечают за `header`(`--vkui--color_text_primary`) или `subheader` (`--vkui--color_text_subhead`), собственные значения. Либо можно точечно обернуть любой компонент типографики в дополнительный `span` также с собственным `className`, в котором задать `color` нужным цветом.
