### ISSUE TITLE
[Feature][Switch]: Привести дизайн к виду Material v3

### ISSUE THREAD

**Issue by qurle** [VKCOM/VKUI#6441]
### Описание

Сейчас у наших свитчей на Android и в веб-версии устаревший дизайн, в Material 3 они уже выглядят иначе. Пригодилась бы возможность включать новый дизайн. Когда команда Android-разработки обновит его у себя, перейдём на него полностью и откажемся от старой версии.

У нового свитча есть анимация  по аналогии [с анимацией в Material](https://m3.material.io/components/switch/guidelines#002b2a0f-feb0-49a2-bdd4-a3029f9c83d8). 
[Прототип](https://www.figma.com/proto/2sQl2eaxsp7RDRdMOeneEC/%F0%9F%92%A0-VKUI-Common-Library?page-id=69%3A5007&type=design&node-id=74958-36232&viewport=-4951%2C-6432%2C2.29&t=tEtX2W8W0AUkucWk-1&scaling=min-zoom&starting-point-node-id=74958%3A36232&show-proto-sidebar=1&mode=design) | [Макет](https://www.figma.com/file/2sQl2eaxsp7RDRdMOeneEC/%F0%9F%92%A0-VKUI-Common-Library?type=design&node-id=74958%3A48145&mode=design&t=33NPZ0VZjUA9wVcp-1)

В макете вынес саму переключалку в отдельный внутренний компонент Switch Toggle. Раньше Switch переиспользовался сам в себе и это вызывало проблемы. Все старые стейты Switch'a сохранил для совместимости.

[Макет с дизайном ↗](https://www.figma.com/file/2sQl2eaxsp7RDRdMOeneEC/%F0%9F%92%A0-VKUI-Common-Library?type=design&node-id=74958-36208&mode=design&t=33NPZ0VZjUA9wVcp-11)

### Скриншоты

![image](https://github.com/VKCOM/VKUI/assets/32414396/c7bfeac5-7c3c-4c4e-9c90-bc60f12fa1a1)

**Comment by Zaycevq** [comment]
@Fliqle

**Comment by inomdzhon** [comment]
> [!NOTE]
> Параметр в коде назовём `useAndroidMaterial3`
