### ISSUE TITLE
[Feature]: Переименовать Badge → Dot, ContentBadge → Badge

### ISSUE THREAD

**Issue by qurle** [VKCOM/VKUI#6444]
### Описание

Сейчас бейджом называется точка, и это может немного путать.
Хотим использовать имя Badge для бейджа, который будет [текстовой или иконочной плашкой](https://www.figma.com/file/2sQl2eaxsp7RDRdMOeneEC/%F0%9F%92%A0-VKUI-Common-Library?type=design&node-id=75548%3A26786&mode=design&t=s06WM4TqSowLZi9y-1).

### Скриншоты

<img width="1087" alt="image" src="https://github.com/VKCOM/VKUI/assets/32414396/f4e80f04-66b9-40c0-ab6d-934e0183a595">

---

- см. #6445

**Comment by SevereCloud** [comment]
Оставляем как есть, поскольку все это по сути [badges](https://m3.material.io/components/badges/overview). Название Dot может конфликтовать с другими точками
