### ISSUE TITLE
[Feature][7.0.0]: Привести значения size к единому виду

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6474]
### Описание

Сейчас Button примнимает size в виде коротких значений - 1 буква: s | m | l.
При этом у Header size описывается словами: regular | large.

Нужно прийти к одинаковому варианту как в коде, так и в Figma, кажется проще уйти от длинных слов, так как их использование в самом VKUI и зависимых проектах меньше. 
Но при этом появляется вопрос что делать с regular обозначением - `r` выглядит странно. Как из вариантов отказываться от этого нейминга вообще и переименовывать в small - `s`

**Comment by qurle** [comment]
> Нужно прийти к одинаковому варианту как в коде, так и в Figma

В фигме (и в нативе) хотели бы оставить именование Extra Small → Small → Medium → Large → Extra Large.
На разработке можете перейти к таким же, либо маппить их на xs → s → m → l → xl.

Если переводить пропы из фигмы в код в голове будет неудобным, можно в теории подключить [Code Connect](https://github.com/figma/code-connect/blob/main/cli/README.md). Он для Dev Mode будет генерировать и показывать корректный код.
 
 
> Но при этом появляется вопрос что делать с regular обозначением - r выглядит странно

От Regular переходим в Medium (M)
Regular / Compact не трогаем.

**Comment by EldarMuhamethanov** [comment]
@qurle 
> От size="regular" переходим к Medium (M)

![Image](https://github.com/user-attachments/assets/a053e9f5-60b2-4b73-b0dd-9544050ee173)

У компонента Spinner есть и regular и medium size. Как быть в таком случае?

**Comment by qurle** [comment]
> У компонента Spinner есть и regular и medium size. Как быть в таком случае?

Разбирать отдельно. Такие случаи — не круто.

**Comment by EldarMuhamethanov** [comment]
В целом можно как breaking change `regular` заменить на `m`, `medium` на `l`, `large` на `xl`. @qurle Что думаешь?

**Comment by qurle** [comment]
Прямо сейчас не скажу, надо смотреть дизайн и кейсы использования. Если найдутся ещё случаи, где **не** Small / Medium / Large, можно заносить сюда.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.0" target="_blank">v7.0.0-beta.0</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
