### ISSUE TITLE
[Bug][ImageBase]: Не экспортируются пропы компонента наружу 

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6475]
### Описание

В точке входа в библиотеку нет экспорта ImageBaseProps

### Версия

5.0.0 - 6.0.0

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.1" target="_blank">v6.0.1</a> 🎉
