### ISSUE TITLE
[Bug][AdaptivityProvider]: не вычисляется sizeY при передаче только viewWidth

### ISSUE THREAD

**Issue by mendrew** [VKCOM/VKUI#6476]
### Описание

Если в `AdaptivityProvider` передавать только `viewWidth`, то `sizeY` значение, возвращаемое из `useAdaptivity`(хука, будет не определено, а значит адаптивностью компонентов будут управлять css media queries.

В тоже время, если вызвать хук `useAdaptivityWithJSMediaQueries`, `sizeY` будет не только определено, но и будет соответствовать значениям `viewWidth`, переданным в `AdaptivityProvider`.

Так как у нас во многих компонентах для адаптивности используется `useAdoptive`, то в окружении, где у `AdoptiveProvider` меняется `viewWidth` в зависимости от ширины, компоненты не будут адаптироваться в соответствии с `viewWidth`, а будут подстраиваться под значения, заданные по умолчанию с помощью css media queries.

Где это может быть проблемой? Кастомные компоненты, использующие `useAdoptive` или `useAdaptivityWithJSMediaQueries` и компоненты VKUI будут по разному адаптироваться под размер экрана, при разных размерах.

### Версия

v5.10.0, v6.0.0

### Шаги воспроизведения

Достаточно в AdaptiveProvider передать только свойство `viewWidth={ViewWidth.SMALL_TABLET}` чтобы в хуке `useAdaptivityWithJSMediaQueries` вернулось `sizeY="compact'`, или  `viewWidth={ViewWidth.MOBILE}`, чтобы в хуке useAdaptivityWithJSMediaQueries` вернулось `sizeY="regular'`.

В то время как в `useAdaptive` `sizeY` будет `undefined`.

### Ожидаемое поведение

Ожидается, что при передаче `viewWidth` и `hasPointer` в `AdoptiveProvider` значения `sizeY`, возвращаемые `useAdoptive` и `useAdaptivityWithJSMediaQueries`, будут совпадать.

### Пример с воспроизведением

https://codesandbox.io/p/sandbox/musing-brook-ntpl25

Тут в AdoptiveProvider передаются разные `viewWidth`, в зависимотси от ширины экрана.
В компоненте SpecialButton возвращается текстовое значение sizeY из useAdoptive().

В качестве примера можно ожидать, что при ширине экрана меньше 600px sizeY будет равно regular, а при ширине больше 600px sizeY будет равно compact.
Но возвращается значение по умолчанию `none`, что значит, что sizeY = undefined при любой ширине экрана.
Ожидается, что значение будет меняться, если у пользователя есть мышка, а не тач устройтсво.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.1" target="_blank">v5.10.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.1" target="_blank">v6.0.1</a> 🎉
