### ISSUE TITLE
[Bug][ImageBase.Badge]: Тень компонента перекрывает его содержимое

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6491]
### Описание

Если вложить в ImageBase.Badge кликабельный элемент, то мы не сможем с ним никак взаимодействовать из-за того, что его перекрывает before с классом `ImageBaseBadge--background-shadow`. 

### Версия

5.0.0-6.0.0

### Ожидаемое поведение

`pointer-events: none` у `ImageBaseBadge--background-shadow::before`

### Скриншоты

<img width="600" alt="Снимок экрана 2024-01-31 в 02 16 39" src="https://github.com/VKCOM/VKUI/assets/42776347/b6af4944-4c3e-42f4-8b79-61d8ab270b16">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.1" target="_blank">v6.0.1</a> 🎉
