### ISSUE TITLE
[Bug][iOS]: Уезжает навбар при показе клавиатуры.

### ISSUE THREAD

**Issue by nayzak** [VKCOM/VKUI#6495]
### Описание

На iOS, в приложении ВКонтакте, в любом мини-аппе навбар перестает быть прибитым к верху вебвью, когда показана клавиатура. На стороне BrowserBridge проблем не увидели: top inset мы не меняем при появлении клавиатуры. Вероятно это либо системное поведение (iOS), которое невозможно обойти. Либо неучтенный кейс в реализации навбара.

### Версия

-

### В каких браузерах воспроизводится проблема?

Другое (укажите в описании)

### Шаги воспроизведения

1. На iOS, в приложении ВКонтакте открыть любой мини-апп с полями ввода, например https://vk.com/test_vkapp
2. Поскроллить контент, удостовериться, что навбар прибит к верхней границе вебвью
3. Вызвать экранную клавиатуру, ткнув в любое поле ввода
4. Поскроллить контент — навбар больше не прибит к верхней границе вебвью.

### Ожидаемое поведение

Навбар не должен уезжать за пределы экрана

### Скриншоты

![SimulatorScreenRecording-iPhone15Pro-2024-01-31at12 25 31-ezgif com-video-to-gif-converter](https://github.com/VKCOM/VKUI/assets/570008/603f7b3f-3b38-4447-b353-695f6b0f72db)

**Comment by SevereCloud** [comment]
К сожалению это системное поведение iOS
