### ISSUE TITLE
[Feature][ImageBase]: Возможность установки пользовательского значения object-fit

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6498]
### Описание

Иногда нам нужны пользовательские значения для `object-fit` у `ImageBase`, сейчас стиль зафиксирован `cover` значением.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.3.0" target="_blank">v6.3.0</a> 🎉
