### ISSUE TITLE
[Bug][Link]: Обнуление стилей агента для button 

### ISSUE THREAD

**Issue by ThreshHNS** [VKCOM/VKUI#6503]
### Описание

Необходимо обнулять стили агента для button (тэг при отсутствии свойства href) в компоненте `Link`.
Столкнулись с проблемой, что браузер устанавливает `text-align: center` для кнопок, для ссылок значение `initial`.

### Версия

5.10.0

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.3" target="_blank">v6.0.3</a> 🎉
