### ISSUE TITLE
Ошибка при импорте usePlatform

### ISSUE THREAD

**Issue by PavelMartinez** [VKCOM/VKUI#653]
https://vkcom.github.io/vkui-styleguide/#section-utils

При глобальном импорте usePlatform вылетает следующая ошибка: 
![image](https://user-images.githubusercontent.com/44809625/80023160-cd011980-84e5-11ea-8ff1-eebb7d1017db.png)

import { usePlatform, ANDOID, IOS } from '@vkontakte/vkui/dist/hooks/usePlatform'
При  импорте из dist, вылетает с ошибкой: 
![image](https://user-images.githubusercontent.com/44809625/80023932-f53d4800-84e6-11ea-9f0e-a992066477c2.png)

**Comment by ArthurStam** [comment]
вам нужно обновить @vkontakte/icons до 1.20.2
