### ISSUE TITLE
[Bug]: PullToRefresh ломает другие компоненты, опирающиеся на Touch 

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#6530]
### Описание

На примере. Создаем панель с HorizontalScroll (внтури много HorizontalCell), вся панель при этом оборачивается в 
PullToRefresh.

ФР: Поломана доступность. Не получается легко и нативно скроллить HorizontalScroll. Нужно подбирать очень конкретные горизонтальные углы жестов, чтобы скролл получился.

ОР: Доступность в порядке. Взаиможействие с HorizontalScroll внутри PullToRefresh такое же легкое, как в случае, когда он не обернут в PullToRefresh.

Проверял на iOS.

Демо код: https://codesandbox.io/p/sandbox/agitated-fast-zs3pjf?file=%2Fsrc%2FApp.tsx
Демо фулскрин (для открытия на моб iOS): https://zs3pjf.csb.app/

### Версия

Проблема стала проявляться, начиная с версии https://github.com/VKCOM/VKUI/releases/tag/v5.9.3.

Предположительный мр с проблемой: https://github.com/VKCOM/VKUI/pull/5967/files. Очень смелый useGlobalEventListener на touchmove

### В каких браузерах воспроизводится проблема?

Safari

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.1" target="_blank">v6.0.1</a> 🎉
