### ISSUE TITLE
[Bug][Popper]: Не работает autoUpdateOnTargetResize проп

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6535]
### Описание

Если передать `autoUpdateOnTargetResize` для Popper и начать в нем изменять контент, то не происходит перерасчет позиции компонента отнсительно рефа к которому он прикреплен. 

Способы решения которые обсудили:

1. Используем ResizeObserver, если он не поддержан в браузере то делаем фоллбек на 2 пункт или для всех случаев используем сразу 2 пункт.
2. Рисуем iframe на всю ширину и высоту Popper, подписываемся на его ресайз, относительно этого ивента триггерим перерасчет. 

### Версия

5.0.0-6.0.0

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.1" target="_blank">v6.0.1</a> 🎉
