### ISSUE TITLE
[Bug]: Не работает formEl.reset() у Textarea и Writebar

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#6560]
### Описание

Не работает нативный formEl.reset() для react uncontrolled компонентов VKUI Textarea и Writebar. При этом VKUI Input работает в порядке.

**Демо**:
https://codesandbox.io/p/sandbox/black-resonance-j7gzxq?file=%2Fsrc%2FApp.tsx

**Причина**:
Снаружи можно пользоваться компонентами как неконтроллируемыми (с использованием defaultValue). Но внутренняя реализация Textarea и Writebar сделана так, что они всегда являются стейт-контроллируемыми (хук useEnsuredControl). Такая реализация убивает нативную работу с form-контроллами. Это вводит разработчика в заблуждение.

Также разработчик, не зная внутренней реализации всегда-контролируемого компонента, может захотеть занулить значение Textarea и Writebar через реф. Это делать не совсем корректно делать для контролируемых компонентов. 

Ожидаемое поведение: внутренняя реализация (не)контролируемая в зависимости от внешних пропсов

### Версия

6.0.0

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.1" target="_blank">v6.0.1</a> 🎉
