### ISSUE TITLE
[Bug]: Group description имеет неверный отступ в vkcom

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#6576]
### Описание

На примере из документации. Остров "Адреса".

<img width="324" alt="image" src="https://github.com/VKCOM/VKUI/assets/22776192/6d6a81aa-404f-4dd1-bf65-1bdaf66b2d24">

В реализации компонента отступы зашиты. Лучше перевести на vkui-tokens.

### Версия

6.0.0

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.1" target="_blank">v6.0.1</a> 🎉
