### ISSUE TITLE
Добавление VK.COM платформы в usePlatform

### ISSUE THREAD

**Issue by PavelMartinez** [VKCOM/VKUI#658]
Сейчас usePlatform() в веб версии выводит "ios". Добавьте, пожалуйста, определение веб версии.

**Comment by ArthurStam** [comment]
Привет, мы сейчас как раз работаем над адаптацией VKUI под другие платформы, в том числе десктопную веб версию vk.com. Естественно, дело там не ограничится обновлением usePlatform. Следите за #665
