### ISSUE TITLE
[Bug][Button]: Пропал плавный переход между состояниями компонента

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6586]
### Описание

В 5 версии был плавный переход между hover/active/default состояниями, сейчас в 6 версии анимации нет вообще, переходы выглядят резкими. 

### Версия

6.0.0

### В каких браузерах воспроизводится проблема?

Chrome

### Скриншоты

5.10.0:
https://github.com/VKCOM/VKUI/assets/42776347/606708d4-b2de-405f-8801-7d68a0afc9c8

6.0.0:
https://github.com/VKCOM/VKUI/assets/42776347/a94d98c5-9ab6-4f2d-8222-2598da0a5e67

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.3" target="_blank">v6.0.3</a> 🎉
