### ISSUE TITLE
[Feature][SplitLayout]: centered проп 

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6587]
### Описание

Сейчас чтобы расположить колонки внутри SplitLayout приходится накидывать style с нужным значением, предлагаю вынести эту логику пропом centered у SplitLayout

### Скриншоты

<img width="471" alt="Снимок экрана 2024-02-17 в 23 06 44" src="https://github.com/VKCOM/VKUI/assets/42776347/8225f828-eed6-4251-a53a-04d8b1038b1a">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.1.0" target="_blank">v6.1.0</a> 🎉
