### ISSUE TITLE
[Bug]: ModalPage + Popout сбрасывают скролл панели

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#6604]
### Описание

Код с примером:
https://codesandbox.io/p/sandbox/musing-kapitsa-y72dh8

1. Панель, проскролить вниз
2. Открыть ModalPage
3. Внутри ModalPage открыть Popout (например ActionSheet)

ФР:
Скролл в фоне сбросился

ОР:
Скролл в фоне остался на месте

### Версия

5.10.0, 6.0.0

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.1" target="_blank">v5.10.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.1" target="_blank">v6.0.1</a> 🎉
