### ISSUE TITLE
[Feature]: Добавить возможность переопределять layout из AppRoot для Panel

### ISSUE THREAD

**Issue by mendrew** [VKCOM/VKUI#6607]
### Описание

Сейчас визульное отображение Panel и Group зависит от заданного значения `layout` в [AppRoot](https://vkcom.github.io/VKUI/#/AppRoot).

В [Group](https://vkcom.github.io/VKUI/#/Group) уже есть свойство `mode` которое позволяет переопределить режим отображения.

Нужно добавить такое же свойство и для Panel. Для того чтобы влиять на фон Panel.

**Comment by shevchux** [comment]
Предлагаю вообще подумать об отказе от layout в AppRoot. Подложку серую можно делать всегда на нужных панелях

**Comment by shevchux** [comment]
Давайте еще сверимся за размер дырки между островами. Нам дизайнеры рисуют поменьше в два раза.


<img width="409" alt="image" src="https://github.com/VKCOM/VKUI/assets/22776192/a620b951-b7dc-4915-b848-24685c308eeb">
