### ISSUE TITLE
Заголовок модального окна не сокращается тремя точками 

### ISSUE THREAD

**Issue by manaenckow** [VKCOM/VKUI#661]
![image](https://user-images.githubusercontent.com/48844646/80384575-b96efd80-88ad-11ea-9458-5edf0ef70e0f.png)

**Comment by ArthurStam** [comment]
Привет. Поправим, спасибо.

**Comment by SkyGopnik** [comment]
Закройте, раз PR был принят и баг уже не воспроизводится
