### ISSUE TITLE
[Feature]: Badge вложенный как label в PanelHeaderButton должен правильно позиционироваться 

### ISSUE THREAD

**Issue by mendrew** [VKCOM/VKUI#6612]
### Описание

Это уже есть для Counter. 

В дизайн системе у нас уже описано такое поведение, так что отступы известны: https://www.figma.com/file/2sQl2eaxsp7RDRdMOeneEC/%F0%9F%92%A0-VKUI-Common-Library?type=design&node-id=25141-205661&mode=design&t=neKCN6eW1hcC5m5d-4

### Скриншоты

<img width="647" alt="Screenshot 2024-02-22 at 12 26 10" src="https://github.com/VKCOM/VKUI/assets/5443359/a3e42d50-2c14-4337-8f2c-1dcb747a4af6">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.7.0" target="_blank">v6.7.0</a> 🎉
