### ISSUE TITLE
[Feature]: Дать возможность размещать блочные элементы в Banner

### ISSUE THREAD

**Issue by Semigradsky** [VKCOM/VKUI#6616]
### Описание

Сейчас у Banner всё что передаём в `header`, `subheader` и `text` оборачивается абзацами (`p`).
Абзац не может содержать блочные элементы, соотвтественно имеем ошибки, если хотим расположить, например, списки.
 https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element
 
 Возможное решение: заменить `p` на `div`.

### Скриншоты

![image](https://github.com/VKCOM/VKUI/assets/1198848/b387176a-13f6-4e71-bd3c-f17fcaaf8afe)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.2" target="_blank">v6.0.2</a> 🎉
