### ISSUE TITLE
[Bug]: В ChipsSelect нет возможности прокинуть disabled опции

### ISSUE THREAD

**Issue by BlackySoul** [VKCOM/VKUI#6629]
### Описание

Нельзя задизейблить опцию

### Версия

v5

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.1" target="_blank">v5.10.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.1" target="_blank">v6.0.1</a> 🎉
