### ISSUE TITLE
[Bug]: Не работает сброс DatePicker на iOS

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#6633]
### Описание

На примере https://codesandbox.io/p/sandbox/dank-firefly-hnp4qw
Без редактора, чтобы открыть на iOS: https://hnp4qw.csb.app/

Платформа: iOS

1. DatePicker defaultValue={{ day: 1, month: 1, year: 2006 }}
2. Кликаем по компоненту, в нативном окне выбираем другую дату.
3. Убираем фокус, кликаем по компоненту еще раз, нажимаем на "Сбросить" внизу слева

ФР: Не сбрасывется до defaultValue, остается прежне введенная дата
ОР: Сбрасывается до defaultValue. Точно так же, как это работает с нативным input type date (тоже есть в песочнице)

![image](https://github.com/VKCOM/VKUI/assets/22776192/57555867-59fb-4406-a201-2c769c7ddcc8)

### Версия

5.10.0, 6.0.0

**Comment by shevchux** [comment]
Проблема в том, что внутренняя реализация компонента DatePicker всегда контролируемая (value контролируется стейтом). Это ломает работу form.reset(). Проблема похожа на #6560

**Comment by shevchux** [comment]
up plz

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.1.1" target="_blank">v6.1.1</a> 🎉
