### ISSUE TITLE
[Bug]: ModalPage c dynamicContentHeight работает некорректно, если высота увеличивается более чем на 100%

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#6635]
### Описание

Код: https://codesandbox.io/p/sandbox/compassionate-wave-yjytpw

Смотрю с настоящего iOS устройства по ссылке https://yjytpw.csb.app/

Баг 1. Шаги [ios / android]
1. Клик "Open modal"
2. Клик "set height to 600"

ФР: модалка открылась на 70% экрана, нужен дополнительный жест для раскрытия ее на полный экран
ОР: модалка раскрылась на максимальную высоту, появился скролл

Баг 2. Шаги [ios / android]
1. Клик "Open modal"
2. Клик "set height to 600"
3. Клик "set height to 20"
4. Клик "set height to 200"

ФР: На шаге 3 модалка выросла на 100%, хотя должна была уменьшиться. На ios only Шаг 4 тоже не помогает уменьшить модалку.
ОР: Модалка изменяет размер в соответствии с размером контента.

Баг 3. Шаги [ios only]
1. Клик "Open modal"
2. Клик "set height to 600"
3. Клик "set height to 20"
4. Закрыть модалку
5. Клик "Open modal"

ФР: Модалка открылась на 100% высоту. Баг 2 запомнился, не сбрасывается
ОР: Модалка открылась с размером в соответствии с контентом

### Версия

5.10.0, 6.0.0

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v5.10.1" target="_blank">v5.10.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.1" target="_blank">v6.0.1</a> 🎉
