### ISSUE TITLE
[Bug]: PullToRefresh ломает iOS эластик скролла вниз

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#6645]
### Описание

На примере кода: https://codesandbox.io/p/sandbox/zen-antonelli-mv7n8q?file=%2Fsrc%2FApp.tsx%3A8%2C12
Без редактора для запуска на iOS смартфоне: https://mv7n8q.csb.app/

Галка "PullToRefresh" = off

1. Резкий скролл вниз - видим эластик эффект - ок
2. Дожидаемся остановки эластика, делаем еще раз жест вниз - видим эффект эластик - ок

Галка "PullToRefresh" = on (содержимое панели оборачивается в PullToRefresh)

1. Резкий скролл вниз - эластик эффекта нет - резкая остановка - не ок
2. По достижении нижнего положения скролла, делаем еще раз жест вниз - эластик эффекта нет - не ок

Ожидаемое поведение: как в примере, когда галка "PullToRefresh" = off. Это системное паттерновое поведение iOS, нарушение которого порождает ощущение, что что-то не в порядке.

### Версия

5.10.0, 6.0.0

Коллеги подсказывают, что в версии 5.1.0 проблемы нет.

**Comment by BlackySoul** [comment]
Уже [исправлено](https://github.com/VKCOM/VKUI/pull/6540)
