### ISSUE TITLE
[Bug]: Нельзя установить размеры ImageBase с сохранением оригинальных пропорций

### ISSUE THREAD

**Issue by andres-kovalev** [VKCOM/VKUI#6660]
### Описание

У `ImageBase` есть свойства `widthSize`/`heightSize` и `width`/`height` - первые вешаются на контейнер через стили, а вторые на саму картинку в качестве атрибутов. При этом есть класс, который картинке задает `height: 100%`. Из-за чего не получается сделать картинку, которая пропорционально тянется по ширине контейнера, если контейнер не имеет своей высоты.

### Версия

6.0.0

### Шаги воспроизведения

```
<div style={{ width: 400 }}>
  <ImageBase src="https://sun9-37.userapi.com/omrQBSDCWu-Es7_S2mw7g_MHVHn3F6ynRUdxhg/j1ca6UaDNck.png" widthSize="100%"/>
</div>
```

Картинка имеет высоту 0 (не видна)

### Ожидаемое поведение

Картинка растягивается на ширину контейнера, а по высоте сохраняет оригинальные пропорции

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.3.0" target="_blank">v6.3.0</a> 🎉
