### ISSUE TITLE
[Bug]: tabIndex для стрелок в HorizontalScroll

### ISSUE THREAD

**Issue by 3all** [VKCOM/VKUI#6661]
### Описание

Прошу добавить tabIndex -1 к стрелкам в компоненте HorizontalScroll. Или позволить управлять этим атрибутом сверху. aria-hidden для них вы уже установили, но этого иногда оказывается недостаточно

### Версия

5

### В каких браузерах воспроизводится проблема?

Chrome

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.2" target="_blank">v6.0.2</a> 🎉
