### ISSUE TITLE
[Feature]: Создать утилитарный компонент `EllipsisText`

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#6662]
### Описание

> [!NOTE]
> Название черновое.

Задача компонента, через CSS, убирать текст не помещающийся в ширину контейнера в многоточие.

## Параметры

Должен принимать `Component`, `getRootRef` и другие валидные DOM свойства. Проще всего использовать `RootComponent` и наследовать его интерфейс `RootComponentProps`.

---

- caused by #5840

### Скриншоты

```jsx
<Group header={<Header>Игры</Header>}>
  <HorizontalScroll>
    <div style={{ display: 'flex' }}>
      <HorizontalCell onClick={() => {}} size="m" header="Warma-geddon">
        <Image
          size={88}
          borderRadius="l"
          src={'https://sun9-45.userapi.com/c846418/v846418215/5cf20/Gd9mQ6dVXTw.jpg'}
        />
      </HorizontalCell>
      <HorizontalCell onClick={() => {}} size="m" header="Golden Valley">
        <Image
          size={88}
          borderRadius="l"
          src={'https://sun9-71.userapi.com/c849220/v849220453/147ade/0MtQXKEVsiQ.jpg'}
        />
      </HorizontalCell>
    </div>
  </HorizontalScroll>
</Group>
```

<img width="363" alt="image" src="https://github.com/VKCOM/VKUI/assets/5850354/93af169f-5c5f-4435-890c-32aa54a1b61e">

**Comment by akcent1132** [comment]
Я бы хотел взять эту задачу.
