### ISSUE TITLE
[Bug]: Клик по правой части Search временно сбрасывает фокус с инпута

### ISSUE THREAD

**Issue by danyadev** [VKCOM/VKUI#6682]
### Описание

У компонента Search, если ввести какой-то текст, появляется кнопка для очистки содержимого. Но если текста нет, то вместо кнопки остается просто отступ размером с эту кнопку

Фокус пропадает при зажатии левой кнопки мыши, и заново появляется при отпускании

Баг появился после https://github.com/VKCOM/VKUI/pull/5790

### Версия

5.10+, 6.0.1

### В каких браузерах воспроизводится проблема?

Chrome

### Скриншоты

https://github.com/VKCOM/VKUI/assets/35631027/17f5a925-a0ea-4332-83d8-b35898ff82c5

### Пример с воспроизведением

https://codesandbox.io/p/sandbox/adoring-frost-4pkxs6

Так же можно потыкать поиск по списку чатов в web.vk.me, чтобы увидеть, к чему это приводит

**Comment by vkcom-publisher** [comment]
Задача закрыта из-за отсутствия активности в течение последних 14 дней. Если это произошло по ошибке или проблема все ещё актуальна, откройте задачу повторно.
