### ISSUE TITLE
[Bug]: Документация не работает

### ISSUE THREAD

**Issue by Kriezdd** [VKCOM/VKUI#6686]
### Описание

https://vkcom.github.io/VKUI/ - очень долго грузится, весь интерфейс не активен в момент загрузки, через какое-то время страница прогружается (не засекал, но больше 5и минут точно) и всё становится активно, но при переходе на любой компонент, всё повисает снова.

### Версия

6.0.1

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.2" target="_blank">v6.0.2</a> 🎉
