### ISSUE TITLE
[Feature]: Добавить поддержку скролла в ChipsInput

### ISSUE THREAD

**Issue by dsedinkin** [VKCOM/VKUI#6688]
### Описание

Есть сервис, TargetViky https://vk.com/app51785816, в разделе "#/get/friends_users/select_users/" (друзья пользователей -> выбор друзей), есть интерактивный раздел, при выборе пользователей из поиска он заполняется и растягивается до бесконечности, что смещает контент ниже него.

ФР: ChipsInput растягивается до бесконечности. Смещая контент.
ОР: Иметь надстройку как в `<Textarea rows={9} />`или какой-то иной пропс для настройки высоты. И иметь скролл списка.

Как выглядит ChipsInput не заполненный:
<img width="648" alt="image" src="https://github.com/VKCOM/VKUI/assets/62930989/44460549-f836-4c99-b17c-8e2d62a9ec6e">
Как выглядит ChipsInput заполненный большим списком значений:
<img width="650" alt="image" src="https://github.com/VKCOM/VKUI/assets/62930989/ce90a414-4a6d-415a-a400-11f86eeebbfd">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.4.0" target="_blank">v6.4.0</a> 🎉
