### ISSUE TITLE
[Feature]: Уменьшить отступ между Group и увеличить border-radius

### ISSUE THREAD

**Issue by mendrew** [VKCOM/VKUI#6700]
### Описание

Необходимо привести Group к виду который чаще всего используется дизайнерами.

На данный момент вместо 16px расстояние между Group рисуют 8px. А border-radius используют 20px вместо 12px.
Такой вид используется в VK Знакомствах и на m.vk

Вопрос был поднят тут: https://github.com/VKCOM/VKUI/issues/6607#issuecomment-1953875306

Дизайнеры VKUI подтвердили, что следует перейти к такому варианту и дизайн в дизайн-системе тоже обновится.

**Comment by Zaycevq** [comment]
Скругление для Compact режима компонента Group должен остаться 12px. Мобильная (Regular) версия 20px
