### ISSUE TITLE
[Bug]: PullToRefresh multiple onRefresh calls

### ISSUE THREAD

**Issue by ponchicken** [VKCOM/VKUI#6715]
### Описание

При ptr на слабом  iOS девайсе, onRefresh может вызваться несколько раз.

### Версия

5.10.1, 6.0.1

### В каких браузерах воспроизводится проблема?

Chrome, Safari

### Шаги воспроизведения

Поймал только на iOS версии, на слабом девайсе или при CPU троттлинге.
Похоже на то, что из-за того что refreshing сделан через useState, он не успевает обновиться, до того как произойдёт следующий вызов onTouchMove

https://github.com/VKCOM/VKUI/assets/12897276/95c17d2d-8a75-4a7c-bc65-649964171eea

### Ожидаемое поведение

onRefresh вызывается один раз в рамках одного ptr

### Пример с воспроизведением

https://codesandbox.io/p/sandbox/reverent-flower-zzchyr

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.2" target="_blank">v6.0.2</a> 🎉
