### ISSUE TITLE
[Bug]: Некорректные боковые отступы у Search в ios

### ISSUE THREAD

**Issue by danillas** [VKCOM/VKUI#6719]
### Описание

Комопнент Search имеет разные боковые отступы.

### Версия

6.0.1

### В каких браузерах воспроизводится проблема?

Safari

### Ожидаемое поведение

Отступы одинаковые

### Скриншоты

![image](https://github.com/VKCOM/VKUI/assets/26124760/6d8ef330-14df-475c-86c2-8b737e82d608)

### Пример с воспроизведением

https://codesandbox.io/p/sandbox/kind-goodall-x5txq7?file=%2Fsrc%2FApp.js

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.2" target="_blank">v6.0.2</a> 🎉
