### ISSUE TITLE
[Bug]: Некорректные боковые оступы у сепаратора ModalPageHeader 

### ISSUE THREAD

**Issue by danillas** [VKCOM/VKUI#6722]
### Описание

В 5.10.1 ModalPageHeader не рисовал сепаратор. Приходилось добавлять вручную компонент `<Separator /> `. Получалось так:
<img width="342" alt="image" src="https://github.com/VKCOM/VKUI/assets/26124760/f09a3ccb-da88-49b2-8471-1c5396471fc0">

Ещё референс  - просмотр информации о себе в VK ios клиенте:

![image](https://github.com/VKCOM/VKUI/assets/26124760/57c9312b-b65b-4241-92c9-a3927b96c2c8)

### Версия

6.0.1

### В каких браузерах воспроизводится проблема?

Другое (укажите в описании)

### Шаги воспроизведения

1. Открыть ModalPage, у которой имеется ModalPageHeader с сепаратором
2. Сепаратор имеет некорректные боковые отступы

### Ожидаемое поведение

Отступ корректный. Сепаратор скрывается при скролле

### Скриншоты

<img width="327" alt="image" src="https://github.com/VKCOM/VKUI/assets/26124760/8c8f2699-e111-41b1-a935-ac993fb16d43">

### Пример с воспроизведением

Воспроизводится в песочнице
https://vkcom.github.io/VKUI/#/ModalRoot

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.2" target="_blank">v6.0.2</a> 🎉
