### ISSUE TITLE
[Bug]: Принудительная приоритизация 'vertical' align'а в компоненте Snackbar

### ISSUE THREAD

**Issue by JurijsKolesnikovs** [VKCOM/VKUI#6733]
### Описание

Snackbar форсит 'vertical' align на десктопных приложениях, что приводит к такому результату и невозможности явно задать горизонтальную ориентацию в vkuiSnackbar__content:

![snackbar](https://github.com/VKCOM/VKUI/assets/164325205/26871c8c-f226-46e5-91fe-2bda00975fec)

```
<StyledSnackbar
  onClose={this.onClose}
  mode="dark"
  before={ICON_MAP[type]}
  action={<Icon className={classes['closeIcon']} icon={cancelIcon} />}
  {...props}
/>
```

Кнопку закрытия я добавил именно в action, а не after, посколько в таком случае:
`after={<Icon className={classes['closeIcon']} icon={cancelIcon} onClick={this.onClose} />`

колбэк отрабатывает "в обход" функции close в Snackbar. 

### Версия

6.0.0

### В каких браузерах воспроизводится проблема?

Chrome

### Ожидаемое поведение

Ожидаемое поведение - при прокидывании layout приоритизировать именно его, чтобы явно задавать horizontal/vertical на десктопах.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.2" target="_blank">v6.0.2</a> 🎉
