### ISSUE TITLE
Не изменяется value у Select

### ISSUE THREAD

**Issue by FireworksX** [VKCOM/VKUI#676]
Если у Select изменить value не через выбор option, то он не отобразится
```jsx
           <Select
              disabled={this.marksList.length === 0}
              placeholder="Марка автомобиля"
              value={this.currentMark}
              onChange={e => this.selectMark(e.target.value)}
              getRef={this.getMarksRef.bind(this)}
            >
              {this.marksList.map((mark: string) => (
                <option key={mark} value={mark}>
                  {mark}
                </option>
              ))}
            </Select>
```

**this.currentMark** - это getter с Mobx хранилища
```ts
@computed get currentMark(): string {
    console.log(1)
    return this.props.calc.currentMark;
  }
```
При изменении **currentMark** getter срабатывает и console.log срабатывает, но value в Select не меняется

Если рядом поставить обычный select, то он нормально отработает
```jsx
           <select value={this.currentMark} placeholder="Марка автомобиля">
              {this.marksList.map((mark: string) => (
                <option key={mark} value={mark}>
                  {mark}
                </option>
              ))}
            </select>
```

![image](https://user-images.githubusercontent.com/22668125/80813994-bf2d5180-8bd3-11ea-924e-709282c10300.png)

**Comment by kiyasov** [comment]
Используй состояния, это не с библиотекой проблема.

**Comment by FireworksX** [comment]
> Используй состояния, это не с библиотекой проблема.

Почему я не могу использовать хранилище?
Если я отрисую рядом div, то там значение корректно изменится, как я показал в примере с обычным селектом

**Comment by kiyasov** [comment]
> > Используй состояния, это не с библиотекой проблема.
> 
> Почему я не могу использовать хранилище?
> Если я отрисую рядом div, то там значение корректно изменится, как я показал в примере с обычным селектом

Потому что это основы React, почитай про контролируемые и неконтролируемые компоненты. Я не говорил что не можешь использовать хранилище, просто это нужно всё перегонять через state. 


P.s Поправьте меня, если я не прав 😁

Пример

```
class ComponentName extends PureComponent {
  state = {
    currentMark: null
  };

  componentDidUpdate(prevProps) {
    let {
      calc: { currentMark }
    } = this.props;

    if (currentMark !== prevProps.calc.currentMark) {
      this.setState({
        currentMark
      });
    }
  }

  render() {
    const { currentMark } = this.state;

    return (
      <Select
        disabled={this.marksList.length === 0}
        placeholder="Марка автомобиля"
        value={currentMark}
        onChange={e => this.selectMark(e.target.value)}
        getRef={this.getMarksRef.bind(this)}
      >
        {this.marksList.map((mark: string) => (
          <option key={mark} value={mark}>
            {mark}
          </option>
        ))}
      </Select>
    );
  }
}
```

[https://ru.reactjs.org/docs/forms.html](url)

**Comment by FireworksX** [comment]
хмм... хорошо, значит буду перегонять через state, отпишусь если получится

**Comment by GeorgeBekh** [comment]
Возможно, это из той же серии: https://github.com/VKCOM/VKUI/issues/695

**Comment by thoughtspile** [comment]
@FireworksX прошло довольно много времени, но я набросал рабочий пример `Select + mobx`: https://codesandbox.io/s/vkui-mobx-w1umc
Баг не воспроизводится — видимо, всё же проблема в интеграции. Так что тикет закрываю.

@kiyasov (прогонять через стейт не обязательно, мобикс сам разруливает).
