### ISSUE TITLE
[Feature]: Оборачивать/заменять кнопки пагинатора на ссылки

### ISSUE THREAD

**Issue by rflban** [VKCOM/VKUI#6770]
### Описание

Частый кейс, при котором нажатие на кнопку пагинатора должно изменять урл в адресной строке браузера. Сейчас это можно сделать, повесив колбэк на смену страницы в пагинаторе, но логичнее сделать каждую кнопку пагинатора ссылкой. Это может выглядеть как-то так:

```tsx
<Pagination
            currentPage={currentPage}
            totalPages={totalPages}
            pageButton={({page, button}) => (
                        <Link to="/some/path/$page" params={{page}}>
                                    {button}
                        </Link>
            )}
/>
```

или

```tsx
<Pagination
            currentPage={currentPage}
            totalPages={totalPages}
            pageButton={({page, buttonProps, buttonContent}) => (
                        <Link {...buttonProps} to="/some/path/$page" params={{page}}>
                                    {buttonContent}
                        </Link>
            )}
/>
```

Так, например, делает библиотека simplebar - https://github.com/Grsmto/simplebar/tree/master/packages/simplebar-react#usage-with-3rd-party-libraries

**Comment by BorisChumichev** [comment]
Плюсую. Проблема в текущей реализации еще в том, что если делать переход по ссылке в колбеке, то не будет работать нативное поведение браузера cmd+click для открытия URL в соседней вкладке.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.1.0" target="_blank">v6.1.0</a> 🎉
