### ISSUE TITLE
RangeSlider: срабатывает swipeback на iOS при изменении крайнего левого значения

### ISSUE THREAD

**Issue by ArtemSviridov** [VKCOM/VKUI#678]
В официальном приложении ВКонтакте на iOS если в сервисе используется навигация поддерживающая swipeback, то становится не возможно изменить крайнее левое значение. Срабатывает и RangeSlider и swipeback.

Скринкаст - https://vk.com/video152873202_456239552

**Comment by ArthurStam** [comment]
Спасибо, поправим
