### ISSUE TITLE
[Feature]: Добавить размеры для Knob в компоненте Slider

### ISSUE THREAD

**Issue by Zaycevq** [VKCOM/VKUI#6785]
### Описание

Текущий ползунок большой и не подходит для всех, добавляем размеры S | M | L

Regular: S 16 | M 20 | L 28
Compact: S 12 | M 16 | L 24

Дизайн: 
IOS - https://www.figma.com/file/jvJUbY10EFMYTkbxNIIPqd/%F0%9F%92%A0-VKUI-iOS-Library?type=design&node-id=64302%3A24441&mode=design&t=yvwIUYmQhPBXmyQk-1
Common - https://www.figma.com/file/2sQl2eaxsp7RDRdMOeneEC/%F0%9F%92%A0-VKUI-Common-Library?type=design&node-id=83305%3A53798&mode=design&t=7vsmrihcVDLGVIw6-1

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.1.0" target="_blank">v6.1.0</a> 🎉
