### ISSUE TITLE
[Feature]: Создать компонент Drag & Drop [Web]

### ISSUE THREAD

**Issue by Zaycevq** [VKCOM/VKUI#6786]
### Описание

Компонент общий и часто появляется в разных продуктах. Хочется завести в базовой библиотеке решение для всех.

За основу можно взять Drag & Drop из VK Мессенджера.

Дизайн: https://www.figma.com/file/2sQl2eaxsp7RDRdMOeneEC/%F0%9F%92%A0-VKUI-Common-Library?type=design&node-id=83231%3A54655&mode=design&t=7vsmrihcVDLGVIw6-1

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.1.0" target="_blank">v6.1.0</a> 🎉
