### ISSUE TITLE
[Bug]: Исправить отступ в SimpleCell для состояния с Иконкой [iOS]

### ISSUE THREAD

**Issue by Zaycevq** [VKCOM/VKUI#6787]
### Описание

Текущий SimpleCell с включенным контентом Иконки для iOS рисует отступ 12px слева и 16px справа. Требуется изменить отступ справа, убрав дополнительные 4px у контента Иконки, чтобы получились равные отступы слева / справа по 12px

<img width="823" alt="simpleCell-paddings" src="https://github.com/VKCOM/VKUI/assets/91548592/eee9b6a1-ca2d-45fa-894c-f969ad788814">
<img width="492" alt="design-simpleCell-paddings" src="https://github.com/VKCOM/VKUI/assets/91548592/5c9f0d45-1121-40fd-b50b-aaeae0f34fcb">

### Версия

v6.0.2

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.3" target="_blank">v6.0.3</a> 🎉
