### ISSUE TITLE
Добавить коллбек открытия модальной страницы

### ISSUE THREAD

**Issue by godknowsiamgood** [VKCOM/VKUI#680]
Иногда надо сделать что-то при открытии модалки ModalPage. Возможно стоит добавить коллбек по окончании транзишена.

**Comment by eolme** [comment]
На закрытие тоже бы

**Comment by eolme** [comment]
Удобно было бы, если был бы хук по аналогии с useNavTransition

**Comment by inomdzhon** [comment]
API будет в ближайшем релизе (`v4.29.0`)
