### ISSUE TITLE
[Feature]: обновить css-loader до ^7.0.0

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#6805]
### Описание

 - https://github.com/webpack-contrib/css-loader/releases/tag/v7.0.0

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.0" target="_blank">v7.0.0-beta.0</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
