### ISSUE TITLE
[Feature]: Убрать прозрачность во вторичных табах

### ISSUE THREAD

**Issue by qurle** [VKCOM/VKUI#6808]
### Описание

В TabsItem c `mode=secondary` у текста и иконок стоит прозрачность `opacity: .72`
Её можно убрать — повысим контрастность и приведём к одному виду с остальными табами

Если вдруг нужен, вот [макет ↗️](https://www.figma.com/file/2sQl2eaxsp7RDRdMOeneEC/%F0%9F%92%A0-VKUI-Common-Library?type=design&node-id=25061-207232&mode=design&t=TsgXhCdF0lhntke2-11)

### Скриншоты

<img width="607" alt="image" src="https://github.com/VKCOM/VKUI/assets/32414396/b44f37fc-9dab-4aea-9dd4-bdb5369dbf9b">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.3" target="_blank">v6.0.3</a> 🎉
