### ISSUE TITLE
[Feature]: Изменить отступ для List / Action Sheet – platform [Android]

### ISSUE THREAD

**Issue by Zaycevq** [VKCOM/VKUI#6812]
### Описание

Текущие отступы слева / справа для List внутри Action Sheet – 20px, это сильно отбивает его от краев обертки. Требуется заменить на 16px для Regular и Compact режимов (в Material 3 отступы по 16px)

<img width="1707" alt="fix-paadings-list" src="https://github.com/VKCOM/VKUI/assets/91548592/84797aa8-bcf4-4ed1-8fa2-2a850905642c">
<img width="578" alt="m3-list" src="https://github.com/VKCOM/VKUI/assets/91548592/4a44179e-1c62-4adb-ad03-e2747498af9c">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.0.3" target="_blank">v6.0.3</a> 🎉
