### ISSUE TITLE
[Bug][Typography]: Некорректный display при передаче normalize

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6814]
### Описание

`normalize` проп обнуляет отступы для текста, выглядит так, что в данном случае он должен инлайниться и иметь `display` свойство с инлайном - например чтобы расположить два Title в строчку или в перемешку с другим текстом, сейчас стоит `display: block`

Возможно нужно добавить отдельный проп inline, normalize убирает отступы от браузерных стилей, но при этом мы все равно можем хотеть его показывать в блочном варианте, inline располагает элемент в строку

### Версия

6.0.0

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.0" target="_blank">v6.2.0</a> 🎉
