### ISSUE TITLE
[Feature]: ChipsSelect добавить onOpen, onClose

### ISSUE THREAD

**Issue by ramilashrafulin** [VKCOM/VKUI#6815]
### Описание

Хотелось бы иметь пропсы onOpen, onClose для отлавливания событий открытия и закрытия меню опций. Как в https://vkcom.github.io/VKUI/5.10.0/#/CustomSelect

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.0" target="_blank">v6.2.0</a> 🎉
