### ISSUE TITLE
[Feature]: Создать компонент Tool Button

### ISSUE THREAD

**Issue by Zaycevq** [VKCOM/VKUI#6817]
### Описание

Требуется реализовать компонент имеющий часть функционала Button, но с вертикальной компоновкой текст + иконка и своими токенами типографики / отступов.

Такие кнопки используются в продуктах: Истории, Музыка, Мессенджер, Профиль.

Дизайн iOS:
https://vk.cc/cw7OZ6

Дизайн Android:
https://vk.cc/cw7OSQ

Дизайн vkCom:
@EleonoraEvans // https://vk.com/cc

- - - -
Примеры из продуктов:
![story-tool-button](https://github.com/VKCOM/VKUI/assets/91548592/967e1fbd-7009-4f50-b6f8-abbac7bb1b52)
![music-tool-button](https://github.com/VKCOM/VKUI/assets/91548592/3bfad08d-73f8-42c0-895f-b531bc5e7dc8)
![messenger-tool-button](https://github.com/VKCOM/VKUI/assets/91548592/8f1db02b-1f13-4c7e-a816-68bd91c064d9)
<img width="366" alt="profile-tool-button" src="https://github.com/VKCOM/VKUI/assets/91548592/55761cf1-3124-41ba-b89b-3a8c5441dfb2">
<img width="691" alt="post-tool-button" src="https://github.com/VKCOM/VKUI/assets/91548592/02f76779-63f6-4057-a941-dc00fae743d9">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.1.0" target="_blank">v6.1.0</a> 🎉
