### ISSUE TITLE
[Bug]: ios Search. Запаздывает анимация кнопки Отмена

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#6833]
### Описание

Видео с замедлением

https://github.com/VKCOM/VKUI/assets/22776192/88bd1bc9-b925-4ca0-ba92-d77c568a117b

### Версия

6.0.2

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.2" target="_blank">v6.2.2</a> 🎉
