### ISSUE TITLE
[Bug][HorizontalCell]: Нет ограничения ширины внутреннего контента компонента 

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6834]
### Описание

Сейчас если вложить в компонент HorizontalCell в header поле текст в обертке по типу TextClamp получаем вот такой результат:

<img width="527" alt="Снимок экрана 2024-04-16 в 12 34 30" src="https://github.com/VKCOM/VKUI/assets/42776347/d8cd3a98-31ba-4e91-b464-a07539885a6b">

Рутовый контейнер с классом vkuiHorizontalCell ограничен по максимальной ширине, но тело ячейки с классом vkuiHorizontalCell__body нет.

Для решения проблемы на скриншоте выше нужно ограничить ширину тела ячейки с классом vkuiHorizontalCell__body на значения с вычетом before элемента, например если ячейка стоит первой в HorizontalScroll компоненте 

### Версия

6.0.0

### В каких браузерах воспроизводится проблема?

Chrome

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.2" target="_blank">v7.0.0-beta.2</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
