### ISSUE TITLE
[Feature]: Улучшить условие установки user-select: none

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#6835]
### Описание

В коде VKUI есть установка user-select none для тач устройств. Понимаю, это лучшая мимикрия под нативное поведение, чтобы интерфейс не выделялся, так как там это не принято.

![image](https://github.com/VKCOM/VKUI/assets/22776192/e48ead5a-3e27-41c7-94e4-ef88e3b243b9)

Но это применимо для мимикрии только под вебвью. Наш интерфейс умеет запускаться на mvk, там как будто возможность выделять элементы это ожидаемая история, так люди привыкли использовать веб.

Хорошо бы улучшить условие для использования user-select none? Например завязаться на проверку isWebView, который передается в ConfigProvider. Можно подумать о новом пропсе в AppRoot, чтобы перебивать поведение по-умолчанию.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.0" target="_blank">v6.2.0</a> 🎉
