### ISSUE TITLE
[Bug][HorizontalCell]: Некорректное поведение компонента при передаче size=l

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6836]
### Описание

При передаче в HorizontalCell size=l для компонента не устанавливается максимальная ширина, обычная стоит на значении auto и компонент зависит от контента в нем. В фигме size=l ограничен шириной в 140px.

Еще нужно подумать про режим динамической ширины компонента, так как сейчас с l size баг, все его используют для того чтобы вкладывать в эту ячейку контент с динамической шириной для получения нужных отступов в HorizontalScroll, такое поведение терять не хочется. 

### Версия

6.0.0

### В каких браузерах воспроизводится проблема?

Chrome

### Скриншоты

<img width="580" alt="Снимок экрана 2024-04-16 в 13 34 15" src="https://github.com/VKCOM/VKUI/assets/42776347/12304752-0f09-4b38-98a4-801b2e3be89f">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
