### ISSUE TITLE
Сжимается Avatar при использовании её в RichSell

### ISSUE THREAD

**Issue by gtishenko** [VKCOM/VKUI#684]
Если текста в RichCell много(и он как бы выходит за рамки экрана), при этом не важно, включен multiline или нет, аватарку сжимает.
![gFLL5RtWweo](https://user-images.githubusercontent.com/56306520/81246361-06767080-9020-11ea-9023-2dd67cea6788.jpg)

**Comment by ArthurStam** [comment]
Спасибо, поправим
