### ISSUE TITLE
[Feature][HorizontalScroll]: Добавить inline проп или сабкомпонент для flex

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6845]
### Описание

Сейчас для расположения горизонтального контента в компоненте, например список HorizontalCell, нужно отдельно обернуть контент в контейнер с `display: flex`, хочется чтобы было какое-то решение из коробки, либо проп - например inline, либо сабкомпонент от HorizontalScroll.

### Скриншоты

![Снимок экрана 2024-04-22 в 16 15 59](https://github.com/VKCOM/VKUI/assets/42776347/41726168-94ad-4edc-b50e-ff4c01959e3b)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.1.0" target="_blank">v6.1.0</a> 🎉
