### ISSUE TITLE
[Feature][TabsItem]: Возможность переопределения hoverMode и activeMode

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6849]
### Описание

Для некоторой продуктовой логики хотим заменять стейты hoverMode и activeMode у TabsItem на свои.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.1.0" target="_blank">v6.1.0</a> 🎉
