### ISSUE TITLE
[Bug]: При определённых условиях у ImageBase при загруженном изображении в углах может проглядывать фон

### ISSUE THREAD

**Issue by mendrew** [VKCOM/VKUI#6850]
### Описание

Иногда, у достаточно светлых картинок можно увидеть фон позади, если они были обрезаны за счёт родительского элемента.

### Версия

6.0.2

### Шаги воспроизведения

Необходимо иметь достаточно светлое изображение, вставленное в родителя с border-radius и overflow: hidden.
Для того, чтобы заметить в районе скруглений часть фона ImageBase нужно фон сделать отличным от основного фона приложения, например в светлой теме обернув ImageBase в `<AppearanceProvider value="dark">`, чтобы фон ImageBase стал темнее и было видно как он выглядывает позади картинки.

### Ожидаемое поведение

Фон ImageBase не должен выглядывать из-за изображения.

### Скриншоты

 ![image-parent-with-border-radius-image-does-not-have-visible-corners-from-image-background-android-chromium-light-1-snap-expected](https://github.com/VKCOM/VKUI/assets/5443359/754c65b0-4bc2-44f5-8e52-925748124a6e)

### Пример с воспроизведением

https://codesandbox.io/p/sandbox/still-dawn-kzr5lf

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.1.0" target="_blank">v6.1.0</a> 🎉
