### ISSUE TITLE
[Feature]: Дать возможность управлять пропами поля icon в Search 

### ISSUE THREAD

**Issue by BlackySoul** [VKCOM/VKUI#6851]
### Описание

В `Search` компонент в поле `icon` могут передавать иконки, обернутые, например, в `Popover`, чтобы при клике триггерилась выпадашка.

Из-за этого атрибуты доступности от `Popover` вешаются непосредственно на icon, а не кнопку, в которую все оборачивается. ﻿

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.3.0" target="_blank">v6.3.0</a> 🎉
