### ISSUE TITLE
[Bug]: Пропадает возможность скроллить textarea при вызове клавиатуры на Android устройстве

### ISSUE THREAD

**Issue by takaghi** [VKCOM/VKUI#6853]
### Описание

На странице присутствует **textarea** с ограниченной высотой и текст достаточной длины для появления скроллбара.
При фокусе на **textarea** вызывается клавиатура, если нижняя граница элемента "выше" клавиатуры, то поведение нормальное. Если клавиатура "сдвигает" **textarea**, то проскроллить текст внутри нельзя, скроллится вся страница.

добавление z-index к textarea, похоже, решает проблему

### Версия

6.0.2

### В каких браузерах воспроизводится проблема?

Chrome

### Скриншоты

https://github.com/VKCOM/VKUI/assets/976040/a3f345b5-7b75-429e-bbcc-9dce9e01c37c

### Пример с воспроизведением

https://codesandbox.io/p/sandbox/determined-solomon-kqpptn

**Comment by SevereCloud** [comment]
Это какие-то приколы работы хрома

https://github.com/VKCOM/VKUI/assets/14944123/51319b71-4033-4a2a-b18c-1143521f0503
