### ISSUE TITLE
[Feature]: Изменить кнопку "Назад" в Modal Page для темы vkCom

### ISSUE THREAD

**Issue by Zaycevq** [VKCOM/VKUI#6857]
### Описание

Текущая иконка chevron_left_24 крайне большая и жирная, выделяется на фоне её текста.
Уменьшаем до `chevron_left_outline_20`
Цвет: `icon_secondary`

Требуется только для темы vkCom.

<img width="1069" alt="modal-cancel-chevron" src="https://github.com/VKCOM/VKUI/assets/91548592/ebc9c966-2516-44d8-ac5d-a8be2d6cbc1c">

<img width="575" alt="modal-chevron" src="https://github.com/VKCOM/VKUI/assets/91548592/17781f74-65e7-4a7b-82aa-004dbb769349">

<img width="531" alt="modal-retail" src="https://github.com/VKCOM/VKUI/assets/91548592/23fe3950-8e13-42e9-bc14-304bb36e11c0">

**Comment by mendrew** [comment]
@Zaycevq А в [дизайн-системе](https://www.figma.com/file/2sQl2eaxsp7RDRdMOeneEC/%F0%9F%92%A0-VKUI-Common-Library?type=design&node-id=27067-219932&mode=design&t=aS5tHWkaBrVCV0no-4) же этого ещё нету? А то я не смог найти...

Мы только chevron_left_24 для VKCOM заменяем для `compact`, а для `regular` оставляем `Icon28ChevronLeftOutline`?

**Comment by Zaycevq** [comment]
> @Zaycevq А в [дизайн-системе](https://www.figma.com/file/2sQl2eaxsp7RDRdMOeneEC/%F0%9F%92%A0-VKUI-Common-Library?type=design&node-id=27067-219932&mode=design&t=aS5tHWkaBrVCV0no-4) же этого ещё нету? А то я не смог найти...
> 
> 
> 
> Мы только chevron_left_24 для VKCOM заменяем для `compact`, а для `regular` оставляем `Icon28ChevronLeftOutline`?

Все так, только для vkCom платформы / темы, другие не трогаем

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.1.0" target="_blank">v6.1.0</a> 🎉
