### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Danil-Golubev** [VKCOM/VKUI#6867]
### Описание

Root/Root.tsx

файл не видит Root.module.css

### Версия

last

### Скриншоты

![Снимок экрана 2024-05-01 201305](https://github.com/VKCOM/VKUI/assets/97256920/2b3118dd-81dc-40df-a5fb-f2e809a15041)

**Comment by levtsypanov** [comment]
Создайте в корне вашего проета `types/env.d.ts`

```ts
declare module '*.module.css' {
  const classes: { [key: string]: string };
  export default classes;
}
```

**Comment by inomdzhon** [comment]
- см. https://github.com/VKCOM/VKUI/issues/6867#issuecomment-2088837475
