### ISSUE TITLE
[Feature][Popover]: Возможность установки своего ref извне

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6891]
### Описание

Popover крепится к элементу переданному в `children`, есть потребность его крепить к элементу извне, передавая например реф через `targetRef` проп как у Popper

**Comment by MrZillaGold** [comment]
@inomdzhon привет! А чем заблокированы?

**Comment by inomdzhon** [comment]
> @inomdzhon привет! А чем заблокированы?

Изначально вот этой задаче #7199, а сейчас подготовкой к релизу **v7.0.0**

---

Когда вернёмся к этой задаче, будем рассматривать вариант создания хука `usePopover()`, который будет возвращать события, которые можно будет навесить на целевой элемент и сам Popover

Как пример
```tsx
const { anchor, popover } = usePopover();

<button {...anchor} />
<Popover {...popover} />
```
