### ISSUE TITLE
[Bug]: CalendarRange/DateRangeInput при изменении месяца через дропдаун выбранный месяц появляется не на той же половине где был вызван дропдаун

### ISSUE THREAD

**Issue by mendrew** [VKCOM/VKUI#6897]
### Описание

Если раскрыть календарь `DateRangeInput` и менять месяц через дропдаун в правой половине календаря, то выбраный в дропдауне месяц может появится в левой пловине, хотя ожидается, что где месяц был выбран, там он появится.
То же относится и к `CalendarRange`

### Версия

6.0.2

### Скриншоты

https://github.com/VKCOM/VKUI/assets/5443359/918aef53-d838-47f8-8570-3c5e49e5537f

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.0" target="_blank">v6.2.0</a> 🎉
