### ISSUE TITLE
[Feature][UsersStack]: Возможность обертки аватаров в любой компонент 

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6907]
### Описание

Сейчас сами аватарки в UsersStack нельзя обернуть в свой контент, возникает необходимость навешивания ссылок на каждый отдельный аватар, например для открытия профиля пользователя при клике на аватарку, либо для добавления туллтипа с именем человека при ховере на сам аватар. 

Как вариант, сделать сабкомпонент UsersStack.Avatar/UsersStack.Photo/UsersStack.Item, в который передавать src для самой аватарки, Component для изменения компонента в который оборачиваются сами аватарки, также этот подход позволит оборачивать аватарки в туллтипы. 

### Скриншоты

![Снимок экрана 2024-05-13 в 16 20 34](https://github.com/VKCOM/VKUI/assets/42776347/1b82069e-d90b-44f5-81a6-78f40d2a3b48)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.3.0" target="_blank">v6.3.0</a> 🎉
