### ISSUE TITLE
[Bug]: Открытие панели из модалки с клавиатурой сохраняет неверное положение скролла

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#6909]
### Описание

Окружение: мобильный iOS (браузер, вебвью)

Предусловия: Первая панель с контентом на один вьюпорт или больше. В первой панели можно открыть модалку. В модалке есть Textarea. Из модалки можно попасть на вторую панель. Из второй панели можно вернуться назад на первую.

Демо: https://qswc6m.csb.app/
Исходный код: https://codesandbox.io/p/sandbox/vkui-typescript-qswc6m

Видео: https://github.com/VKCOM/VKUI/assets/22776192/d33435fb-1efc-47bf-9001-8e4aa1900e22

Шаги на видео:
1. Открыть модалку
2. Открыть клавиатуру, сфокусировавшись по Textarea
3. Нажать на кнопку в модалке
4. Вернуться назад

ФР: Прыжок положения скролла первой панели на период анимации перехода между панелями
ОР: Прыжка положения скролла первой панели на период анимации перехода между панелями нет

Примечание: скорее всего есть связь с репортом https://github.com/VKCOM/VKUI/issues/6832

### Версия

6.0.2

### В каких браузерах воспроизводится проблема?

Safari

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.3.0" target="_blank">v6.3.0</a> 🎉
