### ISSUE TITLE
[Bug]: Некорректное поведение Popover при использовании массива значений в trigger

### ISSUE THREAD

**Issue by BlackySoul** [VKCOM/VKUI#6915]
### Описание

Если использовать `trigger=["focus", 'click']`, то первое открытие всплывашки сразу же триггерит её закрытие.

https://github.com/VKCOM/VKUI/assets/7431217/76bed3c0-c59f-490e-985b-353a45eb8419

### Версия

v6

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.1.2" target="_blank">v6.1.2</a> 🎉
