### ISSUE TITLE
[Bug]: В Calendar есть возможность выбрать отрицательные года

### ISSUE THREAD

**Issue by BlackySoul** [VKCOM/VKUI#6921]
### Описание

![image](https://github.com/VKCOM/VKUI/assets/7431217/5e22314e-d5d3-4446-80c1-e9f80d81a30c)

### Версия

v6

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.1.0" target="_blank">v6.1.0</a> 🎉
