### ISSUE TITLE
[Feature][Image]: Сабкомпонент для абсолютного позиционирования элементов поверх изображения

### ISSUE THREAD

**Issue by egorprnn** [VKCOM/VKUI#6924]
### Описание

Есть потребность располагать пользовательские элементы поверх изображения, хочется чтобы были поля top/left/bottom/right, которые бы принимали пользовательское значение этих свойств, также как и в CSS.

Возможно создание такого сабкомпонента закроет и эту проблему:
https://github.com/VKCOM/VKUI/issues/6923

Элементы могут показывать всегда, но также нужно возможность прятать их отображение под hover на саму картинку - пока не навели на любое место Image, не показываем, полезно для кнопок с дополнительными действиями (2 скрин)

### Скриншоты

![Снимок экрана 2024-05-17 в 15 04 09](https://github.com/VKCOM/VKUI/assets/42776347/22e8641b-6c23-4a32-bd5b-96c2c2e8ad74)

![Снимок экрана 2024-05-17 в 17 42 06](https://github.com/VKCOM/VKUI/assets/42776347/884beb99-7494-4380-9e2e-363960244b23)

![Снимок экрана 2024-05-17 в 15 12 23](https://github.com/VKCOM/VKUI/assets/42776347/fc8620cc-0a1b-437d-a614-bfe8293fa3c4)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.1.0" target="_blank">v7.1.0</a> 🎉
