### ISSUE TITLE
feat(Calendar): Ограничивать просмотр месяцев и годов в селектах компонента Calendar.

### ISSUE THREAD

**Issue by mendrew** [VKCOM/VKUI#6936]
### Discussed in https://github.com/VKCOM/VKUI/discussions/6565

<div type='discussions-op-text'>

<sup>Originally posted by **Rezetchik** February 13, 2024</sup>
Добавить свойство, которое бы ограничивало просмотр месяцев и годов, которые не входят в [minDateTime, maxDateTime]. Cейчас, при ограничении, компонент не скрывает лишние года, всё так же в полосе прокрутки остаётся до 1124 года.
![DPNebhlQT1Q](https://github.com/VKCOM/VKUI/assets/146764865/9a6a6340-ae98-4bb0-835f-d0d9c99c928e)
</div>

Вместо свойства просто следует делать опции `disabled` в селектах выбора месяца и года если они ограничены свойствами minDateTime, maxDateTime, disablePast, disableFuture.

**Comment by struchkov** [comment]
Сделал PR по ограничению выбора. Остается открытый вопрос с элементами навигации Tappable - их нужно тоже дизейблить для крайних вариантов выбора. Не уверен, нужно ли исправлять это в рамках данного issue.

**Comment by mendrew** [comment]
> Сделал PR по ограничению выбора. Остается открытый вопрос с элементами навигации Tappable - их нужно тоже дизейблить для крайних вариантов выбора. Не уверен, нужно ли исправлять это в рамках данного issue.

Спасибо за PR! 💯 

Думаю, что лучше исправить это в рамках данного issue, так как элементы навигации входят в компонент `CalendarHeader` и логика будет основана на коде из PR.
Про эти элементы в issue не сказано только потому, что не подумали про них.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.0" target="_blank">v6.2.0</a> 🎉
