### ISSUE TITLE
[Feature]: Заменить цвета шевронов в табах

### ISSUE THREAD

**Issue by qurle** [VKCOM/VKUI#6943]
### Описание

В `mode="default | secondary"` для `state="active"` цвет шеврона заменить на color_icon_primary. 
Во всех модах для `state="inactive | disabled"` цвет шеврона заменить на color_icon_medium.
Цвет шеврона должен совпадать с цветом иконки слева.

[Макет в фигме ↗](https://www.figma.com/design/2sQl2eaxsp7RDRdMOeneEC/💠-VKUI-Common-Library?node-id=25061-207232&t=KYtl7ExlyLWzenNX-11)

### Скриншоты

![image](https://github.com/VKCOM/VKUI/assets/32414396/690a1413-d9b3-4c31-b2fe-0baa2d4c1adb)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.1.0" target="_blank">v6.1.0</a> 🎉
