### ISSUE TITLE
[Bug][Search]: Иконка очистки поля не исчезает, если почистить value вручную

### ISSUE THREAD

**Issue by AnonJedi** [VKCOM/VKUI#6944]
### Описание

Если ввести что-нибудь в инпут, а потом нажать на крестик, то текст почистится и крестик пропадёт. Но если почистить текст через стейт функцию не нажимая на крестик (setValue('')), то крестик остаётся, пока ты не введёшь что-нибудь в инпут и не сотрёшь через крестик или бекспейсом.

### Версия

6.0.3

### Шаги воспроизведения

- ввести текст в поле
- нажать на кнопку `Clear`
- иконка очистки поля не пропадает

### Ожидаемое поведение

- ввести текст в поле
- нажать на кнопку `Clear`
- иконка очистки поля пропадает

### Скриншоты

https://github.com/VKCOM/VKUI/assets/11361726/e33542f5-bbde-4f6b-8a0f-8671b5ad1f59

### Пример с воспроизведением

https://codesandbox.io/p/sandbox/strange-sea-nzvqzx?file=%2Fsrc%2FApp.js%3A6%2C48

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.1.0" target="_blank">v6.1.0</a> 🎉
