### ISSUE TITLE
[Feature]: Сделать тип mode у Badge необязательным

### ISSUE THREAD

**Issue by Pavel1711** [VKCOM/VKUI#6946]
### Описание

https://github.com/VKCOM/VKUI/blob/master/packages/vkui/src/components/Badge/Badge.tsx#L12
Поле обязательное, при том, что есть дефолтное значение

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.1.0" target="_blank">v6.1.0</a> 🎉
