### ISSUE TITLE
[Doc]: Ссылки из ModalPageHeader указывают на отсутствующие страницы

### ISSUE THREAD

**Issue by Pavel1711** [VKCOM/VKUI#6949]
### Описание

https://vkcom.github.io/VKUI/#/ModalPageHeader
При переходе на PanelHeaderClose, PanelHeaderSubmit 404 ошибка

**Comment by Pavel1711** [comment]
Может поправим немного текст в доке? 
А то указывается PanelHeaderClose, переход на PanelHeaderButton. Потом 3 раза указывается переход на PanelHeaderButton, перечисленный через "или". Например, закончить на ` Это может быть [`PanelHeaderButton`](#!/PanelHeaderButton) с иконкой `<Icon24Dismiss />``

**Comment by inomdzhon** [comment]
> Может поправим немного текст в доке? А то указывается PanelHeaderClose, переход на PanelHeaderButton. Потом 3 раза указывается переход на PanelHeaderButton, перечисленный через "или". Например, закончить на ` Это может быть [`PanelHeaderButton`](#!/PanelHeaderButton) с иконкой <Icon24Dismiss />`

теперь это тема отдельного issue 😢
