### ISSUE TITLE
Select ломается при передаче `undefined` в `value`

### ISSUE THREAD

**Issue by GeorgeBekh** [VKCOM/VKUI#695]
Если передать однажды в Select в проп value значение `undefined`, компонент ломается и больше не реагирует на проп value, даже когда начинаешь передавать туда нормальные значения.

### Workaround

Передавать пустую строку вместо undefined

E.g.
```jsx
//...
<Select  value={this.state.value || ""}
//...
```

**Comment by GeorgeBekh** [comment]
Пример бага: https://codesandbox.io/s/vkui-boilerplate-u26n6?file=/src/index.js

**Comment by ArthurStam** [comment]
Поправлено в v4
