### ISSUE TITLE
[Feature][ScreenSpinner]: Поддержать overlay режим 

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#6952]
### Описание

На макетах отрисовали overlay режим отображения компонента, нужно поддержать в коде

### Скриншоты

![Снимок экрана 2024-05-24 в 13 53 49](https://github.com/VKCOM/VKUI/assets/42776347/f2d52599-e852-4b99-a068-49c4005c160b)

**Comment by BlackySoul** [comment]
Ждем @VKCOM/vkui-design

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.6.0" target="_blank">v6.6.0</a> 🎉
