### ISSUE TITLE
[Feature]: Цвет Background Modal → Background Contrast Themed в немодалках

### ISSUE THREAD

**Issue by qurle** [VKCOM/VKUI#6956]
### Описание

Цвет Modal у нас используется не только для модалки, и мы сталкиваемся с проблемой: компоненты с модальным цветом теряются, когда расположены в модальном окне. 

<img width="383" alt="image" src="https://github.com/VKCOM/VKUI/assets/32414396/7d38665b-6f6b-4063-975e-24f9f9b9da99">

Компонентам, которые могут отображаться на модалке, присвоим цвет `color_background_contrast_themed`. Когда будет готово, токен модалки затемним в [vkui-tokens](https://github.com/VKCOM/vkui-tokens), чтобы улучшить контрастность.

В модалках будет так:
![image](https://github.com/VKCOM/VKUI/assets/32414396/9c62098f-97d6-410d-a7e6-f4bfecddb7fe)

На Background Content — так:
![image](https://github.com/VKCOM/VKUI/assets/32414396/839b189d-9897-4d00-989c-610cff29ac8d)

Элементы, которые точно нужно заменить (могут быть на модалке и без оверлея):
`Calendar`, `Card`, `Dropdown`, `Popover`, `ScreenSpinner`, `SubnavigationButton`, `TabsItem` (активный акцентный таб), `Tooltip`, `WriteBar` (андроид)
Элементы, которые точно не нужно заменять:
`ModalCardBase`, `ModalPage`
Насчёт всех остальных готов обсудить.

**UPD**

Точный список компонентов:

- `Card`
- `Calendar`
- `CalendarRange`
- `CustomSelectDropdown`
- `Popover`
- `ScreenSpinner`
- `ScrollArrow`
- `SubnavigationButton`
- `TabsItem`
- `TooltipBase`
- `WriteBar`

**Comment by qurle** [comment]
По цвету изменение очень минорное, но нам нужно отвязать компоненты от токена `colorBackgroundModal`, чтобы потом его изменить.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.0" target="_blank">v6.2.0</a> 🎉

**Comment by qurle** [comment]
Йоо, давайте ещё в Contrast Themed переведём фоны компонентов `Alert`, `Action Sheet` и `Snackbar`.

**Comment by inomdzhon** [comment]
> Йоо, давайте ещё в Contrast Themed переведём фоны компонентов `Alert`, `Action Sheet` и `Snackbar`.

Йо! Создай отдельное issue плиз – это уже привязано к **v6.2.0**
