### ISSUE TITLE
[Bug]: FocusTrap не корректно работает, если изменяются интерактивные элементы

### ISSUE THREAD

**Issue by Semigradsky** [VKCOM/VKUI#6965]
### Описание

Сейчас в FocusTrap если children не меняется, то может и не происходить перерасчёт `focusableNodesRef.current`.

https://github.com/VKCOM/VKUI/blob/842d8076e17ba1121ab2a2b948d8d06d129fef4d/packages/vkui/src/components/FocusTrap/FocusTrap.tsx#L65

Это приводит к тому, что `focusableNodesRef.current` перестаёт совпадать с реальными интерактивными элементами и клавиатурная навигация работает неверно.

Например, такое происходит в модалке, если мы динамически добавляем/удаляем инпуты.

### Версия

6.x

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.1.2" target="_blank">v6.1.2</a> 🎉
