### ISSUE TITLE
FixedLayout с кнопкой внутри наезжает на длинный раскрытый PanelHeaderContext

### ISSUE THREAD

**Issue by VadimTVJ** [VKCOM/VKUI#697]
FixedLayout с кнопкой внутри наезжает на длинный раскрытый PanelHeaderContext

https://i.imgur.com/bRkaI8B.png

**Comment by ArthurStam** [comment]
Привет. Можно пример с кодом, где воспроизводится проблема? Вот отсюда можно сделать форк: https://codesandbox.io/s/vkui-boilerplate-oj149

**Comment by ArthurStam** [comment]
Закрываю за отсутствием активности
