### ISSUE TITLE
[Bug]: Проблемы с рендером сепаратора на DPR 3 устройствах

### ISSUE THREAD

**Issue by 7lexik0n** [VKCOM/VKUI#6977]
### Описание

Принесли баг, что на некоторых устройствах iOS на странице [m.vk.com/services](https://m.vk.com/services) не отображается сепаратор между секциями. Проверил и обнаружил, что есть разница в отображении этого сепаратора на устройствах с разной плотностью пикселей: при DPR 2 все ок, а при DPR 3 сепаратор бывает не видно (толщина сепаратора при этом 0.5 пкс и 0.33 пкс соответственно). Приложил скрины для iPhone 15 (DPR 3) и iPhone SE 3 gen (DPR 2)

### Версия

5.10.1

### В каких браузерах воспроизводится проблема?

Safari

### Шаги воспроизведения

Открыть m.vk.com/services на устройствах с  DPR 3 (например, iPhone 15)
Сепаратор отрисовывается компонентом Group

### Ожидаемое поведение

Сепаратор отображается корректно

### Скриншоты

![iPhone_15_screen](https://github.com/VKCOM/VKUI/assets/36222378/674744b4-631d-40ca-a273-80c0dd092bae)
![iPhone_15_separator](https://github.com/VKCOM/VKUI/assets/36222378/27418e88-9499-48fe-b4d9-8047a225efa9)
![iPhone_15_separator_height](https://github.com/VKCOM/VKUI/assets/36222378/56495746-7a56-4fa5-bff4-aa24e11ecf19)
![iPhone_SE_screen](https://github.com/VKCOM/VKUI/assets/36222378/f17d0404-33ef-43db-b308-df17e6b3130f)
![iPhone_SE_separator](https://github.com/VKCOM/VKUI/assets/36222378/67601e35-34c3-4a89-8913-a0e5a085174e)
![iPhone_SE_separator_height](https://github.com/VKCOM/VKUI/assets/36222378/0a3edfae-ebb4-44b4-9344-21f5472aba61)
![kEs17-VW6bU](https://github.com/VKCOM/VKUI/assets/36222378/01e8076a-93e1-483d-8aec-26791b0c89b6)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.2" target="_blank">v7.0.0-beta.2</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
