### ISSUE TITLE
[Предложение] Отключать в SimpleCell (text-overflow) при использовании multiline

### ISSUE THREAD

**Issue by AdvTechnoKing** [VKCOM/VKUI#698]
При определённых размерах точки заменяют мелкие слова или предлоги.

Ширина: 320
Иконка слева: 44
Иконка справа: 28

Ширина оставшейся области составила: 188
Текст для повтора: Откройте уведомление, что **бы** получить бонус!

![1](https://user-images.githubusercontent.com/17812651/81471032-0381a880-91f7-11ea-884c-dfcb8ff9880d.JPG)

![2](https://user-images.githubusercontent.com/17812651/81471033-04b2d580-91f7-11ea-9dfd-0b33217271b2.JPG)

**Comment by ArthurStam** [comment]
Спасибо, поправим
