### ISSUE TITLE
[Предложение] Добавить в документацию название классов

### ISSUE THREAD

**Issue by AdvTechnoKing** [VKCOM/VKUI#699]
Есть некоторые труднодоступные компоненты, на которые можно повлиять через его внутренний класс. 

Хотелось бы видеть список этих классов и их примерное расположение, на сколько глубоко уходят элементы, что отвечает за тот или иной блок и т.д.

**Comment by ArthurStam** [comment]
Привет, в react-бибиотеке публичным API является компонент и его свойства. Стилизация компонента — это инкапсулированная логика, которая может меняться и меняется в процессе развития библиотеки. Поэтому завязываться на css-классы — плохой подход, который мы не поощраем.
