### ISSUE TITLE
[Feature]: Коллбек onCancel у компонента Search

### ISSUE THREAD

**Issue by ramilashrafulin** [VKCOM/VKUI#6992]
### Описание

Хотелось бы иметь возможность передать коллбек onCancel (при очистке значения value у input) в компонент Search

**Comment by mendrew** [comment]
@ramilashrafulin Привет, подскажи, пожалуйста, а почему `onChange` для этого не хватает?

**Comment by mendrew** [comment]
Пообщались лично и пришли к выводу, что что `onChange` было достаточно для задачи.
