### ISSUE TITLE
Отсутствует background в PanelHeader на IOS 13

### ISSUE THREAD

**Issue by PavelMartinez** [VKCOM/VKUI#700]
IOS 13, при скролле панели PanelHeader прозрачный
![image](https://user-images.githubusercontent.com/44809625/81742136-4a49f980-94a8-11ea-82d4-468d613c6c3d.png)

**Comment by fedorov-xyz** [comment]
Приложите пример кода, пожалуйста.

**Comment by PavelMartinez** [comment]
`            <PanelHeader separator={false} left={<PanelHeaderBack onClick={() => {clearInterval(intervals); window.history.back();}}/>}  style={{paddingTop: "var(--safe-area-inset-top)", background: "var(--background_content)"}}>
                <PanelHeaderContent style={{paddingTop: "var(--safe-area-inset-top)", background: "var(--background_content)"}} before={<img src="https://i.imgur.com/CEWwHCh.png" className="logo"/>} status={lastUpdated ? "Данные обновлены: " + lastUpdated : "Обновление..."}>
                    {profile ? `Профиль ${profile.player.p_name}` : "Player" }
                </PanelHeaderContent>
            </PanelHeader>`

Пытался исправить стилями, результата не принесло

**Comment by sozonovalexey** [comment]
Аналогично. Пробовал поставить разные версии - не помогло. IphoneX

**Comment by ArthurStam** [comment]
Привет. Лучше пример приложить тут с воспроизведением бага.
https://codesandbox.io/s/vkui-boilerplate-oj149

**Comment by sozonovalexey** [comment]
> Привет. Лучше пример приложить тут с воспроизведением бага.
> https://codesandbox.io/s/vkui-boilerplate-oj149

Обновился до 3.10 + убрал в своих стилях `box-sizing: border-box;` и все заработало.

**Comment by ArthurStam** [comment]
Отлично)
