### ISSUE TITLE
[Bug]: Popover возвращает позицию скролла при закрытии

### ISSUE THREAD

**Issue by Pavel1711** [VKCOM/VKUI#7007]
### Описание

Закрытие Popover'а возвращает позицию скролла на место Popover'а, несмотря на то, что пользователь мог проскроллить компонент

### Версия

6.1.0

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

```
import { Button, Popover } from '@vkontakte/vkui';

const PopoverWithTriggerClick = () => {
  return (
    <Popover
      noStyling
      trigger="click"
      id="menupopup"
      role="menu"
      aria-labelledby="menubutton"
      content={() => (
        <div
          style={{
            width: '200px',
            height: '100px',
            backgroundColor: '#e3e3e3',
            borderRadius: '12px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          Text
        </div>
      )}
    >
      <Button
        id="menubutton"
        aria-controls="menupopup"
        aria-haspopup="true"
        mode="outline"
      >
        Нажми на меня
      </Button>
    </Popover>
  );
};

const Test = () => {
  return (
    <>
      <div style={{ height: '100vh' }}>
        <PopoverWithTriggerClick />
      </div>
      <div style={{ height: '100vh' }}></div>
    </>
  );
};

export default Test;
```

Открыть Popover, пролистнуть вниз и нажать на свободную область. Скролл вернется на место вызова Popover'а

### Ожидаемое поведение

Скролл остаётся без изменений

### Пример с воспроизведением

https://codesandbox.io/p/sandbox/popover-forked-gr97cw?file=%2Fsrc%2FApp.js

**Comment by BlackySoul** [comment]
Привет! Возможно, стоит воспользоваться [пропом](https://vk.cc/cxA6FN) `restoreFocus={false}` (по умолчанию он в `true`), если такая функциональность не нужна.
