### ISSUE TITLE
[Feature][ScreenSpinner]: Разбить компонент на сабкомпоненты

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#7013]
### Описание

Хотим показывать ScreenSpinner, но при этом не зависеть от логики PopoutWrapper, который используется внутри и не учитывает предыдущее значение body стилей при применении своих.
По аналогии с Placeholder.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.4.0" target="_blank">v6.4.0</a> 🎉
