### ISSUE TITLE
[Bug][ModalDismissButton]: Отсутствует анимация между active и hover состояниями

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#7017]
### Описание

У ModalDismissButton отвалилась анимация переходов в/между active и hover состоянием, сейчас на рутовом классе компонента висит transition с opacity, но кажется это просто легаси от 4 версии VKUI 

related #7016

### Версия

5.0.0-6.0.0

### В каких браузерах воспроизводится проблема?

Chrome

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.1" target="_blank">v6.2.1</a> 🎉
