### ISSUE TITLE
[Bug]: Insets не работают с Tailwind

### ISSUE THREAD

**Issue by VladislavZakrevskiy** [VKCOM/VKUI#7018]
### Описание

--vkui_internal--safe_area_inset_top (и другие key) не работают с tailwind (непонятно почему- ????) 

на фото видно, где с tailwind (то есть полетело) и где без: 
![image](https://github.com/VKCOM/VKUI/assets/95054019/17bc4cc6-7bfb-4d48-9708-9086de927727)
![image](https://github.com/VKCOM/VKUI/assets/95054019/b73cf6be-8f63-46f3-983d-b34df25eae26)

### Версия

сейчас на 6.0.2

### В каких браузерах воспроизводится проблема?

Yandex Browser

### Шаги воспроизведения

1. Поставить vk-create-mini-app (все библиотеки)
2. Поставить Tailwind по методичке с их сайта (в конфиге только поле content заполнено, тоже стандартно)
3. Посмотреть, что PanelHeader улетел

### Ожидаемое поведение

1. Поставить vk-create-mini-app (все библиотеки)
2. Поставить Tailwind по методичке с их сайта (в конфиге только поле content заполнено, тоже стандартно)
3. Посмотреть, что PanelHeader НЕ улетел

**Comment by VladislavZakrevskiy** [comment]
мужики, баш решил сам, не знаю, как сделать это из конфига, но вот мое решение: 
1. я так понял, что в VKUI все компоненты не box-sizing: border-box, поэтому ломается padding-top с инсет top - tailwind делает все html-элементы через * box-sizing: border-box

2. чтобы решить, сначала компилируем tailwind стили в css стили через 
```bash
yarn tailwindcss -i ./src/index.css -o ./src/output.css
```

3. в файлике output.css комментите box-sizing
![image](https://github.com/VKCOM/VKUI/assets/95054019/ebdf6e7e-4bde-4437-8e6a-ebae439932cc)
(у меня проблема была в ::before, поэтому я и его комментил, для надежности ::after тоже)

4. Готово! только не забывайте проделывать эти шаги перед каждой компиляцией, иначе все снова улетит
P.S.: буду рад, если предложите нормальное решение, а не костыль, потому что ну это какая-то чушь, зато работает

**Comment by inomdzhon** [comment]
Клёво, что смог починить 👍 

Вот тут предлагается более элегантное решение:

- https://github.com/tailwindlabs/tailwindcss/discussions/2994
- https://stackoverflow.com/a/73792390/2903061 (более подробный пример)
 
Есть нюанс, что `@layer` не поддерживается в старых браузерах.

---

А с `box-sizing: border-box` действительно есть проблемка, но в конкретном компоненте (см. #5054).

**Comment by ankittchaurasia** [comment]
Try this in your css file

```css
 *, ::before, ::after {
    box-sizing:  content-box;
 }
 ```
  
  You can wrap this in your @layer base if you want
