### ISSUE TITLE
[Feature]: Поменять цвет Show More внутри Horizontal Scroll

### ISSUE THREAD

**Issue by Zaycevq** [VKCOM/VKUI#7030]
### Описание

Обновляем цвета в Show More, текущий Accent отвлекает и есть большой запрос от команд изменить эти цвета. Меняем на Icon Secondary и Text Secondary.

Дизайн:
https://vk.cc/cxJCUY

![image](https://github.com/VKCOM/VKUI/assets/91548592/a0429c39-896c-4bd0-844d-563ea4a5d71b)
![image](https://github.com/VKCOM/VKUI/assets/91548592/84a3c97e-cc70-4b34-b23e-87b5c2db58d7)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.0" target="_blank">v6.2.0</a> 🎉
