### ISSUE TITLE
[Bug][ChipsSelect]: Не открывается список опций по клику на иконку со стрелкой ChipsSelect

### ISSUE THREAD

**Issue by DKotov99** [VKCOM/VKUI#7031]
### Описание

В версиях библиотеки ниже 6-ой была возможность открыть список опций, сделав клик по иконке. 

На данный момент, если в поле довольно много выбрано опций, то открыть список опций затруднительно. Для этого нужно попасть в пространство между последним элементом и иконкой (т.к. она не кликабельна).

Однако, если поле пустое, то, по клику на иконку, меню опций вызывается как ожидалось.

### Версия

6+

### В каких браузерах воспроизводится проблема?

Chrome

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.2" target="_blank">v6.2.2</a> 🎉
