### ISSUE TITLE
[Feature][HorizontalCellShowMore]: Поддержать смену режимов отображения компонента 

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#7036]
### Описание

На макетах добавили режим отображения компонента в secondary цветах, нужно поддержать в компоненте

### Скриншоты

![Снимок экрана 2024-06-20 в 14 47 34](https://github.com/VKCOM/VKUI/assets/42776347/8be03916-2b4b-4487-8336-cecc4f91e742)

**Comment by inomdzhon** [comment]
Duplicate of #7030
