### ISSUE TITLE
[Bug]: CustomScrollView следит только за резайзом window, но не блоком где юзается

### ISSUE THREAD

**Issue by daniil-kaverzin** [VKCOM/VKUI#7043]
### Описание

CustomScrollView следит только за резайзом window, но не блоком где юзается

### Версия

6.1.1

### В каких браузерах воспроизводится проблема?

Firefox, Chrome, Safari, Microsoft Edge, Yandex Browser

### Шаги воспроизведения

Делаем внутри CustomScrollView появление какого-то контента, который не вызывает ререндер всего CustomScrollView, дергалка скролла справа себя не апдейтит на ресайз

### Ожидаемое поведение

Вызывается перерасчет всех штуковин внутри CustomScrollView на ресайз блока

### Скриншоты

![image](https://github.com/VKCOM/VKUI/assets/55830579/c8d57646-c354-4de6-bfbd-b715968e73d6)

### Пример с воспроизведением

[https://codesandbox.io/p/sandbox/objective-hermann-537g7j?file=/src/App.tsx](https://codesandbox.io/p/sandbox/objective-hermann-537g7j?file=%2Fsrc%2FApp.tsx)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.1.2" target="_blank">v6.1.2</a> 🎉
