### ISSUE TITLE
[Bug]: Фиксированная высота контента в аккардеоне мешает отображению контента

### ISSUE THREAD

**Issue by fedoseevGIT** [VKCOM/VKUI#7045]
### Описание

В https://github.com/VKCOM/VKUI/blob/master/packages/vkui/src/components/Accordion/AccordionContent.tsx#L51 хардкодится значение max-height для контента аккардеона. Из-за этого, при увеличении высоты контента, содержимое не отображается до ресайза страницы

### Версия

latest

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

https://codesandbox.io/p/sandbox/great-pine-qpxgvl?file=%2Fsrc%2FApp.js%3A5%2C10

1. Открыть sandbox
2. Развернуть аккардион
3. Нажать на кнопку

Контент не убирается

### Ожидаемое поведение

Контент не должен обрезаться

### Скриншоты

Изначальный вид:
![image](https://github.com/VKCOM/VKUI/assets/64091259/edad8acf-6692-4410-a091-6b07ff1898db)

После нажатия на кнопку:
![image](https://github.com/VKCOM/VKUI/assets/64091259/49664909-8f94-4663-834a-5477d0dc9bcc)

После ресайза:
![image](https://github.com/VKCOM/VKUI/assets/64091259/f4278584-bc82-4f61-9555-181e77278e2e)

### Пример с воспроизведением

https://codesandbox.io/p/sandbox/great-pine-qpxgvl?file=%2Fsrc%2FApp.js%3A5%2C10

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.0" target="_blank">v6.2.0</a> 🎉
