### ISSUE TITLE
[Doc]: Сломана навигация из styleguide -> storybook

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#7047]
### Описание

> При переходе с https://vkcom.github.io/VKUI/#/DropZone в Storybook ссылка https://vkcom.github.io/VKUI/playground/?path=/story/forms-dropzone, если использовать навигацию в Storybook, то https://vkcom.github.io/VKUI/playground/?path=/story/blocks-dropzone--playground

Навигация сломана не только в DropZone

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.2" target="_blank">v6.2.2</a> 🎉
