### ISSUE TITLE
[Feature]: Добавить в компонент EllipsisText возможность многоточия не только для первой строки

### ISSUE THREAD

**Issue by Pavel1711** [VKCOM/VKUI#7061]
### Описание

Сейчас многоточие проставляется только для первой строки. Было бы удобно, если бы можно было выставлять кол-во строк, после которых проставляется многоточие

Наш кейс
<img width="289" alt="Снимок экрана 2024-06-24 в 11 51 36" src="https://github.com/VKCOM/VKUI/assets/45904265/1ee56c3a-4e8b-4edb-a7c3-1290f706029f">

**Comment by mendrew** [comment]
Спасибо за идею. Уверен, что это реально было бы полезно.

Хочется остаться на сугубо css решении и не городить js для этого.
А значит, что остаётся только `line-clamp` решение, которое ещё не поддерживается во всех браузерах на которые мы смотрим.
https://github.com/VKCOM/VKUI/blob/master/.browserslistrc

Возможно, было бы здорово, добавить это с оговоркой, что работает на технологии line-clamp и не везде поддерживается, используйте с умом. Мы где-то так уже делали.
Ага, в `Tabs` со `scrollIntoView` и `scrollBehavior` https://github.com/VKCOM/VKUI/pull/5957.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.3.0" target="_blank">v6.3.0</a> 🎉
