### ISSUE TITLE
[Bug]: Select — нет переноса у неразрывной строки

### ISSUE THREAD

**Issue by asssc** [VKCOM/VKUI#7062]
### Описание

Не переносится неразрывная строка в Select'e

<img width="1011" alt="image" src="https://github.com/VKCOM/VKUI/assets/13476320/2f78e566-e19b-4c1b-b936-8df643bda973">

### Версия

6.1.1

### В каких браузерах воспроизводится проблема?

Chrome

### Пример с воспроизведением

https://codesandbox.io/p/sandbox/wizardly-leakey-cjldfk?file=%2Fsrc%2FApp.js%3A10%2C32

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.1" target="_blank">v6.2.1</a> 🎉
