### ISSUE TITLE
[Bug]: Компоненты из Typography используют только системную тему

### ISSUE THREAD

**Issue by Pavel1711** [VKCOM/VKUI#7072]
### Описание

Если нужно перекрыть системную тему компонентом AppearanceProvider, то это никак не влияет на компоненты из Typography.

### Версия

6.1.1

### Ожидаемое поведение

Должно выглядеть так, если системная тема светлая и `<AppearanceProvider value="dark">`
<img width="292" alt="Снимок экрана 2024-06-25 в 15 44 20" src="https://github.com/VKCOM/VKUI/assets/45904265/f097456d-3042-4b44-91b6-33ab2972b811">

### Скриншоты

<img width="295" alt="Снимок экрана 2024-06-25 в 15 43 41" src="https://github.com/VKCOM/VKUI/assets/45904265/3ad565f0-9056-4e08-8209-f8767cab7054">

### Пример с воспроизведением

https://codesandbox.io/p/sandbox/typography-r9hv9s?file=%2Fsrc%2FApp.js%3A17%2C17

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.1" target="_blank">v6.2.1</a> 🎉
