### ISSUE TITLE
[Bug]: Link в Safari внутри текста с переполнением выглядывает наружу, хотя должен исчезать вместе с текстом

### ISSUE THREAD

**Issue by mendrew** [VKCOM/VKUI#7086]
### Описание

Если поместить Link в конец текста с переполнением где у контейнера такие стили
```css
display: -webkit-box;
-webkit-line-clamp: 3;
-webkit-box-orient: vertical;
overflow: hidden;
```

То текст рендерится как надо с многоточием, но в конце выглядывает полный путь ссылки.
<img width="478" alt="Screenshot 2024-06-26 at 17 28 50" src="https://github.com/VKCOM/VKUI/assets/5443359/614b84ec-a19d-44a2-b6f5-ae4c64823180">

Связано это с тем, что Link внутри это Tappable, у которого есть специльный слой для ripple-эффекта (эффект раскодящихся от клика волн) 
https://github.com/VKCOM/VKUI/blob/af6b0b0cda6a50667323f7a905eee5c12933777a/packages/vkui/src/components/Tappable/Tappable.tsx#L75
https://github.com/VKCOM/VKUI/blob/af6b0b0cda6a50667323f7a905eee5c12933777a/packages/vkui/src/components/Tappable/Ripple.tsx#L98-L103

Вот эта часть Tappable и не даёт скрыть ссылку.

### Версия

v6.1.0

### Ожидаемое поведение

Ссылка должна скрываться за многоточием так же как и текст.

### Пример с воспроизведением

https://xj4kwv.csb.app

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.0" target="_blank">v6.2.0</a> 🎉
