### ISSUE TITLE
Pull requests and 3rd party libraries

### ISSUE THREAD

**Issue by roman-rr** [VKCOM/VKUI#709]
I'm about create pull request with my [drawer component](https://github.com/roman-rr/cupertino-pane). The idea is to replace current modal which has not fully functionality. 

So, i have few questions: 
1. Does 3rd party dependencies allowed in pull requests ? 
2. May i improve current modal functionality and replace it with 3-step drawer ? 
3. Why repo still doesn't switch to international community with English as common language ?

**Comment by ArthurStam** [comment]
Hi, Roman!

1. No, we are trying solve our problems without 3rd party.
2. Right now we are working on 4 version of our library. I am afraid that your fixes can cause conflicts. I would recommend you to wait until stable version 4.
3. Because it is simpler for us) most of our community speak russian
