### ISSUE TITLE
[Bug]: Ломается анимация открытия/закрытия модалок

### ISSUE THREAD

**Issue by danillas** [VKCOM/VKUI#7095]
### Описание

Если контент модалки ререндерится в процессе её открытия, анимация отображается некорректно.

В приложенном codesandbox отражены три варианта:

1. В модалке имеется компонент Select. Окно отрывается на большую высоту, чем высота контена. Анимация начинается и заканчивается примерно в середине экрана. 

2. В модалке неизменяемый контент. Анимация корректная, высота открытия корректная

3. В модалке есть изменяющийся в процессе открытия контент. Анимация начинается с середины. Через раз происходит скачок в конечной фазе. 

### Версия

6.1.2

### В каких браузерах воспроизводится проблема?

Chrome, Safari. Мобильные устройства

### Шаги воспроизведения

Предусловия:
В модальном окне есть контент, который ререндерится в процессе открытия

1. Открыть модалку
2. Закрыть модалку

https://github.com/VKCOM/VKUI/assets/26124760/49ed29b0-97c4-4d66-8eb4-6d7f1741b475

### Ожидаемое поведение

Анимация корректная, начинается с низу

### Пример с воспроизведением

https://codesandbox.io/p/sandbox/frosty-cookies-5qqgr9?file=/src/App.js:142,1

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.2" target="_blank">v6.2.2</a> 🎉
