### ISSUE TITLE
Зависает интерфейс при быстрой смене view в root

### ISSUE THREAD

**Issue by serginij** [VKCOM/VKUI#710]
Например, баг появляется в сервисе - https://vk.com/app7363698
1) открыть дропдаун
2) выбрать" история транзакций"
3) перейти в " мои адреса"
4) быстро дважды нажать системную кнопку назад
Приложение полностью зависает
Скорее проблема в том, что компонент Root просто не успевает поставить activeView 
Нечто похожее описано в #482 #177 

Если переходить назад с промежутком во времени, то все работает нормально 
Прикрепляю [видео](https://jmp.sh/POdFvEv), в котором можно наблюдать описанный баг.

![image](https://user-images.githubusercontent.com/24574620/81985600-279e1900-963f-11ea-8c98-2984ff212e71.png)

**Comment by k0t3n** [comment]
https://vk.com/bug226764
https://vk.com/bug227546
https://vk.com/bug227545

**Comment by ArthurStam** [comment]
Привет. Спасибо, поправим.

**Comment by ArthurStam** [comment]
Нашел дубликат задачи: #177. Эту закрываю.
