### ISSUE TITLE
Улучшить Tabbaritem

### ISSUE THREAD

**Issue by paveleremin** [VKCOM/VKUI#711]
Возможно ли расширить компонент, чтобы его можно было использовать таким образом:
```javascript
<TabbarItem
            Component={Link}
            to={userItemsRoute.pathname}
            selected={activeView === userRoute.pathname}
        >
```
Проблема в том, что сейчас Component зашит внутри как div

**Comment by ArthurStam** [comment]
Привет. Звучит, как классная доработка) Нет желания заслать PR?
