### ISSUE TITLE
[Feature][Checkbox]: Возможность перекрасить компонент в любой цвет

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#7114]
### Описание

Обсудили что сделаете сабкомпонент от Checkbox, который будет работать также как и Switch, в таком случае на него можно будет вешать className и style, если компонент будет необходимо перекрасить

### Скриншоты

![image](https://github.com/VKCOM/VKUI/assets/42776347/481770f2-8990-4c63-9aae-69b4e54cea99)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.5.0" target="_blank">v6.5.0</a> 🎉
