### ISSUE TITLE
Модальное окно перекрывается FixedLayout'ом и инпутами

### ISSUE THREAD

**Issue by GeorgeBekh** [VKCOM/VKUI#712]
Пример https://codesandbox.io/s/vkui-boilerplate-kc3wi?file=/src/index.js

**Comment by fedorov-xyz** [comment]
Неверная структура.
`ModalRoot` должен передаваться в качестве свойства `modal` у `Root` или `View`.

Если в примере сделать так, то проблемы нет.

Передавать в `ModalRoot` `onClose` в данном случае необязательно, потому что `onClose` уже передан в `ModalRoot`.

![image](https://user-images.githubusercontent.com/25563268/82210375-a6cd6e80-9917-11ea-959c-b954ebd5d408.png)
