### ISSUE TITLE
[Bug]: При смахивании снекбара вниз, скроллится вся страница

### ISSUE THREAD

**Issue by danillas** [VKCOM/VKUI#7121]
### Описание

На странице имеется открытый снекбар. Наличие скролла контента - не имеет значения

### Версия

6.1.1

### В каких браузерах воспроизводится проблема?

Chrome, Safari

### Шаги воспроизведения

1. Открыть снекбар
2. Попытаться смахнуть вниз
3. Скроллится вся страница

### Ожидаемое поведение

Смахивание снекбара вниз тригерит скролл всей страницы, 
При открытом снекбаре скролл страницы не блокируется

### Скриншоты

https://github.com/VKCOM/VKUI/assets/26124760/a29e18f1-b8f4-4c3f-86a4-54d101345009

### Пример с воспроизведением

[https://codesandbox.io/p/sandbox/morning-hill-nygz7s?file=/src/App.js](https://vk.com/away.php?to=https%3A%2F%2Fcodesandbox.io%2Fp%2Fsandbox%2Fmorning-hill-nygz7s%3Ffile%3D%252Fsrc%252FApp.js&cc_key=)

**Comment by SevereCloud** [comment]
На Андроиде также может конфликтовать

https://github.com/VKCOM/VKUI/assets/14944123/dcf499a1-8c20-4db9-b43e-15447721a8b0

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.2" target="_blank">v6.2.2</a> 🎉
