### ISSUE TITLE
[Bug]: WriteBar на Android в GoogleKeyboard вызывает кнопку с предложением ввести пароль

### ISSUE THREAD

**Issue by white-tracer** [VKCOM/VKUI#7127]
### Описание

Если с андроид устройства зайти в miniapp с функциональностью мессенджера (например https://vk.com/app8039101_29560323 или https://vk.com/app7058363) из супераппа VK и тапнуть в поле ввода текста - периодически отображается кнопка с предложкой ввода паролей.

### Версия

6.0.3

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

1. Авторизоваться в VK App на платформе андроид (в качестве клавиатуры используется Google Keyboard)
2. Открыть миниапп с функциональностью мессенджера (например https://vk.com/app8039101_29560323 или https://vk.com/app7058363) 
3. Открыть в миниаппе диалог и тапнуть на поле ввода текста
4. Проверить поведение клавиатуры устройства

Результат: в поле ввода отображается кнопка "Пароли", ведущая в соответствующую функциональность

### Ожидаемое поведение

Кнопка "Пароли" не отображается.

### Скриншоты

![screen_2](https://github.com/VKCOM/VKUI/assets/24522184/1acd3401-00e1-43c0-841c-ad4630eb5576)

**Comment by SevereCloud** [comment]
Привет, Не воспроизводится ![Screenshot_20240704-181756.png](https://github.com/VKCOM/VKUI/assets/14944123/ad2429e2-a05d-405b-8b1e-7b996f4242f2)

**Comment by vkcom-publisher** [comment]
Задача закрыта из-за отсутствия активности в течение последних 14 дней. Если это произошло по ошибке или проблема все ещё актуальна, откройте задачу повторно.
