### ISSUE TITLE
[Bug]: Tooltip перекрывается табами

### ISSUE THREAD

**Issue by svyatoslavpavlov** [VKCOM/VKUI#7133]
### Описание

<img width="354" alt="image" src="https://github.com/VKCOM/VKUI/assets/7815563/39974b75-641c-49c6-88a2-99f9620c3ed0">
<img width="349" alt="image" src="https://github.com/VKCOM/VKUI/assets/7815563/6b0bbdc7-7469-4e4a-adfc-ae53476a9ce7">

### Версия

6.2.0

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

Расположить на странице Tooltip и разные виды табов (селектор, влкадки)

**Comment by SevereCloud** [comment]
Не воспроизводится. Нужен пример с воспроизведением <img width="416" alt="image" src="https://github.com/VKCOM/VKUI/assets/14944123/1f51514c-9387-46f1-accc-dbf2f9a52528">

**Comment by svyatoslavpavlov** [comment]
```
  const widgetText = <>Отображается только при наличии<br/>в афише минимум трех мероприятий<br/>в афише минимум трех мероприятий</>;
  const widgetTooltip = <Tooltip
    placement="top" text={widgetText}>
    <Icon20HelpOutline fill={"var(--vkui--color_icon_secondary)"}/>
  </Tooltip>;
...
 <Div>
           <ContentCard
             mode={ "outline"}
             text={widgetTooltip}
             caption={ "Выбран"}
           />

           <SegmentedControl
             options={[
               {
                 'label': "dfdf",
                 'value': 'list',
                 'aria-label': 'Список',
               },
               {
                 'label': "dfdf",
                 'value': 'grid',
                 'aria-label': 'Плитки',
               },
             ]}
           />
         </Div>
```
![image](https://github.com/VKCOM/VKUI/assets/7815563/e86aa5d1-c184-4d3c-82e4-f6a501b2f9e7)

**Comment by svyatoslavpavlov** [comment]
да, как я понял, есть отдельные кейсы, когда так происходит 
для информации: мигрировал с версии 5.10 -  там этого не было

**Comment by svyatoslavpavlov** [comment]
Похожая ситуация, если использовать с SimpleCell

```
 <SimpleCell
          hasHover={false}
          hasActive={false}
          className={className}
          indicator={**tooltip**}
          after={<Switch
            checked={checked}
            onChange={handleSubscription}
          />}
        >
          <Headline weight={"semibold"}>Уведомления</Headline>
        </SimpleCell>
```

**Comment by svyatoslavpavlov** [comment]
Есть новости? Похоже на регресс после апдейта на  6 версию

**Comment by SevereCloud** [comment]
Привет, для кейсов с новый [контекстом наложения](https://developer.mozilla.org/ru/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context) используйте `usePortal`

**Comment by svyatoslavpavlov** [comment]
значит проблема в описании: 
<img width="370" alt="image" src="https://github.com/user-attachments/assets/3cb097bc-215b-49ad-9c37-d8ad604efc0f">

поставил document.body и все стало нормально
