### ISSUE TITLE
[Bug]: CustomSelect сломан ховер и клик по айтему

### ISSUE THREAD

**Issue by svyatoslavpavlov** [VKCOM/VKUI#7136]
### Описание

Видео записано прям отсюда: https://vkcom.github.io/VKUI/#/CustomSelect
В своем проекте аналогичные проблемы: ховер ломается, клик по выбранному элементу иногда работает некорректно, курсор скачет в начальное состояние

https://github.com/VKCOM/VKUI/assets/7815563/e64b2e9b-6b7a-4890-9002-e787c9277ebd

Проверено на десктопе на мак 14.4.1

### Версия

6.2.0

### В каких браузерах воспроизводится проблема?

Chrome

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.2.1" target="_blank">v6.2.1</a> 🎉
