### ISSUE TITLE
Компонент Link не меняет цвет в темной теме

### ISSUE THREAD

**Issue by luciuz** [VKCOM/VKUI#715]
На темном фоне дефолтный темно-синий цвет ссылки выглядит некрасиво. Было бы прикольно, если цвет ссылки автоматически менялся на более светлый в темной теме.

**Comment by ArthurStam** [comment]
Привет. Цвет меняется. В `space_gray` это `#71aaeb`, в `bright_light` — `#3f8ae0`.

**Comment by luciuz** [comment]
Спасибо, действительно, я почему-то использовал <a> вместо <Link>
