### ISSUE TITLE
[Feature]: Добавить коллбэк для Popover на завершение анимации закрытия

### ISSUE THREAD

**Issue by BlackySoul** [VKCOM/VKUI#7173]
### Описание

Нужен колбэк не на просто смену закрытия/открытия, а именно на исчезновения всплывающего окна (потому что это происходит с анимацией)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.3.1" target="_blank">v6.3.1</a> 🎉
