### ISSUE TITLE
[Feature]: Покрасить фон снекбара в colorBackgroundContrastThemed

### ISSUE THREAD

**Issue by qurle** [VKCOM/VKUI#7211]
### Описание

С новым модальным цветом он стал сливаться на фоне контента. Контраст темед нам поможет
🐱

### Скриншоты

![image](https://github.com/user-attachments/assets/f738509c-80d4-462c-9829-09feee9cb017)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.3.0" target="_blank">v6.3.0</a> 🎉
