### ISSUE TITLE
[Tappable] Волн не видно на цветных кнопках 

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#722]
Пример (волна над буквой `P`):
![image](https://user-images.githubusercontent.com/11076888/82219072-d8e9cb00-992d-11ea-99ce-f4fa9bfca3b0.png)

Фон при нажатии на кнопку: `rgb(146, 182, 224)`
Получившейся цвет волны: `rgb(149, 182, 220)`

**Comment by eolme** [comment]
@wayshev, есть где-нибудь макеты с волнами на Android?

**Comment by ArthurStam** [comment]
Обсудил с дизайнерами. Есть идеи по тому, как переделать.

**Comment by pfrankov** [comment]
Отказываемся от платформенных стилей в пользу универсальных.

**Comment by eolme** [comment]
И тем более их до сих пор не видно, почему issue закрыли?

**Comment by pfrankov** [comment]
@eolme не будет никаких волн больше, а до исправления этого бага для старой версии мы вряд ли доберёмся.

**Comment by eolme** [comment]
@pfrankov не вижу PR по этому поводу
