### ISSUE TITLE
[Bug]: Выбранные акцентные табы красятся в colorBackgroundSecondary на ховере

### ISSUE THREAD

**Issue by qurle** [VKCOM/VKUI#7229]
### Описание

 При `mode="accent"` выбранные табы на ховере красятся в `color_background_secondary` вместо `color_background_contrast_themed‑‑hover`. 
 

### Версия

v6.2.2

![image](https://github.com/user-attachments/assets/93e4cf99-0531-49e4-9e0a-5a6f2faf26d2)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.3.0" target="_blank">v6.3.0</a> 🎉
