### ISSUE TITLE
[Bug]: Некорректный скролл в TextArea

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7246]
### Описание

При изменении размеров экрана в `TextArea` появляется скролл.

Скорее всего проблема в неправильном расчитывании высоты `TextArea`

### Версия

6.3.0

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

1. Зайти на страницу с документацией [TextArea](https://vkcom.github.io/VKUI/#/Textarea)
2. Долистать до примера TextArea "С кнопкой"
3. Поменять ширину окна на меньшую 

Фактическое поведение:

Появляется Скролл в TextArea слева от кнопки

### Ожидаемое поведение

Скролл в TextArea не появится, а контент растянется на всю доступную ему высоту

### Скриншоты

<img width="291" alt="image" src="https://github.com/user-attachments/assets/3dfcb36a-81ae-4314-b6df-95d4611a0dfe">

Править лучше после PR #7124, так как там был добавлен функционал нормального скролла в таких полях

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.5.0" target="_blank">v6.5.0</a> 🎉
