### ISSUE TITLE
[Feature]: FocusTrap добавить возможность фокусироваться на рутовом компоненте, а не на первом интерактивном

### ISSUE THREAD

**Issue by mendrew** [VKCOM/VKUI#7268]
### Описание

FocusTrap выполняет важную функцию - фокус на первом интерактивном элементе всплывающего окна. Это важно для `доступности`, чтобы пользователи скринридера могли взаимодействовать с модальными и диалоговыми окнами.

Но бывает, что хочется, чтобы фокус был на окне, а не на первом интерактивном элементе, например, когда у этого элемента есть тултип, который хочется показывать при фокусе, но не сразу при открытии окна, только лишь потому, что фокус попал на такой элемент из-за логики `FocusTrap`.

В такой ситуации будет полезно добавить возможность фокуса на самом окне.
У нас есть такая логика в `FocusTrap`, мы фокусируемся на окне, когда в нём нету интерактивных элементов.

Теперь же стоит эту логику включать также по пропу.

Например:
```
autoFocus: boolean | 'root'; // root это на родителе с tabIndex
```

Так как `FocusTrap` используется внутри `Popover` и в него уже можно прокидывать свойства напрямую в `FocusTrap`, то достаточно будет расширить `FocusTrap`.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.6.0" target="_blank">v6.6.0</a> 🎉
