### ISSUE TITLE
[Perfomance][Touch]: удалить использование `useEventListener`

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#7269]
В рамках задачи #7028 выяснилось, что использование `useEventListener` в `Touch` и при большом количестве экземпляров компонента, приводит к увеличению потребляемой памяти из-за того, что `useEventListener`, в обход **React**, который использует делегирование событий, навешивает события:

- `pointerenter`/`pointerleave` при `usePointerHover`, а иначе `mouseenter`/`mouseleave`
- `touchstart` при `touchEnabled()`, а иначе `mousedown`

через DOM API прямо на корневой элемент `Touch`.

В PR #7128 тестово заменил `useEventListener` на навешивание событий через **React** – это привело к уменьшению количество обработчиков и тем самым к уменьшению потребляемой памяти.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.6.0" target="_blank">v6.6.0</a> 🎉
