### ISSUE TITLE
[Bug]: Title добавить адаптивность для декстопа

### ISSUE THREAD

**Issue by mendrew** [VKCOM/VKUI#7270]
### Описание

В дизайн-системе есть, а в компоненте нету.

Дизайн-система: https://www.figma.com/design/2sQl2eaxsp7RDRdMOeneEC/%F0%9F%92%A0-VKUI-Common-Library?node-id=28068-214771&t=u3JKOa4p7PHsuRHA-4

### Версия

v6.3.0

### Скриншоты

<img width="1130" alt="Screenshot 2024-07-30 at 12 06 14" src="https://github.com/user-attachments/assets/90966009-b821-4076-a3a7-a15dc098b157">

**Comment by andrey-medvedev-vk** [comment]
Исправлено в https://github.com/VKCOM/VKUI/issues/7283
