### ISSUE TITLE
[Feature][Group]: Создать подкомпонент для игнорирования вертикальных и горизонтальных отступов 

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#7279]
### Описание

Если вложить в Group HorizontalScroll и начать скроллить контент по горизонтали то сам контент будет обрезаться не на границе компонента Group, а на его внутреннем отступе, зачастую дизайнеры просят решать этот момент и убирать этот отступ только для определенной части контента внутри Group. 

Хочется получить решение для такого из коробки, актуально как для горизонтального отступа, так и для вертикального, подкомпонент должен принимать проп с направлением. 

relates #5758 

### Скриншоты

Сейчас:
<img width="798" alt="Снимок экрана 2024-08-01 в 19 29 15" src="https://github.com/user-attachments/assets/89e09e70-ed71-4e7a-91cb-d0c5a1bbef3e">

Как хочется:
<img width="784" alt="Снимок экрана 2024-08-01 в 19 32 02" src="https://github.com/user-attachments/assets/91fbd82b-dfbb-4959-8085-98df602f1c4f">

### Пример того что хотим видеть в коде

```tsx
<Group>
        <Group.ExpandedContent direction='horizontal'>
          Контент здесь игнорирует отступы Group по горизонтали
        </Group.ExpandedContent>
Контент здесь учитывает отступы Group по горизонтали
      </Group>
```

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.6.0" target="_blank">v6.6.0</a> 🎉
