### ISSUE TITLE
[Bug]: Не все компоненты типографики умеют в адаптивность

### ISSUE THREAD

**Issue by mendrew** [VKCOM/VKUI#7283]
## Проблема

Выяснилось, что не все компоненты из раздела Типографики умеют адаптироваться под размер экрана.
Под умением подразумевается использование специальных компонентных токенов в режиме `regular` и `compact`.

### Например.
Компонент [Headline](https://vkcom.github.io/VKUI/#/Headline).
Иммет разные параметры типографики для разных значений level.
Каждый уровень задан специальными токенами:
`--vkui--font_headline1--font_size--regular`
https://github.com/VKCOM/VKUI/blob/716657bed3a0498ac2458ec0b53f9e3bfa46da0d/packages/vkui/src/components/Typography/Headline/Headline.module.css#L1-L6

В режиме `compact` используются уже другие токены:
https://github.com/VKCOM/VKUI/blob/716657bed3a0498ac2458ec0b53f9e3bfa46da0d/packages/vkui/src/components/Typography/Headline/Headline.module.css#L8-L18

То же самое наблюдается для level 2
https://github.com/VKCOM/VKUI/blob/716657bed3a0498ac2458ec0b53f9e3bfa46da0d/packages/vkui/src/components/Typography/Headline/Headline.module.css#L20-L37

Это можно считать идальным примером, но и тут есть ещё что улучшить.
Например, для режима `compact` отстутсвует использование токенов для `font-weight` и `font-family`.
А они тоже могут быть иными, согласно дизайн системе, по крайней мере `font-weight` в `compact` режиме точно может быть изменён через токены, а значит и мы должны это в компоненте отобразить.
На счёт `font-family`, конечно, вопрос, может быть это можно и не добавлять.

## Общие требования для всех `Typography` компонентов
1. `compact` режим, в котором используются `compact` токены для всех режимов, для которых предусмотрены токены, например `level`.  Пример DisplayTitle1 DisplayTitle2 в [vkui-tokens](https://github.com/VKCOM/vkui-tokens/blob/ecdad88decf36df7ad14f5df493ba5adbddae6a5/src/themeDescriptions/base/vk.ts#L316-L337)
2. в отдельных режимах также должны присутствовать токены `font-weight` и ` font-family`. `font-family` перебор?
3. в отдельных режимах должны присутствовать токены `letterSpacing` и `textTransform`, по крайней мере для компонентов `Caption` и `Footnote`.  Пример в [vkui-tokens](https://github.com/VKCOM/vkui-tokens/blob/ecdad88decf36df7ad14f5df493ba5adbddae6a5/src/themeDescriptions/base/vk.ts#L434-L450)

## Компоненты, которые нужно дополнить.
- [x] [DisplayTitle](https://vkcom.github.io/VKUI/#/DisplayTitle) https://github.com/VKCOM/VKUI/pull/7553
  - нет адаптивности для кадого level
- [x] [Title](https://vkcom.github.io/VKUI/#/Title) https://github.com/VKCOM/VKUI/pull/7554
  - нет адаптивности для каждого level
- [x] [Headline](https://vkcom.github.io/VKUI/#/Headline) https://github.com/VKCOM/VKUI/pull/7551
  - нет токенов для `font-weight`
- [x] [Caption](https://vkcom.github.io/VKUI/#/Caption) https://github.com/VKCOM/VKUI/pull/7555
  - нету режима `compact`
  - нет использования токенов для `letter-spacing` и `text-transform`
  - text-transform есть, но не через токен. Возможно через токен было бы лучше 🤷‍♂️ 
  - в [vkui-tokens](https://github.com/VKCOM/vkui-tokens/blob/ecdad88decf36df7ad14f5df493ba5adbddae6a5/src/themeDescriptions/base/paradigm.ts#L478-L487)
- [x] [Footnote](https://vkcom.github.io/VKUI/#/Footnote) https://github.com/VKCOM/VKUI/pull/7563
  - нету режима `compact`
  - нет использования токенов для `letter-spacing` и `text-transform`
- [x] [Text](https://vkcom.github.io/VKUI/#/Text) https://github.com/VKCOM/VKUI/pull/7564
  - нету использования токенов для `font-weight`
- [x] [Paragraph](https://vkcom.github.io/VKUI/#/Paragraph) https://github.com/VKCOM/VKUI/pull/7565
  - нету использования токенов для режима `compact`.
- [x] [Subhead](https://vkcom.github.io/VKUI/#/Subhead) https://github.com/VKCOM/VKUI/pull/7566
  - нету использования токенов для `font-weight`.

##  Проблема с font-weight. https://github.com/VKCOM/VKUI/pull/7549
Отдельно хочется подчеркнуть проблему с` font-weight`.
`font-weight` в дизайн системе может выглядеть как отдельны режим.
Мы позволяем менять `font-weight `с помощью свойства `weight` компонента `Typography`, который под капотом у всех других типографических элементов.
https://github.com/VKCOM/VKUI/blob/716657bed3a0498ac2458ec0b53f9e3bfa46da0d/packages/vkui/src/components/Typography/Typography.tsx#L21-L24

Но Typography поддерживает не все токены, которые могут быть использованы в дизайн-системе.
Вот все токены `fontWeight` пока что существующие в vkui-tokens. [Ссылка](https://github.com/VKCOM/vkui-tokens/blob/ecdad88decf36df7ad14f5df493ba5adbddae6a5/src/themeDescriptions/base/paradigm.ts#L14-L19) на токены темы `paradigm`
```js
https://github.com/VKCOM/VKUI/blob/716657bed3a0498ac2458ec0b53f9e3bfa46da0d/packages/vkui/src/components/Typography/Typography.module.css#L12-L27
```

Сейчас VKUI поддерживает только разные уровни `fontWeightAccent`
https://github.com/VKCOM/VKUI/blob/716657bed3a0498ac2458ec0b53f9e3bfa46da0d/packages/vkui/src/components/Typography/Typography.module.css#L12-L27

Стоит также поддержать и уровни `fontWeightBase`, я видел использование таких токенов в дизайн системе, независимо от regular/compact. Например жирность была fontWeightBase равная 700 и в режиме compact и в режиме regular, что нельзя сейчас поддержать в VKUI.
Надо придумать как эти токены добавить.

### Версия

v6.4.1

**Comment by andrey-medvedev-vk** [comment]
Все компоненты типографики теперь знают о режиме `compact` начиная с версии [v6.7.0](https://github.com/VKCOM/VKUI/releases/tag/v6.7.0)

Чтобы адаптивность работала по дизайн системе нужно убедиться, что в токенах типографических элементов vkui-tokens прописан режим `compact`.
Как, например, [тут](https://github.com/VKCOM/vkui-tokens/blob/935568888d86a9ff22735cab8eb382dee68ed499/src/themeDescriptions/base/paradigm.ts#L392-L402)
```js
fontText: {
  regular: {
    fontSize: 16,
    lineHeight: 20,
    fontFamily: fontFamilyBase,
    fontWeight: fontWeightBase3,
  },
  compact: {
    fontSize: 15,
    lineHeight: 20,
  },
},

```
