### ISSUE TITLE
Неявное использование dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by stels-cs** [VKCOM/VKUI#730]
https://github.com/VKCOM/VKUI/blob/2dc24d735994438c2358126630de55641bdcf9db/src/components/Alert/Alert.tsx#L119

https://github.com/VKCOM/VKUI/blob/5f4a64ccc0c213d83e91a1cd7f579c538ae943bd/src/components/Search/Search.tsx#L164

**Comment by ArthurStam** [comment]
Поправим в v4, чтобы текущим приложениям, которые рассчитывают на инъекцию HTML, не оторвало вёрстку

**Comment by ArthurStam** [comment]
Поправлено в v4
