### ISSUE TITLE
[Feature][HorizontalCell]: Поддержка кастомных значений ширины ячейки

### ISSUE THREAD

**Issue by enemyXXX** [VKCOM/VKUI#7317]
### Описание

На текущий момент шириной ячейки можно управлять через свойство `size`. Есть необходимость указывать кастомные значений ширины, чтобы добиться иного размера. 

Например, при указании `size='m'`, ячейка ограничивается максимальной шириной в 100 пикселей. В макетах используются значения, такие как `105px`, `147px` и другие значения, без внутренней кастомизации которых не получить.

**Comment by BlackySoul** [comment]
Привет! Вот [здесь](https://vkcom.github.io/VKUI/#/HorizontalCell?id=example1) есть пример для `size='l'`:

Выдержка с той же страницы документации:

> При size='l' рекомендуется <Avatar size={128} mode='image'/> или же любой компонент произвольной ширины.

Этого недостаточно для реализации нужной функциональности?

**Comment by SevereCloud** [comment]
Требуется свойство в которой можно передать ширину блока(например передать `size: number`)

Это требуется чтобы не задавать ширину через стили

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
