### ISSUE TITLE
[Feature][Switch]: Уменьшить размеры в режиме Desktop 

### ISSUE THREAD

**Issue by qurle** [VKCOM/VKUI#7318]
### Описание

Track Width: 42px → 32px
Track Height: 26px → 20px

Know Width, Height: 20px → 16px
handle--withRipple:before: 32×32px → 24×24px
Switch Handle Scale: без изменений

+ убрать обводку у активного состояния или сделать её прозрачной (везде).

![image](https://github.com/user-attachments/assets/bb256d9a-24c6-4b2e-b172-47683404f958)

[Макет в фигме ↗](https://www.figma.com/design/2sQl2eaxsp7RDRdMOeneEC/%F0%9F%92%A0-VKUI-Common-Library?node-id=74958-36208&t=Qk1jJn3b8DtBNBXx-11)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.6.0" target="_blank">v6.6.0</a> 🎉
