### ISSUE TITLE
Попытка закрыть Alert с autoclose во время анимации появления приводит к зависанию

### ISSUE THREAD

**Issue by stels-cs** [VKCOM/VKUI#732]
Проверить можно в документации https://vkcom.github.io/vkui-styleguide/#alert

-- переключить стиль на android
-- замедлить анимации до 10% (чтобы успеть кликнуть по кнопке во время анимации)

![alert-bug](https://user-images.githubusercontent.com/8437497/82545127-db7f3700-9b5e-11ea-8cd4-997ee5bd7b5b.gif)

**Comment by ArthurStam** [comment]
Спасибо, поправим
