### ISSUE TITLE
[BREAKING CHANGE][Feature]: Заменить теги по умолчанию в карточках

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7336]
### Описание

- caused by #7238

Необходимо заменить теги по умолчанию в компонентах `Card`, `CardGrid`, `CardScroll`, `ContentCard` на семантические теги `ul` или `li`

В коде можно найти по `TODO [>=7]: поменять тег на...`

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.0" target="_blank">v7.0.0-beta.0</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
