### ISSUE TITLE
[Doc]: Отсутствует отступ между кнопками в модальной карточке (modalroot)

### ISSUE THREAD

**Issue by githubchikov** [VKCOM/VKUI#7347]
### Описание

Между кнопками в модальной карточке нет отступа
![Screenshot_2024-08-08-20-20-13-733_com android chrome](https://github.com/user-attachments/assets/966a9b61-6f66-4bb0-9978-a40e9d17bf04)
[https://vkcom.github.io/VKUI/#/ModalRoot](url)

**Comment by githubchikov** [comment]
![image](https://github.com/user-attachments/assets/5b2d085c-a03f-4a8c-822c-1e705a44448e)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.5.1" target="_blank">v6.5.1</a> 🎉
