### ISSUE TITLE
[Doc]: Иконка копирования ссылки темы выходит за границы экрана

### ISSUE THREAD

**Issue by githubchikov** [VKCOM/VKUI#7349]
### Описание

![Screenshot_2024-08-09-09-22-34-478_com android chrome](https://github.com/user-attachments/assets/48ba8315-94a4-41be-a90e-49b7df6d1acc)
Нужно навести курсор на любую тему (на телефоне нужно нажать на тему), чтобы появилась иконка копирования ссылки, которая уходит за границу экрана

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.5.1" target="_blank">v6.5.1</a> 🎉
