### ISSUE TITLE
[Doc]: Показывается успешная валидация почты, хотя поле заполнено неверно

### ISSUE THREAD

**Issue by githubchikov** [VKCOM/VKUI#7358]
### Описание

![image](https://github.com/user-attachments/assets/ed068694-3188-4c5d-8796-29b1040d4324)
https://vkcom.github.io/VKUI/#/FormItem

**Comment by githubchikov** [comment]
при попытке отправить форму, фокусируется данное поле (показывается текст, как должна выглядеть почта), также при наведении курсором на input, в title пишется ошибка об отсутствии "@"

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.5.1" target="_blank">v6.5.1</a> 🎉
