### ISSUE TITLE
[Feature][ToolButton]: Rounded режим для горизонтальной ToolButton + фиксы

### ISSUE THREAD

**Issue by qurle** [VKCOM/VKUI#7359]
### Описание

Немножко доделок:

- [x]  Возможность капсульно скруглять горизонтальные кнопки.
    > **Note**
    > Т.е. чтобы `rounded` аффектило кнопки с `hasChildren` и `direction=row `
- [x]  `padding: 10px` → `padding: var(--vkui--spacing_size_m)`
    > **Note**
    > Для `rounded && hasChildren && direction=row`  `padding: var(--vkui--spacing_size_xl)
- [x] Для `appearance=neutral && mode=primary` следующие токены для цветов:

  - `background: var(--vkui--color_background_modal_inverse)`
  - `color: var(--vkui--color_text_contrast_themed)`
- [x] Выравнивание по левому краю у текста (если мы контролируем)

![image](https://github.com/user-attachments/assets/2b4dbc1c-c05e-4cfd-b6c2-ce53c3bb35e3)

**Comment by inomdzhon** [comment]
> - [ ] Для `appearance=neutral && mode=primary` background: var(--vkui--color_background_modal_inverse)

При `--vkui--color_background_modal_inverse` нужно ещё `color` в `--vkui--color_text_contrast_themed` выставлять

> - [ ] Выравнивание по левому краю у текста (если мы контролируем)

Это должен быть параметр `align` или как?

---

Вообще уже слишком уже смахивает на [Button](https://vkcom.github.io/VKUI/6.5.2/#/Button) этот **ToolButton**...

**Comment by qurle** [comment]
> При --vkui--color_background_modal_inverse нужно ещё color в --vkui--color_text_contrast_themed выставлять

Да, спасибо, что заметил.
 

> Это должен быть параметр align или как? Если align, то как он будет себя вести при direction=column?

Пока можно без параметра, просто для `direction=row` выключка слева, для `direction=column` по центру.

**Comment by qurle** [comment]
По дизайну ещё над паддингами думаем, завтра вернусь с ответом.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.7.0" target="_blank">v6.7.0</a> 🎉
