### ISSUE TITLE
[Bug]: После двойного жеста свайпбека интерфейс перестаёт быть кликабельным

### ISSUE THREAD

**Issue by danillas** [VKCOM/VKUI#7371]
### Описание

После быстрого двойного жеста свайпбека интерфейс становится некликабельным. При помощи console.log было зафиксировано, что в таком случае не вызывается onSwipeBack. Стек вызовов в консоли выглядит примерно так:

```
[go: panel-2]
[onSwipeBackStart]
```

Воспроизводится с версии 6.2.0

### Версия

6.5.0

### В каких браузерах воспроизводится проблема?

Safari

### Шаги воспроизведения

1. Сделать переход вперёд
2. Выполнить свайпбек назад
3. Практически сразу сделать жест ещё раз

### Ожидаемое поведение

onSwipeBack вызывается, интерфейс не ломается

### Пример с воспроизведением

https://codesandbox.io/p/sandbox/priceless-mahavira-7p782w

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.5.1" target="_blank">v6.5.1</a> 🎉
