### ISSUE TITLE
«Поехала» вёрстка в Firefox

### ISSUE THREAD

**Issue by Realetive** [VKCOM/VKUI#738]
Google Chrome (79.0.3945.130)

![Снимок экрана 2020-05-24 в 3 59 47](https://user-images.githubusercontent.com/2073959/82743357-0b9f2380-9d73-11ea-98a1-7f63e52d8490.png)

Firefox (76.0.1)

![Снимок экрана 2020-05-24 в 4 00 31](https://user-images.githubusercontent.com/2073959/82743371-26719800-9d73-11ea-8018-588534351576.png)

**Comment by Realetive** [comment]
Судя по .browserlist, поддержки десктопных браузеров не планируется?

**Comment by ArthurStam** [comment]
Привет! Спасибо за репорт. Работа по поддержке десктопов уже ведется, фикс будет в 4-й мажорной версии

**Comment by ElForastero** [comment]
Замена padding на margin в решает проблему с выравниваем по baseline в FF.
