### ISSUE TITLE
Растягивается обводка <Avatar />

### ISSUE THREAD

**Issue by semgoSE** [VKCOM/VKUI#739]
1. Положить компонент Avatar в Div 
![tJEkDhDHEPc (2)](https://user-images.githubusercontent.com/48213103/82752430-a4ab5a00-9dc6-11ea-822f-65e07999126a.jpg)

**Comment by ArthurStam** [comment]
Спасибо, поправим

**Comment by fedorov-xyz** [comment]
Будет исправлено в ближайшей версии.
