### ISSUE TITLE
Табы в шапке обрезаются системными кнопками

### ISSUE THREAD

**Issue by VadimTVJ** [VKCOM/VKUI#740]
Табы в шапке обрезаются системными кнопками
https://sun9-20.userapi.com/c857328/v857328184/1a0aa1/RCSECKZ3-y8.jpg

**Comment by ArthurStam** [comment]
Привет. Приложение обернуто в ConfigProvider?

**Comment by VadimTVJ** [comment]
Привет
Да, разумеется

**Comment by ArthurStam** [comment]
Нужен пример с кодом. У меня не получается воспроизвести. Исходя из вашего скрина видно, что почему-то справа формируется места под нативные контролы

**Comment by ArthurStam** [comment]
Сделайте форк отсюда https://codesandbox.io/s/vkui-boilerplate-oj149

**Comment by ArthurStam** [comment]
Бамп

**Comment by ArthurStam** [comment]
Закрываю за отсутствием активности
