### ISSUE TITLE
Не работает бегунок скролла в модалке IOS

### ISSUE THREAD

**Issue by serginij** [VKCOM/VKUI#741]
**Только на IOS.**
Если прокрутить модалку вниз при помощи бегунка, то этот бегунок становится неактивен, и его невозможно использовать.
Как пример - проявляется в приложении https://vk.com/app7363698

**Шаги воспроизведения:**
1. Зайти в приложение.
2. Перейти в пользовательское соглашение.
3. Ползунок справа открутить в самый низ.
4. Зажать ползунок и попытаться передвинуть его наверх. Если с первого раза получилось повторить все действия начиная со второго.

**Фактический результат:**
После воспроизведения шагов ползунок не будет двигаться вверх, только если двигать пальцем по экрану. Также, когда ползунок перестаёт работать, кнопка «Закрыть» срабатывает со второго раза

Видео
https://drive.google.com/open?id=19z5Wh2iWiaqA753IRumilYjCQEbRjF1O

Оригинал тикета
https://vk.com/bug229225

![Screenshot 2020-05-25 at 17 34 49](https://user-images.githubusercontent.com/24574620/82822255-27f3ab00-9eae-11ea-9d93-8f4fd8153abd.png)

**Comment by fedorov-xyz** [comment]
Спасибо за issue. Не могли бы вы уточнить, что такое бегунок скролла?
Доступа к тикету у меня нет.

**Comment by serginij** [comment]
Сейчас прикреплю видео

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
