### ISSUE TITLE
[Bug][CustomSelect]:  Некорректное расположение скруглений при определенных действиях

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#7413]
### Версия

6.0.0 - 6.5.1

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

1. Пролистать экран вверх, чтобы опции от CustomSelect не помещались снизу, и встали сверху
2. Свернуть опции от CustomSelect кликом по компоненту
3. Пролистать экран вниз, чтобы опции от CustomSelect начали помещаться снизу и открыть их нажатием на компонент

### Ожидаемое поведение

Корректные скругления компонента

### Скриншоты

https://github.com/user-attachments/assets/a90f7559-84f1-4746-9d78-f85075edfed7

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.5.2" target="_blank">v6.5.2</a> 🎉
