### ISSUE TITLE
Нет экспорта ModalRootContext

### ISSUE THREAD

**Issue by shalfey41** [VKCOM/VKUI#744]
Хочется использовать ModalRootContext, но сейчас нет экспорта из VKUI:

```js
useContext(ModalRootContext);
```

<img width="310" alt="Снимок экрана 2020-05-25 в 20 26 00" src="https://user-images.githubusercontent.com/9959518/82833524-dd325d00-9ec6-11ea-847b-cdb0a145d82d.png">

**Comment by fedorov-xyz** [comment]
Спасибо, добавим.

**Comment by fedorov-xyz** [comment]
Добавится в блиджайшей версии.
