### ISSUE TITLE
[Bug]: Получение NODE_ENV окружения для vite

### ISSUE THREAD

**Issue by enemyXXX** [VKCOM/VKUI#7441]
### Описание

Для обнаружения что код запускается в `dev` окружении (например для хука `useEffectDev`) используется `process.env.NODE_ENV`, который не позволяет корректно выполнить проверку, если сборщик `vite` (так как в отличии от `webpack` он не содержит объект `process`), а окружение можно получить только с помощью `import.meta.env.MODE`

### Версия

latest

**Comment by SevereCloud** [comment]
Привет, vite действительно не содержит `process`(да и webpack на самом деле тоже), но `proccess.env.NODE_ENV` в процессе сборки бандла [заменяется](https://github.com/vitejs/vite/blob/561b940f6f963fbb78058a6e23b4adad53a2edb9/packages/vite/src/node/plugins/define.ts#L26) на нужную строку

![image](https://github.com/user-attachments/assets/239f31c3-c73a-48a8-a67f-aa102be7ec42)
![image](https://github.com/user-attachments/assets/0132e496-0af1-49ae-a1b1-584c80852008)

Любые сборщики которые умеют собирать React должны поддерживать `process.env.NODE_ENV`, так как оно [используется в самом реакте](https://github.com/facebook/react/blob/1b7478246d05b030a2ae7a8bb07aea8c7df7ef27/packages/react/npm/index.js#L3)

При этом надо понимать что в vite `process.env.NODE_ENV` и `import.meta.env.MODE` это разные штуки. Про их поведение можно прочитать в документации [vite](https://vitejs.dev/guide/env-and-mode.html#node-env-and-modes)

---

Возможно тут есть какая то другая проблема?

**Comment by vkcom-publisher** [comment]
Задача закрыта из-за отсутствия активности в течение последних 14 дней. Если это произошло по ошибке или проблема все ещё актуальна, откройте задачу повторно.
