### ISSUE TITLE
[Feature]: Закрывать ChipsSelect по клику на стрелочку

### ISSUE THREAD

**Issue by anponew** [VKCOM/VKUI#7458]
### Описание

У вас есть компонент ChipsSelect - https://vkcom.github.io/VKUI/#/ChipsSelect

При нажатии на стрелочку (после открытия) он не закрывается, хотелось бы иметь возможность закрывать ChipsSelect по клику

### Скриншоты

<img width="985" alt="image" src="https://github.com/user-attachments/assets/d120e01a-b905-4960-9201-9b3ea4e14d31">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.6.0" target="_blank">v6.6.0</a> 🎉
