### ISSUE TITLE
[Bug]: дизайн ревью iOS Search after "Отмена" 

### ISSUE THREAD

**Issue by shevchux** [VKCOM/VKUI#7460]
### Описание

Кажется на кнопку «Отмена» в компоненте Search нужен hoverMode activeMode opacity, а не background

https://github.com/user-attachments/assets/41bca4d3-66fc-4be3-993d-f85112507a09

____

А еще посмотрите раскадровку. Кнопка почему-то в своих первых кадрах уезжает в противоположную сторону (второй кадр)

А еще она обрезается в середине своего текста (последний кадр). Ожидалось, что уедет за край экрана

<img width="299" alt="image" src="https://github.com/user-attachments/assets/24bde802-a19b-4f6c-a660-5c63ce3c68c4">
<img width="301" alt="image" src="https://github.com/user-attachments/assets/00a77c9a-a966-4bef-b8ab-ae437a5e9a4e">
<img width="300" alt="image" src="https://github.com/user-attachments/assets/ec0fbdfe-3483-441f-9284-fdd403949db2">

____

Тут трогали последний раз, но видимо не помогло
[https://github.com/VKCOM/VKUI/pull/7196/files](https://vk.com/away.php?to=https%3A%2F%2Fgithub.com%2FVKCOM%2FVKUI%2Fpull%2F7196%2Ffiles&cc_key=)

___

В стайлгйде в третьем примере на platform ios тоже неприятная анимация after

https://vkcom.github.io/VKUI/#/Search?id=example3

### Версия

6.5.1

**Comment by inomdzhon** [comment]
> В стайлгйде в третьем примере на platform android тоже неприятная анимация after
> https://vkcom.github.io/VKUI/#/Search?id=example3

В **Android** `after` не выставляется ведь 🤔

**Comment by shevchux** [comment]
> > В стайлгйде в третьем примере на platform android тоже неприятная анимация after
> > https://vkcom.github.io/VKUI/#/Search?id=example3
> 
> В **Android** `after` не выставляется ведь 🤔

ошибся, ios
