### ISSUE TITLE
[Bug]: Вложенные Flex добавляют отрицательные отступы, что иногда ломает разметку

### ISSUE THREAD

**Issue by andres-kovalev** [VKCOM/VKUI#7464]
### Описание

Содержимое вылезает за пределы контейнеров слева и сверху (см. скриншоты)

### Версия

6.0.0

### Шаги воспроизведения

```jsx
  <Flex gap="xs">
    {createArray(3).map((i) => (
      <div style={{ width: '36px', height: '36px', borderRadius: '50%', border: '1px solid red' }} key={i}>
        <Flex
          align="center"
          justify="center"
          style={{ width: '36px', height: '36px', border: '1px solid blue' }}
        >
          VKUI
        </Flex>
      </div>
    ))}
  </Flex>
```

### Ожидаемое поведение

Содержимое не вылезает за пределы контейнеров слева и сверху

### Скриншоты

Получается:

![image](https://github.com/user-attachments/assets/60bbe641-5fae-480e-8d6d-30320122945d)

Хотелось бы:

![image](https://github.com/user-attachments/assets/bd5b7fb4-3098-4040-be45-d30abc774d8f)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.6.0" target="_blank">v6.6.0</a> 🎉
