### ISSUE TITLE
[BREAKING CHANGE][Feature]: Убрать проп `size` у компонента ScreenSpinner

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7466]
### Описание

Сейчас у компонента `ScreenSpinner`  есть проп `size`, который работает не очень правильно и только с состоянием `'loading'.` По дизайну размер всегда фиксированный. Надо выпилить данный prop(по умолчанию размер соответствует размеру `'large'`)
Также необходимо добавить возможность прокидывания кастомного векторного изображения в компонент

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.0" target="_blank">v7.0.0-beta.0</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
