### ISSUE TITLE
[Bug]: Скрытый текст копируется при копировании даты из компонента DateRangeInput

### ISSUE THREAD

**Issue by nemio** [VKCOM/VKUI#7467]
### Описание

Лишний текст копируется при копировании даты из компонента DateRangeInput

Получается что-то вроде

```
16.
Изменить месяц начала
08.
Изменить год начала
2024 — 
Изменить день окончания
23.
Изменить месяц окончания
08.
Изменить год окончания
2024 
```

### Версия

6.5.2

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

1. Открыть календарь через DateRangeInput
2. Выбрать дату 16.08.2024 - 23.08.2024 
3. Выделить дату в текстовом поле
4. Копировать выделенный текст
5. Вставить выделенный текст

### Ожидаемое поведение

Скопированный текст:

```
16.08.2024 - 23.08.2024
```

### Пример с воспроизведением

Воспроизводится на чистом компоненте

https://vkcom.github.io/VKUI/6.5.2/#/DateRangeInput

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.6.0" target="_blank">v6.6.0</a> 🎉
