### ISSUE TITLE
[Bug]: В CustomSelect с поиском не работает перемещение курсора мышью

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#7504]
### Описание

У CustomSelect с поиском не работает перемещение курсора мышью

### Версия

^6.5.1

### Шаги воспроизведения

Требуется CustomSelect у которого включен поиск и уже выбран элемент

1. Тыкнуть по тексту в поле

ФР
Появится курсор в середине текста
ОР:
Выделится весь текст

2. Попытаться выделить текст

ФР
Текст не выделяется
ОР
Текст выделится 

3. Попытаться переставить курсор с помощью мыши

ФР
Курсор не перемещается
ОР
Курсор перемещается 

### Скриншоты

https://github.com/user-attachments/assets/c6fb1583-926c-478e-ab37-49cbfeefdf3b

### Пример с воспроизведением

https://vkcom.github.io/VKUI/#/CustomSelect

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.5.3" target="_blank">v6.5.3</a> 🎉
