### ISSUE TITLE
Android (Meizu): Не работает скролл в модалке

### ISSUE THREAD

**Issue by serginij** [VKCOM/VKUI#751]
### Скорее всего, баг относится к #335, но проверить не могу, поэтому оставляю issue

На конкретном устройстве (meizu M5s) не работает скролл в модальном окне. Возможно, проблема актуальна и для других устройств.

Проявляется в приложении https://vk.com/app7363698 в модалке с пользовательским соглашением.

[Видео](https://drive.google.com/open?id=1w5Key6D0kICcSnPKcBrV-9lMDv7gROHj) прикрепляю.

**Детальная информация**
ОС - Android 6.0 Marshmallow
Устройство - Meizu M5s
Версия Вк - 6.3 (5274)

**Оригинал отчета**
https://vk.com/bug226745

**Comment by fedorov-xyz** [comment]
Привет, спасибо за issue. Посмотрим.

**Comment by inomdzhon** [comment]
@serginij к сожалению, нет возможности воспроизвести, т.к. нет нужного устройства с нужной версией ОС, а также нет доступа к https://vk.com/app7363698 

К #335 не относится, но есть похожее issue #1539, фикс для которого в `v4.33.2`. Стоит попробовать обновиться до этой версии и проверить воспроизводится ли проблема. Если да, то переоткроем issue.

Спасибо 🙏
