### ISSUE TITLE
[Feature][Card]: plain режим отображения компонента

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#7513]
### Описание

Хотим чтобы Card имел plain режим отображения - должен иметь такой же фон как и у shadow, но без тени

**Comment by EldarMuhamethanov** [comment]
@MrZillaGold  хотелось бы уточнить такой же фон как shadow, без тени и без бордера получается?

**Comment by MrZillaGold** [comment]
@EldarMuhamethanov привет! Бордер нужен, карточку будем класть на контрастный фон, например фон View на десктопе

**Comment by MrZillaGold** [comment]
Про бордер казалось речь про радиусы, как раз нам нужен режим с закруглениями без никаких обводок и теней

**Comment by vkcom-publisher** [comment]
Задача закрыта из-за отсутствия активности в течение последних 14 дней. Если это произошло по ошибке или проблема все ещё актуальна, откройте задачу повторно.

**Comment by qurle** [comment]
Как назовём?

**Comment by EldarMuhamethanov** [comment]
> Как назовём?

Plain?)

**Comment by qurle** [comment]
> > Как назовём?
> 
> Plain?)

Точно! Надо будет начать читать названия задач.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
