### ISSUE TITLE
[Feature]: Кастомный контент в ячейках даты

### ISSUE THREAD

**Issue by k-egor-smirnov** [VKCOM/VKUI#7517]
### Описание

Хочется иметь возможность добавлять кастомный контент в компонент календаря.
Хороший пример подобного API есть у [react-dates](https://react-dates.github.io/react-dates/?path=/story/drp-day-props--with-custom-daily-details).

Фича нужна для добавления кастомного контента, либо замены дефолтных чисел в календаре

### Скриншоты

https://calendar.mail.ru/year/today/?action=openVacationCalculation
<img width="697" alt="image" src="https://github.com/user-attachments/assets/601411be-875c-4f27-a253-dffd52101961">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.7.0" target="_blank">v6.7.0</a> 🎉
