### ISSUE TITLE
Событие VKWebAppGetGeodata долго резолвится

### ISSUE THREAD

**Issue by jellyb0y** [VKCOM/VKUI#752]
Периодически ответ на событие `bridge.send('VKWebAppGetGeodata')` приходит с большим ожиданием в минуту, бывает и больше, а то вовсе не приходит.
Не зависит от устройства.

Видео демонстрации https://cloud.mail.ru/public/4HU8/as8Npofj7
По счастливому стечению обстоятельств во время съемки событие всё-таки пришло, однако всё равно пришлось подождать около 20 секунд.

**Comment by ArthurStam** [comment]
Привет. Эта проблема не относится к библиотеке.

**Comment by jellyb0y** [comment]
> Привет. Эта проблема не относится к библиотеке.

Ок, кому можно написать по данной проблеме?

**Comment by ArthurStam** [comment]
https://vk.com/topic-166562603_40071994
