### ISSUE TITLE
[BREAKING CHANGE][Feature]: Поднять версии браузеров в `.browserslistrc`

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#7528]
В рамках новой мажорной версии необходимо:

1. Изучить до каких версий на 2024 год мы можем поднять версии браузеров в `.browserslistrc` и, собственно, внести новые версии в файл. Текущие версии (**v6.6.0**)
    https://github.com/VKCOM/VKUI/blob/ba6b605b9334da356681cff4b46bbb41020bb01f/.browserslistrc#L1-L8
2. После обновления файла, удалить ненужные полифилы/фолбеки.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.0" target="_blank">v7.0.0-beta.0</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
