### ISSUE TITLE
[BREAKING CHANGE][SSR]: отказаться от выставления CSS классов в рантайме

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#7529]
Для улучшения поддержки SSR необходимо убрать выставление классов на DOM-элемент компонентом [AppRoot](https://github.com/VKCOM/VKUI/blob/v6.6.0/packages/vkui/src/components/AppRoot/AppRoot.tsx)

https://github.com/VKCOM/VKUI/blob/ba6b605b9334da356681cff4b46bbb41020bb01f/packages/vkui/src/components/AppRoot/AppRoot.tsx#L142-L181

Сейчас эти классы нужны для выставления того или иного набора токенов из [@vkontakte/vkui-tokens](https://github.com/VKCOM/vkui-tokens).

## Вариант решения проблемы

**@vkontakte/vkui-tokens** отдаёт две версии CSS файла с токенами:

1. `onlyVariablesLocal.css`  – для определения используется CSS класс
2. `onlyVariables.css` – для определения используется `:root`

Сейчас используется 1-ый вариант, который предполагает выставление класса. 

Можно рассмотреть возможность использования 2-го варианта, но в этом случае нужно будет написать **CSS Media Query** либо на нашей стороне (посредством сборки), либо на стороне **@vkontakte/vkui-tokens**.

```css
@media (prefers-color-scheme: light) {
  :root { ... } /* node_modules/@vkontakte/vkui-tokens/themes/vkBase/cssVars/declarations/onlyVariables.css */
}

@media (prefers-color-scheme: dark) {
  :root { ... } /* node_modules/@vkontakte/vkui-tokens/themes/vkBaseDark/cssVars/declarations/onlyVariables.css */
}
```

Если `appearance` зашит, то пользователь может на уровне сервера выставить, например, `<html style="color-scheme: dark"`.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
