### ISSUE TITLE
Обрезается низ ModalPage на закруглённом дисплее

### ISSUE THREAD

**Issue by TyVik** [VKCOM/VKUI#753]
Пример - https://sun1-29.userapi.com/7xtIbmhm58M0Pjn55dXFrwlXMVZFWiFG-prW1A/a08Os6qIAfg.jpg.

**Comment by fedorov-xyz** [comment]
Привет. Если это Android устройство, то ModalPage никак не сможет определить закруглённость экрана. Добавьте отступ под контентом.

**Comment by ArthurStam** [comment]
Думаю, что мы скоро сможем пофиксить на нашей стороне. Нужно слушать инсеты от андроида в том числе. Задача уже в разработке

**Comment by TyVik** [comment]
Спасибо большое за столь быструю реакцию :)
У себя править пока не буду, т.к. это аффектит не меня одного. Да и мелочь, не особо влияющая на работоспособность приложения.

**Comment by pfrankov** [comment]
Исправили
