### ISSUE TITLE
[Feature][Placeholder]: Добавить вертикальные отступы при наличии stretched

### ISSUE THREAD

**Issue by Kritolan** [VKCOM/VKUI#7530]
### Описание

Сейчас, если для `Placeholder` установить флаг stretched, то его вертикальные отступы становятся `inherit`. Это не заметно, если использовать компонент внутри полноценной страницы т.к. обычно высота страницы больше содержимого компонента, но если `Placeholder` использовать внутри `ModalPage` - то это сразу видно и сейчас нужно выставлять эти отступы вручную.

### Скриншоты

https://codesandbox.io/p/sandbox/romantic-julien-csrqw4

**Comment by inomdzhon** [comment]
Привет)

Есть два варианта решения этого кейса:

1. Не использовать `stretched`.
2. Если `stretched` по какой-то причине всё же нужен, то использовать `Spacing`
    ```tsx
    <ModalPage nav="modal">
      <Placeholder
        stretched
        icon={
          <>
            <Spacing size={24} />
            <Icon56GlobeCrossOutline />
          </>
        }
        header="Возникла ошибка"
      >
        Описание ошибки
        <Spacing size={24} />
      </Placeholder>
    </ModalPage>
    ```

**Comment by Kritolan** [comment]
А чем обусловлена необходимость конкретно inherit? Согласно описанию - использование stretched подразумевает отсутствие других элементов на панели, что как бы намекает на необходимость отступов т.к. наследовать их просто неоткуда.

Что по предложенным решениям - обойтись без stretched нельзя т.к. компонент универсален и используется и в обычных панелях, где содержимое долно быть по центру. А использование Spacing выглядит слишком громоздко и костыльно и проще тогда уж просто выставить отступы в стилях.

**Comment by inomdzhon** [comment]
> inherit

зачем изначально при проектировании добавлялся `inherit`, к сожалению, не подскажу, т.к. не участвовал в создании компонента

> Что по предложенным решениям - обойтись без stretched нельзя т.к. компонент универсален и используется и в обычных панелях, где содержимое долно быть по центру. А использование Spacing выглядит слишком громоздко и костыльно и проще тогда уж просто выставить отступы в стилях.

оки, проблему понял

сейчас исправить ситуацию может быть брейкинг чендж, поэтому могу предложить в рамках **VKUI v6** самому выставлять отступы, а в ближайшей мажорной версии мы поправим, чтобы у `stretched` не было `padding-block: inherit`, чтобы не переибвать `withPadding`, чтобы следующая конструкция применялась верно:

```tsx
<Placeholder stretched withPadding>...</Placeholder>
```

договор?

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.0" target="_blank">v7.0.0-beta.0</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
