### ISSUE TITLE
[Feature][OnboardingTooltip]: Добавить анимации открытия/закрытия

### ISSUE THREAD

**Issue by BlackySoul** [VKCOM/VKUI#7545]
### Описание

По аналогии с `Tooltip`

**Comment by inomdzhon** [comment]
От анимаций на `OnboardingTooltip` пока придётся отказаться, т.к. это брейкинг чендж изменение

Анимация на `OnboardingTooltip` будет ломать родительские анимации.

Например, предполагается появление родительского элемента снизу вверх в течение N времени – анимация `OnboardingTooltip` будет форсить её и родительский элемент будет появляется моментально.

<details><summary>Видео пример поведения до и после изменений</summary>
<p>

https://github.com/user-attachments/assets/4c99a6b8-0206-491f-a1f5-30e987bb15aa

</p>
</details>
