### ISSUE TITLE
[Bug][CustomSelect]: Компонент не принимает базовые пропы HTMLInputElement

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#7557]
### Описание

По типам мы не можем передавать в CustomSelect базовые пропы HTMLInputElement, например minLength и maxLength, но по факту они все равно передаются на input элемент внутри компонента 

### Версия

6.6.0

### Скриншоты

<img width="625" alt="Снимок экрана 2024-09-11 в 14 11 32" src="https://github.com/user-attachments/assets/3b140067-409f-4e31-8f7f-f9fb644136d1">

<img width="812" alt="Снимок экрана 2024-09-11 в 14 12 16" src="https://github.com/user-attachments/assets/eff6074e-ca99-4f71-8603-5c9726bc27cb">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.7.0" target="_blank">v6.7.0</a> 🎉
