### ISSUE TITLE
[Feature][UsersStack]: Адаптивная ширина каунтера

### ISSUE THREAD

**Issue by egorprnn** [VKCOM/VKUI#7573]
### Описание

При добавлении контента от 3 символов в каунтер (+ который идет из коробки, двузначное число в count) текст начинает прилипать к его краям, особенно заметно в m размере 

кажется можно сделать его контент адаптивным по ширине

### Скриншоты

<img width="413" alt="Снимок экрана 2024-09-12 в 18 55 38" src="https://github.com/user-attachments/assets/269d789b-a3ab-4431-b704-8496deaa67cc">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.1.0" target="_blank">v7.1.0</a> 🎉
