### ISSUE TITLE
[Bug][Calendar]: При выставлении maxDateTime для календаря - последующие даты не подсвечены как disabled 

### ISSUE THREAD

**Issue by lorentzimys** [VKCOM/VKUI#7576]
### Описание

Если установить maxDateTime для календаря, то ожидаемым поведением является то, что все последующие даты станут серыми, аналогично тому, как если бы мы проставили disableFuture. Подозреваю, что то же самое справедливо и для minDateTime

### Версия

6.2.0

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

1. Создаем календарь с пропсой maxDateTime в будущем (допустим +1 год)
2. Переходим в выборе дат на год вперед и видим, что весь месяц выделен активным цветом, хотя не все даты будут доступны для выбора

### Ожидаемое поведение

Все даты >maxDateTime оформлены disabled цветом

### Скриншоты

![image](https://github.com/user-attachments/assets/f363a23c-f70f-47b7-ac8c-5e872e74147e)

**Comment by EldarMuhamethanov** [comment]
@lorentzimys Не получилось воспроизвести. Можешь скинуть пример codesandbox?

**Comment by vkcom-publisher** [comment]
Задача закрыта из-за отсутствия активности в течение последних 14 дней. Если это произошло по ошибке или проблема все ещё актуальна, откройте задачу повторно.
