### ISSUE TITLE
[Bug][RichCell]: Отсутствует установка цвета фона при локальной смене темы

### ISSUE THREAD

**Issue by Kritolan** [VKCOM/VKUI#7577]
### Описание

При локальном изменении темы компонента часть текста остается с некорректным цветом

### Версия

6.7.0

### Пример с воспроизведением

https://codesandbox.io/p/sandbox/blissful-aj-d3cfwn

**Comment by inomdzhon** [comment]
Привет,

Не совсем понял проблему

В https://codesandbox.io/p/sandbox/vkui-javascript-o1bvg2 нет воспроизведения проблемы

**Comment by Kritolan** [comment]
Поправил ссылку, почему то в меню поделится для форка ссылка на родителя ведет, а не на форк.

**Comment by inomdzhon** [comment]
> Поправил ссылку, почему то в меню поделится для форка ссылка на родителя ведет, а не на форк.

Спасибо 🙏  Теперь вижу

`RichCell` сам по себе фон не задаёт, поэтому и кажется, что не перебиваются токены, например, можно обернуть в отдельный `<Group mode="card">` (не `<Group mode="plain">`, потому что на мобиле фон не задаёт), вот так:

> [!NOTE]
>
> Также, вместо `ConfgiProvider`, стоит использовать `AppearanceProvider`

<details><summary>Поправленный код из Codesandbox</summary>
<p>

```tsx
import {
  Button,
  ButtonGroup,
  AppearanceProvider,
  Group,
  Panel,
  PanelHeader,
  RichCell,
  View,
} from "@vkontakte/vkui";

export default function App() {
  return (
    <View activePanel="profile">
      <Panel id="profile">
        <PanelHeader>VKUI</PanelHeader>
        <AppearanceProvider value="dark">
          <Group mode="card">
            <RichCell
              subhead="Subhead"
              text="Text"
              caption="Caption"
              after="After"
              afterCaption="After Caption"
              bottom="Bottom text"
              actions={
                <ButtonGroup mode="horizontal" gap="s" stretched>
                  <Button mode="primary" size="s">
                    Primary
                  </Button>
                  <Button mode="secondary" size="s">
                    Secondary
                  </Button>
                </ButtonGroup>
              }
            >
              Children
            </RichCell>
          </Group>
        </AppearanceProvider>
        <AppearanceProvider value="light">
          <Group mode="card">
            <RichCell
              subhead="Subhead"
              text="Text"
              caption="Caption"
              after="After"
              afterCaption="After Caption"
              bottom="Bottom text"
              actions={
                <ButtonGroup mode="horizontal" gap="s" stretched>
                  <Button mode="primary" size="s">
                    Primary
                  </Button>
                  <Button mode="secondary" size="s">
                    Secondary
                  </Button>
                </ButtonGroup>
              }
            >
              Children
            </RichCell>
          </Group>
        </AppearanceProvider>
      </Panel>
    </View>
  );
}
```

</p>
</details> 

Это решает проблему?

**Comment by Kritolan** [comment]
В прицнипе да, но это так каждый подобный элемент в случае необходимости оборачивать? Может тогда стоит отразить подобное в документации? И что делать, когда не нужна дополнительная стилилизация?

**Comment by inomdzhon** [comment]
> В принципе да, но это так каждый подобный элемент в случае необходимости оборачивать? 

Всё так, в частности у компонентов `Cell` нет своего фона, в их случае нужно оборачивать

> Может тогда стоит отразить подобное в документации?

Предложение хорошее, но т.к. в `RichCell` это ожидаемое поведение, что нет фона, а перебивание `appearance` это пограничный кейс не вижу приоритета загружать документацию

> И что делать, когда не нужна дополнительная стилизация?

В таком пограничном кейсе без доп стилизации никак: либо задавать `RichCell` фон (подходящий токен `--vkui--color_background_content`), либо оборачивать в отдельную обёртку и ему задать фон

**Comment by inomdzhon** [comment]
issue закрою, но возможность комментировать остаётся

**Comment by Kritolan** [comment]
Переназначение темы для отдельных компонентов в целом довольно пограничный кейс, но в документации он упомянут. Не думаю, что упоминание того, что при оборачивании компонентов с прозрачной обложкой нужно дополнительно переназначить им цвет фона так уж сильно загрузит документацию.

А еще возможно неплохой идеей было бы несколько расширить `AppearanceProvider`, добавив ему что-то вроде ключа `forceBackground`, при наличии которого содержимое бы автоматически оборачивалось с установкой цвета фона.

**Comment by inomdzhon** [comment]
> Переназначение темы для отдельных компонентов в целом довольно пограничный кейс, но в документации он упомянут. Не думаю, что упоминание того, что при оборачивании компонентов с прозрачной обложкой нужно дополнительно переназначить им цвет фона так уж сильно загрузит документацию.

Ты прав, добавил инфу

PR https://github.com/VKCOM/VKUI/pull/7584/files
Демо [Платформы и темы](https://vkui-screenshot.hb.bizmrg.com/pull/7584/cff17214039a746ee6af17a5fd7acb000e9cc12f/styleguide/index.html#/PlatformsAndThemes)

> А еще возможно неплохой идеей было бы несколько расширить `AppearanceProvider`, добавив ему что-то вроде ключа `forceBackground`, при наличии которого содержимое бы автоматически оборачивалось с установкой цвета фона.

токен `--vkui--color_background_content` в `AppearanceProvider` зашивать не хочется, фон будет зависеть от случая к случаю
