### ISSUE TITLE
[Bug][Spacing]: Не устанавливается верхний отступ, если размер строка

### ISSUE THREAD

**Issue by Kritolan** [VKCOM/VKUI#7606]
### Описание

Если в Spacing передавать размер  виде числа - то отступ делится пополам до и после потомков. Но если пеередать строковый размер - то отступ устанавливает только после потомков, но не до.

### Версия

6.7.0

### Пример с воспроизведением

https://codesandbox.io/p/sandbox/youthful-https-9hcv5x

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.7.1" target="_blank">v6.7.1</a> 🎉
