### ISSUE TITLE
[Bug]: Tooltip disableCloseAfterClick не работает

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#7635]
### Описание

Tooltip disableCloseAfterClick при клике на элемент скрывается

### Версия

6.7.0

### Шаги воспроизведения

0. Делаем тултип с свойством `disableCloseAfterClick`

```
<Tooltip placement="right" text="Привет" disableCloseAfterClick >
  <Button style={{ margin: 20 }}>Наведи и кликни</Button>
</Tooltip>
```

1. Наводим на элемент (тултип появился)
2. Кликаем на элемент (тултип скрылся)

### Ожидаемое поведение

При клике тултип не скрывается

### Пример с воспроизведением

https://vkcom.github.io/VKUI/#/Tooltip

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.7.1" target="_blank">v6.7.1</a> 🎉
