### ISSUE TITLE
[Feature]: Добавить подсказку для EllipsisText

### ISSUE THREAD

**Issue by Kritolan** [VKCOM/VKUI#7636]
### Описание

Довольно удобно, когда у обрезанного текста есть подсказка с его полной версией и не приходится гадать, что же именно там обрезалось. Это выглядит достаточно простой надстройкой над `EllipsisText`, где нужно лишь обернуть компонент в `Tooltip`, скрытый, если переполнение отсутствует. Понятное дело, это можно сделать опциональным поведением.

Набросал пример на скорую руку, но пришлось использовать `Text`, вместо `EllipsisText` т.к. второй не дает доступа к `contentRef`
https://codesandbox.io/p/sandbox/funny-galileo-dgjq7f

**Comment by inomdzhon** [comment]
Спасибо за issue, хорошее замечание 👍 

Решение должен дать дизайн @VKCOM/vkui-design, ждём ответа от них

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.0" target="_blank">v7.0.0-beta.0</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
