### ISSUE TITLE
[Вопрос] Будет ли VKUI на CSS?

### ISSUE THREAD

**Issue by li0ard** [VKCOM/VKUI#765]
Здравствуйте!
Я хотел бы знать будет ли VKUI на CSS, так как не всем удобно работать с React.
Я уже начал работу [тут](https://github.com/3peekawOwD/VKUI), но хотелось бы чтобы и разработчики VK тоже приняли участие.

**Comment by 3peekawOwD** [comment]
Окей. Но тогда можете сказать, где взять основные стили(Не компонентов)?

**Comment by ArthurStam** [comment]
У нас почти все стили — это стили компонентов. За исключением сгенерированных стилей для цветовых схем. Вот тут можете ознакомиться https://github.com/VKCOM/VKUI/tree/master/src/styles
