### ISSUE TITLE
[Feature][Button]: Тёмная кнопка в режиме Appearance = Overlay, Mode = Secondary

### ISSUE THREAD

**Issue by qurle** [VKCOM/VKUI#7659]
Из-за того, что вторичные оверлейные кнопки — сочетание белого текста на полупрозрачном белом фоне, они работают непредсказуемо на фотографиях. 

Давайте поменяем цвет фона у Button с `appearance = overlay`, `mode = secondary` на `--vkui__color_overlay_primary`. И соответствующие цвета у `:hover` и `:active` состояний.

![image](https://github.com/user-attachments/assets/96f0f0b3-000a-4e89-a1fa-caf2149a5eee)

![image](https://github.com/user-attachments/assets/044c218e-4b10-4882-80d8-ae8424f2c79b)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.0" target="_blank">v7.0.0-beta.0</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
