### ISSUE TITLE
[BREAKING CHANGE][Epic]: синхронизировать названия параметров с дизайном

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#7660]
## Описание

Необходимо проанализировать дизайн в **Figma** и найти расхождения в именование параметров.

> [!NOTE]
>
> Задачу упростит вот 🔗 [этот](https://figma-props.hb.ru-msk.vkcs.cloud/index.html) документ, который @BlackySoul собрала с помощью самописного скрипта.
>
> Можно будет у неё уточнить по какому принципу сопоставлялся код и дизайн.

<details><summary>Логика разрешения расхождения в именовании</summary>
<p>

> ⚠️ **IMPORTANT 1**
>
> По поводу **под-компонента** есть нюанс, что одно дело если это некий сервисный компонент, как в случае с компонентом `Group` это `Group.Expanded` или как с `Snackbar` это `Snackbar.Basic`, другое если под-компонент мог бы выступать как параметр компонента, например, `<Button after={} />` ➡️ `<Button.After />` – в этом случае мы должны позаботиться о синхронизации названий.

> ⚠️ **IMPORTANT 2**
>
> Исключением являются логические свойства под **RTL**. С @VKCOM/vkui-design договорились переводить следующим образом:
>
> **Свойства**
> - `left` → `before`
> - `right` → `after`
> - `horizontal` → `inline` (пример, [#7166#discussion_r1732347433](https://github.com/VKCOM/VKUI/pull/7166#discussion_r1732347433))
> - `vertical` → `block` (пример, [#7166#discussion_r1732347433](https://github.com/VKCOM/VKUI/pull/7166#discussion_r1732347433))
>
> **Значения**
> - _1 кейс. Если речь про положение в одной плоскости._
>   - `left` → `start`
>   - `right` → `end`
>   - ❓(решается)  `horizontal` → `inline` или `row`
>   - ❓(решается)  `vertical` → `block` или `column`
> - _2 кейс. Если речь про координаты_
>   - `top` → `block-start`
>   - `right` → `inline-end`
>   - `bottom` → `block-end`
>   - `left` → `inline-start`
>
> Дизайн по возможности должен переименовать в **Figma**.

> ⚠️ **IMPORTANT 3**
>
> В коде значения размерностей `'s' | 'm' | 'l'`. Дизайн может оставить полные названия.
>
> - #6474

```mermaid
flowchart TD
    A[Нашли расхождение в именовании] -->
    B{"Это особенность реализации в React?<br><br>Например, использование под-компонента или размерность (см. #6474) или логического синонима названия или антоним названия свойства (ex, в дизайне <code>enable</code>, в коде <code>disable</code>)"}
    B -->|Да| D["Пропускаем<br><br>По возможности смотрим можем ли добавить комментарий в документации"]
    B -->|Нет| E{"Справшиваем у дизайна могут ли они переименовать в Figma?<br><br>"}
    E -->|Да| F["Дизайн решает проблему у себя"]
    E -->|"Нет<br><br>либо техническая особенность Figma, либо iOS/Android разработка уже завязалась на текущее именование"| G["Добавляем в список в этой Epic задаче"]
```

</p>
</details>

## Текущие задачи

- [x] #7665
  - (a) добавить комментарий, что в дизайне `direction` это `Avatar Position`
  - (b) переименовать в рамках `direction` в `avatarsPosition`
- [x] #7646
    > ⚠️ в этой задаче нужно в первую очередь исходить из дизайн-файла: если в дизайне нет той проблему, что описана в задаче, то нужно взять задачу, иначе задачу закрываем.
- [x] #7693
- [x] #7721
- [x] #7691
- [x] #7716
- [x] #7697
- [x] #7755
- [x] #7756
- [x] #7757
- [x] #7758
- [x] #7759
- [x] #7760
- [x] #7768
- [x] #7770
- [x] #7772
- [x] #7776
- [x] #7777
- [x] #7778
- [x] #7779
- [x] #7780
- [x] #7786
- [x] #7789
- [x] #7791
- [x] #7803

**Comment by Kritolan** [comment]
> SimpleCell: переименовать expandable -> chevrone
> MiniInfoCell: переименовать expandable → chevron
А почему разные итоговые имена? И почему `chevron`? Это не выглядит как имя для булево.

Как собственно и `padding`, причем я где-то уже видел обсуждение, что такое имя вызывает желание передать в него какое-то число и никак не ассоциируется с булево.

**Comment by EldarMuhamethanov** [comment]
> А почему разные итоговые имена?

Опечатка, поправил

**Comment by EldarMuhamethanov** [comment]
На данный момент все пункты выполнены - задачу закрываю

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
