### ISSUE TITLE
[Bug]: `Button` в состоянии загрузки кликабелен

### ISSUE THREAD

**Issue by DimaPopov** [VKCOM/VKUI#7663]
### Описание

Кнопка в состоянии загрузки является кликабельной и реагирует на ховеры

```JS
<Button loading>Продолжить</Button>
```

### Версия

6.7.1

### Ожидаемое поведение

Прокидывать одновременно `loading` и `disabled` выглядит странным, ведь в состоянии загрузки кнопка точно должна быть задизейблина. То есть `loading={true}` по умолчанию означает `disabled={true}`

### Скриншоты

_Кнопка по умолчанию_
![image](https://github.com/user-attachments/assets/eac6e4aa-0df7-4697-abab-ae4ba6b16cc0)

_Кнопка на которую наведен курсор_
![image](https://github.com/user-attachments/assets/96019cc9-a520-4d97-a7ff-8a33028cf0e5)

_Кнопка на которую нажали_
![image](https://github.com/user-attachments/assets/7f5a023e-54e7-4860-b16d-6c099d64455e)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.2" target="_blank">v7.0.0-beta.2</a> 🎉
