### ISSUE TITLE
UsersStack – заменить использование `direction` на `avatarsPosition` как это сделано в дизайне 

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7665]
Сейчас в дизайне компонента `UsersStack` используется prop `avatarsPosition`, а в VKUI используется `direction`, нужно синхронизировать эти параметры

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.0" target="_blank">v7.0.0-beta.0</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
