### ISSUE TITLE
[Баг] При большом кол-ве символов в Snackbar они уходят за его пределы, а не сокращаются в ...

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#767]
![image](https://user-images.githubusercontent.com/26293210/83281905-791eda00-a1e1-11ea-9889-5bf520e8e36a.png)

**Comment by danyadev** [comment]
В данном случае (как мне кажется) возможно только сокращение текста для одной строки, потому что стили для укорачивания строки в "выаыва..." работают только на одну строку.

Если однострочный текст здесь это норма, то тогда проблем нет.

**Comment by fedorov-xyz** [comment]
Спасибо за тикет, поправим.

**Comment by danyadev** [comment]
> > В данном случае (как мне кажется) возможно только сокращение текста до одной строки, потому что стили для укорачивания строки в "выаыва..." работают только на одну строку.
> > Если однострочный текст здесь это норма, то тогда проблем нет.
> 
> line-clamp работает на всех браузерах, которые поддерживают VKUI

Ух ты, не знал об этом поле, спасибо)

**Comment by SevereCloud** [comment]
Привет, фикс будет доступен в следующей версии
