### ISSUE TITLE
[Feature]:CalendarRange изменить логику выбора диапазона дат

### ISSUE THREAD

**Issue by andrey-medvedev-vk** [VKCOM/VKUI#7670]
## Текущее поведение: сложно выбрать первую дату диапазона, если хочется поменять её.

Если уже выбран диапазон и хочется изменить первую дату, с которой диапазон начинается, то сделать это очень сложно. Каждый раз, когда кликаешь нужную дату внутри диапазона, то меняется последняя дата диапазона. Если кликнуть на дату до первой даты диапазона, то она будет выбрана как первая дата и диапазон увеличится.
Чтобы действительно выбрать первую дату нужно дважды кликнуть на один и тот же день в календаре, что бы заного инициировать выбор диапазон. Это не интуитивно. Работать становится комфортно только если эту особенность понять.

https://github.com/user-attachments/assets/881df9c8-5a54-4d56-b296-eabb54794cda

## Решение
Для выбора диапазона нужно проставить первую и вторую дату. Для сброса мы кликаем на третью дату и заполняем все заново.

https://github.com/user-attachments/assets/096a4db5-9cf2-4e34-ac9d-7909046ee223

Вторую дату можно выбрать как до первой, так и после. Если вторая дата выбрана до первой даты, то вторая становится первой, а первая второй. Как и сейчас.

### Discussed in https://github.com/VKCOM/VKUI/discussions/6894

<div type='discussions-op-text'>

<sup>Originally posted by **Semigradsky** May  6, 2024</sup>
Сейчас выбор диапазона дат выглядит "очень не обычно"...
</div>

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.0" target="_blank">v7.0.0-beta.0</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
