### ISSUE TITLE
[Bug][Gallery]: Фатальная ошибка если галерея не имеет потомков при наличии флага looped

### ISSUE THREAD

**Issue by Kritolan** [VKCOM/VKUI#7672]
### Описание

Если в галерея в зацикленном режиме - то в случае, когда в ней отсутствуют потомки т.е. показывать нечего - вылетает ошибка ломающая всю страницу. Сама ошибка возникает в дочернем компоненте CarouselBase, который применяется для зацикленного режима.

### Версия

6.7.0

### Шаги воспроизведения

Добавить в любое место страницы `<Gallery looped />`

### Ожидаемое поведение

Компонент просто не будет отображаться.

### Скриншоты

![изображение](https://github.com/user-attachments/assets/f1fd9cc4-c854-48ee-9fa2-bb0aa2b66643)

**Comment by BlackySoul** [comment]
Привет! Спасибо за `issue`, ошибку исправим и, возможно, в мажорной версии сделаем проп `children` обязательным. Какое практическое применение у `Gallery` без слайдов?

**Comment by Kritolan** [comment]
Ну например в случае, когда содержимое загружается динамически и в итоге может отсутствовать. Без флага looped - компонент просто не рендерится и в целом все выглядит нормально.

**Comment by BlackySoul** [comment]
> Ну например в случае, когда содержимое загружается динамически и в итоге может отсутствовать. Без флага looped - компонент просто не рендерится и в целом все выглядит нормально.

Ага, в обычном режиме сейчас вместо галереи ничего не отрисовывается, но, кажется, что это плохо само по себе - `layout shift` может быть существенный, когда слайды подгрузятся. Лучше будет отрисовывать какой-то слайд-заглушку, чтобы этот момент минимизировать + дать пользователю знать о наличии контента.

**Comment by inomdzhon** [comment]
> Лучше будет отрисовывать какой-то слайд-заглушку, чтобы этот момент минимизировать + дать пользователю знать о наличии контента.

Дополню, что есть компонент [Skeleton](https://vkcom.github.io/VKUI/6.7.1/#/Skeleton)

**Comment by Kritolan** [comment]
Конкретно этот момент мне кажется лучше оставить на совести автора, как и с любыми другими обертками.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.0" target="_blank">v7.0.0-beta.0</a> 🎉
