### ISSUE TITLE
[Bug]: Spacing size=number не работает

### ISSUE THREAD

**Issue by svyatoslavpavlov** [VKCOM/VKUI#7673]
### Описание

Работает с текестовыми параметрами
<Spacing size={"xl"}/> 
Но не работает с числовыми
<Spacing size={16}/> 

### Версия

6.7.1

### В каких браузерах воспроизводится проблема?

Chrome

**Comment by BlackySoul** [comment]
Привет, спасибо за `issue`, на указанной версии (6.7.1) не воспроизводится. Можно какой-то пример?

**Comment by svyatoslavpavlov** [comment]
Не работает
```
 <AppRoot
            mode="full"
            safeAreaInsets={vkBridgeInsets}
          >

                  <SplitLayout>
                    <SplitCol
                      width={"100%"}
                    >
                      <div>Line 1</div>
                      <Spacing size={100}/>
                      <div>Line 2</div>
                    </SplitCol>
                  </SplitLayout>

          </AppRoot>
```

 работает
```
 <AppRoot
            mode="full"
            safeAreaInsets={vkBridgeInsets}
          >

                  <SplitLayout>
                    <SplitCol
                      width={"100%"}
                    >
                      <div>Line 1</div>
                      <Spacing size={"l"}/>
                      <div>Line 2</div>
                    </SplitCol>
                  </SplitLayout>

          </AppRoot>
```

**Comment by BlackySoul** [comment]
> Не работает
> 
> ```
>  <AppRoot
>             mode="full"
>             safeAreaInsets={vkBridgeInsets}
>           >
> 
>                   <SplitLayout>
>                     <SplitCol
>                       width={"100%"}
>                     >
>                       <div>Line 1</div>
>                       <Spacing size={100}/>
>                       <div>Line 2</div>
>                     </SplitCol>
>                   </SplitLayout>
> 
>           </AppRoot>
> ```
> 
> работает
> 
> ```
>  <AppRoot
>             mode="full"
>             safeAreaInsets={vkBridgeInsets}
>           >
> 
>                   <SplitLayout>
>                     <SplitCol
>                       width={"100%"}
>                     >
>                       <div>Line 1</div>
>                       <Spacing size={"l"}/>
>                       <div>Line 2</div>
>                     </SplitCol>
>                   </SplitLayout>
> 
>           </AppRoot>
> ```


Все равно не воспроизводится - [пример](https://stackblitz.com/edit/vitejs-vite-gwzskh?file=src%2FApp.tsx). Что в этот момент в верстке происходит?

**Comment by svyatoslavpavlov** [comment]
Обновил другие зависимости и все заработало корректно, закрываю баг
