### ISSUE TITLE
[Feature][Cell Button]: Покрасить CellButton в Accent

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#7683]
## Требование от дизайна

> Нужно покрасить иконку и текст обычного `CellButton` в цвета _Accent_, а версию `centered` в _Accent Themed_ @qurle 

## Требование к разработке

1. Переименовать `mode` в `appearance` с измененными значениями

    ```diff
    - /**
    -  * @default primary
    -  */
    - mode: 'primary' | 'danger';
    + /**
    +  * > Режим `centered` переопределяет токен для темы `"accent"`.
    +  *
    +  * @default accent
    +  */
    + appearance: 'accent' | 'neutral' | 'negative';
    ```
2. Добавить недостающую стилизацию

## Скриншоты

<img width="320" src="https://github.com/user-attachments/assets/61bdf0be-6dcd-4978-805f-ce57a6d9379d" />

---

- related to #7330

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
