### ISSUE TITLE
[Feature]: предоставить возможность передавать data-testid в важные элементы компонента Calendar и ему подобных

### ISSUE THREAD

**Issue by andrey-medvedev-vk** [VKCOM/VKUI#7688]
### Описание

`Calendar` - сложный компонент со множеством вложенных элементов.
В e2e-тестировании очень тяжело взаимодействовать с календарём опираясь на классы и структуру `DOM` элементов, не говоря уже о том, это опора на не публичное API компонента, которое может поменяться в любом патче, что будет ломать тесты `Calendar`.

Требуется предоставить возможность передавать `data-testid` во все значимые для тестирования подкомпоненты.

---

В одном из обсуждений этой проблемы @inomdzhon предложил следующее API.
```tsx
interface DataTests {
  month?: string;
  day?: string;
  currentDay?: string;
  nextMonthAction?: string;
  prevMonthAction?: string;
}

<Calendar dataTest={{ day: "my-locator-for-test" }} />
```

Стоит обратить внимание, что это только предложение, реальный интерфейс `DataTests` сложнее.
Для дней в календаре одного префикса, скорее всего, мало. Дней в месяце может быть много, стоит дать возможность пользователю построить свой префикс на основе номера дня. 

Нужно учесть особенность CalendarRange, где мы показываем сразу два месяца. Например, добавляя номер месяца в data-testid. Это касается не только дней в месяце, но и других интерактивных элементов, которые мы показывем для каждого месяца.

```ts
interface DataTests {
  day?: string | (day: number, month: number) => string
}
```

----

AC: 
- должна быть возможность прокинуть `data-testid` всем интерактивным элементам.
- поддержка должна работать в компонентах `Calendar`, `CalendarRange`, `DateInput`, `DateRangeInput`.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.7.4" target="_blank">v6.7.4</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.2" target="_blank">v7.0.0-beta.2</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
