### ISSUE TITLE
Не работает скролл в сервисе (веб-версия)

### ISSUE THREAD

**Issue by temafeed** [VKCOM/VKUI#769]
1. Открыть сервис с десктопа, пример: https://vk.com/app6798836
2. Открыть Друзья.
3. Открыть Карьера.
4. Выбрать любую организацию.
5. Скроллим список вниз.

ФР: Скролл списка работников не работает, скроллится страница раздела

видео: vk.com/doc280639911_550624991?hash=9cf949a386f9011989&dl=3d78fae96b658d0c08

![Снимок](https://user-images.githubusercontent.com/48914834/83353800-84971000-a35d-11ea-91c2-ed05865fdfb4.PNG)

**Comment by ArthurStam** [comment]
Привет. Мы начали работу над веб-версией, будет поправлено в v4
