### ISSUE TITLE
[BREAKING CHANGE]Banner: переименовать свойство subheader -> subhead

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7691]
- relates to #7646

Необходимо переименовать свойство `subheader` в `subhead` компонента `Banner`

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉
