### ISSUE TITLE
[Bug]: Недетерминированное поведение CustomSelect и пустого value

### ISSUE THREAD

**Issue by BlackySoul** [VKCOM/VKUI#7696]
### Описание

Сейчас существует неоднозначное поведение компонента `CustomSelect` при значениях `value = undefined | ''`

Необходимо разделить кейсы, когда у нас нет значения - показывается плейсхолдер, и есть значение - но оно равно пустой строке.

https://github.com/user-attachments/assets/02fcbb65-aad9-4306-82a4-f094a495c8dd

### Версия

v6

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
