### ISSUE TITLE
[BREAKING CHANGE] HorizontalCell: переименовать свойство header -> title

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7697]
- relates to #7646

Необходимо переименовать свойство `header` в `title` компонента `HorizontalCell`

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
