### ISSUE TITLE
[BREAKING CHANGE][CustomScrollView]: перейти на CSS-way решение для стилизации ползунка

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#7699]
Так как дизайн никак не документирует поведение полосы прокрутки и его ползунка, необходимо перейти на использование системного поведения, тем самым облегчить компонент [CustomScrollView](https://vkcom.github.io/VKUI/6.7.2/#/CustomScrollView) застилизовав его через CSS (https://caniuse.com/css-scrollbar).

Из **BREAKING CHANGE** это удаление параметров `TrackerOptionsProps`.

### Преимущества

1. удалим DOM-элемет(-ы);
    > Их может быть два если включить и горизонтальный, и вертикальный скроллы.
    > На самом деле их больше чем два, а может остаться только один

2. удалим обработчики событий `onwheel`, `onmousedown`, `onmouseleave`, `ondragstart`, `ondragstop`;
3. удалим использование тяжёлого `useResizeObserver()`, что в целом улучшит производительность страницы, где используется CustomScrollView;
4. предупредим баги связанные с кастомным ползунком.
    > Например, сейчас у ползунка отсутствует взаимодействик на тач-события.
    > Вообще все нативные решения намного более устойчивы к багам
5. Удалим кучу лишнего кода, компонент станет максимально простым

### Нюансы

1. Останется проблема, что в Firefox < 64 будет обычный скролл, а не застилизованный

https://github.com/VKCOM/VKUI/blob/ccb624635142bde31b301a1bfcc19e6d37594c19/packages/vkui/src/components/CustomScrollView/CustomScrollView.module.css#L129-L135

2. Есть два способа кастомизации:
  - используя относительно новые свойства [scrollbar-color](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color) и [scrollbar-width](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width) у этих свойств [поддержка в браузерах](https://caniuse.com/?search=scrollbar-width) такая себе, в основном хорошо поддерживается в firefox, но например абсолютно не поддерживается в Safari
  - использую нестандартные свойства с префиксом -webkit-.. такие как [-webkit-scrollbar](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar) у этих свойств ситуация противоположная. [Поддержка](https://caniuse.com/?search=%3A%3A-webkit-scrollbar) говорит, что поддерживается хорошо везде, кроме Firefox(там вообще нет) 
Исходя из этого надо использовать оба подхода сразу, чтобы покрыть все браузеры. НО, если браузер поддерживает оба способа кастомизации скролла(например последние версии Chrome) то первый способ будет полностью перебивать второй. Возможно не так критично, но все же не всегда очевидно

4. Есть проблема с кастомизацией. Через scrollbar-color, scrollbar-width особо не кастомизировать ничего кроме цвета и ширины(причем только 2 варианта размера есть). А также если кастомизировать через webkit псевдоклассы, то там возможностей побольше, но все равно не идеально. Например плавное изменение размера или смена фону при наведении на thumb реализовать невозможно. Будет меняться довольно резко. И кстати смену размера можно сделать только через небольшой костыль с бордерами.

5. Также при кастомизации через ::webkit у thumb нельзя задать opacity, но можно задать сразу цвет с прозрачностью. В таком случае надо добавлять такой токен, или искать более менее подходящий для этого из имеющихся. Сейчас используется токен без прозрачности и добавляется прозрачность через opacity

6. Нельзя сделать реально прозрачным пространство под thumb, то есть scrollbar-track. Даже если задать цвет transparent, он все равно будет сполшным белым и будет наезжать на контент

## Ссылки

- [CSS Tricks • scrollbar](https://css-tricks.com/almanac/properties/s/scrollbar/)
- [Developer Mozilla • CSS scrollbars styling](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scrollbars_styling)

**Comment by qurle** [comment]
Было бы клёво предупредить о кейсах, где нативные скроллбары немного всё сломают. 
Например, скролл теперь не сможет быть поверх контента, а скачки ширины вьюпорта при появлении оверфлоу станут неизбежными.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
