### ISSUE TITLE
[BREAKING CHANGE] RichCell: переименовать свойства text -> subtitle, caption -> extraSubtitle, subhead -> overtitle

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7716]
- relates to #7646

Необходимо переименовать свойство `text` в `subtitle`, `caption` в `extraSubtitle`,  `subhead` в `overTitle` компонента `RichCell`

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
