### ISSUE TITLE
[BREAKING CHANGE]: переименовать `appearance`, который отвечает за `'light'`/`'dark'`, в `colorScheme`

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#7717]
## Почему?

Сейчас оно коррелирует с параметром `appearance` у компонентов, таких как [Button](https://vkcom.github.io/VKUI/7.0.0-beta.0/#/Button), [CellButton](https://vkcom.github.io/VKUI/7.0.0-beta.0/#/CellButton),  [Separator](https://vkcom.github.io/VKUI/7.0.0-beta.0/#/Separator), [ToolButton](https://vkcom.github.io/VKUI/7.0.0-beta.0/#/ToolButton) и т.п.. В этих компонентах `appearance` используется как определение цветового оформления, а не режим `'light'`/`'dark'`.

## Где нужно переименовать?

1. константа: `Appearance` → `ColorSheme`
2. тип: `AppearanceType` → `ColorShemeType`
3. провайдер: `AppearanceProvider` → `ColorSchemeProvider`
4. хук: `useAppearance` → `useColorSheme`
5. параметр в `ConfigProvider`:
    ```diff
    <ConfigProvider
    -  appearance="light"
    +  colorSheme="light"
    />
    ```

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
