### ISSUE TITLE
[Bug]: Восстановление фокуса после закрытия Popover по 'hover'

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7732]
### Описание

Сейчас у компонента `Popover` есть функционал, с помощью которого при закрытии `Popover` фокус восстанавливается на том элементе, который был в фокусе перед открытием `Popover`. Этот функционал работает ожидаемо, если trigger, например, 'focus', 'click'. Но при trigger: 'hover' может возникнуть проблема, что активный элемент перед открытием Popover не якорный элемент. Из-за этого при закрытии Popover фокус восстановится не на том элементе, и более того может вызвать скролл до этого элемента, что может быть критично в некоторых ситуациях.

### Версия

6.7.2

### В каких браузерах воспроизводится проблема?

Firefox, Chrome, Safari

### Шаги воспроизведения

1. Ставим фокус на любой элемент, который может быть в фокусе
2. Наводимся на элемент с Popover. Popover открывается
3. Убираем мышь с этого элемента. Popover закрывается, фокус устанавливается не на якорный элемент, происходит скролл до этого элемента

### Ожидаемое поведение

Скролл не скачет, и фокус устанавливается на якорный элемент(этот момент нужно обдумать)

### Скриншоты

https://github.com/user-attachments/assets/3ec58618-20b6-4b82-a782-4e73012a0d7b

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.7.4" target="_blank">v6.7.4</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.2" target="_blank">v7.0.0-beta.2</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
