### ISSUE TITLE
[Feature][Calendar]: Добавить возможность скрытия кнопки `Done`

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7733]
### Описание

Сейчас при прокидывании `enableTime` в `Calendar` появляется блок с выбором времени и кнопкой `Done`. Сейчас в этой кнопке можно поменять только текст через `doneButtonText`. Нужно добавить возможность скрытия данной кнопки, а также подумать какие еще свойства могут понадобиться для данной кнопки(например `disabled`). Также при отключении селекты со временем должны центрироваться

### Скриншоты

![f5WZN_lrqyQaNkZtlJIOa8kX0q79owBXWpDf__y0rXsv7XmPO8foBzbGD_KPxK5hziWcBGQkXrKbZrWYlvtowpUv](https://github.com/user-attachments/assets/c3565a80-07a6-4d4c-8b9f-7be1778fd8b8)

**Comment by Kritolan** [comment]
А как закрывать календарь, без этой кнопки? После выбора секунд? Или только кликом за пределы календаря?
Возможно вместо добавления множества свойств с префиксом имеет смысл передавать объект с настройками? Либо в целом передавать всю кнопку как свойство?

**Comment by lorentzimys** [comment]
> А как закрывать календарь без этой кнопки? После выбора секунд? Или только кликом за пределы календаря? Возможно вместо добавления множества свойств с префиксом имеет смысл передавать объект с настройками? Либо в целом передавать всю кнопку как свойство?

Сама по себе эта кнопка календарь не закрывает, а только вызывает обработчик, который ей передается, так что поведение закрытия календаря можно реализовать по собственному усмотрению.

**Comment by Kritolan** [comment]
А, ну да, спутал с `DateInput`. Видимо это будет уже несколько оффтопик, но вопрос все еще актуален т.к. `DateInput` как я понимаю наследует свойства календаря, а значит в нем тоже можно будет отключить кнопку. Это в целом совпадает с ситуацией когда выключено свойство `closeOnChange`, но как закрывать календарь, кроме как кликом снаружи непонятно.
Тут ксатати еще можно заменить, что свойство `closeOnChange` не работает, при включенном времени у `DateInput`.

**Comment by andrey-medvedev-vk** [comment]
> А, ну да, спутал с `DateInput`. Видимо это будет уже несколько оффтопик, но вопрос все еще актуален т.к. `DateInput` как я понимаю наследует свойства календаря, а значит в нем тоже можно будет отключить кнопку. Это в целом совпадает с ситуацией когда выключено свойство `closeOnChange`, но как закрывать календарь, кроме как кликом снаружи непонятно. Тут ксатати еще можно заменить, что свойство `closeOnChange` не работает, при включенном времени у `DateInput`.

Привет @Kritolan 

Спасибо, что поделился своими мыслями, заставил задуматься.

Мы намеренно не будет добавлять эту возможность в `DateInput`, как раз по причинам, которые ты обозначил. `DateInput` наследует свойства календаря, но не все.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.7.4" target="_blank">v6.7.4</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.2" target="_blank">v7.0.0-beta.2</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
