### ISSUE TITLE
Забыли покрасить или так задумано?

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#775]
Как-то странно, что border-top у баннера светлый, не лучше его затемнить?

<img width="385" alt="Снимок экрана 2020-06-02 в 14 46 46" src="https://user-images.githubusercontent.com/45998835/83516549-f008eb00-a4df-11ea-8a0a-c06fd1bc8479.png">

**Comment by ArthurStam** [comment]
Уточню, спасибо.

**Comment by ArthurStam** [comment]
Нужен `--separator_alpha`
