### ISSUE TITLE
[BREAKING CHANGE] Banner: переименовать asideMode -> after

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7755]
## Описание

Нужно переименовать свойство `asideMode` компонента `Banner` на `after` для единообразия с другими компонентами. Также надо учесть, что при `asideMode` `expandable` компонент становится кликабельным. Возможно придется добавить дополнительное свойство, чтобы кликабельность не зависела от свойства `after`

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉
