### ISSUE TITLE
[BREAKING CHANGE] CardScroll: переименовать noSpaces -> padding

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7756]
## Описание

Необходимо переименовать в компоненте `CardScroll` свойство `noSpace` в `padding`. Также необходимо инвертировать существующие значения `noSpace`

**Comment by Kritolan** [comment]
А почему `padding`, а не `withPadding`, например? Это не выглядит как булево, причем я где-то уже видел обсуждение, что такое имя вызывает желание передать в него какое-то число и никак не ассоциируется с булево.

**Comment by EldarMuhamethanov** [comment]
> А почему `padding`, а не `withPadding`, например? Это не выглядит как булево, причем я где-то уже видел обсуждение, что такое имя вызывает желание передать в него какое-то число и никак не ассоциируется с булево.

Синхронизировали название с дизайном + в будущем может появиться необходимость прокинуть число в этот параметр

**Comment by Kritolan** [comment]
Но до этого будущего этот параметр будет лишь всех путать. Может стоит все же поменять название в дизайне, чтобы не использовать термин, который уже имеет вполне конкретную конотацию из CSS с совершенно другим типом данных?

**Comment by inomdzhon** [comment]
> Но до этого будущего этот параметр будет лишь всех путать. Может стоит все же поменять название в дизайне, чтобы не использовать термин, который уже имеет вполне конкретную конотацию из CSS с совершенно другим типом данных?

Спасибо за отличное замечание 🙏  

Обсудили этот момент и пришли к тому, что всё же оставить булин будет лучше, т.к. его легче будет расширить до union типа в рамках одного параметра, а проблему DX будет решена за счёт валидации TypeScript или за счёт IDE в проектах без TypeScript

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
