### ISSUE TITLE
[BREAKING CHANGE] Header: переименовать aside -> after

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7757]
## Описание

Нужно переименовать свойство `aside` компонента `Header` на `after`

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
