### ISSUE TITLE
[BREAKING CHANGE] Placeholder: переименовать header -> title, text -> description

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7759]
## Описание

Нужно переименовать свойство `header` и сабкомпонент `Placeholder.Header` на `title`. Также нужно переименовать `Placeholder.Text` на `Description`

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
