### ISSUE TITLE
[Separator]: значения direction переименовать с `'inline' | 'block'` на `'horizontal' | 'vertical'`

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7760]
- caused by #7720

## Описание

Нужно значения `direction` компонента `Separator` переименовать с `'inline' | 'block'` на `'horizontal' | 'vertical'`

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
