### ISSUE TITLE
При переходе по Link вида https://vk.com/id* закрывается мини-апп

### ISSUE THREAD

**Issue by trofimovdev** [VKCOM/VKUI#777]
Видео: https://vk.com/doc165275777_556300869
Возможно, появилось в VK 6.5 (948) — версия с видео.
В VK Me 1.34 (948) не воспроизводится.

Код с видео:
```
<Link
  href="https://vk.com/id165275777"
  target="_blank"
  rel="noopener noreferrer"
>
  id
</Link>

<Link href="https://vk.com/trofimovdev"
  target="_blank"
  rel="noopener noreferrer"
>
  short url
</Link>
```

**Comment by ArthurStam** [comment]
Привет. Здесь мы обсуждаем библиотеку компонентов. Вам сюда: https://vk.com/vkappsdev
