### ISSUE TITLE
[BREAKING CHANGE] ContentCard: переименовать header -> title, subhead -> overTitle, text ->description

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7770]
## Описание

Нужно переименовать свойства компонента ContentCard: header -> title, subhead -> overTitle, text ->description

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
