### ISSUE TITLE
[BREAKING CHANGE] Banner: переименовать header -> title, subhead -> title, extraSubhead -> extraSubtitle

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7772]
## Описание

В компоненте Banner нужно переименовать header -> title, subhead -> title, extraSubhead -> extraSubtitle

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
