### ISSUE TITLE
[Bug]: На стрелке в HorizontalScroll не работает прокрутка колесом

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/VKUI#7774]
### Описание

При наведении на стрелку в [HorizontalScroll](https://vkcom.github.io/VKUI/#/HorizontalScroll) не работает прокрутка через колесо мыши

Это может доставлять неудобство, если область прокрутки маленькая, как например скролл папок в мессенджере 

### Шаги воспроизведения

1. Навести мышку на стрелку в скроле
2. Попытаться проскролить

### Ожидаемое поведение

Прокрутка скрола

### Скриншоты

https://github.com/user-attachments/assets/076f08e7-a825-459d-9f93-250ecbfeea9a

### Пример с воспроизведением

[HorizontalScroll](https://vkcom.github.io/VKUI/#/HorizontalScroll)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.7.4" target="_blank">v6.7.4</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.2" target="_blank">v7.0.0-beta.2</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉

**Comment by inomdzhon** [comment]
см. описание #8294
