### ISSUE TITLE
[Feature][Button]: Чёрная кнопка в режиме Appearance = Neutral, Mode = Primary 

### ISSUE THREAD

**Issue by qurle** [VKCOM/VKUI#7775]
### Описание

Привзяываем фон к токену Background / Content Inverse (VKUI Tokens v4.55)
Текущие в коде рекомендуем изменить на Appearance = Neutral, Mode = Secondary 

![image](https://github.com/user-attachments/assets/d26ef70e-1110-40a7-a2df-e71b49b1d8c8)

[Макет в фигме ↗️](https://www.figma.com/design/Ofjgb91MHEW1VyAS0AZWgr/%F0%9F%9B%A0%EF%B8%8F-VKUI-Library-%5BBeta%5D?node-id=53384-77750&node-type=frame&t=ZVUNUwWvlGPKRA0z-11)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.2" target="_blank">v7.0.0-beta.2</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
