### ISSUE TITLE
[BREAKING CHANGE] Group: переименовать header -> title и подкомпонент

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7776]
## Описание

Нужно переименовать свойств header на title, а также подкомпонент Group.Header на Group.Title

**Comment by EldarMuhamethanov** [comment]
Обсудили, решили что переименовывать не нужно, так как в Group header - это не текстовый слой

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
