### ISSUE TITLE
[BREAKING CHANGE] PanelHeaderContent: переименовать status -> subtitle

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7777]
## Описание

Переименовать в компоненте PanelHeaderContent свойство status -> subtitle

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉
