### ISSUE TITLE
[BREAKING CHANGE] ModalCard: переименовать header -> title, subheader -> description

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7779]
## Описание

Нужно в компоненте ModalCardBase и ModalCard переименовать свойство header -> title, subheader -> description

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
