### ISSUE TITLE
[BREAKING CHANGE] TabbarItem: переименовать text -> label

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7780]
## Описание

В компоненте TabbarItem переименовать свойства text -> label

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
