### ISSUE TITLE
[BREAKING CHANGE] SimpleCell: переименовать expandable -> chevron

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7786]
## Описание

Необходимо переименовать свойства `expandable` -> `chevron` компонента `SimpleCell` и `Cell`

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
