### ISSUE TITLE
[BREAKING CHANGE] ScreenSpinner: переименовать caption -> label

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7789]
## Описание

В компоненте `ScreenSpinner` нужно переименовать свойство `caption` -> `label`. Также нужно не забыть про подкомпонент `ScreenSpinner.Container`, у него тоже нужно переименовать свойство

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉
