### ISSUE TITLE
[BREAKING CHANGE] CardGrid: рассмотреть возможность задепрекейтить компонент

### ISSUE THREAD

**Issue by EldarMuhamethanov** [VKCOM/VKUI#7803]
## Описание

Необходимо рассмотреть возможность задепрекейтить компонент `CardGrid`. В случае , если задепрекейтить  не получится , нужно переименовать поле `spaced` на `padding` со значением по умолчанию - "false"

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.1" target="_blank">v7.0.0-beta.1</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
