### ISSUE TITLE
[Feature][Counter]: Обновить пропы Counter

### ISSUE THREAD

**Issue by qurle** [VKCOM/VKUI#7805]
### Описание

Давайте разобьём проп каунтера `mode` на `mode` и `appearance`. Как обычно, mode будет отвечать за контрастность элемента, а appearance — за цвета. 

`mode: primary | contrast | tertiary` (простите, secondary не завезли)
`appearance: accent | neutral | accent-green | accent-red` (во многом по аналогии с [бейджом](https://vkcom.github.io/VKUI/#/ContentBadge)) 

+ хотелось бы дать возможность задавать цвет вручную (у нас это типа `appearance = custom`). Вижу два пути: через традиционные стили или через проп `color`, который будет красить фон в режиме `primary` (а цвет текста вычислять) и текст в режимах `contrast` и `tertiary`.

Текущие моды:
`inherit` → оставляем, или заменяем на `mode = undefined, appearance = undefined`
`primary` → `mode = "primary" appearance = "accent"`
`secondary` → `mode = "primary" appearance = "neutral"`
`prominent` →  `mode = "primary" appearance = "accent-red"`
`contrast`→ `mode = "contrast" appearance = "accent"`

[Макет в фигме ↗️](https://www.figma.com/design/Ofjgb91MHEW1VyAS0AZWgr/%F0%9F%9B%A0%EF%B8%8F-VKUI-Library-%5BBeta%5D?node-id=55169-3298&node-type=frame&t=jxLTtImsHKSrwO22-11)

### Скриншоты

<img width="841" alt="image" src="https://github.com/user-attachments/assets/f081176a-d0b3-4725-9cdf-1984c88eddb1">

**Comment by qurle** [comment]
Как думаете, успеем такую штуку или уже поздновато закинул?

**Comment by EldarMuhamethanov** [comment]
@qurle
> через проп color, который будет красить фон в режиме primary (а цвет текста вычислять)

Есть примерное представление, по какому принципу вычислять цвет текста? Может формула какая-то?

**Comment by qurle** [comment]
@EldarMuhamethanov
Что-то [вроде такого](https://stackoverflow.com/questions/3942878/how-to-decide-font-color-in-white-or-black-depending-on-background-color) мб? 

На самом деле тут есть вопросики к тёмной теме и работе с токенами, поэтому можно вынести в отдельную задачу и отложить до востребованности.

**Comment by EldarMuhamethanov** [comment]
> На самом деле тут есть вопросики к тёмной теме и работе с токенами, поэтому можно вынести в отдельную задачу и отложить до востребованности.

Вынести `appearance`=custom ?

**Comment by EldarMuhamethanov** [comment]
@qurle Может пока для `mode=primary` `appearance=custom` сделаем так, чтобы color менял только цвет фона?

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.2" target="_blank">v7.0.0-beta.2</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
