### ISSUE TITLE
[Bug][SplitCol]: Игнорируется style.width/maxWidth/minWidth

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#7829]
### Описание

Если передать style с width/maxWidth/minWidth в SplitCol то они будут проигнорированы в пользу пропов с таким же названием, приоритет нужно отдавать пропам, но при этом фоллбекаться на style, если они не переданы:

`width: width ?? style.width`

### Версия

6.0.0

### Скриншоты

<img width="288" alt="Снимок экрана 2024-10-24 в 20 16 56" src="https://github.com/user-attachments/assets/b6026978-a5c8-41c1-802e-79ae3a48cd84">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
