### ISSUE TITLE
[Bug]: В Gallery с timeout во время drag'а мышкой не останавливается автопереключение слайдов

### ISSUE THREAD

**Issue by pajecawav-vk** [VKCOM/VKUI#7835]
### Описание

В `Gallery` c установленным `timeout` для автопереключения слайдов во время drag'а слайда мышкой не останавливается автопереключение слайдов

https://github.com/user-attachments/assets/b74c41be-53d7-4d9a-b1f6-7397b3cdd4d7

### Версия

6.7.3

### В каких браузерах воспроизводится проблема?

Chrome

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.7.4" target="_blank">v6.7.4</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.2" target="_blank">v7.0.0-beta.2</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
