### ISSUE TITLE
[Bug][DateInput]: Ошибки связанные с id

### ISSUE THREAD

**Issue by Kritolan** [VKCOM/VKUI#7839]
### Описание

Если открыть приложение с этим компонентом, то DevTools выдаст ошибку связанную с невозможностью соотнести label и input
```
The label's for attribute doesn't match any element id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.
To fix this issue, make sure the label's for attribute references the correct id of a form field.
```

А при открытии календаря выдаст еще и 4 предупреждения, что используемые селекты в шапке не имеют id
```
A form field element has neither an id nor a name attribute. This might prevent the browser from correctly autofilling the form.
To fix this issue, add a unique id or name attribute to a form field. This is not strictly needed, but still recommended even if you have an autocomplete attribute on the same element.
```

Это вроде как не влияет на основные сценарии, но возможно повлияет на доступность, да и в целом выглядит не очень.

### Версия

6.7

### Пример с воспроизведением

https://x23fwp.csb.app

**Comment by andrey-medvedev-vk** [comment]
Действительно, это может быть проблемой!
Спасибо за пример, попробуем разобраться.

**Comment by EldarMuhamethanov** [comment]
@Kritolan зашел по ссылке с примером, в консоли не падают ошибки. Можешь перепроверить

**Comment by andrey-medvedev-vk** [comment]
У нас в `DateInput` в целом пробемы с передачей `id`, оно падает на `FormField`, а не на интерактивный элемент. А из интерактинвых у нас там один скрытый инпут и `InputLike` для маски.
Так что даже если ошибок в консоли не видно, то доступность тут явно хромает..

**Comment by Kritolan** [comment]
> @Kritolan зашел по ссылке с примером, в консоли не падают ошибки. Можешь перепроверить

Проверил - все падает. По крайней мере в Edge. Но падают не в стандартную консоль, а во вкладку проблемы. В Firefox подобного не нашел и поэтому там как будто бы ошибок и нет.

**Comment by EldarMuhamethanov** [comment]
> Проверил - все падает. По крайней мере в Edge. Но падают не в стандартную консоль, а во вкладку проблемы. В Firefox подобного не нашел и поэтому там как будто бы ошибок и нет.

Привет! Да, я не туда смотрел, теперь увидел.

Я проанализировал обе ошибки:

1. По задаче #7953 - проблему обнаружил и понимаю, как её исправить.

2. Что касается второго замечания про отсутствующие атрибуты name и id в элементах в шапке календаря:
   - Это не является проблемой доступности
   - Данные атрибуты необходимы только для элементов форм
   - Эти компоненты ни с чем не должны быть связанны
   - Следовательно, отсутствие этих атрибутов не влияет на функциональность и доступность компонента

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.1.0" target="_blank">v7.1.0</a> 🎉
