### ISSUE TITLE
[Bug]: Gallery невозможно переключать слайды если слайды спозиционированы по середине и общая ширина слайдов меньше ширины контейнера

### ISSUE THREAD

**Issue by andrey-medvedev-vk** [VKCOM/VKUI#7841]
### Описание

Если в Gallery спозиционировать слайды по центру (align="center"), и ограничить ширину так, что общая ширина слайдов меньше, чем ширина контейнера, то слайды будут по центру, но их нельзя будте ни свайпать ни переключать с помощью стрелок (не будет стрелок), проскролить ко второму элементу нельзя.

### Версия

6.5.3 - 6.7.3

### Пример с воспроизведением

[https://codesandbox.io/p/sandbox/elated-fire-vggxvh](https://vk.com/away.php?to=https%3A%2F%2Fcodesandbox.io%2Fp%2Fsandbox%2Felated-fire-vggxvh&utf=1)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.7.4" target="_blank">v6.7.4</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
