### ISSUE TITLE
[Feature][Gallery]: Возможность изменения кликабельной зоны стрелок

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#7860]
### Описание

![image](https://github.com/user-attachments/assets/38294c03-c690-483d-aa28-7c5b7bfe41da)

**Comment by qurle** [comment]
Добавляем проп, который позволяет сократить высоту кликабельной зоны стрелок
Назвал Arrows: Fill | Fit. Предложения по неймингу принимаются.

[Макет в фигме ↗](https://www.figma.com/design/Ofjgb91MHEW1VyAS0AZWgr/%F0%9F%9B%A0%EF%B8%8F-VKUI-Library-%5BBeta%5D?node-id=79439-39275&node-type=symbol&t=u1LCAIXnwiXwyOyq-11)

**Comment by inomdzhon** [comment]
> Добавляем проп, который позволяет сократить высоту кликабельной зоны стрелок Назвал Arrows: Fill | Fit. Предложения по неймингу принимаются.
> 
> [Макет в фигме ↗](https://www.figma.com/design/Ofjgb91MHEW1VyAS0AZWgr/%F0%9F%9B%A0%EF%B8%8F-VKUI-Library-%5BBeta%5D?node-id=79439-39275&node-type=symbol&t=u1LCAIXnwiXwyOyq-11)

@qurle в дизайне получится назвать **Arrow Clicable Area**? По задаче **Arrows** не соответствует семантике

+ это к разговору о сохрании консистентности названий между кодом и дизайном

**Comment by qurle** [comment]
@inomdzhon 
Я за семантическое название, но это довольно длинное. Если будут более лаконичные варики, я бы закоммитился.

**Comment by EldarMuhamethanov** [comment]
@qurle Могу предложить варианты `arrowArea`, `arrowHitbox`, `arrowZone`. Какой нравится больше?

**Comment by qurle** [comment]
@EldarMuhamethanov, крутяк
Я бы почекал, что более принято: Zone или Area, и остановился на этом варианте

**Comment by EldarMuhamethanov** [comment]
> [@EldarMuhamethanov](https://github.com/EldarMuhamethanov), крутяк Я бы почекал, что более принято: Zone или Area, и остановился на этом варианте

Я бы все-таки выбрал `arrowArea`, кажется более привычным

**Comment by EldarMuhamethanov** [comment]
@qurle Есть идеи по наименованиями значений? У меня есть парочка `'fullHeight'/'padded'`, `'stretch'/'compact'`

**Comment by qurle** [comment]
@EldarMuhamethanov 
Нет уверенности.
`'fullHeight'/'padded'` длинновато и нестандартно (тоже думал о похожем варианте). `'stretch'/'compact'` — не хочется смешивать термины из адпативности.

`Fill / Fit` или кажется нормальным, потому что нет другой трактовки + термины частично из фигмы (там есть Fill / Hug), iOS (там есть Fill Container / Hug Content) и цсс (там есть fill-available / fit-content). 

В общем,`fill, stretch, full` / `hug, fit` кажется простым и понятным. 
 Если вопрос конкретности, то можно в реакте завести проп как `arrowAreaHeight = fill / fit`.

**Comment by EldarMuhamethanov** [comment]
@qurle 
В целом идея с `arrowAreaHeight` звучит неплохо. Тогда в дизайне делаем `arrowArea`, а в коде `arrowAreaHeight` с указание, что в дизайне это `arrowArea`.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.1.0" target="_blank">v7.1.0</a> 🎉
