### ISSUE TITLE
[Bug]: Белый экран при свайпе на страницу со скроллом

### ISSUE THREAD

**Issue by ExLineP** [VKCOM/VKUI#7864]
### Описание

При SwipeBack с одной панели назад, если первая панель была проскроллена, появляется белый экран пока SwipeBack не закончится. В обратном случае свайп работает нормально и видно страницу на которую ты свайпаешь

### Версия

6.5.1

### Ожидаемое поведение

Всегда видно панель на которую ты делаешь SwipeBack

**Comment by BlackySoul** [comment]
Привет! Можно пример с воспроизведением? И указать версию iOS, на которой воспроизводится.

**Comment by vkcom-publisher** [comment]
Задача закрыта из-за отсутствия активности в течение последних 14 дней. Если это произошло по ошибке или проблема все ещё актуальна, откройте задачу повторно.
