### ISSUE TITLE
[Feature]: DateInput добавить возможность прокидивать коллбэк на onClose

### ISSUE THREAD

**Issue by andrey-medvedev-vk** [VKCOM/VKUI#7865]
### Описание

На данные момент `DateInput` в режиме `enableTime` закрывается не только при клике снаружи, но и при клике на кнопку "готово", а каждое изменение даты, времени, вызывает `onChange`.
Пользователи DateInput которым требуется вызывать запросы при изменении времени сталкиваются с проблемой, что при каждом клике в календаре у них вызываются лишние запросы.
Хотелось бы для оптимизации иметь возможность завязываться на `onClose` и вызывать запрос при закрытии календаря.

- onClose должен вызываться и при клике на "готово" и при клике снаружи.
- и в режиме `closeOnChange = false`.

Актуально и для `DateRangeInput`, так как там есть `closeOnChange`.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v6.7.4" target="_blank">v6.7.4</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0-beta.2" target="_blank">v7.0.0-beta.2</a> 🎉

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
