### ISSUE TITLE
[Feature]: DateInput добавить возможность обрабатывать нажатие кнопки "готово" в режиме "enableTime"

### ISSUE THREAD

**Issue by andrey-medvedev-vk** [VKCOM/VKUI#7866]
### Описание

Связано с https://github.com/VKCOM/VKUI/issues/7865

Стоит продумать добавление дополнительного коллбэка, который бы вызывался при клике на кнопку "Готово". Иногда требуется возможность явного действия для сохранения выбранное даты.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.1.0" target="_blank">v7.1.0</a> 🎉
