### ISSUE TITLE
[Feature]: RichCell, SimpleSell, MiniInfoCell нет возможности выравнить текст по центру имея высокий контент в after

### ISSUE THREAD

**Issue by andrey-medvedev-vk** [VKCOM/VKUI#7870]
### Описание

Используя один из компонентов `RichCell`, `SimpleCell`, `MiniInfoCell` невозможно выравнить основной текст по центру, если имеется высокий контент в `after`, при этом между `after` и контентом должен оставаться отступ какой есть у `RichCell`.

Хорошо подходит MiniInfoCell, но у него нету отступа.

Надо продумать как сделать так, чтобы это было возможно в `RichCell`, либо какие можно внести изменения в `SimpleCell`/`MiniInfoCell` чтобы не противоречить дизайну.

### Скриншоты

<img width="611" alt="Screenshot 2024-10-29 at 16 35 49" src="https://github.com/user-attachments/assets/86ef492f-65cb-476f-af70-fe8bf7566ff5">

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.1.0" target="_blank">v7.1.0</a> 🎉
