### ISSUE TITLE
[Bug]: Неверная обработка onClick внутри after компонента Cell/ SimpleCell при использовании дополнительно обработчика у самого компонента

### ISSUE THREAD

**Issue by quick6response** [VKCOM/VKUI#7873]
### Описание

```tsx
const Example = () => {
  const [activePanel, setActivePanel] = React.useState('list');
  const test = () => alert('test');
  const test1 = () => alert('test1');

  return (
    <View activePanel={activePanel}>
      <Panel id="list">
        <Group header={<Header mode="secondary">Список друзей</Header>}>
          <SimpleCell
            before={<Avatar size={48} src={getAvatarUrl('user_arthurstam')} />}
            after={
              <IconButton label="Написать сообщение" onClick={test}>
                <Icon28MessageOutline />
              </IconButton>
            }
            subtitle="Бот"
            onClick={test1}
          >
            Artur Stambultsian
          </SimpleCell>
        </Group>
      </Panel>
    </View>
  );
};

<Example />;
```

При взаимодействии с after (onClick) - вызывается дополнительно onClick у SimpleCell

### Версия

6.7.3

### В каких браузерах воспроизводится проблема?

Chrome

### Шаги воспроизведения

При взаимодействии с after (onClick) - вызывается дополнительно onClick у SimpleCe

### Ожидаемое поведение

Вызывается onClick у after, обработчик onClick у SimpleCell не вызывается - тк взаимодействие с ним не идет (даже анимации нет)

### Скриншоты

<img width="1088" alt="image" src="https://github.com/user-attachments/assets/e7f8190d-372b-4774-928e-df2d531a2dbe">
<img width="1085" alt="image" src="https://github.com/user-attachments/assets/09e9c2ea-4e76-4de0-9d8e-609053c569f7">

```[tasklist]
### Tasks
```

**Comment by BlackySoul** [comment]
Привет, это не баг, это стандартное поведение, которое мы не переопределяем. Можно об этом почитать, например, [здесь](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Event_bubbling) ([на русском](https://doka.guide/js/events/#rasprostranenie-sobytiy)). 

Поэтому возможное решение такое:

```jsx
const Example = () => {
  const [activePanel, setActivePanel] = React.useState('list');
  const test = () => alert('теперь я не всплываю');
  const test1 = () => alert('test1');
  
  const handler = (event) => {
    event.stopPropagation();
    test();
  }

  return (
    <View activePanel={activePanel}>
      <Panel id="list">
        <Group header={<Header mode="secondary">Список друзей</Header>}>
          <SimpleCell
            before={<Avatar size={48} src={getAvatarUrl('user_arthurstam')} />}
            after={
              <IconButton label="Написать сообщение" onClick={handler}>
                <Icon28MessageOutline />
              </IconButton>
            }
            subtitle="Бот"
            onClick={test1}
          >
            Artur Stambultsian
          </SimpleCell>
        </Group>
      </Panel>
    </View>
  );
};

<Example />;
```

**Comment by inomdzhon** [comment]
см. https://github.com/VKCOM/VKUI/issues/7873#issuecomment-2448988137
