### ISSUE TITLE
[Bug]: PanelHeader показывает delimeter всегда

### ISSUE THREAD

**Issue by svyatoslavpavlov** [VKCOM/VKUI#7895]
### Описание

Собственно на скрине видно. Это всевдоэлемент ::after, в параметрах вьюхи все скрыто

```
<Panel
      nav={nav}
    >
      <PanelHeader
        delimiter={"none"}
        float={true}
        shadow={false}
        transparent={true}
        before={<PanelHeaderBack onClick={backClicked} />}
      >
      </PanelHeader>
      <Group
        separator={"hide"}
      >
        {children}
      </Group>
    </Panel>
```

<img width="1419" alt="image" src="https://github.com/user-attachments/assets/4c2aad88-aed0-4276-9d6d-8188d0bfde3c">

### Версия

6.7.2

### В каких браузерах воспроизводится проблема?

Chrome

**Comment by svyatoslavpavlov** [comment]
на мобилке, кстати, все окей
проблема только на десктопе

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.1" target="_blank">v7.0.1</a> 🎉
