### ISSUE TITLE
Switch(getRootRef) не работает

### ISSUE THREAD

**Issue by paveleremin** [VKCOM/VKUI#790]
```jsx
<Switch
  getRootRef={(ref) => {
    console.log('getRootRef', ref);
  }}
  getRef={(ref) => {
    console.log('getRef', ref);
  }}
/>
```
При рендере вы НЕ увидите в консоле
getRootRef
Но увидите
getRef

**Comment by ArthurStam** [comment]
Вот тут вижу оба сообщения https://codesandbox.io/s/vkui-boilerplate-f7rgk

**Comment by paveleremin** [comment]
@ArthurStam вот здесь воспроизводится https://codesandbox.io/s/vkui-boilerplate-tsj6s

**Comment by ArthurStam** [comment]
Подтверждаю, баг в коде Tooltip. Поправим, спасибо.

**Comment by ArthurStam** [comment]
Закрываю эту таску, потому что появилась более общая, которая про это же #892
