### ISSUE TITLE
[Bug]: Card hover неправильно отрабатывает

### ISSUE THREAD

**Issue by svyatoslavpavlov** [VKCOM/VKUI#7900]
### Описание

При использовании CardScroll c ContentCard с разным наполнением высота карточек одинаковая (что отлично), а вот у состояния hover высота разная 
<img width="583" alt="image" src="https://github.com/user-attachments/assets/030dc05c-5587-445d-984f-3340a7c7c9fc">

```
<CardScroll>
        {suggestions
          .map((item, i) => <ContentCard
            key={i}
            hasActive={true}
            hasHover={true}
            onClick={() => selectPlace(item.vk_city_id, item.city, item.place)}
            mode="tint"
            text={item.city}
            caption={item.place}
          />)}
      </CardScroll>
```

### Версия

6.7.2

### В каких браузерах воспроизводится проблема?

Chrome

### Ожидаемое поведение

Ожидаю, что высота ховера будет равна высоте карточки

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.1" target="_blank">v7.0.1</a> 🎉
