### ISSUE TITLE
[Bug][CustomScrollView]: Не пересчитывается состояние компонента при изменении children

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#7904]
### Описание

Если в children CustomScrollView передать контент, меньше высоты самого CustomScrollView, а потом поменять на контент который по высоте выше CustomScrollView, то его состояние отображения скроллбара не будет пересчитано. Происходит это из-за height: 100% на box-content элементе:

<img width="1277" alt="Снимок экрана 2024-11-06 в 19 25 03" src="https://github.com/user-attachments/assets/48c939c7-e154-44f8-ac17-1f420337e087">

<img width="1295" alt="Снимок экрана 2024-11-06 в 19 25 37" src="https://github.com/user-attachments/assets/db33f900-848c-4be2-be2d-b8ee8efd82cd">

для перерасчета используется iframe, который растягивается на всю высоту box-content, так как контент вложенный в children меньше чем сама высота box-content, то высоту iframe это также не аффектит, перерасчет не триггерится. 

Для решения этой проблемы можно заменить стили box-content на:
```
height: fit-content;
max-height: 100%;
```

### Версия

6.5.4

### Скриншоты

https://github.com/user-attachments/assets/ffa7fad1-1bbd-4245-a911-82fe78a6d46a

**Comment by inomdzhon** [comment]
В задачей #7699 мы перешли на нативный скроллбар, в **v7.0.0** этой проблемы не будет

До обновления как воркэраунд можно перебить стили на своей стороне 

Допустимо? Или нужен хотфикс в **v6**?

**Comment by MrZillaGold** [comment]
Норм, мы на своей стороне переопределили стили, в 6 версию фикс можно не заносить
