### ISSUE TITLE
Как покрасить определённую панель?

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#792]
Есть задачка покрасить две панели.

Раньше панели можно было красить через id.

```
#order {
    background: red !important;
}
```

Теперь это не работает. Через js так себе красить

**Comment by ArthurStam** [comment]
В 3-й версии так точно нельзя. Можно покрасить `.Panel__in`, но отдельно придется разбираться с `.PanelHeader`. Ещё можно на уровне панели переопределить переменную `--background_content`, но не факт, что эта переменная только для фона панели используется.

**Comment by ilyapishchulin** [comment]
Я знаю как перекрасить все панели в один цвет, мне нужно #order в красный, а #home в зеленый

**Comment by ArthurStam** [comment]
Я ж говорю, на уровне #order переопределяешь переменную и должно работать.

**Comment by ilyapishchulin** [comment]
Чет не сработало :(

**Comment by ArthurStam** [comment]
https://codesandbox.io/s/vkui-boilerplate-wexng

**Comment by ilyapishchulin** [comment]
Воу, спасибо, а можно еще вопрос?

Зону эластик скролла вообще реально перекрасить?

**Comment by ArthurStam** [comment]
Какие-то браузеры это позволяют, можно легко нагуглить. Но это уже к либе не относится)

**Comment by ilyapishchulin** [comment]
Разве? VKUI же красит в свой цвет
