### ISSUE TITLE
[Feature]: Добавить поддержку RTL в компонент UsersStack

### ISSUE THREAD

**Issue by vasartam** [VKCOM/VKUI#7941]
### Описание

На данный момент компонент UsersStack не поддерживает вывод изображений в RTL языках. Выглядит это таким образом:

<img width="48" alt="image-2024-11-03-12-20-41-914_crop" src="https://github.com/user-attachments/assets/d4afb4d3-8c9b-45bb-8f02-157f7a017351">

Хочется сделать так, чтобы в RTL языках UsersStack выводился так же корректно, как и в LTR:

![image-2024-11-03-12-23-07-884_crop](https://github.com/user-attachments/assets/d4da267a-aefb-49af-a4a6-50993fff0722)

Как временное решение @inomdzhon предлагает обернуть компонент в элемент с атрибутом `dir="ltr"`:
```html
<div dir="ltr"> <UsersStack /> </div>
```

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.1.0" target="_blank">v7.1.0</a> 🎉
