### ISSUE TITLE
[Bug]: Неправильная role у SegmentedControl при использовании в качестве табов

### ISSUE THREAD

**Issue by MazheM** [VKCOM/VKUI#7952]
### Описание

В документации по SegmentedControl указано, что он может использоваться для навигации в качестве Tabs, но при этом нет возможности указать в каком качестве используется компонент со стороны доступности.
Для обертки нужна роль tablist, а для элементов tab в случае использования в качестве табов

### Версия

6.7.4

### В каких браузерах воспроизводится проблема?

Firefox, Chrome, Safari, Microsoft Edge, Yandex Browser

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.1.0" target="_blank">v7.1.0</a> 🎉
