### ISSUE TITLE
Не выезжает клавиатура на iOS при вызове focus для Search

### ISSUE THREAD

**Issue by igorpost92** [VKCOM/VKUI#796]
На iOS не открывается клавиатура при первом вызове focus. Хотя анимация появляется, выезжает кнопка Отменить. При последующих ок.

```
import React, { useEffect, useRef } from 'react';
import { render } from 'react-dom';
import { Search } from '@vkontakte/vkui';
import bridge from '@vkontakte/vk-bridge';
import '@vkontakte/vkui/dist/vkui.css';

const App = () => {
  const inputRef = useRef();

  useEffect(() => {
    setTimeout(() => {
      console.log('focus');
      inputRef.current.focus();
    }, 2000);
  }, []);

  return (
    <div style={{ marginTop: 200 }}>
      <Search getRef={inputRef} />

      <div style={{ marginTop: 50 }}>
        <button onClick={() => inputRef.current.focus()}>focus</button>
      </div>
    </div>
  );
};

render(<App />, document.getElementById('root'));
bridge.send('VKWebAppInit', {});
```

**Comment by ArthurStam** [comment]
Это известная [проблема](https://medium.com/@brunn/autofocus-in-ios-safari-458215514a5f) на iOS, когда поле подсвечивается, но клавиатура не выезжает. Постараемся придумать решение. Пока рекомендую прокинуть в `Search` `getRef` и вызвать снаружи `focus()`

**Comment by igorpost92** [comment]
Я ведь так и делаю в примере

**Comment by ArthurStam** [comment]
И правда. Поресерчив проблему, я пришел к невеселому выводу.

1. Пока пользователь не начнет взаимодействовать со страницей, автофокуса не произойдет.
2. Допустим, поиск находится на второй панели. Тогда пользователю придется повзаимодействовать со страницей и при переходе на поиске сработает фокус, но это будет сопровождаться отвратительным скроллом (еще одна особенность iOS)
3. Если убрать autoFocus и в onTransition дожидаться завершения перехода, а после вызывать фокус программно, то выедет только клавиатура, но фокуса на самом деле не произойдет.

Пока что без понятия, что мы тут можем со своей стороны сделать.

**Comment by SergeyTrushin** [comment]
@ArthurStam 
Привет! Заметил что на странице логина у ВК сейчас срабатывает фокус и выезжает клавиатура без взаимодействия пользователя со страницей. Не подскажешь - как обошли ограничение на ios?

![image](https://github.com/user-attachments/assets/f9e630bb-488d-431a-8228-09fb39beb282)
