### ISSUE TITLE
[Feature]: Кастомизация кнопки в Calendar

### ISSUE THREAD

**Issue by qurle** [VKCOM/VKUI#7968]
Давайте добавим возможность менять кнопку в календаре.
Может, слотом или пропом. Минимальное, что надо — возможность сделать её акцентной.

В фигме можно просто менять пропы кнопки внутри календаря.

![image](https://github.com/user-attachments/assets/b464ea48-6b03-4bd1-82d2-74c8a574ba23)

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.1.0" target="_blank">v7.1.0</a> 🎉
