### ISSUE TITLE
[Feature]: Добавить возможность управления с клавиатуры пикером времени в Calendar

### ISSUE THREAD

**Issue by anatrobina** [VKCOM/VKUI#7997]
### Описание

Хочется иметь возможность при раскрытии пикера времени в календаре - вводить время на клавиатуре, и чтобы автоматом в пикере выбиралось нужное число, далее нажать Enter, и время выбралось. Далее можно автоматический переход к минутам и ту же логику с вводом с клавиатуры и Enter.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.1.0" target="_blank">v7.1.0</a> 🎉
