### ISSUE TITLE
[Bug]При изменении panel, panelheader появляется по середине

### ISSUE THREAD

**Issue by aloky** [VKCOM/VKUI#804]
**Описание**
При изменении panel, panelheader появляется по середине

**Шаги воспроизведения**
View => Panel[1] и внутри панель в `componentDidMount` запускать подгрузку данных, и когда Panel[1 - тут надо пролистать ниже по списку] меняется на другой т.е. на Panel[2] и нажимает обратно в Panel[1] вот и производится баг

**Ожидаемое поведение**
PanelHeader не появляется по середине, а фиксирован как обычно

**Скриншоты**
[Скриншоты](https://imgur.com/a/J2Xfx9B)

**Comment by fedorov-xyz** [comment]
Привет. Можно увидеть код такого поведения?
Обычно такое может случаться, если шапка рисуется с какими-то отступами.

**Comment by aloky** [comment]
@fedorov-xyz Привет,

`app.js`
```javascript
<View activePanel={this.state.activePanel}>
  <Home id='home' go={this.go} />
  <NewGame id='new-game' go={this.go} />
</View>
```

Получается при переходе назад в Home.js происходит запрос за данными и такой баг
Home.js
```javascript
componentDidMount() {
    this.getGames();
  }
```
Home.js
```javascript
<Panel id={this.id}>
<PanelHeader>Поиск игроков</PanelHeader>
<Group
  header={<Header
    aside={filteringGames.length > 5 && <Link>Показать все</Link>}
    mode="primary">Игры</Header>
  }
>
  {items.slice(0, 5).map((item) =>
    <SimpleCell
      key={item.id}
      before={<Avatar mode="app" src='' />}
      description={item.description}
    >
      {item.title}
    </SimpleCell>
  )}
</Group>
</Pane>
```

**Comment by ArthurStam** [comment]
У вас при перехода из Home высота панели имеет ненулевое значение, так как в ней отрисован контент. При переходе обратно, данных еще нет, поэтому высота не соответствует первоначальному значению. Отсюда и скачок. Вам нужно кэшировать данные Home.js, чтобы при переходе обратно высота была той же, что после первоначального запроса данных.

**Comment by aloky** [comment]
@ArthurStam Спасибо за ответ, но и так понятно, что надо кешировать данные, но таких проблем у других ui библиотек нет таких проблем, если считаете это не исправить, ок. Тогда закрываю.
