### ISSUE TITLE
[Doc]: добавить единообразное описание для свойств, отвечающих за прокидвание `data-testid`

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#8041]
### Описание

Нужно переписать описание `<name>TestId` в компонентах.

**Шаблон:** _Передает атрибут `data-testid` для <кого>_

> **Пример**
>
> ```ts
> type AlertProps = {
>   /**
>    * Передает атрибут `data-testid` для кнопки закрытия
>    */
>   dismissButtonTestId?: string;
> };
> ```

Также стоит добавить эту инфу в `docs/CONTRIBUTING.md`, чтобы это стало как **code convension**.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.1.0" target="_blank">v7.1.0</a> 🎉
