### ISSUE TITLE
[Bug] File не изменяется текст кнопки

### ISSUE THREAD

**Issue by kpachbiu88** [VKCOM/VKUI#805]
**Описание**
В компоненте <File> не выводится строка с числом выбранных файлов в строке  {`Выбрано ${Photos.length}  файлов`}

**Пример с воспроизведением**
```
import React, { useState } from "react";
import ReactDOM from "react-dom";
import { View, Panel, PanelHeader, Group, Header, File } from "@vkontakte/vkui";
import "@vkontakte/vkui/dist/vkui.css";

const App = () => {
  const [Photos, setPhotos] = useState([]);

  const handler = e => {
    const files = [...e.target.files];
    setPhotos(files);
  };

  return (
    <View activePanel="main">
      <Panel id="main">
        <PanelHeader>VKUI</PanelHeader>
        <Group header={<Header mode="secondary">Items</Header>}>
          <File
            multiple
            mode={Photos.length > 0 ? "primary" : "secondary"}
            top="Фотографии"
            controlSize="l"
            onChange={handler}
          >
            {`Выбрано ${Photos.length}  файлов`}
            {Photos.length}
          </File>
        </Group>
      </Panel>
    </View>
  );
};

ReactDOM.render(<App />, document.getElementById("root"));
```

**Comment by fedorov-xyz** [comment]
Привет. У меня не воспроизводится – https://codesandbox.io/s/vkui-boilerplate-jo6wl

**Comment by kpachbiu88** [comment]
Посмотрите пожалуйста, видео (во вложении), строка Выбрано 0 файлов, не меняется.

[https://yadi.sk/i/rvWW2g6TCWn7dA](url)

**Comment by ArthurStam** [comment]
Скопировал пример из последнего комментария. Всё работает. https://codesandbox.io/s/vkui-boilerplate-x7quu

**Comment by kpachbiu88** [comment]
> Скопировал пример из последнего комментария. Всё работает. https://codesandbox.io/s/vkui-boilerplate-x7quu

https://codesandbox.io/embed/vkui-boilerplate-99sdn?fontsize=14&hidenavigation=1&theme=dark
