### ISSUE TITLE
[Bug]: vkui 7.0.0 conflict with vk-mini-apps-router 1.7.0

### ISSUE THREAD

**Issue by kpachbiu88** [VKCOM/VKUI#8059]
### Описание

@vkontakte/vkui@7.0.0 conflict with @vkontakte/vk-mini-apps-router@1.7.0

Can you release fix?

![image](https://github.com/user-attachments/assets/bb8d5ed8-cde8-4d3b-9517-23c0bec2ea84)

### Версия

7.0.0

**Comment by pasha-nikitin-2003** [comment]
Исправлено в "@vkontakte/vk-mini-apps-router" в версии 1.7.1
