### ISSUE TITLE
[Feature] Добавлять реакцию на тап только если есть props onClick

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#806]
Сейчас RichCell и Cell имеют анимацию нажатия без прокидывания пропса onClick, предлагаю изменить данное поведение

**Comment by ArthurStam** [comment]
Я не согласен) У Button, например, то же поведение — они визуализируют тап без проброса onClick. Это же поведение можно встретить в нативном вебе. Всё кликается до тех пор, пока не передан disabled. Мы придерживаемся того же подхода.
