### ISSUE TITLE
[Feature][AspectRatio]: добавить возможность принимать string в свойстве `ratio`

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/VKUI#8064]
### Описание

Есть потребность передавать строку в свойство, например, для передачи CSS переменной `var(--<name>)`, `calc(<value>)` или `<value><unit>`.

```diff
export interface AspectRatioProps extends Omit<RootComponentProps<HTMLElement>, 'baseClassName'> {
-  ratio: number;
+  ratio: number | string;
}
```

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.1.0" target="_blank">v7.1.0</a> 🎉
