### ISSUE TITLE
[Bug]: Код компонента модальной страницы выполняется, даже когда модальная страница не отображается.

### ISSUE THREAD

**Issue by pasha-nikitin-2003** [VKCOM/VKUI#8065]
### Описание

Обнаружена проблема, при которой код React компонента модальной страницы VKUI продолжает выполняться (включая эффекты, обработчики событий и т.д.), даже когда модальная страница не отображается на экране пользователя. 

У меня в приложении [есть модальная страница, которая блокирует навигацию пользователя](https://github.com/VKCOM/vk-mini-apps-router/blob/master/examples/vk-mini-apps-router-example/src/modals/BlockerModal.tsx) через [vk-mini-apps-router](https://github.com/VKCOM/vk-mini-apps-router).
Сейчас при запуске приложения, весь интерфейс блокируется при входе, потому что код страницы почему-то начинает выполняться.

Эта проблема была выявлена при попытке провести интеграцию  [vk-mini-apps-router](https://github.com/VKCOM/vk-mini-apps-router) с @vkontakte/vkui 7.0 (#8059)

### Версия

7.0.0

### Шаги воспроизведения

1. Открыть [песочницу](https://vkcom.github.io/VKUI/#/ModalRoot)
2. Вставить console.log в DynamicModalPage
3. console.log начнет вызываться постоянно

### Ожидаемое поведение

log будет вызываться, только при открытой модальной странице.

**Comment by inomdzhon** [comment]
Из-за того, что `ModalRoot` теперь создаёт лишь контекст и не управляет `children`'ом через `React.cloneElement`, обёртки над `ModalPage` и `ModalCard` остаются всегда примонтированными.

<details><summary>Вот как нужно переписать BlockerModal, чтобы исправить проблему</summary>
<p>

```tsx
import { useCallback, useEffect, useRef } from 'react';

import {
  Button,
  FormItem,
  FormLayoutGroup,
  Input,
  ModalPage,
  ModalPageHeader,
} from '@vkontakte/vkui';

import { BlockerFunction, useRouteNavigator } from '@vkontakte/vk-mini-apps-router';
import { NavProp } from '../types';

const PASSWORD = '1234';

const ModalContent = () => {
  const routeNavigator = useRouteNavigator();
  const unblock = useRef<() => void>();
  const passInput = useRef<HTMLInputElement>(null);

  const blockerFn = useCallback<BlockerFunction>(
    ({ currentLocation, nextLocation, historyAction }) => {
      console.log('Current location', currentLocation);
      console.log('Next location', nextLocation);
      console.log('historyAction', historyAction);

      return true;
    },
    [],
  );

  useEffect(() => {
    unblock.current = routeNavigator.block(blockerFn);
  }, [routeNavigator, blockerFn]);

  const onHandleSubmit = () => {
    const unblockFn = unblock.current;
    const inputElement = passInput.current;

    if (inputElement && unblockFn && inputElement.value === PASSWORD) {
      unblockFn();
      routeNavigator.back();
    }
  };

  return (
    <FormLayoutGroup>
      <FormItem top={`Код разблокировки ${PASSWORD}`}>
        <Input getRef={passInput} id="pass" type="password" placeholder={PASSWORD} />
      </FormItem>

      <FormItem>
        <Button type="submit" onClick={onHandleSubmit} size="l" stretched>
          Применить код
        </Button>
      </FormItem>
    </FormLayoutGroup>
  )
}

export const BlockerModal = (props: NavProp) => {
  return (
    <ModalPage id={props.nav} header={<ModalPageHeader>Разблокируйте навигацию!</ModalPageHeader>}>
      <ModalContent />
    </ModalPage>
  );
};
```

</p>
</details> 

Тоже самое относится к другим подобным обёрткам, логика которых должна быть размонитрована.

---

В документации по миграции не учтён такой кейс – поправлю. Спасибо за issue 🙏
