### ISSUE TITLE
[Bug] Поведение ModalPage

### ISSUE THREAD

**Issue by NicegrinL** [VKCOM/VKUI#809]
**Описание**
Пропадает SHADOW (серая панель заднего плана), блокируется перемещение.
Наблюдается как на десктопе так и в мобильной версии, Очень проблематично работать с формой мышью. Она не слушается. Пользователей это будет раздражать.

**Шаги воспроизведения**
После показа если ее поднять немного и потом опустить, то пропадает SHADOW поверх изначального экрана, если потом еще пару подобных манипуляций и опустить ее обратно, то оно вообще фиксируется в нижней части экрана и больше ни вверх ни вниз не двигается

**Ожидаемое поведение**
Опционально, если считаете, что из описания ожидаемое поведение понятно.

**Скриншоты**
![k-3NRs0jkek](https://user-images.githubusercontent.com/66645901/84078375-7c844380-a9e1-11ea-953d-ba6102b983e0.jpg)

**Пример с воспроизведением**
Можно сделать форк отсюда https://codesandbox.io/s/vkui-boilerplate-oj149. Сильно ускоряет поиск причин проблемы.
форк сделать не получается, так как там даже элементарный код не работает:

import React from "react";
import ReactDOM from "react-dom";
import { View, Panel, PanelHeader, Group, FormLayout } from "@vkontakte/vkui/";
import "@vkontakte/vkui/dist/vkui.css";
import Button from "@vkontakte/vkui/";

/*
class App extends React.Component {
  render() {
    return (
      <View activePanel="modals">
        <Panel id="modals">
          <PanelHeader>Модальные окна</PanelHeader>
          <Group>
            <FormLayout>
              <Button mode="secondary">dd</Button>
              <Button mode="secondary">dd</Button>
            </FormLayout>
          </Group>
        </Panel>
      </View>
    );
  }
}

ReactDOM.render(<App />, document.getElementById("root"));
*/

**Comment by NicegrinL** [comment]
`import React from "react";
import ReactDOM from "react-dom";
import { View, Panel, PanelHeader, Group, FormLayout } from "@vkontakte/vkui/";
import "@vkontakte/vkui/dist/vkui.css";
import Button from "@vkontakte/vkui/";

class App extends React.Component {
  render() {
    return (
      <View activePanel="modals">
        <Panel id="modals">
          <PanelHeader>Модальные окна</PanelHeader>
          <Group>
            <FormLayout>
              <Button mode="secondary">dd</Button>
              <Button mode="secondary">dd</Button>
            </FormLayout>
          </Group>
        </Panel>
      </View>
    );
  }
}

ReactDOM.render(<App />, document.getElementById("root"));
`

**Comment by ArthurStam** [comment]
Привет. Библиотека пока не адаптирована под десктоп и мышь. Нужен пример с воспроизведением, где описанные проблемы наблюдаются на мобильных устройствах. Ваш пример неясно как использовать, там невалидный код.

**Comment by ArthurStam** [comment]
Закрываю за отсутствием активности
