### ISSUE TITLE
[Bug] iOS Swipe Back

### ISSUE THREAD

**Issue by NicegrinL** [VKCOM/VKUI#810]
**Описание**
Работает в браузере. не работает в клиенте ВК. 

**Шаги воспроизведения**
Просто прописать минимальный код из оф примера

class App extends React.Component {

	state = {
	  activePanel: 'main',
	  history: ['main']
	}
  
	goBack = () => {
	  const history = [...this.state.history];
	  history.pop();
	  const activePanel = history[history.length - 1];
	  if (activePanel === 'main') {
		vkBridge.send('VKWebAppDisableSwipeBack');
	  }
	  this.setState({ history, activePanel });
	}
  
	goForward = (activePanel) => {
	  const history = [...this.state.history];
	  history.push(activePanel);
	  if (this.state.activePanel === 'main') {
		vkBridge.send('VKWebAppEnableSwipeBack');
	  }
	  this.setState({ history, activePanel });
	}
  
	render () {
	  return (
		<ConfigProvider isWebView={true}>
		  <View
			onSwipeBack={this.goBack}
			history={this.state.history}
			activePanel={this.state.activePanel}
		  >
			<Panel id="main">
				<CellButton 
					onClick={
							() => this.setState
								(
									{
										activePanel: "profile", 
										history: [...this.state.history, "profile" ]
									}
								)
						}
				>
				Panel1
				</CellButton>
			</Panel>
			<Panel id="profile">Panel2</Panel>
		  </View>
		</ConfigProvider>
	  )
	}
  }

**Скриншоты**
Опционально.

**Comment by ArthurStam** [comment]
Из тикета непонятно, в чем проблема. Мы используем свайп бэк во всех наших приложениях и проблем не наблюдаем.

**Comment by ArthurStam** [comment]
Закрываю за отсутствием активности
