### ISSUE TITLE
[Bug] Дергается скролл при переходе между панелями

### ISSUE THREAD

**Issue by IlyaSteik** [VKCOM/VKUI#815]
При переходе на новую панель, (при этом на старой панели положение скрола внизу), и возвращении назад, положение скрола ставится наверх, и через некоторое время резко перемещается вниз.
Проблему можно наблюдать на видео - https://vk.com/video245481845_456240561

**Comment by SkyGopnik** [comment]
Предполагаю что это происходит из за загрузки контента на главном экране.

**Comment by ArthurStam** [comment]
Привет. Без примера на https://codesandbox.io/s/vkui-boilerplate-oj149 помочь не сможем. Скорее всего проблема в том, что изначально панель рисуется с пустым контентом.

**Comment by IlyaSteik** [comment]
Да, действительно в этом причина. Спасибо.
