### ISSUE TITLE
[Feature] Простой селектор у Tappable

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#816]
Сейчас имеется 2 стиля для каждой из платформ:

https://github.com/VKCOM/VKUI/blob/d0c1d133340d2a94b34ab1075da963f2bf933c38/src/components/Tappable/Tappable.css#L11-L14

https://github.com/VKCOM/VKUI/blob/d0c1d133340d2a94b34ab1075da963f2bf933c38/src/components/Tappable/Tappable.css#L24-L26

И их переопределение задача не из тех, с которыми, ты ожидаешь столкнуться.
Тут и специфичность селектора большая, так и ещё правило с `!important`

**Comment by ArthurStam** [comment]
Привет, да, это общая боль. Избавимся от неё после релиза v4

**Comment by ArthurStam** [comment]
Избавились: #1381
