### ISSUE TITLE
[Feature] Избавиться от Legacy Context

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#817]
Сейчас, если использовать [React Strict Mode](https://reactjs.org/docs/strict-mode.html), то сыпятся предупреждения/ошибки об использовании устаревшего API.

Это относится к [ConfigProvider](https://github.com/VKCOM/VKUI/blob/4dfe4d590d60013bc8c16f2284818d46427fe53c/src/components/ConfigProvider/ConfigProvider.tsx#L76) и [Epic](https://github.com/VKCOM/VKUI/blob/5f4a64ccc0c213d83e91a1cd7f579c538ae943bd/src/components/Epic/Epic.tsx#L18)

**Comment by ArthurStam** [comment]
Привет, спасибо, поправим после релиза v4

**Comment by eolme** [comment]
@ArthurStam, есть новости?

**Comment by NekR** [comment]
В этом году сделаем.

**Comment by eolme** [comment]
@NekR, звучит как мем

**Comment by ewgenius** [comment]
legacy context был убран в #1282
