### ISSUE TITLE
[Feature] Добавить св-во для Snackbar

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#819]
Хотелось бы видеть св-во у Snackbar которое отключает его Padding снизу, т.к. например если его вызвать в модалке, то он будет думать что снизу всё ещё находится Tabbar, если Tabbar банально скрыть в панели, то он всё равно будет подниматься на её высоту, что приходится решать руками.
Пример фикса - https://imgur.com/a/6ChEs7V

**Comment by ArthurStam** [comment]
Привет. Спасибо, поправим, но не путем добавления нового свойства.

**Comment by ArthurStam** [comment]
MR фиксит проблему, когда Snackbar внутри модалки. В панелях мы запрещаем скрывать Tabbar, в [документации](https://vkcom.github.io/vkui-styleguide/#!/Epic) написано почему, поэтому там мы фиксить эту проблему не планируем.

**Comment by SkyGopnik** [comment]
Не соглашусь с вашим подходом то что таббар должен быть всегда, во первых обычно в начале приложения есть инструкция в которой описывается что и для чего приложения, в нём не должно быть таббара, это лишний компонент. Во вторых допустим я хочу открыть панель с ОБЯЗАТЕЛЬНЫМИ правилами для ознакомления, в нём тоже не должно быть таббара. Я думаю таких случаев может быть много и вы должны давать волю разработчикам, а не подминать их под свои рамки, мы же всё таки любители нестандартных решений)

**Comment by ArthurStam** [comment]
Вообще у нас есть тикет для скрытия таббара, но это история следующих мажорных версий. Пока мы пошли на упрощение и делаем таббар обязательным. В рамках текущего тикета фикисть это не планируем. Инструкцию всегда можно отрисовать отдельной View за пределами Epic.
