### ISSUE TITLE
[Bug] Не растягивается контент внутри Panel на всю высоту

### ISSUE THREAD

**Issue by jellyb0y** [VKCOM/VKUI#821]
**Описание**
Не растягивается контент внутри Panel на всю высоту
Из-за неправильного [свойства](https://github.com/VKCOM/VKUI/blob/d11d361d90e4e38d0746338ccb1058db40ba241f/src/components/Panel/Panel.css#L32)

**Шаги воспроизведения**
Создаём внутри Panel любой div со свойством height: 100%
Получаем следующее:
https://cloud.mail.ru/public/M3CR/F2vPQVP2A
https://cloud.mail.ru/public/DjMF/Wdh5NWzu7

**Ожидаемое поведение**
Заменить свойство `min-height: 100%` (Оно здесь явно лишнее) на `height: 100%`
Тогда можно будет делать контент с фиксированной максимальной высотой

**Comment by ArthurStam** [comment]
Фикс min-height на height сломает скролл.
