### ISSUE TITLE
[Bug] Modal, ModalPage не раскрывается во всю высоту

### ISSUE THREAD

**Issue by b-ponomarenko** [VKCOM/VKUI#822]
**Описание**
Если высота контента меньше высоты экрана устройства, то нижняя часть модальной страницы обрезается

**Шаги воспроизведения**
Добавить <ModalPage /> на страницу и добавить произвольный контент, который занимает не всю высоту

**Ожидаемое поведение**
Если контент занимает меньше отведенной 

**Скриншоты**
[картинка](https://ibb.co/vJsyR8z)

**Пример с воспроизведением**
https://codesandbox.io/s/vkui-boilerplate-c2cg5

**Comment by royroev** [comment]
подтверждаю, нужен фикс

**Comment by gbowsky** [comment]
Баг был в третьей версии, в codesandbox с актуальными версиями не воспроизвелось.
