### ISSUE TITLE
[Feature] Оптимизация определения типа устройства в V4

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#824]
1.  Предлагаю использовать [window.matchMedia](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia), который в отличие от `window.innerWidth` не приводит к forced reflow

2. Повесить throttle/debounce на обработчик события изменения размера окна

**Comment by ArthurStam** [comment]
Привет, спасибо, в v4 ещё многие штуки будут переделываться, в том числе то, о чём ты написал

**Comment by NekR** [comment]
Нужны с начала показания, что innerWidth приводит к проблемам в данном кейсе.

**Comment by eolme** [comment]
Ну как минимум, как в issue написано - `innerWidth` вызывает перерисовку в браузере.

Также с методом `VKWebAppResizeWindow` вызывается `resize` у окна.

На mvk бывает `resize`,  например, если само окно скроллится (бывает плашка сверху появляется "установите приложение")

**Comment by inomdzhon** [comment]
Речь идёт о каком-то конкретном компоненте?

**Comment by eolme** [comment]
Вспомнить бы, помню только, что была проблема в reflow на каждый ререндер.

**Comment by NekR** [comment]
Само по себе дёрганье `innerWidth` не вызывает layout, если перед ним ничего не менять. То есть, если на каждый ресайз у тебя пересчитывается layout, значит где-то в приложении ты на каждый ресайзс что-то меняешь.

**Comment by inomdzhon** [comment]
По коду, помимо `innerWIdth`, много других обращений к св-ам HTMElement, которые могут вызвать reflow.
Мы ещё используем `popperjs`, который внутри обмазан получением размеров элемента и координат, поэтому первый пункт сделать можно, но при этом от хака с `reflow` это полностью не избавит

---

Второй пункт, про повесить `throttle/debounce`, на определённо нужен. Возможно не везде. На `"resize"` точно стоит повесить. Вот здесь можно было бы завести https://github.com/VKCOM/vkjs эти декораторы. Что думаете?

**Comment by fedorov-xyz** [comment]
Они уже есть в vkjs: https://github.com/VKCOM/vkjs/blob/master/src/functions.ts

**Comment by inomdzhon** [comment]
Ааа, тогда круть
Я искал в директории `debounce.ts` 😅

**Comment by inomdzhon** [comment]
Ой, в репе VKUI они тоже есть оказывается
- [debounce](https://github.com/VKCOM/VKUI/blob/master/src/lib/utils.ts#L20)
- [nopp](https://github.com/VKCOM/VKUI/blob/master/src/lib/utils.ts#L78)

надо будет реэкспортнуть из vkjs

**Comment by NekR** [comment]
> По коду, помимо innerWIdth, много других обращений к св-ам HTMElement, которые могут вызвать reflow.
Мы ещё используем popperjs, который внутри обмазан получением размеров элемента и координат, поэтому первый пункт сделать можно, но при этом от хака с reflow это полностью не избавит

Тогда ещё поппера не было в VKUI, но да, суть в том что куча всегда может вызывать layout.

**Comment by pfrankov** [comment]
Для v5 будет неактуально — там window.matchMedia будет заменён на CSS Media Queries
