### ISSUE TITLE
Ненадолго появляется горизонтальный скролл-бар в сервисах на версии 3.0+

### ISSUE THREAD

**Issue by R-o-t-I** [VKCOM/VKUI#828]
При запуске сервиса 3.0+ ненадолго появляется горизонтальный скролл-бар.
![1592767944083](https://user-images.githubusercontent.com/49370598/85233648-90cc3580-b410-11ea-9450-64f55046db26.jpg) вот, например, запуск подкастов.

**Comment by ArthurStam** [comment]
Спасибо, посмотрим

**Comment by ArthurStam** [comment]
Увидел это только в подкастах. В других прилках такого не обнаружил. Думаю, проблема у ребят, а не в либе.
