### ISSUE TITLE
[Bug]Проблема с Tabs и TabsItems на iOS при FixedLayout vertical="bottom"

### ISSUE THREAD

**Issue by NicegrinL** [VKCOM/VKUI#831]
**Описание**
Не отрисовываются элементы TabsItem на iOS если задано фиксированное расположение внизу экрана

**Шаги воспроизведения**
Создать 2 панели и Tabs и 2 tabsitem

**Ожидаемое поведение**

**Скриншоты**
Опционально.

**Пример с воспроизведением**
`
import React, { useState, useEffect } from 'react';
import bridge from '@vkontakte/vk-bridge';
import View from '@vkontakte/vkui/dist/components/View/View';
import ScreenSpinner from '@vkontakte/vkui/dist/components/ScreenSpinner/ScreenSpinner';
import '@vkontakte/vkui/dist/vkui.css';
import { Div, Panel, Tabs, TabsItem ,HorizontalScroll, FixedLayout} from '@vkontakte/vkui';
class App extends React.Component {
	
	constructor (props) 
	{
		super(props);
	
		this.state = {
			activePanel : "pnl_orders"
		}
	}

	render()
	{
		return (
			<View
				activePanel={this.state.activePanel}
			>
				<Panel
					id="pnl_orders"
				>
					<Div>
						orders...		
					</Div>
					<FixedLayout
						vertical="top"
					>
						<Tabs>
							<HorizontalScroll>
								<TabsItem	onClick={() => this.setState({ activePanel: 'pnl_orders' })}
											selected={this.state.activePanel == 'pnl_orders'}
								>
									Заказы								
								</TabsItem>
								<TabsItem	onClick={() => this.setState({ activePanel: 'pnl_comments' })}
											selected={this.state.activePanel == 'pnl_comments'}
								>
									Комментарии
								</TabsItem>
							</HorizontalScroll>
						</Tabs>
					</FixedLayout>					
				</Panel>
				<Panel
					id="pnl_comments"
				>			
					<Div>
						Comments...		
					</Div>
					<FixedLayout
						vertical="bottom"
					>
					<Tabs>
						<HorizontalScroll>
							<TabsItem	onClick={() => this.setState({ activePanel: 'pnl_orders' })}
										selected={this.state.activePanel == 'pnl_orders'}
							>
								Заказы								
							</TabsItem>
							<TabsItem	onClick={() => this.setState({ activePanel: 'pnl_comments' })}
										selected={this.state.activePanel == 'pnl_comments'}
							>
								Комментарии
							</TabsItem>
						</HorizontalScroll>
					</Tabs>
					</FixedLayout>					

				</Panel>								
			</View>
		)
			
	}
}

export default App;

`

**Comment by ArthurStam** [comment]
Привет. Скопировал пример, проблему воспроизвести не смог. https://codesandbox.io/s/vkui-boilerplate-vcwsg

**Comment by NicegrinL** [comment]
В сандбоксе и на андроиде все работает. На иос нет. Мы вчера запустили приложение и посыпались жалобы от владельцев ифонов что вкладок нет. На ифоне вкладки отрабатывают только при верхнем расположении fixedlayout/ Ниже скрины - черный - на ифоне белый на ведроиде.24.06.2020, 14:21, "Artur Stambultsian" <notifications@github.com>: Привет. Скопировал пример, проблему воспроизвести не смог. https://codesandbox.io/s/vkui-boilerplate-vcwsg—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  -- С Уважением Дмитрий Л.

**Comment by ArthurStam** [comment]
Окей. Тогда нужна модель iPhone и версия iOS

**Comment by NicegrinL** [comment]
IPhone SEВерсия ПО 13.5.1 24.06.2020, 14:27, "Artur Stambultsian" <notifications@github.com>: Окей. Тогда нужна модель iPhone и версия iOS—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  -- С Уважением Дмитрий Л.

**Comment by ArthurStam** [comment]
SE новый или старый?

**Comment by NicegrinL** [comment]
старый  24.06.2020, 14:55, "Artur Stambultsian" <notifications@github.com>: SE новый или старый?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  -- С Уважением Дмитрий Л.
