### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by NicegrinL** [VKCOM/VKUI#835]
**Описание**
Использую
import { withPlatform, ANDROID } from '@vkontakte/vkui';
и в render() класса App:
const { platform } = this.props; 
this.osname = platform;

В итоге this.osname на мобильном устройстве с Андроидом на борту не получает значение, равное ANDROID
Может я как то неправильно использую withPlatform? Но вроде бы все согласно мануалу.

**Comment by fedorov-xyz** [comment]
Привет.

1) Делать side-эффекты в render – не очень хорошо (записывать в this).
2) Оборачиваешь ли ты `App` в `withPlatform`?

**Comment by NicegrinL** [comment]
Я новичок в этом деле. Готов делать верно. Писал как в мануале.Оборачиваешь.... извини, за ламерский подход, что вижу в мауале то пишу, а тм инфы не оч много.Как правильно сделать? 25.06.2020, 12:41, "Igor Fedorov" <notifications@github.com>: Привет.Делать side-эффекты в render – не очень хорошо (записывать в this).Оборачиваешь ли ты App в withPlatform?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  -- С Уважением Дмитрий Л.

**Comment by fedorov-xyz** [comment]
```jsx
import React, { Component } from 'react';
import { withPlatform, ANDROID } from '@vkontakte/vkui';

class App extends Component {
  render() {
    if (this.props.platform === ANDROID) {
      return 'Это Android';
    } else {
      return 'Это iOS';
    }
  }
}

export default withPlatform(App);

```

**Comment by NicegrinL** [comment]
Ок, обернуть это об этом.export default withPlatform(App);Благодарю покорно. Извиняюсь еще раз за ламерство.Скажи есть ли где про все эти тонкости почитать, чтобы не плодить глупые темы на гитхабе?  25.06.2020, 12:52, "Igor Fedorov" <notifications@github.com>: import React, { Component } from 'react';
import { withPlatform, ANDROID } from '@vkontakte/vkui';

class App extends Component {
  render() {
    if (this.props.platform === ANDROID) {
      return 'Это Android';
    } else {
      return 'Это iOS';
    }
  }
}

export default withPlatform(App);

**Comment by fedorov-xyz** [comment]
Можно изучить официальную документацию React, которая доступна в том числе на русском языке.
https://ru.reactjs.org/
