### ISSUE TITLE
[Bug] не получается сделать отступ для статус бара на айфоне

### ISSUE THREAD

**Issue by ninaandreyanova** [VKCOM/VKUI#837]
**Описание**
не получается сделать отступ для статус бара на айфоне
используем переменную safe-area-inset-top, в текущей версии приложения это работает, потому что там шапка абсолютно позиционированна

сейчас шапку перенесли из абсолюта в корень приложения, то есть она толкает основной контент приложения, и после этого отступ перестал учитываться. Отступ снизу тоже вроде не считается. Наш разработчик считает, что именно другое позиционирование шапки, но не может быть уверенным в этом. Если бы можно было через инспектор отладить приложение на айфоне, то было бы легко выяснить в чём именно проблема, а так непонятно. Т.к. отладить приложение невозможно.

**Шаги воспроизведения**
 Открываем приложение https://vk.com/app7411881_5083923 на айфоне. Видим, что нет отступа для статус бара.

**Ожидаемое поведение**
Отступ для статус бара есть.

**Скриншоты**

**Пример с воспроизведением**
Воспроизводится везде на айфоне https://vk.com/app7411881_5083923.

**Comment by ArthurStam** [comment]
1. Нужен пример с минимальным количеством кода, в котором ошибка воспроизводится.
2. Нужен номер версии vkui.
3. Нужна модель айфона и версия iOS.

**Comment by ninaandreyanova** [comment]
Нашли проблему на стороне партнера.
