### ISSUE TITLE
[Bug] Некорректная работ ползунка, при свайпе

### ISSUE THREAD

**Issue by AllexEvo** [VKCOM/VKUI#838]
**Описание**
Некорректная работ ползунка, при свайпе на странице. Ссылка на Bugtracker https://vk.com/bug223856

**Шаги воспроизведения**
1) Найдите ползунок на странице с возможностью свайпа;
2) Свайпните вправо на уровне ползунка.

**Ожидаемое поведение**
Ползунок должен независимо двигаться, либо вообще не двигаться при свайпе.

**Видео**
https://vk.com/doc216618903_551197080

**Comment by ArthurStam** [comment]
Привет. Тикет дублирует вот этот #562
