### ISSUE TITLE
[Bug] RichCell не всегда срабатывает обработчик клика

### ISSUE THREAD

**Issue by b-ponomarenko** [VKCOM/VKUI#839]
**Описание**
При клике на RichCell не всегда срабатывает обработчик клика

**Шаги воспроизведения**
1. Кликнуть на RichCell
2. Появляется выделение компонента
3. Обработчик не вызывается

**Ожидаемое поведение**
Обработчик вызывается

**Скриншоты**
Ссылка на видео с воспроизведением https://gofile.io/d/Og7cB1

**Пример с воспроизведением**
Можно попробовать сделать по примеру из видео.

**Comment by ArthurStam** [comment]
Привет. Спасибо за тикет, посмотрим.

**Comment by ArthurStam** [comment]
Воспроизвести не смог. По ссылке когда иду, пишет что видео не существует.

**Comment by b-ponomarenko** [comment]
Перезалил https://dump.video/VT6Hk3, воспроизводится на iOS 13

**Comment by ArthurStam** [comment]
Привет. У нас есть вот такая строчка. Вероятно, дело в ней. Может быть так, что ты чутка слайдишь в те разы, когда не отрабатывает клик?
https://github.com/VKCOM/VKUI/blob/master/src/components/Touch/Touch.tsx#L225

**Comment by b-ponomarenko** [comment]
Возможно, просто неприятное поведение. Мб добавить проверку, если сдвиг небольшой (дрожание пальца и тд), то разрешать клик? Или если клик отменяется, то хотя бы анимацию не показыть

**Comment by ArthurStam** [comment]
Да, надо сделать isSlide чутка умнее. Я переименую таску? Просто это ко всем компонентам применимо, не только к RichCell

**Comment by b-ponomarenko** [comment]
Да, переименуй как удобнее)

**Comment by gbowsky** [comment]
С актуальными версиями пакетов не воспроизводится.
https://tox3e.csb.app/

**Comment by SevereCloud** [comment]
RichCell более не использует для обработки нажатий Touch. Вместо этого используются нативные события нажатия и отмены нажатия
