### ISSUE TITLE
Tooltip: добавить светлый вариант помимо Accent

### ISSUE THREAD

**Issue by wayshev** [VKCOM/VKUI#840]
Tooltip Light:

background: white
text: gray_800

![Screenshot 2020-06-29 at 19 17 51](https://user-images.githubusercontent.com/61538408/86030500-3bf67380-ba3d-11ea-8ceb-a354425a3de8.png)

https://www.figma.com/file/kvjzdHwTDO7Vcrh1VglGQ5/VKUI-iOS-Library?node-id=107%3A1613

**Comment by SkyGopnik** [comment]
Так себе выглядит, в чём проблема его самому изменить?
