### ISSUE TITLE
[Feature] non-closing Alert

### ISSUE THREAD

**Issue by kpachbiu88** [VKCOM/VKUI#843]
Иногда бывает нужно показать Alert без действий (см вложение)

![Image](https://i.imgur.com/w1BHPetg.png)

Сделать свойство closable = true | false компоненту Alert, в случае true Alert невозможно будет закрыть нажатием.

**Comment by ilyapishchulin** [comment]
Соглашусь, если не передавать пропс с onClose, то приложение будет ломаться

**Comment by SkyGopnik** [comment]
Сейчас скажут что так и должно быть, мне так модалки отклонили) Хотя я модалку +- для того же самого использовал, только с более подробным описанием и гифкой.

**Comment by ilyapishchulin** [comment]
Модалки это иное, а вот показывать алерт о том, что вы забанены -- ок

**Comment by ArthurStam** [comment]
Мы сейчас с дизайнерами обсудим. В данном случае нельзя просто добавлять такие флаги, можем поломать привычный UX.

**Comment by ArthurStam** [comment]
Нет, всё-таки Alert всегда должен быть закрываемым. Свой кейс можете реализовать самостоятельно, используя PopoutWrapper.
