### ISSUE TITLE
[Bug] Несоответствие дизайну

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#846]
Смотрим в компонент Banner в VKUI, крестик в правом углу типа @vkontakte/icons/dist/24/dismiss, а по дизайну из Figma, должен быть @vkontakte/icons/dist/24/cancel;

Как в VKUI: https://imgur.com/oMYvlTt
Как должно быть: https://imgur.com/a6ohDoB

**Comment by ArthurStam** [comment]
Спасибо, поправим.

**Comment by Lihachyov** [comment]
Лайк за репорт по дизайну, и правда было несоответствие) На Android должна быть иконка cancel, да, а на iOS должна остаться dismiss.
