### ISSUE TITLE
[Bug] Нет отображения для Tabs с mode=segmented на Android

### ISSUE THREAD

**Issue by b-ponomarenko** [VKCOM/VKUI#847]
**Описание**
На устройствах с Android в принципе никак не отрисовываются табы, просто текст

**Шаги воспроизведения**
Добавить табы с таким модом и открыть на андроиде

**Ожидаемое поведение**
Нормальное отображение, хотя бы дефолтное

**Скриншоты**
-

**Пример с воспроизведением**
https://codesandbox.io/s/vkui-boilerplate-u4z8r

**Comment by ArthurStam** [comment]
Привет. Спасибо, подумаем.
