### ISSUE TITLE
[Bug] Закругление Card не применяется к контенту в самом компоненте

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#855]
**Описание**
При использовании Card, закругление применяется только на саму карточку, контент с полным заполнением в ней игнорируется.

**Скриншоты**
![image](https://user-images.githubusercontent.com/42776347/86548160-c0398100-bf7e-11ea-85a4-f59836a64d36.png)

**Пример с воспроизведением**
https://codesandbox.io/s/vkui-boilerplate-99noo

**Comment by ArthurStam** [comment]
Привет. Добиться фикса можно двумя способами:
1. Со стороны библиотеки, добавив `overflow: hidden`.
2. Со стороны приложения, добавив `border-top-left-radius: inherit; border-top-right-radius: inherit`

Я считаю, что первый способ более радикальный, потому что `overflow: hidden` почти всегда в какой-то момент встаёт боком. Предлагаю пофиксить на стороне приложения.

**Comment by MrZillaGold** [comment]
Хорошо, так и сделаю. Спасибо!
