### ISSUE TITLE
[Bug] Div имеет user-select: text;

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#857]
**Описание**
В стилях Div присутствует `user-select: text;`, который вообще не нужен, компонент нужен для того, чтобы сделать блок с стандартными отступами, но в придачу мы еще получаем выделение всех остальных элементов обернутых в этот компонент. 

**Скриншоты**
![image](https://user-images.githubusercontent.com/42776347/86709980-d66a3e80-c05d-11ea-9a57-3091a476e723.png)

**Comment by fedorov-xyz** [comment]
Спасибо за issue. Действительно, user-select там не нужен. Исправим.
