### ISSUE TITLE
[Feature] Возможность использовать FormLayout__row top/bottom не только в children FormLayout

### ISSUE THREAD

**Issue by fix-fix** [VKCOM/VKUI#858]
Сейчас FormLayout пробегается по своим children и смотрит на их props, и рисует top/bottom, если [они есть в props][FormLayout исходники].\
Проблема: Такое поведение само по себе неочевидно для react-компонента в теории, но есть и конкретная проблема - не могу вынести часть формы в компонент (вынос локального состояния и логики, для переиспользования), так как при абстрагировании в компонент больше не могу влиять на отрисовку top/bottom.\
[Пример]

То есть я хочу возжность рендерить top/bottom явно внутри FormLayout.
A сейчас частично не работает возможность абстрагировать набор компонентов внутри FormLayout - приходится дублировать код, либо костылить через массивы.

Возможно стоит выделить публичный компонент, который бы можно было использовать для создания разметки с классом `FormLayout__row`

[FormLayout исходники]: https://github.com/VKCOM/VKUI/blob/d3343b49bd04ca002f36499e685ee7e1d3622513/src/components/FormLayout/FormLayout.tsx#L41
[Пример]: https://codesandbox.io/s/vkui-boilerplate-ulcnj?file=/src/index.js:311-752

**Comment by ArthurStam** [comment]
Будет реализовано в ближайшее время в v4

**Comment by fix-fix** [comment]
Исправлено в свежем v4, пример: https://codesandbox.io/s/vkui-boilerplate-forked-y842r
