### ISSUE TITLE
[Feature] Сделаем VKUI Great Again

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/VKUI#859]
> Я понимаю, что VKUI это один из первых опенсурсных продуктов компании, которые разрабатываются внутри компании для использования как внутренними, так и внешними разработчиками приложений VK Mini Apps. Библиотека заметно ускоряет и упрощает разработку интерфейса, но подход к разработке и обратной связи заставляет желать лучшего.

Хотелось бы обратить внимание менеджмента на следующие моменты:
1. **Прозрачность работы с [репортами](https://github.com/VKCOM/VKUI/issues/)** — задачи висят по году без какого либо ответа. Для разработчиков приложений VK Mini Apps важно понимать **будет ли исправлена** проблема и если будет то **ориентировочные сроки**. В настоящее время складывается следующая ситуация: тестеры и пользователи ждут ответа от разработчика, разработчик ждёт ответа от команды VKUI и всё залипает.
2. **Связь между продуктами** — я понимаю, что VKUI, vk-bridge и биндинги в платформах — это разные **продукты** в терминах VK, но для внешнего разработчика VK Mini Apps они связаны до неразличимости. В настоящее время складывается ситуация, когда репорт "футболят" между продуктами и не найти крайних.
3. **Доступ команды VKUI/vk-bridge** к [баг трекеру продуктов/приложений на ревью](https://vk.com/bugs?act=products). Текущие репорты тестеров невозможно напрямую передать команде VKUI/vk-bridge, приходится копировать между баг трекером и GitHub-ом.
4. **Решения статуса баг трекеров продуктов** [VK Mini Apps](https://vk.com/bugs?act=product&id=76), [iOS](https://vk.com/bugs?act=product&id=21), [Android](https://vk.com/bugs?act=product&id=20), [Web](https://vk.com/bugs?act=product&id=24), [m.vk.com](https://vk.com/bugs?act=product&id=25) трекеры (репорты связанные с интеграцией VK Mini Apps и платформы) и [VK API](https://vk.com/bugs?act=product&id=22) — репорты просматриваются и комментируются ещё хуже, чем на GitHub, а также присутствует вышеперечисленная проблема доступа когда невозможно зарепортить в "нужный" продукт.

**Comment by mahnunchik** [comment]
### Прозрачность работы с репортами

Мои репорты висят с марта без ответа, соответствующие репорты тестеров тоже зависли:

* https://github.com/VKCOM/VKUI/issues/596
* https://github.com/VKCOM/VKUI/issues/597
* https://github.com/VKCOM/VKUI/issues/598
* https://github.com/VKCOM/VKUI/issues/599
* https://github.com/VKCOM/VKUI/issues/600
* https://github.com/VKCOM/VKUI/issues/602
* https://github.com/VKCOM/VKUI/issues/603
* https://github.com/VKCOM/VKUI/issues/605
* https://github.com/VKCOM/VKUI/issues/619
* https://github.com/VKCOM/VKUI/issues/620
* https://github.com/VKCOM/VKUI/issues/624

Варианты решения:
* Выделить специального человека на задачу разгребания и проставления статуса
* И/или выделить время на задачу разгребания (например:среда баг трекера)

### Связь между продуктами

По хорошему бага должна быть зарепорчена в iOS продукт https://vk.com/bug154507 так как проблема на стороне биндинга vk-bridge на iOS, но **за пол года** мне так никто и не открыл доступ к https://vk.com/bugs?act=product&id=20

Варианты решения:

* Переработать подход к репорту и доступу к тикетам для все связки VK Mini Apps (VKUI, vk-bridge и биндинги на платформах)
* Выделить человека/время на "переправление" репортов в правильные места
* Написать документацию, что куда правильно репортить, чтобы проблема быстрее дошла до нужного отдела.

**Comment by ArthurStam** [comment]
1. Привет. У нас действительно есть проблема с разгребанием проблем, особенно сейчас, когда идет активная разработка следующей мажорной версии. Не так давно мы реорганизовали работу над тикетами и вроде наметилась положительная динамика решения проблем. Понимаем вашу боль.

2. VKUI, VK Bridge и ряд пакетов для VK Mini Apps — это действительно разные продукты для разработчиков. Тут проблемы не вижу. Разработчики должны понимать, что это независимые модули, у каждого из которых есть свой issue-трекер. Если мы видим, что "проблема не на нашей стороне", то максимум, что мы можем сделать — это направить человека в другой треккер, чат или группу.

3, 4. Нам комфортнее иметь один публичный канал для тикетов — GitHub. Как я вижу, багтрекер — это место для продуктовых репортов. Если выясняется, что проблема на стороне библиотеки, то необходимо завести тикет на GitHub с полным описанием того, что случилось. Недавно мы завели шаблоны для создания тикетов. 
https://github.com/VKCOM/VKUI/issues/new/choose

**Comment by mahnunchik** [comment]
1. Привет! Отлично, надеюсь на положительные изменения и то, что очередь дойдёт и до моих тикетов 😉 

2. >  Разработчики должны понимать, что это независимые модули, у каждого из которых есть свой issue-трекер. 

Считаю, что это хорошая тема для поста сюда https://vk.com/vkappsdev или даже раздела в документацию. Я то уже в курсе, но новичкам может быть полезно.

* Проблема в интерфейсе - репорти в https://github.com/VKCOM/VKUI
* Проблема с общением с устройством - репорти https://github.com/VKCOM/vk-bridge (или сюда https://vk.com/bugs?act=product&id=76 почему опять два места для репорта?) 
* Если идентифицировал, что проблема с общением с устройством на определённой платформе, то репорти: web https://vk.com/bugs?act=product&id=24 m.vk.com https://vk.com/bugs?act=product&id=25 Android https://vk.com/bugs?act=product&id=20 и iOS https://vk.com/bugs?act=product&id=21

3 и 4. Аналогично, удобнее работать с единой точкой входа, в частности https://github.com/VKCOM/VKUI/issues/new/choose - шаблоны круто!

---

Но предлагаю разобрать случай с тикетом https://vk.com/bug154507 куда его правильно репортить?

1. Ясно понятно, что не VKUI проблема - интерфейс системный.
2. Можно зарепортить в https://github.com/VKCOM/vk-bridge или в https://vk.com/bugs?product=76
3. Если ешё подебажить, то можно понять, что только на iOS проблема, то есть правильнее репортить в iOS https://vk.com/bugs?act=product&id=21

Но у большинства **нет** доступа к продуктам.

Как быть?

**Comment by ArthurStam** [comment]
У меня тоже нет доступа к продуктам. Я занимаюсь разработкой данной библиотеки и хочу, чтобы мне не приходилось бегать по ссылкам и понимать, что произошло у разраба. Алгоритм заведения тикета должен быть таким (и только таким):

1. Что-то не работает.
2. Понимаешь, что проблема в VKUI.
3. Создаешь тикет, идя по шаблону https://github.com/VKCOM/VKUI/issues/new/choose.
4. Ждёшь нашей реакции.

Ссылки на другие трекеры, отхождения от шаблона — всё это замедляет работу над тикетом.

**Comment by danyadev** [comment]
Думаю, редактирование всех тикетов @mahnunchik с добавлением напрямую в тикет шагов воспроизведения и скриншота или видео с результатом поможет разработчикам в дальнейшем оценить каждый баг, а так же даст возможность сторонним разработчикам поработать над ним не имея дел с баг трекером вк (я, к примеру, вовсе оттуда исключен)

**Comment by eolme** [comment]
vk-bridge - это тема отдельная, но очень сильно касается VKUI, например, на Android инсеты не работают и весь контент при `action_bar_color: none` залазит под статус и навбар, и приходится, мягко говоря, огромные костыли писать, чтобы вообще хоть как-то это исправить.

**Comment by ilyapishchulin** [comment]
@eolme этой проблеме год и о ней знают, увы фиксить не хотят.

Вообще не понимаю, второй пункт тут не вписывается. Логично, что библиотеки разные, так бы их совместили.
Все проблемы с VK Mini Apps на любой платформе можно репортить сюда: vk.com/bugs?act=product&id=76

**Comment by eolme** [comment]
Еще один вопрос по старым платформам (a.k.a Android 4 = Chrome 27-33, iOS 9), которые обговариваются как поддерживаемые, по факту оными не являются ([css-variables](https://caniuse.com/#feat=css-variables)). И, собственно, никаких альтернатив то и нет, можно конечно SASS (SCSS) или LESS с двойным переопределением для каждой темы, либо Styled Components с темами, но тоже - это огромная работа.

**Comment by fedorov-xyz** [comment]
Для платформ без переменных у нас есть фолбек в виде значения переменной строкой выше в собранных стилях. 
Там смены тем, увы, не будет.

**Comment by eolme** [comment]
Хорошо, бог с ними, с темами, а что делать с m.vk.com? Я имею ввиду старые/вендорные браузеры, которым показывается вот [эта страница](https://vk.com/badbrowser.php), на которым прямо и говорится, что воспользуйтесь мобильной версией сайта. И добро пожаловать IE, Windows Phone, Opera Mini и т.п.

**Comment by mahnunchik** [comment]
@ArthurStam @fedorov-xyz  если бага явно VKUI то алгоритм понятен https://github.com/VKCOM/VKUI/issues/859#issuecomment-655522378

Что делать если проблема в `vk-bridge` или вообще непонятно где?

Как уже говорилось выше, трекер https://vk.com/bugs?act=product&id=76 очень плохо просматривается.

**Comment by mahnunchik** [comment]
бля.... все ссылки на скринкасты с багами в моих тикетах протухли... нет доступа даже у меня. Проклятые продукты!

**Comment by fedorov-xyz** [comment]
Проблема в vk-brigde – слишком размытое определение. vk-brigde – просто JS-библиотека. Скорее всего корень проблемы кроется где-то в нативном клиенте – куда и нужно репортить. Если проблема в самой библиотеке, то на GitHub – https://github.com/VKCOM/vk-bridge.

**Comment by mahnunchik** [comment]
@fedorov-xyz к продуктам нативных клиентов почти ни у кого нет доступа, как уже [писали выше](https://github.com/VKCOM/VKUI/issues/859#issuecomment-655522378).

До iOS продоукта мне не выдают доступ уже год.

Так куда репортить проблема которая в **vk-brigde** и/или **нативном клиенте** при условии, что ни у кого нет доступа к продуктам? Нет возможности зарепортить - нет проблем, увы не выход.

**Comment by ArthurStam** [comment]
> Хорошо, бог с ними, с темами, а что делать с m.vk.com? Я имею ввиду старые/вендорные браузеры, которым показывается вот [эта страница](https://vk.com/badbrowser.php), на которым прямо и говорится, что воспользуйтесь мобильной версией сайта. И добро пожаловать IE, Windows Phone, Opera Mini и т.п.

А какое отношение это имеет к текущему тикету?

**Comment by ArthurStam** [comment]
Ребята, давайте не делать из тикета помойку, где вы пытаетесь поделиться всеми наболевшими проблемами. Я описал регламент рассмотрения багов и фича-реквестов. Мы стараемся отвечать на каждый тикет по мере сил.

**Comment by ArthurStam** [comment]
Я не понимаю, зачем мы тут говорим про нативные клиенты.
Если есть проблема на стыке vkui и клиента, то репорт стоит слать в этот репозиторий, если на стыке vk-bridge и клиент — в репозиторий vk-bridge.
Если вы не понимаете, на чьей стороне проблема, то делайте догадки и шлите туда, куда считаете нужным. Мы перенаправим тикет, если ваша догадка окажется неверной.

**Comment by mahnunchik** [comment]
> в репозиторий vk-bridge.

В репозиторий https://github.com/VKCOM/vk-bridge или в Продукт https://vk.com/bugs?act=product&id=76 

И зачем два места куда можно зарепортить?

Это противоречит, тому что написал @fedorov-xyz тут https://github.com/VKCOM/VKUI/issues/859#issuecomment-655593024

> Скорее всего корень проблемы кроется где-то в нативном клиенте – куда и нужно репортить

Собственно, хотелось бы понять воркфлоу с проблемами на стыке vk-bridge и клиента: https://github.com/VKCOM/VKUI/issues/859#issuecomment-655595485

**Comment by ArthurStam** [comment]
> И зачем два места куда можно зарепортить?

Багтрекер — это место для продуктовых репортов, Github — для репортов по конкретным технлогиям (vkui, vk-bridge, icons)

>Собственно, хотелось бы понять воркфлоу с проблемами на стыке vk-bridge и клиента

Если есть проблема на стыке vkui и клиента, то репорт стоит слать в этот репозиторий, если на стыке vk-bridge и клиента — в репозиторий vk-bridge.

**Comment by mahnunchik** [comment]
@ArthurStam спасибо за разъяснение.

Передайте, тогда, пожалуйста, поддержке, которая отвечает за ревью приложений VK Mini Apps, чтобы **НЕ** отправляли в продуктовые трекеры.

**Comment by ArthurStam** [comment]
Написал тебе на почту
