### ISSUE TITLE
[Bug] Библиотека не поддерживает старые/вендорные браузеры

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#861]
**Описание**
Старым/вендорным браузерам показывается вот [эта страница](https://vk.com/badbrowser.php), на которым прямо говорится, что воспользуйтесь мобильной версией сайта. И добро пожаловать IE, Windows Phone, Opera Mini и т.п.

**Ожидаемое поведение**
Такие браузеры должны поддерживаться, либо должно быть предупреждение и соответствующая инструкция, как сделать так, чтобы они поддерживались, если разработчик хочет распространять свое приложение на данной платформе

**Comment by ArthurStam** [comment]
Не понял суть бага. С какими конкретно браузерами проблемы сейчас?

**Comment by eolme** [comment]
Ну, например, `Mozilla/5.0 (Windows Phone 8.1; ARM; Trident/8.0; Touch; rv:11.0; WebBrowser/8.1; IEMobile/11.0; Microsoft; Lumia 640 LTE) like Gecko`, пока еще раз через babel уже с другим browserslist не прогнал, падал с `script error`

**Comment by eolme** [comment]
`Mozilla/5.0 (iPad; CPU OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D257 Safari/9537.53` с `syntax error`

**Comment by ArthurStam** [comment]
Если говорить про либу, то у нас нет планов по поддержке древних браузеров. browserslist со временем будет только ползти вверх. Вопросы по написанию мини аппов с поддержкой древних браузеров предлагаю адресовать сюда https://vk.com/topic-166562603_40071994

**Comment by eolme** [comment]
Это перекладывание с одного на другого
> ... должно быть предупреждение и соответствующая инструкция, как сделать так, чтобы они поддерживались, если разработчик хочет распространять свое приложение на данной платформе

**Comment by ArthurStam** [comment]
Нет, это разграничение ответственностей. Библиотека != VK Mini Apps. Мы отвечаем за библиотеку и говорим, что не будем поддерживать старые браузеры. На крайняк можно сделать форк, поменять в нём браузерлист и собирать библиотеку оттуда.

**Comment by eolme** [comment]
Хорошо, сделал PR

**Comment by ArthurStam** [comment]
Так, мне только что птичка из mvk напела, что сервисы там поддерживаются с тех версий, на которых работает vkui. Возвращаюсь к вопросу о проблеме. В чем она заключается?

**Comment by eolme** [comment]
Ок, если они не поддерживаются, то как сервисы запускают?

**Comment by eolme** [comment]
У меня нет подобных устройств, я не могу проверить как оно там работает или нет, мне прилетают ошибки через сервис

**Comment by eolme** [comment]
Вот, я спокойно открыл свой сервис на m.vk.com с Chrome 26


![image](https://user-images.githubusercontent.com/11076888/86957212-6cd85600-c16b-11ea-987f-04987bf4fa4d.png)


Сам m.vk.com выглядит нормально


![image](https://user-images.githubusercontent.com/11076888/86957257-837ead00-c16b-11ea-8033-5cc4fec24d99.png)

**Comment by eolme** [comment]
Это я к тому, что ничего мне не помешало это сделать, и m.vk.com работает, и vk-bridge работает

**Comment by eolme** [comment]
Остальные приложения, которые не заморачиваются с поддержкой старых браузеров, падают с соответствующими ошибками

**Comment by fedorov-xyz** [comment]
Завели задачу. Добавят проверку на версию браузера.

**Comment by eolme** [comment]
Либо #864, либо #865 восстановите?

**Comment by ArthurStam** [comment]
Оки
