### ISSUE TITLE
[Possible Bug] Инсеты не поддерживаются на старых браузерах

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#862]
**Описание**
После #794 инсеты используют [css-variables](https://caniuse.com/#feat=css-variables), которые не поддерживаются старыми браузерами.

**Ожидаемое поведение**
Инсеты работают на всех поддерживаемых библиотекой браузерах.

**Comment by ArthurStam** [comment]
CSS-переменные не работают в ios <= 9.1 и android <= 4.4, если верить данным [caniuse](https://caniuse.com/#search=css%20variables). Наши iOS и Android клиенты перестали поддерживать эти браузеры. Библиотека тоже скоро перестанет. 

Есть какие-то конкретные проблемы сейчас? Девайс, не поддерживающий css-переменные, на котором открыли vkui-приложение? Речь про открытие именно в клиентах, потому что только там bridge-инсеты были актуальны.

**Comment by ArthurStam** [comment]
Закрываю за отсутствием активности
