### ISSUE TITLE
[Bug] Модальные окна ломаются при отсутствии контента

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#863]
**Описание**
Если в модальном окне отсутствует контент в момент его создания, оно ломается и блокирует работу всего приложения.

**Ожидаемое поведение**
Модальное окно ожидает контент и реагирует на его изменение.

**Пример с воспроизведением**
https://codesandbox.io/s/vkui-boilerplate-ypwsf

**Comment by fedorov-xyz** [comment]
Я не вижу здесь проблемы, потому что модальная страница не получила вообще ничего – ни шапки, ни содержимого. Закрыть в примере модальную страницу я тоже не могу, потому что нет обработчика `onClose`.

**Comment by eolme** [comment]
Обновил пример

**Comment by fedorov-xyz** [comment]
Спасибо, покопаюсь.

**Comment by vkcom-publisher** [comment]
✅ <a href="https://github.com/VKCOM/VKUI/releases/tag/v7.0.0" target="_blank">v7.0.0</a> 🎉
