### ISSUE TITLE
[Bug] Поставили не ту иконку в Epic на место профиля.

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#866]
**Шаги воспроизведения**
Переходим по [ссылочке](https://vkcom.github.io/vkui-styleguide/#epic)

**Ожидаемое поведение**
Иконка от профиля.

**Скриншоты**
<img width="1440" alt="Снимок экрана 2020-07-08 в 22 48 15" src="https://user-images.githubusercontent.com/45998835/86963386-1d932500-c16d-11ea-92d5-4131bab03eb4.png">

**Comment by fedorov-xyz** [comment]
Спасибо, поправим :)

**Comment by ilyapishchulin** [comment]
Хех, не увидел коммент, ты так быстро ответил)
