### ISSUE TITLE
[Bug] SimpleCell оборачивается в Tappable без передачи onClick

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#870]
**Описание**
Если мы хотим использовать SimpleCell просто для создания списка, сделать у нас это не получится, так как в любом случае он оборачивается в Tappable, даже без передачи onClick.

**Comment by ilyapishchulin** [comment]
#806

**Comment by ArthurStam** [comment]
Собсно, @ilyapishchulin пояснил)
