### ISSUE TITLE
[Bug] Tabbar всё равно рисуется при передаче пустого свойства

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#871]
**Описание**
Не скрывается место под таббар на панелях, где он принудительно отключен.

**Шаги воспроизведения**
1. Вставляем PromoBanner на панель с выключенным таббаром.

**Ожидаемое поведение**
PromoBanner располагается в самом низу. (Аналогично со Снекбарами и так далее)

**Скриншоты**
<img width="376" alt="Снимок экрана 2020-07-09 в 12 55 46" src="https://user-images.githubusercontent.com/45998835/87025799-85845280-c1e3-11ea-940e-0051cef6f815.png">

**Пример с воспроизведением**
Можешь сразу в [песочницу](vkcom.github.io/vkui-styleguide/#epic) вставить этот [код](https://pastebin.com/9jqn2EX1)

**Comment by ArthurStam** [comment]
Таббар всё ещё является обязательным. Скрытие — недокументированная возможность. Аналогия со снекбарами некорректна, потому что там мы делали фикс для отображения внутри модалок, которые перекрывают таббар и там этот отступ был лишним.

У нас есть планы #149 по скрытию таббара, можете подписаться на тикет.

**Comment by ilyapishchulin** [comment]
Ну да, можно отнести туда, хотя всё равно странное поведение)
