### ISSUE TITLE
[Bug] Некорректная работа свайпа

### ISSUE THREAD

**Issue by b-ponomarenko** [VKCOM/VKUI#872]
**Описание**
В кейсе, если установить фокус на инпут и начать делать свайп назад, то есть возможность скроллить по вертикали

**Шаги воспроизведения**
Добавить 2 страницы, на второй должен быть инпут и сделать свайп назад

**Ожидаемое поведение**
Скролл по вертикали отключен

**Скриншоты**
Видео https://dump.video/i/GWVf7e.mp4

**Comment by ArthurStam** [comment]
Спасибо. Поправим.

**Comment by inomdzhon** [comment]
Не воспроизводится.

Проверил в песочнице `v6.0.0` – [ссылка на песочницу](https://vkcom.github.io/VKUI/6.0.0/playground/iframe.html?id=layout-view--swipe-block-example&viewMode=story)
