### ISSUE TITLE
[Bug] Скачет PanelHeader

### ISSUE THREAD

**Issue by b-ponomarenko** [VKCOM/VKUI#873]
**Описание**
При возвращении на страницу с большим количеством контента со страницы, где его не много (не во весь вьюпорт) наблюдается "скачки" PanelHeader

**Шаги воспроизведения**
1. Добавить страницы, где на одной будет много контента, а на другой нет.
2. Сделать возврать со 2 на 1-ю

**Ожидаемое поведение**
PanelHeader намертво прикреплен вверху

**Скриншоты**
Видео https://dump.video/YqleNf

**Comment by ArthurStam** [comment]
Уже несколько таких тикетов было #804

**Comment by b-ponomarenko** [comment]
Так как быть, в подобных тикетах написано, что нужно кэшировать данные, в моем случае данные закешированы, т.е. высота панели осталась такая же, вопрос как быть, можно ли это как-то пофиксить из вне?

**Comment by ArthurStam** [comment]
Видос говорит об обратном. Советую проверить, что возвращает render при маунте предыдущей панели и при завершении анимации. Вангую, там разный контент.

**Comment by ArthurStam** [comment]
Я добавлю в доке комментарий по этому поводу. Это неочевидный момент и к нам уже несколько раз пришли с подобными багами.

**Comment by b-ponomarenko** [comment]
> Видос говорит об обратном.
Не совсем понял: у меня список элементов, мы переходим на другую view, удаляем элемент, но когда мы возвращаемся обратно он на какое-то время висит т.е. по высоте контент идентичный, и только после перезапроса данных этот элемент пропадает.

Просто не совсем понятно, почему нельзя просто зафиксировать PanelHeader в верхней точке? Как уже было написано в #804, не совсем понятно, почему даже если высота разная это афектит PanelHeader

**Comment by ArthurStam** [comment]
Потому что у fixed блоков начинаются проблемы, когда их контейнер трансформируется. Поэтому на время переходов мы меняем позиционирование всех фиксированных блоков на absolute, двигая их соответственно скроллу панели.

**Comment by ArthurStam** [comment]
https://codesandbox.io/s/vkui-boilerplate-oj149 вот сюда залейте код, в котором воспроизводится слетание шапки.

**Comment by ArthurStam** [comment]
Но можете этого не делать и чекнуть код первой панели. Уверен, что проблема именно там. Уже несколько точно таких же тикетов обрабатывали.

**Comment by b-ponomarenko** [comment]
Спасибо, подробней изучу этот момент

**Comment by b-ponomarenko** [comment]
Привет еще раз, я на досуге покопался в ваших исходниках, и как мне кажется, это вполне реализуемо.
Как я понял, при уходе с панели вы записываете ее вы запоминаете ее высоту (https://github.com/VKCOM/VKUI/blob/master/src/components/View/View.tsx#L154), далее когда мы на нее возвращаемся вы передаете в эвенте все высоты (https://github.com/VKCOM/VKUI/blob/master/src/components/View/View.tsx#L186) и далее сам `FixedLayout` вытягивает высоту по актуальной панели (https://github.com/VKCOM/VKUI/blob/master/src/components/FixedLayout/FixedLayout.tsx#L72)

В итоге, в кейсах, когда высота предыдущей и текущей панели уменьшается, то `PanelHeader` скачет вниз.
В некоторых кейсах панель уходит вверх, но пока не понял почему.

Мы бы могли в момент маунта `Panel` каким-то механизмом уведомить `View` об изменении размера и изменить `this.state.scrolls`

**Comment by b-ponomarenko** [comment]
Добавил ПР с концептом https://github.com/VKCOM/VKUI/pull/897, @ArthurStam посмотри плз. Это очень черновой вариант, но концепт понятен. Можем спрятать все во View, контекст пока добавил для наглядности
