### ISSUE TITLE
[Опечатка] PromoBanner

### ISSUE THREAD

**Issue by AdvTechnoKing** [VKCOM/VKUI#874]
В модуле PromoBanner, а именно [здесь](https://github.com/VKCOM/VKUI/blob/master/src/components/PromoBanner/PromoBanner.tsx#L64), указано ageRestriction, когда сам ответ запроса рекламы возвращает ageRestriction**s**.

**Comment by ArthurStam** [comment]
@danakt можешь помочь?

**Comment by AdvTechnoKing** [comment]
![XNXISrV3I5w](https://user-images.githubusercontent.com/17812651/87192191-a7262c80-c2fe-11ea-9eb5-533c5db7d8d6.jpg)
