### ISSUE TITLE
[Bug] Скролл в модалке перестает работать

### ISSUE THREAD

**Issue by b-ponomarenko** [VKCOM/VKUI#876]
**Описание**
свайп не срабатывает и после этого вообще не срабатывают свайпы вверх или вниз в течение пары секунд.

**Шаги воспроизведения**
1. Создать модальное окно больше размеров вьюпорта
2. Проскроллить в самый низ
3. Подождать 1-2 секунды
4. Сделать свайп вверх (как-бы сделать elastic scroll)
5. Интерфейс зависает, скролл перестает работать на несколько секунд

**Ожидаемое поведение**
Модалка растягивается, интерфейс не фризится

**Скриншоты**
Видео https://dump.video/5YkEX6

**Comment by ArthurStam** [comment]
Привет. С модалками у нас много проблем уже, скоро будем переделывать. Скорее всего фиксы уже будут в v4, так как там сильные расхождения.

**Comment by b-ponomarenko** [comment]
Очень жду, спасибо.
