### ISSUE TITLE
[Bug] Не работает скролл текста внутри Textarea в Modalpage на мобильном

### ISSUE THREAD

**Issue by kpachbiu88** [VKCOM/VKUI#877]
**Описание**
Не работает скролл текста внутри Textarea в Modalpage на мобильных устройствах и в Mini app

**Шаги воспроизведения**
Вводить текст с переносами строк. Вместо скролла закрывается модалка, либо не работает скролл

**Ожидаемое поведение**
Работает скролл

**Пример с воспроизведением**
https://codesandbox.io/s/vkui-boilerplate-tfc6m
https://yadi.sk/i/ZSwyI29fMyyHiw

**Comment by ArthurStam** [comment]
Привет. С модалками у нас много проблем уже, скоро будем переделывать. Скорее всего фиксы уже будут в v4, так как там сильные расхождения.

**Comment by thoughtspile** [comment]
Duplicate of #335
