### ISSUE TITLE
[Bug] Method indicator у SimpleCell

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#879]
Если в метод indicator передать 0, например indicator={0}, то цвет текста справа становится чёрным, а не серым, как должен быть, решается если обернуть indicator={String(0)}, как я понимаю он думаю что 0 - false, но если передать false, тогда текст справа вообще не отображается, как и задумано.

**Comment by ArthurStam** [comment]
Поправим, спасибо.
