### ISSUE TITLE
[Bug] Виснет интерфейс при двойном нажатии системной кнопки назад

### ISSUE THREAD

**Issue by b-ponomarenko** [VKCOM/VKUI#880]
**Описание**
В случае быстрого нажатия системной кнопки назад 2 раза, интерфейс фризится

**Шаги воспроизведения**
1. Открыть приложение
2. Уйти на 2 страницы вперед
3. Подряд нажать кнопку назад
4. Интерфейс зависает, причем на странице "текущая - 1"

**Ожидаемое поведение**
Интерфейс стабильно себя ведет

**Скриншоты**
Видео 

**Пример с воспроизведением**
https://codesandbox.io/s/vkui-boilerplate-ucfpx

**Comment by ilyapishchulin** [comment]
#177

**Comment by kpachbiu88** [comment]
Можно решить так:
`
        window.addEventListener('popstate', _.throttle((e) => {
            dispatch(changePage()) 
        }, 850))
`

**Comment by ArthurStam** [comment]
Посмотрим, спасибо.

**Comment by ArthurStam** [comment]
Закрою, так как дублирует #177
