### ISSUE TITLE
[Bug] Некорректный цвет фона Tabs с HorizontalScroll в Card

### ISSUE THREAD

**Issue by MrZillaGold** [VKCOM/VKUI#883]
**Описание**
Если использовать Tabs с HorizontalScroll в Сard и начать скроллить компонент в бок, то цвет фона не применяется на весь компонент, а только на его часть.

**Скриншоты**
![image](https://user-images.githubusercontent.com/42776347/87351511-e40f4f00-c59c-11ea-9df6-cb16f0565b7a.png)

**Пример с воспроизведением**
https://codesandbox.io/s/vkui-boilerplate-cb3u4?file=/src/index.js

Довольно странный вариант использования, в своем приложение фон вообще заменяю на прозрачный, что думаете по поводу фикса в библиотеке?

**Comment by ArthurStam** [comment]
Привет. Не совсем понятно, зачем Tabs класть внутрь Card.

**Comment by ArthurStam** [comment]
Хотя Card тут не при чем. Структура табов со скроллом вот такой должна быть:

Tabs
--HorizontalScroll
----TabsItem

https://vkcom.github.io/vkui-styleguide/#!/Tabs вот тут пример

**Comment by ArthurStam** [comment]
Если хочется валидного отображение в карточке, то придется добавить стиль

```css
.Card .Tabs {
  border-radius: inherit;
}
```

В либу эти стили пока тащить не станет, так как в нашем дизайн гайде нет подобных вложенностей.

**Comment by MrZillaGold** [comment]
Спасибо, посмотрю
