### ISSUE TITLE
[Bug] Выравнивание по горизонтали Button 

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#884]
**Описание**
Размер кнопки переопределяет выравнивание по горизонтали.

**Пример с воспроизведением**
```jsx
<Button size="xl" align="left" />
```
![image](https://user-images.githubusercontent.com/11076888/87403892-7c71f780-c5ce-11ea-9cb2-ea9c657af9d7.png)

**Comment by Lihachyov** [comment]
Спасибо за тикет! Дело в том, что для кнопок размером XL это является рекомендуемым поведением по дизайну. 

Очень большие кнопки обычно располагаются внизу экрана во всю ширину с отступами по бокам, обозначая главное действие на экране. Такие кнопки не рекомендуется вставлять прямо в контент, для этого есть размеры поменьше, которые лучше соответствуют размерам контента. 

Поэтому предлагаю оставить как есть. Мы такие рекомендации ещё опишем в гайдлайнах, а пока только так :)

**Comment by eolme** [comment]
Просто хочется большую кнопку с иконкой справа и выравниванием текста по левому краю

**Comment by Lihachyov** [comment]
В кнопке такое выравнивание текста будет выглядеть не очень хорошо: сами по себе кнопки и так визуально тяжёлые из-за цвета, и пустое расстояние между текстом и иконкой этот вес будут только увеличивать. 

У нас поддержано наличие иконки слева от текста при их общей центровке. Это общепринятый стиль кнопок, который проще читается, так как пустое место распределено слева и справа у кнопки, фокусируя внимание на иконке и тексте действия.

**Comment by eolme** [comment]
Хорошо, подумаю, что с этим можно сделать.
