### ISSUE TITLE
[Feature] Стандартный отступ у Button со stretched

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#885]
Когда 2+ кнопки стоят рядом со stretched не добавляется стандартный отступ между ними. Предлагаю его сделать.

**Comment by fedorov-xyz** [comment]
Привет. Приложите, скриншот, пожалуйста.

**Comment by eolme** [comment]
У вас в примере он через style установлен:
![image](https://user-images.githubusercontent.com/11076888/87407956-e771fd00-c5d3-11ea-879d-262f1a1f1f9c.png)

Если же просто разместить рядом:
![image](https://user-images.githubusercontent.com/11076888/87407895-d32e0000-c5d3-11ea-8b9d-a1a6db44a04c.png)

**Comment by ArthurStam** [comment]
Обсудим с дизайнерами, спасибо.

**Comment by ArthurStam** [comment]
Обсудил, сделаем. Отступ между кнопками — 12px. Будет возможность позиционировать их как горизонтально, так и вертикально.

**Comment by pfrankov** [comment]
Есть компонент ButtonGroup, в котором есть отступы.
