### ISSUE TITLE
[Bug] Невозможно скроллить Textarea в Modal

### ISSUE THREAD

**Issue by b-ponomarenko** [VKCOM/VKUI#886]
**Описание**
При добавлении компонента Textarea в модалку, например в ModalCard скролл перестает работать

**Шаги воспроизведения**
Добавить ModalCard с Textarea

**Ожидаемое поведение**
Textarea скроллится

**Скриншоты**
Видео https://dump.video/bos1Zs

**Comment by ArthurStam** [comment]
Дубликат #877
