### ISSUE TITLE
[Feature] Button стиль - комбинация tertiary и destructive

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#888]
Пример:
![image](https://user-images.githubusercontent.com/11076888/87570140-3190d680-c6d9-11ea-86d5-8e0bddc54aad.png)

**Comment by ArthurStam** [comment]
Обсудим с дизайнерами, спасибо.

**Comment by eolme** [comment]
Я имею ввиду добавить такие, как в компоненте Alert

**Comment by ArthurStam** [comment]
Я понял. Пока у нас mode может принимать только одно из вышеперечисленных значений. Мы в процессе разнесения mode на несколько свойств.

**Comment by ArthurStam** [comment]
Поговорил с дизайнерами. В пока неопределенном будущем у нас будет новая версия дизайна библиотеки, в которой в том числе будет возможна такая комбинация стилей кнопок.

**Comment by pfrankov** [comment]
Уже доступно в v4
