### ISSUE TITLE
[Feature] Сделать SimpleCell действительно простым

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#889]
Сейчас `SimpleCell `всегда отрисовывает `Tappable`.
Eсли не ошибаюсь, он задумывался, чтобы оптимизировать большие списки путем уменьшения сложности DOM и логики, но `Tappable` сам по себе достаточно комплексный.

**Comment by ArthurStam** [comment]
Внесем эту оптимизацию в v4, спасибо.

**Comment by ArthurStam** [comment]
Поправлено в v4
