### ISSUE TITLE
[Bug] Невозможно получить ref элемента, обернутого в Tooltip

### ISSUE THREAD

**Issue by b-ponomarenko** [VKCOM/VKUI#892]
**Описание**
В случае, если мы имеем структуру, типа
```jsx
<Tooltip>
  <SomeComponent ref={componentRef} />
</Tooltip>
```
то мы не можем получить ref элемента (ref не отрабатывает)

**Ожидаемое поведение**
ref отрабатывает

**Пример с воспроизведением**
https://codesandbox.io/s/vkui-boilerplate-k8cfi?file=/src/index.js

**Comment by ArthurStam** [comment]
Спасибо, известно. Поправим.
