### ISSUE TITLE
[Feature] Сделать Gallery полностью контроллируемым

### ISSUE THREAD

**Issue by b-ponomarenko** [VKCOM/VKUI#894]
В текущей реализации компонента Gallery сохраняется возможность менять слайды свайпами. В некоторых кейсах хочется, чтобы изменять слайды можно было только сверху, передавая slideIndex и, если пользователь начинает свайпать, отключить анимацию переходов.
Пример: https://codesandbox.io/s/vkui-boilerplate-tf8he?file=/src/index.js

**Comment by ArthurStam** [comment]
Поправлено в `4.0.0-beta.36`
