### ISSUE TITLE
[Feature] Добавить обычный индикатор к TabbarItem

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#896]
Сейчас в нативном приложении есть обычный индикатор того, что нужно зайти на вкладку. Предлагаю сделать аналогичный и в VKUI.

Что-то типо:
<img width="378" alt="Снимок экрана 2020-07-19 в 17 32 41" src="https://user-images.githubusercontent.com/45998835/87877292-1d551e00-c9e6-11ea-9caf-ef1e648138b4.png">

**Comment by gbowsky** [comment]
Сделано в #1306
<img width="358" alt="image" src="https://user-images.githubusercontent.com/36237725/106916905-c52f0080-6718-11eb-9ee4-cf2c90cf578c.png">
