### ISSUE TITLE
[Feature] В v4 сломан Cell для Switch и так далее

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#907]
Ранее Cell при прокидывании свойства asideContent не имел анимации выделения всего блока, а теперь имеет.

<img width="380" alt="Снимок экрана 2020-07-23 в 02 02 17" src="https://user-images.githubusercontent.com/45998835/88237762-9b385400-cc88-11ea-8704-582300da07f4.png">

**Comment by ArthurStam** [comment]
`Cell` теперь использует `SimpleCell` под капотом. Анимация нажатия у него по-умолчанию включена. Для отключения нужно передавать `<Cell disabled />`. Опишу это в breaking changes.

**Comment by ArthurStam** [comment]
Указал вот тут https://github.com/VKCOM/VKUI/releases/tag/v4.0.0-beta.1

**Comment by ilyapishchulin** [comment]
Топчег
