### ISSUE TITLE
[Bug] Некорректная анимация нажатия на MiniInfoCell

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#909]
**Описание**
При нажатии на MiniInfoCell он очень странно выделяется. (4.0.0-beta.3)

<img width="387" alt="Снимок экрана 2020-07-23 в 12 51 35" src="https://user-images.githubusercontent.com/45998835/88273739-4d046e80-cce3-11ea-87b4-01db6b540c63.png">

**Ожидаемое поведение**
На iOS при нажатии надпись на половину скрывается. (opacity: 0.6 примерно)

**Comment by ArthurStam** [comment]
Это в v4 так?

**Comment by ilyapishchulin** [comment]
Да

**Comment by ArthurStam** [comment]
Давай на будущее договоримся, что ты в тикете сразу пишешь номер хотя бы мажорной версии.

**Comment by ilyapishchulin** [comment]
Странно почему не указал, видимо когда переписывал -- убрал

**Comment by fedorov-xyz** [comment]
Стиль анимации нажатия исправим чуть позже.

**Comment by SevereCloud** [comment]
Стиль анимации изменен с v5
