### ISSUE TITLE
[Feature] Объединить modal и popout

### ISSUE THREAD

**Issue by eolme** [VKCOM/VKUI#922]
Может в V4 объединить `modal` и `popout`? Потому что, условно, `ModalRoot` переданный в `popout` (с оговоркой/костылем) работает нормально.

**Comment by NekR** [comment]
Там будет ещё всё переделываться. Но предложение интересное, спасибо.

**Comment by ArthurStam** [comment]
После объединения непонятно как показывать одновременно модалку и ActionSheet/Alert/Snackbar и любой другой popout

**Comment by eolme** [comment]
Реализовать, например, через стек, модалки ведь накладываются друг на друга

**Comment by ArthurStam** [comment]
Модалки накладываются, но двух активных модалок быть не может. И сейчас логика простая — одна модалка всегда сменяет другую. Popout всегда показывается поверх. А объединение сильно усложнит внутреннюю логику. Плюсы такого решения мне непонятны.

**Comment by eolme** [comment]
Да я вообще про упрощение наоборот: из `ModalRoot` логику свайпов разнести для `ModalPage` и `ModalCard` в отдельные компоненты, в `PopoutWrapper` перенести оставшийся функционал и добавить поддержку наложения.

Хотя про наложение достаточно спорный вопрос, вроде это считается плохим тоном - один оверлей поверх другого.

@Lihachyov, вообще по гайдлайнам/дизайну такое разрешено?

**Comment by Lihachyov** [comment]
@eolme спасибо за вопрос! С точки зрения продукта тут действительно нужно два типа:
- модальные страницы, заменяющие друг друга и находящиеся в одном стеке навигации.
- временные накладывающиеся поповеры, при появлении которых фоновая модальная страница не должна закрываться. Поповеры также могут отображаться поверх обычных страниц и иногда за пределами модалок. 

Представь кейс: десктоп с большим экраном, поверх небольшое модальное окно по центру для написания новой записи. При выполнении действий могут появляться снэкбары и контекстные меню, но они точно не должны закрывать основную модалку, потому что пользователь не выходит за пределы контекста создания записи. Кроме того, снэкбар вообще было бы хорошо отображать за пределами модалки (как чёрные уведомления слева-снизу экрана на сайте), то есть таким образом они должны стать ещё менее зависимыми.
