### ISSUE TITLE
[Bug] Несоответствие дизайну/не красится иконка в ActionSheetItem

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#927]
**Описание**
Если применить mode="destructive" на ActionSheetItem, то на Android иконка в before не красится в красный цвет, хотя на iOS с этим всё ок, приходится колхозить: https://pastebin.com/9vcmfqCf

По дизайну из фигмы иконка должна краситься.

Версия: 3.12.0, обновился с 3.11.6, там тоже самое было.

**Comment by ArthurStam** [comment]
Это уже пофикшено в v4.
