### ISSUE TITLE
[Feature] Изменение statusbar при открытии popout

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#928]
Сейчас во многих приложениях смена темы реализована просто через подписку на настройки, из за того что у всех тема ставится 1 раз, то при открытии popout, статусбар остаётся цвета приложения, а не затемненного как должен быть и как сделано во всём ВК.

Как решил это я: https://pastebin.com/844fkU0y
Как было: https://imgur.com/a/D4yrqqg

В общем, не забудьте об этом, если будете переносить смену темы внутрь vkui)

**Comment by ArthurStam** [comment]
Мы не забудем, спасибо.
