### ISSUE TITLE
[Bug] Рабочая область PullToRefresh

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#933]
Проблема в том что сейчас рабочая область ptr зависит от контента который в нём находим, это не очень удобно допустим если у тебя 1 Cell в списке, а ты хочешь просто свайпнуть по экрану чтобы произошло обновление, у тебя ничего не получится.

Больше подробностей, на фото ниже пометил голубым где ptr работает, а красным где не работает, хотелось бы чтобы он растягивался на всю высоту Panel и работал даже в красной области.
Фото: https://imgur.com/a/2s7GR02

**Comment by fedorov-xyz** [comment]
Спасибо за issue! Исправим это поведение.

**Comment by thoughtspile** [comment]
Исправлено в [v4.0.0-beta.34](https://vkcom.github.io/VKUI/4.0.0-beta.34/#!/PullToRefresh)
