### ISSUE TITLE
[Bug] prop size = xl у Button растягивает кнопку на всю ширину родителя

### ISSUE THREAD

**Issue by tayurus** [VKCOM/VKUI#935]
**Описание**
Собственно, кажется нелогичным, что данный проп влияет на "резиновость" кнопки. Для этого ведь есть проп stretched?

**Шаги воспроизведения**
Пишем в коде
 `<Button size={"xl"}>Текст кнопки</Button>`

**Ожидаемое поведение**
Кнопка становится больше по ширине и высоте, чем кнопка с size='l', но не растягивается на всю ширину родителя

**Пример с воспроизведением**
https://codesandbox.io/s/vkui-boilerplate-3wmqr?file=/src/index.js

**Comment by SkyGopnik** [comment]
Скорее всего так и должно быть т.к. VKUI пока не очень дружит с ПК (вроде в v4 начали над этим работу), а рассчитан на мобайл, для него такое поведение правильное - https://imgur.com/a/jtqTaH6.

**Comment by ArthurStam** [comment]
Привет. Согласен, действительно нелогичное поведение. Переделаем его в v4.

**Comment by tayurus** [comment]
Наверное, не стоило закрывать.
