### ISSUE TITLE
[Bug, iOS] Некорректное поведение при использовании Input и Select в ModalPage

### ISSUE THREAD

**Issue by ToTheHit** [VKCOM/VKUI#938]
**Описание**
При нажатии на Input или Select, размещенных в ModalPage, происходят скачки анимации и скролл основного контента. 
Если страница проскроллена до низа, то багов анимации нет.
При Select'е блок с ModalPage не перемещается наверх.

**Ожидаемое поведение**
* Анимация работает плавно
* Контент "за модалкой" автоматически не скроллится
* При Select'е модалка перемещается наверх

**Видео**
https://www.youtube.com/watch?v=uaIttS1bmYY

**Пример с воспроизведением**
https://codesandbox.io/s/vkui-boilerplate-ph1qt

**Comment by inomdzhon** [comment]
На момент тестировании в [v6.7.4](https://github.com/VKCOM/VKUI/releases/tag/v6.7.4), не воспроизводится
