### ISSUE TITLE
[Feature] Добавление WriteBar

### ISSUE THREAD

**Issue by ItzNeviKat** [VKCOM/VKUI#940]
Пожалуйста, добавьте WriteBar - она используется, например, для написания комментария. В библиотеке VKUI для Figma этот элемент есть, а тут нет.
![image](https://user-images.githubusercontent.com/24193020/89416355-d0877c00-d735-11ea-8fa7-2a04a315b50e.png)

**Comment by ArthurStam** [comment]
Привет. Добавим, спасибо

**Comment by ArthurStam** [comment]
Если хотите, можете и сами сделать контрибьют)

**Comment by AdvTechnoKing** [comment]
> Если хотите, можете и сами сделать контрибьют)

А это только ему разрешили или участие может принять кто угодно?)

**Comment by ArthurStam** [comment]
Кто угодно может контрибьютить в библиотеку)

**Comment by gbowsky** [comment]
https://github.com/VKCOM/VKUI/pull/1099

**Comment by gbowsky** [comment]
https://github.com/VKCOM/VKUI/pull/1112

Можно закрывать.

**Comment by fedorov-xyz** [comment]
Доступен в версии 3.13.0.
