### ISSUE TITLE
[Bug] Неправильная работа ActionSheet (вложенность элементов)

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#947]
Если использовать в ActionSheet вложенность, то айтемы начинают вести очень странно.

Нормальная работа
Код: https://pastebin.com/ygdxwjQJ
Скрин: https://imgur.com/XOq2w0R

Неправильная работа
Код: https://pastebin.com/9p0djvDt
Скрин: https://imgur.com/NNsAAOp

**Comment by ArthurStam** [comment]
Номер мажорной версии какой?

**Comment by SkyGopnik** [comment]
> Номер мажорной версии какой?

"@vkontakte/vkui": "^3.12.0"

**Comment by ArthurStam** [comment]
Понятно. В 3-й версии экш шиты больше не трогаем. Данная проблема пофикшена в 4-й версии, которая пока в бете
