### ISSUE TITLE
[Bug] Нет затемнения Tabbar при PanelHeaderContext

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#949]
Собственно, если открывать PanelHeaderContext в панели, которая находится внутри Epic с включенным Tabbar, то Tabbar при открытии PanelHeaderContext остаётся белым, а не затемнятся как должно быть и сделано в самом вк.

Скрины: https://imgur.com/a/0ASf5al (1 скрин из сервиса, 2 из самого вк).

"@vkontakte/vkui": "^3.12.0"

**Comment by ArthurStam** [comment]
Закрываю, так как есть старый дублирующий тикет #362
