### ISSUE TITLE
[Bug] Некорректно обрезается заголовок в PanelHeader на Android

### ISSUE THREAD

**Issue by ilyapishchulin** [VKCOM/VKUI#951]
**Описание**
В заголовке название не сокращается троеточием.

**Шаги воспроизведения**
1. Создаем шапку с длинным названием и кнопкой назад.
```jsx
<PanelHeader left={<PanelHeaderBack/>}>Длинный заголовок</PanelHeader>
```

**Скриншоты**
![](https://sun9-75.userapi.com/O_FYLoBsiLA7pSKlUCXjNogZqUj0ZN6kaC-DqQ/xVDD9X8pysU.jpg)
![](https://sun9-55.userapi.com/DjSFgE4klybUoDICm0oA3fjnF8pIOYIzRCY9pQ/Xbk7jdMKMJQ.jpg)

**Comment by TouristPlay** [comment]
Поддерживаю автора

**Comment by ilyapishchulin** [comment]
Хотел бы отметить, что webviewType не указан.

Если дело в нем, то нужно убрать сокращение с iOS, чтобы поведение было единым

**Comment by thoughtspile** [comment]
Исправлено в [v4.0.0-beta.34](https://vkcom.github.io/VKUI/4.0.0-beta.34/#!/PanelHeader)
<img width="352" alt="Снимок экрана 2020-12-08 в 17 17 18" src="https://user-images.githubusercontent.com/5262915/101495138-3c465380-3979-11eb-855f-0ed445bd68d5.png">
