### ISSUE TITLE
[Feature] Добавить в PullToRefresh отклик при обновлении

### ISSUE THREAD

**Issue by kachemirova** [VKCOM/VKUI#956]
При срабатывании onRefresh добавить вызов события vk-bridge:
`bridge.send("VKWebAppTapticImpactOccurred", {"style": "light"})`

**Comment by fedorov-xyz** [comment]
Привет! Спасибо, сделаю.

**Comment by fedorov-xyz** [comment]
Доступно в версии https://github.com/VKCOM/VKUI/releases/tag/v3.12.1
