### ISSUE TITLE
[Bug] Проблема с FixedLayout

### ISSUE THREAD

**Issue by a1phaZ** [VKCOM/VKUI#958]
**Описание**
Есть несколько View с панельками, на главной View на панельке находится FixedLayout. При возврате на главную View происходит присвоение FixedLayout стилей position: absolute и top: 752px - (кол-во пикселей зависит от тестируемого размера экрана = высота экрана - PanelHeader)

**Шаги воспроизведения**
Установить View/Panel с FixedLayout выше остальных View/Panel

**Ожидаемое поведение**
FixedLayout не добавляются ненужные стили.

**Скриншоты**
![fixedlayout1](https://user-images.githubusercontent.com/6966909/90608556-3a1a8680-e21c-11ea-8f25-cc0e4356e29d.png)
![fixedlayout2](https://user-images.githubusercontent.com/6966909/90608564-3c7ce080-e21c-11ea-8c81-a49ec3443ab5.png)

**Лечение**
Перемещение View/Panel с FixedLayout ниже остальных View/Panel

З.ы. это баг или фича? Всю голову сломал, пока нашел решение %)

**Comment by ArthurStam** [comment]
Это фича. В переходах мы используем трансформации, которые не дружат с position: fixed. Поэтому на момент перехода мы меняем позиционирование с fixed на absolute

**Comment by a1phaZ** [comment]
> Это фича. В переходах мы используем трансформации, которые не дружат с position: fixed. Поэтому на момент перехода мы меняем позиционирование с fixed на absolute

Понял, спасибо. Может это как-то в доки внести?
Можно закрывать тикет

**Comment by ArthurStam** [comment]
Это внутренние механизмы компонента, а дока описывает публичное АПИ. Поэтому нет, смысла описывать это в доке не вижу.
