### ISSUE TITLE
[Bug] Клавиатура в мобильном клиенте на Android перекрывает ModalPage

### ISSUE THREAD

**Issue by a1phaZ** [VKCOM/VKUI#961]
**Описание**
Имеется ModalPage с Input'ом, при фокусе на input'е в Android версии мобильного клиента вызывается клавиатура и перекрывает половину ModalPage.

**Шаги воспроизведения**
Стандартная модалка с полем ввода. Прикрученая к Root или View компоненту. Поведение одинаковое

**Ожидаемое поведение**
Клавиатура не перекрывает модалку.

**Скриншоты**
![habit_modal1](https://user-images.githubusercontent.com/6966909/90715805-c08aa300-e2c4-11ea-852c-a914be6d5419.png)
![habit_modal2](https://user-images.githubusercontent.com/6966909/90715809-c2546680-e2c4-11ea-8bf5-d43d88ac795f.png)

Код модалки:
```js
const modal = (
  <ModalRoot
    activeModal={state.activeModal}
    onClose={modalBack}
  >
    <ModalPage
        id={'add-habit'}
	onClose={modalBack}
	dynamicContentHeight
	header={
	  <ModalPageHeader
	    left={osName !== IOS && <PanelHeaderButton onClick={modalBack}><Icon24Cancel/></PanelHeaderButton>}
	    right={osName === IOS &&
	      <PanelHeaderButton onClick={modalBack}>{osName === IOS ? 'Готово' : <Icon24Dismiss/>}</PanelHeaderButton>}
          >
             Создать цель
         </ModalPageHeader>
	}
	>
	<FormLayout
	  onSubmit={(e) => {
	    e.preventDefault();
	    doApiFetch({
	      method: 'POST',
	      title: title,
	      days: days
            });
	   dispatch({type: SET_MODAL, payload: {modal: null}});
	   setDays(21);
	   setTitle('');
	}}
      >
      <Input
	required
	type={'text'}
	value={title}
	onChange={(e) => {
	  setTitle(e.currentTarget.value)
	}}
	top={'Название цели'}
      />
      <Slider min={1} max={21} step={1} value={days} top={`Кол-во дней: ${days}`} onChange={(d) => {
        setDays(d)
      }}/>
      <CellButton
	before={<Icon24Add/>}
      >
	Создать цель
      </CellButton>
    </FormLayout>
  </ModalPage>
</ModalRoot>
)
```

Вызов
```js
<PopoutWrapper alignY="center" alignX="center">
  <Root activeView={state.view} popout={state.popout} modal={modal}>
    ...
  </Root>
</PopoutWrapper>
```

**Comment by inomdzhon** [comment]
@a1phaZ подскажи, пожалуйста, какая у тебя версия VKUI?

Мы выпустили [v7.0.0](https://github.com/VKCOM/VKUI/releases/tag/v7.0.0) с фиксом модалок (#6759), если есть возможность, то стоит проверить с этой версией. Или с [v6.7.4](https://github.com/VKCOM/VKUI/releases/tag/6.7.4), или с [v5.10.2](https://github.com/VKCOM/VKUI/releases/tag/v5.10.2)

**Comment by a1phaZ** [comment]
Проверить к сожалению не могу, проект давно похоронен и нет планов по реинкорнации. Прошло уже 4 года и подозреваю, что проблема давно устранена и ишью можно закрывать.

**Comment by inomdzhon** [comment]
> Проверить к сожалению не могу, проект давно похоронен и нет планов по реинкорнации. Прошло уже 4 года и подозреваю, что проблема давно устранена и ишью можно закрывать.

Спасибо за ответ и issue 🙏
