### ISSUE TITLE
[Bug] Не совместимы Slider с ModalPage 

### ISSUE THREAD

**Issue by AdvTechnoKing** [VKCOM/VKUI#971]
**Описание**
Если поместить Slider внутрь ModalPage, то из за стиля на ModalPage__in, а именно `margin: 0 auto;`, зона работы слайдера будет за приделами ModalPage

**Шаги воспроизведения**
Помещаем Slider в ModalPage

**Ожидаемое поведение**
Зона Slider в пределах ModalPage

**Видео**
[ModalPage & Slider](https://vk.com/video_ext.php?oid=102343170&id=456239425&hash=4939b8b97a333a64&hd=2)

**Comment by ArthurStam** [comment]
Привет. В `4.0.0-beta.30` это поправлено. В 3-й версии исправления уже не будет.
