### ISSUE TITLE
Иконки в SelectMimicry слева/справа [Feature]

### ISSUE THREAD

**Issue by Melzmr** [VKCOM/VKUI#975]
В текущей реализации `VKUI 4` невозможно добавить иконки слева/справа через props в `<SelectMimicry />`.
Если добавлять иконку как ребенка у `<SelectMimicry />`, например:
```
<SelectMimicry>
	<VKUI4Icon />
</SelectMimicry>
```
То на иконку накидываются классы, которые относятся к dropdown иконке, тем самым всем иконкам присваивается класс `.Select .Icon`.

Как сейчас:
![image](https://user-images.githubusercontent.com/38521674/91047912-82261880-e623-11ea-9561-52308d58c791.png)

Как хотелось бы:
![image](https://user-images.githubusercontent.com/38521674/91047935-8baf8080-e623-11ea-9440-4abd1cde81f4.png)

P.S. Тоже самое, наверное, относится к компоненту `<Select />`

**Comment by eugpoloz** [comment]
Закрываем в пользу #2374, которая покрывает этот кейс.
