### ISSUE TITLE
Вылетает ошибка при попытке собрать кастомный popout

### ISSUE THREAD

**Issue by damirian** [VKCOM/VKUI#98]
При попытке собрать собственный popout, согласно документации, вида 
```
<PopoutWrapper v="center" h="center">
    Some content
</PopoutWrapper>
```
... вылетает ошибка

[Пример в codesandbox](https://codesandbox.io/s/jjmk3zq7l3)

**Comment by ArthurStam** [comment]
Довольно долго бился над поиском проблемы. Оказывается, я просто не экспортирую этот компонент наружу(
