### ISSUE TITLE
[Bug] Не работает autoclose ActionSheet (вложенность элементов)

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#980]
Из за этого бага https://github.com/VKCOM/VKUI/issues/947 не работает autoclose у ActionSheetItem, а изменение попапа на null закрывает его без анимации.

**Comment by SkyGopnik** [comment]
Если фикс в v4 то закройте

**Comment by ArthurStam** [comment]
В v4 это работает
