### ISSUE TITLE
[Tappable] При ховере на вложенные Tappable подсвечивать только самый глубокий

### ISSUE THREAD

**Issue by fedorov-xyz** [VKCOM/VKUI#993]
В этом примере мышка наведена на иконку и подсвечен должна быть только она.

![image](https://user-images.githubusercontent.com/25563268/92004528-fd39ae00-ed4a-11ea-922b-73855a06c3a0.png)

**Comment by NekR** [comment]
Тоже самое нужно с кликом/активацией -- анимировать только самый глубокий блок. Сейчас активируются все.

**Comment by thoughtspile** [comment]
Исправлено в v4.0.0
<img width="317" alt="Снимок экрана 2020-12-24 в 12 55 05" src="https://user-images.githubusercontent.com/5262915/103080649-5160ea80-45e7-11eb-96e3-7a204fa36045.png">
<img width="316" alt="Снимок экрана 2020-12-24 в 12 55 10" src="https://user-images.githubusercontent.com/5262915/103080651-52921780-45e7-11eb-8015-7b8154b1bbed.png">

PR https://github.com/VKCOM/VKUI/pull/1206
