### ISSUE TITLE
[Bug] Некорректная работа ползунка Slider (при свайпе IOS)

### ISSUE THREAD

**Issue by ArtemKha** [VKCOM/VKUI#997]
**Описание**
При наличии обработчика onSwipeBack во View на странице со слайдером происходит переход назад.

**Шаги воспроизведения**

1. Найдите ползунок на странице с возможностью свайпа;
2. Свайпните вправо на уровне ползунка.

**Ожидаемое поведение**
Передвигается только ползунок, страница не переключается.

**Скриншоты**
![ezgif-6-df975610f272](https://user-images.githubusercontent.com/23254507/92102865-d8dfdf00-ede7-11ea-94b9-c3d73072ba8c.gif)

**Comment by thoughtspile** [comment]
related: #997 #562
